### ISSUE TITLE
Fork-network command doesn’t accept suffix starting with dash

### ISSUE THREAD

**Issue by vlad-kopcil** [near/nearcore#10034]
**Describe the bug**
While the default chain id starts with dash, given the help screen
--chain-id-suffix <CHAIN_ID_SUFFIX> 
[default: -fork] 

We can’t do the same from command line

**To Reproduce**
```
neard.polina --unsafe-fast-startup fork-network --validators /opt/validators.json --epoch-length 1000 --chain-id-suffix -really
error: a value is required for '--chain-id-suffix <CHAIN_ID_SUFFIX>' but none was supplied
```

```
neard.polina --unsafe-fast-startup fork-network --validators /opt/validators.json --epoch-length 1000 --chain-id-suffix -fork
error: unexpected argument '-f' found
```

```
/opt/neard.polina --unsafe-fast-startup fork-network --validators /opt/validators.json --epoch-length 1000 --chain-id-suffix \-fork
error: unexpected argument '-f' found
```

When tried with `--chain-id-suffix=-fork`, the parameter was ignored completely.

**Expected behavior**
We should be able to use any suffix we like, including dash as the first character.
There's multiple way how to handle values with dash as the first character. Usually the quoting is the best call.
As we already support the long arguments, the assignment operator is also viable option here.
The work around might be to add dash always by the code, and only expect the test after as the parameter.

**Version (please complete the following information):**
- It's originaly in Polina's branch at https://github.com/near/nearcore/pull/9642, but I suppose that Nikolay's version inherited the same

**Comment by posvyatokum** [comment]
Fixed in #10101
