### ISSUE TITLE
🔷 [ProjectTracking] RPC API improvements

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#10047]
# Goals

## Background

WOrk on this task focuses on sunsetting the support of 2 experimental RPC methods: EXPERIMENTAL_check_tx and EXPERIMENTAL_broadcast_tx_sync. Both of these methods exist in the codebase, but were never included in our documentation due to their experimental nature.

The sunsetting will be active starting from nearcore version 1.37.

## Why should NEAR One work on this

Reducing the complexity of the RPC API, eliminating unused code.

## What needs to be accomplished

- EXPERIMENTAL_check_tx can be replaced with tx method;
- EXPERIMENTAL_broadcast_tx_sync can be replaced with broadcast_tx_commit or the new send_tx method
- We plan to add an additional check to broadcast_tx_commit method. Right now, we check that the transaction and all the corresponding receipts were executed. Starting from 1.37, we will also check that all the blocks which include the transaction/receipts are the part of the canonical chain. This additional verification allows us to offer improved, stricter guarantees. However, the response time might increase by a small amount of time.

## Main use case

Starting from 1.37, we will introduce a new method, send_tx, which allows you to guarantee the minimal level of execution, e.g., if you need to be sure that the transaction is included into the canonical chain, and you don't want to wait for the receipts, you can use send_tx with the INCLUDED_FINAL option.

# Links to external documentations and discussions

https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=pagodaplatform.near&blockHeight=108340383

# Estimated effort

As of 2024-01-23, there is no remaining effort for this project.

# Assumptions

There are no specific assumptions that this project is making.

# Pre-requisites

N/A

# Out of scope

N/A

# Task list:

```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/10048
- [ ] https://github.com/near/nearcore/issues/10078
```

**Comment by gmilescu** [comment]
2023-11-27
* We prepared an announcement for the API changes, and we are waiting for it to be published. Later we want to broadcast that announcement to all partner and dev channels.
* PR with RPC API changes is merged into master, and ready to be shipped with 1.37.
* documentation will be updated after 1.37 is rolled out.

**Comment by telezhnaya** [comment]
- We still wait for the announcement to be published, Mally will do this tomorrow. I'll proceed with the broadcasting to the other channels this week as well
- We need to prepare PRs for all the repos which depend on previous API version. E.g., https://github.com/near/near-jsonrpc-client-rs
- https://github.com/near/nearcore/issues/10078 is deprioritised

**Comment by telezhnaya** [comment]
Upd:
- The post is here https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=pagodaplatform.near&blockHeight=108340383
- JSONRPC client is updated: https://github.com/near/near-jsonrpc-client-rs/pull/136, as well as the docs https://github.com/near/docs/pull/1660 https://github.com/near/docs/pull/1564
- So, IMO, the most important part is done
- Next plan is to run through other projects, check if we need to update any other stuff (maybe just ping the maintainers and clarify they control this process), create a doc based on this

**Comment by gmilescu** [comment]
Since development for this feature is done and we are now only waiting for 1.37 to be released, we can close the tracking issue.
