### ISSUE TITLE
Nayduck status on PRs is non-actionable

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#10079]
Currently, literally each PR gets a red cross on nayduck "nightly" tests, that do not test the PR code itself. This is non-actionable, and gives negative feedback.

Instead, we should either change this check to only display on CI (bad, as we wouldn’t notice failing tests as easily), or change this check to actually run on each PR (good, the solution that was picked in the Zug offsite).

Considering it takes 1 hour, I’d suggest not running it on top of each PR, but running it on the merge queue only. This would significantly reduce our compute time usage. It would also avoid issues whereby unreviewed code could run on our nayduck infrastructure, as the merge queue only ever sees reviewed code.

Considering changing nayduck to run on each merge group might be hard, I think it would make sense to turn it into a github action workflow instead. This would enable easy merge queue integration, in addition to allowing us to trash out a significant amount of code as dead code. It could be facilitated by using [a self-hosted github actions runner](https://docs.github.com/en/actions/hosting-your-own-runners), as I think most nayduck tests require multiple machines to run.

In the meantime, I’d advocate for the status check to be temporarily removed from the PRs, as it’s just (currently) red noise hard to understand for anyone not specifically aware of what exactly is currently going on.

WDYT?

**Comment by nagisa** [comment]
> Considering changing nayduck to run on each merge group might be hard, I think it would make sense to turn it into a github action workflow instead

Not arguing against it, getting rid of self-maintained infrastructure is always nice, but I don’t believe having a workflow along the lines of

```
- run: curl https://webhook-to-start-a-run
- run: while true; do sleep 60 && curl https://check-for-completion; done
```

would be particularly onerous (which we can definitely implement seeing as we do maintain the nayduck infrastructure :))

**Comment by andrei-near** [comment]
As the name suggest, this check verifies the status of last nightly Nayduck run and isn't supposed to run Nayduck tests on PRs.
This is to raise awareness that there are failed tests which require attention. For now it is non-blocking (this will change)

**Comment by Ekleog-NEAR** [comment]
> For now it is non-blocking (this will change)

My point is, this cannot change until it tests the PR itself and not the last nightly nayduck run. Because otherwise, any PR to fix the last nightly nayduck run would be unable to land due to not passing this test.

And the current situation, while understandable for us, is probably very confusing for external contributors. As someone who regularly contributes to open-source projects I don’t know the internals of, every time I see a CI check failing, even if it seems unrelated to my change, I’m always left wondering whether I unknowingly broke something with my change, and unsure whether anyone ever will come reviewing my PR considering it doesn’t have a green CI checkmark.

Hence my suggestion to, for now, only have this check on master (which we should be monitoring anyway, though I guess we currently are probably not); and to add it back to PRs only when we actually can have it test the PR code itself and block landing PRs.

**Comment by Ekleog-NEAR** [comment]
Closing as we removed the nayduck status from PRs for now.
