### ISSUE TITLE
fork-network amend-access-keys crashes

### ISSUE THREAD

**Issue by vlad-kopcil** [near/nearcore#10156]
**Describe the bug**
The command `near fork-network amend-access-keys` crashes immendiately with exception
We run `near fork-network init` beforehand without issues. Please see the detailed logs in attachements.
I run it several times to prevent "unlucky snapshot", but maybe I'm still unlucky?

**To Reproduce**

Configure your git to allow password-less https (you'll need this for TF modules)
1. create PAT on UI
2. amend config by
```
git config --global --add url."https://${ GITHUB_CLONE_PAT }:x-oauth-basic@github".insteadOf https://github
```

Steps to reproduce the behavior.
```
git clone https://github.com/PagodaPlatform/tf-forknet.git
cd prepare
cat <<EOF >prepare.tfvars
chain_id            = "mainnet"
data_image_project  = "rpc-prod"
module_prefix       = "$USER-forknet-prepare-mainnet"
system_image_family = "near-node-custom"
EOF
terraform init --upgrade
terraform apply -var-file=prepare.tfvars --auto-approve 2>&1 > tf-$(date +%Y%m%d%H%M%S).log
```

**Expected behavior**
The command should finish in 10 hours without failure.

**Screenshots**

**Version (please complete the following information):**
+ su - ubuntu -c '~/neard --version'
neard (release trunk) (build 1.1.0-4528-gcadf11d58) (rustc 1.73.0) (protocol 64) (db 38)

[neard-amend-access-keys-20231111213335.log](https://github.com/near/nearcore/files/13331443/neard-amend-access-keys-20231111213335.log)
[neard-amend-access-keys-20231112182453.log](https://github.com/near/nearcore/files/13331444/neard-amend-access-keys-20231112182453.log)
[tf-20231111213335.log](https://github.com/near/nearcore/files/13331445/tf-20231111213335.log)
[tf-20231112182453.log](https://github.com/near/nearcore/files/13331446/tf-20231112182453.log)

**Comment by nikurt** [comment]
Fixed by #10160
