### ISSUE TITLE
transaction pool iteration timeout

### ISSUE THREAD

**Issue by wacban** [near/nearcore#10278]
The transaction pool of a chunk producer is propagated with transactions ready to be included in the next chunk. Some of them however may become invalid by the time the chunk producer is ready to produce the chunk - e.g. by already being included in the chain in a recent chunk.

Currently the chunk producer iterates over the transaction pool when assembling the chunk and filters the invalid transactions at the same time. This process may actually slow down the chunk production if the transaction pool is full of invalid transactions. This could in turn lead to missed chunks and penalties for the chunk producer.

The goal of this issue is to set a timeout when iterating the transaction pool when preparing a chunk. 

By setting the timeout we hope to avoid missing a chunk due to the transaction pool being filled with large quantities of invalid transactions. The drawback is that not all valid transactions may be included. Given this tradeoff it seems better to produce a smaller chunk than to miss the chunk all together.

**Comment by wacban** [comment]
related issue #10277

**Comment by jancionear** [comment]
A simple prototype could look like this: https://github.com/jancionear/nearcore/commit/28919644b7162da5f324ddfd2bc294405697bc06

However this looks eerily similar to `"compute limits"` that I saw elsewhere: https://github.com/near/nearcore/issues/8859

I wonder if this is the same thing - trying to limit the maximum time (called compute there) it takes to produce a chunk

**Comment by wacban** [comment]
The code snippet looks good to me. I would just make it configurable. We also need to take care to set a good default and some analysis may be needed for that.

**Comment by jancionear** [comment]
> I would just make it configurable. We also need to take care to set a good default and some analysis may be needed for that.

Yeah choosing a good time limit is difficult.

In the current code, the gas limit for preparing transactions is half of the chunk's gas limit:
https://github.com/near/nearcore/blob/81b7082507fcf393e2f3b185339d83b56eebc9b1/nearcore/src/runtime/mod.rs#L722

So the logic looks like this:
```rust
let transactions_gas_limit = gas_limit / 2;
let mut total_gas_burnt = 0;

while total_gas_burnt < transactions_gas_limit {
    total_gas_burnt += add_transaction_to_chunk();
}
```
I'm not sure why it's half of the total. Maybe the other half is reserved for applying incoming receipts (?)
A single transaction could take up to 300ms, so maybe it's a safety buffer to make sure that the total preparation time stays under `gas_limit/2 + 300ms` (?).

We could choose a time limit by converting `transactions_gas_limit` to time, but I'm not sure how to convert gas to seconds. I heard that `gas_limit` is adjusted to make sure that applying a chunk doesn't take too long, so I thought that I could look at this logic to figure out what's the current relation between gas and time. Sadly I couldn't find the piece of code that does it. Is the `gas_limit` really adjusted, or is it only a planned feature?

There's also a metric called `near_produce_chunk_time`. We could look at the metrics to see how long a typical node takes to produce a chunk and choose a good value based on that. I'll try to make a grafana dashboard for it, but I need to get editor access to grafana first. Working on it.

**Comment by jancionear** [comment]
> 1TG ~ 1ms of compute time

I read somewhere that this is the case now, but in the future with faster hardware/different way to calculate usage, etc the ratio could change. When it changes, the gas limit per block would be adjusted to make sure that running a block still takes under 1 second. Because of that I can't just convert 1 TGas to 1ms, in the future the gas limit might be increased to 1200 TGas and my time limit would become 1200ms instead of 1000ms.

That's why I was looking for the gas limit adjustment logic - there would be something like "I executed 1200TGas of operations in 1 second, this means that 1Tgas = 0.83ms right now"

> We can consider it from the other end - what is the maximum time that we can spend on preparing transactions that would still leave us enough time to produce the chunk?
>
> Anyway as long as it's configurable we can start with some high default until we find out what is the good default that would actually help with bloated tx pool but without impacting the chunk production.

:+1:,  I will look at the metric, it should give a pretty good estimate how long a chunk production might take.

**Comment by akashin** [comment]
Sorry, missed the initial mention!

> I believe the compute limit referes to compute costs and is specific to the chunk processing in the runtime. I guess there is similarity but the implementation will need to be separate as those are not related or similar. @akashin can you confirm please?

That's correct, Compute Costs are only relevant during receipt processing and are not computed at the stage where we include transactions in the chunk (you can read about Compute Costs in more detail in https://github.com/near/NEPs/blob/master/neps/nep-0455.md).

> Should I call time_limit_for_processing_transactions compute_limit? Does compute equal cpu time?
Would this make https://github.com/near/nearcore/issues/8859 redundant?

No, as per above, these are not related.

@jancionear in the snippet https://github.com/near/nearcore/issues/10278#issuecomment-1836526687 please note that the iterator is draining, so you will need to return the transaction back to the pool after the break statement.
I think the draining behavior is a bit hard to work with https://github.com/near/nearcore/issues/9060 and I've been working on the migration to non-mutation iteration https://github.com/near/nearcore/pull/9337 but didn't get it to the finish line yet. If you think this work is useful for the feature that you're implementing now, let me know and I will finish it up (or feel free to take over this refactoring).

> So that'd mean that half of each block's gas_limit is spent on converting new transactions to receipts, and the other half of it is spent on executing receipts.

Yes, the motivation here is to provide a sort of liveness even under congestion. But if there are no new transaction, the leftover gas up till `gas_limit` **will** be used to process delayed receipts.

There have been some proposals to make this split more dynamic, see https://github.com/near/nearcore/issues/1700#issuecomment-1700682506

But again, this doesn't seem to be relevant for the timeout-based approach that you are taking.

**Comment by jancionear** [comment]
> So that'd mean that half of each block's gas_limit is spent on converting new transactions to receipts, and the other half of it is spent on executing receipts.

I wonder if this limit isn't too high. AFAIU when there's a lot of transactions and receipts we could get a scenario like this:
* Chunk producer spends 500 Tgas/ms converting transactions to receipts
* Chunk producer sends the chunk to validators
* Validators also convert the transactions to receipts to validate the correctness. This also takes 500 Tgas/ms
* Validators run the receipts using the other half of the `gas_limit`, which also uses up 500 Tgas/ms
* Producing a validated chunk takes 1.5s instead of 1s

Does it work this way? If it does, maybe we should reduce the `transaction_gas_limit` to 1/3 instead of 1/2 of total gas? (same with the time limit)

**Comment by akashin** [comment]
> * Producing a validated chunk takes 1.5s instead of 1s
> Does it work this way?

Not quite. Because NEAR protocol only stores pre-state root as a part of the block, it can overlap distribution of the new chunk and processing transactions. See https://near.github.io/nearcore/architecture/how/tx_receipts.html#advanced-but-reality-is-more-complex and https://docs.google.com/document/d/1k0NRMcLsDZp6C9pCRjNu5l7irDyRHsZ3VtKAKno_tFY/edit#heading=h.v15oyovy4rfl for a detailed explanation.
This is quite different from other blockchains (e.g. Ethereum) and is a very common source of confusion.

Also, even if we did process the blocks in 1.5s, as long as that time stays constant (below something like 4s), the network will still operate nicely at full capacity.

By the way, if you want to test any of these congestion behaviors, I suggest trying out https://github.com/near/nearcore/tree/master/pytest/tests/loadtest/locust which is a load generation framework that @jakmeier and I developed this year. This way you can easily see the impact of different congestion-handling strategies on the network in the end-to-end setup.

**Comment by jancionear** [comment]
@akashin, I saw the diagram, but I still have doubts about it.

![image](https://github.com/near/nearcore/assets/149345204/d3afdabf-68c7-4544-b993-968e0bcbee09)
My issue is that the "Pick txn" step is done only on the chunk producer. Doesn't the validator have to do this step as well? I think it should run the transactions again and convert them to receipts?

AFAIU the causal chain looks like this:
1) Produce chunk (process transactions)
2) send chunk to validator
3) Verify chunk (process transactions)
4) Process receipts
5) Send out endorsement for chunk
6) Now we have all the information to produce the next chunk
7) Go to step 1)

Each of those steps depends on the previous ones, so we can't do them in parallel. If 1), 3) and 4) each takes up 500ms, that would mean that producing a chunk takes 1500ms, no?

If there was only a single chunk producer, it would be possible to pipeline it:
![image](https://github.com/near/nearcore/assets/149345204/5583871f-c027-49bf-92e0-6c1801919251)


But AFAIU each chunk is produced by a different chunk producer, I don't see how pipelining could work there:
![image](https://github.com/near/nearcore/assets/149345204/75fc446c-11e4-44d8-98a3-4333e70c89c6)

With two interleaved chunk producers, wouldn't it take 1.5s to produce a chunk?

**Comment by jancionear** [comment]
> There's also a metric called near_produce_chunk_time. We could look at the metrics to see how long a typical node takes to produce a chunk and choose a good value based on that. I'll try to make a grafana dashboard for it, but I need to get editor access to grafana first. Working on it.

I made a grafana dashboard that tracks chunk production time on mainnet:
https://nearinc.grafana.net/d/cd668436-f19a-4f3d-b4a5-a35ebd3701b0/chunk-production-stats?from=now-12h&to=now&refresh=1h&orgId=1

The P99 time to produce a chunk is ~60ms. I think 200ms would be a reasonable default value for the time limit. This would give us 200ms to process transactions on the chunk producer, 50ms to publish the chunk, 200ms to process the transactions on the validator and 500ms to process the receipts. And it's over three times the maximum observed value, so it won't break anything.

It's also interesting to take a look at chunk production time during the minting of NEAT. It caused a heavy load on the chain, with P99 chunk production time reaching 850ms (!). This time limit should prevent such behaviors:
https://nearinc.grafana.net/d/cd668436-f19a-4f3d-b4a5-a35ebd3701b0/chunk-production-stats?from=1701298800000&to=1701342000000&orgId=1

**Comment by jancionear** [comment]
One more thought: is there some kind of penalty for producing an empty chunk?

In the previous configuration a proper chunk producer would never produce an empty chunk when there are pending transactions. I could imagine a rule saying that chunk producers who make empty chunks should be banned.
With the time limit it might turn out that a chunk producer creates a chunk with 0 transactions, we should make sure that they won't get punished for that.

**Comment by wacban** [comment]
> Out of curiosity, why would we need to maintain the old structure?

There are two dimensions to this question:
* Can a chunk producer not include any new transactions from the pool? - I believe the answer to be yes. 
* Can a chunk producer not include any incoming receipts? - No, the receipt inclusion algorithm is predefined, deterministic and verified by validators. The chunk producer must follow it for the chunk to be valid.
