### ISSUE TITLE
Insufficient resources: could not allocate code memory

### ISSUE THREAD

**Issue by aleksuss** [near/nearcore#10374]
I started getting the [error](https://github.com/aurora-is-near/aurora-engine/actions/runs/7364544173/job/20045028697#step:8:1347): `LoadingError("Insufficient resources: could not allocate code memory: Cannot allocate memory (os error 12)")` while running tests on my CI after switching to the `near-vm-runner = "0.19"`. But at the same time, I don't get such an error locally on my M2 laptop. Firstly, I thought that it could be related to different architectures, but then I decreased the number of threads for running tests on the CI (which uses 64 core runner by default) and the error didn't occur. I started some code investigation and found that there is only one [mempool](https://github.com/near/nearcore/blob/master/runtime/near-vm-runner/src/near_vm_runner.rs#L245) is used for all parallel running tests. After changing the `count` value from 8 to [num cpus](https://github.com/aleksuss/nearcore/commit/68326087963ae661295048d2bf7e7c9137ce607e#diff-7cc5d2369515d3e62ade4ee055515423d6c141c261cc9689cbbebd1a6efcb876R246) in my fork and use it instead of dependencies from crates.io fixed the issue and the started passing. 

**To Reproduce**
Use heavy smart contract in `near-vm-runner` (in my case, it's about 1.2 mb) in tests running parallel on a host with >= 32 CPUs. 

**Expected behaviour**
CPU number on the host shouldn't affect the result of running tests. 

**Screenshots**

**Version (please complete the following information):**
- near-vm-runner 0.19.0 
- rust version: nightly-2023-12-15

**Comment by nagisa** [comment]
As the comment in the relevant code suggests, 8 is the best guess we made at the time. This works for `neard` as it can only have as many contracts running in parallel as there are shards being tracked by a node.

`near-vm-runner` is not written with any other use-cases in mind and I'm not sure what it would take before that happens.

It wouldn’t be too hard to make the pool arguments configurable here. Add some fields to [the `Config` struct](https://github.com/near/nearcore/blob/ba024a2ecba10bdaa0552cd7c50e29c276c4b51d/core/parameters/src/vm.rs#L145) & use those parameters to construct the pool. For neard the default values of these parameters should stay the same, but in your tests you would be able to specify whatever value you wish at the time you construct the runtime.

**Comment by aleksuss** [comment]
> near-vm-runner is not written with any other use-cases in mind and I'm not sure what it would take before we consistently consider other users.

But version 0.17.0 works fine. Unfortunately, this version doesn't support contracts compiled with recent Rust versions.

**Comment by nagisa** [comment]
That's unsurprising. The pool of memories has been added reasonably recently and having it be fixed size is actually desirable for neard as there have been concerns about statically establishing an memory requirement ceiling for the runtime.

The fact that a prior version worked for an external use-case doesn’t change the essence of my statement either. `near-vm-runner` is developed and maintained for its primary use as a runtime within the reference NEAR validator. Suitability for any other use-case is incidental.

That said, there's no reason it cannot be used elsewhere, but an implicit expectation is that the interested parties would contribute to the effort (of making it suitable for those other use-cases and helping to keep it in that shape by e.g. contributing to reviews.)
