### ISSUE TITLE
[BUG] By default, the first time you deploy a node localnet on gitpod, then execute with tools/restaked, and then an error occurred

### ISSUE THREAD

**Issue by zwong91** [near/nearcore#10386]
$./target/debug/neard --home ~/.near init --chain-id localnet
$ ./target/debug/neard --home ~/.near run

gitpod /workspace/nearcore/tools/restaked (master) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0, wasmer-singlepass-backend-near v0.18.1, wasmparser v0.78.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `/workspace/nearcore/target/debug/restaked`
2024-01-05T13:36:54.906251Z  INFO config: Validating Config, extracted from config.json...
thread 'main' panicked at tools/restaked/src/main.rs:91:48:
called `Result::unwrap()` on an `Err` value: "RpcError { error_struct: Some(InternalError(Object({\"info\": Object({\"error_message\": String(\"Connect(Resolver(Custom { kind: Uncategorized, error: \\\"failed to lookup address information: Name or service not known\\\" }))\")}), \"name\": String(\"INTERNAL_ERROR\")}))), code: -32000, message: \"Server error\", data: None }"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

![image](https://github.com/near/nearcore/assets/36259838/80221e59-ad36-4282-b0d1-43411eac5d51)
![image](https://github.com/near/nearcore/assets/36259838/335c509e-dd4d-4b6e-a87d-becf02eae7af)

**Comment by telezhnaya** [comment]
Hey!
Sorry for the long response.
Please update to the latest version and feel free to re-open if it's still an issue for you
