### ISSUE TITLE
unmerge near-vm-runner from near-vm-logic

### ISSUE THREAD

**Issue by frol** [near/nearcore#10421]
#9255 merged near-vm-logic into near-vm-runner. The existence of near-vm-logic was justified in the README and even highlighted by @nagisa: https://github.com/near/nearcore/pull/9255#discussion_r1243805599

> > It is not dependent on the specific way the smart contract code is executed, e.g. through Wasmer or whatnot, and
> > therefore can be used for unit tests in smart contracts.

> @nagisa: Curious this idea never actually materialized to any significant degree.

This is nearcore-developer thinking that there is no world outside of nearcore. It is frustrating. crates.io "Dependents" tab could have helped you: https://crates.io/crates/near-vm-logic/reverse_dependencies

**Describe the bug**

[near-sdk-rs 5.0.0 is blocked](https://github.com/near/near-sdk-rs/pull/1130/files#diff-c3fb7631cde4c892fbaeff8da210a49530a6c0b60333f46dc22e302f1ec7024fL42) by the lack of new near-vm-logic. Using near-vm-runner is pretty ugly and makes developer experience much slower as to build unit-tests for near-sdk-rs one suddenly needs to compile several Wasm runtimes (I don't even mention that it is [not compilable on Windows at the moment](https://github.com/near/near-sdk-rs/actions/runs/7508585322/job/20444285922?pr=1130)).

I have also noticed that the latest version of near-vm-logic before being merged into near-vm-runner depends on near-o11y (same problem as #8888), so this should be also addressed.

**Comment by nagisa** [comment]
FWIW all of the runtimes are optional features in `near-vm-runner`, if its depended upon with `default-features = false` it should end up pretty lean overall.

**Comment by frol** [comment]
I will close this issue for now since #10423 solved the immediate pain point. We will come to it later with even more near-sdk-rs refactoring.
