### ISSUE TITLE
Tune parameters at syncing

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1047]
Parameters to tune:

*   Block headers to fetch at one time
*   Num blocks to fetch per one time from one peer
*   Block fetch horizon
*   State fetch horizon

**Comment by Kouprin** [comment]
@SkidanovAlex @ilblackdragon please assign back when it becomes actual

**Comment by nikurt** [comment]
Header Sync runs at about 500 headers per 10 seconds - good enough.
Block Sync saturates block processing - can't improve by tuning sync parameters.
Block fetch horizon seems to work fine too.
