### ISSUE TITLE
Compress state at StateSync

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1048]
Use ZIP or similar to compress the state when sending.
 Also optimize the sending to send state in parts / collect them on the other side.

**Comment by Kouprin** [comment]
delayed by #1805

**Comment by Kouprin** [comment]
Assign to me again when become actual.

**Comment by nikurt** [comment]
Gave it a try: https://pagodaplatform.atlassian.net/wiki/spaces/EAP/pages/140214353/Improved+State+Sync#Is-state-compressible%3F
Not impressed with the results.
Best case is 2X compression at the cost of burning **a lot** of CPU.

```
mainnet:

zip compression rate is less than 2x:

shard0: 6.4G → 3.9G
shard1: 4.5G → 2.9G
shard2: 5.8G → 3.1G
shard3: 15G → 8.2G

xz -9 compression rate is about 2x:
shard0: 6.4G → 3.4G
shard1: 4.5G → 2.6G
shard2: 5.8G → 2.4G
shard3: 15G → 7.0G

mainnet shard3, about 2x:
xz -9: 15G → 7.0G
xz -5: 15G → 7.3G
xz -1: 15G → 7.7G
```
