### ISSUE TITLE
[stateless_validation][tracking issue] Security concerns Round-1

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#10565]
As new messages for StateWitness and ChunkEndorsement are introduced, we need to ensure that protocol is safe under malicious behaviour of nodes.

Currently state witness is signed by the chunk producer which makes it possible to validate the source early in validation process. We still need to address the issues described below.

### Deserialising potentially large state witness struct

Currently stateless validator receives `ChunkStateWitnessMessage` via network and puts it in memory before performing any further validations. We need to ensure a size limit for this message, something like `32MB`.

**Update**: we actually limit incoming network message to 500MB: [source](https://github.com/saketh-are/nearcore/blob/5a35c020ddc41b53d9175efd183bd2570732346c/chain/network/src/peer/stream.rs#L14-L16). 

### Making validator waste resources validating irrelevant chunks

Currently it is possible to make chunk validator perform irrelevant/redundant work in the following scenarios:
* send the same valid state witness multiple times: #11111
* send state witness for the old chunk (can happen under normal circumstances with network delays): #11081
* https://github.com/near/nearcore/issues/11193

We need to introduce protection agains that.

**Comment by walnut-the-cat** [comment]
@pugachAG , will add you as an owner of this issue for now. Please update as you work towards it

**Comment by walnut-the-cat** [comment]
Appending 'Round-1' to the title to indicate this is first round of security concerns. Please note that there may be more incoming as we make progress and following concerns will be tracked in a different issue.

**Comment by pugachAG** [comment]
the only remaining item here is #11193
