### ISSUE TITLE
Use metering lifting, aka superblock metering

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1057]
There is a patch (implemented by https://github.com/cdetrio) to the standard metering injection used by Parity that reduced the slowdown caused by metering from 500x to 1.05-2.4x. See: https://youtu.be/XxMTGi4gDfE?t=648

We should use it since according to our benchmarks metering is accounted for >95% of execution time.

**Comment by nearmax** [comment]
Here is their implementation: https://github.com/ewasm/sentinel-rs/tree/superblock-metering

**Comment by ilblackdragon** [comment]
This seems critical @nearmax ?

**Comment by bowenwang1996** [comment]
@nearmax what is the status of this issue? cc @olonho @matklad

**Comment by matklad** [comment]
I think this is superseded by #4410. We should look at the superblock metering approach, but from a glance, #4410 should be both faster and more reliable -- seems like superblock metering is a "happy case optimization", so it'll still cause slowdowns worst-case.
