### ISSUE TITLE
Make size limit of orphan witnesses configurable

### ISSUE THREAD

**Issue by jancionear** [near/nearcore#10650]
The size of orphaned chunk state witnesses admitted to the `OrphanStateWitnessPool` is limited by the constant `MAX_ORPHAN_WITNESS_SIZE`. Value of `MAX_ORPHAN_WITNESS_SIZE` was chosen based on the observed values, but this estimation might not be perfect. If the limit turns out to be too small, it could lead to discarding valid orphaned witnesses. This isn't a big problem, but it could increase the number of missing chunks.
It would be nice to allow node operators to control this limit from `config.json`, just like it's possible to control the pool size by using the `orphan_state_witness_pool_size` config parameter.

Refs: https://github.com/near/nearcore/pull/10613#discussion_r1499260996

**Comment by tayfunelmas** [comment]
Addressed in PR #10847.

In config.json the orphan witness data size can be specified as follows:
```
"orphan_state_witness_max_size": 40000000
```
