### ISSUE TITLE
Make ChunkStateWitness a Tier1 network message

### ISSUE THREAD

**Issue by jancionear** [near/nearcore#10668]
In stateless validation chunk producer sends out a `ChunkStateWItness` message to every chunk validator responsible for validating the corresponding chunk. Currently it's a `Tier2` `RoutedMessage`, but I think it would be better to make it a `Tier1` message.

AFAIU `Tier1` is meant to exchange information between validators in a quick and stable manner. There's a direct `Tier1` connection between every pair of validators, so the connections are much more reliable and efficient than routed `Tier2` connections.
`ChunkStateWitness` messages are sent only between chunk validators and chunk producers, and additionally they're big and time-sensitive. I think they'd be a good fit for `Tier1`.

Having direct connections could also allow us to ban peers which send invalid `ChunkStateWItness` messages, which was disabled in https://github.com/near/nearcore/pull/10667

cc @saketh-are

**Comment by walnut-the-cat** [comment]
how much useful this can be at this moment, considering the low participation rate of tier 1?

**Comment by jancionear** [comment]
> how much useful this can be at this moment, considering the low participation rate of tier 1?

Is the participation rate of tier 1 network low? I though that every active validator participates in the tier1 network o-0

**Comment by walnut-the-cat** [comment]
That's the hope, but I don't think it's happening right now.
cc. @saketh-are

**Comment by jancionear** [comment]
It appears that this has been implemented in https://github.com/near/nearcore/pull/11021
