### ISSUE TITLE
congestion-model: strategy with one outgoing buffer for each other shard

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#10706]
Discussed in the congestion-control meeting today:

We want to try a congestion control strategy where each shard has an outgoing buffer for each of the other shards.
The idea is that this can distribute backpressure more fairly.

**Comment by jakmeier** [comment]
cc @wacban I think you wanted to work on this.

**Comment by jakmeier** [comment]
@wacban I think this is resolved with #10830, right?

**Comment by wacban** [comment]
Yes, let me close it.
