### ISSUE TITLE
Avoid eager loading of wasm binaries when executing a function call

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#10801]
In `execute_function_call`, we always first load the wasm binary https://github.com/near/nearcore/blob/a1cac9149e7bf392bc7c2636fcb669b6b86aaab6/runtime/runtime/src/actions.rs#L82. However, this step is only needed if the contract has not been compiled. We should refactor to avoid unnecessarily loading of wasm binaries.

**Comment by nagisa** [comment]
This can be pretty difficult to achieve however. The `ContractCode` that we're loading here besides the wasm code itself also contains a `CryptoHash` which is the key into the compiled contract cache.

The obvious thing to do would be to split them up into independent columns perhaps? Or independent key-values within this column? RocksDB does return memory slices that we don't need to copy necessarily, but I believe that the data still needs to be read from the disk and decompressed in full before this slice gets passed to the caller.

**Comment by bowenwang1996** [comment]
@nagisa contract hash is stored as part of `Account`, which is readily available in [execute_function_call](https://github.com/near/nearcore/blob/607118f6f52521ed895d75594d3642bfc09ffc59/runtime/runtime/src/actions.rs#L70)
