### ISSUE TITLE
Issue with Near archive data (Blocks : 114744298 and 114744299)

### ISSUE THREAD

**Issue by qn-srikanth** [near/nearcore#10828]
**Describe the bug**

Both [114744298](https://nearblocks.io/blocks/2mTXasRZT9QiKq9z6yn8gxy5tYnRGhxSVNcco8XGQqBW) and [114744299](https://nearblocks.io/blocks/Ggb1bFz3W8hbZNEorwDH6c59WsbNj51QyvP4KWKfg1Eg) have some common `chunk_hash`

**To Reproduce**

- Two chunks are common for these two blocks :
```
7LXbrj1mDUhC8cmP38V6V6qdVmxTmPpMSVC7GX5x2fpF  
FDYKcKnYnsypVTEHQPegxu4Nf35M1rqVzDKQXTavzZrD
```

- For example, transaction [J6wqoiAeampwZvyKsean3ZgtoFcGAf9AS83UJ5b5pTMF](https://nearblocks.io/txns/J6wqoiAeampwZvyKsean3ZgtoFcGAf9AS83UJ5b5pTMF)  is found in chunk 7LXbrj1mDUhC8cmP38V6V6qdVmxTmPpMSVC7GX5x2fpF,
so, as per the API now the tx belongs to 2 blocks.

**Expected behavior**
Transaction should belong to only 1 block.

**Screenshots**

![Screenshot 2024-03-19 at 2 51 54 PM](https://github.com/near/nearcore/assets/107944932/0fe01058-0052-49cf-a4a2-a1e548e543d1)

**Version (please complete the following information):**
Near archive public RPC : https://archival-rpc.mainnet.near.org/

**Comment by telezhnaya** [comment]
Hey @qn-srikanth,
If the chunk for shard X was not produced for block N, block N will copy the chunk from previous block. This is expected behaviour.
The transaction details will point to the first chunk where transaction appeared.
