### ISSUE TITLE
Disabled test: test_storage_proof_size_soft_limit

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#10864]
As part of https://github.com/near/nearcore/pull/10852, we disabled test_storage_proof_size_soft_limit

This is likely because we no longer fetch the contract wasm from trie upon each execution, and so the test stops hitting the storage proof limit.

In order to fix this, we need to define how statelessnet is expected to deal with contract compilation. Are validators expected to know all the contracts for all shards and keep a compiled cache, or should chunk producers supply validators with contract each time? (in which case validators would need quite a bit more processing power than today, because compiling a contract is probably the slowest operation in our system and we currently avoid most of it)

Depending on the answer, either we should adjust the test to use more storage / lower the limit, or we should re-introduce the early loading of wasm code just for stateless chunk producers.

Discussion also happened on https://near.zulipchat.com/#narrow/stream/295302-general/topic/test_storage_proof_size_soft_limit

cc @shreyan-gupta

**Comment by Longarithm** [comment]
Works again since #11185
