### ISSUE TITLE
[Tracking issue] In-mem trie loadtest on forknet

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11020]
* Investigation note: [link](https://docs.google.com/document/d/1DaGd_yv01a0I9oTLRVuF13T1MqF26al3QhtffPR84WQ/edit?usp=sharing)

## TODOs
* Make sure Forknet works with MainNet state, without In-Mem trie & Single shard tracking (no traffic)
  * Address all the issues along the way
* Enable In-mem trie and single shard tracking (no traffic)
  * Address all the issues along the way
* Add synthetic traffic
  * Address all the issues along the way
* Add mainnet traffic mirroring
  * Address all the issues along the way

As we discover an issue, please create a sub issue / PR and add it here so we can track.

**Comment by tayfunelmas** [comment]
Since we have been testing memtrie with stateless validation on forknet for a couple weeks, closing this one.
