### ISSUE TITLE
[stateless_validation] Limit witness size growth on missing chunks

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#11039]
Due to `source_receipt_proofs` field, state witness size can uncontrollably grow if there are lots of missing chunks in a row.
Consider mitigation of its size + whether it is required for MVP.

In more details: when new chunk at height H1 appears and **previous** chunk was at height H2, all receipts originated from other shards in chunks at heights `[H2, H1)` must be processed (is could be better to say "included" or "preprocessed"...). Yeah many of them will end up delayed but currently state witness must hold them all.

Basic idea - limit number of such receipts by some constant, include receipts up to certain pointer, so that next chunk producer will pick up last pointer and include bunch of receipts on top of that.

Concern: if we want to state sync and receipts queue is not exhausted, we need to download additional chunks in order to find the old receipts that have not been processed yet. Or change set of receipts stored in chunk, but it may change chunk distribution significantly.

**Comment by Longarithm** [comment]
Our idea:
* if some shard misses a lot of chunks in a row (10, TBD), treat it as congested
i* f outgoing receipt targets congested shard, instead of distributing it - save it to “Delayed Outgoing Receipts” (DOR) queue at source shard. So we end up having two queues - Delayed Incoming and Delayed Outgoing receipts
* For target shards which are not congested anymore, we pull receipts from DOR queue (1000, TBD) and distribute them

Alternatives
* Distribute outgoing receipts separately so they can be accumulated by chunk validator and not occupy state witness space. Concern: chunk validators are always rotating so we may have overhead of distributing these receipts to everyone
* Solve it on the level of aggregating outgoing receipts, taking only part of `DBCol::OutgoingReceipts`. However, roughly, it introduces an issue that whoever has to pull receipts from this col after congestion, has to iterate over couple blocks in the past, which complicates protocol. Also may make state sync more complicated. Putting receipts direcly to state looks more sensible. 

Open questions 
* How do we currently plan to expose shards congestion info to runtime, and does the DOR queue align well with Congestion Control plans?
* How to support resharding?

**Comment by wacban** [comment]
> cc. @wacban

I'm supportive of the idea of leveraging congestion control for that purpuse. It is very well aligned with the current congestion control design, it's simple and should work out of the box.

**Comment by jancionear** [comment]
I just added some new metrics, including the size of `source_receipt_proofs`:

![image](https://github.com/near/nearcore/assets/149345204/eb2e2f1c-e4ee-4f77-ab98-663ad71fd358)

[link to dashboard](https://nearone.grafana.net/d/edbl9ztm5h1q8b/stateless-validation?orgId=1&from=1714482112000&to=1714483922000&var-chain_id=mainnet&var-shard_id=All&var-node_id=jan-mainnet-node&viewPanel=29)

On mainnet traffic (with shadow validation) the majority of `source_receipt_proofs` are under 50kB. This means that we can miss 200 chunks, and it'll increase the size of `ChunKStateWitness` by just ~1MB (200 * 50kB).

The situation is a bit better than I thought, but 1MB of size growth per 3min is still catastrophic if the chain stalls for more than an hour.

**Comment by wacban** [comment]
@jancionear Do you have any estimate on the worst case scenario?

**Comment by jancionear** [comment]
> @jancionear Do you have any estimate on the worst case scenario?

A single `Action` can be 4MB large (4MB contract, FunctionCall with 4MB args). I guess in the worst case scenario `source_receipt_proofs` could be full of receipts with those 4MB actions (?).
But I didn't investigate it, I'm not sure what's possible within the gas limits.

**Comment by walnut-the-cat** [comment]
what blocks us from closing this issue?

**Comment by walnut-the-cat** [comment]
let's create another issue to track the remaining with freshly.

**Comment by wacban** [comment]
Please disregard the mention above, it's a duplicate. 

Let's track the remaining work in #11295
