### ISSUE TITLE
Introduce `sweat.claim` as a Locust workloads

### ISSUE THREAD

**Issue by akashin** [near/nearcore#11107]
At the moment we only have the loadtest setup for the main `sweat` contract: https://github.com/near/nearcore/blob/71b22e776a161a071a38ed760047cfc2af4ca83c/pytest/tests/loadtest/locust/common/sweat.py

Recently we've been doing optimizations for `sweat.claim` specifically, so it makes sense to introduce a Locust workload for this.

**Comment by mooori** [comment]
For reference, [this is the method](https://github.com/sweatco/sweat-claim/blob/b2f071c7a75c85a051a70a26f5a53b6115526464/contract/src/claim/api.rs#L54) we optimized the prefetcher for in #11094.
