### ISSUE TITLE
Do not panic upon receiving invalid state witness

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11109]
Relevant discussion: [link](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Forknet.20.2B.20Stateless.20Validation/near/433831329)

As of now, when a chunk validator receives an invalid state witness (e.g. missing contract code), it will panic and crash. We should change the behavior so it simply logs the issue but move on without panicking.

**Comment by jancionear** [comment]
> This was commit from Alex PR: https://github.com/near/nearcore/commit/b62b6a3cf1e38c947ea523dc855d58444bf24109.

Thanks for the link, now I see it :+1:

> Maybe this unwrap was removed recently in master.

I took a look at it's the same code as on `master`.
Mysterious 0_O

**Comment by staffik** [comment]
Oh, we used tracing. It was: https://github.com/near/nearcore/pull/10843/files#diff-e073548a40d97af14f75cf143fab41a1cffe61d159e0b9a6297daeab0b2a5d45R317

**Comment by tayfunelmas** [comment]
I see this line (called through validate_chunk_state_witness --> apply_new_chunk --> apply_chunk may also get to MissingTrieValue: https://github.com/near/nearcore/blob/a1a01b45c53c1619c5c9ddfc0d5c9f1cf7a39d43/chain/chain/src/runtime/mod.rs#L917

**Comment by jancionear** [comment]
> Oh, we used tracing. It was: https://github.com/near/nearcore/pull/10843/files#diff-e073548a40d97af14f75cf143fab41a1cffe61d159e0b9a6297daeab0b2a5d45R317

Ahh ok, so the panic was caused by custom code that was added for debug purposes. The code on `master` doesn't have `expect("!!!CRASH!!!"));`, so there's nothing to fix there.

**Comment by jancionear** [comment]
> I see this line (called through validate_chunk_state_witness --> apply_new_chunk --> apply_chunk may also get to MissingTrieValue:
> 
> https://github.com/near/nearcore/blob/a1a01b45c53c1619c5c9ddfc0d5c9f1cf7a39d43/chain/chain/src/runtime/mod.rs#L917

```rust
Err(e) => match e {
    Error::StorageError(err) => match &err {
        StorageError::FlatStorageBlockNotSupported(_)
        | StorageError::MissingTrieValue(..) => Err(err.into()),
        _ => panic!("{err}"),
    },
    _ => Err(e),
},
```

This won't panic on `MissingTrieValue`, it'll return an error.
It could panic if it hits another `StorageError`  that isn't accounted for, but I don't know if that's even possible 0_o

It seems that most of `StorageError` variants are fatal errors (corrupted database etc):
```rust
/// Errors which may occur during working with trie storages, storing
/// trie values (trie nodes and state values) by their hashes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StorageError {
    /// Key-value db internal failure
    StorageInternalError,
    /// Requested trie value by its hash which is missing in storage.
    MissingTrieValue(MissingTrieValueContext, CryptoHash),
    /// Found trie node which shouldn't be part of state. Raised during
    /// validation of state sync parts where incorrect node was passed.
    /// TODO (#8997): consider including hash of trie node.
    UnexpectedTrieValue,
    /// Either invalid state or key-value db is corrupted.
    /// For PartialStorage it cannot be corrupted.
    /// Error message is unreliable and for debugging purposes only. It's also probably ok to
    /// panic in every place that produces this error.
    /// We can check if db is corrupted by verifying everything in the state trie.
    StorageInconsistentState(String),
    /// Flat storage error, meaning that it doesn't support some block anymore.
    /// We guarantee that such block cannot become final, thus block processing
    /// must resume normally.
    FlatStorageBlockNotSupported(String),
    /// In-memory trie could not be loaded for some reason.
    MemTrieLoadingError(String),
}
```

Maybe we shouldn't panic on `UnexpectedTrieValue`, that looks like something that could be triggered by an invalid witness. But OTOH we have tests which check for this error and they don't trigger the panic, so it's probably a different code path. /cc @Longarithm

**Comment by jancionear** [comment]
Idk, it doesn't feel very productive to read the code in hopes of finding of a possible panic. AFAIU the panic that spawned this issue can't happen on `master`, so there's nothing concrete to fix.

I remember that we wanted to fuzz the validation code, maybe that'd be a quicker way to find possible crashes in validation?

**Comment by jancionear** [comment]
Made an issue about fuzzing: https://github.com/near/nearcore/issues/11132

**Comment by walnut-the-cat** [comment]
Issue is not valid anymore. Closing it
