### ISSUE TITLE
Limit size of transactions included in ChunkStateWitness

### ISSUE THREAD

**Issue by jancionear** [near/nearcore#11103]
`ChunkStateWitness` contains transactions which were included in the last two chunks:

```rust
pub struct ChunkStateWitness {
    ...
    pub transactions: Vec<SignedTransaction>,
    ...
    pub new_transactions: Vec<SignedTransaction>,
    pub new_transactions_validation_state: PartialState,
}
```

We must ensure that the size of these fields isn't too big. A malicious chunk producer could potentially try to construct a `ChunkStateWitness` with so many transactions that the size of the witness would explode. Large witnesses are known to cause problems, so we must implement some sort of limit.

Refs: https://github.com/near/nearcore/issues/10259#issuecomment-1971557822

It's a security issue, so I'd say that it's necessary for stateless validation MVP.

**Comment by jancionear** [comment]
From what I read it seems that a single `Action` is always no more than ~4MB in size.
`Action::DeployContract` contains a contract which is limited to 4MB. `Action::FunctionCall` contains function arguments which are limited to 4MB.
Despite that, a single transaction can contain multiple actions (up to 100), so a single transaction could potentially be as large as 400MB!

Because of that I think that we should introduce a hard per-transaction limit, which could be set to 4MB. We can't make the limit much smaller than that because there are already contracts which are larger than 2MB, so the limit would have to be at least 2MB to allow deploying such contracts. 4MB is in line with the previous limitation.

**Comment by jancionear** [comment]
I collected some metrics to see how big all these fields of `ChunkStateWitness` really are.
Things generally look like this (mainnet traffic with shadow validation):

![image](https://github.com/near/nearcore/assets/149345204/ef0330cf-3583-4760-8c6d-c2e95c535979)
[link to the dashboard](https://nearone.grafana.net/d/edbl9ztm5h1q8b/stateless-validation?orgId=1&from=1714482112000&to=1714483922000&var-chain_id=mainnet&var-shard_id=All&var-node_id=jan-mainnet-node)

* `new_transactions_size` is usually under 200kB
* `new_transactions_validation_state_size` is usually under 500kB

This means that:
* We don't need size limits for "normal" mainnet traffic, the limits are mainly needed to protect against attacks
* `5MB` limit for previous and new transactions is more than enough

I'm a bit surprised that the storage proof is this big, afaik validating a transactions requires only reading the account and access key, which are rather small o-0. I guess things add up.

**Comment by jancionear** [comment]
Adding a simple `5MB` limit on transaction size might not be enough on its own. `5MB` of transactions and `7MB` of receipt storage proof would add up to `12MB`, which is quite big.
Maybe 12MB is acceptable, it would be nice if it were as we could go with a simpler solution, but it might not be. I opened https://github.com/near/nearcore/issues/11184 to figure out what's the actual maximum size that the network can handle.

If it turns out that `12MB` is too large, we'll have to think of resolving the the conflict between transactions and receipts somehow. What to do when there's a `4MB` transaction waiting in the pool, as well as `7MB` of receipts to process?
Currently we reserve 300TGas for processing new transactions, and the rest is spent on processing receipts. Plus we stop adding new transactions when the delayed receipt queue gets too big. The problem is that this approach doesn't really translate to size limits. We must accept a `4MB` transaction, but with low limits that  `4MB`  would take up the whole chunk, so it's like spending 1PGas on processing a single transaction :/ So if we gave priority to transactions, having a lot of `4MB` transactions would mean that we stop processing receipts. Giving priority to receipts also doesn't work, as it would starve big transactions.
One way to solve it would be to accept big transaction on every n-th block. For example we could accept transactions larger than 1MB on every 10th block. This "big transaction blocks" would contain the big transaction, but in exchange they would contain less receipts, we could lower the per-chunk soft limit on those blocks.

**Comment by jancionear** [comment]
Idea from @bowenwang1996 

We could lower the size limit for a single transaction. Disallow contracts larger than e.g 1MB.
Ethereum has a 24kB limit for contracts, why is it 4MB on NEAR?

**Comment by Longarithm** [comment]
From my discussion with @jancionear:

[There is check](https://github.com/near/nearcore/blob/a1ae126f3c55fbb2865fdb9c13ad181071491deb/runtime/runtime/src/verifier.rs#L465-L470) of max args length of function call.
You can generate really small tx, but inside a contract it'll generate child receipt with 4MB garbage args.
And you can probably generate plenty of them
And this itself may make source receipt fields for state witness so big that it can't get distributed.
Limiting tx size doesn't help but actually we can include this to "upper bound" and interrupt the contract if it happens.

Another concern - we can get unlucky and receive large txs/receipts from all shard ids simultaneously, so we'd have to multiply worst case by 6, currently.
So I'm afraid we will need to distribute source receipts separately, for each source shard, and reconstruct full source_receipt_proofs on the target node.

**Comment by jancionear** [comment]
Collected some data:

In the current state there are ~170 accounts with contracts larger than 1MB, the largest ones reach 4MB:
[top-200.txt](https://github.com/near/nearcore/files/15249241/top-200.txt)

To support those contracts we'd have to support 4MB `DeployContract` transactions :/

Applying compression helps, only 6 accounts have contracts with compressed size larger than 1MB:
```
Top 200 accounts by compressed contract size:
1.3 MB: myriad.octopus-registry.near
1.3 MB: discovol.octopus-registry.near
1.3 MB: gateway-routerprotocol.near
1.1 MB: mint.exverse.near
1.1 MB: client.bsc-bridge.near
1038.8 KB: nearpay-portals.near
931.1 KB: moodev.near
...
```
[top-200-compressed.txt](https://github.com/near/nearcore/files/15249201/top-200-compressed.txt)

The only problem is that it'd make `zstd` compression part of the consensus protocol,  we'd have to keep this exact version of `zstd` forever :/

I also scanned the last year of blockchain history to find the largest transactions: [top-transactions-1year.txt](https://github.com/near/nearcore/files/15249276/top-transactions-1year.txt)
There were ~600 transactions with size >= 1MB: ~400 DeployContracts, ~100 FunctionCalls and ~100 other transactions.
Out of those, about 400 were >= 1.5MB

**Comment by jancionear** [comment]
zulip discussion about lowering the size limit: https://near.zulipchat.com/#narrow/stream/295306-contract-runtime/topic/Lowering.20the.20limit.20for.20contract.20code.20size
