### ISSUE TITLE
[ForkNet] Figure out why ForkNet has only 5 shards

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11114]
Relevant discussion: [link](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/Debug.20page.20.2F.20Grafana.20questions/near/434226432)

Somehow, we have only 5 shards in ForkNet instead of 6, which is unexpected. We need to investigate and fix.

**Comment by tayfunelmas** [comment]
The layout with 6 shards were disabled for stateless protocol here:
https://github.com/near/nearcore/blob/a1a01b45c53c1619c5c9ddfc0d5c9f1cf7a39d43/core/primitives-core/src/version.rs#L205

Maybe this was for the statelessnet that was run before?

**Comment by walnut-the-cat** [comment]
relevant discussion on Zulip: https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/SimpleNightshadeV3.20.286-shard.20layout.29.20disabled.20in.20stateless/near/434766943
