### ISSUE TITLE
Make sure chunk validators to avoid contract compilation as much as possible

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11125]
With #11124, state witness will always include uncompiled contract code even when compiled version is cached from Chunk Validator side. Since compilation takes a lot of time, we need to make sure chunk validators always use cached compiled contract binary when it's available. 

Relevant discussion: [ref](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/Missing.20contract.20code.20in.20witness/near/434414744)

**Comment by tayfunelmas** [comment]
Part of this is addressed in #11099 by proactively distributing the newly deployed contract code to validators to allow them to pre-compile and persist the contracts in their cache, so closing this issue.
