### ISSUE TITLE
Stateless validation A/A testing

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11134]
Make sure Stateless validation performance is on par with MainNet.

Need to get support from Node team to set up ForkNet-Control and ForkNet-Test ([link](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/A.2FA.20testing.20for.20Stateless.20validation/near/434806098)).

Once it's in place, we should test with both MainNet as well as synthetic traffic to understand where StatelessNet is at compared to MainNet

Following metrics can be considered
* Is txn per second good enough?
* Txn per second
* Transaction success rate?
* Number of receipts processed
  * Metrics can be shaky so we need to be mindful
* Conduct A/A test under controlled loads
* Chunk misses 
* Block misses
* Block production time
* Delayed queue size?
* Things that matter in controlled environment
  * # of txns/receipts per chunk/block
  * Gas spent per block

**Comment by tayfunelmas** [comment]
Currently focusing on performance testing of stateless validation on forknet and now in statelessnet, so we have decided to deprioritize this.
