### ISSUE TITLE
Understand how often chunk producers change shards they are in charge of

### ISSUE THREAD

**Issue by walnut-the-cat** [near/nearcore#11204]
[With the recent alignment](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/disable.20chunk.20producer.20shuffling.20for.20mainnet.20launch/near/436534397), we decided to disable shard shuffling for initial launch of stateless validation.

It means that State sync will be leveraged only when a chunk producer changes the shard it creates chunks for. 

We need to understand frequency of such event by looking at the historical data of the current MainNet, so we set the expectation on state sync.

**Comment by VanBarbascu** [comment]
I've created a spreadsheet of tracked shards per epoch. 
https://docs.google.com/spreadsheets/d/1Y6-4lztfpVz80EnB1XTUV8OYqaZQIq3hUlbX7CivtIA/edit?usp=sharing

**Comment by walnut-the-cat** [comment]
Additional data sheet, containing some analysis data for all validators and top 100 validators: https://docs.google.com/spreadsheets/d/1Eya8t8u2b509pZTLFFHl198DEpLATwUTpVyuQPjAS2k/edit?usp=sharing
