### ISSUE TITLE
[Docs] RPC: Block request should return the block producer's account_id

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1121]
And any other relevant information.

**Comment by frol** [comment]
Resolved in #1962. The documentation is not reflecting the change, yet.

**Comment by amgando** [comment]
I think this can be closed

> _The documentation is not reflecting the change_

Validator endpoint
https://docs.nearprotocol.com/docs/interaction/rpc#validators

Automatically Restaking
https://docs.nearprotocol.com/docs/validator/staking#automatically-re-staking

**Comment by frol** [comment]
This issue is about the new field called `author` (hmm, we had better named it `author_id`) added to the blocks and chunks API call responses.

**Comment by nearmax** [comment]
Adding this piece of documentation is not critical for the Mainnet. Removing from the release and moving to the Ice Box.

**Comment by bowenwang1996** [comment]
> This issue is about the new field called author (hmm, we had better named it author_id) added to the blocks and chunks API call responses.

This is already done
