### ISSUE TITLE
Strategy for enabling memtries during stateful-to-stateless validation protocol upgrade

### ISSUE THREAD

**Issue by tayfunelmas** [near/nearcore#11240]
Identify the right way to enable memtrie during the stateful-to-stateless validation protocol upgrade.
Before the upgrade all nodes will track all shards and they will start tracking only one or some shards after the upgrade. Memtrie is expected to be enabled in the case of tracking single or some shards, as it requires more memory. However, we may also need to think about how to make the transition from (stateful + disk tries) to (stateless + memtries). During this, we may need to run nodes with memtries while tracking all shards. Assuming this is the path to follow, we need to follow-ups.

1) Profile the memory usage needed to do that (a similar task opened for RPC nodes tracking all nodes: 
https://github.com/near/nearcore/issues/11230)

2) Make sure after the protocol upgrade the memtries for the shards that are not tracked in the new epoch are unloaded, leaving the nodes only with memtries for their tracked shards.

Related [thread here](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/putting.20all.20state.20in.20memory/near/437324729).

**Comment by tayfunelmas** [comment]
Since @robin-near is involved in the initial discussions around this, assigning to Robin for now.

**Comment by walnut-the-cat** [comment]
we already have https://github.com/near/near-one-project-tracking/issues/65 so we will want to clean one of them up

**Comment by robin-near** [comment]
Closing this as it's tracked in https://github.com/near/near-one-project-tracking/issues/65
