### ISSUE TITLE
Integrate new tracing services to forknet setup

### ISSUE THREAD

**Issue by tayfunelmas** [near/nearcore#11256]
Currently @robin-near is managing a server to contain tracing services.
Related information here: https://docs.google.com/document/d/1EcpsF4ovGiBOZE4voeul6PZJPcrk7CxUudlQ3qxt37A/edit

We patch [this commit](https://github.com/robin-near/nearcore/commit/b85ed54ac03f1184c47df197631dea969c5f479c) to point from the validator nodes to the opentelementry trace collector in this server.

Instead of managing it in a personal server, we should have a dedicated tracing server for the forknet setup; it should be brought up together with other nodes and the nodes should point to the tracing server for OpenTelemetry traces. See a [related thread here](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/Chunk-based.20tracing/near/435228747).

**Comment by andrei-near** [comment]
Adding a tracing server in https://github.com/Near-One/infra-ops/pull/77 .
To enable tracing server, set the tracing_server variable to true, i.e:
```
terraform apply \
    -var="chain_id=testnet" \
    -var="unique_id=tracing-test" \
    -var="start_height=1111" \
    -var="**tracing_server**=true"
```

Once TF finished provisioning mocknet network, the tracer IP address will be shown and can be used in when preparing neard with neard_runner:
```
Outputs:
tracer_public_ip = "104.197.219.173"
```

**Comment by tayfunelmas** [comment]
Tracing node is now part of the mocknet setup. Closing this one.
