### ISSUE TITLE
[local testnet] login through wallet link should be generated for user

### ISSUE THREAD

**Issue by potatodepaulo** [near/nearcore#1129]
What's happening:

I run `./scripts/start_testnet.py` from nearcore for the first time.

It asks me for account id. It's unclear what this is for.

<img width="691" alt="Screenshot 2019-08-01 14 06 33" src="https://user-images.githubusercontent.com/6679554/62327866-7d198880-b466-11e9-8d98-d98dfab1629d.png">

I put in my account ID and It returns the line highlighted in red:

<img width="823" alt="log_in" src="https://user-images.githubusercontent.com/6679554/62327620-fa90c900-b465-11e9-8866-e6ba9f646952.png">

As a user, I don't know what to do. 

What should happen:

I go through the above flow, and at the end, something similar to this is printed: 

<img width="889" alt="Screenshot 2019-08-01 14 18 37" src="https://user-images.githubusercontent.com/6679554/62328184-44c67a00-b467-11e9-8931-2eeac69afb08.png">

As a user, I have a clear directive to accomplish this.

**Comment by bowenwang1996** [comment]
Outdated. I believe we no longer use `start_testnet.py`
