### ISSUE TITLE
Implement handling of slow chunks

### ISSUE THREAD

**Issue by wacban** [near/nearcore#11339]
Make sure that the blockchain can handle and recover from chunks that may take long time to be produced, validated, endorsed and included in a block. Currently the chain running stateless validation would never be able to produce another chunk after the slow chunk is included in a block. 

The following scenario would lead to this issue (this needs confirmation!). 

1. A slow chunk `C(h)` is produced and included in a block `B(h)` at height h. 
2. The chunk producers take a while to apply the slow chunk. Let's say blocks at h+1, h+2 and h+3 were produced in the meantime. 
3. The chunk producer for h+4 creates a new chunk `C(h+4)` and state witness for the state transition from `C(h)`. 
4. The chunk producer distributes the chunk `C(h+4)` and the corresponding state witness to chunk validators. 
5. The chunk validators apply C(h) using the state witness in order to validate `C(h+4)`. This is slow. 
6. Block `B(h+4)` is produced without the chunk C(h+4) because endorsements are missing. 
7. The chunk validators finish validating `C(h+4)` and send chunk endorsements - but it is too late. 
-  The steps 3-7 repeat and no new chunk can ever be included in a block. The shard is stuck. 

There may be different reasons for a chunk to be slow. Those factors are additive. The most likely ones are:
* slow apply time - e.g. An undercharged chunk takes a long time to apply. 
* slow chunk and witness distribution - e.g. an overblown state witness may not be distributed to enough validators on time. 
* existing missing chunks - If chunks were missed on a shard, the next chunk needs to include the receipts from the other shards from multiple heights. This contributes to both the apply time and distribution. 
* bugs

The test implemented in #11317 uses a fake `sleep` host function to trigger this behaviour. It currently fails on nightly where stateless validation is enabled. It can be used as a repro tool to get a better understanding of this issue and to prove that the solution works.

**Comment by bowenwang1996** [comment]
We can consider this done for the mainnet launch since #11344 is merged. Will do more testing in forknet
