### ISSUE TITLE
Saturate multiple shards with the Locust FT transfer benchmark

### ISSUE THREAD

**Issue by akashin** [near/nearcore#11347]
We can saturate a single shard with 550 TPS, but two shards also peak at around the same number which is not expected - the throughput should be roughly double that. We should investigate why this is not the case and fix it.

**Comment by MCJOHN974** [comment]
Upd: [document](https://docs.google.com/document/d/1NRYRkJUjVAb5djJKNY6Vl4gyXyNCOE48P_KscD3Sy1Y/edit) with instructions how to saturate two shard network (and get around 800 TPS on a bit weaker machine comparing to one that produces 550 TPS on single shard)



TODO: refactor the document, probably create a new one with this instruction only.

**Comment by MCJOHN974** [comment]
@akashin, probably solution "just use multiple locusts or multi-machine locust" is good enough for our purposes and we can close this?
