### ISSUE TITLE
Identify and document the setup for large contract state for Locust FT benchmark

### ISSUE THREAD

**Issue by akashin** [near/nearcore#11359]
The size of the FT contract used in a benchmark needs to be big enough to expose costs of storage operations similar to the ones on mainnet

**Comment by akashin** [comment]
With [these changes](https://github.com/near/nearcore/pull/11488) we can create ~110 FT users per second. It will still take 12 hours to get to 6M users that Sweatcoin has, so we will need to reuse that setup between benchmark runs.

**Comment by akashin** [comment]
To summarize some interesting stats after creating 10M users:
- The total running time was 14 hours
- The total contract size gets to 1'250'178'692 ~= 1.25GB
- The database size grows to 134GB
- The total IO/R of the node is 2.78TB
- The total IO/W of the node is 6.18TB
- The compute cost was 2.3s per second
- The network processed 350 tps

I find the disk usage to be surprisingly large

**Comment by akashin** [comment]
> I have the same impression, especially considering my run for 18M users only created 19G of database. Are you measuring the database size with `du -hs`? And if yes, did you maybe disable rocksdb compression or something?

Yes, I'm using `du -sh *`. In the current setup I have:
- 40M users spread across 4 contracts
- each contract is 1.25GB in size, 5GB total
- The size of `data` folder on disk is 250GB

I'm running with a default configuration provided by `nearup`, attaching it here.
[config.json](https://github.com/user-attachments/files/15902828/config.json)
[genesis.json](https://github.com/user-attachments/files/15902829/genesis.json)

**Comment by Ekleog-NEAR** [comment]
Hmm strange 🤷 I guess it all depends on how rocksdb decides to compress, or not, the workload, so the difference is most likely due to the timing I’d guess — if your machine was able to generate 10M users in 14 hours it’s significantly faster than when I ran on the GCP VM (which generated 18M users in 2~3 days). So possibly the discrepancy is due to rocksdb deciding to compress less aggressively.
