### ISSUE TITLE
Sync process not working - corrupted data

### ISSUE THREAD

**Issue by ncavedale-xlabs** [near/nearcore#11401]
**Describe the bug**
After setting up a mainnet RPC node and downloading the snapshot as indicated in the [documentation](https://near-nodes.io/intro/node-data-snapshots), I noticed the sync process would go veeery slow. It could take between 24 and 48 hs to finish, and in the end I encountered a `DBNotFoundErr` which seemed to indicate my data was corrupted and I had to resync.

**To Reproduce**
N/A

**Expected behavior**
The node should be able to catch up in just a few hours.

**Version (please complete the following information):**
- nearcore: `v1.39.0`, `v1.39.1`, `v1.39.2`
- rust: `v1.75.0`, `v1.78.0`

**Additional context**
During the `sync` process, I encountered several messages like these in the logs:

```shell
May 22 20:05:34 m-near-01 neard[1933]: 2024-05-22T20:05:34.188349Z  INFO near_network::peer_manager::connection: peer ed25519:8nKBjwX34CbNMEqnFVbcDDh6J7W8PzE99rXCTK7zKKgE disconnected, while sending SyncAccountsData
May 22 20:05:34 m-near-01 neard[1933]: 2024-05-22T20:05:34.727682Z ERROR network: Failed to save peer data err=Peer ed25519:8nKBjwX34CbNMEqnFVbcDDh6J7W8PzE99rXCTK7zKKgE is missing in the peer store
```

As indicated by the documentation, _A bad performing peer that is close to your node may cause your node to miss blocks_
 (https://near-nodes.io/troubleshooting/common-errors).

So I decided to try blocking those peers using the "blacklist" parameter in `config.json`. Using the following API call, I found out their IP addresses:
```shell
curl -sq -H 'Content-Type: application/json' -XPOST -d '{"id":"yolo","method":"network_info","params":[],"jsonrpc":"2.0"}' localhost:3030 | jq '.result.active_peers'
```

After blocking them, the sync process sped up and I was able to catch up with the network in a few hours, as expected.
I don't know why this happened to me while no one else seems to have this issue. Maybe, as the documentation says, it's caused by bad peers that are geographically close to my node?

In any case, I think it would be ideal if this was handled automatically by `neard`, by adding the offending peers to the blacklist dynamically, and maybe keep them there for a couple hours.
Also, it would be good if we could blacklist peers using their IDs instead of their IP addresses.

**Comment by qedgardo** [comment]
I'm facing the same issue. is there any update on this issue?

**Comment by DDeAlmeida** [comment]
@walnut-the-cat @wacban 
If you can take a look

**Comment by wacban** [comment]
cc @saketh-are Who's both state sync and networking expert, can you have a look? :)

**Comment by saketh-are** [comment]
@qedgardo @DDeAlmeida Thanks for reaching out. It would be very helpful if you could clarify which part(s) of the issue you are facing.

- Did you see DBError after performing sync? If so, would you happen to have the full contents of the error message?
- Did you see the issue with peers disconnecting unexpectedly?
- Did you experience a slow sync process? If this is still the case would you be able to share the debug info at `:3030/debug/pages/sync`?

**Comment by ncavedale-xlabs** [comment]
I'm no longer having this issue after blacklisting those peers. If it happens again, I'll capture the debug info at `:3030/debug/pages/sync`.

**Comment by qedgardo** [comment]
Hi @saketh-are thanks for your reply!
I was facing a slow sync process due to bad peers. I blacklisted those peers and the node has caught up now. I will share the debug info if this happens again

**Comment by telezhnaya** [comment]
I guess it should be fixed by now
Feel free to re-open if needed
