### ISSUE TITLE
Mocknet testing for stateful-to-stateless protocol upgrade

### ISSUE THREAD

**Issue by tayfunelmas** [near/nearcore#11465]
Also see [the related task](https://github.com/near/near-one-project-tracking/issues/65) for preparing for the stateful-to-stateless transition.

This could be combined with the task [here about testing with 100+ nodes](https://github.com/near/nearcore/issues/11231).

**Comment by walnut-the-cat** [comment]
duplicate of https://github.com/near/near-one-project-tracking/issues/65
