### ISSUE TITLE
Investigate high memory and disk usage for FT benchmark

### ISSUE THREAD

**Issue by akashin** [near/nearcore#11585]
In the [FT benchmark](https://github.com/near/nearcore/issues/11348), on a powerful machine we were able to increase the gas limit to 10 PGas and increase the throughput to 3000 TPS.

However, at this load, the node started consuming additional 26GB of RAM and writing to disk 400 MB/s. This seems excessive for this workload, that only has a few megabytes of contract state and each transaction is only 100s of bytes in size.

We need to investigate where this resource usage comes from as it is preventing us from processing more transactions.

**Comment by nagisa** [comment]
Was this with or without memtries?

**Comment by akashin** [comment]
> Was this with or without memtries?

I saw high memory usage in both cases.
You can see the stats for memtrie in https://github.com/near/nearcore/issues/11458#issuecomment-2149680529.

**Comment by akashin** [comment]
We did a further investigation with @Ekleog and concluded that this is likely happening due to RocksDB compactions, which works as intended.
