### ISSUE TITLE
Start TestNet should connect with an account

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1162]
Current behavior:

Currently we ask for an account id, but that might not be existing account id.
Also after the node starts, user might not be clear to find the key they need to stake.

Possible behavior:

When running `./scripts/start_testnet.py`. 
New key pair is created and provides a URL to Wallet (which can be customized with `--wallet-url`) to stake with the given key. 
After that is done, user can return and enter the account id - we can check that this account id is actually staking.

Possible behavior 2:

We don't ask to stake when starting the node.
Instead we have another script that initiates the flow later after node is synced (restarting the node). This script would need to verify that node is synced before allowing to stake.

**Comment by bowenwang1996** [comment]
Outdated. I don't think that script is used anymore
