### ISSUE TITLE
[Forknet][BUG] state-dumper nodes cannot start when forknet is initialized with congestion control

### ISSUE THREAD

**Issue by VanBarbascu** [near/nearcore#11694]
Reported in [Zulip](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Forknet.20100-node.20test/near/447232490)

This currently blocks the setup of a new forknet on with protocol version >= 81

**Comment by wacban** [comment]
I think this issue will be fixed by #11724. That being said it won't fix it retroactively, we will need to restart the dumper from genesis in order for it to cache the congestion info. From this point onwards it should work. Let's wait for this PR to be merged and then we can try again.

**Comment by VanBarbascu** [comment]
FIxed! Thanks @wacban
