### ISSUE TITLE
nayduck: sync_state_dump

### ISSUE THREAD

**Issue by staffik** [near/nearcore#11770]
`sync_state_dump` is failing in nayduck: https://nayduck.nearone.org/#/test/61012

Run with: `cargo test -pintegration-tests --features test_features,expensive_tests -- --exact --nocapture tests::client::sync_state_nodes::sync_state_dump`

It passes all the time on my mac, and it passed two times on my linux.

**Comment by tayfunelmas** [comment]
Fixed in https://github.com/near/nearcore/pull/11773.
