### ISSUE TITLE
2.1.0-rc.2 congestion gas for a `PromiseYield`

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#11873]
**Describe the bug**
During block catch-up on testnet, the node is spamming:
`ERROR congestion_control: Attempting to calculate congestion gas for a PromiseYield.`

I'm not sure if it is related only to the sync, or just in general

**To Reproduce**
1. Stop node
2. Wait some time
3. Start node
4. Observe the error in the logs

**Expected behavior**
Do not attempt Or don't show an error.

**Screenshots**
https://gist.github.com/evgenykuzyakov/0e73c389351367ec1f67c218a34c65b3

**Version (please complete the following information):**
- nearcore commit/branch: `2.1.0-rc.2` (+sha disabled)
- rust version (if local): 1.79.0
- docker (if using docker): no
- mainnet/testnet/betanet/local: testnet

**Additional context**

**Comment by bowenwang1996** [comment]
cc @wacban @saketh-are

**Comment by wacban** [comment]
JFYI I am removing the error message. It will take a while until it is released though. I will follow up separately to make sure that the promise yield are accounted for in congestion control.
