### ISSUE TITLE
2.1.0-rc.2 SIGILL on older CPU

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#11872]
**Describe the bug**
Testnet RPC node crashes with `2.1.0-rc.2` release: https://gist.github.com/evgenykuzyakov/4d4bd4759f8ebee978ef7f2898200a06

It has the following CPU: https://gist.github.com/evgenykuzyakov/0b54e1ec527a6bc1d7b0507e472dbca1

Seems like 2.1.0 release introduced `+sha` target in `.cargo/config.toml` that is not available on some older CPUs.

It also looks like `+sha` is just an optimization and is not a hard requirement for a node to function.

**To Reproduce**
1. Upgraded node from from `2.0.0-rc.5` to `2.1.0-rc.2`.
2. Run `neard` on the x86 CPU without `sha` flag

**Expected behavior**
Either verify the CPU flag exists before compilation or make it an explicit requirement in the release.

**Version (please complete the following information):**
- nearcore commit/branch: `2.1.0-rc.2`
- rust version (if local): 1.79.0
- docker (if using docker): no
- mainnet/testnet/betanet/local: testnet

**Additional context**

Verified that it runs when the flag is removed from the `.cargo/config.toml`

**Comment by frol** [comment]
@evgenykuzyakov Well, it was discussed in this thread: https://github.com/near/nearcore/pull/11711#issuecomment-2208401078, and concluded with:

> If they are running without SHA-NI, their node is pretty slow and with stateless this problem would likely get exacerbated to the point where the node cannot keep up with the network at all (if it is still able to right now.)

**Comment by evgenykuzyakov** [comment]
> @evgenykuzyakov Well, it was discussed in this thread: [#11711 (comment)](https://github.com/near/nearcore/pull/11711#issuecomment-2208401078), and concluded with:
> 
> > If they are running without SHA-NI, their node is pretty slow and with stateless this problem would likely get exacerbated to the point where the node cannot keep up with the network at all (if it is still able to right now.)

Let's add it to the release notes than and update docs

**Comment by VanBarbascu** [comment]
Hi @evgenykuzyakov, the hardware requirements have always required SHA-NI. See the [docs](https://near-nodes.io/validator/hardware). We initially hoped that this will be an easy transition since it is specified in the requirements. 

You are right, it is worth adding it to the release notes to make it clear.

**Comment by VanBarbascu** [comment]
I have updated the [release notes](https://github.com/near/nearcore/releases/tag/2.1.0-rc.2).
