### ISSUE TITLE
Tracking issue for fixing minimal required stake

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#11953]
We should consider simpler configuration for minimal required stake. For the current one, we missed accidental increase to 100K NEAR for 2.0.0 release.
Some lower boundary must exist, e.g. 1 staked NEAR causes more chain overhead than gives benefit. We probably should just set boundary explicitly, e.g. by saying that proposal is ignored only if stake < 10K NEAR. But some dependency on total stake must exist as well because inflation exists.

See https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/2.2E0.2E0/near/462393447 for more details.

#11947 was the temporary fix for mainnet setting min stake ratio to 1/62500 which is ~10K NEAR as of 2024-08-15.

**Comment by foxreymann** [comment]
@Longarithm So 1/62500 * x = ~10k NEAR. What is `x` in this equation? Please explain.

**Comment by Longarithm** [comment]
The protocol iterates over stake proposals in non-increasing order and adds account to the validator list if this condition is met: https://github.com/near/nearcore/blob/master/chain/epoch-manager/src/validator_selection.rs#L400-L409

`account_stake / (total_current_validator_stake + account_stake) > 1 / 62500`

So roughly account stake must be at least `total_validator_stake / 62500`. Now total validator stake is 610887913 NEAR, so threshold will be ~= 9774 NEAR. In other words, `x` is total validator stake.
