### ISSUE TITLE
[Epoch Sync] Merkle tree size for a block mismatches with the block ordinal?

### ISSUE THREAD

**Issue by staffik** [near/nearcore#12256]
### Description

Follow-up task to https://github.com/near/nearcore/pull/12020.
Investigate, why `+1` is needed in:
```
current_epoch.partial_merkle_tree_for_first_block.size() + 1
            != first_block_header.block_ordinal()
```

**Comment by robin-near** [comment]
This is expected. block_ordinal stored in the header is 1-based; everywhere else is 0-based.

Will remove the TODO and make it clearer when tackling the general merkle tree task.
