### ISSUE TITLE
Implement a better way to create shard layout

### ISSUE THREAD

**Issue by wacban** [near/nearcore#12325]
Today the shard layouts are created manually. The new shard layout typically contains a new boundary account and information about how the shards are split relative to the previous shard layout. 

The goal of this task is to implement a better way to create a shard layout, for example from the previous shard layout and a new boundary account. 

The API can be something like: 
`fn new(prev_shard_layout: ShardLayout, new_boundary_account: AccountId) -> Result<ShardLayout>`

**Comment by wacban** [comment]
@ybensacq sorry, I promised it to eagr. I can draft some other issue for you, do you have any particular interests?

**Comment by ybensacq** [comment]
@wacban  just a rust one :-) and something to start to understand the code. but I am open :-) thank you

**Comment by wacban** [comment]
@ybensacq How about #11486 or #11531?

**Comment by ybensacq** [comment]
@wacban  yes go for the first one :-)

**Comment by eagr** [comment]
> `fn new(prev_shard_layout: ShardLayout, new_boundary_account: AccountId) -> Result<ShardLayout>`

From the look of the signature, I presume you're not planning to use the api for e.g. resharding that involves splitting a shard?

**Comment by wacban** [comment]
I was planning on using it for resharding actually. In production networks in particular each shard layout is a split of the previous one. That being said the first target is likely to be the tests in `resharding_v3.rs`. Basically we'd want something like `create_new_shard_layout` except the test version only works for adding a new boundary at the very end.

**Comment by wacban** [comment]
Also I no longer like the `prev_shard_layout` in the API, `prev` is a bit too overloaded in our codebase. Perhaps something like `current_` or `base_` would be better.
