### ISSUE TITLE
refactor BorshDeserialization for Receipt 

### ISSUE THREAD

**Issue by wacban** [near/nearcore#12400]
The deserialization for receipt is a custom implementation that first checks the first few bytes and based on that chooses to deserialize the receipt as either V0 or V1. Since the first bytes are read from the Reader, each of the V0/V1 deserializations is done field by field. It's quite ugly. The goal for this issue is to refactor the implementation so that the deserialization of V0 and V1 can be used directly. It can be done using the following trick:
- read the necessary bytes to decide how to deserialize
- prepare a buffer that consists of the read bytes and the remaining reader - it can be done by using `chain`
  - e.g. https://github.com/near/nearcore/blob/864270f15964e0fa0e8fb1ddc4ec73c358f0bac9/core/primitives/src/receipt.rs#L329
- deserialize using the V0/V1 deserialization

Please note that the actual data layout should not change - it's only the implementation of the deserialization that we're trying to make nicer.

**Comment by wacban** [comment]
@eagr all yours :)

**Comment by wacban** [comment]
You asked:
>  This may need further discussion, maybe in a separate thread. Is there a particular reason that it needs to change? It may be hacky but it's also kinda common in serialization to leverage certain characteristics of data to save bytes. If there's no practical (or potential) issues with this then it feels like an it-aint-broke-dont-fix-it situation, more so if the serialized data is being persisted.

We're not trying to get rid of the hacky deserialization format, we're merely trying to make the implementation thereof simpler. It should be a no-op.

**Comment by eagr** [comment]
Oh, I totally misunderstood the intention. Curious though, is it possible there will be a V4? I mean V2/V3 are still manageable given there're 2 free left in the bytes recording the id length.

**Comment by wacban** [comment]
Reading the comments I think we have a full byte worth of versions (256). The first byte is the version and the disambiguation happens on the second byte. Care needs to be taken though because there is another layer of hackery on top of this one - the ReceiptOrStateStoredReceipt also relies on the serialization format. This one sets the first two bytes to u8::max so we should still have plenty of wiggle room for the future.

**Comment by eagr** [comment]
Yeah, that's right. The padded byte could be used to further discriminate versions.
