### ISSUE TITLE
refactor: Implement `account_id_to_shard_id` as a method in ShardLayout

### ISSUE THREAD

**Issue by wacban** [near/nearcore#12480]
### Description

Today we use a function called `account_id_to_shard_id` in order to figure out what shard an account belongs to. It's a bit annoying to use. A better way would be to have it as a method in ShardLayout. This would be nicer since then the IDE can suggest this method when dealing with ShardLayout. It also seem more natural to have it as a method. 

The goals of this issue are to:
* Implement `account_id_to_shard_id` as a method in ShardLayout
* Adjust the existing `account_id_to_shard_id` to simply called the ShardLayout::account_id_to_shard_id
* Migrate a few usages of the old one to the new one. 

There is no need to migrate all of the old usages as that may be annoying and of little learning value. It's fine to just do a few to show that it works. 

reference:
https://github.com/near/nearcore/blob/10369c6e035d31d0ab49686befffc0816b9bfc0c/core/primitives/src/shard_layout.rs#L760-L765

**Comment by virajbhartiya** [comment]
Can I work on this?

**Comment by wacban** [comment]
@virajbhartiya Sorry, it's a ramp up task for someone else.
