### ISSUE TITLE
Please do not re-tag releases in Git

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#12603]
Please read https://handbook.chorus.one/ and especially https://handbook.chorus.one/node-software/release-engineering.html

To all your Engineers who are going to be responsible for release tagging, please make sure they read our Release Engineering guidelines.

FYI @staffik 

Validators on Telegram already started to ask, which version should they really use and it's hard to say who deployed which commit to production already from broader community. Our automation already detected re-tagging and conflict of the same version string versus different commits behind it. Please don't do this.

**Comment by staffik** [comment]
Sorry, was not aware of that, won't do this again.

**Comment by staffik** [comment]
Would it help if I restore the tag to the initial release commit?

**Comment by kucharskim** [comment]
It wold be good to add Git commit to the `/status` endpoint, so people know from which exact checkout the built the code:
```
$ curl -s 10....:3030/status | jq -Mr .version
{
  "version": "2.4.0",
  "build": "2.4.0",
  "rustc_version": "1.82.0"
}
```

**Comment by staffik** [comment]
> please make sure they read our Release Engineering guidelines.

Added it to our internal release handbook.


> It would be good to add Git commit to the `/status` endpoint

We'll handle this as part of issue: https://github.com/near/nearcore/issues/12624.
