### ISSUE TITLE
Validate account_id when we parse it in vm-logic.

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#1266]
Either in Ext or Vm-logic utils.

**Comment by nearmax** [comment]
@fckt This is fixed now, correct?

**Comment by ailisp** [comment]
Looks current "validate": validate it's valid utf-8, do we need additional validation there?
```rust
        let account_id = AccountId::from_utf8(buf).map_err(|_| HostError::BadUTF8)?;
        Ok(account_id)
```

**Comment by fckt** [comment]
We have an account validation here
https://github.com/nearprotocol/nearcore/blob/54b597cfc53de24aa7c9813eea87926ad9752aa1/runtime/runtime/src/actions.rs#L246

https://nomicon.io/Primitives/Account.html#account-id-rules

**Comment by evgenykuzyakov** [comment]
The main reason for early validation is to avoid memory cost issues. We don't charge extra fees for the length of the `account_id` when creating a new receipt. So you only paying memory access when passing the account from the buffer.

Another reason: we should stop the contract as early as possible to save gas for the contract and for the user. It increases TPS and good for the network.

**Comment by evgenykuzyakov** [comment]
Validation requires  refactoring `core/primitives` to extract `utils`.

**Comment by bowenwang1996** [comment]
Duplicate of #2074
