### ISSUE TITLE
keygen generator shouldn't depend on `near` crate

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#1582]
We should refactor `get_default_home` out of near

**Comment by bowenwang1996** [comment]
I tried, but it depends on `near` for the keyfile names. I don't think we want to refactor that.

**Comment by evgenykuzyakov** [comment]
Why?

**Comment by bowenwang1996** [comment]
Actually we do not need key generator any more. We should simply remove the crate

**Comment by bowenwang1996** [comment]
key generator is no longer relevant
