### ISSUE TITLE
Fix banning other peers for abuse.

### ISSUE THREAD

**Issue by mfornet** [near/nearcore#1586]
This is closely related to #1519 
A temporary workaround to avoid this is disable banning for that reason (#1585).

**Comment by bowenwang1996** [comment]
@mfornet is this still relevant?

**Comment by mfornet** [comment]
Currently there is little protection against Peer that tries to DOS a node. So banning those peers is still a good idea. However, as seen in the past, just by measuring the amount of bytes received from a Peer is a poor metric, since some times there are traffic spikes between honest nodes.

Also this problem can be solved outside of nearcore, by having control of the traffic with other peers with an external tool that allows banning manually/automatically.

I'm closing this issue now, and let's open a more relevant issue if this creates a problem.
