### ISSUE TITLE
Stability and throughput testing

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#1634]
This is Epic that collects all stability and throughput / performance testing issues.

**Comment by ailisp** [comment]
azure, aws, digitalocean support in progress, they would make 100 node test possibly less automatic as current, but before block production in 100 gcloud node go well I think we don't need to try it in a higher latency / diversed environment

**Comment by bowenwang1996** [comment]
We should first have this kind of testing on gcloud with 100 nodes. This is WIP.

**Comment by bowenwang1996** [comment]
This is outdated with the introduction of mocknet
