### ISSUE TITLE
Add a bootnodes config validation

### ISSUE THREAD

**Issue by ae0f** [near/nearcore#1655]
Add a bootnode config validation. account_id cannot be `Some("34.89.175.66 :24567")`  and address must be defined.

[2019-11-06T11:06:42Z WARN  near_network::peer_manager] Trying to connect to peer with no public address: PeerInfo { id: ed25519:FF7ttcBjsyNtXh6fBw5q85o2HYgtPxnC36Xhvt3HYb8X, addr: None, account_id: Some("34.89.175.66 :24567") }

**Comment by janewang** [comment]
@chefsale Are you working on this already? Please let us know. Thanks!

**Comment by chefsale** [comment]
I haven't started working on this, I just added th boot nodee to the init command. Is this urgent, if yes I can takr it over.

**Comment by bowenwang1996** [comment]
> Is this urgent

No it is not urgent. Just want to make sure that it is still relevant

**Comment by Rishabhraghwendra18** [comment]
@bowenwang1996 @janewang I will like to work on this issue . May you guide me what changes I have to make in which file to solve this issue ?

**Comment by bowenwang1996** [comment]
I think it is about making sure that the ip address can be properly parsed. Actually it seems that this has already been fixed. @Rishabhraghwendra18 maybe you can help verify that

**Comment by Rishabhraghwendra18** [comment]
@bowenwang1996 yup sure... I think you are correct it has been implemented . I have found this [PR](https://github.com/near/nearcore/pull/5029) which talks about `boot_address` . It made the changes to extract the address inside a function (as per the PR description)

**Comment by bowenwang1996** [comment]
@Rishabhraghwendra18 thanks! closing this issue as it is already implemented
