### ISSUE TITLE
database lock didn't get removed

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#1693]
In a remote test when i force shutdown a tmux session and reopen the node, get:
```
[2019-11-14T21:24:00Z INFO  near] Opening store database at "/home/bo_nearprotocol_com/.near/data"
thread 'main' panicked at 'Failed to open the database: Custom { kind: Other, error: "IO error: While lock file: /home/bo_nearprotocol_com/.near/data/LOCK: Resource temporarily unavailable" }', src/libcore/result.rs:1165:5
```
Not sure if database is in a corrupted state or just remove LOCK file it works. but ideally we should be able to handle this (clean up corrupted part of database, sync them from peers) instead of panic

**Comment by bowenwang1996** [comment]
Sometimes when I encounter this problem, I just remove the LOCK file it works, but I don't quite understand why this happens. It may be that the shutdown was not clean. We should definitely look more into this.

**Comment by ailisp** [comment]
>  I just remove the LOCK file it works
This would be great, we can just remove it when exist to avoid panic. Rely rocksdb to recover from sudden exits

> I don't quite understand why this happens
My understanding: It's likely happen when a force shutdown happens. when rocksdb is writing something it place a LOCK file. If gracefully start with C-c rocksdb clean up it. If force shutdown kill -9, -15, or just force shutdown the laptop, there isn't time for rust to run Drop for rocksdb

**Comment by ilblackdragon** [comment]
@ailisp Is this fixed now?

**Comment by ailisp** [comment]
I think LOCK file wasn't removed (at a force kill) is expected behavior. We need handle this either in nearcore (try some rocksdb methods to recover db. But it's possible the LOCK is real (another near process is running), so maybe this should be handled in script, which check near is not running, delete LOCK if it's there

**Comment by bowenwang1996** [comment]
This is similar to #3266
