### ISSUE TITLE
State sync should not split state into parts if state is tiny

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1708]
Right now state sync will always split the state and sync it in parts even if it is 1KiB. 
 This is highly inefficient since it produces unnecessary communication and the only reason it is done is to make sure all our tests also automatically test the state sync done in parts as discussed here: [https://github.com/nearprotocol/nearcore/pull/1661#discussion_r347074146](https://github.com/nearprotocol/nearcore/pull/1661#discussion_r347074146)

I think it makes a lot of sense to fix it by having a flag `force_state_split` somewhere in some config that we only enable on the tests. WDYT @SkidanovAlex @mikhailOK

**Comment by Kouprin** [comment]
Should be discussed with @SkidanovAlex first. We must measure the profit of the task before starting doing it.

**Comment by nikurt** [comment]
Irrelevant for networks with state larger than a few megabytes.
If network's state is just a few megabytes it will be very easy to sync, whether it's 2 parts more or fewer.
