### ISSUE TITLE
Expose downloading Wasm binary

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1712]
Currently, RPC allows seeing the account state (which includes Wasm code hash) and key values stored by the smart contract. But it does not allow seeing the code of the smart contract itself.

**Comment by mikedotexe** [comment]
Clicked the subscribe button on this issue. Been talking with an experienced Ethereum dev who's excited about NEAR and he's similarly emphasized the importance of this. Wanted to give this issue a friendly bump.

**Comment by ailisp** [comment]
Done in #3714
