### ISSUE TITLE
RuntimeConfig generator should use tries of various sizes

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1725]
RuntimeConfig generator should use tries of various sizes to expose fees that depend on the size of the trie and make sure we correctly parametrize it.

**Comment by nearmax** [comment]
Motivation is explained here: https://github.com/nearprotocol/nearcore/issues/1510

**Comment by bowenwang1996** [comment]
@nearmax is this issue still relevant?

**Comment by bowenwang1996** [comment]
Obsolete
