### ISSUE TITLE
Switching back and forth between RuntimeConfigs

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1739]
Once we have `RuntimeConfig` in the trie: #1738 We need to allow to have several different versions of the `RuntimeConfig` to be usable at the same time. The problem is that each block index is associated with one `RuntimeConfig` and runtime should be able to pick config for the past block index (if the fork happens or a proof is needed to be validated).

**Comment by evgenykuzyakov** [comment]
This change might break balance checker. I'm not sure it will, but there is definitely a possibility that some fee decreased or increased and it breaks the balance for some reason during.

Or we would be able to mint more tokens based on fees difference during refunds.

**Comment by nearmax** [comment]
> Or we would be able to mint more tokens based on fees difference during refunds.

Refunds should be then using the old config.

**Comment by ilblackdragon** [comment]
Just to confirm, at this point with BFT finality we don't need multiple version of RuntimeConfig.
We also only should switch any versions on the epoch boundary.

**Comment by bowenwang1996** [comment]
This is effectively implemented with how the protocol upgrade works in general. For each block we know the associated protocol version and can then decide which runtime config to use
