### ISSUE TITLE
process_state_update shouldn't panic

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#1773]
Right now `process_state_update` might panic for chunk state challenge for malicious state values. E.g. if both account balance and locked are `u128::max_value()`

**Comment by evgenykuzyakov** [comment]
Also these line might overflow:
https://github.com/nearprotocol/nearcore/blob/73c0e7cd86068eeafdeed067f0f6d65cb0c479fe/near/src/runtime.rs#L323-L324

**Comment by bowenwang1996** [comment]
Already fixed
