### ISSUE TITLE
PartialEq should be using hash whenever it is relevant

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#186]
The derived implementation of `PartialEq` trait would compare every field of a struct. However some of our structs are too large for that. Many structs that we use have hash or signature field that should be used instead. This might be a major bottleneck and should be fixed as soon as we use correct signatures and hashes everywhere.

**Comment by azban** [comment]
this is done for TransactionBody. we should probably enumerate the list of structs we want to do this for.

**Comment by nearmax** [comment]
Yes, after we start benchmarking it will be easier to talk about the bottlenecks.

**Comment by bowenwang1996** [comment]
outdated
