### ISSUE TITLE
Rebalance network

### ISSUE THREAD

**Issue by mfornet** [near/nearcore#1896]
Currently network is growing organically without any optimization. Since network graph is known to every peer we can optimize it to minimize network latency by minimizing diameter. 

Notes:
- We should take into account attack vectors from malicious actors, avoid eclipse attacks.
- Useful link from [wikipedia](https://en.wikipedia.org/wiki/Table_of_the_largest_known_graphs_of_a_given_diameter_and_maximal_degree).

**Comment by ailisp** [comment]
I'm thinking if network is optimized by latency, 100 node test maybe work fine. Currently one node send shard to 50%-60% nodes are fast, with in half second, but send to some slow nodes are too slow.

**Comment by mfornet** [comment]
> I'm thinking if network is optimized by latency, 100 node test maybe work fine. Currently one node send shard to 50%-60% nodes are fast, with in half second, but send to some slow nodes are too slow.

I don't think it is a good idea to optimize regarding latency from the point of view of decentralization, since it can be gamed by placing "very fast" nodes closing to honest nodes, and effectively launching an eclipse attack.

Though nodes that are too slow might be "banned" (not necessarily a hard ban), right now, there is no action take in that regard from the network side, but slow block/shard producers are kicked out if they can't keep up expected production rate.

**Comment by ilblackdragon** [comment]
@mfornet I'm moving this to Post-MainNet. If you don't agree, please comment.

**Comment by bowenwang1996** [comment]
Since we are considering a different design, I am going to close this issue
