### ISSUE TITLE
Deprecate block_index in favor of block_height

### ISSUE THREAD

**Issue by Kouprin** [near/nearcore#1903]
Deprecate `block_index()` host function in favor of `block_height()`.
Meaning, we need to add `block_height()` and then at some point in the future when we can confirm no one is using `block_index()` or we have inspection tools to surgically rewrite WASM delete `block_index()` host function.

Related to the comment: https://github.com/nearprotocol/nearcore/pull/1882#pullrequestreview-336923714

See also discussion: https://github.com/nearprotocol/nearcore/pull/2053#discussion_r396735590

**Comment by Kouprin** [comment]
@nearmax please make sure this will be added with next hard fork.

**Comment by nearmax** [comment]
We still don't have a consensus on whether this change is needed at all. Since it will be breaking everything in our system (Applayer and already deployed smart contracts) and the only upside of it is that it unifies `block index` and `block height` which are synonymous in the blockchain world.

**Comment by Kouprin** [comment]
> We still don't have a consensus on whether this change is needed at all. Since it will be breaking everything in our system (Applayer and already deployed smart contracts) and the only upside of it is that it unifies `block index` and `block height` which are synonymous in the blockchain world.

Can we decide when next hard fork will happen?

**Comment by nearmax** [comment]
> > We still don't have a consensus on whether this change is needed at all. Since it will be breaking everything in our system (Applayer and already deployed smart contracts) and the only upside of it is that it unifies `block index` and `block height` which are synonymous in the blockchain world.
> 
> Can we decide this when next hard fork will happen?

Why the timing of the hardfork is relevant with regards to whether we are making this change or not?

**Comment by Kouprin** [comment]
> Why the timing of the hardfork is relevant with regards to whether we are making this change or not?

I guess it will be easy to decide when we are not restricted. Do we want to add this as a bonus for free?

**Comment by nearmax** [comment]
You mean make it an optional change? Sure, we can make it optional for whoever will be making the fork. However, since it will make the fork much harder to make it is unlikely that someone will volunteer to do it.

**Comment by Kouprin** [comment]
> You mean make it an optional change? Sure, we can make it optional for whoever will be making the fork. However, since it will make the fork much harder to make it is unlikely that someone will volunteer to do it.

It makes sense. I believe in volunteers, so let's leave it for whoever will make a fork.

**Comment by bowenwang1996** [comment]
Doing this will break existing contracts. I am not sure what the process of deprecating a host function is. cc @matklad @olonho

**Comment by matklad** [comment]
Is this just about renaming the function? It's easy to inject the same host function under two different aliases, so we can make both names available to contracts. 

I don't think we can have a reasonable process for *removing* the old alias -- there are deployed contracts using it. But I also don't see much problem with not removing it. 

The pragmatic solution would be to just do the rename at the sdk level:

```diff
diff --git a/near-sdk/src/environment/env.rs b/near-sdk/src/environment/env.rs
index 5515527..1d802e4 100644
--- a/near-sdk/src/environment/env.rs
+++ b/near-sdk/src/environment/env.rs
@@ -183,6 +183,7 @@ pub fn input() -> Option<Vec<u8>> {
 }
 
 /// Current block index.
+#[deprecated(reason = "use block_height instead")]
 pub fn block_index() -> BlockHeight {
     unsafe {
         BLOCKCHAIN_INTERFACE
@@ -190,6 +191,10 @@ pub fn block_index() -> BlockHeight {
     }
 }
 
+pub fn block_height() -> BlockHeight {
+    block_index()
+}
+
 /// Current block timestamp, i.e, number of non-leap-nanoseconds since January 1, 1970 0:00:00 UTC.
 pub fn block_timestamp() -> u64 {
     unsafe {
```

cc @austinabell

**Comment by bowenwang1996** [comment]
@austinabell could we create a near-sdk-rs issue and close this one?

**Comment by austinabell** [comment]
Closing as requested, but feel free to re-open if there was something else intended to be added to this
