### ISSUE TITLE
Extract RPC API client into a standalone project

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1905]
Our current restaking tool uses RPC client that was designed to work for testing only. We should extract it into a separate proper RPC client for node.

Following the example, the name on GitHub should be `near-api-rs`, Crates.io - `near-api`, Rust `use` namespace - `near_api`.

**Comment by nearmax** [comment]
As discussed with Near developers it would be nice if we have cleanly extracted RPCUser without pulling too many dependencies from nearcore. Specifically, that would allow us to compile it with stable instead of nightly.

**Comment by frol** [comment]
This issue is quite involving, and required quite some refactoring and restructuring:

* #2976 (and all the sub-items)
* #4651

**Comment by miraclx** [comment]
Update on this: we've successfully completed the task as defined in the original comment as we do now have the new `jsonrpc-client` built from the ground up specifically to be approachable by actual users and outside internal testing. It currently exists in its own repo: https://github.com/near/near-jsonrpc-client-rs. And we have it published in its initial stages at https://crates.io/crates/near-jsonrpc-client.

However, the higher-level `near-api-rs` that should draw closer parallels to the revered `near-api-js` is still WIP but this would serve as a stepping stone for that endeavor.

**Comment by frol** [comment]
I feel we can close this issue on nearcore side now, and next quarter we will lay out the plans about `near-api-rs`
