### ISSUE TITLE
Estimating contract gas usage through interpreter on Applayer side

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1937]
We want Applayer components to know the upper bound on gas before they submit the transaction. It is possible to expose the config with fees through the RPC, however this will allow calculating gas usage only for basic transaction action and will not include smart contract execution. In general, it is not possible to estimate gas usage without executing the contract due to the halting problem. However, Applayer could request the most recent state of the contract from the node through RPC and run the smart contract inside the browser using Wasm interpreter (Wasm interpreters are known to be very small) which would give it a pretty good gas estimate assuming the state of the contract does not change too drastically.

**Comment by evgenykuzyakov** [comment]
It will be good enough to estimate the actual TX fee that you will prepay, but later you'll get part of it back.

So it should be a simple RPC that takes `Transaction` and returns in (tx fee in gas including prepaid gas, attached balance, the latest gas_price).

**Comment by willemneal** [comment]
[This is one possible solution](https://github.com/trailofbits/manticore).   It already has support for Ethereum, [example here.](https://github.com/trailofbits/manticore/blob/5b2e15953394977cb0633b6d3e894b012c7f2609/tests/ethereum/test_general.py#L1665)

However, it's in python so we couldn't use it on the browser side.  But for simple functions it can exhaust every path and even for those that it can't we could get a good estimation of the range of costs.

**Comment by bowenwang1996** [comment]
I believe this will be part of the near-sandbox initiative.
