### ISSUE TITLE
Upgradability

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#1994]
Nearcore node should support being upgraded, this includes:
* Discussion on how we want upgradability to work:
  * Do we want the node to be upgraded automatically or manually by the user?
  * Who determines the output?
  * In what cases the upgrade needs to be backward compatible?
  * etc.
* Design and implementation of config upgradability;
* Design and implementation of binary upgradability.

**Comment by potatodepaulo** [comment]
> Nearcore node should support being upgraded, this includes:
> 
> * Discussion on how we want upgradability to work:
>   
>   * Do we want the node to be upgraded automatically or manually by the user?
>   * Who determines the output?
>   * In what cases the upgrade needs to be backward compatible?
>   * etc.
> * Design and implementation of config upgradability;
> * Design and implementation of binary upgradability.

Wanted to port last bullet point of this issue: https://github.com/nearprotocol/nearcore/issues/1951

Good actors with bad node hygiene will damage the health of the network. We need to create incentives for upgrading quickly (this is not relevant if we choose automatic upgrades). Likewise we may need to punish people with out of date nodes.

**Comment by fckt** [comment]
> Likewise we may need to punish people with out of date nodes.

Note: It's not relevant to upgradability itself. It's related to the consensus algorithm.

**Comment by ilblackdragon** [comment]
Large discussion on upgradability have happened here - https://commonwealth.im/near/proposal/discussion/261-upgradability

**Comment by bowenwang1996** [comment]
Protocol upgradability is implemented. See https://nomicon.io/ChainSpec/Upgradability.html for details
