### ISSUE TITLE
Implement Safes

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#2006]
Implement NEP design https://github.com/nearprotocol/NEPs/pull/26

From nearcore: need to update Runtime, VMLogic to handle Safes
From near-bindgen: need wrappers for Safes
From near-runtime-ts: needs wrappers for Safes

**Comment by nearmax** [comment]
Moving to Ice Box, until after the StakeWars launch

**Comment by bowenwang1996** [comment]
It is not clear whether we want to go with the design in the first place. Will close for now
