### ISSUE TITLE
serde_with.rs in near-vm-logic can panic

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#2011]
It uses unwrap in a few places.

It's also unclear whether we need serialize there at all. Maybe it makes sense to remove all serialize/deserialize derived traits. Needs investigation

**Comment by bowenwang1996** [comment]
I think it's for diagnostics https://github.com/nearprotocol/nearcore/pull/1928

**Comment by evgenykuzyakov** [comment]
Not sure we have this diagnostics in VMLogic. Also it might be an overhead in serialization for diagnostics.

**Comment by evgenykuzyakov** [comment]
It's actually used for `near-vm-runner-standalone`.
So we need to fix the serialization by switching to base64 from utf-8 strings.

**Comment by nearmax** [comment]
Since it is not critical moving it to an IceBox.

**Comment by evgenykuzyakov** [comment]
https://github.com/nearprotocol/nearcore/pull/2257 addressed some concerns but the panic can still happen if the result is non-utf8 for some fields.

**Comment by bowenwang1996** [comment]
@matklad @Longarithm could you take a look to see if this is still relevant?

**Comment by matklad** [comment]
was fixed by https://github.com/near/nearcore/commit/21bd739601a2eef4b5604f25c4539d4c83b2b160#diff-9a360c8a1f103abfcd5312a3a0a559eb719ff2e4f52e62c4c6c58d84249f3141 I belive. 

Although, that module as a whole doesn't "make sense" to me, vm-logic shouldn't care about serialization at all.
