### ISSUE TITLE
Replace actix-web for RPC

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2057]
We are using actix-web for RPC, however we have experienced issues with stability and had some version upgrades break our tests. Also the status of actix-web is not well-defined. We should consider other frameworks:
* https://github.com/seanmonstar/warp
* https://github.com/hyperium/hyper
* ?
Depending on the level of abstraction we want to go with.

**Comment by frol** [comment]
I don't think actix-web is even close to being the main blame for the problem we usually have with RPC. We usually hit internal limitations like slow trie iteration or exhausted actix mailbox much earlier than we hit issues with actix-web.
