### ISSUE TITLE
Investigate testnet slow restart

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2105]
Currently it takes more than 20 minutes for the testnet node to restart. We need to understand why it is the case and how we can fix it.

**Comment by ailisp** [comment]
Why it happens: As Bowen discovered it doesn't happen in the last restart, but once it happened it involve a `~/.near/data` shrink. It goes from 70G to 30G last time. This is a data compaction done by rocksdb. The gcloud instance take `~20 min` to copy 30G data, the same disk io can use 20min to compact 70G to 30G. I think we do want this auto compaction to avoid storage use up very soon (in my local test, run it node a while generate a 800M data, and it was then compact to 200M, therefore I think we do need its compaction). 

How can we fix it: possibly configure compaction to happen in a time deterministic / time bounded way.

**Comment by ailisp** [comment]
Just saw @bowenwang1996 mentions it's because of the other reason. Does restart fast after your PR? https://github.com/nearprotocol/nearcore/pull/2086#issuecomment-583798073

**Comment by ailisp** [comment]
Might be resolved as we limit wal size in #2729 , will see if this week's betanet release saves time

**Comment by bowenwang1996** [comment]
outdated
