### ISSUE TITLE
Dump only the latest state.

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2118]
Currently state dumping https://github.com/nearprotocol/nearcore/pull/2086 dumps the past states as well. We should change it to dump only the latest state.

**Comment by ilblackdragon** [comment]
@bowenwang1996  I'm not clear how we are dumping all states, but is this blocking MainNet?

**Comment by bowenwang1996** [comment]
It is not. Changing to post-mainnet.

**Comment by bowenwang1996** [comment]
Outdated. We still dump state to json
