### ISSUE TITLE
INFO logging level reporting of number of peers is incorrect

### ISSUE THREAD

**Issue by damons** [near/nearcore#2160]
During the staging release process today we noticed that the number of peers reported by the nearcore daemon is incorrect.  For example:
```
Feb 19 19:34:46.910  INFO stats: #     289 2bZz6tiE3chzVmwchS5XvcKEZoLTFVKSF5KvsX9kBWxP -/1  3/2/40 peers ⬇ 5.7kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:34:56.912  INFO stats: #     303 7FwA7FpiKK2Ye7BdtTJzoFAbLc6aX97kkK3UF2TEBWep -/1  3/1/40 peers ⬇ 5.8kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:06.914  INFO stats: #     317 7Rng7K7usN6CbPRpnuBSNZiJ3W97egt1XMLVJqabHpZ3 -/1  3/1/40 peers ⬇ 5.6kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:16.916  INFO stats: #     330 G2UU2vDZUAgXc3GUKmG36jZxbKiJ96pZJjBvvZTTMTS7 -/1  3/1/40 peers ⬇ 5.6kiB/s ⬆ 10.3kiB/s 1.30 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:26.919  INFO stats: #     344 Frmt71UZwuGCiBK8LvYuGf2AqLsQKrq5stabseM15htX -/1  3/1/40 peers ⬇ 5.6kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:36.920  INFO stats: #     358 9VSNaP1c9bdG5AFTA8UVPnvv8fycqzk8WhDb69jg9zyp -/1  3/1/40 peers ⬇ 5.7kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:46.923  INFO stats: #     372 GmECo2rH7B4cwzj133qhfefMmc3dzQYFWhkCKjMsXTL7 -/1  3/2/40 peers ⬇ 5.5kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:35:56.925  INFO stats: #     386 GpbXANNWs8QQeE4qRGJ5sjJKKTXzYjwiyYdx4chXdnmX -/1  3/3/40 peers ⬇ 5.6kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:36:06.928  INFO stats: #     400 76Nm9s3b8XFkLK5LgtRpHmYJGo7JRToYnqFUVJ1WDeV2 -/1  3/1/40 peers ⬇ 5.8kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:36:16.932  INFO stats: #     414 8gECKWcKqD2dRb8VaPncWRm6nFmbmotGw4bGZ78UUy4A -/1  3/1/40 peers ⬇ 5.8kiB/s ⬆ 10.3kiB/s 1.40 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
Feb 19 19:36:26.936  INFO stats: #     427 G42pb9xZpjWjUWu4mCu9pBpyEqsr3aPzgYDKBCi7PHkd -/1  3/1/40 peers ⬇ 5.8kiB/s ⬆ 10.3kiB/s 1.30 bps 0 gas/s CPU: 1%, Mem: 294.2 MiB    
```

This shows a varying number of peers as they are discovered/brought online.  The bug is exposed whenever the first server is brought online (at that point the number of peers is reported correctly), then  more peers are started, what we see then is the first server only shows itself.  When the other servers are executed, the number reported by the first node fails to increment.  This bug can also be seen on the subsequent servers started.  The second server will only show two peers.  The third server will only show three peers, etc.

Expected results:  As new servers/peers are brought online, the number of peers connected to the previously started servers should increase accordingly.

**Comment by mfornet** [comment]
@damons From the logs you are showing I can't see the error, since that node correctly sees the other 3 nodes.  I can't reproduce this locally, are you looking at the correct numbers.

This are logs from two of the four nodes that I ran locally, the first that I spawn and the last one (fourth). In the first node you can see as the number of peers increase as I started spawning new nodes (manually), In the last see how it starts with 3 peers already.

First node
```
Mar 03 17:21:29.360  INFO near: Opening store database at "/Users/marcelo/.near/node0/data"
Mar 03 17:21:29.645  INFO stats: Server listening at ed25519:7PGseFbWxvYVgZ89K1uTJKYoKetWs7BJtbyXDzfbAcqX@0.0.0.0:24567
Mar 03 17:21:39.644  INFO stats: #      42 Waiting for peers V/4  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 37.8 MiB
Mar 03 17:21:49.648  INFO stats: #      42 Waiting for peers V/4  1/1/40 peers ⬇ 12 B/s ⬆ 8 B/s 0.00 bps 0 gas/s CPU: 2%, Mem: 38.9 MiB
Mar 03 17:21:59.653  INFO stats: #      42 Waiting for peers V/4  2/2/40 peers ⬇ 12 B/s ⬆ 8 B/s 0.00 bps 0 gas/s CPU: 2%, Mem: 38.9 MiB
Mar 03 17:22:09.656  INFO stats: #      42 Waiting for peers V/4  2/2/40 peers ⬇ 38 B/s ⬆ 27 B/s 0.00 bps 0 gas/s CPU: 2%, Mem: 38.9 MiB
Mar 03 17:22:19.658  INFO stats: #      53 9m8fF1ZruDEankHJv1HQAPYvX1CiDHNpAWf5r54rWnE2 V/4  3/3/40 peers ⬇ 0.4kiB/s ⬆ 0.4kiB/s 1.10 bps 0 gas/s CPU: 5%, Mem: 41.8 MiB
Mar 03 17:22:29.661  INFO stats: #      67 BMKMYS9Rq3ihnPDhsKHoWE7BqNcmzf29n7AS9ErxZcRu V/4  3/3/40 peers ⬇ 1.3kiB/s ⬆ 1.3kiB/s 1.40 bps 0 gas/s CPU: 5%, Mem: 42.8 MiB
Mar 03 17:22:39.663  INFO stats: #      81 CRefwEPRWCiaLNinw6jgZqLvX9FwaF4JsUW4paJvpSY6 V/4  3/3/40 peers ⬇ 2.4kiB/s ⬆ 2.3kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 43.0 MiB
Mar 03 17:22:49.666  INFO stats: #      95 2G1eJqDHBf74kt9whvES5VBauYzXRmBCKG2CjVr8eEUT V/4  3/3/40 peers ⬇ 3.3kiB/s ⬆ 3.3kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 43.3 MiB
Mar 03 17:22:59.668  INFO stats: #     109 4fJVhcCn6TzfzSnshZJo4Ahihny2ZqbQ4rfavvcZ9JLJ V/4  3/3/40 peers ⬇ 4.4kiB/s ⬆ 4.3kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 43.6 MiB
```

Fourth node:
```
Mar 03 17:22:10.902  INFO near: Opening store database at "/Users/marcelo/.near/node3/data"
Mar 03 17:22:11.103  INFO stats: Server listening at ed25519:ydgzeXHJ5Xyt7M1gXLxqLBW1Ejx6scNV5Nx2pxFM8su@0.0.0.0:24570
Mar 03 17:22:21.108  INFO stats: #      55 7HtkkUeFmQgEinCEFeNrDs23SVghTnaXmGWpv4u2uhzy V/4  3/3/40 peers ⬇ 0.5kiB/s ⬆ 0.6kiB/s 1.20 bps 0 gas/s CPU: 0%, Mem: 41.6 MiB
Mar 03 17:22:31.111  INFO stats: #      69 AX7SgoeRSdLQwbyrZWPSEkPPrnKRnjyU6trdE8CGZZrj V/4  3/3/40 peers ⬇ 1.4kiB/s ⬆ 1.5kiB/s 1.40 bps 0 gas/s CPU: 5%, Mem: 42.7 MiB
Mar 03 17:22:41.116  INFO stats: #      83 ccTJ7wGX2VGbELnS5tx5knJom3VU5MyYyJsjTkQYuQ3 V/4  3/3/40 peers ⬇ 2.5kiB/s ⬆ 2.5kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 42.9 MiB
Mar 03 17:22:51.121  INFO stats: #      97 4xfoQA1gj3cQzdfaCSFj78diUBDQSSSjpLCgNBzcvNnP V/4  3/3/40 peers ⬇ 3.5kiB/s ⬆ 3.5kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 43.2 MiB
Mar 03 17:23:01.124  INFO stats: #     111 F1txDJxe3a7wrLgRnuzsFYSbXXtSbfCQeFe2UV6NPJ42 V/4  3/3/40 peers ⬇ 4.5kiB/s ⬆ 4.5kiB/s 1.40 bps 0 gas/s CPU: 6%, Mem: 43.5 MiB
```

**Comment by damons** [comment]
@mfornet I'll try to come up with a simple test case.  Have other higher priority items at them moment.

**Comment by ilblackdragon** [comment]
@damons Just to double check, are you talking about number of peers or number of "up-to-date" peers?

In reported `3/1/40` in your log - 3 is total peers give node has, 1 is the number of peers with latest blockchain.

Given you are running with 1 validator, it is expected to see there 1 - because the node that is up-to-date is that validator. Everyone else just receives blocks from it.
Also even when there is more block producers, for given node observing others up-to-date is non-consistent, hence that number can be really anything depending on network topology and latency.

**Comment by damons** [comment]
I believe I'm talking about the number of peers with the latest blockchain.  

I still suspect a bug here, but I need to try to reproduce it again.

**Comment by damons** [comment]
The first node/peer started will show:  1/1/40.  It will never increment the second number past one.  The first number will increment when a new node is started/connected. The second node, once started and connected to a peer will show:  2/2/40.   If a third node is started it will show 3/3/40.  However, the second node will only show up to 2/2/40 and never be incremented to 3/3/40.  Only the latest node has the total node counts which are correct.   For example, if a fourth node is started/connected, it will display 4/4/40, but node three will only show up to 3/3/40.  If either of node one or two were to drop out, node three’s (and all subsequent servers) will decrement the second number, and when they return, the second number will be incremented; however, the second number will never be incremented higher than it’s own order, i.e., if it’s node two, then second number will never increase over 2.  If it’s node 5, the second number will never exceed 5, even if there are 20 more nodes that were started after it initially joined the network.

**Comment by bowenwang1996** [comment]
I think it is a known issue that sometimes peer discovery is slow. @mfornet

**Comment by bowenwang1996** [comment]
looks like no action items here. Closing
