### ISSUE TITLE
Improve RPC APIs around returning enums with empty variants

### ISSUE THREAD

**Issue by frol** [near/nearcore#2176]
Currently, Actions in Transaction and Permissions in Access Key APIs are serialized into a list of `string` or `object` depending on whether the enum variant has anything inside:

https://github.com/nearprotocol/nearcore/blob/a031e4f670c70ae362244ef68cf1ed3235a78f4f/core/primitives/src/views.rs#L68-L76

Which leads to inconsistency like:

```js
    "keys": [
      {
        "access_key": {
          "nonce": 1,
          "permission": "FullAccess"   // <-- it is a string
        },
        "public_key": "ed25519:4Ynh6YmogjUYc5V9VqtQ1pRnZ4KuJSAJdkuj9hLj4a2p"
      },
      {
        "access_key": {
          "nonce": 0,
          "permission": {   // <-- it is an object
            "FunctionCall": {
              "allowance": "100000000",
              "method_names": [],
              "receiver_id": "studio-d4zxn4xdu"
            }
          }
        },
```

There is no simple way to force serde to always serialize it to an object (https://github.com/serde-rs/json/issues/602), i.e.:

```js
    "keys": [
      {
        "access_key": {
          "nonce": 1,
          "permission": {  // <-- it would be consistent if it will be an object as well
            "FullAccess": null
          }
        },
        "public_key": "ed25519:4Ynh6YmogjUYc5V9VqtQ1pRnZ4KuJSAJdkuj9hLj4a2p"
      },
      {
        "access_key": {
          "nonce": 0,
          "permission": {   // <-- it is an object
            "FunctionCall": {
              "allowance": "100000000",
              "method_names": [],
              "receiver_id": "studio-d4zxn4xdu"
            }
          }
        },
```

While the above transition can be treated as a semi-breaking change, it seems to provide some consistency for the future. If we decide to go with a new version of the API, we should consider [tagged enum representation](https://serde.rs/enum-representations.html).

**Comment by frol** [comment]
That would be a breaking change, so we should not do it. This change is only possible when we redesign the whole API layer. I close this issue in favor of #3395

**Comment by r-near** [comment]
Yes! Tagged enums would actually go a **long** way in generating clean, shareable types. Most of the ecosystem can't represent untagged enums cleanly, like we do in Rust.

**Comment by frol** [comment]
More context, just for the future reference: https://near.zulipchat.com/#narrow/channel/295302-general/topic/OpenRPC.3A.20What.20It.20Is.2C.20Where.20We.20Are.2C.20and.20Why.20It.20Matters/with/577046208
