### ISSUE TITLE
Redesign TX-status RPC to avoid confusion

### ISSUE THREAD

**Issue by frol** [near/nearcore#2194]
According to @evgenykuzyakov and @bowenwang1996, only Receipt Outcome can have logs, but not the Transaction Outcome. Currently, we reuse the Outcome type for both and this leads to some confusion. At the very least, we should hide the field on the RPC level.

**Comment by evgenykuzyakov** [comment]
@frol, do we prohibit receipt hash query through the `tx-status` RPC?

**Comment by frol** [comment]
@evgenykuzyakov Sorry, I don't quite get the question. Can you elaborate more?

**Comment by bowenwang1996** [comment]
@evgenykuzyakov yes it is prohibited

**Comment by evgenykuzyakov** [comment]
Ok. In the past `tx-status` RPC returned the results even if the given hash was a a receipt hash. Now it doesn't but instead hangs for X seconds until returning 502.

Filed this following issue: #2195

**Comment by nearmax** [comment]
Moving it to Mainnet release because it is going to be painful to remove post Mainnet. CC @ilblackdragon

**Comment by frol** [comment]
@evgenykuzyakov @bowenwang1996 I am trying to wrap my head around the ExecutionOutcome, and it seems that at least from the point of view of the currently implemented contracts, the log *can* be non-empty as it is literally one of the receipt outcomes:

https://github.com/nearprotocol/nearcore/blob/56622f45e20e91cc00a7d85227f8828c8af1d832/chain/chain/src/chain.rs#L1955

It seems that `transaction_output.outcome.gas_burnt` is also misleading, thus, the only useful fields are `receipt_ids` and `status`. Am I correct?

<details>
<summary>Sample transaction status output</summary>

```json
{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "receipts_outcome": [
            {
                "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
                "id": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd",
                "outcome": {
                    "gas_burnt": 924119500000,
                    "logs": [],
                    "receipt_ids": [],
                    "status": {
                        "SuccessValue": ""
                    }
                },
                "proof": [
                    {
                        "direction": "Left",
                        "hash": "82vrsjuJpRdqXax4ZX3ejjzbY2routMTqiNLphKBk28m"
                    }
                ]
            }
        ],
        "status": {
            "SuccessValue": ""
        },
        "transaction": {
            "actions": [
                {
                    "AddKey": {
                        "access_key": {
                            "nonce": 0,
                            "permission": {
                                "FunctionCall": {
                                    "allowance": "100000000000000000000",
                                    "method_names": [],
                                    "receiver_id": "test1586824920022380"
                                }
                            }
                        },
                        "public_key": "ed25519:ndTHtKtoJ9J8dCMmnhH74mNji1E8EtTHA6vq39vRQ94"
                    }
                }
            ],
            "hash": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
            "nonce": 1,
            "public_key": "ed25519:BBSheK56Dd7XtmTd2CS8X7DpTcwvmbuSKRkz85FcJGH7",
            "receiver_id": "test1586824920022781",
            "signature": "ed25519:5U4fNnXhmUw56km4mEjFjy2tWPViwcMF6SkrkKujphsfGBn4RtEUAwaPEUWqwXH7vFeVHurbxsmLAPhWFk7QmDsu",
            "signer_id": "test1586824920022781"
        },
        "transaction_outcome": {
            "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
            "id": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
            "outcome": {
                "gas_burnt": 924119500000,
                "logs": [],
                "receipt_ids": [
                    "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                ],
                "status": {
                    "SuccessReceiptId": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                }
            },
            "proof": [
                {
                    "direction": "Right",
                    "hash": "58XbhAhW971sCo1c3c3RR7bao7LDkXKgNHJLt3mKM4tK"
                }
            ]
        }
    }
}
```
</details>

**Comment by bowenwang1996** [comment]
yes logs are often empty. I am not sure what your question is.

**Comment by frol** [comment]
@bowenwang1996 

1. Can the logs in the `transaction_outcome.outcome.logs` be non-empty? (It was claimed that those are always empty, in which case we want to remove it to better encode the possible scenarios as one may expect those logs to include all the logs from all receipts)
2. What is the meaning of `transaction_outcome.outcome.gas_burnt`? It is not the total gas_burns for all the receipts as far as I know.
3. Should we better remove `transaction_outcome.outcome.gas_burnt` field?

**Comment by bowenwang1996** [comment]
> Can the logs in the transaction_outcome.outcome.logs be non-empty? (It was claimed that those are always empty, in which case we want to remove it to better encode the possible scenarios as one may expect those logs to include all the logs from all receipts)

It is always empty.

> What is the meaning of transaction_outcome.outcome.gas_burnt? It is not the total gas_burns for all the receipts as far as I know.

It is the cost of actions in the transaction I believe.

> Should we better remove transaction_outcome.outcome.gas_burnt field?

Why?

**Comment by frol** [comment]
> Why?

I vote for its removal since it is confusing, and to prove that let me quote your reply: "... I believe."

It seems that the user should count all the `gas_burnt` from the receipts to get the complete picture of the execution costs.

**Comment by bowenwang1996** [comment]
I see. I think it makes sense. @evgenykuzyakov what do you think?

**Comment by evgenykuzyakov** [comment]
gas burnt in the execution outcome for a transaction refers to the execution cost of the receipt creation. It's an actual gas amount.

**Comment by frol** [comment]
@evgenykuzyakov 

1. that is not obvious, and it is really misleading (which is "dangerous")
2. that is useless since it is incomplete

**Comment by evgenykuzyakov** [comment]
It's not part of the `gas_burnt` for any receipt. It's in addition to the gas burnt by receipts. Imagine a scenario, where you send a transaction to an account that doesn't exist. You have to pay a fee for sending this receipt before it arrives on a given shard, because validators on your shard are doing work for sending the receipt.
Now Validators on the receiving side also have to get a fee for executing the receipt.

**Comment by frol** [comment]
@evgenykuzyakov Do you want to say that the `gas_burnt` in the transaction outcome (924119500000) and `gas_burnt` in the first receipt output (924119500000 - the same value) should be summed up to get the total `gas_burnt`? (I am referring to the RPC response in my comment above: https://github.com/nearprotocol/nearcore/issues/2194#issuecomment-613180287)

**Comment by evgenykuzyakov** [comment]
Yes

**Comment by evgenykuzyakov** [comment]
Here is base for receipts:
```
      "action_receipt_creation_config": {
        "send_sir": 924119500000,
        "send_not_sir": 924119500000,
        "execution": 924119500000
      },
```

Both `send` and `execution` fees are the same.

But adding a key right now is free:
```
        "add_key_cost": {
          "full_access_cost": {
            "send_sir": 0,
            "send_not_sir": 0,
            "execution": 0
          },
          "function_call_cost": {
            "send_sir": 0,
            "send_not_sir": 0,
            "execution": 0
          },
          "function_call_cost_per_byte": {
            "send_sir": 37538150,
            "send_not_sir": 37538150,
            "execution": 37538150
          }
        },
```

Unless there are some method names.

**Comment by frol** [comment]
Ok, thanks for the clarification, I will think what I can come up with to make this API response useful (currently, it is super confusing).

How do you feel about the following set of changes:

1. do not hide the fact that there is this first receipt (include it on the list and just have the receipt ID in the transaction outcome)
2. don't include the [execution] outcome in the transaction outcome

Another problem I see is that the receipts list might be incomplete due to cross-shard calls. This incompleteness is invisible until it is too late (I learned about this state of things by accident). In my opinion, incomplete API is worse than a completely broken or non-existing one since it makes users false confident.

**Comment by evgenykuzyakov** [comment]
I guess it's always the following:
- transaction {
  gas_burnt,
  receipt_id
}
- One or many [receipt_id -> execution_outcome]

Every `ExecutionOutcome` contain list of `receipt_ids` that were spawned by this receipt. If a `receipt_id` is missing the corresponding `ExecutionOutcome` it means it's not processed yet.

How do you want to change it?

**Comment by frol** [comment]
@evgenykuzyakov @bowenwang1996 Here is the current `method=tx` response:

```js
{
    ...
    "result": {
        "receipts_outcome": [
            {
                "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
                "id": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd",
                "outcome": {
                    "gas_burnt": 924119500000,
                    "logs": [],
                    "receipt_ids": [],
                    "status": { "SuccessValue": "" }
                },
                "proof": [...]
            }
        ],
        "status": { "SuccessValue": "" },
        "transaction": {
            "actions": [
                {
                    "AddKey": {
                       ...
                    }
                }
            ],
            "hash": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
            ...
        },
        "transaction_outcome": {
            "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
            "id": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
            "outcome": {
                "gas_burnt": 924119500000,
                "logs": [],
                "receipt_ids": [
                    "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                ],
                "status": {
                    "SuccessReceiptId": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                }
            },
            "proof": [...]
        }
    }
}
```

I suggest moving `transaction_outcome` back to the `receipts_outcome` (is it true that the "transcation receipt" hash equals to the transaction hash?):

```js
{
    ...
    "result": {
        "receipts_outcome": [
            {
                "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
                "id": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
                "outcome": {
                    "gas_burnt": 924119500000,
                    "logs": [],
                    "receipt_ids": [
                        "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                    ],
                    "status": {
                        "SuccessReceiptId": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd"
                    }
                }
                "proof": [...]
            },
            {
                "block_hash": "8JEiwjAsZeE7Pqa6dM9MFJDqRzAuYpaeyw7zuPiPLTY4",
                "id": "B4jU4cjzdzrhxAgf5P5oPxUA2G8HmmG7wpeuijYqSVSd",
                "outcome": {
                    "gas_burnt": 924119500000,
                    "logs": [],
                    "receipt_ids": [],
                    "status": { "SuccessValue": "" }
                },
                "proof": [...]
            }
        ],
        "status": { "SuccessValue": "" },
        "transaction": {
            "actions": [
                {
                    "AddKey": {
                       ...
                    }
                }
            ],
            "hash": "3BCTSWsvPLQc8GsncosBwmdND28w8KV9LsMGj6bWudyQ",
            ...
        },
    }
}
```

**Comment by bowenwang1996** [comment]
> is it true that the "transcation receipt" hash equals to the transaction hash

Do you mean receipt id? It will never be the same as transaction hash.

**Comment by frol** [comment]
I am moving this issue to the Icebox as it is not a blocker for the mainnet and it makes sense to do a full response refactoring:

* Consider avoiding `transaction_outcome` in the first place and just let the structure to be simple receipts with outcomes + transaction info
* Use [Adjacently tagged enums representation](https://serde.rs/enum-representations.html) (specificatlly, for Status and Actions)

**Comment by frol** [comment]
There is nothing to be improved at this stage. We should improve the documentation: https://github.com/near/docs/issues/701
