### ISSUE TITLE
[Discussion] How to stop shard congestion attack

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#2196]
A shard can be attacked by continuously sending receipts to this shard through other shards.
The total cost of this attack doesn't increase by default, because the global gas_price doesn't go up with the current logic, because the total gas used doesn't go beyond the half of the entire system. This means the cost of the attack can be pretty low until the shard becomes completely clogged and can't recover.

This attack has the following problems to address:
- It can be executed in one block, because the chunks/shards are independent, the initial gas price for all transactions in one block will be low. We can increase the gas price on the next block, but all transactions in the first block will have low gas price. Those transactions during the same block produce a lot of receipts that are all going to a single shard, which will be congested for a while.
- If we raise the global gas price immediately after an attack, it means an attack on a single shard will influence the pricing of every other shard, so the cost of the network will depend on the most congested shard making other shards suffer from demand. This leads to a lower revenue for validators because of unsatisfied supply.
- If we don't raise the global gas price, but instead start decline transactions, then we need a way to know which transactions to decline. It's almost impossible to know which transactions are going to the attacked shard.
   - We can ask developers to tell which accounts the transactions is going to touch and decide at the chunk production time to include or not include given transaction. But it introduces additional burden on developers and makes it more complicated.
   - We can try to develop an algorithm that automatically blocks transactions, but it's probably can be abused on it own.
   - We can block most transactions, which would lead to lower global throughput, so it has the same unsatisfied supply issue as above.
- If we keep the gas price unaffected, but instead fail receipts. We can't fail a receipt once it's issued, otherwise the devx will be completely broken. There are a few ideas that might be combined to address the issue:
   - Delay outgoing receipts. Right now we only delay incoming receipts on the congested shard, but we can also delay receipts that are supposed to go to the congested shard. This doesn't change the cost of the attack, just helps the congested shard a little,
   - Introduce surge pricing for the cross-shard fees towards a congested shard. Instead of raising gas price globally, we can charge more gas for the receipts going towards the affected shard. It might have it's own pitfalls around valid transactions, but it will affect increase the cost of the attack if the attacker wants to continue blocking the same shard.
   - Fail a receipt after we know it goes to the affected shard. This will waste the compute we just did, but will give us an option to react. E.g. remember that this receipt is going to the affected shard. It doesn't solve the issue, but let us do something else with this receipt next time.
- Variable gas prices per shard. It's an alternation of the surge pricing. Makes a development more complicated, because now you need to worry about shards and their gas pricing:
   - If the gas has to be prepaid ahead of time, then you need to know which shards the transactions is going to touch and how much gas you need on every shard.
   - If the gas pricing is charged at the moment when the transaction is executed, then you have to prepay for gas at the highest gas price, making all transactions potentially expensive with unpredictable costs.
   - If the transaction can specify the max gas price for a receipt, it makes transactions like a Ethereum with premium gas pricing. Unclear what to do with receipts that can't be executed because the gas price is too low. They might be in the state forever and block certain transfers within a locked state indefinitely.

**Comment by bowenwang1996** [comment]
> This leads to a lower revenue for validators because of unsatisfied supply

While there might be fewer transactions, each transaction will cost more and since we split reward between validators, I don't think it necessarily lead to lower revenue for validators.

**Comment by nearmax** [comment]
@evgenykuzyakov did I understand your concern correctly, that adding dynamic gas after we have apps running static gas might break them and might even need an entire redesign, because it would break their composability?

**Comment by evgenykuzyakov** [comment]
That's right. Basically we need to add think about the idea of fee surge. Instead of designing around dynamic gas price, we should design around dynamic gas fees for cross-contract promises. This will stop the receipt from propagating towards the attacked shards and stop old transactions in the middle. If the attack wants to continue it would have to buy more gas which will increase overall gas demand and increase gas pricing which would stop the attack by making it more expensive.

It also doesn't affect regular transactions that might touch a given shard with complicated dynamic gas pricing. Instead the contract might fail before it completes a full transaction in the middle. 

If the safes were already implemented then they it would not result in the locked state. 
Before safes are implemented we should avoid having complicated composability (e.g. locking dependencies) and instead rely on the escrow model where you first have to transfer asset to the exchange (in the first transaction).  And the escrow contract should own both items before exchanging them between corresponding owners (the second transaction). Now if any of the transactions fails, the state is still valid.

**Comment by bowenwang1996** [comment]
The discussion happens here https://gov.near.org/t/gas-price-auction/1423 now. Closing this thread
