### ISSUE TITLE
Hash account ids in the Trie

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2215]
We need to prevent users from attacking the shard which they currently can if they create accounts with names `hello_aa`, `hello_aaa`, `hello_aaaa`, etc. This will create a deep trie that will be expensive to work with. Roughly 6 nodes of depth decrease the speed 4 times. So one can slow down the node approximately 40 times by creating 60 accounts using the above scheme.

To prevent this from happening we should be using hashes of the account ids, instead of the raw accounts in the trie. This can be fixed on the runtime level without modifications to the store/state crate.

**Comment by frol** [comment]
@nearmax @evgenykuzyakov Hmmmm, does this mean that Trie keys schema will get changed? This affects the `changes` API implementation since we store changes by simply prepending the Trie key with a block hash. It won't affect the exact matches for changes by a given account ID, but it will require some unknown amount of work for #2128.

**Comment by evgenykuzyakov** [comment]
Link: https://github.com/nearprotocol/NEPs/pull/39

**Comment by nearmax** [comment]
@frol It does add some work to #2128 , but please let's not wait for this to land go implement #2128 first and then adjust later.

I think it is not fundamentally different for when account ids are hashed or not. On DB level all changes are prefixed by the block id, so we can query all changes within the block and iterate over them. We can add an additional enum (u8) that we prepend between the block id prefix and the rest of the key.

**Comment by evgenykuzyakov** [comment]
@frol I'll try to make it in such a way that it doesn't affect your PR. The idea is to hash the `account_id` at key `key_for_column_account_id` method.
We might need to store `account_id` itself in the trie under column, so we can do reverse hash of a given key towards the `account_id`. It's only needed for `StateRecord` dumps.

**Comment by evgenykuzyakov** [comment]
Refactoring of storage keys might take longer

**Comment by vgrichina** [comment]
I don't think there is big enough improvement on how difficult it is to come up with de-generate prefixes with hashes, see:
https://commonwealth.im/near/proposal/discussion/225-iterators-and-trie-structure?comment=634

**Comment by nearmax** [comment]
As discussed our state trie remains trivially abusable even with hashing so I am moving this Epic to the Ice Box and removing from the Mainnet release. AFAIR @evgenykuzyakov also wanted to do the same.

**Comment by bowenwang1996** [comment]
Looks like no action items here. Closing
