### ISSUE TITLE
Upgrade rpctypegen to new Borsh Schema format

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2242]
[rpctypegen](https://github.com/nearprotocol/nearcore/blob/da9e48b359535d9f9f85dc314a10fdb69b114129/tools/rpctypegen/core/src/lib.rs) generates Borsh schema in TS format for all RPC errors.

Now that we have implemented `BorshSchema` macro in nearprotocol/borsh#57 and nearprotocol/borsh#56 we can use `#[derive(BorshSchema)]` to generate schema for RPC errors and reduce our code base. We would also need to do two more things:
* Switch nearlib to new Borsh Schema format that is slightly different from the one introduced by rpctypegen (this can be easily done after we upgrade borsh TS/JS to new Borsh Schema format, see: https://github.com/nearprotocol/nearlib/issues/252)
* Add a single executable in `nearcore/tools` that has a hardcoded list of error types. The executable would iterate over the error types and for each of them generate Borsh Schema using `BorshSchema` trait it then would dump the schema into a file that we can hardcode in nearlib.

**Comment by frol** [comment]
Borsh schema does not necessarily match the JSON schema (e.g. some values can be base64-encoded, some fields/enum variants are renamed, etc). Unfortunately, I don't think it is feasible to try to fit Borsh schema for JSON schema. Please, reopen if you think otherwise.

**Comment by nearmax** [comment]
Borsh schema is not Borsh-specific. We call it Borsh schema because it is defined in Borsh library but it can be used by many serializers. Our current schema generated by `rpctypegen` has nothing specific to JSON either. The point of the proposed changes is to reconcile the schemas that we currently use in nearlib. I am reopening this issue. However, I don't think it is blocking for the Mainnet. Therefore I am removing it from the Mainnet release and moving it to IceBox. I am also doing the same with the Epic.

**Comment by frol** [comment]
Nice! Then, for the future context, we need to make sure that whatever schema-generation we use should respect the serialization annotations (currently, we extensively use serde renamings, enum representations, and skips). There are OpenAPI spec generators for serde out there for inspiration: https://docs.rs/rweb/0.4.3/rweb/openapi/index.html

**Comment by bowenwang1996** [comment]
looks like a duplicate of #1972
