### ISSUE TITLE
Expose the reason for ValidatorAccountsUpdate

### ISSUE THREAD

**Issue by frol** [near/nearcore#2246]
Currently, when rewards are allocated, stakes are returned, and validators get slashed, we only observe the balance state change and track all those changes with a single `ValidatorAccountsUpdate` marker:

https://github.com/nearprotocol/nearcore/blob/697d15debabcb69c6bea286329f0aa0d2a8e7284/runtime/runtime/src/lib.rs#L917

Thus, we don't have enough granularity. One can deduce whether that was a reward by inspecting the locked amount (it gets increased with a reward). @bowenwang1996 suggested introducing details:

```rust
ValidatorAccountUpdate {
    reason: ValidatorAccountUpdateType,
    liquid_balance_change: BalanceChange,
    locked_balance_change: BalanceChange
}
```

for `StateChangeCause`:

https://github.com/nearprotocol/nearcore/blob/6d07a2d408a58ae1feeefecb815ad7351cdc6086/core/primitives/src/types.rs#L131

that will mean that we will have to commit the changes per individual account change. However, two questions are not clear to me:

* it changes the behavior for early-return since currently we only commit when no errors happen (BTW, currently it seems that we can have left-over changes in the state, but it seems that it gets discarded anyway)
* performance implications

**Comment by nearmax** [comment]
With `StateChangeCause` we should not be specifying information that can be deduced from the state itself. As we discussed with what we allow in RPC API -- if information can be easily deduced then we do not expose it. I suggest we do not implement this feature request and close this issue. WDYT?

**Comment by frol** [comment]
@nearmax Yeah, I recall our conversation about what we add and what we don't. However, in this case, I would not say that it is a reliable way to learn what is going on. After a reward is allocated, there is the following code:

https://github.com/nearprotocol/nearcore/blob/697d15debabcb69c6bea286329f0aa0d2a8e7284/runtime/runtime/src/lib.rs#L841-L853

This means that not only the locked amount should be checked, but also the balance amount. Thus, it requires consulting with the code and ensure that nothing gets there.

As far as I can tell, to compute the reward you have to do:

```python
amount_diff = new_amount - amount_on_the_previous_block
locked_diff = new_locked - locked_on_the_previous_block
return locked_diff + amount_diff
```

And if that amount change is positive, that is the reward. Otherwise, it is a punishment for slashing behavior. At the very least, we should document this. WDYT?

**Comment by frol** [comment]
I failed to deliver the main idea:

Currently, an external observer has no way to learn WHY the balance has changed, and the implementation of updating the validator balances looked to me as such that a node may change balances arbitrarily (since there are no associated transactions/receipts), though, once I learned more about the way NEAR operates with the balances (it keeps them in the state, so every node in a shard has to have the same balances [computed or synced] to have the same state to agree on the next chunk) I don't have that misconception anymore; yet, the external observer has to reimplement the whole internal logic of this method and keep it up-to-dated to properly deduce the update reasons.

Thus, I still think it is worth to be implemented. All the performance implications should be resolved with a feature-flag, so the changes tracking is completely disabled by default.

**Comment by ilblackdragon** [comment]
For your concerns @frol:
- If we have failures in the Validator Info update - we probably should fail block production overall. E.g. that function should not be early-returning in normal case.
 - There is no performance overhead - committing is a cheap operation of moving data from one collection to another.

**Comment by frol** [comment]
> Do we have requests for this info?

Yes, it is a request from one of our partners.

> We can add it later (hence Icebox)

Agree

> There is no performance overhead - committing is a cheap operation of moving data from one collection to another.

There is still some performance overhead, but it is probably really unnoticeable given the relatively small number of validator accounts.

**Comment by bowenwang1996** [comment]
@frol is this still important?

**Comment by frol** [comment]
I think it is not important these days since we have extensively covered all the balance-changing scenarios with documentation: https://github.com/telezhnaya/docs/blob/b628ebd23a8604a8f0393e2704ee93d661dda9bd/docs/tokens/balances.md (kudos to @telezhnaya!)
