### ISSUE TITLE
Docker build with a modified in build version

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#2267]
In a fresh checkout nearcore, and `make`, it builds `nearcore` docker image, Then run `docker run nearcore near --version`, it shows: `near x.y.z (build <commit>-modified)`. There should be no `modified` there

**Comment by bowenwang1996** [comment]
@ailisp is this still relevant?

**Comment by ailisp** [comment]
Just finished a docker build, looks it's fixed!
