### ISSUE TITLE
Prepare for launch

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2289]
This is catch all epic for preparing for launch of MainNet v1.

**Comment by bowenwang1996** [comment]
Why is genesis contract not part of this epic?

**Comment by ilblackdragon** [comment]
What do you mean by genesis contract?
Do you mean lock up contracts? There is separate epic https://github.com/nearprotocol/nearcore/issues/1990

**Comment by bowenwang1996** [comment]
Okay. I would expect this epic to include everything but it doesn't seem to be the case.

**Comment by bowenwang1996** [comment]
Obsolete
