### ISSUE TITLE
rpc requests interfere with block production

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2313]
We have seen multiple times now that on testnet even a moderate amount of rpc requests can cause block production to slow down, which is quite undesirable. We need to understand the root cause and whether it is easily solvable. The last resort would be to disable rpc on block producing nodes.

**Comment by bowenwang1996** [comment]
@frol Do you think that the slow down might be related to the fact that view client and client shares the underlying database and block production needs to write to the database and therefore might block view client from reading and vice versa?

**Comment by frol** [comment]
It was my initial guess, but it seems that the most severe slowdown is happening without observable resource load, and especially with the view method calls, so I guess that WASM execution locks the whole DB down. On the other hand, Explorer backend does not use view method calls, but still brings the block production down, and it only uses blocks and chunks APIs. Chunks API exposes a list of transactions and a list of receipts, and my guess is that this fetching is slow. Also, we serialize into JSON synchronously in the JSON RPC handler, and it blocks the whole reactor, we need to offload this to a separate worker, I would say.

**Comment by bowenwang1996** [comment]
> it only uses blocks and chunks APIs

I think that is sufficient to slow down block production. Block production needs to write chunk and block to the database but if there are a lot of read requests it might be blocking.

> we serialize into JSON synchronously in the JSON RPC handler, and it blocks the whole reactor

But this shouldn't affect block production in anyway. Rpc handler is running in a separate thread.

**Comment by frol** [comment]
/me Merging external conversation:

@SkidanovAlex said:
> could the RPC slowing down block production be due to rocksdb?
> If `view_client` tries to read from database aggressively, it could potentially significantly slow down writes to the same database by `client`

**Comment by frol** [comment]
Can we tweak RocksDB to prioritize writes over reads?

**Comment by bowenwang1996** [comment]
@ailisp does RocksDB support this?

**Comment by nearmax** [comment]
We should actually track the slowness down to the RocksDB and then tweak it. There are other things upstream that we should check: are there any actors or channels that are blocking the block production? Do we have a lock or a mutex guarding the access to state?

**Comment by bowenwang1996** [comment]
Ah I just realized that the rpc requests for both block and chunk needs to go through epoch manager, which is behind a lock. That might be the bottleneck. @frol

**Comment by bowenwang1996** [comment]
It is actually quite problematic. Even though epoch manager is behind a `RwLock`, most methods that access epoch manager takes the write lock due to the need to update cache internally. That means rpc handler cannot serve multiple requests concurrently even if there is no block production. I think for now we will not enable rpc on block producing nodes, but that still doesn't solve the problem entirely.

**Comment by nearmax** [comment]
So cache has it is own Mutex inside, so we don't actually need to hold the write lock on cache when doing an immutable access to epoch manager. Unfortunately, if we stop write-locking epoch manager on reads it will surface race conditions that we currently have in it. For example, this function will become racy if it is used concurrently: https://github.com/nearprotocol/nearcore/blob/24db970ae8f127862ca478bc77d35c3a168f687d/chain/epoch_manager/src/lib.rs#L920

**Comment by nearmax** [comment]
But we should make sure that epoch manager is actually the bottleneck here. We can do it by replacing epoch manager with some hardcoded data and then run RPC load testing against the node.

**Comment by bowenwang1996** [comment]
I don't see an easy solution here. Even non block producing nodes need to write to epoch manager when it processes blocks so it cannot serve a lot of reads without blocking. But yeah we should benchmark it. Also is there a reason that we must have block producer associated with the block in rpc response? @frol

**Comment by frol** [comment]
> Also is there a reason that we must have block producer associated with the block in rpc response?

You lost me here. I have no idea about block producer. /cc @ilblackdragon

**Comment by bowenwang1996** [comment]
@frol I was talking about https://github.com/nearprotocol/nearcore/blob/7b56f548c5d841353cd3935f316d9abf752f4d7f/chain/client/src/view_client.rs#L367. It does blame to @ilblackdragon though 🤔

**Comment by nearmax** [comment]
As discussed with @SkidanovAlex I am unassigning @frol since he does not have spare cycles to work on this issue and this issue requires an intimate understanding of how actors an mutexes are orchestrated in chain.

**Comment by ailisp** [comment]
The benchmark of @nearmax had in runtime/storage level load test would be a good one to tune rocksdb. Although It looks quite fast when running locally that doesn't seem to be a bottleneck. 
One obvious improvement we should make is upgrade our node use ssd. All our node is using hdd but current set of rocksdb config is copied from parity's ssd one. And in one disk benchmark i made in gcloud it's at least 20x slower than my local disk.
After that I plan to have some integration test to simulate rocksdb reads similar to a read world node and see if need more tuning

**Comment by ailisp** [comment]
@bowenwang1996 read fast should be the default. There's a quite detailed tuning guide: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide but i didn't have time to perform. Plan to write some test simulate rocksdb reads similar to a read world node as a benchmark and tune to improve that next month

**Comment by nearmax** [comment]
We discussed with @frol offline that this issues conflates two very separate problems:
* RPC is resource heavy;
* RPC is blocking block production.

I think we should be focusing on the latter rather than the former. Even if our RPC was extremely resource hungry and not parallelized we still should be able to make sure it does not interfere with block production. If let's say we had an actor guarding the state and the runtime which both `ViewClientActor` and `ClientActor` were using to communicate with state and runtime then this actor could establish priority by first polling from the channel associated with `ClientActor` and only polling from `ViewClientActor` if there are currently no messages in `ClientActor` channel. In the future we are going to have even more rules about the priorities (e.g. block production has higher priority than block import) and we would have to separate these into actors too and poll from them in strict order.

**Comment by ilblackdragon** [comment]
@bowenwang1996 There are no other way to know who produced block - as we don't expose the block production schedule from validators. If want to optimize this, we can create a copy of EpochManager in ViewNightshadeRuntime...

I think we should though postpone this issue for later. And instead now run block producer without RPC open and RPC open on a non block producing nodes. This will better represent MainNet environment, where we for sure won't have validator node serving RPCs for our "infura".

**Comment by frol** [comment]
Given all the info, I agree with @ilblackdragon. This issue should go into icebox, but here are the actions I would expect given the current knowledge:

* Deploy betanet -> testnet the same way we expect it running on mainnet (using non block producing nodes as firewall nodes)
* Document this setup as a best practice deployment

**Comment by bowenwang1996** [comment]
Okay looks like this doesn't need to be resolved right now. We will move to serving rpc only from nonvalidating nodes.

**Comment by bowenwang1996** [comment]
There are still some shared locks with epoch manager, but it is rather low impact

**Comment by bowenwang1996** [comment]
> There are still some shared locks with epoch manager, but it is rather low impact

Will merge this with #2745
