### ISSUE TITLE
Review interdepdendencies

### ISSUE THREAD

**Issue by frol** [near/nearcore#2315]
There are quite a few circular dependencies in nearcore crates, which leads to confusion and bad separation of concerns.

The major one is the `neard` (previously known as `near`) crate, which should serve as a binary-only crate, but suddenly, quite a few other crates depend on it right now.

**Comment by bowenwang1996** [comment]
> The major one is the neard (previously known as near) crate, which should serve as a binary-only crate, but suddenly, quite a few other crates depend on it right now.

neard is refactored and we have neard and nearcore as separate crates now. The dependency issue is now tracked in #4357
