### ISSUE TITLE
Chain Stability Push

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2323]
This issue is to track progress on internal review, stabilization and writing a spec for chain code.

The chain code is roughly separated into five components. For each component there are two tracking work items: one for writing the specification, and one for reviewing the code and writing new tests:

* Block production, Doomslug and Finality Gadget: 
  - https://github.com/nearprotocol/NEPs/issues/51 
  - https://github.com/nearprotocol/nearcore/issues/2310
* Epoch Manager: 
  - https://github.com/nearprotocol/NEPs/issues/52 
  - https://github.com/nearprotocol/nearcore/issues/2311
* Chunk production and distribution: 
  - https://github.com/nearprotocol/NEPs/issues/49 
  - https://github.com/nearprotocol/nearcore/issues/2308
* Network: 
  - https://github.com/nearprotocol/NEPs/issues/50 
  - https://github.com/nearprotocol/nearcore/issues/2309
* Syncing: 
  - https://github.com/nearprotocol/NEPs/issues/48 
  - https://github.com/nearprotocol/nearcore/issues/2307
* GC:
  - nearprotocol/NEPs#61
  - #2596

The review work items are expected to get weekly updates on the review progress each Friday.

This issue will contain short summaries of such updates.

**Comment by ailisp** [comment]
Add one:
- GC:
    -  nearprotocol/NEPs#61
    -  #2596

**Comment by bowenwang1996** [comment]
Outdated
