### ISSUE TITLE
high cpu usage when there are no transactions

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2325]
When there are 100 validators running in the network, the cpu usage is roughly 50% without any transactions, which seems unreasonable. We should investigate what is consuming a lot cpu and fix/optimize it.

**Comment by bowenwang1996** [comment]
@ailisp @frol what tool would you recommend to profile cpu usage?

**Comment by ailisp** [comment]
recently i find this tool maybe a faster and better alternative than valgrind. https://github.com/AtheMathmo/cpuprofiler
And classic valgrind cachegrind/callgrind: https://github.com/svenstaro/cargo-profiler but i didn't have luck to run it with nearcore

**Comment by frol** [comment]
Try https://github.com/killercup/cargo-flamegraph

**Comment by frol** [comment]
Try https://github.com/flamegraph-rs/flamegraph (updated link)

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek we should start looking into cpu profiling.
