### ISSUE TITLE
[Discussion] Collected metrics from network

### ISSUE THREAD

**Issue by mfornet** [near/nearcore#2335]
This are the metrics collected from 100 nodes running on google-cloud after few hours. [See live dashboard](https://marcel.o-for.net/near/). Check #2239 to read what every graphic means.

- The graph diameter is 2 (which is the best we can achieve), all nodes have at most 40 direct connections and at least 35 (which is expected in a healthy system). 

<img width="1669" alt="Screen Shot 2020-03-27 at 5 47 04 PM" src="https://user-images.githubusercontent.com/28708963/77803289-272bcd80-7053-11ea-8a61-0bd521781b3f.png">

- The latency matrix shows the average time in milliseconds among ping message from node A to node B and going back (it is the round trip) so divided by two is the average time a small package take to go from A to B.  For different peers we see that minimum is 24ms and maximum is 768ms (round trip). Latency is measured between all nodes (even between those that don't have direct connection).

- Light yellow square in bytes/total matrix implies that there is no transfer so far between this pair (because they haven't been direct peers at any moment so far). Number of sent messages goes from 10M to 26M and number of received Mb goes from 35Mb to 75Mb (after initial ~2hours).

<img width="1618" alt="Screen Shot 2020-03-27 at 5 47 33 PM" src="https://user-images.githubusercontent.com/28708963/77803599-e1233980-7053-11ea-9344-e000782b69f3.png">

- Number of bytes received by type of message for peer0. IMPORTANT: I think something is going very wrong with `PartialEncodedChunkRequest` message since it has huge impact on the traffic (both in number of message sent and total size of these message)  while I expect it shouldn't.

<img width="1437" alt="Screen Shot 2020-03-27 at 5 47 44 PM" src="https://user-images.githubusercontent.com/28708963/77803893-a40b7700-7054-11ea-840b-e191eaff681b.png">

- Total package sent to different peers looks good (as it is balanced).

<img width="1510" alt="Screen Shot 2020-03-27 at 5 47 53 PM" src="https://user-images.githubusercontent.com/28708963/77804199-5e02e300-7055-11ea-8d97-3413b07e3e2b.png">

This a follow up of #2239 and #1543 (closing the latter, let's open new issue if we need new metrics).

**Comment by bowenwang1996** [comment]
There should be quite a few `PartialEncodedChunkRequest` messages. It's how the system works. How many shards did you run?

**Comment by bowenwang1996** [comment]
Can you increase `chunk_request_retry_period` to 400ms and `CHUNK_REQUEST_RETRY_MS` to 300ms?

**Comment by mfornet** [comment]
@bowenwang1996 I launched the network again with new parameters.  `PartialEncodedChunkRequest` are still consuming large percent of the bandwidth, but this time 34% instead of 41%.

**Comment by bowenwang1996** [comment]
@mfornet which commit are your running the nodes with?

**Comment by bowenwang1996** [comment]
looks like no action items here. Closing
