### ISSUE TITLE
Phase 1 Launch Criteria

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2381]
Update by @nearmax : The following process was proposed by @ilblackdragon . It should be performed before every release. However, I propose we use it as a criteria for launching the Phase 1. Currently our criteria for launching Phase X, besides feature completeness, is observing the network and launching if it is stable for at least Y days. This method is not reliable, since it depends on the load of the network and the type of the traffic during these days. Instead we need to have a reproducible criteria for launching: for instance spinning up 100 nodes and hammering them with either synthetic traffic (financial transactions, contract deployments, creations/deletions of accounts/access keys, staking transactions, calls to core contracts) or real traffic that we have pre-recorded. If system is not failing and is maintaining the minimum set TPS we green light the launch/release.

Before every testnet release (merge beta into stable), we should have test for stability and throughput of the network as a whole. I propose we do the following:
* Spin up 100 validating nodes in different geographical locations and on different cloud providers (gcloud, aws, azure, etc) to mimic the real-world distribution of our network. 
* Keep the network under moderate load (100tps for example) and make sure block speed does not drop below certain threshold (we need some data to establish SLA) and the cpu/memory/network usages are normal.
* Loadtesting the network to see the maximum tps the network can handle. Once we have some data collected, we can establish SLA on maximum throughput as well.

Originally was body of #1634 but that is an epic for collecting issues around stability and this is more related to releases.

**Comment by SkidanovAlex** [comment]
The work above is done as part of mocknet testing. The performance is tracked in #3068.

Currently the launch criteria is defined as having no issues on testnet and betanet for a week.

**Comment by vgrichina** [comment]
> Keep the network under moderate load (100tps for example) and make sure block speed does not drop below certain threshold (we need some data to establish SLA) and the cpu/memory/network usages are normal.

I think we need to keep this constantly running for both betanet and testnet.

**Comment by damons** [comment]
Are we going to do what the description suggests?  i.e., Are we spinning up 100 validating nodes, loading up with 100tps, etc.?  If so, when is this happening?

**Comment by bowenwang1996** [comment]
We are running mocknet with 50 validators and loading it with much higher tps (500). We can change to 100 nodes if needed.

**Comment by bowenwang1996** [comment]
Outdated
