### ISSUE TITLE
near-runtime-standalone should be published to crates.io and not use rocksdb

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2433]
We should examine dependencies of the `runtime` crate and `near-runtime-standalone` and refactor them in such way that we can publish them to crates.io.

We also should be using `TestDB` instead of the rocksdb.

This is not critical for the Mainnet or for using `near-runtime-standalone` in the AssemblyScript tests.

**Comment by bowenwang1996** [comment]
I believe this is already done. Please reopen if it is not
