### ISSUE TITLE
AssemblyScript tests should be using `near-runtime-standalone`

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2434]
To make sure AS tests can test for cross-contract calls and interactions with the blockchain, they should be using `near-runtime-standalone`. At the beginning `near-runtime-standalone` will not be compiled to Wasm but it would still be possible to use it as a command-line tool that has JSON input and output.

This will require adding a bunch of the glue code to interact with the command line tool.

**Comment by bowenwang1996** [comment]
I believe it is outdated given that we have the simulator now
