### ISSUE TITLE
Staking pool contract. Nightly test

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2436]
Implement a nightly test for staking & delegation contract https://github.com/near/staking-contract/.

Scenario:
 - Start a singe node
 - Deploy staking contract
 - Start another node that uses this staking contract.
 - Delegate funds enough to stake
 - Validate that second node is staking 
 - Undelegate funds
 - Second node stops staking
 - Funds received back by delegator contain correct amount including rewards.

**Comment by bowenwang1996** [comment]
@evgenykuzyakov this is done right?

**Comment by bowenwang1996** [comment]
Obsolete
