### ISSUE TITLE
State sync can potentially bring down a node

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2512]
State sync is quite resource intensive, especially for the node that is being synced from. I think ~5 peers syncing from the same node is probably sufficient to make the node stall or crash it entirely, which gives a potential vector of attack to the validating nodes. We should consider limiting the number of peers that can do state sync at a time.

**Comment by Kouprin** [comment]
We should discuss and choose the most preferable way for resolving this. @mfornet could you please tell us which % of network use StateResponse queries? I want to figure out where is a bottleneck.
There are several ideas we can implement and combine together:
1. **Caching State Headers and Parts.** As Sync Hash may be only the very beginning of the epoch, caching may work perfectly for not recalculating State Header and Parts. This solves CPU part of the problem.
2. **Limiting number of peers.** We can automatically reject all State Sync queries for newcomers if there are more than MAX_STATE_SYNC_PEERS in last 60 seconds.
3. **Limiting number of State Responses.** We can not answer for any State Request which comes in less than 5 seconds after the previous one.
4. **Smart way of choosing peers to allow Syncing, State Sync Manager.** Some malicious nodes can attack us by sending lots of State Requests. We may want to pessimize them and prioritize new ones.
5. **Add StateSyncClient and delegate to it all State queries.** It will help to unleash ViewClient.

@mfornet @bowenwang1996 @SkidanovAlex WDYT?

**Comment by bowenwang1996** [comment]
I mostly agree with what you propose, but I think there is no need to do 5 right now unless we observe view client starving because 1) validating node will not serve rpc so view client is mostly free and 2) we mostly sync from peers that are validators.

**Comment by mfornet** [comment]
Added heuristic proposed by @SkidanovAlex  (https://github.com/nearprotocol/nearcore/pull/2714#issuecomment-634783718) about limiting the number of state part request while syncing in #2515 . Not banning for nodes that try to abuse yet, but doing it is "slightly harder" since we are caching parts now.

**Comment by mfornet** [comment]
This was fixed in #2515

**Comment by bowenwang1996** [comment]
Happened on testnet again. The node is syncing has a sudden surge in memory usage and crashes due to oom

**Comment by bowenwang1996** [comment]
We implemented throttling on network and also the number of state part to respond within a minute. Since then we have not observed this again
