### ISSUE TITLE
Need to add `transferable_amount` to host methods

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#2516]
Because of the state staking, it's now hard to know what's the amount of tokens can be transferred out from the account without triggering the staked storage limits. It's desirable to have it within the contract to avoid function calls failing.

I suggest to introduce `transferable_amount` which is the amount of tokens that can be transferred out from the account using `transfer` action without failing the function call.

**Comment by bowenwang1996** [comment]
@evgenykuzyakov do we still want this?

**Comment by evgenykuzyakov** [comment]
Yes

**Comment by bowenwang1996** [comment]
Duplicate of #1738
