### ISSUE TITLE
Investigate rocksdb cache size

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2526]
On testnet I observe that rocksdb alone consumes more than 2GB of memory. We need to understand the exact cache size of rocksdb under our current configuration and adjust it if necessary. Related to https://github.com/nearprotocol/nearcore/issues/1782

**Comment by nearmax** [comment]
It might not be the cache size issue. Rocksdb is using separate workers for compression they might be using this memory.

**Comment by ilblackdragon** [comment]
We should check what others are doing, for example - https://github.com/nervosnetwork/ckb/pull/2036

**Comment by ailisp** [comment]
> We should check what others are doing, for example - nervosnetwork/ckb#2036

so far our configuration is mostly copied from parity's. I found the major issue is rocksdb cache size * num of column families and we have much more column families so it should be limited accordingly. Reading to see what else i can tweak.

**Comment by bowenwang1996** [comment]
We figured out the memory issue caused by rockdb cache size misconfiguration and have already fixed it
