### ISSUE TITLE
Nightly failure: basic tests fail

### ISSUE THREAD

**Issue by SkidanovAlex** [near/nearcore#2555]
Earlier runs:

churn_attack:
http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_072213

test_validator_kickout:
http://nightly.neartest.com/run/1aea93d3cbcc83e45c84b533f9746527ec7caabc_200427_205649/basic/basic/stdout

All the recent runs fail the same way:

test_sync_from_archival_node:
http://nightly.neartest.com/run/67104c495994de5723804c2a22b59f54cf531680_200427_171952/basic/basic/stdout
http://nightly.neartest.com/run/b693daeca9a871c0fd96cf9960551a047597c403_200427_140713/basic/basic/stdout
http://nightly.neartest.com/run/b693daeca9a871c0fd96cf9960551a047597c403_200427_105513/basic/basic/stdout

**Comment by damons** [comment]
Can we get an estimate?

**Comment by bowenwang1996** [comment]
@damons The overall estimate is done in the epic #2400.

**Comment by chefsale** [comment]
@bowenwang1996 this can be closed?
