### ISSUE TITLE
No way to tell if account is configured properly for node to become validator

### ISSUE THREAD

**Issue by vgrichina** [near/nearcore#2600]
When I launch `nearup betanet` there is:
1) No detailed instructions for me on what to do to become validator. Instead of `Stake for user 'vlad-validator.test' with 'ed25519:3zvhMcdSswKvGyjYBqEZoXascpiVL85ZHvQJDTxZ2G8x'`  there can be copy-pastable near-shell command, so that it is hard to mess up
2) No indication of whether current state is ok for becoming validator. I can stake too small amount of tokens, I can stake with a wrong key – there's going to be no indication anywhere. I'll have to wait until next epoch and notice that there is no `V` letter to understand that I failed and after that there is still no easy way to figure out why.

**Comment by vgrichina** [comment]
Proposed solution to 2:

Looks like we cannot report error on `near stake` (which makes sense) – however node I'm running can be checking status of account every once in a while (important that it's much more frequent than epoch) and display errors (with suggestions on how to fix) if not staked properly.

**Comment by bowenwang1996** [comment]
There is this rpc that you can use for now https://docs.nearprotocol.com/docs/interaction/rpc and I believe there is some work on near-shell side to provide better tooling for validators to check their status.

**Comment by jimmy3dita** [comment]
Vlad, give a look here: https://github.com/nearprotocol/stakewars/blob/new-readme/challenges/challenge002.md#heads-up
Let me know if it helps. The issue is that you don't want to run near shell (and its authorized keys) on the validator machine - so you can't really script the `account_id` and the `validator_key` in the staking pool call.

By now, you might generate a new keypair on your near shell machine, and copy/paste it in the `~/.near/betanet/` folder of your node before your start to sync it

**Comment by vgrichina** [comment]
> The issue is that you don't want to run near shell (and its authorized keys) on the validator machine - so you can't really script the account_id and the validator_key in the staking pool call.

Not sure how does it relate to described issue. I don't expect to run near-shell on node. I just expect node to give me useful info on both how to stake and on whether everything is ready for the node to become validator.

**Comment by jimmy3dita** [comment]
I never said to run near-shell on a validator machine. From what I know, it's possible to generate a key with the command `near key`, and transfer the generated json file to the validator machine, in the config folder.
The very same key would then be used to issue staking transactions and/or deploy the staking pool - solving at once two problems:
1. avoid the (today frequent) mistakes of using the wrong validator key in the staking transaction
2. launch the node from a file that is generated by the administrator and not pulled out from "cattle" servers

I suppose that any additional information can be extracted from running nearup in `--verbose` mode - we can eventually introduce an integer from 0 to 5 to it, to decide how much should be sent to the log

**Comment by vgrichina** [comment]
> I never said to run near-shell on a validator machine. 

I was referring to

> The issue is that you don't want to run near shell (and its authorized keys) on the validator machine - so you can't really script the account_id and the validator_key in the staking pool call.

**Comment by jimmy3dita** [comment]
I published this troubleshooting guide, and step 1 explains how to see if the node is correctly configured or not: https://github.com/nearprotocol/stakewars/blob/troubleshoot-file/troubleshooting.md

The solution from what you say is that we could print at nearup start the command to copy and paste to configure the pool. It's a great shortcut, but I think it's defeating the benefit of having competent validators who know keys, accounts and staking principles well

**Comment by vgrichina** [comment]
> The solution from what you say is that we could print at nearup start the command to copy and paste to configure the pool. 

No, main point I'm making that staking/validation process should be clearly observable from our tools. When some action doesn't succeed – error should be returned to the user vs requiring user to scout for all potential reasons for error.

E.g. I made mistake of specifying too small stake today and I only realized what is wrong because community members in Discord explained what's going on.

>  but I think it's defeating the benefit of having competent validators who know keys, accounts and staking principles well

This is interesting way to look at it, but right now we set the bar so high that NEAR team members need to struggle when setting up validator node. I already got stuck in multiple different ways when trying to run a node. I'm also having terrible experience keeping it online, as I have to restake after some arbitrary events.
  
Don't think that even competent validators want to waste their time figuring out these kinks with NEAR vs just getting proper error message that makes it clear where to dig. We should be adjusting our tooling in direction making it easy for everyone to become competent validator, especially as we are going to need 10x–100x more validators when number of shards get increased.

**Comment by bowenwang1996** [comment]
> I made mistake of specifying too small stake today and I only realized what is wrong because community members in Discord explained what's going on.

Unfortunately for this issue specifically we cannot return an error message because when you stake, it is impossible to determine the final seat price.

**Comment by bowenwang1996** [comment]
Duplicate of #3526
