### ISSUE TITLE
Migration instructions are outdated

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2607]
https://www.notion.so/nearprotocol/TestNet-Maintenance-668aee9f4c6f4fc2997b18a368dc3fd2#befda596e1c84d5381cc4f2aaddda24a is outdated, specifically section "Hard fork". For example `scripts/new-genesis-from-existing-state.sh` does not exist.

This is blocking @olonho from migrating to new fees, because we need to try running migration scripts locally, for which we need to dump the state.

**Comment by bowenwang1996** [comment]
@nearmax I'll fix it on the documentation side. The way to do it is to run `scripts/state/update_res.py`. Also CI checks for state migration automatically so you can easily see whether something went wrong.

**Comment by bowenwang1996** [comment]
I believe this is no longer relevant because now we need to do protocol upgrades to update the fees
