### ISSUE TITLE
Refactor Arc in storage

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#2639]
Storage classes use a lot of `Arc` (`ShardTries`, `Trie`, `Store`, `Database`), here are some ideas for a refactor:
- make `Trie` stateless - it just adds methods for `TrieStorage` which has an `Arc` inside
- `TrieStorage` has `Arc<Store>` and `Store` has `Arc<dyn Database>` - sounds like `Store` can be copyable.
-  `TrieUpdate` has a shared pointer to `Trie`, but can potentially be refactored to a reference with a lifetime parameter

**Comment by bowenwang1996** [comment]
Duplicate of #4837
