### ISSUE TITLE
near-primitives should not depend on near-vm-errors

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2652]
Currently `near-primitives` depends on `near-vm-errors` for some error type, which doesn't make much sense since in general, primitives is supposed to be the common denominator of crates in runtime and chain, so having it depend on something inside `runtime` is paradoxical.

**Comment by nearmax** [comment]
Overall, our primitives crate should be cut into smaller encapsulated crates. E.g. RPC-specific primitives do not need to live with other primitives. It will however create dependencies between primitives crates, e.g. rpc-primitives will depend on chain-primitives. So dependencies do make sense to me.

Especially when it comes to errors. Our error type is a large hierarchically composed structure that includes errors from all kind of places in our code base: storage, runtime, etc.

**Comment by bowenwang1996** [comment]
I believe this is done with the introduction of primitives-core
