### ISSUE TITLE
OpenRPC Support

### ISSUE THREAD

**Issue by shanejonas** [near/nearcore#2656]
Since this project uses JSON-RPC, I think this project could benefit from integration with OpenRPC which provides a base foundation for service discovery and tooling such as documentation and client generation for JSON-RPC akin to OpenAPI/Swagger.

Here is an example of an ethereum node with the OpenRPC playground, it gets the OpenRPC Document via calling the [rpc.discover](https://spec.open-rpc.org/#service-discovery-method) method:

https://playground.open-rpc.org/?schemaUrl=https://services.jade.builders/core-geth/mainnet/1.11.2

Let me know how I can help.

**Comment by nearmax** [comment]
Thank you for the suggestion we will revisit it once we are through the Phase 2 launch, see our timeline: https://near.org/blog/near-mainnet-genesis/
