### ISSUE TITLE
Spec describing state machine of staking/locking/unstaking transitions

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2667]
AFAIR, when @ilblackdragon drew it on the whiteboard the state machine was quite non-trivial. While audit company might not need to understand all of it to correctly review the staking pool, they might need to understand some parts. We might want to have this spec before Phase 1 launch for our own sake to avoid bugs, because currently this knowledge is only in the heads of @mikhailOK , @bowenwang1996 , and @ilblackdragon . While we need everyone to be able to understand it, including @jimmy3dita and @evgenykuzyakov .

Assigning it to @bowenwang1996 since I don't know who would be better person to work on it @bowenwang1996  or @mikhailOK . @bowenwang1996 could you please share your thoughts about this issue and set the estimate?

**Comment by bowenwang1996** [comment]
Epoch manager spec: https://github.com/near/NEPs/tree/master/specs/BlockchainLayer/EpochManager
