### ISSUE TITLE
Expose more information in logs for validation nodes

### ISSUE THREAD

**Issue by frol** [near/nearcore#2690]
It would be helpful to have more insight into the validation state online instead of waiting for epochs to learn your status.

I think we can provide information about the number of expected and produced blocks, and warnings about the ban/kick-out with an explanation as to why the node is going to be kicked out.

**Comment by bowenwang1996** [comment]
This can be fully done through rpc. I don't see any actionable item here for nearcore.

**Comment by frol** [comment]
Actionable item: add a log indicating a reason for a kick-out, so if the human was asleep and did not query RPC for the kick-out reason from `validators` RPC (`prev_epoch_kickout`), they can still see it in their logs.

**Comment by frol** [comment]
Another item: proactive warnings if the account id is on the validators list, but the node is not actually producing blocks (e.g. validator key is different ?)

**Comment by bowenwang1996** [comment]
> Another item: proactive warnings if the account id is on the validators list, but the node is not actually producing blocks (e.g. validator key is different ?)

That is done in https://github.com/nearprotocol/nearcore/pull/2683

**Comment by bowenwang1996** [comment]
I believe all the action items in this issue are done. Please reopen if that is not the case.
