### ISSUE TITLE
Measure re-orgs vs missed blocks

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2692]
Do we have tools for measuring how often we have re-org vs missed blocks due to offline nodes on BetaNet? @SkidanovAlex @bowenwang1996 

It’s interesting for Wallet and App Layer to understand speed of UI (CC @kcole16 @vgrichina).

**Comment by bowenwang1996** [comment]
Unfortunately no. I believe it shouldn't be too hard to add to the counter we use for graphana.

**Comment by nikurt** [comment]
Obsolete
