### ISSUE TITLE
Contract method args count towards QUERY_DATA_MAX_SIZE, in some cases

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2706]
It seems like in some cases the arguments to the contract method count towards QUERY_DATA_MAX_SIZE which prohibits RPC calls with large arguments. This does not look to be intended.

Steps to reproduce:
* Checkout https://github.com/near/rainbow-bridge/
* Initialize submodule in `environment/vendor/ethhashproof`
* Go to `environment`
* Run the following:
```bash
python3 main.py cleanup --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 main.py prepare --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 run --eth_node_url=wss://mainnet.infura.io/ws/v3/<project_id> --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
```
Wait for several minutes until it submits several blocks to the EthClient.
* In a separate terminal run:
```bash
python3 main.py test --eth_node_url=https://mainnet.infura.io/v3/<project id> --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
```
(Be careful, with the urls, they are different). You can get `<project id>` from @nearmax .
Observe that the app in the second terminal crashes.
* Increase `QUERY_DATA_MAX_SIZE`, repeat the above steps, and observe that it does not crash anymore. 

See temporary workaround: https://github.com/nearprotocol/nearcore/pull/2705

**Comment by frol** [comment]
Where is the query RPC call? We can swtch it from the legacy to the new format: https://docs.near.org/docs/interaction/rpc#query

**Comment by bowenwang1996** [comment]
@frol what is the status of this issue?

**Comment by frol** [comment]
The legacy `query` input `call//lockup.near/...` is still limited by 10kb, but the new recommended and adopted these days `query` with `{"request_type": "call_function", "account_id": "lockup.near", "method_name": "...", "args_base64": "..."}` is limited with 10mb on the payload. Thus, I believe it is addressed now.
