### ISSUE TITLE
add a commit hook which compare tests in Nightly and all non-ignored tests

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#2736]
to make sure no expensive test is forgotten

**Comment by bowenwang1996** [comment]
Shouldn't we just add this to CI? @ailisp what is the status of this issue?

**Comment by ailisp** [comment]
@bowenwang1996 I believe this is still nice to have. Yeah it should be part of CI, perhaps some kind of bot, so that if you add an expensive test or a test under pytest dir, a script should check complete_nayduck_set.txt and remind if it's not added

**Comment by mina86** [comment]
Just to confirm that I understand what this issue is about. On high level the request is to list all `pytest/tests/**/*.py` files and check if they have a corresponding line somewhere in one of the `nightly/*.txt` files?

**Comment by bowenwang1996** [comment]
@mina86 yes
