### ISSUE TITLE
Live backup tool as part of neard

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#2747]
This's a live backup tool based on rocksdb's wiki, and add load all column family feature, https://github.com/nearprotocol/rocksdb/blob/rust-rocksdb-20200427/examples/backup.cc
https://github.com/nearprotocol/rocksdb/blob/rust-rocksdb-20200427/examples/restore.cc
The backup was all success on betanet, until recently, about May 27, debugging on node shown error is always this assert(s.ok()):
```c++
  s = backup_engine->CreateNewBackup(db);
  std::cout << s.getState() << " " << s.code() << " " << s.subcode() <<std::endl;
  assert(s.ok());
```
By print the error, it's showing something like
```
/home/ubuntu/.near/data/002078.sst: No such file or directory 5 9
```
The file number greater and less than 2078 exists, so it's neard rocksdb triggered compaction, that deleted 002078.sst when backup is processing. This is not triggered every time, but about 40% chance backup will fail as of yesterday. Today chance to fail seems getting higher: I retried at most 10 times on each node and there's still 4 of 8 nodes backup fails, and those success one takes 2 hours, after several times to finish backup, which is too long. If backup without retry it takes about 10-20 minutes.

So I propose doing backup just inside neard process, which is controlled in same db handle will avoid compaction happening (or if it's not happening automatically, we can manually turn off db compaction, and backup. Discussed with @bowenwang1996 , it's going to behind feature flag, a local only rpc, that when received, node doing db backup while still processing blocks/mutate db states.

**Comment by ailisp** [comment]
Asked in rocksdb groups to see if there's any external neard work around: https://groups.google.com/forum/#!topic/rocksdb/1a2hEnSivQk

**Comment by bowenwang1996** [comment]
I think we decided to not pursue this. Closing
