### ISSUE TITLE
Incorrect CPU usage in Nearcore logs

### ISSUE THREAD

**Issue by Cloudpostru** [near/nearcore#2749]
OS: Ububntu 18.04
NEAR: version: 0.4.13, build:2d02b333

During node synchronization the nearcore fully utilises only 1 CPU core (which will be fixed in the future according to the NEAR devs, such thing is a serious bottleneck) and displays misleading CPU load in the logs: user might think that there's not enough CPU resources for nearcore because of high CPU % usage numbers in logs, but adding more cores will not help - CPU % load numbers in logs will stay the same.

Upgaded my VM that is running nodecore from 8 to 16 cores but still often see high CPU % load numbers, usually smth like 30-50% however according to HTOP my average CPU load is ~1%

![CPU display](https://user-images.githubusercontent.com/28756593/83334613-60c9c080-a2b0-11ea-9820-afa88682c760.PNG)

**Comment by bowenwang1996** [comment]
I believe this is fixed
