### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Cloudpostru** [near/nearcore#2755]
OS: Ububntu 18.04
NEAR: version: 0.4.13, build:2d02b333

I run nearcore using command `nearup betanet --nodocker`

RAM consumption increases over time for nearcore until it uses all remaining free ram, this might lead to node crash and missed blocks (for those who have 4 GB RAM and no SWAP file). 

Update:

Logged some metrics from my validator node, please check how RAM usage increases while # of peers stay the same:

Jun 01 21:39:46.520  INFO stats: # 6473010  V/85 30/29/40 peers Mem: 1.5 GiB  
Jun 01 23:41:42.722  INFO stats: # 6478283  V/85 30/30/40 peers Mem: 2.0 GiB 
Jun 02 01:13:22.565  INFO stats: # 6482229  V/85 30/29/40 peers Mem: 2.1 GiB 
Jun 02 03:11:30.448  INFO stats: # 6487323  V/84 30/30/40 peers Mem: 2.2 GiB  
Jun 02 12:16:25.703  INFO stats: # 6511504  V/85 30/30/40 peers Mem: 2.4 GiB 
Jun 02 14:21:03.205  INFO stats: # 6517129  V/85 30/30/40 peers Mem: 2.4 GiB 
Jun 02 16:29:40.502  INFO stats: # 6522701  -/84 30/29/40 peers Mem: 2.7 GiB
Jun 02 20:49:41.458  INFO stats: # 6533379  V/85 30/29/40 peers Mem: 2.8 GiB 
Jun 03 02:46:58.994  INFO stats: # 6548085  V/88 30/29/40 peers Mem: 3.0 GiB  

Is it expected behaviour of nearcore?

**Comment by bowenwang1996** [comment]
> there is a correlation between active peers and used RAM

There is but since there is a maximum value for the number of peers allowed, I don't think that should be an issue.

**Comment by Cloudpostru** [comment]
My validator is working stable last 24 hours, I decided to check RAM usage stats, here's what I got:

May 31 23:51:32.018  INFO stats: # 6412654 V/83 30/30/40 peers  Mem: 2.2 GiB  
Jun 01 13:39:47.623  INFO stats: # 6450795 V/81 30/29/40 peers  Mem: 2.5 GiB

As you can see, RAM usage increases slowly over time in similar coditions. I'll try to gather more stats.

**Comment by Cloudpostru** [comment]
Added some stats, please check them...

**Comment by bowenwang1996** [comment]
> As you can see, RAM usage increases slowly over time in similar coditions. I'll try to gather more stats.

That is expected. We have a lot of caches. We will try to bound the size of our caches so that the memory consumption isn't outrageous.

**Comment by damons** [comment]
Is there a way to configure cache size so we can see what happens when our caches are full?

I'm seeing the same thing on my nodes:

```
Jun 10 11:31:00.014  INFO stats: # 6999952 36zSeEyWEJfiqF5kM7Kapb39VTTdeYZ92E8UN2okgB7B -/87  8/8/40 peers ⬇ 112.8kiB/s ⬆ 111.2kiB/s 11.22 bps 2.20 Tgas/s CPU: 0%, Mem: 0 B    
Jun 10 11:31:10.015  INFO stats: # 6999961 Bi1hnQHKk9QWeMNwCrg5mEXv4FmBuR6XdYF5utRFNmUX -/87 10/9/40 peers ⬇ 205.3kiB/s ⬆ 174.8kiB/s 0.90 bps 523.73 Ggas/s CPU: 13%, Mem: 437.8 MiB    
```

Then 29 hours later:

```
Jun 11 16:37:03.281  INFO stats: # 7082819 ZomAAxPXQnWrjLnNa8cWS1uTTAcQeKY47Ao8QkXj4uj -/87 30/30/40 peers ⬇ 148.6kiB/s ⬆ 146.5kiB/s 0.80 bps 0 gas/s CPU: 27%, Mem: 1.2 GiB    
```

**Comment by damons** [comment]
^^^ This is on beta, btw.

**Comment by mfornet** [comment]
> Is there a way to configure cache size so we can see what happens when our caches are full?

This is a very interesting test to have, not sure if it is easy to make (probably not). With it we will know how much RAM we are targeting in the worst case. 

Also we need metrics about how much memory we are using on each cache, to understand better the memory consumption, in case there is a real memory leak.

**Comment by mfornet** [comment]
Btw, we are currently restarting betanet nodes every week, so if there is a slow/long term memory leak we will not learn about it until we run betanet (or any other network) with several nodes at the same time longer than a week.

**Comment by bowenwang1996** [comment]
We have some caches that are not bounded in size and that causes problems. We are addressing some but it is probably worth going through to make sure that we don't make such mistakes anywhere.

**Comment by ilblackdragon** [comment]
I thought our nodes expected to take ~2gb+ of ram when fully ramp up. @damons what you observe would be normal to me. We should though understand more how big memory would grow over time in normal operation and may be tune sizes of caches in some places accordingly to match some expected memory capacity.

Of cause we should bound the container sizes anyway as @bowenwang1996 pointed out.

**Comment by bowenwang1996** [comment]
> expected to take ~2gb+ of ram when fully ramp up

Definitely more than that. What we need to make sure is that this number doesn't exceed what we put on the minimum requirement for node hardware.

**Comment by ilblackdragon** [comment]
@Cloudpostru just pinged me that after 2 week uptime, it's 5.6GB.

I think we should move all the constants for cache sizes into a configuration - and try running a node with 0 cache size. This way we can probably see memory leaks vs natural cache growth.

**Comment by mfornet** [comment]
> I think we should move all the constants for cache sizes into a configuration - and try running a node with 0 cache size. This way we can probably see memory leaks vs natural cache growth.

The problem with this is that some mechanics will be broken with 0 cache sizes.

**Comment by bowenwang1996** [comment]
Yes I can immediately see that several things in chunk production and network will break or at least become quite suboptimal if we have zero cache size.

**Comment by bowenwang1996** [comment]
Currently we see that under normal operation the node can consume more than 10GB of memory. We should start investigating its cause.

**Comment by damons** [comment]
This is a constant problem now on testnet:

Via Slack from Mario in Release Engineering: 

> Mario Halambek  2:27 AM
> Restarted testnet-nearup0
> Out of memory: Killed process 26084 (near) total-vm:17013280kB, anon-rss:15220196kB, file-rss:96kB, shmem-rss:4kB
> looks like a common problem by now

**Comment by chefsale** [comment]
@pmnoxx @bowenwang1996 This can be most likely used to the profiling: https://github.com/gperftools/gperftools

**Comment by pmnoxx** [comment]
I added a couple changes that hopefully will show us where the memory leak is. 
We will measure the amount of memory used by rocksdb, from jemalloc, memory used by each actor.
Also most importantly the number of allocations/size of allocations per thread.
Here is a draft PR: (https://github.com/nearprotocol/nearcore/pull/3319) 

I'll run a node for a few days, hopefully we will know more soon.

**Comment by pmnoxx** [comment]
All memory leaks related to Wasmer has been fixed.
We currently have 8.5gb block cache size limit for RocksDB, this is a little bit excessive, we will reduce it to 1.5gb.

**Comment by bowenwang1996** [comment]
I believe this is addressed with the change to rocksdb cache size
