### ISSUE TITLE
Missing rpc_errors_schema.json test 

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#2764]
**Describe the bug**
There are no test that enforces `rpc_errors_schema.json` being regenerated.

**To Reproduce**
Currently on master `rpc_errors_schema.json` is not up to date. Some fields have to be added and some fields needs to be removed.
Run the following to regenerate the schema:
```bash
chain/jsonrpc/build_errors_schema.sh
```

**Expected behavior**
Prevent being able to commit to master if the schema is not up to date. Run schema generation in the CI and verify it matches the one in the tree.

**Comment by bowenwang1996** [comment]
don't think this is still relevant
