### ISSUE TITLE
Currently most of our Python code base is using print instead of proper logging

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#2780]
Currently most of our Python code base is using print instead of proper logging, we should change that.

cc: @ailisp @bowenwang1996

**Comment by ailisp** [comment]
Good point, logging gives us error and verbose level. timing is probably more important in our tests

**Comment by bowenwang1996** [comment]
Good point.

**Comment by mikedotexe** [comment]
hey @bowenwang1996 it seems that Nayduck is wanting Phuong to have access to the `nearprotocol` GitHub org. Can we give this access to him and/or give him access to Azure in order to change this setting?

**Comment by bowenwang1996** [comment]
@mikedotexe is this resolved?

**Comment by ChaoticTempest** [comment]
@bowenwang1996 nayduck is working for me. Thanks for the help!
