### ISSUE TITLE
Query ViewAccount with non-existing account id does not return error as expected

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#2789]
**Describe the bug**
Calling query method `view_account` with `account_id` that doesn't exist returns `result` with data instead of error.

**To Reproduce**
I'm including rust test `test_query_view_account_non_existing_account_must_return_error` to reproduce it. #2740 

**Expected behavior**
I expect to receive response with `error` key instead of `result`

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version rustc 1.45.0-nightly (a74d1862d 2020-05-14)
- testnet

**Additional context**
it is found while implementing #2422

**Comment by khorolets** [comment]
We have such test in `neard/tests/rpc_nodes.rs` which runs with realish nodes, I'm going to remove this test from `jsonrpc` crate
https://github.com/near/nearcore/blob/1e4253a13d27e6241d5f8f18054a50ded40184e1/neard/tests/rpc_nodes.rs#L735-L772

**Comment by bowenwang1996** [comment]
@khorolets any updates on this?
