### ISSUE TITLE
Query ViewAccessKey with non-existing account id  and PublicKey does not return error as expected

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#2790]
**Describe the bug**
Calling query method `view_access_key` with `account_id` that doesn't exist and `public_key` that doesn't exist, returns `result` with data instead of error.

**To Reproduce**
I'm including rust test `test_view_access_key_non_existing_account_id_and_public_key_must_return_error` to reproduce it. #2740 

**Expected behavior**
I expect to receive response with `error` key instead of `result`

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version rustc 1.45.0-nightly (a74d1862d 2020-05-14)
- testnet

**Additional context**
it is found while implementing #2422

**Comment by bowenwang1996** [comment]
@frol @khorolets what is the status of this issue?
