### ISSUE TITLE
Query CallFunction with non-existing account id, method name and empty args does not return error as expected 

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#2791]
**Describe the bug**
Calling query method `call_function` with `account_id` that doesn't exist and `method_name` that doesn't exist and empty `args`, returns `result` with data instead of error.

**To Reproduce**
I'm including rust test `test_call_function_non_existing_account_method_name` to reproduce it. #2740 

**Expected behavior**
I expect to receive response with `error` key instead of `result`

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version rustc 1.45.0-nightly (a74d1862d 2020-05-14)
- testnet

**Additional context**
it is found while implementing #2422

**Comment by bowenwang1996** [comment]
@frol @khorolets what is the status of this issue?
