### ISSUE TITLE
Query ViewAccessKeyList with non-existing account id does not return error as expected

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#2792]
**Describe the bug**
Calling query method `view_access_key_list` with `account_id` that doesn't exist returns `result` with data instead of error.

**To Reproduce**
I'm including rust test `test_view_access_key_list_non_existing_account` to reproduce it. #2740 

**Expected behavior**
I expect to receive response with `error` key instead of `result`

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version rustc 1.45.0-nightly (a74d1862d 2020-05-14)
- testnet

**Additional context**
it is found while implementing #2422

**Comment by bowenwang1996** [comment]
@frol @khorolets what is the status of this issue?
