### ISSUE TITLE
Query ViewState with with non-existing account id and invalid prefix does not return error as expected

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#2793]
**Describe the bug**
Calling query method `view_state` with `account_id` that doesn't exist returns `result` with data instead of error. But it might be intentional /cc @frol 

**To Reproduce**
I'm including rust test `test_view_state_non_existing_account_invalid_prefix` to reproduce it. #2740 

**Expected behavior**
I expect to receive response with `error` key instead of `result`

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version rustc 1.45.0-nightly (a74d1862d 2020-05-14)
- testnet

**Additional context**
it is found while implementing #2422

**Comment by frol** [comment]
It might be by design, so it is yet to be decided if we want to return Not Found (I guess, it is nice to have it this way).

**Comment by bowenwang1996** [comment]
@frol @khorolets what is the status of this issue?

**Comment by frol** [comment]
@miraclx I believe with the recent strictly-typed AccountId we addressed this issue. Can you try removing the `#[ignore]` attribute from the tests in `chain/jsonrpc/tests/rpc_query.rs`? We might be able to close a ton of issues now!

**Comment by miraclx** [comment]
Indeed! We go from

this:

```console
test test_view_state_non_existing_account_invalid_prefix ... FAILED

failures:

---- test_view_state_non_existing_account_invalid_prefix stdout ----
thread 'test_view_state_non_existing_account_invalid_prefix' panicked at 'queried view account for not exsiting account, but received success instead of error', chain/jsonrpc/tests/rpc_query.rs:659:9
```

to this:

https://github.com/near/nearcore/blob/9f5e20b29f1a15a00fc50d6051b3b44bb6db60b6/chain/jsonrpc/tests/rpc_query.rs#L656

```console
test test_view_state_non_existing_account_invalid_prefix ... FAILED

failures:

---- test_view_state_non_existing_account_invalid_prefix stdout ----
thread 'test_view_state_non_existing_account_invalid_prefix' panicked at 'called `Result::unwrap()` on an `Err` value: ParseAccountError(Invalid, "\u{0}\u{0}\u{0}\u{0}\u{0}\u{4}\u{0}\u{0}\u{0}\u{8}\u{0}\u{0}\u{0}\u{0}\u{0}eeeeeeeeeeeeeeeeeeeeeeeeeeeee")', chain/jsonrpc/tests/rpc_query.rs:656:148
```

Yay for early validation. We can proceed to resolve these issues. I can take this one.

**Comment by frol** [comment]
> Yay for early validation. We can proceed to resolve these issues. I can take this one.

Great! Please, take it!
