### ISSUE TITLE
Append only storage

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2796]
Currently we are updating/replacing some pieces of storage. This means that if we have Client changing storage and ViewClient fetching it in parallel - we will observe failures from time to time.

For example if code relies that after fetching block, block_header is also there but Garbage collector got executed. Or if we are iterating over values in storage, but storage got updated (we updated ref counter of nodes, which removes node with previous hash).

This is important to allow Client and ViewClient to run in parallel threads.

**Comment by SkidanovAlex** [comment]
Since `ViewClient` doesn't write to the storage in a way that affects `Client` (presumably?), shall we instead just write all the routines in `ViewClient` in a way that are ready to data disappearing?

Our `store` is already mostly written in a way that doesn't allow *updating* (only *deleting*) data.

Append only sounds to me like "can't be garbage collected"?

**Comment by mikhailOK** [comment]
Trie does updates to refcounts, we might have to put them into a separate db column. If nothing that ViewClient touches allows updates, and only GC does deletes it will make things simpler.

Another thing we can do is use [read snapshots](https://docs.rs/rocksdb/0.12.3/rocksdb/struct.Snapshot.html).

**Comment by bowenwang1996** [comment]
> Since ViewClient doesn't write to the storage in a way that affects Client (presumably?), shall we instead just write all the routines in ViewClient in a way that are ready to data disappearing?

As far as I know it is already written that way.

**Comment by SkidanovAlex** [comment]
@ilblackdragon do you have a particular race condition in mind?

**Comment by ilblackdragon** [comment]
@SkidanovAlex We have updates that will be read from different threads after https://github.com/nearprotocol/nearcore/issues/2751: trie updates, block number -> hash updates, head/tail updates.

There is https://github.com/nearprotocol/nearcore/issues/2863 epic to target this.

**Comment by bowenwang1996** [comment]
I believe `ViewClient` has already been changed to tolerate transient errors (data disappearing) and it does not write any data to storage.
