### ISSUE TITLE
[Enhancement] Additional RPC and Prometheus Data Points

### ISSUE THREAD

**Issue by htafolla** [near/nearcore#2834]
The current challenge on Stakewars is to setup monitoring with email alerts and as I was working through it I noticed a couple of enhancements that would improve things. The idea would be to monitor and alert from a single dashboard or service.

Additional Prometheus Data points - http://localhost:3030/metrics 
1. Blocks Expected
2. Blocks Produced
3. Node Version and Build
4. Seat Price
5. Is Validator
6. Is Kicked
7. Has Enough Stake

Additional Remote RPC Data points - These would enable the ability for true remote monitoring
1. Node Version and Build
2. Peers

**Comment by gaia** [comment]
Version/Build is already available via `echo -n "Remote " && curl -s https://rpc.testnet.near.org/status | jq -r .version.build && echo -n "Local " && curl -s http://localhost:3030/status | jq -r .version.build`? What else would you like to see?

**Comment by bowenwang1996** [comment]
> Node Version and Build

This is provided through `/status` endpoint.

> Peers

You can use `/network_info` for this

**Comment by janewang** [comment]
In addition to `num_expected_blocks` and `num_produced_blocks`, consider add a graph of delta of those two, so num_expected_blocks - num_produced_blocks. Closing https://github.com/near/nearcore/issues/3580 in favor of this story, as this is the superset.

**Comment by nikurt** [comment]
@htafolla Thank you for posting these suggestions. As most of them are currently available, let me close the issue. If you have a concrete use case for one of the metrics please let me know by re-opening the issue.


## Metrics

> Blocks Expected

Available as metrics `near_validators_blocks_expected` and `near_validators_chunks_expected`

> Blocks Produced

Available as metrics `near_validators_blocks_produced` and `near_validators_chunks_produced`

> Node Version and Build

Available, as mentioned above by @gaia and @bowenwang1996 

> Seat Price

What's your use case for making this a metric? This is provided by `near-cli` as `near validators current`.

> Is Validator

Available as `near_is_validator`

> Is Kicked

Seems that "Is Validator" should be sufficient in most cases.

> Has Enough Stake

Seems that "Is Validator" should be sufficient in most cases.


## Additional Remote RPC Data points

> Node Version and Build

Available as mentioned above by @gaia and @bowenwang1996 

> Peers

Available as mentioned above by @gaia and @bowenwang1996
