### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Viacheslav198** [near/nearcore#2837]
**Describe the bug**
Sync failed

**To Reproduce**
Unknown

**Expected behavior**
Sync should not fail

**Screenshots**

The screenshots are in historical order from older to newer:

<img width="1085" alt="Снимок экрана 2020-06-11 в 17 19 42" src="https://user-images.githubusercontent.com/65883388/84368208-3cef6e80-ac10-11ea-8541-382443ab1dc0.png">
<img width="1147" alt="Снимок экрана 2020-06-11 в 17 33 48" src="https://user-images.githubusercontent.com/65883388/84368206-3c56d800-ac10-11ea-9c55-4f95879b8b19.png">
<img width="1153" alt="Снимок экрана 2020-06-11 в 17 53 17" src="https://user-images.githubusercontent.com/65883388/84368203-3b25ab00-ac10-11ea-890d-e2bd320eb942.png">
<img width="1182" alt="Снимок экрана 2020-06-11 в 17 57 05" src="https://user-images.githubusercontent.com/65883388/84368198-3a8d1480-ac10-11ea-90bc-e4005c770688.png">
<img width="1197" alt="Снимок экрана 2020-06-11 в 18 05 39" src="https://user-images.githubusercontent.com/65883388/84368174-352fca00-ac10-11ea-840b-29dac52f60ac.png">

**Version (please complete the following information):**
- nearcore commit/branch: b30864b8
- betanet

**Additional context**
It used to be running fine, but failed and does not recover. The connections to the peers were disappearing until the completely died out.

**Comment by frol** [comment]
@mfornet @bowenwang1996 Is this a known issue? According to Explorer telemetry we had 3 nodes stuck at the same block height. It also seems that the node was banned by peers (hence 0 peers observation).

**Comment by bowenwang1996** [comment]
@Viacheslav198 did you do any of the following:
* stake before your node is synced
* change your validator key when your node is synced and running

If so, then it is a known issue.

**Comment by frol** [comment]
@bowenwang1996 According to Explorer, he did ping for the staking pool, which stakes... Is there are tracking issue for this?

@Viacheslav198 Please, never stake (or ping your staking pool contract) before your node is fully synced as not only this causes problems for your node, it also slows down the whole network if your node is not able to participate in the epoch validation since it is not synced yet.

**Comment by bowenwang1996** [comment]
outdated
