### ISSUE TITLE
Monitor important health metrics in Grafana, etc

### ISSUE THREAD

**Issue by vgrichina** [near/nearcore#2856]
We should track important health metrics for nearcore and make it easy to look them up as time series in Grafana (or elsewhere).

Every time we see some anomaly (e. g. too many timeouts when sending tx) it should be possible to eyeball quickly what else is going wrong (queue sizes, ram usage, cpu usage, number of threads, etc)

It makes sense to monitor such things:
- [x] error count by type (e.g. specifically timeouts in RPC to submit transaction are super interesting)
- [x] error count by RPC endpoint
- [x] response time by RPC endpoint
- [ ] time from transaction being received to it landing on chain
- [ ] queue sizes
- [ ] event loop execution time (per every distinct event loop)
- [ ] number of threads if it's dynamic
- [x] RAM / CPU / disk space usage per component where it makes sense and is measurable
- [ ] whatever more custom counter / gauges make sense for given component, should be easy to add new metric

**Comment by vgrichina** [comment]
After few incidents while having graphs we likely will see which of the metrics are most interesting and need closer monitoring (and maybe alerts for anomalous values).

**Comment by htafolla** [comment]
@vgrichina I also requested a few metrics be added to the Prometheus feed on this PR for validators: https://github.com/nearprotocol/nearcore/issues/2834

**Comment by bowenwang1996** [comment]
@chefsale could you check whether all of the items are done here?

**Comment by chefsale** [comment]
All the items we can extract data at the moment are done, some of them I would say are not possible at the moment like time from transaction being received to it landing on chain, etc. WDYT?

**Comment by bowenwang1996** [comment]
Yeah makes sense. Let's close it
