### ISSUE TITLE
Very long deploying node and stuck after generating keys on betanet/testnet

### ISSUE THREAD

**Issue by anes-madiyarov** [near/nearcore#2882]
Hello everyone.
I have troubles with deploy node testnet/betanet. Some times ago my own image works fine. But from sunday it doesn't working.
If deploy node it's stuck on string "Node key generated" or "Validator key generated" or it's started but stuck on first string on logs "Jun 22 20:00:07.741  INFO near: Version: 1.0.0, Build: ebe21b33, Latest Protocol: 22" and can't start syncing headers.
Also get this exception 
spawn nearup testnet --nodocker
Using officially compiled binary
Downloading latest deployed version for testnet
Setting up network configuration.
Enter your account ID (leave empty if not going to be a validator): 
Generating node key...
PK: ed25519:4TASWwdPXhnoCwBgzZFwxBZRAGc1pE792Ds4jejsXU2W
Node key generated
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
Traceback (most recent call last):
  File "/root/.nearup/main.py", line 96, in <module>
    args=sys.argv[1:])
  File "/root/.nearup/nearuplib/nodelib.py", line 599, in setup_and_run
    no_gas_price)
  File "/root/.nearup/nearuplib/nodelib.py", line 137, in check_and_setup
    nodocker_init_official(chain_id, binary_path, home_dir, account_id)
  File "/root/.nearup/nearuplib/nodelib.py", line 42, in nodocker_init_official
    download_genesis(chain_id, home_dir)
  File "/root/.nearup/nearuplib/nodelib.py", line 164, in download_genesis
    os.path.join(home_dir, 'genesis.json'))
  File "/root/.nearup/nearuplib/util.py", line 27, in download_near_s3
    filepath)
  File "/root/.nearup/nearuplib/util.py", line 16, in download
    '-o', filepath
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['curl', '--proto', '=https', '--tlsv1.2', '-sSfL', 'https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json', '-o', '/root/.near/testnet/genesis.json']' returned non-zero exit status 56.

**Comment by bowenwang1996** [comment]
@ailisp can you take a look?

**Comment by anes-madiyarov** [comment]
root@app-15068230-833c-4983-a51c-5586ffe76dd4-near-full-node-fchfcqd:/# netstat -a | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 app-15068230-833c:60586 actiontoad.canonic:http TIME_WAIT  
tcp        0      0 app-15068230-833c:33138 aerodent.canonical:http TIME_WAIT  
tcp        0      0 app-15068230-833c:47528 aerodent.canonical:http TIME_WAIT  
tcp        0      0 app-15068230-833c:47536 aerodent.canonical:http TIME_WAIT  
tcp        0      0 app-15068230-833c:34830 aerodent.canonical:http TIME_WAIT  
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
Some additional info. It's netstat result from node which started but stuck on first string of logs

**Comment by anes-madiyarov** [comment]
I think node can't connect to other peers

**Comment by ailisp** [comment]
> If deploy node it's stuck on string "Node key generated" or "Validator key generated" 

>  subprocess.CalledProcessError: Command '['curl', '--proto', '=https', '--tlsv1.2', '-sSfL', 'https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json', '-o', '/root/.near/testnet/genesis.json']' returned non-zero exit status 56.

These two errors are failed to download genesis, sometimes I encounter s3 ssl cert fails and failed of this error. And testnet genesis is 366M as of now, so if your network condition isn't good it would stuck for a while to at "Node key generated" or "Validator key generated"

> I think node can't connect to other peers or can't download resources

This I cannot reproduce with our build, can you share your docker image?

**Comment by anes-madiyarov** [comment]
FROM ubuntu:18.04
ARG deb_repo=release

RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    python3 \
    git \
    curl \
    dumb-init \
    iputils-ping \
    expect \
    sudo

ADD ./scripts /

RUN curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh -o install_nvm.sh

RUN bash /install_nvm.sh

RUN bash /install.sh

ENV NODE_ENV=testnet

This is docker image

#!/bin/bash

bash -c 'source ~/.profile'
bash -i -c 'nvm install 12.16.3'
bash -i -c 'npm install -g near-shell'

curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/near/nearup/master/nearup -o setup.py
python3 setup.py --help

This is install.sh

**Comment by bowenwang1996** [comment]
looks like this is outdated
