### ISSUE TITLE
Extend RPC /status to calc epoch progress

### ISSUE THREAD

**Issue by akme** [near/nearcore#2914]
It would be nice to have `epoch_id` and `start_epoch_height` in response to the status method instead of making 3 different method calls just to get the needed data to calculate epoch progress.

**Comment by bowenwang1996** [comment]
@frol is this something that your team is interested in doing?

**Comment by frol** [comment]
I vote for keeping it in the icebox. I believe it is self-contained enough to be "good-first-issue", so if someone wants to contribute, I am happy to walk you through and show which pieces we need to connection.

**Comment by mooori** [comment]
I would like to pick this up. Can it be assigned to me?

I'm unsure what `start_epoch_height` refers to. Maybe `EpochHeight` of the current epoch or `BlockHeight` of the current epoch's first block?

**Comment by bowenwang1996** [comment]
> I'm unsure what start_epoch_height refers to. Maybe EpochHeight of the current epoch or BlockHeight of the current epoch's first block?

I think it refers to the height of the first block in the epoch. `epoch_start_height` may be a better name (and it is how this thing is named in nearcore anyways). @mooori assigned the issue to you
