### ISSUE TITLE
Move pipeline definition in repo

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#2966]
We used to have problems when we have beta/stable and master branch together and pipeline file in repo diverge from time to time and need to update three branches for any pipeline change. Now we're moving to single master branch as the PR destination, we should move pipeline definition in repo so each PR can add/delete pipeline definition without affect other PRs.

**Comment by chefsale** [comment]
This has been resolved, as we migrated all the pipelines into the repos for nearcore.
