### ISSUE TITLE
state_sync.py triggers read timeout during getting blocks while epoch is switching

### ISSUE THREAD

**Issue by Kouprin** [near/nearcore#2981]
Origin: https://github.com/nearprotocol/NEPs/issues/91

@SkidanovAlex:
See state_sync.py failures here:

http://nightly.neartest.com/run/master_06b21f724204626db490f6062999a5832c323b01_20200710_124728

Note that the test finished and gets to the store valitity checks, and then triggers the read timeouts reported in the stderr

**Comment by Kouprin** [comment]
The issue still appears in Nighty but not in custom Nightly. It seems Nightly and custom Nightly use system resources in different way.

**Comment by bowenwang1996** [comment]
outdated
