### ISSUE TITLE
NEAR Indexer ideas

### ISSUE THREAD

**Issue by frol** [near/nearcore#2996]
*This is a discussion board tracking requests and ideas for future work around [NEAR Indexer](https://github.com/nearprotocol/nearcore/tree/master/chain/indexer).*

As mentioned in [the README](https://github.com/nearprotocol/nearcore/tree/master/chain/indexer), we have plenty of ideas as to NEAR Indexer applications. Feel free to share your ideas and build your own indexers!

**Comment by stevepro-lab** [comment]
Is there Java Script or Type Script version of this indexer available?

**Comment by bowenwang1996** [comment]
@frol why is this not a discussion :)

**Comment by stevepro-lab** [comment]
@bowenwang1996  @frol We are estimating efforts to support Near Protocol on [Dappquery](https://dappquery.com/) analytics platform. In this process we are checking existing available indexers. We are already aware of [Mintbase Near Indexer](https://github.com/Mintbase/mintbase-near-indexer ). 

Please share any resources which we can use for further analysis.
