### ISSUE TITLE
Node Performance

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3068]
This is epic to track performance across the stack:

*   WASM execution
*   Chain processing
*   RPC latency and throughput
*   End2end TPS on various networks
*   EVM performance

Here are existing benchmarks:

*   Load test on mocknet - [https://github.com/nearprotocol/nearcore/blob/master/pytest/tests/mocknet/load_testing.py](https://github.com/nearprotocol/nearcore/blob/master/pytest/tests/mocknet/load_testing.py)
*   Listen counter (needs 10+ machines) - [https://github.com/near-examples/listens-counter/blob/master/src/benchmark.js](https://github.com/near-examples/listens-counter/blob/master/src/benchmark.js)

1.  Current results

<div class="table-wrap">
  | Benchmark | Network | Date | Value | | | | | | | Payments tps | mocknet-50-1 | <span class="error">[July 27, 2020]</span>([http://nightly.neartest.com/run/master_4ca4e9dbd17c234238ecaf775481597dc343daf4_20200729_202503/mocknet/mocknet_mocknet_load_testing_py/stdout](http://nightly.neartest.com/run/master_4ca4e9dbd17c234238ecaf775481597dc343daf4_20200729_202503/mocknet/mocknet_mocknet_load_testing_py/stdout)) | 498 | | MIxed transactions tps | mocknet-50-1 | <span class="error">[July 27, 2020]</span>([http://nightly.neartest.com/run/master_4ca4e9dbd17c234238ecaf775481597dc343daf4_20200729_202503/mocknet/mocknet_mocknet_load_testing_py/stdout](http://nightly.neartest.com/run/master_4ca4e9dbd17c234238ecaf775481597dc343daf4_20200729_202503/mocknet/mocknet_mocknet_load_testing_py/stdout)) | 337 | | Listen-counter tps | testnet-20-1 | <span class="error">[July 25, 2020]</span>([https://explorer.testnet.near.org/blocks/APsyvorvhGJj7bwThx7K6A2eYRYPQszwjRi8hAwaYyry](https://explorer.testnet.near.org/blocks/APsyvorvhGJj7bwThx7K6A2eYRYPQszwjRi8hAwaYyry)) | 200 | 
</div>

Network name: <name>~~<# nodes>~~<# shards>

**Comment by vgrichina** [comment]
@ilblackdragon where did you get 200 value for listen-counter TPS? It is only occasionally hitting 200 transaction blocks, we don't have sustainable 200 TPS on testnet.

Peak results like this are at best metric of what we theoretically can do. They do not represent actual real life performance.

**Comment by nikurt** [comment]
I think this issue is obsoleted in favor of modern mocknet and benchmarking projects.
