### ISSUE TITLE
Run param estimator on nightly

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3079]
We need to run runtime fees param estimator on nightly to make sure we don't accidentally introduce regression by tinkering with the runtime. Compilers are tricky and seemingly no-op changes might cause performance regression, especially around hight-performance code, like gas counter.

CC @olonho @evgenykuzyakov

**Comment by nearmax** [comment]
The test should fail if performance decreases by more than the tolerance margin provided by @olonho

**Comment by willemneal** [comment]
Meeting with @chefsale tomorrow to discuss.

**Comment by bowenwang1996** [comment]
What is the status of this issue?

**Comment by bowenwang1996** [comment]
@matklad ?

**Comment by matklad** [comment]
On the plate for me!

**Comment by matklad** [comment]
@jakmeier tackled this!
