### ISSUE TITLE
Investigate whether param estimator is affected by disk caching

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3097]
As reported by @SkidanovAlex Ubuntu can cache up to 1GiB of disk, we need to make sure param estimator is hitting the actual disk and not the cache.

**Comment by bowenwang1996** [comment]
@olonho what is the status of this issue?

**Comment by bowenwang1996** [comment]
@matklad @olonho

**Comment by matklad** [comment]
No progress here, good to keep in mind though. #4771  feels related as vaguely database-related issue which
