### ISSUE TITLE
Fix contract call fee issue

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3158]
We have discovered that we were underpricing contract call fee due to a bug in param estimator tool that was hidden by a bug introduced in this PR: https://github.com/nearprotocol/nearcore/pull/2845/files#diff-a811f7fb6a4892a2b6cc0098f7f68616R567. It turns out 300KiB contracts would cost >100Tgas to compile which is prohibitively expensive for our partners. According to @willemneal this is not only a Wasmer issue, but Wasmtime+lightbeam have the same CPU cost.

We need to fix it urgently and delay Mainnet launch until we do so CC @SkidanovAlex , @bowenwang1996 Things that we need to do:
* @olonho or @evgenykuzyakov  to independently double check @willemneal 's results that Wasmtime+lightbeam and Wasmer+singlepass produce almost exactly the same number of CPU instructions during compilation. This coincidence looks suspicious for two completely different backends with different architectures;
* @olonho, @willemneal, @evgenykuzyakov need to investigate whether there are low-hanging fruits in Wasmer+singlepass compilation. E.g. why does compilation cost so much, isn't it supposed to be JIT?
* @evgenykuzyakov should start working on implementing https://github.com/nearprotocol/NEPs/issues/97 . Good news, this might boost our contract call TPS significantly overall.

**Comment by mikedotexe** [comment]
Please advise if this affects if/how we should communicate to launch partners when you have a free moment.

**Comment by evgenykuzyakov** [comment]
Please comment on https://github.com/nearprotocol/NEPs/issues/97#issuecomment-673724401
Does this work?

**Comment by frol** [comment]
Consider testing the rewrite of wasmer (wasmer-reborn): https://github.com/wasmerio/wasmer-reborn

**Comment by bowenwang1996** [comment]
@frol looks like the repo doesn't exist

**Comment by frol** [comment]
It seems they had made it private again... Should we ask them to share it with us?)

**Comment by willemneal** [comment]
It seems risky to try a new VM that is less tested.  We could revisit when it's stabilized.

**Comment by bowenwang1996** [comment]
@frol looks like it's already merged https://github.com/wasmerio/wasmer/commit/518e0f32226abffff78d01af195d6de0dbaea00b

**Comment by nearmax** [comment]
Setting estimate to 5 -- how much time it is going to take in this cycle.

**Comment by bowenwang1996** [comment]
Superseded by #4401
