### ISSUE TITLE
Exhaustively cover potential error types returned from JSON RPC in docs

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3183]
We need to add JSON RPC spec to nomicon.io . It should describe all endpoints, use-cases of these points, together with all situations when they return normal result vs error. It is blocked by https://github.com/nearprotocol/nearcore/issues/2976

**Comment by bowenwang1996** [comment]
@frol what is the status of this issue?

**Comment by frol** [comment]
The error types are yet to be documented, so let's keep this issue open (I renamed it).

**Comment by frol** [comment]
This was actually addressed by @khorolets! https://github.com/near/docs/pull/811

Each JSON RPC endpoint has an exhaustive documentation about all the possible errors: https://docs.near.org/docs/api/overview
