### ISSUE TITLE
Regression tests for JSON RPC

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3184]
We need to cover every JSON RPC endpoint, it's usages, together with all successful and erroneous responses. Basically we need to hardcode a list of tuples: `(setup, request, response)`, where `setup` is some condition that we need to check, e.g. node going out of sync, gc collecting some blocks, etc. `request` and `response` have to be actually hardcoded as much as possible, so that if anything unintended breaks deep down in the infrastructure we notice its effects through the RPC.

**Comment by frol** [comment]
We use nightly tests (see `/pytest/tests/sanity/rpc_*.py`) to implement such tests. Essentially, the current pytest suite implements the regression tests through JSON RPC, so it is not immediately clear what we as an RPC team can do better on this front. Feel free to re-open.

**Comment by nearmax** [comment]
Are the current tests exhaustive, i.e. do they cover all error responses?

**Comment by frol** [comment]
They don't cover all error responses. It is blocked by #2536

**Comment by bowenwang1996** [comment]
@frol what is the status of this issue?

**Comment by frol** [comment]
We covered most of the error cases during the work on #2976, and while there is always room for improvement, I think it is good enough to close this issue for now and open smaller ones whenever necessary.
