### ISSUE TITLE
[Discussion] Ensure deletion of large contracts cannot be abused

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3192]
While users cannot have more than one contract deletion in the transaction, deletion of a large contract can still be disruptive to the node. We need to do the following:
* Come up with a list of potential attacks and their hypothetical effects on the node;
* If the effects turn out to be abusable to substantially disruptive to the node, discuss what we can do about it. Potential solutions: severely limit single node size; make it less disruptive through tree flattening and db-level optimizations; introduce protocol-level change to pay for the contract deletion action with the locked tokens.

**Comment by bowenwang1996** [comment]
Fixed in #4116
