### ISSUE TITLE
Ensure touch_trie_node fee is correct

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3193]
The computation of the touch_trie_node fee is tricky, since it requires constructing states of various sizes and measuring the difference in the number of CPU instructions it takes for the write operation.

Also, we need to make sure the fee is only applied for write operations, since we are going to flatten the trie and it won't matter much for read operations how deep is the trie, cc @mikhailOK .

Not assigning to @olonho . While this is related to param estimator most of the logic is around the state trie.

**Comment by evgenykuzyakov** [comment]
> Also, we need to make sure the fee is only applied for write operations, since we are going to flatten the trie and it won't matter much for read operations how deep is the trie.

Can you point me to the issue?

**Comment by bowenwang1996** [comment]
we should look into this as many Aurora transactions spend more than 50% of the gas used on touch_trie_node. cc @Longarithm @mm-near

**Comment by jakmeier** [comment]
There is some progress on this in PR #6336. But I will also need to solve #3097 to make the estimate meaningful.

Additionally, I should investigate how much the size of the touched nodes matter. Currently, the estimate operates on nodes with only one child each.

**Comment by jakmeier** [comment]
I think we did enough to justify closing this issue.

See #6336, #6347, #6464, #6618
