### ISSUE TITLE
Move nearcore to near organization once there are no launches

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3249]
Once there is a period of relative stability and we don't have large launches we should move neracore repo from nearprotocol to near organization.

* @bowenwang1996  should make a decision when we migrate, therefore he is an assignee;
* Release team with @chefsale are responsible for the migration, fixing the CI, and updating the release scripts.

**Comment by chefsale** [comment]
Lets make an announcement two weeks ahead and give time to validators to upgrade, also we should create a list of files which have to be changed. As well, we have to check all the documentation once this happens. cc: @bowenwang1996 @jimmy3dita

**Comment by nearmax** [comment]
@bowenwang1996 suggests that he would need to work with @chefsale and @jimmy3dita on it.

**Comment by bowenwang1996** [comment]
We have announced that this will happen on 12th of October at 4PM CET. Will close the issue once the migration is done.

**Comment by bowenwang1996** [comment]
done
