### ISSUE TITLE
Do not run all compilation features in tests

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3282]
Currently our CI tests assume that if we enable all features the code will work correctly. This have been the case mostly because we were very conservative with adding compilation features (because they are difficult to maintain) and we made sure for some features that at least one of them is enabled, and if both of them are enabled then only one is used https://github.com/nearprotocol/nearcore/blob/9d759ad639c3c1edc4443836b88bb1cbfcd5a8f7/runtime/near-vm-runner/src/runner.rs#L132 

However, Rust does not guarantee that combinations of features when enabled together do not interfere with each other in unexpected way. Also, some of our current features disable things, rather than enabling them. Therefore our tests should not run with all features enabled. Instead if we want certain tests to exercise specific features we need to have separate tests for these specific features.

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek can you look into this?

**Comment by bowenwang1996** [comment]
I don't think we run with all features in CI when we run tests. More specifically, we run
```
cargo test --locked --workspace
```
to test stable features and
```
cargo test --workspace --features nightly_protocol,nightly_protocol_features
```
to test nightly features.
