### ISSUE TITLE
Bound size of `TransactionPool` in memory

### ISSUE THREAD

**Issue by birchmd** [near/nearcore#3284]
Presently transactions are simply stored in a `BTreeMap` in memory, however, if we receive too many transactions too quickly, then this could grow over time, especially if the transactions are large.

**Comment by nikurt** [comment]
Not sure what to do if a pool reaches its maximum size but transactions keep coming in.
Is it possible that rejecting incoming transactions will also the one transaction that needs to be processed next, i.e. a transaction with the lowest nonce?
@mzhangmzz do you have suggestions?

**Comment by nikurt** [comment]
To get an idea of a reasonable tx pool size bound, will add a metric get back to it.

**Comment by bowenwang1996** [comment]
> Not sure what to do if a pool reaches its maximum size but transactions keep coming in.

We might need to stop accepting transactions at that point. cc @mm-near

**Comment by akashin** [comment]
I'll pick this issue in the context of congestion work (https://github.com/near/nearcore/milestone/26, https://github.com/near/nearcore/issues/8878).

As a first step, I plan to investigate two naive approaches:
- [ ] Introducing hard capacity limit for transaction pool (e.g. 1000 transactions)
- [ ] Introducing TTL for transactions in the pool (e.g. 1 minute)

I highly suspect that both approaches will break some tests/assumptions that the clients make. My first goal will be to understand:
- [ ] What will actually break
- [ ] How easy would it be to fix it
- [ ] How should the clients behave in the face of these limits: https://github.com/near/nearcore/issues/8879

**Comment by akashin** [comment]
We do indeed have tests that rely on putting many transactions into the pool. Example failures are:
- https://buildkite.com/nearprotocol/nearcore/builds/27048 (with size limit 20)
- https://buildkite.com/nearprotocol/nearcore/builds/27050 (with size limit 2)

Concrete test https://github.com/near/nearcore/blob/055a9e27f2652e0f13a398d74660db20e1e9acd1/integration-tests/src/tests/client/benchmarks.rs#L25 puts 20 transactions into the pool before starting to process them.

I'm adding explicit checks for the returned transaction status https://github.com/near/nearcore/pull/8976 which would make it much easier to catch tests broken by introducing transaction pool size limits.

Retrying the failure in all those tests would likely be too burdensome, so we'll have to use some high-enough limit that will cover the majority of tests and only introduce in the retries in tests that actually exercise the congestion scenario.

**Comment by akashin** [comment]
I will proceed with implementing a hard capacity limit measured in bytes. The limit will be separate for each per-shard transaction pool within the [`ShardedTransactionPool`](https://github.com/near/nearcore/blob/7dc51a5dacab435b765bb52e18e21a3dec5a37cb/chain/chunks/src/client.rs#L33).
I confirmed that none of the tests break with a limit > 1000 transactions (yet to measure how many bytes that would be).

We will also start returning a new error type to the clients when we reach the transaction pool size limit, so that they can retry this error intelligently with a back-off.

**Comment by akashin** [comment]
I've filed a bug for some follow-up work to simplify transaction pool code: https://github.com/near/nearcore/issues/9060
