### ISSUE TITLE
Ensure Upgradability Process

### ISSUE THREAD

**Issue by mfornet** [near/nearcore#3289]
The goal of this design is keep each pair of consecutive version compatible with each other

Most notable elements to take into account:

1. Which type of message each version is using in the function `send_handshake`
2. Which type of handshake is it able to deserialize.
3. What are the response to each type of handshake.

**Step 1**:

1. It is using old version of Handshake
2. It is able to deserialize both old version of Handshake and HandshakeV2
3. It doesn’t respond at all if the new version is newer than the protocol error (this was a bug that can’t be fixed now)

**Step 2**:

1. It is using HandshakeV2 with a caveat. Instead of sending version=35, it is using version=34 so it is accepted by previous node.
    From a network point of view this is no problem, in version 35 all changes introduced were related to runtime, and they will became active when certain threshold of nodes running version 35 is surpassed.
2. It is able to deserialize both old version of Handshake and HandshakeV2
3. It responds with VersionNotSupported if the version is too high (for both Handshake and HandshakeV2)

**Step 3**:

1. It will use Handshake (but with newer layout, and version=36), it will fallback to use HandshakeV2 when required
    If it receive version not supported (from a node with version 34/35) it will fallback to use HandshakeV2 with version=34.
2. It is able to deserialize both old version of Handshake and HandshakeV2
3. It responds with VersionNotSupported if the version is too high (for both Handshake and HandshakeV2)

**Step 4**:

1. Will only use Handshake (not fallback to HandshakeV2 which will be deprecated)
2. Will only be able to deserialize Handshake
3. It responds with VersionNotSupported if the version is too high (for Handshake only)

**Comment by bowenwang1996** [comment]
Thanks for documenting this 🚀

**Comment by nearmax** [comment]
Converting it from discussion and renaming it. The remaining work for @mfornet is to monitor that the upgrades are done as described above.

**Comment by bowenwang1996** [comment]
Already done
