### ISSUE TITLE
Thread main panicked at AVX support

### ISSUE THREAD

**Issue by Avadon** [near/nearcore#3300]
**Describe the bug**
Thread 'main' panicked at 'AVX support is required in order to run Wasmer VM Singlepass backend.', runtime/near-vm-runner/src/wasmer_runner.rs:196:9

**To Reproduce**
It was one time, so I couldn't find a pattern or a way to reproduce it

**Expected behavior**
Stable work of nearcore

**Screenshots**
![alt text](https://i.ibb.co/cQ7BYdq/Screen-Shot-2020-09-09-at-11-34-34.png "Log screen")

**Version:**
- nearcore - docker image nearprotocol/nearup:0.4.2
- docker 19.03.12, build 48a66213fe
- betanet

**Additional context**
The issue happened on a server with 2 CPU Intel Xeon CPU E5-2650 v2 @ 2.60GHz. **lscpu | grep "avx"** output:

> Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti fsgsbase smep erms xsaveopt arat

[betanet.log](https://www.dropbox.com/s/z2an77obcfnmo7p/betanet.log?dl=0)

**Comment by olonho** [comment]
Is it lscpu on the host or in container?

**Comment by Avadon** [comment]
Inside docker container. On the host machine:

> Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Comment by olonho** [comment]
Could you please upload the docker image somewhere?

**Comment by Avadon** [comment]
It's not a custom image, it's an official one - https://hub.docker.com/r/nearprotocol/nearup

**Comment by olonho** [comment]
And you always see this crash?

**Comment by Avadon** [comment]
Surprisingly it was just 1-2 times in today's morning. Since that everything runs smoothly.

**Comment by olonho** [comment]
Is it always the same machine/OS? Because check that fails checks rather basic CPU capability, and either here or not.

**Comment by olonho** [comment]
What command do you execute inside image?

**Comment by Avadon** [comment]
> Is it always the same machine/OS? Because check that fails checks rather basic CPU capability, and either here or not.

Yes, it's always the same.

> What command do you execute inside image?

nearup run betanet

**Comment by bowenwang1996** [comment]
Outdated
