### ISSUE TITLE
Adjust the fees for new hardware requirements

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3329]
We have bumped hardware requirements for our validators: https://docs.near.org/docs/roles/validator/hardware#machine-specifications

This does not change how many CPU instructions each runtime operation takes, however it might change how many CPU instructions fit into 1 second of computation.  As the result all fees need to be rescaled proportionally. 

Assigning to @olonho to triage and reassign to someone in Contract Runtime team.

**Comment by bowenwang1996** [comment]
@olonho what is the status of this issue?

**Comment by bowenwang1996** [comment]
Superseded by #4461 and #4561
