### ISSUE TITLE
Research including disk cost into param estimator tool

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3336]
Currently, param estimator tool only counts the number of userland CPU instructions for estimation of operation fees. It however, does not account for the cost of reading from the disk. We need to research different ways for on how we can account for it. This issue tracks only the research part and does not track the implementation part.

**Comment by bowenwang1996** [comment]
@olonho is this already done?

**Comment by bowenwang1996** [comment]
@matklad @olonho ?

**Comment by matklad** [comment]
Probably obsoleted by https://github.com/near/nearcore/issues/4474. We do have infra for measuring IO costs, but we haven't actually rolled out the fees using this infra.
