### ISSUE TITLE
Implement meta-transactions flow in EVM

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3338]
As explained here: https://github.com/nearprotocol/NEPs/pull/106#issuecomment-691337854 we want to support meta-transactions in our EVM. @ilblackdragon estimated that it will take 4 days to implement.

**Comment by ailisp** [comment]
@djsatok how to "reference" #3734 to this issue?

**Comment by djsatok** [comment]
@artob is this still relevant? I believe no, taking into account taken approach with the base token.

**Comment by ilblackdragon** [comment]
This is implemented.
