### ISSUE TITLE
[Tracking issue] Implement calling NEAR from EVM

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3339]
As discussed here: https://github.com/nearprotocol/NEPs/pull/106#issuecomment-686808411 and allegedly already prototyped by @ilblackdragon , we need a way for EVM contacts to be able to call NEAR contracts. Since design has been already discussed it is a matter of implementation and @ilblackdragon estimates it to take 2 days.

**Comment by djsatok** [comment]
Closed as duplicate #3449
