### ISSUE TITLE
[Tracking issue] GHSA-qgwh-g5gr-8mxg

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3350]
This is a tracking issue for https://github.com/nearprotocol/nearcore/security/advisories/GHSA-qgwh-g5gr-8mxg . It is a separate issue so that we can add it to Milestones and Zenhub.

**Comment by bowenwang1996** [comment]
Investigation is done. Will address it in https://github.com/near/nearcore/issues/3458
