### ISSUE TITLE
Write Runtime Specification

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3357]
Our current Runtime implementation is quite complex, and it is getting increasingly more complex with addition of implicit accounts and native EVM. At the same time, other projects like Rosetta, Indexer, and Contract Runtime, require deep and precise understanding of internal functions of the runtime. Unfortunately, most of this knowledge is currently locked in @evgenykuzyakov and @nearmax 's heads. Also, the current runtime specification https://nomicon.io/RuntimeSpec/README.html is far from complete and hard to use.

**Comment by bowenwang1996** [comment]
It is broken down into multiple smaller ones in the NEP repository and some of them are already done:
* https://github.com/near/NEPs/issues/212
* https://github.com/near/NEPs/issues/198
* https://github.com/near/NEPs/issues/195
* https://github.com/near/NEPs/issues/191

I suggest that we close this issue in favor of smaller ones.
