### ISSUE TITLE
Reorganize primitives and dedup with runtime utils

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3384]
We have primitives cargo, which grew outside of it's original intention.

Given requirement to have WASM compilable primitives, we should reorganize to move all the non primitive stuff (especially, one that doesn't compile to WASM) out. 

Runtime now has tons of it's own utils that should be then merged back when primitives is cleaned up.

**Comment by bowenwang1996** [comment]
looks like it is already done with the introduction of `primitives-core`

**Comment by mina86** [comment]
This isn’t done yet.  For example:

```
$ gg pub\ mod\ u128_dec_format\\b
core/primitives-core/src/runtime/fees.rs:309:pub mod u128_dec_format {
core/primitives-core/src/serialize.rs:145:pub mod u128_dec_format {
runtime/near-vm-logic/src/serde_with.rs:111:pub mod u128_dec_format {
```

There’s bunch of duplicate code dealing with serialisation.
