### ISSUE TITLE
RPC API versioning and re-design

### ISSUE THREAD

**Issue by vgrichina** [near/nearcore#3395]
We need to introduce API versioning to support breaking API changes like https://github.com/nearprotocol/nearcore/pull/3204

There are multiple ways to pass API version. However specifying it in URL is likely the easiest to use in every context (i.e. including curl and other manual ways to query), basically something like this:

```
https://rpc.testnet.near.org/v2.0/status
```

Given that we are introducing new API version anyway – it might be good time to simplify some other things about API:
- Remove JSON-RPC wrapper. We don't seem to be doing anything useful with it. E.g. it has it's own layer for errors but we are not using it anyway (using our own custom encoding as discussed in https://github.com/nearprotocol/nearcore/pull/3204)
- Custom error JSON response should come with corresponding HTTP error code as well. This makes handling non-specific errors much easier on client-side + plays well with all middleware like proxy servers/status monitoring/etc.
- All readonly queries should be `GET` requests. Then requests become much simpler.

For example:

```
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
  params:='{
    "request_type": "view_account",
    "finality": "final",
    "account_id": "near.test"
  }'
```

becomes

```
http get https://rpc.testnet.near.org/v2/account/near.test?finality=final
```

This seems like small difference, but it is basically difference between being able to use any HTTP client to access API without any specific support (or using some RESTful API sugar) and having to provide client library specific to given language.

**Comment by bowenwang1996** [comment]
@frol what is the status of this issue?

**Comment by frol** [comment]
There is no active phase of implementing new version of API just yet, so we can probably close it for now and re-open or create a new one once we decide to reorganize things

**Comment by frol** [comment]
More context, just for the future reference: https://near.zulipchat.com/#narrow/channel/295302-general/topic/OpenRPC.3A.20What.20It.20Is.2C.20Where.20We.20Are.2C.20and.20Why.20It.20Matters/with/577046208
