### ISSUE TITLE
BUG: Actix doesn't guarantee fairness when processing different messages inside one client actor

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3406]
I noticed that in Actix current implementation of futures, Actix will continue reading messages until given channel is empty. During that time no other messages or trigger will execute.
This change requires either submitting a hotfix to Actix or creating our own Actix branch.

**Comment by bowenwang1996** [comment]
From actix's perspective is this a bug or a feature?

**Comment by pmnoxx** [comment]
Actix doesn't make any claims about fairness guarantees. I suppose this could be considered as adding a new feature.

The issue is with how one particular async function is implemented in Actix. It's implementation can be changed in order to add fairness guarantees.

**Comment by pmnoxx** [comment]
We decided to go with a different approach.

Instead we moved out routing table calculation out of `PeerManager` (https://github.com/near/nearcore/issues/4859) and we will me adding tracking memory usage / limiting number of messages that are "being processed" that come from each peer (https://github.com/near/nearcore/issues/5155)
