### ISSUE TITLE
Implement --download-config flag which overrides the config, as --download-genesis does

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#3415]
We have support for --download-genesis which downloads testnet or betanet config and overrides it, we want to have some logic for config.json.

**Comment by bowenwang1996** [comment]
@chefsale what is the status of this issue?

**Comment by chefsale** [comment]
Not, implemented yet, but plan to do so in near future.

**Comment by chefsale** [comment]
Implemented the download-config flag in this PR: https://github.com/near/nearcore/pull/4427

cc: @mhalambek @bowenwang1996 @frol
