### ISSUE TITLE
Upgrade `DeleteAccount` action to generate regular transfer

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3421]
Currently `DeleteAccount` action generates a refund. A refund can't create an implicit account.
If we switch it to generate regular accounts, then beneficiary receiver account can be created. This allows to support UTXO like transactions on NEAR. Where every transaction on an implicit account instead a `Transfer` and `DeleteAccount` action that removes current account and splits the amount into a receiver and the remainder. The order of the receiver and the remainder can be randomized.

- [ ] Create a NEP for the proposal
- [ ] Implement a protocol upgrade
- [ ] Commit NEP and update the spec.

**Comment by nearmax** [comment]
As discussed today, this proposal does not explain what is the benefit of this feature, and given that it makes the protocol more complex it shouldn't have been implemented. Since this feature has already caused problems for NEAR network, @bowenwang1996 decided to revert it.
