### ISSUE TITLE
Investigate memory leak in mainthread/peermanager.

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3431]
Previously I added a measurement of memory usage in `neard`.
I noticed that in a day the memory usage grew from 1.2gb to 3.9gb. That's 2.7gb increase.
Meanwhile allocated memory by Rust code grew from 500mb (600mb mapped) to 1.4gb (1.7gb mapped).
main thread:  872151 allocations 593 mb  (up from 25275 / 49mb)
peermanager: 37890 allocations 275 mb (up from 8566/28mb)
33 peer actors: 55 allocations each, total 503mb. (up from 29 peer actors / 55 allocations / 422mb) 
other threads use less than 20mb

Meanwhile RocksDB usage went up from 50 mb to 322mb.

I want to investigate on where the memory leak is happening on the main thread, and also why peer manager usage went up.

**Comment by pmnoxx** [comment]
https://stackoverflow.com/questions/262439/create-a-wrapper-function-for-malloc-and-free-in-chttps://stackoverflow.com/questions/6083337/overriding-malloc-using-the-ld-preload-mechanism

**Comment by bowenwang1996** [comment]
@pmnoxx is the leak in peer manager addressed?

**Comment by bowenwang1996** [comment]
@pmnoxx any updates on this?

**Comment by pmnoxx** [comment]
@bowenwang1996 I'll run a node and check if there are any new leaks. We fixed it once, but there could be new ones.
