### ISSUE TITLE
Add Balancer truffle tests into nightly test

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3450]
We have running Balancer's tests here - https://github.com/ilblackdragon/balancer-core/pull/1

We should run them in the nightly test to make sure that EVM + web3 provider continues to function.
Also later we can add more contracts / setups there.

**Comment by ailisp** [comment]
Status: Mike has about 9 test failed. I'm not even not able to get test running, stuck infinitely after create 4 testing accounts and before deploy evm contracts

**Comment by ailisp** [comment]
@artob and @mikedotexe is going to look how to make all truffle tests pass. Please let me know when you success so i can make a script and add to nightly

**Comment by artob** [comment]
@ailisp The CryptoZombies tests fixed in #3624. I'm working on adding more tests. I believe @mikedotexe is working with the Balancer tests.

**Comment by artob** [comment]
FYI, as @mikedotexe was occupied elsewhere, I'm working on fixing the Balancer tests in #3665.

**Comment by artob** [comment]
All right, @mikedotexe and I have collaborated to investigate and fix the issues with the Balancer test suite, and all tests now pass (#3665). Our customizations to the test suite are pending upstream submission at https://github.com/near/balancer-core/pull/1.

@ailisp Will you have time soon to add the Balancer tests to the nightly test, or should @mikedotexe or I take this over?

**Comment by ailisp** [comment]
@artob Just about to asking this! I can add it. After following #3665, is current way of running it by:
- merge https://github.com/near/balancer-core/pull/1
- then truffle test from there?

**Comment by artob** [comment]
@ailisp Yes, that's pretty much it. However, given https://github.com/near/nearcore/issues/3665#issuecomment-738784633, you probably want to use @mikedotexe's `package-lock.json` which is known to work. If you just do an `npm install` from scratch, you are likely to see the same problems that I did. I'll send the file over privately.

**Comment by artob** [comment]
@ailisp Do you still plan to tackle this task, or should we reassign it?

**Comment by artob** [comment]
Fixed in #3763.
