### ISSUE TITLE
Support blockhash API

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3456]
Currently we return hash of 0x0 for `blockhash` API for Solidity.

Challenge with this, is that we don't have access to blocks data at all from `NearExt`.

**Comment by ilblackdragon** [comment]
Also given most of the times, this used for randomness and time in Ethereum, it may be useful to add separate precompiles for those two things.

**Comment by ilblackdragon** [comment]
Alternative, is to raise Invalid instruction.

**Comment by bowenwang1996** [comment]
> Challenge with this, is that we don't have access to blocks data at all from NearExt.

Why is it not possible to pass it to `NearExt`?

**Comment by frankbraun** [comment]
On the [weekly update 2021-02-26](https://github.com/near/nearcore/discussions/4019) @abacabadabacaba suggested that we use a "simulated blockhash" for this. For example, we could simply hash the block height (`block.number`) to get a unique block hash for every block.

I think that makes sense. However, we could have EVM contracts deployed on multiple shards in the future, or even in the same shard. Therefore, in order to have unique block hashes for every EVM, I suggest something like this: `blockhash = hash(account_id|block.number)` where `account_id` is the account identifier the EVM is deployed under.

**Comment by nearmax** [comment]
I suggest to use `hash(account_id, block.hash)` as EMV hash to take care of potential rare situation where we have short-term NEAR fork.

**Comment by joshuajbouw** [comment]
@nearmax I'm addressing this in #4256. Did you mean to have the `hash(account_id, block_hash)` as part of the EVM? For sake of consistency, I think its fine for the `vm_logic` just to return the `block_hash` from `VMContext`.

**Comment by ilblackdragon** [comment]
@joshuajbouw `block.blockhash(uint blockNumber) returns (bytes32)` in Solidity takes the block number up to 256 most recent.

I remember the idea by @abacabadabacaba was discussed to completely simulate `blockhash` in a deterministic way. 
Is that not correct? Otherwise your PR should be modified to also return block hashes based on block index (up to last 2 epochs) on something like that.

**Comment by joshuajbouw** [comment]
@ilblackdragon right but it was suggested to instead do `hash(account_id, block.hash)` as per @nearmax's comment given the rare situation where we could have a short-term NEAR fork.

**Comment by ilblackdragon** [comment]
The problem is not in how to prevent hash of NEAR's block.
The problem is having hashes for the past blocks.

So I thought the idea was to implement via contract to maintain last computed hash in the state and update on the call with the current `block_index` and a random number (pretty much storing last 256 hashes). This way it's unique for any fork and state maintains this and hash last 256 with some overfill.

I'm not against adding block hash of the current block to host functions on NEAR - my point is that it doesn't solve this issue.

**Comment by bowenwang1996** [comment]
> So I thought the idea was to implement via contract to maintain last computed hash in the state and update on the call with the current block_index and a random number (pretty much storing last 256 hashes). This way it's unique for any fork and state maintains this and hash last 256 with some overfill.

This is similar to what I suggested to @artob, but Arto wanted to have one unique hash per NEAR block. Since block heights are not necessarily consecutive, we don't know how many blocks elapse between two evm invocations unless we expose block ordinal.
