### ISSUE TITLE
Include contract input into EVM gas cost

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3461]
Following @ilblackdragon 's comment: https://github.com/nearprotocol/nearcore/pull/3299#issuecomment-703881207 we need to include input into gas cost evaluation of EVM.

**Comment by ailisp** [comment]
Did this today, but the cost difference in cpu instructions are very small, and convert this number to evm gas it's close to 0.

**Comment by ailisp** [comment]
elaborated by #3552
