### ISSUE TITLE
InfoHelper memory stats: print retained memory info

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#3476]
Discovered in https://github.com/nearprotocol/nearcore/issues/3063#issuecomment-705888807:
InfoHelper prints memory used by the process, but some of it is free pages retained by the allocator.
We can include that in the output: http://jemalloc.net/jemalloc.3.html#stats.mapped 

>  stats.mapped (size_t) r- [--enable-stats]
> 
> Total number of bytes in active extents mapped by the allocator. This is larger than stats.active. This does not include inactive extents, even those that contain unused dirty pages, which means that there is no strict ordering between this and stats.resident.

> stats.retained (size_t) r- [--enable-stats]
> 
> Total number of bytes in virtual memory mappings that were retained rather than being returned to the operating system via e.g. munmap(2) or similar. Retained virtual memory is typically untouched, decommitted, or purged, so it has no strongly associated physical memory (see extent hooks for details). Retained memory is excluded from mapped memory statistics, e.g. stats.mapped. 

>  opt.retain (bool) r-
> 
> If true, retain unused virtual memory for later reuse rather than discarding it by calling munmap(2) or equivalent (see stats.retained for related details). It also makes jemalloc use mmap(2) or equivalent in a more greedy way, mapping larger chunks in one go. This option is disabled by default unless discarding virtual memory is known to trigger platform-specific performance problems, namely 1) for [64-bit] Linux, which has a quirk in its virtual memory allocation algorithm that causes semi-permanent VM map holes under normal jemalloc operation; and 2) for [64-bit] Windows, which disallows split / merged regions with MEM_RELEASE. Although the same issues may present on 32-bit platforms as well, retaining virtual memory for 32-bit Linux and Windows is disabled by default due to the practical possibility of address space exhaustion.

**Comment by bowenwang1996** [comment]
@pmnoxx do you mind addressing this issue?

**Comment by pmnoxx** [comment]
I already implemented printing those statistics inside https://github.com/near/nearcore/pull/3319
