### ISSUE TITLE
Archival node syncing crashes on initial "Downloading blocks 0%"

### ISSUE THREAD

**Issue by frol** [near/nearcore#3477]
**Describe the bug**

Our fresh mainnet and betanet archival node died syncing blocks (stuck for 11 hours and died with "out of memory" on 16GB RAM server).

**To Reproduce**

1. Start a fresh archival node (`"archive": true` in the `config.json`) for mainnet and wait until all the headers are synced
2. The node gets stuck and no logs are printed for hours (see screenshot)
3. Ultimately, the node gets killed for running out of memory

**Expected behavior**

It should sync just fine without glitches.

**Screenshots**

![image](https://user-images.githubusercontent.com/304265/95553937-bbed8b80-09e5-11eb-94f8-bb8b7d71b942.png)

**Version (please complete the following information):**
- nearcore commit/branch: e76b8dd1f7aca44e348844303d290c3b9c9a4387 (we build Indexer for Explorer based on this exact commit, but I don't think Indexer is the cause since Indexer just sits waiting until the node is fully synced)
- docker (if using docker): native host Debian 10.6
- mainnet, betanet

**Comment by bowenwang1996** [comment]
I tried with both https://github.com/nearprotocol/nearcore/commit/e8738ab4a9d3f5e30b57611dc1ff56b4bd63e2a0 and https://github.com/nearprotocol/nearcore/commit/9fa9b815. In both cases the node does not get stuck and is able to sync blocks. I also didn't see any unusually high memory consumption. Are you running this locally?

**Comment by frol** [comment]
I was on GCP instance. There was nothing more I could collect about this issue

**Comment by bowenwang1996** [comment]
> I was on GCP instance. There was nothing more I could collect about this issue

Okay I'll try to run indexer to see if it works

**Comment by frol** [comment]
@bowenwang1996 well, I just noticed that our betanet indexer also died the same way, so you can ssh into `khorolets@betanet-indexer-for-explorer-node0` instance if you have any ideas what can help you to debug it. I left it as is there (`tmux attach`). /cc @khorolets

**Comment by chefsale** [comment]
Same happened on another archival node today on betanet-nearup4.

**Comment by bowenwang1996** [comment]
@khorolets it appears to me that this happens because you are not using SSD. The node is trying to do around 10m reads and that is too much for HDD :)

I suggest that you do the following:
1. change machine spec to use SSD and have at least 500GB of disk space
2. Allow verbose logging in indexer so that it is easier for me to debug.

**Comment by chefsale** [comment]
Hmm, i have seen the same bahaviour on one of the betanet machines though, so not sure why did it happen there?

**Comment by frol** [comment]
@bowenwang1996 It is unclear how IO can lead to excessive RAM usage :thinking:

**Comment by bowenwang1996** [comment]
On betanet it is likely caused by no node having the entire history. If this issue is about betanet we can close it since betanet will be repurposed soon. If the issue is about mainnet and it still persists, please let me know

**Comment by frol** [comment]
I originally observed it on mainnet, but I have no idea if it still persists. I can close this issue for now as you are already aware that our syncing implementation is suboptimal and I would not be surprized to see all sorts of corner cases.
