### ISSUE TITLE
Weird behaviour of ExecutionOutcome

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#3478]
**Describe the bug**
I’ve been running Indexer for testnet and got into weird situation.

Indexer was unable to handle ExecutionOutcome for receipt `6gGEKfo9eJ3KQvJcrork82QZ8RcZS9ZFs5rifwC9uej7`

Here’s the ExecutionOutcome

```
{
  "proof": [],
  "block_hash": "VBGfsfX538gamd9SH52M32Da8mTduwZTcqKCFuwMNkm",
  "id": "6gGEKfo9eJ3KQvJcrork82QZ8RcZS9ZFs5rifwC9uej7",
  "outcome": {
    "logs": [],
    "receipt_ids": [],
    "gas_burnt": 0,
    "tokens_burnt": "0",
    "executor_id": "eth2nearrelay10.testnet",
    "status": {
      "SuccessValue": ""
    }
  }
}
```

Pay attention to `block_hash`

RPC call for block by hash returns the information about the block at height `19165379`

RPC call for block by height returns `"DB Not Found Error: BLOCK HEIGHT: 19165379 \n Cause: Unknown"`

So the block with this height not included in chain. But somehow in the other block we’ve received the ExecutionOutcome with `block_hash` of not included block.

Is it expected behaviour or is it a bug? 

Let me know if I can add anything else to help investigate it.

**Expected behavior**
ExecutionOutcome `block_hash` can't be equal the block not included in chain

**Version (please complete the following information):**
- nearcore e76b8dd1f7aca44e348844303d290c3b9c9a4387 (built Indexer for Explorer on that commit)
- testnet

/cc @frol

**Comment by frol** [comment]
@evgenykuzyakov @bowenwang1996 Can you shed some light on this issue, please?

**Comment by bowenwang1996** [comment]
> Is it expected behaviour or is it a bug?

It is expected. When you query block by height, it always search for block on the canonical chain and forks are not considered. However, when you query block by hash, you can query blocks on forks. Feel free to close the issue if that answers your question

**Comment by frol** [comment]
That does not answer our question. The question is why execution outcome from a canonical chain refer to a block that is not on the canonical chain, and how to deal with that

**Comment by bowenwang1996** [comment]
Oh I see. Sorry that I misread the question. I am actually working on fixing this
