### ISSUE TITLE
Return non 200 for health rpc endpoint when the node is syncing

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3492]
It suffices to return an error in the handling of `Status` message in `ClientActor` when `is_health_check` is true. This will greatly help with rpc load balancer to auto remove nodes that should not serve rpc.

**Comment by frol** [comment]
@bowenwang1996 I want to remind you that we already tried to disable RPC serving if a node is in syncing mode (#3059), and it failed miserably. Had we changed anything to the fact that a node goes into "syncing" state even if it is just a few blocks behind?

**Comment by bowenwang1996** [comment]
@frol that should not matter. The point is that if health check failed the load balancer will auto remove the nodes so that the requests will not even get there. What failed before is that we still allow the requests to get to the node and return an error there, which is very confusing.

**Comment by frol** [comment]
@bowenwang1996 we may end up with all nodes removed from the load balancing... load balancer might not be quick on bringing back the excluded nodes.

**Comment by bowenwang1996** [comment]
@frol I think it is very unlikely and when that happens, it indicates that something is seriously wrong and I don't think the current setup is better in that situation.
