### ISSUE TITLE
Non-archival node was killed after quite long time

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#3496]
**Describe the bug**
I have Indexer for Wallet (commit we've used to build e8738ab4a9d3f5e30b57611dc1ff56b4bd63e2a0) running for quite long time. Suddenly it started to sync and was killed after using all the CPU (4) and RAM (15 GB)

**To Reproduce**
Don't know how to reproduce it was running for at least a week before it happened

**Expected behavior**
Expected to be running smoothly and don't be killed suddenly

**Screenshots**
![image](https://user-images.githubusercontent.com/3235740/96225847-604d7000-0f9a-11eb-9b51-6fd3b4bb0ff9.png)

**Version (please complete the following information):**
- nearcore commit e8738ab4a9d3f5e30b57611dc1ff56b4bd63e2a0
- testnet

**Comment by bowenwang1996** [comment]
Please update to this commit bf9ae4ce8c680d3408db1935ebd0ca24c4960884 and let me know if you still experience the same issue

**Comment by bowenwang1996** [comment]
@khorolets did this happen again? If not let's close the issue
