### ISSUE TITLE
Investigate memory leak by Rocksdb

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3510]
While investigating memory usage for `near`. I noticed that the memory usage for rocks db keeps growing.
`< func rocksdb/memory/arena.cc rocksdb::Arena::AllocateNewBlock(unsigned long) 557778947f28: 646.96MiB/167
< func rocksdb/table/block_fetcher.cc rocksdb::BlockFetcher::ReadBlockContents()  5577789bcc9c: 185.73MiB/10125
< func rocksdb/table/format.cc rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&, rocksdb::MemoryAllocator*)  5577789c0768: 367.29MiB/12864`

`>func rocksdb/memory/arena.cc rocksdb::Arena::AllocateNewBlock(unsigned long)  557778947f28: 699.23MiB/181
162,167c181,186
> func rocksdb/table/block_fetcher.cc rocksdb::BlockFetcher::ReadBlockContents()  5577789bcc9c: 192.00MiB/10472
> func rocksdb/table/format.cc rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&, rocksdb::MemoryAllocator*)  5577789c0768: 399.24MiB/14918 (edited)`

This seems to be related to https://github.com/facebook/rocksdb/issues/4112

I'll try first to limit the maximum number of open files, which is currently set to 512 to see if it helps.

**Comment by pmnoxx** [comment]
I tracked down where memory in RocksDB is being stored:
It turns out that rocksdb has caches, which are responsible for memory usage

cache 1:
(C) func rocksdb/memory/arena.cc rocksdb::Arena::AllocateNewBlock(unsigned long) 55d8c0841838: 333.72MiB/99

here is a chain of references to given memory:
rocksdb::Arena::AllocateNewBlock(unsigned long) 
rocksdb::ColumnFamilyData::ConstructNewMemtable(rocksdb::MutableCFOptions const&, unsigned long) 
rocksdb::ColumnFamilySet::CreateColumnFamily(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, rocksdb::Version*, rocksdb::ColumnFamilyOptions const&) 
rocksdb::VersionSet::ProcessManifestWrites(std::deque<rocksdb::VersionSet::ManifestWriter, std::allocator<rocksdb::VersionSet::ManifestWriter> >&, rocksdb::InstrumentedMutex*, rocksdb::FSDirectory*, bool, rocksdb::ColumnFamilyOptions const*)

cache 2:
(C) func rocksdb/table/block_fetcher.cc rocksdb::BlockFetcher::ReadBlockContents() 55d8c08b65ac: 913.16MiB/31262

here is a chain of references to given memory:
rocksdb::BlockFetcher::ReadBlockContents() 
rocksdb::Status rocksdb::BlockBasedTable::PutDataBlockToCache<rocksdb::Block>(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::CachableEntry<rocksdb::Block>*, rocksdb::BlockContents*, rocksdb::CompressionType, rocksdb::UncompressionDict const&, rocksdb::MemoryAllocator*, rocksdb::BlockType, rocksdb::GetContext*) const 

cache 3
(C) func rocksdb/table/format.cc rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&, rocksdb::MemoryAllocator*) 55d8c08ba078: 1230.38MiB/61429

here is a chain of references to given memory:
rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&, rocksdb::MemoryAllocator*) 
rocksdb::Status rocksdb::BlockBasedTable::PutDataBlockToCache<rocksdb::Block>(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::CachableEntry<rocksdb::Block>*, rocksdb::BlockContents*, rocksdb::CompressionType, rocksdb::UncompressionDict const&, rocksdb::MemoryAllocator*, rocksdb::BlockType, rocksdb::GetContext*) const

It theory we should be able to decrease memory usage by clearing data that's stored in `PutDataBlockToCache` cache, and `CreateColumnFamily` cache.

**Comment by bowenwang1996** [comment]
@pmnoxx what about the issue with `max_open_files`?

**Comment by pmnoxx** [comment]
@bowenwang1996

I started a new node with max_open_files setting set to 20 instead of 512. I already see that RocksDB is using around 500mb. There are no reasons which could indicate that the issue is fixed. I'll keep running the node for next 24h to see whenever  there is any affect or not.

**Comment by pmnoxx** [comment]
@bowenwang1996 I checked `RockDB` stats 7 hours after starting it. `RocksDB` is already using `1999.16MiB`.
Before I changed `max_open_file` to `20`. RocksDB was using only 700mb after 7 hours. Limiting the number of open files only made the issue worse.

**Comment by bowenwang1996** [comment]
I see. For the caches that you pointed to, do they have a limit in size?

**Comment by pmnoxx** [comment]
I'll create another issue for analyzing how those caches work.

**Comment by areyohrahul** [comment]
Hey @pmnoxx, were you able to solve this problem? Also, do you use JNI or CPP?
