### ISSUE TITLE
Add basic performance metrics.

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3512]
I've been working on analyzing memory usage in Rust, and I see that some of my changes affect performance.

It would get to have some basic performance metrics. Those include
1) cpu % utilization for each actor 
2) number/type of messages processed by each actor per minute
3) for each handle method in actor - number of calls, total time spend per minute, avg time, 50,10,1 percentiles.
4) optionally, max memory used during each call, this could measured at almost no cost, if we are fine adding extra 4 bytes to each allocation

In the future those stats would be great to include in graphana as well

**Comment by pmnoxx** [comment]
I posted a PR: https://github.com/near/nearcore/pull/3738

**Comment by bowenwang1996** [comment]
@pmnoxx let's close the issue when the PR is merged. Also github has keywords like "resolve" and "fix" that allows you to close the corresponding issue automatically when the PR is merged https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
