### ISSUE TITLE
How to start a normal node on the mainnet? Do not be a validator, only synchronize blocks and use rpc.

### ISSUE THREAD

**Issue by zenghq3** [near/nearcore#3515]
This is my startup method
```
git clone https://github.com/near/nearcore
cd nearcore
git checkout 1.13.2
cargo build -p neard --release
target/release/neard init --chain-id="mainnet"
target/release/neard run
```
Cannot find the peer node, and still prompt `INFO stats: # 9820210 Waiting for peers   0/0/40 peers ` for one hour.
 port 24567 has been opened.

**Comment by zenghq3** [comment]
After I added the peer node, he can synchronize. But it is stuck in 
`
INFO stats: # 9943039 Downloading headers 100%
`, 
and he no longer actively connects to the peer node after restarting, how to solve this problem?

**Comment by bowenwang1996** [comment]
> and he no longer actively connects to the peer node after restarting, how to solve this problem?

Do you mean there are no peers after you restart? Is there any error in the logs?
