### ISSUE TITLE
Scaling tps throughput with more shards

### ISSUE THREAD

**Issue by birchmd** [near/nearcore#3530]
Previous tests have shown max tps throughput remains constant with more shards instead of increasing as expected. The purpose of this issue is to investigate whether this is still true and if so find solutions to enable scaling up to a modest number of shards (e.g. 16).

**Comment by birchmd** [comment]
I ran an experiment where I linearly increase the number of transactions sent to the network as I increase the number of shards. I started with ~1000 tps, since this is what can be maintained by a single shard and increased in steps of ~500 tps. Overall, the network performed well. The nodes kept up with the load while maintaining a reasonable bps.

There is a linear decay in bps which starts after 5 shards, indicating this scaling could not continue forever (if this trend were to continue, bps would drop below 0.5 by 15 shards). (See plot below)

However, this test should an 8 shard network should easily be able to handle 4000 tps, and likely more than that in short bursts (the breaking point is something I could investigate more closely if desired).

![tps_vs_shards](https://user-images.githubusercontent.com/13788876/97455590-66364000-190e-11eb-8b89-82d9b6e54932.PNG)

Some notes about this experiment setup:
* There are 50 validators and 4 rpc nodes
* There is one seat per validator
* Seats are roughly evenly divided among shards
* Each validator node tracks only the shard it is assigned to (this is exactly one shard on each validating node), each rpc node tracks all shards
* Each test maintained the transaction load for 3 minutes, and the rates shown are averaged over this period

Since this set of experiments is short-lived in nature, I will next try a longer running test focusing on 8 shards. The goal is to confirm validators are not being kicked out for not producing enough chunks.

cc @bowenwang1996 @SkidanovAlex

**Comment by bowenwang1996** [comment]
@birchmd are we only sending transfer transactions? Also are transactions all sent through the rpc nodes? In addition I think it makes sense to measure the performance when there are 100 validators instead of 50

**Comment by birchmd** [comment]
This experiment uses only transfer transactions. Transactions are sent to all 54 nodes at a steady rate. Sure, I can run the same experiment with 100 validators and 100 seats.

**Comment by birchmd** [comment]
Update on whether validators are kicked out over the long term (with 8 shards):

* With the default config I found validators are kicked out for not producing chunks
* With the config settings listed below I found validators do not get kicked out (after running for 16 hours) and the bps stays around 1 without load, and 0.85 with load.

We could repeat the test to see if we can refine the bounds on the `max_*` settings, but I think the `min_block_production_delay` increase is important. I suspect the reason validators could be kicked out before is that some nodes with a faster connection between them could get ahead of the other nodes (because the min block production time was lower), then when it came time for one of the slower nodes to produce a chunk they were not fully up to date with the state, so did not produce a chunk in time for it to propagate to the block producer. With a longer minimum block production time, nodes with faster connections cannot get ahead.

Increasing the max may have helped too in the occasional cases of network lag, but a bps of ~1 was maintained during the whole test, so I think the minimum block production time increase was more important.

Settings used in the test where no validators were kicked out:

```diff
     "min_block_production_delay": {
-      "secs": 0,
-      "nanos": 600000000
+      "secs": 1,
+      "nanos": 0
     },
     "max_block_production_delay": {
-      "secs": 2,
+      "secs": 4,
       "nanos": 0
     },
     "max_block_wait_delay": {
-      "secs": 6,
+      "secs": 8,
       "nanos": 0
     },
```

Today I will repeat the load testing experiment with 100 validators and 100 seats.

**Comment by bowenwang1996** [comment]
> Increasing the max may have helped too in the occasional cases of network lag, but a bps of ~1 was maintained during the whole test, so I think the minimum block production time increase was more important.

Agree. Have you tried 800ms instead of 1s? That is the number we use for mainnet.

> This experiment uses only transfer transactions. Transactions are sent to all 54 nodes at a steady rate. Sure, I can run the same experiment with 100 validators and 100 seats.

Are blocks saturated in the experiment? I'd like to see what happens if we send function call transactions instead of transfers.

**Comment by birchmd** [comment]
> Have you tried 800ms instead of 1s? 

No, but I can do that test as well.

> Are blocks saturated in the experiment?

If doubling the number of shards doubles the gas capacity, then no, they are not saturated. For example, at 8 shards, there are ~5100 transactions (just transfers for now) per block. If the capacity is ~2000 transactions per shard, then the block is only ~40% filled. I can hit the nodes with more transactions per second, though I expect this will impact bps. The initial results already show a linear decline in bps after 5 shards, and I expect that degradation would be faster with more transactions.

> I'd like to see what happens if we send function call transactions instead of transfers

Sure, we can do that. Do you have specific functions in mind? In the mocknet load test we have today there is the do-nothing bubble sort function.

**Comment by bowenwang1996** [comment]
> If doubling the number of shards doubles the gas capacity, then no, they are not saturated. For example, at 8 shards, there are ~5100 transactions (just transfers for now) per block. If the capacity is ~2000 transactions per shard, then the block is only ~40% filled. I can hit the nodes with more transactions per second, though I expect this will impact bps. The initial results already show a linear decline in bps after 5 shards, and I expect that degradation would be faster with more transactions.

So how many transactions do you send per second?

> Sure, we can do that. Do you have specific functions in mind? In the mocknet load test we have today there is the do-nothing bubble sort function.

We can use that as a starting point. Later on we can potentially add function calls to change state to see how it may affect the throughput.

**Comment by SkidanovAlex** [comment]
`min_block_production_time` is how much we wait before sending the endorsement, and should not affect kickouts.
Changing `max_block_production_time` should be sufficient, if the reason for kickouts is insufficient blocks.

If it's insufficient chunks, I need to double check how long we wait before producing the block if the chunks haven't arrived. I think it also depends on `max_block_production_time`, not `min`.

**Comment by birchmd** [comment]
> So how many transactions do you send per second?

The network was keeping pace with what I was sending, so you can see the tps in the plot above. I was changing the number of transactions sent per second as the number of shards increased. For 8 shards it was ~4300.

**Comment by birchmd** [comment]
> One extra thing to try is to make the tracing of the kickout reasons to be info level, and if we observe kickouts again, see why they happened.

I was tracking the kickouts. Sample output follows:

```
[
  {'account_id': 'node0', 'reason': {'NotEnoughChunks': {'produced': 82, 'expected': 100}}},
  {'account_id': 'node15', 'reason': {'NotEnoughChunks': {'produced': 76, 'expected': 85}}},
  {'account_id': 'node20', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node24', 'reason': {'NotEnoughChunks': {'produced': 89, 'expected': 100}}},
  {'account_id': 'node35', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node40', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node41', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node43', 'reason': {'NotEnoughChunks': {'produced': 73, 'expected': 86}}},
  {'account_id': 'node47', 'reason': 'DidNotGetASeat'}
]
[
  {'account_id': 'node2', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node36', 'reason': 'DidNotGetASeat'},
  {'account_id': 'node39', 'reason': {'NotEnoughChunks': {'produced': 74, 'expected': 86}}},
  {'account_id': 'node40', 'reason': {'NotEnoughChunks': {'produced': 87, 'expected': 100}}}
]
[
  {'account_id': 'node39', 'reason': {'NotEnoughChunks': {'produced': 84, 'expected': 100}}},
  {'account_id': 'node44', 'reason': {'NotEnoughChunks': {'produced': 77, 'expected': 86}}}
]
 [
  {'account_id': 'node12', 'reason': {'NotEnoughChunks': {'produced': 80, 'expected': 100}}},
  {'account_id': 'node27', 'reason': {'NotEnoughChunks': {'produced': 84, 'expected': 100}}},
  {'account_id': 'node31', 'reason': {'NotEnoughChunks': {'produced': 73, 'expected': 86}}},
  {'account_id': 'node44', 'reason': {'NotEnoughChunks': {'produced': 89, 'expected': 100}}}
]
```

Each list is a different instance of nodes being kicked out. You can see the main reason is 'not enough chunks' and as a result of these kickouts, some other validators lost their seats.

**Comment by birchmd** [comment]
> `min_block_production_time` is how much we wait before sending the endorsement, and should not affect kickouts.

I'm still not so sure about that. If 2/3 of validators can communicate with each other faster than the remaining 1/3, wouldn't sending approvals faster still mean the remaining 1/3 could lag behind just long enough that they occasionally miss getting their chunks to the block producer?

This is ultimately an experimental question though, so I can try running with a `min_block_production_time` equal to the default value and only change the max to see if I still observe kickouts or not, and if the bps is different or not.

**Comment by birchmd** [comment]
I repeated the same experiment that resulted in the graph from my initial comment, but this time with 100 validators as Bowen suggested. The result was not as good. The throughput TPS was significantly lower than the input TPS. However, the BPS remained consistent with the first experiment.

![tps_vs_shards_100](https://user-images.githubusercontent.com/13788876/97631755-d07edb80-1a07-11eb-8f7f-3935265e5581.PNG)

**Comment by birchmd** [comment]
I repeated the test (on 8 shards) where I see if validators get kicked out with 100 starting validators as well. Again I got a different result than when there were 50.

In the initial test with 50 validators I saw that the default configuration led to validators being kicked out from not producing enough chunks, and some due to not getting a seat. With the adjusted configurations I posted no validators were kicked during the test (~16 hours).

In the test with 100 validators I started with the configuration which worked for the 50 validator case. After about 20 minutes some validators were kicked out for not getting a seat, but no other reason. Then some validators were kicked out later for not making enough blocks; there was never a validator which was kicked out for not producing enough chunks. Setting the max block production delay to 6s still gave the same result.

**Comment by bowenwang1996** [comment]
> In the test with 100 validators I started with the configuration which worked for the 50 validator case. After about 20 minutes some validators were kicked out for not getting a seat, but no other reason.

That feels like the configuration may have been wrong.

> If it's insufficient chunks, I need to double check how long we wait before producing the block if the chunks haven't arrived. I think it also depends on max_block_production_time, not min.

@SkidanovAlex it depends on both

**Comment by bowenwang1996** [comment]
> I'm still not so sure about that. If 2/3 of validators can communicate with each other faster than the remaining 1/3, wouldn't sending approvals faster still mean the remaining 1/3 could lag behind just long enough that they occasionally miss getting their chunks to the block producer?

There is an additional wait for chunks to arrive after sufficient approvals have arrived, but looks like that may have been too small.

**Comment by birchmd** [comment]
@bowenwang1996 I tried turning off inflation to avoid validators losing seats as you suggested, but the same thing happened, and at around the same time too (~1000 seconds into the run).

Genesis config diff:
```diff
   "protocol_reward_rate": [
-    1,
-    10
+    0,
+    1
   ],
   "max_inflation_rate": [
-    1,
-    20
+    0,
+    1
   ],
```

Output from `prev_epoch_kickout`:

```
[{'account_id': 'node13',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node20',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node34',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node36',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node45',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node48',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node58',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node65',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node84',
 'reason': 'DidNotGetASeat'},
 {'account_id': 'node99',
 'reason': 'DidNotGetASeat'}]
```

**Comment by birchmd** [comment]
I am closing this issue since it is now the end of this cycle. New issues have been created to capture follow-up for this issue (listed below). @SkidanovAlex @bowenwang1996 please let me know if I've missed any questions we want to have answered.

https://github.com/near/nearcore/issues/3545
https://github.com/near/nearcore/issues/3546
https://github.com/near/nearcore/issues/3547
https://github.com/near/nearcore/issues/3548
