### ISSUE TITLE
Change CI to include tests for nightly protocol features

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3538]
Currently CI only runs cargo tests without any flags and with the introduction of nightly protocol features, we want tests that are guarded by a nightly protocol feature flag also be run in CI to ensure the correctness of the protocol feature. More specifically, we want do
```
cargo test --all --features nightly_protocol --features nightly_protocol_features
```
which will run tests with all nightly features enabled.

**Comment by chefsale** [comment]
So currently this doesn't seem to be the case that we just run cargo test, it some super complicated script which I don't understand:

https://github.com/near/nearcore/blob/master/scripts/parallel_run_tests.py

I'm not sure, why are we using this script to test of just using:
```
cargo test
```
in the first place?

cc: @ailisp @bowenwang1996

**Comment by ailisp** [comment]
First it must be `cargo test --workspace` to include all tests. Then cargo test --workspace is much slower and have a very high chance to fail because it doesn't isolate port of nodes in integration test and run them in parallel

**Comment by chefsale** [comment]
So, in that case I could add the flags `--all --features nightly_protocol --features nightly_protocol_features`
here:
https://github.com/near/nearcore/blob/7e04c063c82a00c3ff0fbbcd0701f13d363082f4/scripts/testlib.py#L27
when nigthly flag is passed.

Also, why are we using `--workspace` instead of `--all`?

**Comment by ailisp** [comment]
all is depreciated in favor of workspace
        --all                                        Alias for --workspace
(deprecated)
