### ISSUE TITLE
Test request: upgradability

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3543]
We need to introduce a test that checks that the upgraded binary produces blocks with the current master.

Let's take the current master branch and run a network for a bit. Then upgrade one of the nodes to the new PR node binary and make sure it still produces blocks with the master branch.

Ideally we throw traffic at this network that includes basic transactions: 
- transfers
- creating accounts
- contract deploys
- function calls

With more nightly features coming, the master branch might have unexpected side-effects from the not very well guarded protocol changes.

**Comment by bowenwang1996** [comment]
Done in #3559
