### ISSUE TITLE
Can a sharded network handle many many transactions?

### ISSUE THREAD

**Issue by birchmd** [near/nearcore#3546]
Previously we investigated an issue where sending too many transactions to the network (>10k per second) would cause it to stall (reduce bps to < 0.2). This issue was resolved and now a single shard network can handle this extreme load without stalling. The purpose of this issue is to see if that is still true when there are 8 shards, and if not make the necessary changes so that the network remains stable under extreme load.

**Comment by birchmd** [comment]
I ran several tests where an 8 shard network was receiving ~15k tps for a three minute period, and was able to maintain ~5k throughput tps with ~0.3 bps.

**Comment by bowenwang1996** [comment]
@birchmd is it with 50 validators or 100 validators?

**Comment by birchmd** [comment]
That was with 100 validators. I also thought it was interesting it managed to hit 5k throughput when we have seen that it does not if there is 5k input transactions.

For the purposes of this issue, I think the test result is sufficient for closing, we see the network maintains a reasonable performance under extreme loads. But clearly there is more investigation to be done with regards to throughput under more normal conditions. I am also still investigating the mysterious kickout issue.

**Comment by bowenwang1996** [comment]
@birchmd do validators also get kicked out in this case?

**Comment by birchmd** [comment]
I don't run the test long enough to see validators being kicked out. The load is only maintained for 3 minutes, and the network is taken down shortly after. I don't think it makes sense to look at validators being kicked out under other conditions until we get to the bottom of the issue where they are being kicked out for no reason.

**Comment by birchmd** [comment]
Closing this issue for this cycle. Work related to validator kickout will be continued in https://github.com/near/nearcore/issues/3547
