### ISSUE TITLE
Obtain a Full Archive Node DB Snapshot from the NEAR Blockchain

### ISSUE THREAD

**Issue by fmanea** [near/nearcore#3549]
The current genesis on mainnet starts syncing from block 9M

Does anyone have a snapshot of the DB starting from block 0 that can be shared?

Maybe a link from a storage site or a torrent would do the trick.

Thank you

@frol @chefsale

**Comment by bowenwang1996** [comment]
> Does anyone have a snapshot of the DB starting from block 0 that can be shared?

No. Genesis height is 9820210

**Comment by frol** [comment]
@bowenwang1996 I should have communicated this better. @mhalambek is already working on providing the public snapshots of archival nodes

**Comment by fmanea** [comment]
Hello @mhalambek ,

Do we have any ETA on this request?

**Comment by mhalambek** [comment]
https://near-protocol-public.s3.ca-central-1.amazonaws.com/mainnet/archive/latest.zip

**Comment by frol** [comment]
@mhalambek Thank you!

@fmanea Thank you for raising this concern! I am sorry it took us so long. The team is working on also providing dumps in tar-archives as well as dumps of non-archival data.

**Comment by fmanea** [comment]
Thank you very much guys,

Will give it a try in the following days and give you feedback about the outcome,

Have a nice day!

**Comment by bowenwang1996** [comment]
Looks like this can be closed

**Comment by frol** [comment]
@bowenwang1996: @mhalambek asked me to keep this issue open to track the final steps - discoverability of the link (mention it in relevant places in the docs/nearup), migration to .tar instead of .zip, and also non-archival backups.

**Comment by alexfilip2** [comment]
@mhalambek We plugged in the snapshot you provided which seems to start from block 0 (confirmed by the naming of the ".sst" files). The problem we face is that the near node (version 1.16.2) will automatically generate a genesis.json with paramater "height" 9820210. We start the node and tried the RPC 'block' with 'block_id' 9820209 and got back the error {"code":-32000,"message":"Server error","data":"DB Not Found Error: BLOCK HEIGHT: 9820209 \n Cause: Unknown"}.
We assume we also have to use a different genesis.json file (specifying height 0) than the one automatically generated, right? Therefore, we woulld like to know if you can provide us with such genesis.

**Comment by frol** [comment]
@alexfilip2 TL;DR: current mainnet started with 9820210 block, so the blockchain history starts from 9820210.

NEAR protocol does not need to store the whole history to operate, its main goal is to maintain the latest state. The reason we lost the history before 9820210 block is due to a hard reset (due to an unrecoverable state the network reached). Hard reset means that we dump the latest correct state (accounts, access keys, contracts, contract states) into the genesis and set the genesis block height to the block height of the block we dumped the state from. Technically, it is a new network, but we preserve the state.

**Comment by alexfilip2** [comment]
@frol thank you very much for the explanation. Therefore, I understand that it is impossible to querry blocks with height lower than the current mainnet genesis.

**Comment by frol** [comment]
> Therefore, I understand that it is impossible to querry blocks with height lower than the current mainnet genesis.

@alexfilip2 That is correct

**Comment by bowenwang1996** [comment]
Done in https://github.com/near/docs/pull/769
