### ISSUE TITLE
Possible broken nightly tests on master

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#3562]
When I run the nightly tests with run_parallel tests on buildkite tests are failing due to:
https://buildkite.com/nearprotocol/nearcore/builds/4227#aa0692e1-04d5-4b7d-ba22-11488e58e9a6

I have retried two times, but I get the same tests failing so don't think it's flaky.

**Comment by birchmd** [comment]
@bowenwang1996 This looks like the issue I mentioned would come up with regards to having the nightly protocol version differ from the normal protocol version, but only have one copy of the `genesis.json` file.

**Comment by chefsale** [comment]
Yes, so I just found the same thing right now, both tests are failing on that. Could you help with fixing this :+1: 

At least I tested that the nightly vs normal tests are working :D

**Comment by birchmd** [comment]
Sure, I can assist in fixing this tomorrow (unless Bowen has already gotten to it by then).

**Comment by bowenwang1996** [comment]
> Sure, I can assist in fixing this tomorrow (unless Bowen has already gotten to it by then).

Yeah I am working on it
