### ISSUE TITLE
Implement --no-color/--color flag in neard

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#3574]
A lot of validators are asking for a feature which disables coloring in neard. cc: @mhalambek @frol @bowenwang1996 @SkidanovAlex

**Comment by chefsale** [comment]
Created a pr: https://github.com/near/nearcore/pull/3575

**Comment by kucharskim** [comment]
Could this be backported to stable (1.13.x) or to whatever the next mainnet release will be?

**Comment by chefsale** [comment]
cc: @bowenwang1996 yes we will include it in both the next testnet and mainnet release than.
