### ISSUE TITLE
nayduck 51024: Block production took more than 100 seconds

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#3577]
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/51024
commit: f588f46d4815f7bb9ea88550d00bc72a88dec28b

**Comment by mikhailOK** [comment]
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/51306

**Comment by mikhailOK** [comment]
investigated in #3644 and https://github.com/near/nearcore/security/advisories/GHSA-w385-wmpg-p9xm

**Comment by bowenwang1996** [comment]
Okay let's close this one in favor of #3644 then
