### ISSUE TITLE
Feat Request: extend storage to allow more efficient SCs and to query a key range

### ISSUE THREAD

**Issue by luciotato** [near/nearcore#3583]
Currently smart contracts access to storage is limited to read/write/remove by key
In many DApps, the app needs to be able to grab "ordered lists" out of storage.

For example the **core-contracts/staking-pool** has [pub fns to retrieve accounts list](https://github.com/near/core-contracts/blob/215d4ed2edb563c47edd961555106b74275c4274/staking-pool/src/lib.rs#L386) requiring listing accounts by index.
In order to be able to do that, staking accounts are stored in a `UnorderedMap<AccountId, AccountData>`
The unordered map allows access by key AND INDEX, but in order to do that, is stores the data **3 times**:
1 & 2. TWO Vectors: 1:PersistentVectorKeys `index->accountName` and 2:PersistentVectorValues `index->accountData`
3: UnorderedMap itself stores **prefix+accountName->index**
So there are 3 Vectors, and the account names are stored twice, once as keys and once as data in index->accountName. **That's not very efficient**. It can be easily reduced to a single `OrderedMap AccountId->AccountData` as long key range retrieval is added

The current feature request is for env:: to provide some access to retrieve ranges of keys and to create a new collection: **OrderedMap**

For the Staking-Pool case, if env:: provides a key range access, the accounts could be stored only **ONCE** in a single `OrderedMap accountName->accountData` and when a list is required `can be obtained with a function like:
```rust
env::storage_read_key_range(start:Vec<u8>,count:u32)->Vec<Vec<u8>>
```

where `start` is a key (or None to start from the lowest key), and count is the number of keys to retrieve

A new collection derived from **LookupMap** but with the ability to retrieve a key range can be created: **OrderedMap**

Having that function **would allow smart-contracts to**:
1. Use less storage and gas (currently there are 3 storage operations for each insert in Staking-Pool, using **OrderedMap** instead of UnorderedMap would reduce that significantly, in CPU and Storage)
2. Retrieve ordered key lists from storage.
3. Using **OrderedMap** with crafted keys to keep "Ordered Lists" on storage. For example a Staking-Pool V2 can store a **OrderedMap** with `u128.MAX-staked_amount->accountName` and then retrieve the first 50 keys in order to provide the list of Top 50 stakers in the pool.
With current env:: support, retrieving the top 50 stakers in a pool is a very expensive read operation requiring to read all accounts.

**Comment by bowenwang1996** [comment]
We deliberately avoided such host function due to concerns with potential abuses.

**Comment by evgenykuzyakov** [comment]
Bowen is correct. We've made a decision to remove access to ordering from the Trie. The plan is to replace Trie with a non-ordered map in the future to allow much faster access and storage. Current implementation of the Trie is limited to be represented as a merkle tree, which provides ordering from the nature of it. But so long as the protocol doesn't require the tree to be ordered, the underlying representation may be changed in the future to have faster random read access.

**Comment by robert-zaremba** [comment]
Ah, i didn't know the `OrderedMap` is not supported. 
I guess if we serialize it to a single record then we can still use it. But this will only make sense if the map will be small ( because every operation will require full structure deserializatio)

**Comment by luciotato** [comment]
I supposed that you did that on purpose. I understand the reasons, **but I ask you to reconsider**. 

You're putting too much work on the shoulders of SC developers. The function I proposed can be limited to 1000 keys. Are there other abuse vectors? Can other limits be imposed to avoid abuse?
The function *is not* just some fancy extra, it allows sensible reductions in gas consumption and storage.
_How much gas and storage can a Staking-Pool with 200k users save by using OrderedMap instead of UnorderedMap?_ (this is a question of the optimizer in you, Evgeny). Considering accountIds are stored twice, plus 2 extra prefix-indexed Vectors... I think it could be significative. And the staking-pool is a small contract. Bigger contracts could benefit way more.


Please reevaluate, mainly because you're moving the burden to other areas. **The fact that the function is not in the core will not make the need disappear. Developers will solve it another way, which will be naturally way less efficient**. Maybe requesting all state and parsing it, maybe implementing the same 3-storage-access inefficient mechanism from the staking-pool and retrieving ALL the information every time, filtering ang sorting on the DApp. (In my case I'll have to do something like that). 
For a DApp with 200k users this is a problem, and those "alternative solutions" normally end up generating a burden on other areas, (developers/validator's CPU/storage/bandwidth).

Regarding the Trie, even if you change the underlying key-value store, 99% of key-value stores sort by keys out of necessity and will probably provide a key iterator.

Based on the motto: "The Builder's fastest path to market." I ask you to reconsider unburden the builder's shoulders

**Comment by evgenykuzyakov** [comment]
I don't know if you saw `TreeMap` collection. It does support all you need and can be extended to support prefix lookups.
It's built without ordered iterators based on random access only.

The amount of gas to use an ordered lookup was much higher than sequential lookup of every independent element due to inefficient implementation of the underlying storage. So you're not going to win a lot.

If the node implementation finally switches the storage from storing in patricia merkle tree to a more efficient random access implementation. The gas cost and time costs to access a random value will be 10-50X cheaper than the current access. Which makes simulated data structures more reasonable. 

In terms of duplicated keys for unordered map, it does have a burden, but doesn't really require iterators for the implementation to exist. There are `LookupMap` that doesn't have replicated keys, but doesn't give in contract ability to iterate. You can still grab entire contract state through RPC, but as other non-core methods it's up to the node to serve it.

**Comment by luciotato** [comment]
Ok thanks @evgenykuzyakov, I might end using a combination of `TreeMap` when I need iterators, and capped-length vec or hashmap (as the Voting contract does) for ordered rankings (the Top 50 stakers example)

**Comment by bowenwang1996** [comment]
Looks like there is no action item here. Closing
