### ISSUE TITLE
Error compiling neard.

### ISSUE THREAD

**Issue by wg200202** [near/nearcore#3584]
Error building the release version, the version used nearcore-1.13.3 build command is cargo build -p neard --release

Hope to get help! Thanks!

The error message is as follows:

error: git describe failed with status 128: fatal: bad revision 'HEAD'
  --> neard/src/../src/main.rs:69:65
   |
69 |         Version { version: crate_version!().to_string(), build: git_version!().to_string() };
   |                                                                 ^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: git describe failed with status 128: fatal: bad revision 'HEAD'
  --> neard/src/main.rs:69:65
   |
69 |         Version { version: crate_version!().to_string(), build: git_version!().to_string() };
   |                                                                 ^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: aborting due to previous error

error: could not compile `neard`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: could not compile `neard`.

**Comment by wg200202** [comment]
![image](https://user-images.githubusercontent.com/10970322/98726448-7c91d080-23d1-11eb-9589-65ee1ea6ae1f.png)

**Comment by wg200202** [comment]
![image](https://user-images.githubusercontent.com/10970322/98726502-916e6400-23d1-11eb-891e-a81b7016f7e3.png)

**Comment by wg200202** [comment]
![image](https://user-images.githubusercontent.com/10970322/98727022-41dc6800-23d2-11eb-9cfb-3707e260d91f.png)

**Comment by birchmd** [comment]
Looks like the directory you are compiling in is not a git repo. Ensure you have cloned the source code from github then run `cargo` from inside the directory it creates.

**Comment by wg200202** [comment]
I downloaded version 1.13.3 from https://github.com/near/nearcore/releases. The instructions above are to download and build from here

**Comment by birchmd** [comment]
Sounds like we need to update our docs 😅 

Could you link to where you found these instructions? I'll see who the right person is to update them.

In the mean time I suggest the following steps:

```
git clone https://github.com/near/nearcore.git
cd nearcore
cargo build -p neard --release
```

**Comment by wg200202** [comment]
Ok, let me try~ thanks~

**Comment by wg200202** [comment]
The documentation is here https://docs.near.org/docs/validator/deploy-on-mainnet

**Comment by wg200202** [comment]
I have successfully built it ~ thank you so much

**Comment by birchmd** [comment]
Awesome! Good to hear.

I'll close this issue now then. I've opened an issue in the near docs repo to fix the instructions. Once that is resolved hopefully others will not run into the same issue.

Thanks for letting us know about your issue; we're always looking to improve our documentation and on-boarding.
