### ISSUE TITLE
Validator randomly stops producing blocks

### ISSUE THREAD

**Issue by leoluk** [near/nearcore#3590]
**Describe the bug**

Node stops producing blocks at epoch boundaries and ceases log output. It no longer responds to Prometheus queries. 

It wouldn't shut down on SIGTERM and has to be killed with SIGKILL.

gdb stacktrace for all threads while the process hung: http://logbin.certus.one:8080/Qui9iehu/near/gdb-20201110.txt

**Version (please complete the following information):**
- NEAR Protocol Node 1.13.2 (build 043a54a)
- On mainnet.

**Comment by bowenwang1996** [comment]
Looks like a few threads are waiting for a condition variable in rocksdb. Could it be some kind of deadlock? @mikhailOK

**Comment by kucharskim** [comment]
When we lost blocks, `neard` was in `D` state, `generic_file_buffered_read`:

```
# ps -p 391290 -L -o pid,tid,class,rtprio,ni,pri,psr,pcpu,stat,rss:8,size:8,vsize:8,wchan:14,comm
    PID     TID CLS RTPRIO  NI PRI PSR %CPU STAT      RSS     SIZE      VSZ WCHAN          COMMAND
 391290  391290 TS       -   0  19   0 27.9 Dl+   7883244  8109864  8332620 generic_file_b neard
...
```

See more info in [neard-chorusone-20201113-060538.txt](https://github.com/near/nearcore/files/5535127/neard-chorusone-20201113-060538.txt)

**Comment by kucharskim** [comment]
Issue started after Nov 13 16:26 (maybe a minute later), when we finally lost validator status (metric `near_is_validator 0`) around 16:33, I decided to restart, before restart I collected `thread apply all bt` from `gdb` around 16:39.

[neard-logs-20201113-v001.txt](https://github.com/near/nearcore/files/5538462/neard-logs-20201113-v001.txt)

[neard-gdb-20201113-v001.txt](https://github.com/near/nearcore/files/5538437/neard-gdb-20201113-v001.txt)

**Comment by bowenwang1996** [comment]
It seems that this has not been observed for a while. I'll close this for now and please reopen or create new issues if it happens again
