### ISSUE TITLE
investigate rust memory usage leaks

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3617]
We should investigate whenever there are any leaks remaining in the Rust code.
For some reason stack trace couldn't be resolved for a few allocations in Rust, I need to investigate why.

**Comment by lcgogo** [comment]
ver 1.16.0 still has memory leak

**Comment by bowenwang1996** [comment]
> ver 1.16.0 still has memory leak

Yes. Most of the fixes didn't go into that release because we wanted to have more testing

**Comment by pmnoxx** [comment]
I ran a node for a week, I see following leaks in our Rust code:
actix_rt::arbiter::Arbiter::spawn  -> 5mb/28000 allocations a day 
<actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call -> 1.1mb/9000 allocation a day

I didn't notice any leaks in Wasmer.
It's possible that there is a 0.5mb a day leak in RocksDB, but it's hard to hard because there is a few mb variation in each measurement. We should run a node at least a week or two to make sure.
