### ISSUE TITLE
--no-color flag is not working

### ISSUE THREAD

**Issue by mabalaru** [near/nearcore#3619]
With the new official mainnet version v1.16.0, the --no-color flag is not working, although it is present on `./neard --help`:

```
neard --help|grep color
        --no-color    Disable ansi charset and colored logging.
```
Service is starting with `ExecStart=/opt/bin/neard --no-color run` and the output on the logs is:

```
Nov 16 20:38:36 near-backup01 neard[5844]: Nov 16 20:38:36.455  INFO near: Version: 1.16.0, Build: 8fc2882a-modified, Latest Protocol: 39
Nov 16 20:38:36 near-backup01 neard[5844]: Nov 16 20:38:36.457  INFO near: Opening store database at "/opt/near/.near/data"
Nov 16 20:38:36 near-backup01 neard[5844]: Nov 16 20:38:36.855  INFO stats: Server listening at ed25519:4GLdEcAAdZb7irLkjQUAJvVRFDYiupw3qU3LePZVRry2@0.0.0.0:24567
Nov 16 20:38:39 near-backup01 neard[5844]: Nov 16 20:38:39.732  WARN network: Received Block while Connecting from Outbound connection.
Nov 16 20:38:46 near-backup01 neard[5844]: Nov 16 20:38:46.859  INFO stats: #033[1;33m#22803611 Downloading headers 99%#033[0m #033[1;37m#033[0m #033[1;36m 6/6/40 peers#033[0m #033[1;36m⬇ 444.4kiB/s ⬆ 0.6kiB/s#033[0m #033[1;32m0.00 bps 0 gas/s#033[0m #033[1;34mCPU: 0%, Mem: 0 B#033[0m
Nov 16 20:38:56 near-backup01 neard[5844]: Nov 16 20:38:56.862  INFO stats: #033[1;33m#22803615 Downloading headers 99%#033[0m #033[1;37m#033[0m #033[1;36m11/10/40 peers#033[0m #033[1;36m⬇ 1.3MiB/s ⬆ 1.3MiB/s#033[0m #033[1;32m0.40 bps 10.48 Tgas/s#033[0m #033[1;34mCPU: 116%, Mem: 819.2 MiB#033[0m```

**Comment by chefsale** [comment]
@mabalaru have you ran:  systemctl reload-deamon after changing the service unit file?

**Comment by mabalaru** [comment]
@chefsale Yes: 
My deployment is done with ansible and it's doing that automatically, but here it is also:

```
root@near-backup01:~# systemctl daemon-reload ; systemctl restart neard; tail -f /var/log/syslog |egrep -v kernel
Nov 16 21:32:15 near-backup01 systemd[1]: Reloading.
Nov 16 21:32:15 near-backup01 systemd[1]: Stopping Neard node...
Nov 16 21:32:16 near-backup01 systemd[1]: Stopped Neard node.
Nov 16 21:32:16 near-backup01 systemd[1]: Started Neard node.
Nov 16 21:32:16 near-backup01 neard[6117]: Nov 16 21:32:16.396  INFO near: Version: 1.16.0, Build: 8fc2882a-modified, Latest Protocol: 39
Nov 16 21:32:16 near-backup01 neard[6117]: Nov 16 21:32:16.397  INFO near: Opening store database at "/opt/near/.near/data"
Nov 16 21:32:18 near-backup01 neard[6117]: Nov 16 21:32:18.131  INFO stats: Server listening at ed25519:4GLdEcAAdZb7irLkjQUAJvVRFDYiupw3qU3LePZVRry2@0.0.0.0:24567
Nov 16 21:32:28 near-backup01 neard[6117]: Nov 16 21:32:28.135  INFO stats: #033[1;33m#22807390 Downloading blocks 99%#033[0m #033[1;37m#033[0m #033[1;36m 7/7/40 peers#033[0m #033[1;36m⬇ 347.4kiB/s ⬆ 1.7kiB/s#033[0m #033[1;32m0.10 bps 20.47 Tgas/s#033[0m #033[1;34mCPU: 0%, Mem: 0 B#033[0m
```

**Comment by chefsale** [comment]
Hmm, thanks. Interesting, will check why is it still colored.

**Comment by kucharskim** [comment]
Yup, same here:

```
$ neard -V
NEAR Protocol Node 1.16.0 (build 8fc2882a-modified)

$ pgrep -ax neard
1351 /data/neard/neard --no-color run
```

and `--no-color` flag doesn't work.

**Comment by chefsale** [comment]
So, after some investigation seems like the RUST_LOG_STYLE=never environment variable only applies to the syslog and not the output which we are providing from the code here: https://github.com/near/nearcore/blob/60e3a5725db06599df46a491ba9acffd3d63b315/chain/client/src/info.rs#L116. 

Maybe we should totally ditch the colors all together, as a bunch of people are complaining about it  (cc: @kucharskim @mabalaru). 


If not, the question is how can I add an if statement here to disable the coloring, can we stuck it in the config and fetch it from there or something else, as passing it all way from neard to here seems very suboptimal and cumbersome. (@bowenwang1996)

**Comment by kucharskim** [comment]
To clarify from my end. Colors are not grep, awk, sed friendly, that's why I'm not fan of them. Nobody cares if logs are colorful or not, when there is a revenue drop. Efficient usage of tooling like grep, awk, what-not helps debugging problems faster, when there is an outage. If I can have any tiny amount of influence here, I would just drop colors altogether from the code. However I would ask broader validation community, would that be a problem for any of them or just give them heads up that you are planning to drop colors, if that would be the case.

**Comment by chefsale** [comment]
Totally agree with @kucharskim, that was one of the points I made before when I wanted to delete the coloring altogether, as also makes a bunch of our tooling also harder to setup, as we have to regex clearup the coloring for graylog, etc.

**Comment by bowenwang1996** [comment]
While I agree that it makes it harder for tools like grep and awk, I found it easier to read when logs have colors. So I think we can add some config parameter to toggle it.

**Comment by chefsale** [comment]
Where can I adapt the config to do so? And is the config some kind of singelton which gets loaded into memory at startup or is reads the config everytime? I assume we don't want to read it from disk every time we do a log print?

**Comment by chefsale** [comment]
I assume i can just add it here: https://github.com/near/nearcore/blob/master/core/chain-configs/src/client_config.rs?

**Comment by chefsale** [comment]
Removed the flag and added a log_color: {true/false} flag which can be added to the config.json to disable logging. https://github.com/near/nearcore/pull/3631

**Comment by chefsale** [comment]
Removed the flag amd added a parameter in config:
"log_summary_style": "plain/colored"
