### ISSUE TITLE
Investigate on how to improve compilation time without having to modify Cargo.toml

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3626]
I did a bit of searching on the internet/testing.

I turns that that you can modify enviroment to improve compilation time.
This can be done by adding to ```.bashrc``` the following
```export RUSTFLAGS="-C lto=off -C link-arg=-fuse-ld=lld -Zshare-generics=y -C codegen-units=6"```

So far 3 options are helping
1) switching lto of off
2) using lld linker instead of ld
3) using experimental feature share-generics
4) setting codegen-units to the number of available cores helps ensure that all core are utilized, even when only one package is being compiled

**Comment by bowenwang1996** [comment]
@pmnoxx is this considered done?

**Comment by pmnoxx** [comment]
I found out a few more options, which improve compilation time.
I'll write a document and put it in docs/docs/contribution/nearcore.md

**Comment by pmnoxx** [comment]
https://github.com/near/docs/pull/543
