### ISSUE TITLE
Bootnodes should not get wiped

### ISSUE THREAD

**Issue by frol** [near/nearcore#3641]
**Describe the bug**

@khorolets and I observed a few times a situation where a perfectly working node just stops syncing and after a restart we observe that the `"boot_nodes"` section in the config is completely blank.

@bowenwang1996 I have no idea who might be the best person to clarify the situation. Could you help to triage it?

**To Reproduce**

N/A

**Expected behavior**

There should be boot nodes.

**Version (please complete the following information):**
- nearcore commit/branch: f3ba9f9d (recent master)
- rust version (if local): rust-toolchain
- mainnet/testnet

**Comment by bowenwang1996** [comment]
Was bootnodes not blank before? I don't think there is anything that magically changes the file.

**Comment by frol** [comment]
The nodes were running just fine and we use `neard` directly, so no nearup is in play. I am 99% sure that the `boot_nodes` were there before (otherwise I don't understand how they could work in the first place).

**Comment by bowenwang1996** [comment]
> The nodes were running just fine and we use neard directly, so no nearup is in play. I am 99% sure that the boot_nodes were there before (otherwise I don't understand how they could work in the first place).

They could either by passing bootnodes as command line arguments, or if the node was already running before and has peer stored in storage.

**Comment by frol** [comment]
We don't have boot nodes CLI argument (#3156). Well, if we wipe the `boot_nodes` when we store them in the storage, that might be the trick. What is going to happen if I:

1. Run a fresh node with the `boot_nodes` in the config file
2. Stop it
3. Run the node again and it will have some sort of failure and thus unable to connect to any peers just yet
4. Restart the node

It seems that currently, we can lose the `boot_nodes` from the config as well as from the storage.

**Comment by bowenwang1996** [comment]
We definitely don't wipe out bootnodes in the config. You can verify this by stopping and restarting a node many times. I am not sure why it happened. Is it possible that you changed your config?

**Comment by frol** [comment]
I did not edit the file. I had a running node, and it stuck on the epoch boundary due to protocol incompatibility, so I brought a new `neard` binary there and restarted the node, boom, I observe "Waiting for peers" and then I open the config file and see the boot_nodes being empty. It is far from the first time I observe it. I believe I bumped into this in January when I started running nodes more often during Stake Wars, but I always blamed myself for this madness

**Comment by bowenwang1996** [comment]
@frol interesting. Can you reliably reproduce it? I have a node that I have stopped an restarted many times (including using different neards) and it still has bootnodes in the config file.

**Comment by frol** [comment]
I cannot reproduce it 😞

**Comment by frol** [comment]
Let's keep it closed, but if you observe it, you know where to report it
