### ISSUE TITLE
Protocol version number collision on mainnet and testnet

### ISSUE THREAD

**Issue by frol** [near/nearcore#3645]
After https://github.com/near/nearcore/releases/tag/1.16.2, mainnet and testnet both have protocol version # 40 (master branch has `SHARD_CHUNK_HEADER_UPGRADE_VERSION` whereas the hotfix introduced completely different protocol change under version # 40 [`DELETE_KEY_STORAGE_USAGE_PROTOCOL_VERSION`]).

The only way to recover for the nodes stuck at block height 23341948 (#3642) is to resync after applying the hotfix.

@bowenwang1996 @evgenykuzyakov have you considered such a scenario when designed "protocol version"?

**Comment by bowenwang1996** [comment]
> After https://github.com/near/nearcore/releases/tag/1.16.2, mainnet and testnet both have protocol version # 40 (master branch has SHARD_CHUNK_HEADER_UPGRADE_VERSION whereas the hotfix introduced completely different protocol change under version # 40 [DELETE_KEY_STORAGE_USAGE_PROTOCOL_VERSION]).

That is not true. Testnet is still on version 39. We will port that fix to master with higher protocol version to avoid collision.

**Comment by frol** [comment]
I see. Well, some of the users (including ourselves on Indexer and RosettaRPC side) seem to use master builds, and that is still suboptimal from a protocol version perspective.

**Comment by bowenwang1996** [comment]
> I see. Well, some of the users (including ourselves on Indexer and RosettaRPC side) seem to use master builds, and that is still suboptimal from a protocol version perspective.

Agree that it can be suboptimal. However, I don't really see a better alternative when we need to do emergency upgrades.

**Comment by bowenwang1996** [comment]
@frol can we close this issue or are there more actions required?

**Comment by frol** [comment]
Let's close for now
