### ISSUE TITLE
Wasmer compilation error database

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#3651]
From contract-runtime okr: Implement crash analysis tool for contract precompilation: whenever contract fails to compile - we know about it. Simple database analysis tool to find which contracts fail to compile.

From me:
This would be a tool to listen to indexer database, and fetch error message that has `Wasmer compilation error` pattern (since by analyze error structure when compile a wasm contract, this is the only place that cause by a wasmer compilation error). Then analyze the txn and figure out `code: &[u8]` that failed to compile

**Comment by bowenwang1996** [comment]
@ailisp what is the status of this issue?

**Comment by ailisp** [comment]
@bowenwang1996 the tool is implemented and listen wasmer compilation errors that store in a simple nedb database. We didn't encounter interesting kind of errors last time checked and also haven't looked into database recently
