### ISSUE TITLE
Loops in routing messages

### ISSUE THREAD

**Issue by birchmd** [near/nearcore#3654]
**Describe the bug**
While working on the 8-shard network I noticed forwarded chunks were taking a long time to propagate through the network; often slower than blocks. I added some logging to track routed messages as they passed through the network and found that loops in the routing can appear (see example below). These loops are fairly rare, <1% of routed messages end up in a loop, but it could be enough to cause the instability in the sharded network I have been observing.

**To Reproduce**
100 node mocknet test with 8 shards and extra logging.

**Expected behavior**
@mfornet also added some extra logging which analyzes the peer graph, This reports any pair of nodes should be at most two hops away from each other. In terms of the logging I added to track routed messages, that should correspond to at most one log entry per message. In particular, we should never see the same message be routed back through the node which sent it initially.

**Example loop**
author | enum | machine_name | msg_from | msg_hash | target
------ | ---- | ------------ | -------- | -------- | ------ 
sharded-mocknet-node38 | PartialEncodedChunkForward | mocknet-node25 | sharded-mocknet-node38 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)
sharded-mocknet-node38 | PartialEncodedChunkForward | mocknet-node31 | mocknet-node25 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)
sharded-mocknet-node38 | PartialEncodedChunkForward | mocknet-node16 | mocknet-node31 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)
sharded-mocknet-node38 | PartialEncodedChunkForward | mocknet-node2 | mocknet-node16 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)
sharded-mocknet-node38 | PartialEncodedChunkForward | sharded-mocknet-node38 | mocknet-node2 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)
sharded-mocknet-node38 | PartialEncodedChunkForward | sharded-mocknet-node27 | sharded-mocknet-node38 | FWAikaKNHTmMmADL4eqhNDh2uaSE7zTLbTAsfsgoosgk | PeerId(mocknet-node5)

**Version (please complete the following information):**
Built from commit https://github.com/birchmd/nearcore/commit/394f637fe3c77fe91273b1e9358ac31af6191eac

**Comment by bowenwang1996** [comment]
@birchmd can we get the following information:
* How often does this occur?
* Does this occur after you start sending transactions or only in the setup phase?

**Comment by birchmd** [comment]
Correlating the timestamps together, these loops only occur during the network shutdown phase. This makes sense because the routing table will be changing rapidly as nodes go offline.

The network is only shutdown by the test runner after it detects validators have been kicked out, so these loops cannot be the source of the instability.
