### ISSUE TITLE
Work of fixing security issue related to NAPTHA attack

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3663]
Our current implementation was creating a new thread for each incoming connection. It was possible to create tens of thousands of connections to cause node crash because of OOM. The details of the attack will be published soon in a separate document.

**Comment by pmnoxx** [comment]
I merged fix for this issue: https://github.com/near/nearcore/pull/3639

**Comment by bowenwang1996** [comment]
@pmnoxx isn't this captured in https://github.com/near/nearcore/issues/3643?
