### ISSUE TITLE
automerge does not autoupdate

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3675]
The automerge label used to do both autoupdate and automerge but it appears that now it only does automerge. Would be nice if it can do autoupdate of the branch as well.

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek is this something that you could potentially work on?

**Comment by chefsale** [comment]
Hi Bowen, this should be already added. Maybe just the flow is confusing:

```
When using the branch update functionality, Bulldozer only acts when the target branch is updated after updates are enabled for the pull request. For example:

User A opens a pull request targeting develop
User B pushes a commit to develop
User A adds the update me label to the first pull request
User C pushes a commit to develop
Bulldozer updates the pull request with the commits from Users B and C
Note that the update does not happen when the update me label is added, even though there is a new commit on develop that is not part of the pull request.
```

**Comment by chefsale** [comment]
I have already added this, but seems like the configuration has changed from whitelist to trigger in the meantime. I fixed this and will test it out if works. cc: @bowenwang1996

**Comment by chefsale** [comment]
@bowenwang1996 seems like it is working for new PRs now. Closing for now, let me know if there are any other issues.
