### ISSUE TITLE
limit rocksdb memory usage in case of no_cache option

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3679]
It should be safe to limit rocksdb write buffer to 64mb and read buffer to 16mb per column in case no_cache option is used.

https://github.com/near/nearcore/pull/3609

- [ ] check performance after change in production
- [ ] check memory usage in production before/after
- [ ] Check again how rocksdb implements those Settings

**Comment by bowenwang1996** [comment]
@pmnoxx is this still relevant?

**Comment by pmnoxx** [comment]
@bowenwang1996 That's no longer relevant. I'll close the issue.
