### ISSUE TITLE
investigate memory leak in rust code

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3680]
We currently see 6mb/s memory leak per day in our Rust code.
```
actix_rt::arbiter::Arbiter::spawn -> 5mb/28000 allocations a day
<actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call -> 1.1mb/9000 allocation a day
```
I'm going to investigate to see what's causing it.
```actix_rt::arbiter::Arbiter::spawn` leak indicates that we keep creating more futures, and adding them to Actix.
This could potentially cause issues, I'll check which futures are those.

**Comment by bowenwang1996** [comment]
What is the reason for closing it?

**Comment by pmnoxx** [comment]
`(Rust) func 134c046 55e2d6fb4046 4.00MiB/34990 <actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call `
I see that we open connection every 10s to `https://explorer.testnet.near.org/api/nodes `.
This is causing a memory leak, after 3 days we saw 34990 leaks, which is after 349000 seconds.

**Comment by pmnoxx** [comment]
I don't see the leak in `actix_rt::arbiter::Arbiter::spawn` anymore.

There is one more leak that I see in `(Rust) func 1260841 55e2d6ec8841 25.46MiB/38306 near_client::client::Client::process_partial_encoded_chunk `
I'll investigating to what's causing it.

**Comment by pmnoxx** [comment]
The second leak is inside `EncodedChunksCache`. I see we don't have a limit of the size of this cache,

**Comment by bowenwang1996** [comment]
> The second leak is inside EncodedChunksCache. I see we don't have a limit of the size of this cache,

There is an implicit limit due to the way we add and remove entries. Basically there is a height range of 1024. I suggest that we not spend time investigating this for now since the leak is small.

**Comment by pmnoxx** [comment]
Yes, it's a small leak. Less than 1mb a day. It's probably not worth spending any more time on it.
