### ISSUE TITLE
Experiment with sending chunk parts to next block producer twice

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3685]
Currently if a block producer doesn't receive all its parts for some chunk, it would simply not including that chunk in the block it produces. Therefore, if a partial encoded chunk message gets lost, it could lead to some chunk not getting included and this may eventually cause some chunk producer to get kicked out. One idea to address this is to send the chunk parts to the next block producer twice, which may trigger different paths in the network, thereby increasing the chance of the next block producer getting the chunk. However, such an approach will also increase the network traffic slightly, so we should do some testing to see how much it helps.

**Comment by birchmd** [comment]
The investigation around slow delivery of chunks lead us to upgrade actix/tokio, and it seems to resolve the issue. I'm closing this ticket since I think it is no longer necessary.
