### ISSUE TITLE
Investigate slow message delivery

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3686]
@birchmd found while investigating #3660 that sometimes it takes quite some time for a message to get delivered. Some preliminary investigation shows that it is caused not because it physically takes a long time to send messages from one node to another, but because, for some unknown reason, the message takes a long time to be sent, meaning that it gets stuck for a while in the peer actor before being sent out. We need to understand the underlying cause of the issue.

**Comment by bowenwang1996** [comment]
I captured once on mainnet that `send_message` takes a long time, but after adding more tracing I haven't reproduced it yet. Meanwhile, @SkidanovAlex observed on mainnet that his node would sometimes not receive any responses for requests for 2 minutes, while still receiving incoming messages during that time. This suggests that it is possible that the request messages were not sent immediately after https://github.com/near/nearcore/blob/2277b5ac128d8452c85cc295217885345f08e0a6/chain/network/src/peer.rs#L256

**Comment by bowenwang1996** [comment]
This is related to https://github.com/near/nearcore/security/advisories/GHSA-2chw-q82g-874q

**Comment by birchmd** [comment]
I think our conclusion has been that upgrading actix/tokio will resolve this issue. @bowenwang1996 shall we close this issue?
