### ISSUE TITLE
Understand the messages that are lost during transmission

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3687]
As reported by @birchmd, some messages are lost when they are sent from one node to another. More specifically, the node logs that it sends the message but the destination node fails to receive it. It is helpful to understand the following before we look deeply into the issue:
* Is the message actually sent successfully? Sometimes when we send a `NetworkRequest`, it ends up not getting sent because the route to the destination could not be found.
* What is the percentage and absolute number of the messages that are lost?
* For those lost messages, what are their types?

**Comment by birchmd** [comment]
I made a mistake when I was reporting this initially. The messages I thought were being dropped were not being sent for another reason. Closing this issue for now, unless I find other evidence of this happening.
