### ISSUE TITLE
Implement the Ethereum JSON-RPC API

### ISSUE THREAD

**Issue by artob** [near/nearcore#3699]
We need to offer betanet/testnet/mainnet RPC endpoints supporting Ethereum's Web3 JSON-RPC API. It is yet to be decided whether this will be in the form of an external proxy process translating between the Web3 API and the NEAR API, or if the protocol will be incorporated directly into nearcore's RPC server. The specifications for the protocol are here:

- https://eth.wiki/json-rpc/API
- https://ethereumbuilders.gitbooks.io/guide/content/en/ethereum_json_rpc.html
- https://geth.ethereum.org/docs/rpc/server

A special note related to our findings in #3665: there are aspects of the protocol that are not nailed down in any specification, where clients rely on how Geth behaves as a de-facto standard. In particular, we will need to ensure that error messages from our endpoint match Geth's as closely as possible, so that, for example, reverts returning data are detected correctly by client libraries. Therefore Geth source code will be needed as much as the protocol specification itself.

**Comment by frol** [comment]
This will essentially mean that we want to build Layer 2 Ethereum on top of NEAR. I am still failing to understand this strategy. :man_shrugging: 

Just a friendly heads up, from my experience with Rosetta RPC, be prepared for quirks.

/cc @nearmax @ilblackdragon

**Comment by ilblackdragon** [comment]
This should not be a part of nearcore.

This can and should be done as a separate proxy service.
It's pretty much express server that proxies all the RPCs similar to near-web3-provider.

I also think there is someone who already was planning to work on that @djsatok ?

**Comment by artob** [comment]
> This should not be a part of nearcore. [...]
> This specific issue to have JSON RPC API endpoint can and should be done as a separate proxy service.
> It's pretty much express server that proxies all the RPCs similar to near-web3-provider.

All right, thanks for that @ilblackdragon: that clarifies the approach we must take. I will discuss with @djsatok and @evgenykuzyakov.

**Comment by djsatok** [comment]
@ilblackdragon, JSON-PRC implementation is a must have for seamless transition for Ethereum projects. Let's make it a separate repo.

**Comment by evgenykuzyakov** [comment]
> Currently the fact that we precompiled it is due to performance issues which I hope can be addressed later and we will be able to remove EVM from the nearcore and transition it back into a WASM contract.

This will never happen, as EVM will always be a part of nearcore now. It's as native as our Wasm VM.

**Comment by evgenykuzyakov** [comment]
> This specific issue to have JSON RPC API endpoint can and should be done as a separate proxy service.
It's pretty much express server that proxies all the RPCs similar to near-web3-provider.

It's still possible and maybe even easier to implement it in nearcore as part of a separate client similar to Rosetta RPC client. But we can also try to implement it outside of nearcore, so you can point any NEAR RPC endpoint. But before we start we need to figure out whether the required items are available within the NEAR RPC.

**Comment by ilblackdragon** [comment]
Why do you think it's impossible to do?
The current code that is dispatched when account EVM is called - can be
moved into a compiled WASM and be executed same as others.
There is gas parameters and few other things that will change.

Re: all the things needed for truffle and similar tools are exposed - hence
Web3 provider is working.

Things that are not working are mocked.
This service should just literally be express server that calls Web3
provider methods.

There prob a bunch of encoding stuff that prob  Web3 Provider that this RPC
should not - so it probably make sense to move the method that does
dispatch and using it directly.

**Comment by ilblackdragon** [comment]
Following up on my comments about JSON RPC is just an express server on top of web3 provider, I created a quick hack:

https://github.com/near/near-eth-rpc/blob/master/index.js#L35

It works for basic RPC commands (block number, etc) and need to test it with some more advanced things like deploying contracts.

@djsatok Let's close this issue and move the discussion there?

**Comment by djsatok** [comment]
@ilblackdragon, let's not close this issue just for now, since we need to track the progress on this task;

Let's move the discussion on the future of the EVM not in the RPC repo, but in discussions here: https://github.com/near/nearcore/discussions/3719

**Comment by bowenwang1996** [comment]
@djsatok I believe there are now a separate repo for this. Closing
