### ISSUE TITLE
Replace wasmer 0,17 code serialization and deserialization with borsh

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#3724]
Discovered by @evgenykuzyakov: 
> Wasmer 0.17.1 uses serde_bench for artifact serialization. Except it’s mostly not supported: https://github.com/serde-rs/benchI wonder if it’s performant enough to serialize large contracts, e.g. 1Mb
> Based on description it seems the format is similar to bincode and according to borsh benchmarks for large objects, it loses substantially to borsh: https://borsh.io/

wasmer 0.17 we maintain our own fork: https://github.com/near/wasmer/tree/0.17.2. so we can replace the code serialization with borsh

**Comment by bowenwang1996** [comment]
@ailisp what is the status of this issue?

**Comment by ailisp** [comment]
@bowenwang1996 mostly finished but haven't merge, I'm doing a rebase and test it again to merge & release a new wasmer-near: https://github.com/near/nearcore/pull/4448

**Comment by matklad** [comment]
Fixed by @ailisp !
