### ISSUE TITLE
Improve ViewClient trie cache

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#3742]
Reverting #3593 means that it's easier to hit cache inconsistency in view client. ViewClient already has to be tolerant to this type of errors for independent reasons (not reading from snapshots). The goal of this issue is to track possible improvements to the cache.

**Comment by mikhailOK** [comment]
#3879 reduces lock contention.
ViewClient instances still share one cache, so we should keep this open

**Comment by bowenwang1996** [comment]
@mikhailOK is there a plan to address the shared cache there?

**Comment by bowenwang1996** [comment]
@mikhailOK do we still have any action items here? If not, let's close the issue
