### ISSUE TITLE
Benchmark CryptoZombies contract with ERC-721 token functionality

### ISSUE THREAD

**Issue by frankbraun** [near/nearcore#3746]
Although the CryptoZombies contract at https://cryptozombies.io/en/lesson/5/chapter/1 has ERC-721 token functionality built in, which we should use for testing and benchmarking, the contract in the code base doesn't contain that code.

The CryptoZombies contract should be extended accordingly such that the ERC-721 functionality can be used to extend tests and benchmarks with it.

**Comment by bowenwang1996** [comment]
@frankbraun is this done?

**Comment by frankbraun** [comment]
With the new EVM implementation we switched to a different testing strategy, closing the issue.
