### ISSUE TITLE
build fails with --release

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3748]
i tried building with `cargo build -p neard --release`
The build fails on 445ee2e64a90f9d7bd75e6cc9c60c95f839aded4,
 but works on 445ee2e64a90f9d7bd75e6cc9c60c95f839aded4~1.

I'm able to build without --release though.

**Comment by pmnoxx** [comment]
@bowenwang1996

**Comment by pmnoxx** [comment]
Author: Willem Wyndham <willem@cs.umd.edu>
Date:   Tue Dec 15 16:11:46 2020 -0500

    feat: Update wasmer dependency to allow for stable toolchain for nearcore (#3533)
    
    * fix: make near-vm-runner compile on stable
    * fix: switch to crates version of wasmer deps
    * fix: don't use default features in wasmtime
    * fix: use newer version of nightly to fix compile errors
    * fix: update deny to ignore new duplicates
    * feat: switch to libc instead of file API
    * fix: update toolchain to build
    
    Co-authored-by: Nikolay Igotti <olonho@users.noreply.github.com>
@willemneal Can you take a look?

**Comment by pmnoxx** [comment]
```To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" 
........
-Wl,-Bdynamic" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-fuse-ld=lld"
  = note: ld.lld: error: /home/xxxxxxx/nearcore/target/release/deps/libopenssl_probe-976c3e6caa6e638b.rlib(openssl_probe-976c3e6caa6e638b.openssl_probe.5a9meb9q-cgu.1.rcgu.o): Invalid record
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: build failed

**Comment by birchmd** [comment]
Maybe it's a bug in `lld`? I was able to compile fine with the normal `ld` linker.

**Comment by willemneal** [comment]
Seconding Michael, I too was able to compile locally on Mac.

**Comment by pmnoxx** [comment]
I see, the new version of RUST doesn't work properly when you set RUSTFLAGS='-C lto=off'  environment variable and have lto=on in Cargo.toml. This cause `cargo build -p neard --release` to fail.

**Comment by pmnoxx** [comment]
I'll close the issue as this is a bug/feature related to new rust version and there is nothing we can do about it.
