### ISSUE TITLE
Archival node syncing very slow

### ISSUE THREAD

**Issue by JonasPf** [near/nearcore#3756]
**Describe the bug**

I'm trying to sync an archival node but it is very slow. The machine has been running for 49 days and has currently 62% of blocks synced.

I'm experiencing two issues that may or may not be related (let me know if you want them in separate tickets and I'll split them up):

1. Blocks per seconds are really low. Sometimes they are so slow that new blocks get created faster and we are slowly starting to fall behind. The first 2-3 days of syncing the bps where higher (up to 15bps) but after that it got slowly slower until we hit 1-2bps about 2 weeks ago.

```
Dec 18 10:07:57.209  INFO stats: #19732483 Downloading blocks 63%  32/22/40 peers ⬇ 376.8kiB/s ⬆ 124.5kiB/s 1.99 bps 0 gas/s CPU: 243%, Mem: 6.9 GiB
Dec 18 10:08:07.211  INFO stats: #19732499 Downloading blocks 63%  32/22/40 peers ⬇ 383.3kiB/s ⬆ 137.3kiB/s 1.60 bps 0 gas/s CPU: 222%, Mem: 6.9 GiB
Dec 18 10:08:17.215  INFO stats: #19732516 Downloading blocks 63%  32/22/40 peers ⬇ 382.3kiB/s ⬆ 145.7kiB/s 1.70 bps 0 gas/s CPU: 227%, Mem: 6.9 GiB
Dec 18 10:08:27.226  INFO stats: #19732533 Downloading blocks 63%  32/22/40 peers ⬇ 373.8kiB/s ⬆ 138.8kiB/s 1.70 bps 0 gas/s CPU: 218%, Mem: 6.9 GiB
Dec 18 10:08:37.230  INFO stats: #19732549 Downloading blocks 63%  32/22/40 peers ⬇ 380.1kiB/s ⬆ 143.0kiB/s 1.60 bps 0 gas/s CPU: 206%, Mem: 6.9 GiB
```

2. Sometimes (happened 4-5 times over the course of 49 days) the bps drop to 0 and stays there for hours or even days. Periodically (once or twice per day) it starts syncing again for 10-15 minutes but then it drops back to 0. Every time it starts syncing again I can see the message `Downloading headers 100%` just before the bps increase. This makes me think that the bps may be 0 because the node doesn't have all the headers.
```
Dec 11 13:03:36.556  INFO stats: #19302095 Downloading blocks 62%  33/30/40 peers ⬇ 229.2kiB/s ⬆ 130.2kiB/s 0.00 bps 0 gas/s CPU: 128%, Mem: 7.3 GiB
Dec 11 13:03:46.558  INFO stats: #19302095 Downloading blocks 62%  33/30/40 peers ⬇ 382.3kiB/s ⬆ 122.8kiB/s 0.00 bps 0 gas/s CPU: 191%, Mem: 7.3 GiB
Dec 11 13:03:57.079  INFO stats: #19302097 Downloading headers 100%  33/30/40 peers ⬇ 372.9kiB/s ⬆ 116.9kiB/s 0.19 bps 2.69 Tgas/s CPU: 122%, Mem: 7.3 GiB
Dec 11 13:04:07.099  INFO stats: #19302112 Downloading blocks 62%  33/30/40 peers ⬇ 437.9kiB/s ⬆ 116.6kiB/s 1.50 bps 2.55 Tgas/s CPU: 213%, Mem: 7.3 GiB
Dec 11 13:04:17.102  INFO stats: #19302120 Downloading headers 100%  33/30/40 peers ⬇ 440.3kiB/s ⬆ 104.1kiB/s 0.80 bps 1.78 Tgas/s CPU: 176%, Mem: 7.3 GiB
Dec 11 13:04:27.108  INFO stats: #19302132 Downloading blocks 62%  33/30/40 peers ⬇ 438.2kiB/s ⬆ 89.6kiB/s 1.20 bps 1.49 Tgas/s CPU: 167%, Mem: 7.3 GiB
[...]
Dec 11 13:17:17.414  INFO stats: #19303102 Downloading blocks 62%  33/30/40 peers ⬇ 234.5kiB/s ⬆ 102.4kiB/s 1.70 bps 1.99 Tgas/s CPU: 81%, Mem: 7.3 GiB
Dec 11 13:17:27.415  INFO stats: #19303115 Downloading blocks 62%  33/30/40 peers ⬇ 248.7kiB/s ⬆ 118.6kiB/s 1.30 bps 743.00 Ggas/s CPU: 112%, Mem: 7.3 GiB
Dec 11 13:17:37.418  INFO stats: #19303121 Downloading blocks 62%  33/30/40 peers ⬇ 252.6kiB/s ⬆ 126.5kiB/s 0.60 bps 742.92 Ggas/s CPU: 113%, Mem: 7.3 GiB
Dec 11 13:17:47.420  INFO stats: #19303121 Downloading blocks 62%  33/30/40 peers ⬇ 255.2kiB/s ⬆ 132.7kiB/s 0.00 bps 0 gas/s CPU: 119%, Mem: 7.3 GiB
Dec 11 13:17:57.422  INFO stats: #19303121 Downloading blocks 62%  33/30/40 peers ⬇ 276.8kiB/s ⬆ 153.2kiB/s 0.00 bps 0 gas/s CPU: 106%, Mem: 7.3 GiB
```

A restart of the node usually fixes the 0bps and the node syncs again (albeit slowly).

**To Reproduce**

1. Start a node with the configuration setting `"archive": true,`
2. Wait a couple of days
3. See the bps drop down to 1-2 (or sometimes 0)

**Expected behavior**

I would expect it to sync faster. I can't say how fast. For a very rough comparison: A Stellar Full History node syncs roughly 5TB of data in about a month.

**Version (please complete the following information):**

- `Version: 1.16.0-rc.2, Build: e3b3e835, Latest Protocol: 39`
- rust version (if local)
- I'm using this docker image: `nearprotocol/nearcore:1.16.0-e3b3e8352be319a78b3d2f2186d4d5539412f7fb`
- mainnet

**Additional context**

nearcore runs on a Google Cloud c2-standard-8 machine with 8 vCPUs and 32GB memory.

CPU load stays around 1.5 and memory usage tends to stay under 2GB. The disk is an SSD.

**Comment by JonasPf** [comment]
In a separate email thread the option of getting the most recent snapshot for an archival node was mentioned. Would that allow us to skip some of the syncing problems?

**Comment by mhalambek** [comment]
We have regular snapshots of archival nodes, unfortunately they are stale now due to a desperate issue
Latest snapshot data should be available starting next week

With snapshot node starts within a few hours

Link to the snapshot data https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/archive/data.tar

Will post here when we resume snapshot data

**Comment by JonasPf** [comment]
Is there any update on this? Has the snapshot data been updated?

**Comment by frol** [comment]
Links to the archival backups are available on the docs now: https://docs.near.org/docs/roles/integrator/exchange-integration#running-an-archival-node
