### ISSUE TITLE
Does ReceiptIndex need to be usize in near_primitives?

### ISSUE THREAD

**Issue by willemneal** [near/nearcore#3769]
I'm currently working to re-organize primitive types and `near-vm-logic` had duplicated and exported some type aliases from `near_primitives`.  However, there was one difference `near-vm-logic` defines `ReceiptIndex` as  `u64` and `near_primitives` defines it as `usize`. Is there a reason behind this?  If not, can it become `u64` so that I can consolidate the two types?

**Comment by bowenwang1996** [comment]
Currently neard can only be run on 64 bits architectures, in which case `usize` is the same as `u64`.

**Comment by bowenwang1996** [comment]
@willemneal are there any action items here? If not let's close this issue
