### ISSUE TITLE
Add details how to run a local node in readme

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3774]
For example how to run a local node in nightly mode vs main mode, connect to different networks and etc.
Also update other links (still nearprotocol.com for example) 

Separately, installation instruction for nearup should include the whole `export PATH="$HOME/.local/bin:$PATH"` part, otherwise it doesn't work.

IMO, ideally either should not include installation instructions of nearup and refer to nearup fully or should be self sufficient part.

**Comment by bowenwang1996** [comment]
@janewang please take a look to see whether there are still action items here

**Comment by bowenwang1996** [comment]
@janewang is this done?

**Comment by janewang** [comment]
@bowenwang1996 WIP, will wrap soon.
