### ISSUE TITLE
Rethink state sync

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3777]
Currently when we do state sync, we request state parts of size at most 1MB. However, when the state size is on the order of gigabytes, it means that a node needs to request thousands of parts and each part takes some time to compute. Since we request all parts at once, this causes unnecessary increase in network traffic, especially since the requests and responses are also routed. We should maybe reconsider the entire approach and see how we make it better when the state size is very large.

**Comment by bowenwang1996** [comment]
cc @mikhailOK

**Comment by mikhailOK** [comment]
Potential ideas:
- Try to speed up computing state parts with a faster trie iterator
- Pre-compute state parts in the background when epoch starts (currently we compute state parts upon receiving a request)
- Manage incoming state part requests. Don't respond twice to duplicate requests, reject instantly if there are too many queued up.

**Comment by Longarithm** [comment]
Tracked around #8545.
