### ISSUE TITLE
Mismatching tag and neard version.

### ISSUE THREAD

**Issue by dtp263** [near/nearcore#3786]
The `neard` version does not match the release tag. This causes tag based builds to report an incorrect neard version via telemetry. 

Mistake can be seen here: https://github.com/near/nearcore/blob/1.16.2/neard/Cargo.toml#L3

Git Tag: 1.16.2
Expected neard version: 1.16.2
Actual neard version: 1.16.2-rc.1

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek please take a look

**Comment by chefsale** [comment]
@bowenwang1996 @mhalambek It seems that when we did the mainnet release somebody forgot to bump the version in the cargo file, we could do another release just to fix it, but we have a new mainnet release next week, so I assume this could be waited out until next release and than bumped properly, so we don't have everybody upgrade twice in a week.

**Comment by chefsale** [comment]
There seems to be a "conflict" of the git tag and branch name being the same, git by default uses the tag, while github uses the branch.

**Comment by mhalambek** [comment]
Removed my commit which causes changes version from 1.16.2 branch, should be ok now
