### ISSUE TITLE
[Tracking Issue] Review the error handling infrastructure

### ISSUE THREAD

**Issue by frol** [near/nearcore#3788]
*This is a tracking issue preparing to dive into #3517.*

* [x] Learn best practices on error handling (`thiserror` is the best crate I know that fits our needs)
* [x] Review the PR #3204 that we need to "rebase" onto the latest master

**Comment by khorolets** [comment]
@frol I guess we should also add something like "come up with design of error structs" for view client

**Comment by frol** [comment]
@khorolets I guess, we can try to copy what Bowen has already done unless we find a better option during review. Ideally, every function should return only what it can potentially return, meaning that there should not be a huge enum with all possible errors in the world, instead, there should be granular types (it can even be just a struct, not an enum, e.g. in Rust standard library there is [`AddrParseError`](https://doc.rust-lang.org/stable/std/net/struct.AddrParseError.html), which is `struct AddrParseError(())`)

@bowenwang1996 I would like to ensure exhautiveness of the potential error responses. How realistic is this approach in your opinion in regarts to the core?

**Comment by bowenwang1996** [comment]
> How realistic is this approach in your opinion in regarts to the core?

It may be possible, but will likely take several months to complete
