### ISSUE TITLE
Investigate the Too many files failure happening due to pam limits not properly propagated to buildkite-agent

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#3792]
Seems like the issue is happening due to the buildkite-agent running under chroot and not applying the pam limits to the session.

I have sent an email to buildkite support and waiting for an answer on how to approach this, as we don't really have much control there.

cc: @bowenwang1996 @artob @mhalambek

**Comment by chefsale** [comment]
Fixed.

**Comment by artob** [comment]
@chefsale What was the resolution mechanism?

**Comment by chefsale** [comment]
I have increased the `LimitNOFILE=10000` in the systemd service configuration for buildkite-agent in `/etc/systemd/system/buildkite-agent.service` and reloaded the deamon with `systemctl daemon-reload`. The file limit is than propagated to all the forked processes from this deamon.
