### ISSUE TITLE
Incompatible with Macs based on the Apple M1 chip

### ISSUE THREAD

**Issue by artob** [near/nearcore#3803]
I'm recording this as a current known limitation: nearcore currently requires an x86 host which supports the [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) extensions.

https://github.com/near/nearcore/blob/daad871d042a838220ce5823d12844e94ce3af1f/runtime/near-vm-runner/src/wasmer_runner.rs#L191-L196

Apple's [Rosetta](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) does not support AVX as of macOS 11.1 (Big Sur):

> Rosetta translates all x86_64 instructions, but it doesn’t support the execution of some newer instruction sets and processor features, such as AVX, AVX2, and AVX512 vector instructions. If you include these newer instructions in your code, execute them only after verifying that they are available.

This effectively precludes running nearcore on [Apple Silicon](https://en.wikipedia.org/wiki/Mac_transition_to_Apple_Silicon), such as the initial Apple M1 chip found in the new 2020 MacBook Pro, MacBook Air, and Mac Mini. While that's unlikely to be an issue for any production deployments, it will increasingly hamper our development as developers switch to new Macs.

The future is NEAR and the future is ARM (on Macs, at least), so we better figure out how to reconcile the two before too long.

**Comment by vgrichina** [comment]
> While that's unlikely to be an issue for any production deployments

probably not this year, but given how much of energy savings M1 gives – I'm pretty sure data centers will start migrating once there is rack mounted option (i.e. likely within next 2 years)

**Comment by vgrichina** [comment]
check this mind blowing benchmark for neural nets training https://wandb.ai/vanpelt/m1-benchmark/reports/Can-Apple-s-M1-help-you-train-models-faster-cheaper-than-NVIDIA-s-V100---VmlldzozNTkyMzg

**Comment by artob** [comment]
Related upstream pull request: https://github.com/wasmerio/wasmer/pull/1831

**Comment by ailisp** [comment]
@artob I recently worked with new version of wasmer, they support wasmer on ARM, this issue is on our side: when it's not x86, we should not require AVX

**Comment by ailisp** [comment]
And this one
>     // TODO(#1940): Remove once NaN is standardized by the VM. =
they claimed fixed: https://github.com/wasmerio/wasmer/issues/1269

**Comment by ailisp** [comment]
@olonho pointed out that Linux ARM and Mac ARM is different compiler backend for Rust and also different rust crates availability, so although I can do some initial attempt on compile rust on a linux arm server, it doesn't mean it would work or not work on a M1 Macbook. @olonho recently have a M1 Macbook, so let me assign him to further investigate this issue :D

**Comment by ailisp** [comment]
FYI https://github.com/rust-rocksdb/rust-rocksdb/pull/483 rust-rocksdb current release also have problem on new mac, waiting for this PR

**Comment by artob** [comment]
To aid in testing M1 support, note that Scaleway have just rolled out M1 hardware in the cloud, Apple-Silicon-as-a-Service:

https://www.scaleway.com/en/hello-m1/

**Comment by webmaster128** [comment]
While there is M1 support for Wasmer in general, there does not seem to be M1 support for Wasmer+Singlepass. This is documented in https://github.com/wasmerio/wasmer/blob/2.0.0/Makefile#L33-L37 and https://docs.wasmer.io/ecosystem/wasmer/wasmer-features#compiler-support-by-chipset. I guess this ticket is blocked on https://github.com/wasmerio/wasmer/issues/2463.

**Comment by Kouprin** [comment]
> check this mind blowing benchmark for neural nets training https://wandb.ai/vanpelt/m1-benchmark/reports/Can-Apple-s-M1-help-you-train-models-faster-cheaper-than-NVIDIA-s-V100---VmlldzozNTkyMzg

FYI https://www.reddit.com/r/MachineLearning/comments/kwqev4/d_comparing_performance_on_apples_m1_with_nvidias/

**Comment by khorolets** [comment]
> > rustup set default-host x86_64-apple-darwin
> 
> Trying that now, will edit this message with results.
> 
> UPDATED: yep, this worked. Cold `nearcore` build on 13" M1 8 RAM is done in 6m 36s

OK, my bad, at that moment I've just checked `cargo build --release -p neard` and the posted the result.

Recently, I've decided to use `neard` and failed. 

I guess it was expected according to different architecture, but still I guess it's worth mentioning in this issue.

```
Running target/debug/neard init --chain-id localnet
fish: Job 1, 'cargo run -p neard -- init --...' terminated by signal SIGBUS (Misaligned address error)
```

/cc @matklad

**Comment by matklad** [comment]
I've had a call with dev-platform team and realised that we really need a seamless support for M1 (and, more generally, a seamless cross-platform story). The reason for that is `sandbox` -- the local instance of `neard` that *contract developers* to test their contracts.

**Comment by artob** [comment]
> Recently, I've decided to use `neard` and failed.
> 
> I guess it was expected according to different architecture, but still I guess it's worth mentioning in this issue.

Building nearcore for x86 was not the issue, running it was. Runtime errors were to be expected, as per the original ticket description:

> Apple's [Rosetta](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) does not support AVX as of macOS 11.1 (Big Sur):
>> Rosetta translates all x86_64 instructions, but it doesn’t support the execution of some newer instruction sets and processor features, such as AVX, AVX2, and AVX512 vector instructions. If you include these newer instructions in your code, execute them only after verifying that they are available.

**Comment by artob** [comment]
> I've had a call with dev-platform team and realised that we really need a seamless support for M1 (and, more generally, a seamless cross-platform story). The reason for that is `sandbox` -- the local instance of `neard` that _contract developers_ to test their contracts.

Good to hear, given that I, like increasingly many developers elsewhere, haven't used x86 for going on a year by now and don't expect that to change back.

**Comment by ChzenChzen** [comment]
Hi. I can't build near-core for my indexer project. I use `channel = "stable-x86_64-apple-darwin"` on my m1 mac. I wonder if I do something wrong, or it's because nearcore isn't available for m1 users?

**Comment by jackrobsonalpha** [comment]
to confirm this means m1's cannot run the local develop env described in: https://docs.near.org/docs/tools/kurtosis-localnet

or is there a workaround?

**Comment by rsilvestre** [comment]
> Now I regret not getting a M1 Macbook :(

Now I regret getting a M1 Macbook Pro :(

**Comment by frol** [comment]
I have tested neard with #6200 patch and it works great on my Macbook with Apple M1 chip (except that I needed to hotfix #6293 as otherwise the node crashes on boot)!

While neard cannot be used on M1 in production given that it uses wasmtime instead of wasmer, I believe this particular issue should be closed as the main concern was usability during development cycles and it is now addressed! Kudos to @Ekleog 🎉 

@Ekleog If you believe there is still some work left to be done, feel free to re-open this issue or open a new one.

**Comment by ChzenChzen** [comment]
https://github.com/near/nearcore/pull/6200#issuecomment-1059641212
