### ISSUE TITLE
Prevent compilation with `--all-features` flag

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3815]
Many our features were not designed to be enabled simultaneously and effects of doing so are unknown. However, sometimes we compile `nearcore` with `--all-features` flag, e.g.: 
```
RUSTFLAGS='-D warnings' cargo check --all --tests --benches --all-features
```

We need to prohibit it to prevent potential misusage. We can do it by adding two artificial mutually exclusive features that prohibit compilation, into `neard` crate:
```rust
#[cfg(feature = "disable-all-features-a")]
struct NotUsedStruct;

#[cfg(feature = "disable-all-features-b")]
struct NotUsedStruct;
```
then when someone compiles with `--all-features` the compilation will fail, because of the redeclaration of the struct.

**Comment by bowenwang1996** [comment]
@nearmax The reason we do
```
RUSTFLAGS='-D warnings' cargo check --all --tests --benches --all-features
```
is not to compile all features so that we can use it for some other purpose. Rather, we would like to make sure that all features can be compiled and hence we use `cargo check` here. I am not sure how this can be done better.

**Comment by bowenwang1996** [comment]
Closing as it looks like there is no action item here. Please reopen if there are unaddressed issues here
