### ISSUE TITLE
Archival node Unable to sync

### ISSUE THREAD

**Issue by hzccc** [near/nearcore#3817]
**Describe the bug**
Waiting for peers all the time

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch:1.16.2
- rust version :1.45.0-nightly
- mainnet

**Additional context**
![image](https://user-images.githubusercontent.com/20179548/105009529-8ab93880-5a75-11eb-9028-b218f09101fd.png)

**Repeat**
./target/release/neard --home="/data2/nearcore/data" init --chain-id="mainnet"
./target/release/neard --home="/data2/nearcore/data" run --archive

**Comment by bowenwang1996** [comment]
Did you use the same node key somewhere else?

**Comment by hzccc** [comment]
> Did you use the same node key somewhere else?

No.

**Comment by hzccc** [comment]
> Did you use the same node key somewhere else?

By the way, how to estimate the transaction fee? I'd like to estimate the fees before initiating the transaction. Is there a formula?

**Comment by hzccc** [comment]
I did it again
![image](https://user-images.githubusercontent.com/20179548/105119214-d833b500-5b0a-11eb-8791-dfcdb941dc4e.png)

**Comment by bowenwang1996** [comment]
@hzccc does your config.json have any bootnodes? If not, you can either add bootnodes yourself or use https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/config.json

**Comment by hzccc** [comment]
> @hzccc does your config.json have any bootnodes? If not, you can either add bootnodes yourself or use https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/config.json

Thinks! May I have two more questions. 
1.How Do I get to how many tokens I mortgaged through the RPC. 
2.How to estimate transaction fees, is there a formula,I want to estimate the fee when creating a transaction
