### ISSUE TITLE
Document the process of introducing a new protocol version

### ISSUE THREAD

**Issue by frol** [near/nearcore#3823]
We currently have a deprecated (using independent consts in [version.rs](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L24-L53)) and a new version ([`ProtocolFeature enum`](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L78-L87) with [`STABLE_PROTOCOL_FEATURES_TO_VERSION_MAPPING`](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L98-L100) and [`nightly_protocol_features_to_version_mapping`](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L115-L127) with a helper [`checked_feature` macro](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L143)) of how we deal with the features that require protocol upgrade.

# Acceptance Criteria

* [ ] `ProtocolFeature` enum has the documentation covering the new protocol feature introduction flow
* [ ] `checked_feature` macro has the usage examples for all its variants (returning a boolean and covering the blocks)
* [ ] The deprecated way of managing new protocol versions using consts is either migrated to the new way or clearly marked as deprecated

**Comment by bowenwang1996** [comment]
There is some work in progress on this and I need to finish it up.

**Comment by frol** [comment]
Extra notes:

I would prefer if we use `checked_feature` macro whenever we need a conditional behavior based on the protocol version (even if adding the feature to `STABLE_PROTOCOL_FEATURES_TO_VERSION_MAPPING` directly). We should avoid manual protocol version checks like

BEFORE:

```rust
if protocol_version < CREATE_RECEIPT_ID_SWITCH_TO_CURRENT_BLOCK_VERSION
```

AFTER:

```rust
if checked_feature!(CreateReceiptIdSwitchToCurrentBlock, protocol_version)
```

, **HOWEVER** currently the `checked_feature` macro expects that there is a dedicated cargo feature flag, so it requires the first parameter to be the name of the cargo feature flag:

```rust
if checked_feature!("protocol_feature_create_receipt_id_switch_to_current_block", CreateReceiptIdSwitchToCurrentBlock, protocol_version)
```

, so we probably need another macro variant that does not require a dedicated cargo feature flag.

Also, it seems that we don't need a HashMap for `PROTOCOL_FEATURES_TO_VERSION_MAPPING`, instead, we can have `mod` with `consts`:

```rust
pub mod stable_protocol_features {
    pub const PROTOCOL_FEATURE_SHARD_CHUNK_HEADER_UPGRADE: ProtocolVersion = ProtocolVersion(41);
}

#[cfg(feature = "nightly_protocol")]
pub mod nightly_protocol_features {
    #[cfg(feature = "protocol_feature_evm")]
    const PROTOCOL_FEATURE_EVM: ProtocolVersion = ProtocolVersion(46);
}

pub mod protocol_features {
    use super::stable_protocol_features::*;

    #[cfg(feature = "nightly_protocol")]
    use super::nightly_protocol_features::*;
}
```

`checked_feature` macro can be easily adjusted.

**Comment by ilblackdragon** [comment]
Also would be great to document things like this: https://github.com/near/nearcore/pull/3827#issuecomment-765153080
And update the upgradability section in Nomicon to include details about "nightly protocol". Even though it's not fully protocol level concern (e.g. clients have their own features / nightly versions) it still worth considering the process of having nightly as a general pattern that all clients should have.

**Comment by bowenwang1996** [comment]
Now we have https://github.com/near/nearcore/blob/master/docs/protocol_upgrade.md that documents this process
