### ISSUE TITLE
Add `cargo test` to CI

### ISSUE THREAD

**Issue by frankbraun** [near/nearcore#3833]
`cargo test` was broken in e2e6bd63f3d6ad34e0711d8068d755ac480e0b8e (see #3832) but the build is shown as "passing".
It would be good to add `cargo test` to the CI pipeline to prevent such problems.

Or even better, `cargo test --features protocol_feature_evm,nightly_protocol_features`, such that the new EVM features are tested as well.

**Comment by chefsale** [comment]
This is already running as part of the CI, so closing the issue.
