### ISSUE TITLE
Understand current syncing time

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3839]
There have been multiple reports that the time it takes to sync a node to mainnet is quite suboptimal. It is important to understand where we are at with syncing in its current form and it may impact how we want to roll out the new syncing.

**Comment by frol** [comment]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/304265/200527685-115adc05-6106-4f62-97fa-7864de7ec5b1.png">

It is indeed unclear if it got stuck or if it just needs more time (it is trying to get through state sync for more than 1.5 hours already).

It is a non-archival node running nearcore 1.29.0 release on mainnet.

**Comment by Longarithm** [comment]
Tracked around #8545.
