### ISSUE TITLE
Docker cannot build using "docker build ."

### ISSUE THREAD

**Issue by mikedotexe** [near/nearcore#3849]
***Describe the bug***
 After performing `docker build .` in the project root, several errors happen. Here are some snippets that might be helpful, seemingly related to rocksdb:

> error: failed to run custom build command for `librocksdb-sys v6.10.2 ([https://github.com/nearprotocol/rust-rocksdb?branch=disable-thread#44592812](https://github.com/nearprotocol/rust-rocksdb?branch=disable-thread#44592812))`
 > #15 547.8
 > #15 547.8 Caused by:
 > #15 547.9 process didn't exit successfully: `/tmp/target/release/build/librocksdb-sys-11e7f831e59698bd/build-script-build` (exit code: 1)
 > …
 > error occurred: Command "c+

<ins>" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-std=c</ins>

<ins>11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/tmp/target/release/build/librocksdb-sys-ea35b8aae8e84238/out/rocksdb/db/db_impl/db_impl.o" "-c" "rocksdb/db/db_impl/db_impl.cc" with args "c</ins>

+" did not execute successfully (status code exit code: 4).
 > …
 > executor failed running <span class="error">[/bin/sh -c cargo +"$(cat /tmp/rust-toolchain)" build -p neard --release &amp;&amp; mkdir /tmp/build &amp;&amp; cd /tmp/target/release &amp;&amp; mv ./neard /tmp/build]</span>: exit code: 101

***To Reproduce***

 docker build .

***Expected behavior***
 Docker builds without issues

***Screenshots***

***Version (please complete the following information):***
 `rustc version` gives
 >rustc 1.49.0-nightly (91a79fb29 2020-10-07)

*   docker (if using docker)
     Docker Desktop on MacOS 3.0.4

*   mainnet/testnet/betanet/local
     Not specified explicitly

***Additional context***
 If there's a different command I'm supposed to use to run Docker, please let me know. I didn't see other instructions in the README, we may want to add some.

**Comment by mikedotexe** [comment]
Actually, following some notes from this post:
https://bitcointalk.org/index.php?topic=304389.0

I upped the limits on my Mac's Docker Desktop and it seemed to get farther before running into this:

> Caused by:
>   could not write to '/usr/local/cargo/git/checkouts/openethereum-73b1d27a6fe08245/2662d19/secret-store/src/key_server_cluster/io/message.rs': No space left on device; class=Os (2)

So now I've upped it even more:

<img width="795" alt="Screen Shot 2021-01-24 at 4 28 32 PM" src="https://user-images.githubusercontent.com/1042667/105648635-5bce0880-5e61-11eb-9f3f-0a60e01911e1.png">

and it built. So I don't know the exact amount (it took over 24 minutes to build)

<img width="844" alt="Screen Shot 2021-01-24 at 4 38 56 PM" src="https://user-images.githubusercontent.com/1042667/105649176-eb74b680-5e63-11eb-8ff2-b8f8f6a26973.png">

but this is probably something we should flag in the README

**Comment by ailisp** [comment]
@mikedotexe The recommend way of build is via `make docker-nearcore`, which use this command under the hood:
```
	DOCKER_BUILDKIT=1 docker build -t nearcore -f Dockerfile .
```

The difference is DOCKER_BUILDKIT=1 enables docker to build with multiple cpu cores

**Comment by bowenwang1996** [comment]
@mikedotexe is there any action item here? If not let's close the issue
