### ISSUE TITLE
Exhaustively define error types to improve correctness (security and stability) and maintainability

### ISSUE THREAD

**Issue by frol** [near/nearcore#3851]
Ideally, every function should return only what it can potentially return, meaning that there should not be a huge enum with all possible errors in the world (like [`ErrorKind` in chain](https://github.com/near/nearcore/blob/17701a2616416d66874f216ff590651dec33b72b/chain/chain/src/error.rs#L22-L176)), instead, there should be granular types (it can even be just a struct, not an enum, e.g. in Rust standard library there is [`AddrParseError`](https://doc.rust-lang.org/stable/std/net/struct.AddrParseError.html), which is `struct AddrParseError(())`)

> @frol: I would like to ensure the exhaustiveness of the potential error responses. How realistic is this approach in your opinion in regards to the core?

> @bowenwang1996: It may be possible, but will likely take several months to complete

https://github.com/near/nearcore/issues/3788#issuecomment-756304365

Pros:

* Methods are sealed and have clear possible outcomes
* Methods with clear outcomes are easier to compose with each other in a predictable way
* From a stability point of view, methods with clear outcomes are "tested" by Rust compiler for free (Rust compiler will guard us during refactoring ensuring that we handle all the corner cases)
* From a security point of view, methods with clear outcomes can be easier to reason about and do not have surprises (unhandled use-cases, especially in a long run)
* From API UX point of view, it is easier to reason about the possible outcomes and handle them exhaustively (Rust compiler will help us here again), and it is especially useful for our public APIs like JSON RPC (see #2976, #3517, and #3518)

Cons:

* It feels verbose to introduce a new error type when you don't have one that matches your use-case. This should be addressed by setting up a proper framework (hopefully #3805 will pave the road here)

**Comment by volovyk-s** [comment]
@frol Is there a possibility that two or more functions will return the same error type? How we will manage them in this case?

**Comment by frol** [comment]
@volovyk-s If the methods share semantics, we can use the same error type, otherwise, we can compose the error types (extract common parts into a separate entity and implement simple wrappers for the specific needs of the functions)

**Comment by bowenwang1996** [comment]
@frol what are the action items here?

**Comment by frol** [comment]
We strictly defined our JSON RPC layer errors and while we struggled to identify all the possible underlying error cases, we managed to handle those. This issue does not have any action items at the moment, so I am closing it.
