### ISSUE TITLE
Node cannot start if compiled with `memory_stats`

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3886]
To reproduce, checkout out the most recent commit on master (91bba0713a7ac19e85c901a7106afcb2b53e700e) and do
```
cargo build -p neard --features memory_stats
cd pytest
python3 tests/sanity/block_production.py
```
and observe that nodes fail to start
```
=== Error: failed to start node, rpc does not ready in 10 seconds
```

**Comment by pmnoxx** [comment]
@bowenwang1996 Are you running in on mac?

**Comment by bowenwang1996** [comment]
> @bowenwang1996 Are you running in on mac?

Yes

**Comment by pmnoxx** [comment]
The node starts, but it's slow. We can fix it with https://github.com/near/near-memory-tracker/pull/5/files

**Comment by pmnoxx** [comment]
https://github.com/near/nearcore/pull/3888
