### ISSUE TITLE
Near stop processing blocks on epoch change

### ISSUE THREAD

**Issue by mabalaru** [near/nearcore#3895]
**Describe the bug**
In mainnet, when the epoch change, the node stop sync'ing and it's not processing new blocks. 
The last line on log is: 
```
Feb  3 07:33:00 ino-near01 neard[5091]: #033[2mFeb 03 07:33:00.527#033[0m #033[32m INFO#033[0m stats: #29044239 DpEWG5qCqPXdjki2uZj8MFV9L6H8QUTmHWGNXuhfe9Nn V/56 31/30/40 peers ⬇ 302.6kiB/s ⬆ 293.0kiB/s 0.90 bps 0 gas/s CPU: 272%, Mem: 5.1 GiB
Feb  3 07:33:24 ino-near01 neard[5091]: #033[2mFeb 03 07:33:24.396#033[0m #033[33m WARN#033[0m network: Received invalid tx from peer Some(ed25519:BUmFALW9sum43kunTmrj2nD65VGYgoFaG8WbWWMiLQsa@35.197.16.22:24567): Transaction nonce 877289 must be larger than nonce of the used access key 877374
Feb  3 07:35:10 ino-near01 neard[5091]: #033[2mFeb 03 07:35:10.543#033[0m #033[32m INFO#033[0m stats: #29044244 Downloading blocks 99%  31/6/40 peers ⬇ 210.3kiB/s ⬆ 115.8kiB/s 0.04 bps 0 gas/s CPU: 132%, Mem: 5.1 GiB
```
If you restart the neard process, the node will be stuck with "Waiting for peers" and the process hand with 100% usage. 

```
| inotel.poolv1.near                    | 4,688,463  | 1       | 0%       |               0 |               8 |
```

**To Reproduce**
Not sure how can we manually reproduce this

**Expected behavior**
Node should process blocks on new epoch

**Screenshots**
**Version (please complete the following information):**
NEAR Protocol Node 1.17.0 (build 02396e9d) -- Mainnet

**Additional context**
To solve the issue I have to import the data folder from a working server and change the node_id.

**Comment by bowenwang1996** [comment]
@mabalaru given what we have discussed, could this be caused by your rpc queries?

**Comment by mabalaru** [comment]
Yes Bowen, the issue was form RPC queries which hanged the node from sync. Thank you for your support
