### ISSUE TITLE
Improve memory dump tools to analyze memory usage per Rust thread

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3978]
I recently added printing memory usage per thread. We've seen cases where some PeerActors, where using up to 3gb of memory.
I'll work on improving tools the dump tool to analyze memory usage per thread.

- [x] add dump.sh to make it simpler to run analyzer
- [x] add <TID> paramater
- [ ] add few extra debugging paramaters

**Comment by bowenwang1996** [comment]
@pmnoxx is this done already?

**Comment by bowenwang1996** [comment]
@pmnoxx any update on this?

**Comment by pmnoxx** [comment]
@bowenwang1996 I'll check what's left to do and give you update.

**Comment by pmnoxx** [comment]
@bowenwang1996 Yes, everything that I planned has already been finished. We can add more features if we find that something is missing. Feel free to reopen this PR or open a new one if some particular feature is needed.
