### ISSUE TITLE
How to query every block from genesis?

### ISSUE THREAD

**Issue by Brochao** [near/nearcore#3989]
Got error when query an early block:

`{"jsonrpc":"2.0","error":{"code":-32000,"message":"Server error","data":"Block Missing (unavailable on the node): 4EZn16JrHvB52A8G4JzkYn6RgDRt8z9FcLGYftb8QUFu \n Cause: Unknown"},"id":"curltext"}`

only recently blocks can be queried.

**Comment by bowenwang1996** [comment]
You need to use an archival node https://docs.near.org/docs/roles/integrator/exchange-integration#running-an-archival-node
