### ISSUE TITLE
NEAR shouldn't ship with Cargo.lock for libraries

### ISSUE THREAD

**Issue by joshuajbouw** [near/nearcore#3991]
**Describe the bug**
As with the build issue with https://github.com/near/near-evm/pull/65 and https://github.com/near/near-sdk-rs/issues/292, it isn't correct to ship a `Cargo.lock` with libraries and binaries should be considered to not be included in the `Members =` section of the root level `Cargo.toml`. Then generate a seperate `Cargo.lock` per binary as it is the end of the dependency chain. This can cause issues such as dependency clashes.

Reference: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**To Reproduce**
Potentially, `Cargo.lock` can become outdated and newly added dependencies can cause clashes. Bit tricky to quite exactly reproduce.

**Expected behavior**
A clean use of the library in another library or binary shouldn't cause dependency clashes without running `cargo update`.

**Screenshots**

**Version (please complete the following information):**
- nearcore master
- rust version 1.52.0-nightly

**Comment by frol** [comment]
We don't release nearcore with Cargo.lock, that is the reason why those issues raise in the first place, exactly due to the lack of pinning.
