### ISSUE TITLE
Replace all usage of `include_bytes` with `lazy_static_include_bytes`

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3996]
`include_bytes` is slowing compilation time and require recompilation when a dependency is touched

It'll save ton of $$$ on CI

**Comment by rishank-shah** [comment]
Hi. I am new to contributions. I would like to give this issue a try if it's okay with you.

**Comment by KaiserKarel** [comment]
Mind if I pick this up?

**Comment by bowenwang1996** [comment]
@KaiserKarel please feel free to take it

**Comment by matklad** [comment]
Note that lazy_static_include is not *exactly* what we need for tests. It has this "if release, just `include!`" logic, which isn't necessary and slows down compilation in release (when benchmarking). What we need is just "read file at runtime", and this doesn't need to be a macro. There's a once_cell recipe for that:

https://github.com/matklad/once_cell/blob/master/src/lib.rs#L167-L200

If we have some common dependency for our tests, we can put it there. 

But the actual diff is minor here, lazy_static_inculude_bytes works ok, it just does a couple of unnecessary hops.

**Comment by bowenwang1996** [comment]
Fixed in #4053
