### ISSUE TITLE
Investigate if trie iterator can be sped up

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#4011]
Look for low hanging fruit optimizations we can do right now without a storage redisign

**Comment by bowenwang1996** [comment]
What are the possible optimizations here?

**Comment by mikhailOK** [comment]
multiget didn't give much improvement, hacky prototype here https://github.com/near/nearcore/tree/trie_multiget_testing.

**Comment by bowenwang1996** [comment]
> multiget didn't give much improvement

Do you have a more concrete number?

**Comment by mikhailOK** [comment]
Tens of % speedup. Orders of magnitude gain not possible without changing storage format.
