### ISSUE TITLE
produce_block_with_approvals_arrived_early is flaky

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4042]
The test seems to be flaky https://buildkite.com/nearprotocol/nearcore/builds/6012#2618fca2-004c-4396-9763-f2f159b2151a. I have trouble reproducing the failure locally

**Comment by bowenwang1996** [comment]
@mikhailOK any update on this? This test `test_ban_peer_for_ill_formed_block` also seems flaky https://buildkite.com/nearprotocol/nearcore/builds/88#0b2ea479-053f-40ef-93d1-49742514097c

**Comment by Longarithm** [comment]
Same issue for build https://buildkite.com/nearprotocol/nearcore/builds/303#c9b39ff8-f4d0-4444-869b-25a8eb73171c, couldn't reproduce locally

**Comment by Longarithm** [comment]
Noticed a flakiness in `test_ban_peer_for_ill_formed_block` again.

[Buildkite link](https://buildkite.com/nearprotocol/nearcore-ghsa-5p2h-xpv5-f88m-dot-git/builds/11#200e6df4-f133-4e3d-a513-ae7e7ff45344)

[Error message](https://hackmd.io/5wPClC1LTp2mszViR1_4-w) if you don't have access
