### ISSUE TITLE
How wasmer is integated with near blockchain?

### ISSUE THREAD

**Issue by apiscerena** [near/nearcore#4056]
hey, I'm interested in wasm-based near vm. Wanna know how wasmer is integated with near blockchain, like the gas metering, determinstric solutions?. Any detailed docs, cause i cannot find any related reading materials.

**Comment by bowenwang1996** [comment]
@olonho do we have any documentation on this?

**Comment by bowenwang1996** [comment]
@olonho @matklad any update on this?

**Comment by matklad** [comment]
We don't have suuuper thorough docs here but

https://github.com/near/nearcore/blob/master/runtime/near-vm-runner/README.md

and 

https://github.com/near/nearcore/blob/master/runtime/near-vm-runner/FAQ.md

should be enough to get started. The integration isn't particularly complicated, so reading the relevant sources will also help:

https://github.com/near/nearcore/tree/master/runtime/near-vm-runner/src

I am closing the issue, but feel to open a Q&A [discussion](https://github.com/near/nearcore/discussions/categories/q-a) and tag @matklad if you have further questions!
