### ISSUE TITLE
Fully switch to wasmer 1 by default

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4076]
In https://github.com/near/nearcore/pull/3799, @ailisp implementing support for wasmer 1.0 :tada: 

However, we are still using wasmer 0.17 by default -- major upgrade of vm version is not a laughing matter, we must make sure that the two behave identically. This issue exists to track our progress on switching to wasmer 1.0 by default, and eventual removal of support for wasemer 0.17 from the tree. 

The next step in transition is to deploy a *fraction* of nodes with `wasmer1` to the beta net.

**Comment by matklad** [comment]
@ailisp am I correct that enabling wasmer1 is just `cargo build --release --features wasmer1_default`? Is anyone actively looking into deploying & monitoring that on betanet?

**Comment by matklad** [comment]
@bowenwang1996 is there anything else we can do besides "deploy to beta and observe" to make sure that transition goes smoothly?

**Comment by bowenwang1996** [comment]
@chefsale @mhalambek let's do the following:
- Deploy a node on testnet and a node on mainnet using this commit https://github.com/near/nearcore/commit/79f173271665534288a5ddf126b386668fa5682f
- Run them until the next release
- Set up alerts to make sure we are notified when they crash

This should give us ~1 month of testing in production. @matklad are there other tests that you would like to see done?

**Comment by ailisp** [comment]
@matklad correct

**Comment by matklad** [comment]
>are there other tests that you would like to see done?

If one node behaves OK, we should try to deploy *half* of the nodes, to make sure that network with mixed versions work.

**Comment by bowenwang1996** [comment]
> If one node behaves OK, we should try to deploy half of the nodes, to make sure that network with mixed versions work.

I don't think that is needed because whether it works solely depends on the transactions, which means that it is sufficient to use a one-node canary that will apply all the transactions. Having more nodes does not improve testing coverage in this case.

**Comment by chefsale** [comment]
The current releases on testnet and mainnet do not have the wasmer1 file. Should w:
1. wait until this get release in the proper cycle and than try to create a machine which will be running this and do the rollout
2. @matklad can create a branch `testing-wasmer` with all the cherry picks needed to run the thing and I can add ` --features wasmer1_default` to the makefile on top of that and build the binary and release that.

cc: @bowenwang1996 @mhalambek

**Comment by chefsale** [comment]
I talked to @matklad, we wanted to create enable the wasmer1 based on the current release 1.18.0 and 1.18.1. They do not contain the wasmer changes. Even if we decide to create a build and run one node based of the commit: https://github.com/near/nearcore/commit/79f173271665534288a5ddf126b386668fa5682f, we still will need for the next release which includes this change. 

So my proposal was to:
1. actually wait until these changes cut an actual release, we make sure that that release without wasmer1 enabled is running fine
2. create a release from that release 1.19.0-wasmer1 for example with the Make file cherry-picked on top which enables wasmer1
3. Deploy on node with that release to mainnet and testnet
4. Deploy that release on all of our nodes
5. Make that release 1.19.1 and officially lets external people to use it.

I think this is most likely a safer approach, not sure how burning this is. cc: @matklad

**Comment by matklad** [comment]
Yes, I definitely agree that it's safer to release 1.19 without wasmer1, and than test wasmer1 on top of that, and that switch to wasmer in a separate (minor/patch) release. 

That being said, deploying a node today from  79f1732 will help us to discover and fix bugs earlier. It won't affect when we ship, but it would improve the quality of what we ship, as more time will pass between last bug-fixes and actual deployment. 

So, if that's not too difficult, I would prefer to have nodes from 79f1732 as an additional help.

**Comment by chefsale** [comment]
Yes, in that case I will create a seperate branch from https://github.com/near/nearcore/commit/79f173271665534288a5ddf126b386668fa5682f which enabled wasmer in the Makefile and we will deploy this.

**Comment by chefsale** [comment]
Created a branch for the wasmer build: https://github.com/near/nearcore/tree/wasmer1-enabled

**Comment by chefsale** [comment]
Created the release builds:
https://buildkite.com/nearprotocol/nearcore-release/builds/479
https://buildkite.com/nearprotocol/nearcore-perf-release/builds/117

**Comment by chefsale** [comment]
Please review: https://github.com/near/near-ops/pull/445. This is creating the wasmer1 enabled canaries. @bowenwang1996 @mhalambek @matklad

**Comment by chefsale** [comment]
Machines are running:
rpc-prod => canary-wasmer-mainnet-rpc-node-kmqt
near-core => canary-wasmer-testnet-rpc-node-gtfp

but they die:
```
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]: Mar 18 12:26:11.859  WARN near_rust_allocator_proxy::allocator: Thread 3102 reached new record of memory usage 512MiB
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:    0: <near_rust_allocator_proxy::allocator::MyAllocator as core::alloc::global::GlobalAlloc>::alloc
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/near-rust-allocator-proxy-0.2.8/src/allocator.rs:203:26
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:    1: __rg_alloc
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/neard/src/main.rs:26:1
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::alloc::alloc
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/alloc.rs:74:14
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::alloc::Global::alloc_impl
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/alloc.rs:153:73
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <alloc::alloc::Global as core::alloc::AllocRef>::alloc
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/alloc.rs:203:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::raw_vec::RawVec<T,A>::allocate_in
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/raw_vec.rs:186:45
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::raw_vec::RawVec<T,A>::with_capacity_in
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/raw_vec.rs:161:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::raw_vec::RawVec<T>::with_capacity
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/raw_vec.rs:92:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       alloc::vec::Vec<T>::with_capacity
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/vec.rs:355:20
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       base64::decode::decode_config
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.11.0/src/decode.rs:109:22
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       base64::decode::decode
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.11.0/src/decode.rs:85:5
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       near_primitives_core::serialize::from_base64
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives-core/src/serialize.r
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:    2: near_primitives_core::serialize::base64_format::deserialize
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives-core/src/serialize.r
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:    3: <<<near_primitives::state_record::_::<impl serde::de::Deserialize for near_primitives::state_record::StateRecord>::deserialize::__Visitor as ser
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives/src/state_record.rs:
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.123/src/de/mod.rs:785:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <serde_json::de::MapAccess<R> as serde::de::MapAccess>::next_value_seed
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.61/src/de.rs:1984:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       serde::de::MapAccess::next_value
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.123/src/de/mod.rs:1846:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <<near_primitives::state_record::_::<impl serde::de::Deserialize for near_primitives::state_record::StateRecord>::deserialize::__Visitor as serd
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives/src/state_record.rs:
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.61/src/de.rs:1817:31
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <serde_json::de::VariantAccess<R> as serde::de::VariantAccess>::struct_variant
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.61/src/de.rs:2037:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <near_primitives::state_record::_::<impl serde::de::Deserialize for near_primitives::state_record::StateRecord>::deserialize::__Visitor as serde
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives/src/state_record.rs:
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:    4: <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_enum
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.61/src/de.rs:1850:38
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       near_primitives::state_record::_::<impl serde::de::Deserialize for near_primitives::state_record::StateRecord>::deserialize
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/builds/buildkite-i-00c4cecfed2f7980e-1/nearprotocol/nearcore-perf-release/core/primitives/src/state_record.rs:
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.123/src/de/mod.rs:785:9
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       <serde_json::de::SeqAccess<R> as serde::de::SeqAccess>::next_element_seed
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:              at var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.61/src/de.rs:1925:37
Mar 18 12:26:11 canary-wasmer-testnet-rpc-node-gtfp sh[3099]:       serde::de::SeqAccess::next_element
```
cc: @matklad @ailisp

**Comment by bowenwang1996** [comment]
@chefsale can you post the reason why the crash? What you posted is just a stacktrace from memory stats, which does not indicate why the node crashed.

**Comment by chefsale** [comment]
I mean the log is long, you can take a look at the full log at the machine: with `journalctl -u neard`, but the reason on the end says:
```
Mar 18 12:29:06 canary-wasmer-testnet-rpc-node-gtfp sh[14040]: Mar 18 12:29:06.617 ERROR near: DB version 17 is created by a newer version of neard, please update neard or delete data
```
I assume this is what you were looking for. The stacktrace from above is from this error i assume.

**Comment by bowenwang1996** [comment]
> The stacktrace from above is from this error i assume.

No. As I said, it is the result of enabling memory_stats.

> I assume this is what you were looking for.

Yes. This indicates that there is a database version mismatch, which is likely caused by you trying to run the node with a commit that has an older database version than what was run before. This has nothing to do with wasmer1. I'd suggest that you try a more recent commit.

**Comment by ailisp** [comment]
The error is generated by `CARGO_PROFILE_RELEASE_DEBUG=true`. it can continue run after print these mem alloc > 512M fail error messages. Without this env var and rebuild there's no error. 
The .near/data has a database version problem as mentioned by @bowenwang1996, so i copied key, config and genesis.json to .near2
Then observe combination of with/without .near2/data, wasmer0_default/wasmer1_default, wasmer1_default doesn't use more memory than wasmer0_default in peek and after peek, so I think this isn't an issue.
To make sure this is not related to wasmer1, I'll also check if previous commit/this commit with wasmer0_default, with `CARGO_PROFILE_RELEASE_DEBUG=true`, whether will it showing this error message, I think it will, because 512M is far less than the memory need for bootstrap a testnet node (top shows > 40% of 16G ram used at peek)

**Comment by ailisp** [comment]
I just confirmed from build previous commit a6375193f16526064b46397f49bed786bf729755 that this fail is not related to wasmer1. So there're two errors:
1. large memory alloc warnings, which also happened in previous commit and this does not cause node crash. Also, we're okay with bootstrap a testnet node use high load of mem (and wasmer1 doesn't use more than wasmer0 node), this debug output is for observing memory consumption in long running node.
2. database version error. This also unrelated to wasmer1, there's no database format change, can be resolved by @bowenwang1996 suggested way, or simply delete .near/data to let it create new version of database that state synced from other nodes, works too.

**Comment by chefsale** [comment]
Machine on mainnet: `canary-wasmer-mainnet-rpc-node-kmqt` is running the version from commit: https://github.com/near/nearcore/commit/79f173271665534288a5ddf126b386668fa5682f that is working.

I migrated testnet to the current master (rebased): https://github.com/near/nearcore/tree/wasmer1-enabled. It is running on the machine: `canary-wasmer-testnet-rpc-node-jg6j` working as well. 

Let me know if you need anything else and when do we plan to start migrating testnet first. Probably give it a few days running first. cc: @matklad @ailisp @bowenwang1996

**Comment by matklad** [comment]
One important thing we need to do before switching to wasm 1.0 is auditing wasmer 1 error paths, to make sure that non-deterministic errors a-la OOM crash the node, instead of being treated as deterministic failure to execute the contract. We have this logic for wasmer 0.7 [here](https://github.com/matklad/nearcore/blob/4d414c0bcf6e01519afd663770823383a477b7a5/runtime/near-vm-runner/src/wasmer_runner.rs#L92-L170), it needs to be updated to cover wasmer 1.0 as well. 

@olonho volunteered to look into this, and maybe even write some fault-injection tests for this logic.

**Comment by bowenwang1996** [comment]
@matklad @chefsale I thought about this again and realized that what I said before didn't make sense. We should run more nodes with wasmer1 since this will increase the chance of nondeterministic errors happening and can help better test wasmer1. I suggest the following:
* First, we switch all our testnet nodes to use wasmer1
* If that works well, we switch all our mainnet nodes to use wasmer1.
* If no issue is observed for more than 1 month, we can switch to wasmer1 by default.
What do you think?

**Comment by matklad** [comment]
How hard would it be to switch only half of nodes at a time? I fear cases where we need to rollback wasmer 1.0 due to some yet unknown issue, and, after rollback, realize that wasmer 0.17 is broken as well, because we didn't use it  on the test net for some time. 

Other than that, good idea. We probably need to merge #4181 first though (might be done with it today even?)

**Comment by bowenwang1996** [comment]
> How hard would it be to switch only half of nodes at a time? I fear cases where we need to rollback wasmer 1.0 due to some yet unknown issue, and, after rollback, realize that wasmer 0.17 is broken as well, because we didn't use it on the test net for some time.

Sure we can do that

**Comment by matklad** [comment]
One more thing to do here: re-run params estimator, to makes sure that wasmer1 estimated fees are not worse than 0.17 fees. Note that we don't necessary want to lower the fees together with wasmer1. We can do that separately, as long as estimates are lower, and we might want to batch fees lowering with other changes, like addition of fees for contract compilation on deployment.

**Comment by matklad** [comment]
@ailisp  @olonho @bowenwang1996 I realized there's an unresolved question about wasmer 1 rollout. Namely: should we switch to wasmer 1 in lockstep with enabling compilation on deploy, removing memory cache and upgrade costs?

Summary of the current state:

* wasmer 0.17 is default, it has on-disk contract cache and in-memory contract cache. It doesn't have compilation on deployment. 
* wasmer 1.0 is not default, it has on-disk contract cache, but it *doesn't* have in-memory cache. It doesn't have compilation on deployment. 

Cost measurements show that wasmer1 is not slower for all metrics ([ref](https://github.com/near/nearcore/pull/4231#issuecomment-823315849)). Note that costs do not reflect in-memory cache -- during estimation, the cache is disabled. 

I see three ways forward: 

1. we just flip default to wasmer1
2. we add in-memory caching to wasmer1 and flip the default
3. we don't add in-memory caching, we do enable precompilation, upgrade costs and switch to wasmer1

To me, it seems that option 2. is the safest, as it minimizes the diff with the current state, and doesn't requite protocol upgrade as it doesn't touch costs. So, do you agree that we should do the following?

* add in-memory caching to wasmer1, to preserve parity with wasmer0.17, and with understanding that we'll switch to precompilation as the next work-item after switching to wasmer1
* change #4231 to not actually switch the costs, precompilation & wasmer version just yet.

checkbox list to make sure we have consensus:

- [ ] @ailisp 
- [ ] @olonho 
- [ ] @bowenwang1996

**Comment by olonho** [comment]
Fine, let's make 4231 less intrusive. Also attached there latest costs update.

**Comment by bowenwang1996** [comment]
@matklad should we close this one given that we are now planning to move to wasmer2?

**Comment by matklad** [comment]
Yeah, let's close this for now: it's pretty clear that we need to do significant changes on the wasmer side before we can reconsider this, and that'll require re-starting the process here. In particular, https://github.com/wasmerio/wasmer/issues/2329 is still outstanding.
