### ISSUE TITLE
RaidGuild Request: indexed.wtf doc edits and additions

### ISSUE THREAD

**Issue by kittyslasher** [near/nearcore#4095]
Hello blessed devs,
@bowenwang1996 @ilblackdragon @nearmax @evgenykuzyakov @mikedotexe @ailisp @SkidanovAlex @mfornet @Kouprin @azban @vgrichina @frol @chefsale @janedegtiareva @matklad @chain-police @olonho @birchmd @khorolets @pmnoxx @utka @abacabadabacaba @david-stolp @willemneal @potatodepaulo @k06a @frankbraun @AnaisUrlichs @mhalambek @ckshei @thisisjoshford @EgorKulikov @eriktrautman @artob @amgando @KaiserKarel @cyberbono3 @jubos @robert-zaremba @Longarithm 

We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically. Having easily accessible information about all these solutions will bring more attention to your project.

Please find the markdown for the docs for your project below.

Kindly review, edit and provide any missing details and information at your taste and discretion as project leaders.

Moving forward we aim to keep indexed.wtf as current and beneficial to developers researching the ecosystem as possible. Please feel free at any time to submit an issue or PR to update the displayed information.

Thank you for your attention to this matter.

Best,
The Indexed Army
We stand for accurate data.

www.RaidGuild.org
@chair28980 @kittyslasher

```markdown
# Near Docs


## Name
Near Protocol

## Description
NEAR Protocol is a decentralized development platform where developers can host server-less applications and smart contracts that easily connect to "open finance" networks and benefit from an ecosystem of "open web" components.

NEAR Protocol is built from the ground with the mission to be the easiest in the world for developers and their end users, while still providing the scalability and security you need to serve those users.

## Consensus Type
Proof of Stake

## Tx Cost


## Average TPS


## Governance/validator Token
$NEAR

## Transactional Token
$NEAR

## Resources
[Website](https://near.org/)
[Github](https://github.com/near)
[Docs](http://docs.near.org/)
[Whitepaper](https://near.org/papers/the-official-near-white-paper/)


## Social Media & Community
[Twitter](https://twitter.com/NEARProtocol?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)
[Telegram](https://t.me/cryptonear)
[Medium](https://medium.com/nearprotocol)
[Facebook](https://www.facebook.com/NEARProtocol/)
[Career Opportunities](https://near.org/careers/)


```

**Comment by bowenwang1996** [comment]
> make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically

NEAR is neither a layer 2 nor a side chain. I don't think this repo is the best place for such request. Please submit the issue to https://github.com/near/docs
