### ISSUE TITLE
RuntimeConfig has wrong storage amount per byte by default

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#4148]
**Describe the bug**
[Runtime Config] default has wrong storage amount per byte by default.
This leads to issues like near sdk simulator and runtime standalone calculating it wrong as well.

**To Reproduce**
See https://github.com/near/nearcore/blob/master/core/primitives/src/runtime/config.rs#L34

**Expected behavior**
It should be 1e19 yN.

CC @willemneal

**Comment by willemneal** [comment]
Will republish after https://github.com/near/nearcore/pull/4143 is merged too.

**Comment by willemneal** [comment]
This also needs to be updated with the new cost: https://nomicon.io/Economics/README.html#general-variables

**Comment by willemneal** [comment]
@evgenykuzyakov Could you look into the PR.  You implemented the storage cost change and I'm a little lost with the cascading changes that result from my change.

**Comment by bowenwang1996** [comment]
What is the status of this issue @willemneal ?

**Comment by willemneal** [comment]
This is stale.
