### ISSUE TITLE
Store abstraction is coupled with rocksdb

### ISSUE THREAD

**Issue by willemneal** [near/nearcore#4153]
Currently the main `Database` trait is

<pre>pub trait Database: Sync + Send {
 fn transaction(&self) -> DBTransaction {
 DBTransaction 

 { ops: Vec::new() } 

 }
 fn get(&self, col: DBCol, key: &<span class="error">[u8]</span>) -> Result<option>
 <vec>
 <u8>
 >, DBError>;
 fn iter<'a>(&'a self, column: DBCol) -> Box
 <dyn iterator<item="(Box<<span class="error">[u8]</span>">
 , Box<<span class="error">[u8]</span>>)> + 'a>;
 fn iter_without_rc_logic<'a>(
 &'a self,
 column: DBCol,
 ) -> Box
 <dyn iterator<item="(Box<<span class="error">[u8]</span>">
 , Box<<span class="error">[u8]</span>>)> + 'a>;
 fn iter_prefix<'a>(
 &'a self,
 col: DBCol,
 key_prefix: &'a <span class="error">[u8]</span>,
 ) -> Box
 <dyn iterator<item="(Box<<span class="error">[u8]</span>">
 , Box<<span class="error">[u8]</span>>)> + 'a>; fn write(&self, batch: DBTransaction) -> Result<(), DBError>; fn as_rocksdb(&self) -> Option<&RocksDB> 

 { None } 

 }
 </dyn>
 </dyn>
 </dyn>
 </u8>
 </vec></option></pre>

And `DBError` is

<pre>pub struct DBError(rocksdb::Error);</pre>

This means that implementers of the trait are required to import rocksdb. For context's like simulation testing this means a large dependency that doesn't even get used. The abstraction and implementation should be separated so that in the future using the leveldb provided in browsers could be possible.

**Comment by chadoh** [comment]
This would also slow down the rate at which I thrash my SSD as it fills to the brim with Rust `target` artifacts when I test various projects. Here's a screenshot of [Grand Perspective](https://apps.apple.com/us/app/grandperspective/id1111570163?mt=12)'s analysis of my hard drive, highlighting the many occurrences of librocksdb:

<img width="752" alt="my_librocksdb_collection" src="https://user-images.githubusercontent.com/221614/112046161-1016a300-8b22-11eb-969c-38cf97d0c499.png">

**Comment by willemneal** [comment]
Not stale.  Storage abstraction should not rely on rocksdb

**Comment by chadoh** [comment]
not stale

**Comment by mina86** [comment]
02821d86b780c946778dc5ec1617c558216bb483 has fixed that.
