### ISSUE TITLE
Performance degradation related to near-rust-allocator-proxy

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#4157]
While doing benchmarking I saw performance degradation of loading genesis from json config. While having `memory_stats` feature enabled. That's due to extra work done in the allocator proxy, most likely atomic reads and write. 

Solution:
- reduce the number of atomic operations used in allocator proxy - most likely by doing atomic operations less often

Related to #4155

Improvements
- 1% improvement on 32 bytes allocations - https://github.com/near/near-memory-tracker/pull/52
- 20% performance improvement - https://github.com/near/near-memory-tracker/pull/53
- https://github.com/near/near-memory-tracker/pull/55

Total time of doing 32 bytes allocation decreased from `38ns` to `25ns`.

Goals
- Measure and document performance effect on `neard` - for example time it takes to load genesis
- Simplify code - a lot of performance optimizations, are a simple result of making code simpler
- Maintainability - after rewrite it will be easier to extend the code, and verify that there are not issues
- Benchmarks -  will make it easier to work with code, and ensure that there is no performance degradations
- tests - Tests, will make it easier to maintain the code
- performance - a side effect of rewriting the code, will be improved performance

**Comment by bowenwang1996** [comment]
> It's possible near-rust-allocator-proxy is responsible for some performance degradations.

Is there actual evidence of this? Also I believe this only affects the cases where we enable `memory_stats`

**Comment by pmnoxx** [comment]
> > It's possible near-rust-allocator-proxy is responsible for some performance degradations.
> 
> Is there actual evidence of this? Also I believe this only affects the cases where we enable `memory_stats`

> > me, we should reduce performance overhead when running with memory_stats feature flag.
Yes, like I said above, it only affects performance when using 'memory_stats` feature.

**Comment by pmnoxx** [comment]
@bowenwang1996 We should refactor our code base to get rid of unnecessary allocations first.
We started doing the work for `near-network`. There were a couple of PRs, but we should do it for the rest of the code base.

@matklad Can you take a look at `near-rust-allocator-proxy` whenever you see any obvious ways to improve performance?

**Comment by matklad** [comment]
I wonder if the original premise of "We saw recently performance issues related to allocations in our code" was invalidated by #4988? Ie, we were running glibc allocator in prod, we swithced to jemalloc since, this should have completely changed the observed behavior.

**Comment by matklad** [comment]
https://github.com/near/near-memory-tracker/issues/26

**Comment by pmnoxx** [comment]
> I wonder if the original premise of "We saw recently performance issues related to allocations in our code" was invalidated by #4988? Ie, we were running glibc allocator in prod, we swithced to jemalloc since, this should have completely changed the observed behavior.

@matklad 
I should have made the description more clearly. I should have written:

"While doing benchmarking I saw performance degradation of loading genesis from json config. While having `memory_stats` feature enabled. That's due to extra work done in the allocator proxy, most likely atomic reads and write. "

**Comment by pmnoxx** [comment]
@matklad I updated the description to what I should have written.

**Comment by pmnoxx** [comment]
@bowenwang1996  @matklad Here is the benchmark, which shows performance degradation 

https://github.com/near/near-memory-tracker/pull/27

**Comment by pmnoxx** [comment]
@matklad @mm-near @bowenwang1996 Here is an issue that tracks progress: https://github.com/near/near-memory-tracker/issues/36

**Comment by pmnoxx** [comment]
I improved performance, by 1% https://github.com/near/near-memory-tracker/pull/52

**Comment by pmnoxx** [comment]
After https://github.com/near/near-memory-tracker/pull/53
The allocation time decreases from 38ns to 12ns.

**Comment by matklad** [comment]
>The allocation time decreases from 38ns to 12ns.

Curious, what's the macro effect here? EG, how fast "load genesis" as a whole becomes?

**Comment by pmnoxx** [comment]
> > The allocation time decreases from 38ns to 12ns.
> 
> Curious, what's the macro effect here? EG, how fast "load genesis" as a whole becomes?

Currently, with all features it takes ` took=32.098465268s` to load config with `performance_stats, memory_stats` features
Without those features it's ` took=31.974870134s`

In `near-memory-tracker` allocator, there is a 1000 bytes threshold, after which we will do `backtrace` 100% of the time.

That's an issue, because now allocating `1024` bytes takes `2000ns` instead of default `40ns`.
After optimizations, while still doing backtrace 100% of the time for memory allocations above 1000 bytes, we are down to `700ns`.

I'm planning to add a setting ,where you can configure whenever or not you want to do backtraces or not. Alternatively, I can adjust the heuristics, to make the impact lower.

It's fine if memory allocations are 2-4x slower, but they shouldn't be 50x slower in certain conditions.
