### ISSUE TITLE
Test contracts nayduck failures

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#4174]
Lots of tests are failing after #4160:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1433
```
Traceback (most recent call last):
  File "tests/contracts/deploy_call_smart_contract.py", line 22, in <module>
    '../runtime/near-test-contracts/res/test_contract_rs.wasm'), 10, hash_)
  File "lib/utils.py", line 177, in load_binary_file
    with open(filepath, "rb") as binaryfile:
FileNotFoundError: [Errno 2] No such file or directory: '../runtime/near-test-contracts/res/test_contract_rs.wasm'
```

**Comment by matklad** [comment]
So what happens here is that some test `.wasm`  contracts are now generated as a part of build process. Rust code naturally can access them, as it transparently kicks the build process. 

Python code, however, needs to explicitly arrange for the build to happen. In #4160 [this line](https://github.com/near/nearcore/pull/4160/files#diff-d28d59459b8ccd11688b677d143f07ce9c252bb9fec4132b63c2da78bfafb711R72) is enough to make the CI green. Obviously, it's not enough to make nayduck happy. Something along those lines should be added to nayducks entry point. 

This is sadly the point where I reach the limits of my knowledge: I don't know where that entry point is, and I don't know how to "launch nayduck" (

A "naive" fix might work though, where we just arrange the relevant build to happen on importing a Python module:


```diff
diff --git a/pytest/lib/utils.py b/pytest/lib/utils.py
index 1797cfd5..00181f4a 100644
--- a/pytest/lib/utils.py
+++ b/pytest/lib/utils.py
@@ -9,6 +9,7 @@ import tempfile
 import json
 import hashlib
 import time
+import subprocess
 
 
 class TxContext:
@@ -318,3 +319,8 @@ def wait_for_blocks_or_timeout(node, num_blocks, timeout, callback=None, check_s
             if callback():
                 break
         time.sleep(check_sec)
+
+def compile_test_contracts():
+    subprocess.check_output(['cargo', 'build', '-p', 'near-test-contracts'])
+
+compile_test_contracts()
```

**Comment by utka** [comment]
NayDuck is fixed.
