### ISSUE TITLE
Optimize genesis loading speed and memory usage

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4190]
After the most recent hard fork, testnet genesis file is 5GB large and requires more than 16GB of memory to load it the first time. This is mostly caused by:
* Representing genesis in json is inefficient and takes more space due to base64 encoding
* In [genesis_state_from_records](https://github.com/near/nearcore/blob/14711926391d3ec1d23116658a295a62e77bc701/neard/src/runtime/mod.rs#L259) we first load all state records into memory and then computing the genesis state based on the records. This means we try to hold at least twice the size of genesis in memory at peak usage, which is fairly suboptimal.

I think in the short term, switching to using binary state dump (genesis_state_from_dump) could be sufficient. More concretely, this means:
* Creating a binary state dump of [the current testnet genesis](https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json)
* Make sure that we can load it successfully and that the memory consumption during this process is reasonable (< 8GB)

**Comment by posvyatokum** [comment]
After this pull request, there is still a matter of loading full genesis in neard init to change the chain id. We can load config from the genesis file and check for chain_id. If it's correct, then we do nothing, else we load full genesis, change chain_id, write genesis back (what we do now).
