### ISSUE TITLE
State viewer doesn't dump the latest protocol version in the new genesis

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#4207]
This caused issues on testnet aurora hardfork where we had to wait several epochs to upgrade and some contract were not working.

**Comment by nikurt** [comment]
Can you please clarify what is State viewer.
Is there a way to reproduce the issue locally?

**Comment by chefsale** [comment]
Uff, not sure how are we going to approach this issue. cc: @bowenwang1996 

But to summarize, state viewer is a tool inside the nearcore repo which we use for taking all of the current state and compress it into a new genesis.json file, we call the process "hardfork" which is semi correct, but we still use it. 

I believe the problem here is that the protocol version during this dump stays the same and that is causing migrations to all run again from scratch. The ideal solution would be to add the "right" protocol version so the migrations which aren't needed aren't run.

First you will need to run some neard node (I believe archival) to get some data and once running, you should be able to stop it and you can run the state viewer to get the new genesis by running:
```
cargo build -p state-viewer
./target/debug/state-viewer --home <near_home> dump_state
```
it is going to create and output.json file which is your new genesis.json.

I think running this on betanet would be the best, as there is least amount of data, but for details on why this is happening and how best to reproduce this exact issue maybe @bowenwang1996 can help.

**Comment by chefsale** [comment]
Also links to how to run an archival node with and without nearup:
https://docs.near.org/docs/develop/node/archival/run-archival-node-with-nearup#docsNav
https://docs.near.org/docs/develop/node/archival/run-archival-node-without-nearup#docsNav

**Comment by bowenwang1996** [comment]
@nikurt state viewer allows one to dump the state of the current network into a new genesis that can be used to start a new network. `protocol_version` is a field in the genesis and the current behavior is to preserve the one from the old genesis, which is suboptimal. We should simply replace it with the latest protocol version of the network
