### ISSUE TITLE
Get rid of serialization annotations on most runtime structures.

### ISSUE THREAD

**Issue by olonho** [near/nearcore#4217]

**Comment by bowenwang1996** [comment]
Could you explain a bit more on what the motivation is here?

**Comment by olonho** [comment]
Idea is that derived serialization attributes pretty much enforce structures from any further modifications, if we need to read old databases. Thus, we must only use this on structures we sure will never ever change, and for all others implement custom versioned deserialization.

**Comment by bowenwang1996** [comment]
@matklad who should we assign this to?

**Comment by matklad** [comment]
Good question! I feel that this might be part of node-X actually? The problem contract runtime team has is that some of the structs we use, like `VMError`, are BorshSerialize, so accidental changes to them break compatability with out-of process data. What would be ideal is having setup similar to our `view` structs which we (aspirationally) use only for RPC, but for `borsh` stuff. We can do this on case-by-case basis (see `FunctionCallErrorSer`), but ideally there should be some specific nearcore-wide module for such things.
