### ISSUE TITLE
Increase Rust JSON-RPC client limit on receiving payload

### ISSUE THREAD

**Issue by frol** [near/nearcore#4241]
**Describe the bug**

Currently, our jsonrpc-client has a limit of 256k on receiving payload, which causes Overflow errors on trying to download contract code, state, or state changes even when a server is fine sending such payloads. We need to configure the limit [here](https://github.com/near/nearcore/blob/1b77673548ebaf884e25169dbafae25ce4713472/chain/jsonrpc/client/src/lib.rs#L43-L46) somehow.

**To Reproduce**

1. Clone https://github.com/FroVolod/near-cli
2. `cargo run -- view contract-code network testnet contract meta.pool.testnet download ./meta.pool.testnet.wasm`

You will get:

```
Failed to fetch query for view contract: RpcError { code: -32700, message: "Parse error", data: Some(String("Failed to retrieve payload: Overflow")) }
```

Here is the code that uses jsonrpc-client: https://github.com/FroVolod/near-cli/blob/5d32f348e727ae52053a2b044cf67f11c1ad8938/src/commands/view/view_contract_code/contract/download_mode/download/mod.rs#L50-L57

**Expected behavior**

It should download the payload just fine, and it does it for smaller payloads (contracts).

**Version (please complete the following information):**
- nearcore: any
- rust version (if local): any
- docker (if using docker): n/a
- mainnet/testnet/betanet/local: any

**Comment by ChaoticTempest** [comment]
@frol What's a good limit we should increase to? I've tested with 50x that of the 256k limit and it gets past the overflow, but I don't know how big our payloads get. I think if we don't care, I can just put max `usize` then

**Comment by frol** [comment]
@ChaoticTempest Let's go with 100MB for now.
