### ISSUE TITLE
Feature request. Indexer warns when it notices protocol or client update in the network

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4275]
Currently when user of the indexer framework miss protocol or neard version upgrade and do not recompile their code, their node is getting abruptly disconnected from the network.

It would be difficult to implement auto-upgrade for indexer, since it requires running migration scripts, and recompiling user-specific code, which it total can take 12+ hours and would be disruptive for the user if it happens automatically under their feet. (This is however debatable, if for instance we can run migration scripts on a cloned database to have zero downtime for indexer)

Instead, indexer node should be notifying users that they noticed a peer with higher protocol version or node version on the network. It can be done by printing warning message every ~10 secs into stdout. Once we publish nearcore-lib to crates.io or sign our releases with PGP indexer should not ignoring node/protocol versions that were not signed or published to crates.io.

**Comment by chefsale** [comment]
Talked to @frol about this, the only issue we have to figure out how to detect that the protocol version change will actually happen. Will talk to @bowenwang1996 .

**Comment by bowenwang1996** [comment]
@chefsale is this still relevant?

**Comment by chefsale** [comment]
I believe we discussed this issue and it doesn't seem like a solution just to spam indexer logs with an WARNING, as most likely it will not be seen there. Maybe a better solution would be looking into automating messages to TG and Discord to let people know if there is a new release happening, as it seems also very hard to detect protocol version changes based on my discussion with @bowenwang1996. 

I believe we should close this issue and create a new one focusing on automating releases messages for indexer? We currently have @janewang which does a great job of summarizing all the release notes and changes and letting people know.
