### ISSUE TITLE
v1.19.0 RPC Server intermittent FetchError

### ISSUE THREAD

**Issue by DenysOf** [near/nearcore#4315]
We use our own RPC server (fully synced neard node) to pull the data from the blockchain (for near-staking website), such as blocks, transactions, etc. Since we upgraded RPC node to the v1.19.0 we noticed intermittent error in our app logs:

`Retrying HTTP request for http://X.X.X.X:3030 because of error: FetchError: request to http://X.X.X.X:3030/ failed, reason: socket hang up`

Switching the RPC endpoint to `https://rpc.mainnet.near.org` rectify the issue.

- nearcore commit/branch: `git branch * 1.19.0`
- rust version (if local): `cargo 1.48.0-nightly (9d1a4863a 2020-10-05) release: 1.48.0`
- mainnet

**Comment by bowenwang1996** [comment]
@frol could you take a look at this?

**Comment by frol** [comment]
@DenysOf I was under impression that nearcore is not compilable by that old nightly Rust compiler. Please, make sure you run 1.19.0 (please, attach status RPC response) and compile with stable Rust 1.51+.

Does it recover after retry?

**Comment by bowenwang1996** [comment]
@DenysOf any update on this?

**Comment by DenysOf** [comment]
> @DenysOf any update on this?

Hi @bowenwang1996, I have enabled the debug logging, but haven't seen that message since, I'm closing the issue as no more presented. Thanks.
