### ISSUE TITLE
Restoring receipts should not cause network to crash

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4321]
Betanet crashed with
```
thread 'main' panicked at 'Receipts to restore must contain an entry for shard 0', runtime/runtime/src/lib.rs:1122:18
```
It appears that we assert `restored_receipt` is nonempty for every network, which is not the case. It might be a good idea to add to `MigrationFlags` whether the network is mainnet.

**Comment by bowenwang1996** [comment]
@EgorKulikov please check whether there is a similar issue for restoring storage usage.

**Comment by EgorKulikov** [comment]
> @EgorKulikov please check whether there is a similar issue for restoring storage usage.

I have no similar checks

**Comment by Longarithm** [comment]
I removed this assertion, because it's already checked in `test_restored_receipts_data` test, so it actually doesn't make sense to check it again in `Runtime`.

**Comment by bowenwang1996** [comment]
> I removed this assertion, because it's already checked in `test_restored_receipts_data` test, so it actually doesn't make sense to check it again in `Runtime`.

That is not necessarily the case. We sometimes have asserts in our code to prevent the node from getting into an inconsistent state such that it cannot recover. For example if the node tries to access a trie node that does not exist, it will simply crash rather than trying to do something else because some fundamental invariant is broken. 

In this case though, that does not apply and yes, we should not panic if there is no receipts to be restored.
