### ISSUE TITLE
Remove nearcore features from `neard` Cargo.toml

### ISSUE THREAD

**Issue by frol** [near/nearcore#4325]
With the decoupling of `neard` and `nearcore` we did a copy of features in the Cargo.toml file. Instead, we should just ~make the features in `neard/Cargo.toml` proxy~ remove them from `neard/Cargo.toml` file. UPD: see further conversation for details.

~after #4292 they look like:~

~`nightly_protocol = ["near-primitives/nightly_protocol", "near-jsonrpc/nightly_protocol"]`~

~which may diverge if we forget to maintain the list in both `neard/Cargo.toml` and `nearcore/Cargo.toml`~

**Comment by matklad** [comment]
Alternatively, we can remove features from `neard/Cargo.toml` altogether, and instead use the following CLI for activating them:

```
cargo build -p neard --feature nearcore/nightly_protocol,nearcore/nightly_protocol_features
```

**Comment by frol** [comment]
@matklad looks good to me, so let's do it! I will update the issue, and I still want @chefsale to work on it since he will be able to double-check all our CI and release scripts for the use of `--feature` flags.
