### ISSUE TITLE
Add interface for "data driven" testing of runtime

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4335]
Imagine if you could create a `scenario.json` file, which contains serialized representation of series of blocks (or just actions) and feed it into runtime. In this world, you'd have several new super-powers for improving reliability:

* you could create a giant `scenario.json`, which encapsulates the whole history of the network, and use it to replay the history during major upgrades, to check that the behavior stays the same. 
* you could teach a fuzzer to generate syntactically valid scenarios, to check that the runtime doesn't crash even if deliberately attacked
* if you notice a performance regresson, you can create a `scenario.json` file as a reproduction, send it to another team, and allow them to quickly reproduce & profile the issue. 
* you can write many integration tests in a data-driven fashion, specifying the input as a scenario, rather than as a rust code which calls specific methods

Now, I don't think we necessary need to push this down to JSON in particular, but I think it does make sense to build the infra for data-driven record-replay and fuzzing. So, we should add some kind of 

```rust
#[derive(Serialize)]
struct Scenario {}
```

which is a plain old data, and which can describe a series of runtime actions. After we have this, I think the best next step would be to implement an Arbitrary trait for `Scenario`, and use that to fuzz our runtime. Take a look at how [wasm-smith](https://github.com/bytecodealliance/wasm-tools/tree/f632261627a0ea758762e431d8be32740111e33c/crates/wasm-smith) uses this approach. After fuzzing, the next good target would be the ability to capture & replay historical data from the mainnet, to give us more confidence during upgrades.

Once we try this out and agree that it works, it might make sense to try to express our integration tests in such framework.

**Comment by bowenwang1996** [comment]
@posvyatokum is this already done?

**Comment by posvyatokum** [comment]
I think we can close this issue and create separate tasks for future improvements.
