### ISSUE TITLE
CI doesn't check all feature combinations any more

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#4336]
we have `cargo check --workspace --all-features --all-targets` on ci, however as a consequence of removing workspace dependencies recently, it doesn't check member package features, and since there's no workspace features, this now equivalent to `cargo check --workspace --all-targets`. So we should add check with individual packages for possible feature combinations, such as `cargo check -p neard`,` cargo check -p neard --features sandbox` etc. (The sandbox one I've added in a recent PR, and from there I discovered sandbox feature was not checked by CI)

**Comment by bowenwang1996** [comment]
@chefsale looks like we only need to add `cargo check -p neard --features sandbox` since `cargo check -p neard` is added in #4368

**Comment by chefsale** [comment]
It seems like sandbox was added in: https://github.com/near/nearcore/commit/1fe28a25f4eda7e438735b8b4450947a2c697209#diff-a3991ebf1475eb82acab13946ffc1eca02b43917f6d5bec3898f45c8b0b9bd53. Closing this issue, as it seems to be resolved.
