### ISSUE TITLE
Slow response time of calling contract methods via JSON RPC API

### ISSUE THREAD

**Issue by think-in-universe** [near/nearcore#4342]
**Describe the bug**

NEAR is designed to provide Web 2 experience for DApp users. To achieve this objective, the response time for operations (read state, make contract call, etc.) should be extremely fast. 

When building a DApp that requires high performance and quick response time, we find that average response time of calling contract methods via `near-api-js` is around 3~10s if we use the TestNet RPC Node (from calling a method to receiving its result). 

The worst case is more than 10s if we're using the TestNet RPC Node. The average is around 5s if we move to a dedicated RPC Node only used by the DApp. 

**To Reproduce**
To reproduce the issue, we use BerryClub as an example. 

1. `git clone https://github.com/evgenykuzyakov/berryclub` and then `cd berryclub`
2. add profiling code around the `draw()` method: https://github.com/evgenykuzyakov/berryclub/blob/f5a288f81e669ff6073500aa815cec09fba0175e/frontend/src/App.js#L418-L423

define `profile()` function:

e.g. 
```js
    let start = Date.now();
    let counter = 0;
    function profile() {
      let end = Date.now();
      if (counter > 0) {
        console.log(`#${counter}: draw() costs ${end - start} ms`);
      }
      start = end;
      counter += 1;
    }
```

call `profile()` function

```js
      profile();
      await this._contract.draw(
        {
          pixels,
        },
        new BN("75000000000000")
      );
      profile();
```

3. `cd frontend` and then `yarn && yarn start`, open the frontend in http://localhost:3000
4. login with NEAR account and draw on the board, look at the log in Chrome dev console

The response time could be as slow as 8 ~ 10s sometimes, and it's 3 ~ 10s in most cases.

You can also write a script to call the contract method locally or via NEAR CLI if needed. 

**Expected behavior**
The response time of calling a method such as `draw()` in BerryClub should take around 2 ~ 3s on average. 

**Screenshots**
The response time on testnet today is much faster than what we have tested in last two weeks. 
Now it's around 3~6 seconds, and 4.5s on average.

![image](https://user-images.githubusercontent.com/46699230/120148804-5c194e80-c21b-11eb-9fc1-0b980e89be29.png)

**Version (please complete the following information):**
- testnet

**Additional context**
With more DApp deployed into testnet and mainnet, we do care more about the performance and user experience of the DApps

**Comment by think-in-universe** [comment]
@frol Hey Frol, could you please have a look? also discussed with Amos and Illia, and we thought this might be a performance issue. 

Ideally the average response time of contract method call should be around 2~3, but the performance could be impacted by many factors including the number of concurrent requests, and the RPC Node server, etc. 

If there're any best practice about tuning the RPC node to be performant, it will also be helpful. 

We also had some discussion in [Discord](https://discord.com/channels/490367152054992913/801214719146590238/845578995922763787) previously.

**Comment by frol** [comment]
@think-in-universe calling a contract method creates a transaction with a function-call action, and RPC waits for the transaction to be completely executed on the chain (including all the cross-contract calls and refunds). `draw` method takes 3 blocks to execute:

1. transaction pre-charges some gas and gets included in a block/chunk and converted to a receipt
2. the receipt gets executed
3. the remaining gas gets refunded

See "Transaction Execution Plan" on Explorer: https://explorer.near.org/transactions/83718ciUcuBLtmYJsfYNnRPMdd6vHHLtrJ6bXYrnbft3

Also, there is some delay before a transaction gets routed to the validator in the first place, and execution results propagate back to the RPC node.

@think-in-universe Your Discord link does not seem to be right or at least I don't see how it is related.

@bowenwang1996 Do you think it is fair to expect sub-3-second execution on testnet for 3-block-long transaction?

**Comment by think-in-universe** [comment]
@frol  thanks Frol. 

I think it makes sense to have 3s execution time for `draw()` method as you have explained, as long as that is the fundamental limit by the blockchain. 

The question would be whether it's possible to optimize the RPC node's execution time except the on-chain processing, as the response time seems to vary among nodes, and it would be good to have some tools help to deploy standalone RPC nodes with high performance to serve the use cases that expect fast response.

The Discord channel's discussion should be relevant. See my screenshot below and the comments below this one. 

![image](https://user-images.githubusercontent.com/46699230/120208543-2ba7d380-c260-11eb-8c0c-8b3c96abaeb6.png)

**Comment by bowenwang1996** [comment]
@frol the broadcast_tx_commit call does not actually wait for the refund to processed.
@think-in-universe Do they need low latency or high throughput? You can submit a lot of transactions in parallel using `broadcast_tx_async` and wait for them to finish by querying the transaction statusues.

**Comment by think-in-universe** [comment]
@bowenwang1996  low latency is the key objective here, i.e. reduce the latency for a single function call.

**Comment by bowenwang1996** [comment]
> @bowenwang1996 low latency is the key objective here, i.e. reduce the latency for a single function call.

Then likely there is not much else to do besides running your own rpc nodes. There are some fundamental limitations that are hard to change. A function call takes at least two blocks to complete.

**Comment by think-in-universe** [comment]
@bowenwang1996 we tested self-owned RPC node and the response time is around 3~5 seconds, which is more stable than our shared RPC node (3~10s previously). 

The purpose here is to optimize the RPC call to reduce the latency to 2~3 seconds (decreasing by 1~2 seconds) if possible. 

Amos's comment here is 3 seconds is acceptable but 5 seconds is too long. please let me know how you guys think.

**Comment by bowenwang1996** [comment]
@frol right now we poll the result every 500ms, which could contribute to some extra latency. Do you think it makes sense to lower that number?

**Comment by think-in-universe** [comment]
A relevant issue is the state change latency based on some feedback from developers. 

Take BerryClub as an example, after calling `draw()`, the canvas data is not update-to-date until 1~2 seconds later. 

Will run more testing and sharing the latency data here.

**Comment by bowenwang1996** [comment]
> Take BerryClub as an example, after calling draw(), the canvas data is not update-to-date until 1~2 seconds later.

Well it takes time to process the transaction. If we don't change block production speed, there is not much we can do at this point.

**Comment by think-in-universe** [comment]
@bowenwang1996 it's a bit different from what's talking about in the current issue. 

I mean, for example, after the transactions are already processed on chain for function calls like `draw()` on RPC Node A, the latest contract state is not synchronized on RPC Node B until seconds later.

**Comment by bowenwang1996** [comment]
@think-in-universe is it because they are querying the final state? It takes a couple seconds to finalize a block.

**Comment by bowenwang1996** [comment]
@think-in-universe @frol are there any action items here? if not let's close the issue

**Comment by frol** [comment]
I feel that the execution time is fair and expected for a transaction with cross-contract calls.

@think-in-universe If you think we can improve something specific, feel free to re-open this issue.
