### ISSUE TITLE
State of contract <contract name> is too large to be viewed

### ISSUE THREAD

**Issue by think-in-universe** [near/nearcore#4343]
**Describe the bug**
As merged in the PR https://github.com/near/nearcore/pull/4167 , now contract with large state cannot be viewed with RPC. That makes sense to improve performance and avoid attack. 

Here we have a contract whose state's size is almost constant and is queryable until several days ago. We want to understand what has happened that caused the issue here. Is there any way to bypass the limit and view the latest state, so we can debug how the state was changed?

**To Reproduce**

Query the account state with prefix `p`.

```bash
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
  params:='{
    "request_type": "view_state",
    "finality": "final",
    "account_id": "feiyu-dev.testnet",
    "prefix_base64": "cAo="
  }'

HTTP/1.1 200 OK
Alt-Svc: clear
Content-Length: 153
Via: 1.1 google
access-control-allow-origin: 
content-type: application/json
date: Mon, 31 May 2021 14:45:18 GMT

{
    "error": {
        "code": -32000,
        "data": "State of contract feiyu-dev.testnet is too large to be viewed",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

**Expected behavior**
We need some approach to debug why the state is too large to be viewed, since the state's size should be almost constant. 

**Version (please complete the following information):**
- testnet

**Additional context**
This issue blocks one feature of a DApp. We want to understand why the error happens.

**Comment by think-in-universe** [comment]
@bowenwang1996   Hey Bowen, we're seeking one way to debug the error and understand why it happens. The contract itself functions well, but somehow the view state function doesn't work from last Friday.

**Comment by bowenwang1996** [comment]
Viewing contracts with state larger than 50kb is prohibited by default. See https://github.com/near/nearcore/pull/4167. Created https://github.com/near/docs/issues/732

**Comment by think-in-universe** [comment]
@bowenwang1996 we know there's a 50 KB limit, but don't know how why the limit was exceeded and want to read the latest state to understand what goes wrong. that's why we raise the issue to find a way to debug the issue. 

now the developer is using a dedicated RPC node, how could we configure that node to bypass the limit?

**Comment by think-in-universe** [comment]
With the help of @frol we figured out the cause, the contract state's size exceeds 50KB limit, though the state size for a specific prefix doesn't change. The size limit applies to the total state size, not the size under a specific prefix, which confused us previously. 

Now the workaround is to set up a archival node which we can configure the `config.json` to set state size limit to null.
