### ISSUE TITLE
Change log to tracing

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4346]
We currently use both `log` and `tracing` for logging in nearcore. Given that `tracing` is a superset of `log` in terms of functionalities, we should switch all the logging crates to `tracing`.

**Comment by bowenwang1996** [comment]
@mzhangmzz this is done right?

**Comment by mzhangmzz** [comment]
ah no, sorry I forgot about this

**Comment by mzhangmzz** [comment]
I'll release myself from this PR
