### ISSUE TITLE
Add current_protocol_version and supported_protocol_version to Telemetry

### ISSUE THREAD

**Issue by frol** [near/nearcore#4355]
Currently, Telemetry reports only agent name and version which we use to estimate the protocol versions supported in the network, and when it is going to vote for the protocol upgrade. It would be much better to have explicit information about the supported protocol versions in the telemetry, so Explorer can provide useful metrics: [https://github.com/near/near-explorer/issues/644](https://github.com/near/near-explorer/issues/644)

**It might be non-trivial to get the information about the current and the supported version of the protocol version. Let me know if you need any help**

Here is the entry-point: [https://github.com/near/nearcore/blob/07b4fd45f90570d9c4f306f724cf84499cc519c7/chain/client/src/info.rs#L165-L197](https://github.com/near/nearcore/blob/07b4fd45f90570d9c4f306f724cf84499cc519c7/chain/client/src/info.rs#L165-L197)

Tips: run some minimal HTTP server locally (well, even `netcat -l -p 8080` will do) and [run nearcore node in localnet](https://docs.near.org/docs/develop/node/running-a-node), and configure `config.json` so `telemetry` looks like:

<pre> "telemetry": 

 { "endpoints": [ "http://127.0.0.1:8080" ] } 

,</pre>

**Comment by andrei-near** [comment]
done in https://github.com/near/nearcore/pull/11444.
