### ISSUE TITLE
Process `VMError::CacheError` more safely

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4375]
Ideologically, when there is some trouble loading the compiled module, `precompile_contract` and `action_function_call` should not result in `panic`. This is because compilation error are normal on the blockchain side when user submitted the uncompilable contract, thus it should be treated as a specific result, not an error.

OTOH, currently `FunctionCall` execution may result in `VMError::CacheError` which may be transferred to `StorageError::StorageInconsistentState` which lead to panic in `apply_transactions_with_optional_storage_proof`.

cc @bowenwang1996 @olonho

**Comment by bowenwang1996** [comment]
@matklad @olonho any update on this?

**Comment by matklad** [comment]
Thanks for tagging me bowenwang1996, didn't notice this issue before. I've audited usages of the VMError::CacheError and it *seems* to me that they are correct. That is, we create CacheError only when the contract cache rerutned an IO Error or some bogus data. If an actual wasm-is-invalid compilation error happens, than we return a different error. 

That is, we correctly fatal-error if the cache itself is not good, but avoid fatal-erroring if the contract just have some invalid wasm in it. But of course I might be wrong. @Longarithm could you give a specific example where you think things go wrong. That said, 


```rust
// TODO: remove serialization derives, once fix compilation caching.
#[derive(Debug, Clone, PartialEq, Eq, BorshDeserialize, BorshSerialize, Serialize, Deserialize)]
pub enum VMError {
    FunctionCallError(FunctionCallError),
    /// Serialized external error from External trait implementation.
    ExternalError(Vec<u8>),
    /// An error that is caused by an operation on an inconsistent state.
    /// E.g. an integer overflow by using a value from the given context.
    InconsistentStateError(InconsistentStateError),
    /// Error caused by caching.
    CacheError(CacheError),
}
```

is clearly problematic. This is exactly 

```rust
enum Error {
  Local(LocalError),
  Fatal(FatalError),
}
```

from http://sled.rs/errors.html, so this could use a refactor.
