### ISSUE TITLE
Recompute gas costs for function call base and data creation

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4401]
Function call base cost should be dramatically reduced after #4344 is merged. Also we did not correctly estimate the cost for data receipt creation (right now it costs 9.4Tgas for every promise [https://github.com/near/NEPs/issues/120#issuecomment-859162821](https://github.com/near/NEPs/issues/120#issuecomment-859162821)). We should recompute those gas costs together and make one protocol upgrade to change them.

**Comment by bowenwang1996** [comment]
@Longarithm please sync with @olonho on how to recompute the costs now that #4311 is merged

**Comment by Longarithm** [comment]
Data receipt costs were reduced in protocol feature `LowerDataReceiptAndEcrecoverBaseCost` (protocol version 48), function call costs were reduced in `DecreaseFunctionCallBaseCost` (66) by Contract Runtime team. Good example of how much more work was actually required...
