### ISSUE TITLE
Consider disabling lto in Cargo.toml

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4403]
Apparently, this resurrects https://github.com/near/near-ops/issues/169

We currently set `lto = true`, `codegen-units=1` in Cargo.toml:

https://github.com/near/nearcore/blob/cb229d06595ebf01bf9e39d43f11a7478c92664e/Cargo.toml#L57-L58

This **massively** increases compile times (and compile-time memory usage) in release mode. This in turn hurts productivity for cases where you work on some benchmark and want to recompile the code repeatedly. 

The work-around is to 

```bash
export CARGO_PROFILE_RELEASE_LTO=false
```

locally.

The reason why we set `lto=true` is that it does improve performance of release. 

I think the best practice in this area is to optimize the default configuration for developer convenience, and making the release process opt into additional optimizations. At the same time, it's important that a developer can easily reproduce the exact configuration we use for release. So I suggest:

* _First_, to move the script that prepares release binaries into this repo. It doesn't have to be the full release & deploy pipeline, but the result should be that a developer  can run `./.buildkite/build-release-binaries.sh` and get the bins compiled as for release. as a side benefit, a developer can look into `build-release-binaries.sh` and understand what we are we actually releasing (I, for example, don't know what constitutes a `nearcore` release).
* _Second_, we modify this script to explicitely enable LTO, remove lto and codegen units config from Cargo.toml. 

Checklist 
---------
- [x] Fix our existing makefile: https://github.com/near/nearcore/issues/4475
- [x] Add `export CARGO_PROFILE_RELEASE_LTO=fat`, `export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1` to the Makefiles
- [ ] Remove corresponding entires [from cargo-toml](https://github.com/near/nearcore/blob/ff01c544ce2675fadbf0284af52b356a383b27a8/Cargo.toml#L57-L58).
- [x] Verify that release is actually build with LTO,
- [x] Verify that removing LTO actually speeds up local `cargo build --release -p neard`.
- [x] Verify that the `Makefile` is the only place which produces release builds. Perhaps there are some nayduck load tests or something which also require a true release binary?

**Comment by frol** [comment]
My concern is that I would prefer to have the same production build by default when I do just `cargo build --package neard --release`. I configured my local env to speed compilation up on my side, but I don't think it is sane to break defaults for release builds in order to optimize development use-case.

Still, I am fine with the proposed solution.

**Comment by mina86** [comment]
FYI, I’ve looked into Cargo custom named profiles and while they seem
perfect fit for this issue, but it would `cargo +nightly build` even
if named profile is not used.  For the time being (if we want to go
with disabling lto by default) we’ll need to stick to a build script
with environment variables:

    CARGO_PROFILE_RELEASE_LTO=fat \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 \
        cargo build --release

**Comment by mina86** [comment]
Also, the ‘script’ for building the release files is already present
in the repository. Specifically it’s the `Makefile` with the following
rule:

```
release:
	cargo $(RUST_OPTIONS) build -p neard --release
	cargo $(RUST_OPTIONS) build -p near-vm-runner-standalone --release
	cargo $(RUST_OPTIONS) build -p state-viewer --release
	cargo $(RUST_OPTIONS) build -p store-validator --release
```

The file defines other rules as well such as `nightly-release`,
`perf-release` etc.

**Comment by bowenwang1996** [comment]
What are the action items here @frol @matklad ?

**Comment by matklad** [comment]
I guess, first item is to reach a decision whether we want this or not. This should be easy to revert change, so let's just do it, and revert if it causes problems. 

Steps:

* Fix our existing makefile: https://github.com/near/nearcore/issues/4475
* Add `export CARGO_PROFILE_RELEASE_LTO=false`, `export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1` to the Makefiles
* Remove corresponding entires [from cargo-toml](https://github.com/near/nearcore/blob/ff01c544ce2675fadbf0284af52b356a383b27a8/Cargo.toml#L57-L58).
* Verify that release is actually build with LTO, and that removing LTO actually speeds up local `cargo build --release -p neard`.

**Comment by mina86** [comment]
If there is an agreement that we want to go forward with it, I think I can take a stab at this Issue. Looking into it I’ve essentially done most of the things you’ve listed already. The only thing I envision to potentially be troublesome is confirming that no other place needs to have LTO enabled.

**Comment by bowenwang1996** [comment]
@matklad then we also need to update documentation on how to run a node. Many validators build the binary by `cargo build -p neard --release`.

**Comment by mina86** [comment]
OK, I’m gonna just go ahead and start with this. @bowenwang1996, could you point to where the documentation is located?

**Comment by bowenwang1996** [comment]
@mina86 I think it is https://github.com/near/docs/blob/master/docs/develop/node/validator/compile-and-run-a-node.md. cc @janewang

**Comment by mina86** [comment]
> Verify that release is actually build with LTO,

That’s all configured in near-ops as far as I understand. It all goes through buildkite pipelines which eventually reach the Makefile.

> Verify that the Makefile is the only place which produces release builds.

I’ll double check but NayDuck shouldn’t be affected. Load tests are done against mocknet and don’t build the binary.

Anyone has any idea where else we might be building releases?
