### ISSUE TITLE
Document the issue labeling system we use

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4409]
We have a lot of issue labels in this repository, but we don't have docs explaining which labels are used when. For example, it's unclear to me what https://github.com/near/nearcore/labels/misterwhite is for. 

It would be useful have a map of labels in the docs in this repo.

We might also want to cleanup the labels we use as well, while we are at it. With 50+ labels, it's hard to know what the label is about at a glance. The trick that may rust project use is prefixing the label with category describing the label. So, `T-nodeX` is for node experience **team**, `T-contract-runtime` is for contract runtime **team**, `A-cryptograhpy` is about crypro **area** of code, and `S-blocked` is about **status** of the PR. 

Backstory: I want to create an issue relevant to contract runtime, and I want to label it as such. There's no existing label I can use. If I create a new label, I want to be able to explain its meaning to others, and let folks know that they can apply it to the issues they create.

**Comment by bowenwang1996** [comment]
Thanks for the suggestion Alex. I'll take a stab at this.

**Comment by bowenwang1996** [comment]
@matklad I overhauled the labels. Could you take a look?

**Comment by matklad** [comment]
Looks soo much better now, thanks for investing time into this @bowenwang1996!

I suggest, before closing this issue, to add a paragraph about issue labeling to CONTRIBUTING.md. Here's the relevant section from rust-analyzer docs: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/dev#issue-labels

I think it's important to mention:

* What's our overall strategy for labeling: is it best-effort (its ok to have untagged issues), or is it strict (each untagged issue should be triage and have some sort of tag (as with rust-analyzer's actionable/unactionable labels))
* What's the system we use for labels (L- prefixes). It's sort-of self-evident, but still nice to document. 

Additionally, this create a place in the docs where we document labels, so if, at some point, we'd want to document a specific label or process, it'll be low-friciton to add additional docs. "Where should I put the docs for X" is a hard problem, sometimes it's uselful to solve it up-front, even if the actual docs are thin, just to encourage everyone to expand the existing docs later.
