### ISSUE TITLE
Experiment with wasm-global based gas metering

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4410]
One of the things contract runtime dose is measuring how many wasm instructions a given contract executed, and stopping the contract early if it exceeds the budget. The current implementation for this logic lives here: 

https://github.com/near/nearcore/blob/8ebff13a53db01a121b5b729c582a5450bbabb98/runtime/near-vm-runner/src/prepare.rs#L60-L66

The way it works is by using `pwasm` to inject calls to the `gas(u32)` host function at every basic block entry. 

Calling a host function is a relatively heavy operation, so this style of gas metering slows down execution a lot (>order-of-magnitude). See the rough benchmarks here:

https://gov.near.org/t/on-running-some-wasm-contracts-with-llvm-specifically-for-evm/2869/5?u=matklad

There is alternative, faster way to account for gas, which bypasses host functions. The idea is to add a gas allowance mutable global to the wasm module after validation, and instrument basic blocks to immediately deduct allowance. This is how wasmer metering middleware works:

https://github.com/wasmerio/wasmer/blob/6773109fe0cf2fea78376939e084c097d37a9629/lib/middlewares/src/metering.rs

This approach is safe -- because the module is validated before instrumentation, it can not access the global directly. Wasm doesn't have instructions for indirect access global. The fact that wasm globals & locals are managed is a part of wasm security model, so this is unlikely to change and can be relied on (see gov.near.org discusion for additional links). 

We should see if we can use this approach to significantly speed up our metering. The rough plan:

* double check that an address of global in wasm can't be escaped
* implement wasmer-style instrumentation as a function transforming wasm to wasm. Note that we don't want to use wasmer middleware directly, to not depend on a specific engine. Not sure what's the right tool here -- I suggest looking into the bytecodealliance wasm-tools ecosystem and also looking for existing alternative implementations. 
* integrate this style of gas metering with our host function mechanism -- host functions also use gas, so we should deduct from wasm global upon returning from a host function. 
* using various sepecific and randomly generated contracts, verify that both style of instrumentations yield exactly same gas costs.

EDIT: also we should take a closer look at the approach from https://github.com/near/nearcore/issues/1057

**Comment by nearmax** [comment]
> implement wasmer-style instrumentation as a function transforming wasm to wasm. Note that we don't want to use wasmer middleware directly, to not depend on a specific engine. Not sure what's the right tool here -- I suggest looking into the bytecodealliance wasm-tools ecosystem and also looking for existing alternative implementations.

We can hack pwasm-utils and replace injection of the host function call with injection of global variable decrement.

**Comment by matklad** [comment]
>We can hack pwasm-utils and replace injection of the host function call with injection of global variable decrement.

Yeah, impl wise, I think "consider what's the best impl strategy" is an important point. My understanding is that pwasm actually predates bytecodealliance wasm ecosystem, and building on top of pwasm could be backwards looking. This needs more research for sure!

**Comment by willemneal** [comment]
If we are planning for the long term I think that [`walrus`](https://github.com/rustwasm/walrus) is a good bet for implementing gas injection.

**Comment by syrusakbary** [comment]
> implement wasmer-style instrumentation as a function transforming wasm to wasm. Note that we don't want to use wasmer middleware directly, to not depend on a specific engine.

Our current middleware system is designed to generate wasm that could also be used by any other runtime (or even in the browser, similarly to pwasm-utils). Perhaps we can work to make it Wasmer-abstract (which it should be doable more or less easily, since it's main dependency is only wasmparser).

At the end I think it might be a question of if you want to build the middleware yourselves or use someone else's :)

The nice thing of using Wasmer is that it allows for a streaming-fashion consumer (wasm -> assembly) rather than wasm->other wasm->assembly

**Comment by matklad** [comment]
Thanks for chiming it, @syrusakbary!

Yeah, long term, I think it'll be beneficial to split wasmer middleware ecosystem into vendor-agnostic `wasm->wasm` functions, and wasmer specific hooks to plug those functions into wasmer engine. The hard question is what type is `wasm` exactly? `Vec<u8>` is maximally interoperable, but inconvenient and requires re-parsing. Something like `walrus::Module` is convenient, but much more opinionated. I expect that a lot of design iteration is needed to figure out the best type. 

Given that the amount of code in question is not that large, that today middlewares depend on wasmer crates, and that we still use wasmer 0.17, I think it makes sense for us to start with just re-implementing this, to get the thing out of the door, and then work with the ecosystem to ensure code-reuse.

**Comment by ailisp** [comment]
> integrate this style of gas metering with our host function mechanism -- host functions also use gas, so we should deduct from wasm global upon returning from a host function.

@nearmax This is the problem I mentioned in our talk. I did further investigating and this seems a run-time thing that should be handled with data structures provided by wasmer/wasmtime. bytecodealliance tools/pwasm are used for handling compile-time thing only, like parsing and inject wasm inst, but this require access a run-time vm instance such as wasmer.Memory. We can make a wasm runtime agnostic abstraction and handle it differently in each wasm vm we support.

Alternatively, we can calc host function cost still on host side and wasm cost in wasm. Then we don't need deduct wasm global from host side.

**Comment by matklad** [comment]
> I prefer plan B,

:+1: 

> but this require access a run-time vm instance such as wasmer.instance:

Yes, we'll need to change the gas  counter when we return from a host function, but that's still runtime-independent, as long as we use the same variable name on the wasm side. I think this basically means that `imports.rs` needs to be changed to do gas extra deducing.

**Comment by nearmax** [comment]
CC @joshuajbouw

**Comment by nearmax** [comment]
Closed in favor of https://github.com/near/nearcore/issues/4911
