### ISSUE TITLE
Revisit Clippy whitelisting

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#442]
We should start enabling <span class="error">[clippy]</span>([https://github.com/rust-lang/rust-clippy](https://github.com/rust-lang/rust-clippy)) gradually. To do that, we should first figure out which rules trigger warnings and document them. The purpose of this issue is to get a list of clippy rules that we do not follow now so that we can fix them in the future.

**Comment by frol** [comment]
I assigned L1 implying that initial items should not be huge and Clippy + Rust compiler should guide us through, but if a bigger refactoring is necessary, we should decouple those into separate dedicated issues.

**Comment by bowenwang1996** [comment]
@matklad @nagisa curious what your thoughts are on this topic

**Comment by pmnoxx** [comment]
I'm a big favor of `clippy`. I detected many potential issues ahead of time. 
It also has many useful suggestions on how to write a cleaner, more readable code.I think we should enable it by default.

**Comment by akhi3030** [comment]
Closing in favour of https://github.com/near/nearcore/issues/8145
