### ISSUE TITLE
Node cannot download any blocks after restart

### ISSUE THREAD

**Issue by danielimkk** [near/nearcore#4422]
**Describe the bug**
After a restart of the node, no more blocks are being downloaded. So it is stuck at block 41175921

**To Reproduce**
Start a node, using a snapshot. And at some moment of it running, restart it.

**Expected behavior**
I'd expect a node to continue synchronization after a restart

**Screenshots**
![image](https://user-images.githubusercontent.com/45372041/123588005-efd53f00-d808-11eb-857a-de2c504448e1.png)

**Version (please complete the following information):**
- nearcore commit/branch 1.19.1
- rust version (if local) rustc 1.49.0-nightly
- mainnet

**Additional context**
I have built the neard binary from sources. This issue has happened the second time, last time I had to remove all current database and start the node using a snapshot provided in documentation. Do you have any ideas on how to prevent this issue happening and what could have caused it? Thank you!

A bit more information about setup:
Process manager: supervisor
Binary: neard, built from sources
Version of neard: 1.19.1

**Comment by bowenwang1996** [comment]
Did you ever change your config.json?

**Comment by danielimkk** [comment]
> Did you ever change your config.json?

Nope, it was not changed before or after the restart and update
Here is the config file contents:

```
{
    "genesis_file": "genesis.json",
    "genesis_records_file": null,
    "validator_key_file": "validator_key.json",
    "node_key_file": "node_key.json",
    "rpc": {
        "addr": "0.0.0.0:3030",
        "cors_allowed_origins": [
            "*"
        ],
        "polling_config": {
            "polling_interval": {
                "secs": 0,
                "nanos": 500000000
            },
            "polling_timeout": {
                "secs": 10,
                "nanos": 0
            }
        },
        "limits_config": {
            "json_payload_max_size": 10485760
        }
    },
    "telemetry": {
        "endpoints": [
            "https://explorer.mainnet.near.org/api/nodes"
        ]
    },
    "network": {
        "addr": "0.0.0.0:24567",
        "external_address": "",
        "boot_nodes": "ed25519:86EtEy7epneKyrcJwSWP7zsisTkfDRH5CFVszt4qiQYw@35.195.32.249:24567,ed25519:BFB78VTDBBfCY4jCP99zWxhXUcFAZqR22oSx2KEr8UM1@35.229.222.235:24567,ed25519:Cw1YyiX9cybvz3yZcbYdG7oDV6D7Eihdfc8eM1e1KKoh@35.195.27.104:24567,ed25519:33g3PZRdDvzdRpRpFRZLyscJdbMxUA3j3Rf2ktSYwwF8@34.94.132.112:24567,ed25519:CDQFcD9bHUWdc31rDfRi4ZrJczxg8derCzybcac142tK@35.196.209.192:24567",
        "max_num_peers": 40,
        "minimum_outbound_peers": 5,
        "ideal_connections_lo": 30,
        "ideal_connections_hi": 35,
        "peer_recent_time_window": {
            "secs": 600,
            "nanos": 0
        },
        "safe_set_size": 20,
        "handshake_timeout": {
            "secs": 20,
            "nanos": 0
        },
        "reconnect_delay": {
            "secs": 60,
            "nanos": 0
        },
        "skip_sync_wait": false,
        "ban_window": {
            "secs": 10800,
            "nanos": 0
        },
        "blacklist": [],
        "ttl_account_id_router": {
            "secs": 3600,
            "nanos": 0
        },
        "peer_stats_period": {
            "secs": 5,
            "nanos": 0
        }
    },
    "consensus": {
        "min_num_peers": 3,
        "block_production_tracking_delay": {
            "secs": 0,
            "nanos": 100000000
        },
        "min_block_production_delay": {
            "secs": 1,
            "nanos": 100000000
        },
        "max_block_production_delay": {
            "secs": 2,
            "nanos": 500000000
        },
        "max_block_wait_delay": {
            "secs": 6,
            "nanos": 0
        },
        "reduce_wait_for_missing_block": {
            "secs": 0,
            "nanos": 100000000
        },
        "produce_empty_blocks": true,
        "block_fetch_horizon": 50,
        "state_fetch_horizon": 5,
        "block_header_fetch_horizon": 50,
        "catchup_step_period": {
            "secs": 0,
            "nanos": 100000000
        },
        "chunk_request_retry_period": {
            "secs": 0,
            "nanos": 400000000
        },
        "header_sync_initial_timeout": {
            "secs": 10,
            "nanos": 0
        },
        "header_sync_progress_timeout": {
            "secs": 2,
            "nanos": 0
        },
        "header_sync_stall_ban_timeout": {
            "secs": 120,
            "nanos": 0
        },
        "header_sync_expected_height_per_second": 10,
        "sync_check_period": {
            "secs": 10,
            "nanos": 0
        },
        "sync_step_period": {
            "secs": 0,
            "nanos": 10000000
        },
        "doomslug_step_period": {
            "secs": 0,
            "nanos": 100000000
        }
    },
    "tracked_accounts": [],
    "tracked_shards": [0],
    "archive": false,
    "gc_blocks_limit": 2,
    "view_client_threads": 4
}
```

**Comment by bowenwang1996** [comment]
@danielimkk that is weird. Could you enable verbose logging and see if there is something like "Error on receival of block"

**Comment by janewang** [comment]
@danielimkk Are you able to print the verbose logging for this? Thanks

**Comment by frol** [comment]
@bowenwang1996 @janewang I also observed this behavior, and it is not rare to arrive to this situation. I feel it might be related to #3021. Today I observed this behavior again running indexer-for-explorer (it has nearcore 1.20.0 embedded into it).

I believe the reproduction is that I start a node and then in a few minutes of syncing I restart it. The node seems to connect to the network, but no blocks get synced.

Here is the command I run (it is a bit specific to indexer, so the most relevant part is the logging-level):

```
env RUST_LOG=indexer=error,aggregated=error,cranelift_codegen=warn,h2=warn,trust_dns_resolver=warn,trust_dns_proto=warn,debug cargo run --release -- --home-dir ~/.near/mainnet run --store-genesis --stream-while-syncing --allow-missing-relations-in-first-blocks 1000 --concurrency 100 sync-from-interruption --delta 100 2>&1 | tee -a mainnet.log
```

Here is the log I collected during 10 minutes of running the node after restart:

[mainnet.log](https://github.com/near/nearcore/files/6961113/mainnet.log)

It is an archival node tracking shard 0. Here is the 
[config.json](https://github.com/near/nearcore/files/6961132/config.json.txt) for your reference.

P.S. sometimes restart solves the issue.

**Comment by asifhj** [comment]
@janewang I am also facing the same issue after the restart of the near mainnet validator. And I found a DB error in the debug logs

![image](https://user-images.githubusercontent.com/1665106/146714604-a2ecc4c0-86fd-4c4d-b458-7b2b834d77b0.png)

The blocks count keeps increasing.

![image](https://user-images.githubusercontent.com/1665106/146714629-b5ccee6d-fe3e-460d-943d-3a36a0a77496.png)

**Comment by marcelo-gonzalez** [comment]
@asifhj Could you please share the neard version you were running? Also did you see any log messages that look something like ``` Block sync: ... requesting block { hash } from N peers``` ?

**Comment by asifhj** [comment]
@marcelo-gonzalez thanks for the response. I am running 1.23.0 version. I am participating in the mainnet delegation program. 4 other guys reported the same issues in the discord. I am sorry, restarted from scratch with a new dump. Let me try to pull some logs from my Splunk setup.

**Comment by bowenwang1996** [comment]
@asifhj did you change your config.json between restart of the node? This error could be the result of you trying to change from tracking no shard to tracking some shard

**Comment by marcelo-gonzalez** [comment]
Just took another look at this, and I think the logging cleanup in https://github.com/near/nearcore/commit/5c323f2c5b66ee3370ec60733a5b6e7fe97cda75 is actually relevant. In the logs @frol posted in the comment above, we see the log lines:

```
Aug 10 11:03:23.388 DEBUG sync: Block sync: 38182230/44856718 requesting block 3Q6bZyH4y8kPCChWtXJqJwrW1MELAdiNVbZKVY2v1DgK from 3 peers
...
...
Aug 10 11:03:26.435  INFO stats: #38182230 Downloading blocks 80.95% (6674491)   3/3/40 peers ⬇ 475.5kiB/s ⬆ 468.4kiB/s 0.00 bps 0 gas/s CPU: 30%, Mem: 2.3 GiB
...
...
Aug 10 11:12:56.648 DEBUG sync: Block sync: 38182230/44857276 requesting block 3Q6bZyH4y8kPCChWtXJqJwrW1MELAdiNVbZKVY2v1DgK from 8 peers
...
...
Aug 10 11:12:56.690  INFO stats: #38182230 Downloading blocks 80.95% (6675046)   8/8/40 peers ⬇ 49.2kiB/s ⬆ 16.6kiB/s 0.00 bps 0 gas/s CPU: 23%, Mem: 2.6 GiB
```

So the first block sync debug log line shows that the node was trying to request a block from one out of 3 highest height peers, and there were no other active peers (from the "3/3/40" part. Then there are lots more lines like that til it gets to 8 peers. But if we look at the handshake log lines like:

```
Aug 10 11:02:48.495 DEBUG network: ed25519:E6BhYdFEvyMnG3SKnTF6ibPQgwWEYXTqCrNSQAYdW2uZ: Received handshake Handshake { version: 46, oldest_supported_version: 34, peer_id: ed25519:UeH6Q1wm6ENxH5LBCL8ghiEeXZS5q8ZtbyLPeMR5Mzm, target_peer_id: ed25519:E6BhYdFEvyMnG3SKnTF6ibPQgwWEYXTqCrNSQAYdW2uZ, listen_port: Some(24567), chain_info: PeerChainInfoV2 { genesis_id: GenesisId { chain_id: "mainnet", hash: `EPnLgE7iEq9s7yTkos96M3cWymH5avBAPm3qx3NXqR8H` }, height: 44856685, tracked_shards: [0], archival: false }, edge_info: EdgeInfo { nonce: 5, signature: ed25519:325Wsz3freCTV48YzunMFP5pLL9oBUqerkyde6THqw2zY5pgKupnWYUCveZwQ4nthnirbGRN6AEeWPUWsW7HrTfb } }
```

They all show `archival=false`, and this indexer node was trying to sync from block height #38182230 to block height #44857276, which would def need archival nodes to sync from

**Comment by marcelo-gonzalez** [comment]
well, at least that explains what happened in that particular case, but not really what happened in the original post...

**Comment by bowenwang1996** [comment]
obsolete
