### ISSUE TITLE
Nayduck build is broken

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4430]
All the adversarial tests fail with something like
```
AssertionError: {'jsonrpc': '2.0', 'error': {'name': 'REQUEST_VALIDATION_ERROR', 'cause': {'name': 'METHOD_NOT_FOUND', 'info': {'method_name': 'adv_disable_doomslug'}}, 'code': -32601, 'message': 'Method not found', 'data': 'adv_disable_doomslug'}, 'id': 'dontcare'}
```
which seems to indicate that the build is broken. This might be a result of the nearcore crate refactoring we did recently.

**Comment by mina86** [comment]
This has been broken for a while http://nayduck.eastus.cloudapp.azure.com:3000/#/test/160516 so it must be caused by something else. In general this looks like the tests using non-adversarial build of the node.
