### ISSUE TITLE
Nayduck regression

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4432]
Looks like #4418 caused some python tests to regress:
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/169005
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/169025

**Comment by austinabell** [comment]
Wasn't aware this infra used the master branch of the SDK. Is there a channel I should notify of these kinds of changes in the future?

**Comment by bowenwang1996** [comment]
Actually I don't think we should depend on the master branch of near-sdk-rs. cc @mina86

**Comment by mina86** [comment]
I’ve been wondering about that. The dependency is only in the tests so perhaps it could be viewed as testing the SDK as well. But yeah, otherwise I can see how that's surprising.

**Comment by mina86** [comment]
The two failures are now fixed, though it still remains an open question whether we want to depend on master branch of near-sdk-rs. I don’t have strong opinions and the change should be trivial.

**Comment by austinabell** [comment]
> The two failures are now fixed, though it still remains an open question whether we want to depend on master branch of near-sdk-rs. I don’t have strong opinions and the change should be trivial.

I don't have an opinion, but it would be very rare for another breaking change like this where this contract would break.
