### ISSUE TITLE
nearcore migrations IO Error: Unexpected length of input

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#4441]
**Describe the bug**
Tried to start nearcore's latest master with archival mainnet database and failed with error

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner:
IO Error: Unexpected length of input }'
nearcore/src/migrations.rs:345:49
``` 

**To Reproduce**
Build neard with `master` branch, spin up an archival mainnet node, try to start

**Expected behavior**
Expect that all necessary migration will be applied and the node will start

**Version (please complete the following information):**
- nearcore master
- mainnet (and testnet perhaps)

**Additional context**
I wanted to check this [indexer for explorer PR](https://github.com/near/near-indexer-for-explorer/pull/131) on block #17761085 and failed to start a node with archival mainnet node

**Comment by bowenwang1996** [comment]
@khorolets but I believe you've applied this migration previously and it worked fine right?

**Comment by bowenwang1996** [comment]
Caused by #4450
