### ISSUE TITLE
NEARCore localnet continues to run after attempting to stop with Ctrl+C

### ISSUE THREAD

**Issue by DiscRiskandBisque** [near/nearcore#4446]
**Describe the bug**
A localnet NEARCore node won't stop with Ctrl+C. The console will output `Stopping NEARCore.`, but the process will continue. INFO logs will continue to stream into the same console instance as well. The process must be killed manually.

**To Reproduce**
1. Start NEARCore using `./scripts/start_localnet.py --nodocker`
2. Attempt to shutdown with Ctrl+C
3. Console displays `Stopping NEARCore.`
4. New INFO logs continue appearing
5. `pgrep near` will provide a process number, showing it's still running
6. Kill the process with `kill <process_number>`

**Expected behavior**
After the `Stopping NEARCore.` message appears, the process should shutdown and no more logs should be printed to the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/3990373/124039264-9e77ac00-d9d0-11eb-8c60-b98271cfc4fa.png)

**Version (please complete the following information):**
- `commit 9a121f42379d67bcb67d65d9d1137797105c9666 (HEAD -> master, origin/master, origin/HEAD)`
- `rustc 1.51.0 (2fd73fabe 2021-03-23)`
- not using docker
- local

**Additional context**
- OS: WSL 2 on Windows 10 Home
- Terminal: Windows Terminal

**Comment by DiscRiskandBisque** [comment]
The `./scripts/start_localnet.py --nodocker` and `git add -A` after the `^C` are not part of the logs themselves, just me up-arrowing through previous console commands not knowing the INFO logs would continue to output.

**Comment by bowenwang1996** [comment]
I believe this is the same issue as #3266
