### ISSUE TITLE
Improve docs for `runtime-params-estimator`

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4460]
I ran into some pitfalls during generating `RuntimeConfig` using `runtime-params-estimator`. I plan to improve docs a bit so it will be easier for future users to work with it, e.g. adding QA section.

**Comment by bowenwang1996** [comment]
@Longarithm is this done?

**Comment by Longarithm** [comment]
@bowenwang1996 Yes. https://github.com/near/nearcore/pull/4684 is one of the outcomes here
