### ISSUE TITLE
Refactor `RuntimeConfig` handling 

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4468]
We store `RuntimeConfig` in the NightShadeRuntime:

https://github.com/near/nearcore/blob/056f789e38c3e364cf1ae3db846499db518e32c5/nearcore/src/runtime/mod.rs#L132

The original idea seemed to be that this is basically a constant, but now we have two places where we actually modify config.

First, when we get config for specific protocol version:
 https://github.com/near/nearcore/blob/056f789e38c3e364cf1ae3db846499db518e32c5/core/primitives/src/runtime/config.rs#L58-L71

Second, when max_gas_burnt_view is set:

https://github.com/near/nearcore/blob/056f789e38c3e364cf1ae3db846499db518e32c5/nearcore/src/runtime/mod.rs#L157-L164

There are two problems here:

* The first code-path is subtly buggy -- it caches RuntimeConfig into a global variable, which might create dependence between different tests
* The data flow is unclear -- it's not obvious which config value is actually used when. For example, the logic [here](https://github.com/near/nearcore/blob/056f789e38c3e364cf1ae3db846499db518e32c5/nearcore/src/runtime/mod.rs#L1547-L1564) is quite subtle. 

To fix the first point, as suggested by @mina86 , we should just remove the lazy static can compute the config eagarly:

```rust
pub struct CurrentRuntimeConfig {
    inital_config: RuntimeConfig
    after_lowered_costs: RuntimeConfig
}

impl CurrentRuntimeConfig {
    pub fn  for_protocol_version(&self, pv: ProtocolVersion) -> &RuntimeConfig
}
```

Not sure what's the best solution to the second bullet point, I haven't looked super closely what happens there.

**Comment by matklad** [comment]
cc https://github.com/near/nearcore/issues/1738

**Comment by matklad** [comment]
@mina86 I wonder if you might be interested in picking this up -- you suggested much better solution than I had in #4263 :-)

**Comment by mina86** [comment]
Yeah, I probably can take it. It shouldn’t be too much work.
