### ISSUE TITLE
Clear obsolete compile contract cache entires when upgrading VM

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4473]
Today, we store contracts, precompiled from wasm to VM-specific contract, in the database. We include the version and other bits of vm configuration into the key:

https://github.com/near/nearcore/blob/ff01c544ce2675fadbf0284af52b356a383b27a8/runtime/near-vm-runner/src/cache.rs#L20-L62

When configuration changes, all currently stored versions become useless. This doesn't affect correctness, but does increase store usage, as the old caches are stored in the DB as a dead weight. 

We need to add some ability to prune the cache. There are two strategies here:

* make cache key more structured, so that it's possible to iterate old keys and drop them one by one
* just drop the whole DB column when upgrading version: https://github.com/near/nearcore/blob/ff01c544ce2675fadbf0284af52b356a383b27a8/core/store/src/db.rs#L118-L120

We should pick one strategy and implement it. It seems that the simplest thing to do is to just write a cache-cleaning migration everytime we change the key. We probably want to do this with https://github.com/near/nearcore/pull/4448 the first  time, to iron out the process.

**Comment by bowenwang1996** [comment]
Ideally we should recompiled the contracts during migration to avoid breaking the invariant that contracts stored in state are compiled. However, that means that migration could take a while if there are a large number of contracts.

**Comment by ailisp** [comment]
Right now there's no way to iterate old keys (you can iterate the DB column, but the key is hashed, you cannot make a new key from the old key. So the first approach or @bowenwang1996 's comment doesn't work. I'll do approach 2 for https://github.com/near/nearcore/pull/4448. 

I suggest the following way to layout the new key in order to support iterate-and-recompile, inspired by @olonho :
```
<VersionNumber:u32><code_hash><hash of contract cache key>
or just non hashed ContactCacheKey, with the guarantee that first field always being <code_hash>
```
borsh serialized. Current format there is only `<hash of contract cache key>`. With this format it's easy to iterate contracts of certain version number, and easy to iterate all versions (if exists) of certain contract code hash. Also, because code_hash at the front, it's distributed enough as trie key.

**Comment by matklad** [comment]
Can we iterate `CONTRACT_CODE` column of the Trie?

https://github.com/matklad/nearcore/blob/ceac6a1d949424fd957b854f1e4d5770d4a9c7e6/core/primitives/src/trie_key.rs#L14-L16

I don't think we need the ability to iterate data in compiled contract cache -- seems its enough to be able to drop it, and to iterate the contracts themselves?

**Comment by ailisp** [comment]
Yeah that probably works, we can iterate CONTRACT_CODE and check if they have been compiled by making and checking the compiled cache column, and if so make a recompile, save under the new cache key format to solve @bowenwang1996's concern.

**Comment by bowenwang1996** [comment]
> Can we iterate CONTRACT_CODE column of the Trie?

We can, but it will be much slower than iterating a database column since we need to do a trie traversal and cannot take advantage of data locality.

**Comment by bowenwang1996** [comment]
Tbh rewriting a migration every time it happens is also *a* general mechanism :)

**Comment by matklad** [comment]
:+1: then let's close this: the current approach is good enough, and there are bigger problems to solve!
