### ISSUE TITLE
Non-reproducible tests due to pytest/empty-contract-rs

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4480]
We have this "stub" contract: 

https://github.com/near/nearcore/blob/3ac2b829f019372d69c9e98b29a5ccdf89bf6d5d/pytest/empty-contract-rs/

It is used primarily by this function:

https://github.com/near/nearcore/blob/c85bf403909018e24c7a83a20b9bbf33958a16c9/pytest/lib/utils.py#L192-L211

The problem with this empty contract is that it depends on master branch of the sdk repo *without lockfile*:

https://github.com/near/nearcore/blob/c85bf403909018e24c7a83a20b9bbf33958a16c9/pytest/empty-contract-rs/Cargo.toml#L11

So, every time we run a test, we get what's currently the latest commit in master, meaning that test actually run different contracts. 

I suggest to, at minimum, pin the version in Cargo.toml to a specific commit using the `rev = ` Cargo.toml key. 

Perhaps a better solution is to move the tests currently using empty-contract to use the standard testing contracts instead, a-la: https://github.com/near/nearcore/issues/4475. I don't think it makes a ton of sense that `nearcore` depends on `near-sdk-rs` for testing (nearcore ships SDK-independent ABI), and that create extra complexity (need to track sdk changes, more time spent compiling sdk-enabled contrcts, which include heavy proc-macro machinery).

**Comment by matklad** [comment]
Looking at the git history of this test contract, looks like this issue suggests to revert the decision in https://github.com/near/nearcore/pull/1947. 

@nearmax, I wonder what are your thoughts here, should we, or should we not use `near-sdk-rs` for pytests?

I think your main point is that it's easier to use sdk for testing complex functionality like cross-shard calls.

That's true, but we also didn't add a lot of sdk-dependent tests in a year, so perhaps we don't need this just yet, and should re-visit once we need to add such tests? My gut feeling would be that it's still beneficial to write those tests on top of our bare-bones sdk-less test contract -- that way it's easier for nearcore devs to understand what exactly the contract is doing, as sdk adds quite a bit of abstraction and indirection.

**Comment by mina86** [comment]
At this point there's only one remaining test which uses near-sdk-rs. It uses it to build a trivial busy work function. It’s easiest to just not depend on the near-sdk IMO. The only thing to consider is whether we want to test near-sdk as part of the tests but we probably don’t want to do that.

**Comment by mina86** [comment]
We no longer depend on `near-sdk`.
