### ISSUE TITLE
Investigate unrealistic base cost of `DataReceiptCreationConfig`

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4482]
In recent `runtime-params-estimator` launches, `DataReceiptCreationConfig` base cost is 50 TGas, which is unrealistically high comparing to current cost of 4.5 TGas.

Examples:
https://github.com/near/nearcore/pull/4231
https://github.com/near/nearcore/pull/4455

```
data_receipt_creation_config: DataReceiptCreationConfig {
  base_cost: Fee {
      send_sir: 50745691155500,
      send_not_sir: 50745691155500,
      execution: 50745691155500,
  }
  ...
}
```

cc @bowenwang1996 @olonho

**Comment by bowenwang1996** [comment]
To be clear, the current cost of 4.5Tgas is also unrealistically high. See https://github.com/near/nearcore/pull/3279 for a discussion on this.

**Comment by Longarithm** [comment]
From the first sight, difference is explained by taking IO costs into account:
https://github.com/near/nearcore/pull/3771#issuecomment-750358010 - 50 TGas
https://github.com/near/nearcore/pull/3771#issuecomment-750357731 - 300 Ggas
Local computation in docker confirm this.

But there is conflicting info here:
https://github.com/near/nearcore/pull/3771#issuecomment-751226986 - 40 Ggas **in both cases**. 
Need to investigate further

cc https://github.com/near/nearcore/issues/4474 @matklad

**Comment by Longarithm** [comment]
Data receipt fee estimation depends on its place in the vector of metrics: https://github.com/near/nearcore/blob/master/runtime/runtime-params-estimator/src/cases.rs#L536

Consider an example:
```
    let v = calls_helper! {
        data_receipt_base_10b_1000_1 => data_receipt_base_10b_1000,
        data_receipt_10b_1000_1 => data_receipt_10b_1000,
        data_receipt_100kib_1000_1 => data_receipt_100kib_1000
        cpu_ram_soak_test => cpu_ram_soak_test,
        base_1M => base_1M,
        read_memory_10b_10k => read_memory_10b_10k,
        ...
        data_receipt_base_10b_1000_2 => data_receipt_base_10b_1000,
        data_receipt_10b_1000_2 => data_receipt_10b_1000,
        data_receipt_100kib_1000_2 => data_receipt_100kib_1000
    };
```
Computation of DataReceipt fees based on `data_receipt_base_10b_1000_1`, `data_receipt_10b_1000_1`, `data_receipt_100kib_1000_1` yields 30 Ggas; same computation for `data_receipt_*_2` fees yields 50 TGas. 

Also, if we cleanup data by re-creating `RuntimeTestbed` before computation of `data_receipt_*_2` fees, we get 30 Ggas again.

Supposed explanation:

- initially storage is in optimal state A
- we compute `data_receipt_*_1` fees and get 30 Ggas
- computation of some metric `M` moves storage to suboptimal state B
- we compute `data_receipt_*_2` fees and get 50 Tgas

I currently suspect `M = storage_write_10kib_key_10b_value_1k`.

It makes sense to use separate `RuntimeTestbed` for each computation. But anyway we have to separate the following two cases:
- on mainnet, storage never comes to state B, thus 30 Ggas is the correct realistic price
- on mainnet, there is a way to put storage to state B, and then we risk to have x1000 underestimated `DataReceipt` prices for unknown period of time.

To do so, I plan to understand more deeply what exactly causes the difference by profiling tools.

cc @matklad @olonho @nearmax

**Comment by bowenwang1996** [comment]
@Longarithm is it correct that `data_receipt_creation_cost` measures the cost of one storage write? If not, what exactly does it measure?

**Comment by Longarithm** [comment]
There is also a curious dependency between fees and accounts number.
In the notation of https://github.com/near/nearcore/issues/4482#issuecomment-887633866:
```
+----------+----------------------+----------------------+
| Accounts | data_receipt_*_1 fee | data_receipt_*_2 fee |
+----------+----------------------+----------------------+
| 10K      | 30 Ggas              | 30 Ggas              |
| 20K      | 35 Ggas              | 50 Tgas              |
| 50K      | 40 Ggas              | 110 Tgas             |
+----------+----------------------+----------------------+
```

**Comment by Longarithm** [comment]
@bowenwang1996 
It measures cost of `DataReceipt` creation and processing: https://github.com/near/nearcore/blob/master/core/primitives-core/src/runtime/fees.rs#L71-L85
Strictly speaking, it measures cost of:
- set, get and remove for `ReceiptData`, e.g. https://github.com/near/nearcore/blob/2c4f6dc28bf485a2cba41ca86c928caca7363d4b/core/store/src/lib.rs#L341
- set, get and remove for `PostponedReceiptId`, e.g. https://github.com/near/nearcore/blob/28d9b7d9e01b7a10e2b0258466814dd3b4bb6423/runtime/runtime/src/lib.rs#L925
- update of pending data count https://github.com/near/nearcore/blob/28d9b7d9e01b7a10e2b0258466814dd3b4bb6423/runtime/runtime/src/lib.rs#L898

Though I'm not entirely sure that all these operations are called ~1000 times, as we expect in the measurement.
It's possible that 1000 `DataReceipt`s are processed before processing `ActionReceipt` which collects them, and in such case we don't save postponed receipt ids: https://github.com/near/nearcore/blob/28d9b7d9e01b7a10e2b0258466814dd3b4bb6423/runtime/runtime/src/lib.rs#L914
I need to double-check this. cc @olonho @matklad

**Comment by bowenwang1996** [comment]
@Longarithm is the base cost calculated based on some trivial data or through some statistical method? It looks like this involves at most 4 storage operations and it should not be more expensive than 4 storage writes of [some trivial data]. Also it seems to me that this fee depends on the shape of the trie, but we also have a separate `touching_trie_node` fee that accounts for this.

**Comment by nearmax** [comment]
This explains lots of discrepancies that we are observing: https://near.zulipchat.com/#narrow/stream/295306-dev-contract-runtime/topic/fees.20.26.20state.20size/near/247505050

**Comment by Longarithm** [comment]
Closing, because we have a decent explanation for the issue, and it was fixed in https://github.com/near/nearcore/pull/4647.
