### ISSUE TITLE
Make `cargo test` usable for nearcore developers

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4490]
I've noticed that I never run `cargo test --workspace` locally. I do want to have an ability to quickly check if I broke something somewhere, but the usability of our current `cargo test` is abysmal. 

Specifically: 

* Tests output *a lot* to the terminal, making terminal scrollback buffer useless. 
* Test suite is prohibitively slow. It takes 15 wall-clock minutes / 12 cpu minutes on a 24-core machine.

I suggest immediate AIs:

* fixing the tests such that the output of `cargo test` is never polluted unless the test actually fails. I think using [`TestWriter`](https://docs.rs/tracing-subscriber/0.2.19/tracing_subscriber/fmt/struct.TestWriter.html) is one possible way to do this
* moving all obviously slow tests to `expensive_tests`
* revisiting this issue after this easy wins are achieved.

Longer term, I think it might sense to do the following: 

* replace `expensive_tests` with run-time check (see the example at the end of "Make Tests Fast" section of [this post](https://matklad.github.io/2021/05/31/how-to-test.html#make-tests-fast)).
* add two tiers of `expensive_tests` -- `nightly_only_tests` (> 5 min) and `ci_only_tests` (>10s, <5min). Local `cargo t` skips `ci_only_tests` by default, but they are run by CI for every commit that gets into master
* document the expectations about tests run-time and actively fix regressions. 
* aim for really short test turn-around time. To give an aspiration goal, in rust-analyzer `cargo t` takes 5s wall-clock/35s cpu by default and 30s/100s when including ci only tests.

**Comment by bowenwang1996** [comment]
@matklad this is fixed right?

**Comment by matklad** [comment]
Not at all:

* running `cargo test` still outputs megabytes of DEBUG-level logging to the terminal, 
* it still takes 15 minutes to complete on a 12-core machine

**Comment by pmnoxx** [comment]
@matklad The solution for having many prints is to run the code with
`RUST_LOG=warn cargo test --workspace`.

By setting proper environment flags you eliminate the issue.

**Comment by matklad** [comment]
Seems reasonable to flip the default? Run with `RUST_LOG=INFO` if you need the logs, but get no unnecessary verbose output by default. Generally you only want to see logs for failing tests.

**Comment by pmnoxx** [comment]
> Seems reasonable to flip the default? Run with `RUST_LOG=INFO` if you need the logs, but get no unnecessary verbose output by default. Generally you only want to see logs for failing tests.

I agree, it's a good idea to switch the default for tests. However, then we should update the CI to run with `RUST_LOG=INFO`. Otherwise, you won't see errors on test failure. 

Also changing the default, would change default settings for `neard` binary.

**Comment by mina86** [comment]
> Generally you only want to see logs for failing tests.

Yes, this is the issue. When I run tests all I want to see is `test foo::bar::baz ... ok` a bunch of times. Logs should only be printed on failure.  And to be honest I don’t understand why this isn’t happening; isn’t test runner supposed to capture output of each test? Why are logs still visible?

**Comment by mina86** [comment]
Turns out libtest is broken: https://github.com/rust-lang/rust/issues/90785

**Comment by matklad** [comment]
```diff
diff --git a/test-utils/logger/src/lib.rs b/test-utils/logger/src/lib.rs
index 7372b5308..6be107180 100644
--- a/test-utils/logger/src/lib.rs
+++ b/test-utils/logger/src/lib.rs
@@ -20,7 +20,7 @@ fn setup_subscriber_from_filter(mut env_filter: EnvFilter) {
     let _ = tracing_subscriber::fmt::Subscriber::builder()
         .with_span_events(tracing_subscriber::fmt::format::FmtSpan::CLOSE)
         .with_env_filter(env_filter)
-        .with_writer(std::io::stderr)
+        .with_writer(tracing_subscriber::fmt::TestWriter::new())
         .try_init();
 }
 
```

might fix the issue (a bit swamped rn to submit an actual PR)

**Comment by pmnoxx** [comment]
> ```diff
> diff --git a/test-utils/logger/src/lib.rs b/test-utils/logger/src/lib.rs
> index 7372b5308..6be107180 100644
> --- a/test-utils/logger/src/lib.rs
> +++ b/test-utils/logger/src/lib.rs
> @@ -20,7 +20,7 @@ fn setup_subscriber_from_filter(mut env_filter: EnvFilter) {
>      let _ = tracing_subscriber::fmt::Subscriber::builder()
>          .with_span_events(tracing_subscriber::fmt::format::FmtSpan::CLOSE)
>          .with_env_filter(env_filter)
> -        .with_writer(std::io::stderr)
> +        .with_writer(tracing_subscriber::fmt::TestWriter::new())
>          .try_init();
>  }
>  
> ```
> 
> fixes the issue (a bit swamped rn to submit an actual PR)

I tried that, but that doesn't work. This test will never print anything:

```

    #[test]
    fn test_print_info() {
        info!("TEST");
        assert!(false);
    }
```

**Comment by pmnoxx** [comment]
> ```diff
> diff --git a/test-utils/logger/src/lib.rs b/test-utils/logger/src/lib.rs
> index 7372b5308..6be107180 100644
> --- a/test-utils/logger/src/lib.rs
> +++ b/test-utils/logger/src/lib.rs
> @@ -20,7 +20,7 @@ fn setup_subscriber_from_filter(mut env_filter: EnvFilter) {
>      let _ = tracing_subscriber::fmt::Subscriber::builder()
>          .with_span_events(tracing_subscriber::fmt::format::FmtSpan::CLOSE)
>          .with_env_filter(env_filter)
> -        .with_writer(std::io::stderr)
> +        .with_writer(tracing_subscriber::fmt::TestWriter::new())
>          .try_init();
>  }
>  
> ```
> 
> fixes the issue (a bit swamped rn to submit an actual PR)

Thanks, I tested it. This works fine: https://github.com/near/nearcore/pull/6023

**Comment by mina86** [comment]
> fixes the issue (a bit swamped rn to submit an actual PR)

Indeed, https://github.com/near/nearcore/pull/6025

> replace expensive_tests with run-time check (see the example at the end of "Make Tests Fast" section of this post).

The issue with that approach is that if you forget to set the environment variable you end up with a passing test that doesn’t test anything. This is another limitation of libtest which does not allow returning an `ignore` state from a test, see <https://github.com/rust-lang/rust/issues/68007>. The issue mentions test-with crate and an RFC so I’m looking at those now.

**Comment by matklad** [comment]
https://github.com/near/nearcore/issues/5817 is related -- tests not being flaky is a part of `cargo test` being usable out of the box.

**Comment by matklad** [comment]
FWIW, the situation is much improved, `cargo test` now takes only 4 minutes locally! Thanks @mina86 and @pmnoxx !

**Comment by matklad** [comment]
For the future, by running `cargo test -- -Z unstable-options --report-time` we can find further slowest tests.

**Comment by pmnoxx** [comment]
@matklad Thanks, that's really useful. I'll add it to my scripts.
