### ISSUE TITLE
Remove protocol_feature_evm

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4515]
I think we want to completely remove `protocol_feature_evm` and the related functionality. Is that correct?

I don't think we currently are tracking this work, so let's create an issue for this. I wonder what's the right team to do this? Probably contract runtime at this point?

**Comment by bowenwang1996** [comment]
> I think we want to completely remove protocol_feature_evm and the related functionality. Is that correct?

Not so sure about that. @artob @djsatok what do you think?

**Comment by birchmd** [comment]
As far as I know the feature is not needed any more because we used a different one for the math API work, which is all that Aurora needs from nearcore since it was decided to have the engine be a contract instead of part of nearcore itself.
