### ISSUE TITLE
Remove support for wasmer engine native

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4520]
We currently use `wasmer-engine-native`, also known as dylib engine (wasmer 1+):

https://github.com/near/nearcore/blob/321e4caa0fcd866aae036f15c45a9a841d8a8c30/runtime/near-vm-runner/Cargo.toml#L25

This engine uses `.so` format for wasmer modules and uses system dynamic linker to load wasm modules into memory. This gives some speed increase, at the cost of runtime dependency on the system's linker. This is not a reasonable tradeoff for contract runtime, as reproducibility and reliability is more important than performance. We should remove the code and dependencies related to native engine.

**Comment by matklad** [comment]
I think this might get fixed by #5960

**Comment by nagisa** [comment]
I believe we already use the `universal` engine even before the PR in question. I think that makes this issue solved already. Closing, but lets reopen if there's any reason to believe that's not the case.
