### ISSUE TITLE
Flaky behavior in nayduck

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4574]
It appears that sometimes tests fail for reasons unrelated to the tests themselves. Examples:
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/187252
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/187386
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/187368
* http://nayduck.eastus.cloudapp.azure.com:3000/#/test/187378

And it appears that there is some weird cascading effects here where such failures often appear together in multiple tests.

**Comment by mina86** [comment]
I’m certainly not opposed to that.
