### ISSUE TITLE
Consider upgrading to the most stable Rust

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4588]
At the moment, we still use Rust 1.51.0. The latest stable is 1.53.0, and 1.54.0 release is imminent, so we might consider upgrading. 

Some interesting considerations:  

* 1.53.0 includes https://github.com/rust-lang/cargo/pull/9298, which should significantly improve compile times for devs using macs. 
* 1.51 (current version) has broken incremental compilation, 1.52&1.53 have incremental compilation disabled, I *think* 1.54 fixes and re-enabled it. 

I suggest that we wait for 1.54 and switch to that. From then on, it perhaps makes sense to always upgrade to the latest rust. but we might want to do that couple of weeks *after* the release, in case a minor release happens.

**Comment by bowenwang1996** [comment]
1.54 is already released. This issue is not blocked any more

**Comment by matklad** [comment]
Note: our outdated rust prevents merging #4395
