### ISSUE TITLE
Using snapshot from here https://docs.near.org/docs/develop/node/intro/node-data-snapshots leads to weird crash

### ISSUE THREAD

**Issue by rozum-dev** [near/nearcore#4605]
**Describe the bug**
Node crashes after I get and unarchive a snapshot from here https://docs.near.org/docs/develop/node/intro/node-data-snapshots

Log looks like this
Jul 29 12:19:51 frhb51389ds neard[30513]: thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "NotFound: /home/near/.near/data/CURRENT: does not exist" })', core/store/src/migrations.rs:46:32

File CURRENT is in the /home/near/.near/data/ has 644 permission and owns by the user 'near' witch I use to start the node by service

**To Reproduce**
Steps to reproduce the behavior.
1. wget ~/.near/data.tar https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/rpc/data.tar
2. sudo tar -xf ~/.near/data.tar -C ~/.near/data
3. sudo chown near:near -R  /home/near/.near/data
4. sudo chmod -R 644 /home/near/.near/data
5. sudo systemctl restart  neard.service
6. sudo journalctl -u neard.service -f
Jul 30 06:13:33 frhb51389ds systemd[1]: Started NEARD service.
Jul 30 06:13:33 frhb51389ds neard[3879]: Jul 30 06:13:33.645  INFO neard: Version: 1.20.0, Build: 09b978c15, Latest Protocol: 46
Jul 30 06:13:33 frhb51389ds neard[3879]: Jul 30 06:13:33.654  INFO near: Opening store database at "/home/near/.near/data"
Jul 30 06:13:33 frhb51389ds neard[3879]: thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "NotFound: /home/near/.near/data/CURRENT: does not exist" })', core/store/src/migrations.rs:46:32
Jul 30 06:13:33 frhb51389ds neard[3879]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 30 06:13:33 frhb51389ds systemd[1]: neard.service: Main process exited, code=exited, status=101/n/a
Jul 30 06:13:33 frhb51389ds systemd[1]: neard.service: Failed with result 'exit-code'.

**Expected behavior**
Node should run

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
1.20.0
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**

**Comment by frol** [comment]
@mhalambek Any clues?

**Comment by nikurt** [comment]
Please see the discussion on telegram, that a successful download can lead to a corrupted file.
https://t.me/c/1331540142/11128
