### ISSUE TITLE
Automate canary node testing from PR

### ISSUE THREAD

**Issue by frol** [near/nearcore#4607]
Currently, we run CI tests automatically, and can manually trigger nayduck tests, but we cannot trigger canary node testing for PR, and it is not rare that we break canary immediately after we land some PR from master. This requires then extra effort to revert the changes, and re-introduce them. (#4440 + #4601)

**Comment by chefsale** [comment]
Yes, I agree we decided firstly not to run a canary on every PR, as the reasoning was we will not catch issues as we need to run the canary for the while. I think most of the cases we have seen in the past is that the canary doesn't even start often. I think we can just implemebt a sanity test to start the node in tge CI which would catch all the issues like this. What do you think?

**Comment by bowenwang1996** [comment]
Agree with Sandi that running it in CI might take too long. Our CI already takes longer than desired to finish

**Comment by frol** [comment]
I don't suggest we run these heavy canary tests on every PR. Yet, I still want to be able to trigger it manually just like sometimes we trigger nayduck for the branch instead of merging it and waiting for the nightly build.

**Comment by bowenwang1996** [comment]
@mina86 could we add this functionality to nayduck?

**Comment by mina86** [comment]
On first sight it doesn’t sound like a good fit for NayDuck.  Unless I misunderstands what canary is, this would require messing with production (in testnet flavour I’m guessing) by updating what code canary nodes are running.  I certainly would not like NayDuck to have any kind of credentials which would allow it to do that.  Apart from that, this doesn’t sound like a test, i.e. there’s no passing condition, rather we just want to update the binary on canary nodes and see what happens.

**Comment by chefsale** [comment]
I personally feel this should be added to the CI sanity checks and kind of agree with @mina86 that this is not really a test.
