### ISSUE TITLE
Clean up profile data  and vm outcome

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#4615]
From @matklad 's comment in https://github.com/near/nearcore/pull/4582:

- [ ] remove serialize/deserialize from vm outcome
- [ ] re-install partial eq on vm outcome
- [x] don't track burn gas in two places
- [x] get rid of the cells inside ProfileData

**Comment by ailisp** [comment]
Note: We need VMOutcome Serialize in standalone runner, so we can't drop it yet.

**Comment by ailisp** [comment]
Hmm drop burn gas in ProfileData is also problematic. burn gas is the `ProfileData.all_gas()`, and profile data need it to figure out `wasm_gas()`. The other way would be drop burnt_gas from VMOutcome

**Comment by bowenwang1996** [comment]
@ailisp is this issue still relevant?

**Comment by ailisp** [comment]
Two of them are still relevant, create two PR to address: 
https://github.com/near/nearcore/pull/5107
https://github.com/near/nearcore/pull/5108

**Comment by matklad** [comment]
Was fixed!
