### ISSUE TITLE
ShardTracker's update_epoch is not called correctly

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#4629]
**Describe the bug**
`ShardTracker::update_epoch` should be called at least once per epoch for non-validator clients to track shards correctly, if they ever call the `untrack_shards` or `untrack_accounts` function. 

If a non-validator client is tracking some shards and calls `untrack_shards` at epoch T, the untracked shards will only be take effect at epoch T+1 after `update_epoch` is called. However, right now, there is no place in the code that calls `update_epoch`, so the shard may never be updated.

This will also cause a problem when we implement sharding splits for the simple nightshade migration.

**Expected behavior**
ShardTracker::update_epoch should be called at the beginning of every epoch

**Version (please complete the following information):**
- nearcore commit/branch master 624a3bc621ebb76b9a8e6d718cb92a30590ddfb0

**Additional context**

**Comment by bowenwang1996** [comment]
> if they ever call the untrack_shards or untrack_accounts function.

Currently there is no way to them to call it. Do you suggest adding this functionality? If so, it is more of a feature request rather than a bug

**Comment by mzhangmzz** [comment]
Yeah, I created this issue because I didn't know that untrack_shards and untrack_accounts are not used (before our meeting).  We might want to consider getting rid of these functions.  They complicate the implementation when shard layout change, makes the code quite confusing.
