### ISSUE TITLE
1.19.2 stopped syncing - Required re-sync after update to 1.20.0

### ISSUE THREAD

**Issue by jwbd1** [near/nearcore#4645]
**Describe the bug**
Node stopped syncing on version 1.19.2 with errors:
```
WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
```

The node didn't continue to sync after updating to 1.20.0 and required a re-sync.
(used the snapshot)

**To Reproduce**
Sync with 1.19.2 until it reaches block 44337060, at which point we received:
```
WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
```
 
Upgrading to the latest version doesn't resolve it(without a re-sync).

**Expected behaviour**
Node continues to sync after version update without any data corruption,  a re-sync not required.

**Version (please complete the following information):**
- nearcore 1.19.2 -> 1.20.0
- docker 20.10.2
- mainnet

**Additional Information**
If known, it would be really useful to include network upgrade timeline information(block number etc.) in the version announcement to ensure we meet the update ahead of it.

Thanks!

**Comment by bowenwang1996** [comment]
> If known, it would be really useful to include network upgrade timeline information(block number etc.) in the version announcement to ensure we meet the update ahead of it.

Unfortunately this is not possible. The upgrade depends on when the majority of the validators decide to upgrade to the new version. You can read more about this here https://nomicon.io/ChainSpec/Upgradability.html
