### ISSUE TITLE
Abnormally high CPU Usage - Restart Resolved

### ISSUE THREAD

**Issue by gaia** [near/nearcore#4655]
**Describe the bug**
Abnormally high CPU Usage causes node to fall out of sync

**To Reproduce**
?

**Expected behavior**
Normal CPU usage, as it has been current for the past few months

**Version (please complete the following information):**
neard 1.20.0 (build 09b978c1) (protocol 46) (db 23)
rustc 1.46.0 (04488afe3 2020-08-24)
mainnet

**Additional context**
Last night, the daemon started using a lot CPU soon after 23:00 (went to 25 on a 6 core/12 thread Xeon), which caused it to fall out of sync at Aug 08 01:07:22.798. Restarting neard (systemd) immediately brought CPU usage back to normal levels. 

I am 100% sure there were no networking issues during the period in question. There are plenty of monitors on this machine.

CPU usage:
![image](https://user-images.githubusercontent.com/87547/128640765-39ff3517-8844-4427-b0e0-141987db8d21.png)

PS: password for the log zip archive is "09b978c1"
[neard.zip](https://github.com/near/nearcore/files/6951230/neard.zip)

**Comment by bowenwang1996** [comment]
By looking at the logs I found that the node essentially got stuck for 6 minutes and then strangely receives no new blocks for a while before it realized that it is out of sync. Something very weird happened there, but the log unfortunately does not have enough information for me to tell what exactly happened.

**Comment by gaia** [comment]
Thanks Bowen. What are the timeframes for the 2 events? The CPU was thru the roof. 

If there is anything, let me know what I can run next time this happens (hopefully it won't).

**Comment by nikurt** [comment]
Hi @gaia ,
Unfortunately, the log doesn't have debug information and doesn't help understanding the issue.

Would you please enable debug logging and let me know when the issue happens again?
Assuming you run a node using `neard`, please add `RUST_LOG` to the command line, so that it looks something like that:
`RUST_LOG='debug,actix_web=info' neard run`
