### ISSUE TITLE
`state-viewer` fails to dump new genesis state due to mismatching supply

### ISSUE THREAD

**Issue by nikurt** [near/nearcore#4665]
**Describe the bug**
`cargo build --package state-viewer --features nightly_protocol,nightly_protocol_features && ./target/debug/state-viewer --home=~/.near/betanet dump_state`
```
Aug 10 16:24:45.084  INFO near: Opening store database at "/home/user/.near/betanet/data"
Aug 10 16:24:48.135  INFO runtime: Tracking shards: {0}
Generating genesis from state data of #34125348 / Dve5dnycfdsn7F9gWfVUQEwwCD3xqw4SpJ7f9bmqo9Cn
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1371902924464758940086228587317865`,
 right: `1331261183170775131069856846142903`: wrong total supply', core/chain-configs/src/genesis_validate.rs:85:9
```

This is caused by a recent change forcing validation of total_supply upon each creation of `Genesis`.
What happens is that every epoch the total supply is burned and/or minted. Which leads to a discrepancy between the supply in `records` and in `total_supply` in `genesis.json`.

**Comment by bowenwang1996** [comment]
> What happens is that every epoch the total supply is burned and/or minted. Which leads to a discrepancy between the supply in records and in total_supply in genesis.json.

This is not the case. The following invariant should always hold: total supply is equal to the sum of locked and liquid balance across all accounts. When new tokens are minted, they are distributed to some accounts (validators). When tokens are burnt, some account paid for them.
