### ISSUE TITLE
Wasmer 2 trap handler doesn't work well with cargo test --test-threads=1

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#4669]
Could be cargo test's trap handler has some confliction with wasmer 2's and does not necessarily need fix on wasmer2. But we need to investigate to understand why cargo test --test-threads=1 doesn't work. This is the only unclear thing in #4395 . A few facts:

- wasmer 1 was working with cargo test --test-threads=1 or no test-threads limitation
- wasmer 2 near vm runner tests work with cargo test, but don't work when --test-threads=1
- it does not related to wasmer 0's trap handler behavior as comment wasmer 0 code the result is same

**Comment by ailisp** [comment]
@olonho I assigned to you first since you're quite good at understanding how their trap handler interacts and I got other priorities, in case you're busy I can take it some time later. /cc @matklad

**Comment by matklad** [comment]
fixed by removing the trap handler altogether.
