### ISSUE TITLE
Add an integration test for creating invalid subaccount

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4696]
Add a test that asserts an account `alice` cannot create accounts of type `x.y.alice` but can create accounts of type `x.alice`. This should catch bugs like what this fixed in https://github.com/near/nearcore/pull/4694

**Comment by miraclx** [comment]
I suppose this covers it, right?

https://github.com/near/nearcore/blob/6db93dab90dbdaf238b627c03d0af5b855961718/core/account-id/src/lib.rs#L361

**Comment by bowenwang1996** [comment]
@miraclx that is not an integration test
