### ISSUE TITLE
Remove `max_gas_burnt_view` from `VMLimitConfig`

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4719]
`max_gas_burnt_view` field is not used in `VMLimitConfig` anymore, so let's remove it when the new way of updating `RuntimeConfig` will be introduced: https://github.com/near/nearcore/issues/4649

See https://github.com/near/nearcore/issues/3080 and https://github.com/near/nearcore/pull/4716 for more details.

**Comment by bowenwang1996** [comment]
This may change genesis hash. Please sync with @posvyatokum on #4447
