### ISSUE TITLE
Misleading error when not full access key is used

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#4746]
**Describe the bug**
If developers tries to send money using function access key, the error is confusing.
Please provide a short description of the bug.

**To Reproduce**
1. Add function access key to the account
2. Sign transaction with single transfer action
Observer error:
```
            InvalidAccessKeyError::RequiresFullAccess => write!(
                f,
                "The transaction contains more then one action, but it was signed \
                 with an access key which allows transaction to apply only one specific action. \
                 To apply more then one actions TX must be signed with a full access key"
            ),
```

**Expected behavior**
Error that says you can not send money with non full access key.

**Screenshots**
![image](https://user-images.githubusercontent.com/175486/131123522-c291cb0e-1af2-4e15-95d5-be37ff6b05ea.png)

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**
The error is coming from here: https://github.com/near/nearcore/blob/2d7b3c0eb1823f4f96748cac9e561874dad10af9/core/primitives/src/errors.rs#L523

**Comment by frol** [comment]
@miraclx I believe we should just update the wording of the error message.
