### ISSUE TITLE
Minimize fuzzing test case in CI

### ISSUE THREAD

**Issue by posvyatokum** [near/nearcore#4760]
Currently fuzzing in nayduck just writes in stdout the first failing scenario and it can be really large [http://nayduck.eastus.cloudapp.azure.com:3000/#/test/217190](http://nayduck.eastus.cloudapp.azure.com:3000/#/test/217190). We can utilise fuzzing minimising tool to reduce output size.

**Comment by bowenwang1996** [comment]
Is this fixed in #4759 ?

**Comment by posvyatokum** [comment]
Sort of, this certainly decreases the tasks priority, but minimised output would be helpful during debugging, because scenario won't have redundant transactions.
