### ISSUE TITLE
churn_attack::churn_attack is flaky

### ISSUE THREAD

**Issue by posvyatokum** [near/nearcore#4761]
https://buildkite.com/nearprotocol/nearcore/builds/3659#80bac2d4-3c8e-4754-a538-d466928dcc31

@bowenwang1996 please forward this issue in a right direction

**Comment by bowenwang1996** [comment]
@pmnoxx please take a look

**Comment by pmnoxx** [comment]
@bowenwang1996 That's a test which was run on `27th Aug`. We fixed a couple of bugs causing random failures related to `runner.rs`. At, that time, we didn't have proper debug logs, allowing us to pinpoint the issue. I'll close this PR as fixed, if that issue happens again, we can reopen it.
