### ISSUE TITLE
Migrate off clap2

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4764]
In nearcore, a bunch of crates uses `clap3`, and a bunch of crates uses `clap2`. As neard itself uses `clap3`, I think we should migrate everything else to it. The specific benefits are:

* no confusion about what to use for new tools
* better compile times (clap is pretty big, two claps are twice as big)
* easier to maintain code -- clap3 has derive API which makes adding or changing cli options much easier.

**Comment by bings47** [comment]
Hi, would like to try my hand at this issue if it's still open for contribution.

**Comment by bowenwang1996** [comment]
@bings47 sure. Assigned it to you

**Comment by bings47** [comment]
should I also bump the v3 version out of the beta version and into the latest one? Seems to be [3.1.6](https://github.com/clap-rs/clap/tree/v3.1.6) now

**Comment by matklad** [comment]
@bings47 probably makes sense to

* first upgrade all betas to proper v3
* then remove the remaining usages of v2
