### ISSUE TITLE
Set limit on top level account length on testnet

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4775]
We want to have a limitation on top level account length. It is configured using `AccountCreationConfig`. The desired configuration is:
```
{
  "min_allowed_top_level_account_length": 32,
  "registrar_account_id": "registrar"
}
```

You can see the desired condition [here](https://github.com/near/nearcore/blob/baafc663b572a7ced2b1600125f21e27e28dedb6/runtime/runtime/src/actions.rs#L349-L374).
  
It is set properly on mainnet. The problem is that on testnet `min_allowed_top_level_account_length` (let's define it as `length` from now) is incorrectly set to `0`, and we want to fix that. You can see it on the top of [testnet genesis file](https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json)

Another moment is that we want runtime configs to be the same for all -nets. This is not currently the case, because `AccountCreationConfig` is a part of runtime config.

I see two approaches to fix this.

## Testnet hardfork

We can simply dump the testnet state and start using mainnet runtime config there.

### Pros

Simple to implement

### Cons

* Genesis file grows from 5 GB to 14 GB. It takes 1.5 hours to load instead of 0.5 currently.

## Temporarily put `AccountCreationConfig` to `Genesis`and do protocol upgrade

If we want to avoid testnet hardfork, we can't simply unite `RuntimeConfig` for testnet and mainnet. This is because for all protocol versions before current one (47), we still have to keep the discrepancy in `length`.

The idea is we can actually simulate this discrepancy by copying `AccountCreationConfig` to `Genesis` which can be (and certainly is) different for testnet and mainnet. And then we can do a protocol upgrade U after which we again will take `AccountCreationConfig` from `RuntimeConfig`.

So, for testnet:
- before U, we take `length` from genesis which is 0
- after U, we take `length` from runtime config which is 32

For mainnet:
- before U, we take `length` from genesis which is 32
- after U, we take `length` from runtime config which is also 32, so it is not actually affected

Implementation plan
* Copy `AccountCreationConfig` to `Genesis` and pass it to `action_create_account` instead of the one taken from `RuntimeConfig`. Use 32 as default value for `length`, and set this value to 0 on each testnet node. For all other -nets, genesis remains the same.
* Start using the same `RuntimeConfig` for all -nets, by reintroducing https://github.com/near/nearcore/pull/4698
* Implement protocol upgrade taking `AccountCreationConfig` from `RuntimeConfig` again 

### Pros

Genesis file won't grow

### Cons

* Harder to implement, though don't expect that it will take >3 days
* Idea of moving config back and forth is not very natural and hard to explain, so unexpected pitfalls may occur here
* `AccountCreationConfig` will be unused in `Genesis` after the protocol upgrade
* Until protocol upgrade, we still will be able to create short top-level accounts

cc @bowenwang1996 @frol

**Comment by bowenwang1996** [comment]
@Longarithm thanks for the detailed analysis!

14GB is definitely too much. Let's go with the second option. How about we actually refactor the genesis config into something that we use for genesis and a separate protocol config, as described in #4447 ? I believe that may be less of a hassle

**Comment by Longarithm** [comment]
@bowenwang1996 I agree that it should be done, but could you elaborate on how it may help here?

Now we can just take account creation config from genesis, and there is no need to introduce a separate structure.

What else we can do is to have three separate structures:
- genesis config
- versioned account creation config for each -net
- runtime config

But this is also independent with removing protocol config from genesis config.

**Comment by Longarithm** [comment]
I also don't see how to avoid affecting `ApplyState`.

To put correct `AccountCreationConfig` to `action_create_account`, we need to access genesis. The last point where we have genesis is `NightshadeRuntime::process_state_update`, and the simplest option is to save `genesis_config.runtime_config.account_creation_config` to `ApplyState` and pass it through the whole sequence of calls to `action_create_account`.

We could also update the entire protocol config through the protocol upgrade, but then we have to leave in the code both old and new ways to get runtime configs (`ActualRuntimeConfig` and `RuntimeConfigStore`). And the whole structure we use for storing configs will again depend on the argument passed to constructor (`genesis_runtime_config` for `ActualRuntimeConfig`).

cc @matklad

**Comment by matklad** [comment]
>The problem is that on testnet min_allowed_top_level_account_length (let's define it as length from now) is incorrectly set to 0

Quick sanity check: do we have actual testnet accounts that break it? That is, what will break if we just make the change?

**Comment by Longarithm** [comment]
@matklad well, I created one to check that it is actually possible: https://explorer.testnet.near.org/accounts/sanchez

If we just make the change and someone decides to simulate blockchain including tx created this account, states diverge because the simulation will reject this tx.

**Comment by Longarithm** [comment]
UPD: Another simple option we see is to pass `min_allowed_top_level_account_length` to `RuntimeConfigStore`, and then make a protocol upgrade which will ignore this argument for newer versions.
