### ISSUE TITLE
Cost breakdown of EVM contract

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4776]
We would like to improve the cost of executing EVM contracts. However, to do so we need to know the main contributors to the gas cost. Fortunately, @ailisp recently added a change that exposes gas cost breakdown in the JSON RPC. @mfornet , Anton Paisov, @birchmd would need to reach out to @ailisp to learn how to use it and produce a report that shows the gas cost breakdown for a typical EVM transaction.

**Comment by birchmd** [comment]
@nearmax by "breakdown" do you mean like what is posted here? https://github.com/aurora-is-near/aurora-engine/discussions/226

It shows that the vast majority of the gas usage in in wasm execution, which from what I understand cannot be broken down further.

It's also worth noting that what contributes the most to the gas cost depends on the workload. For example deploying a solidity contract is mostly storage while executing something like uniswap (linked above) is almost exclusively computation.

**Comment by nearmax** [comment]
@birchmd . Thanks.

To double check, is this report saying that 86-88% is spent on pure Wasm operations (that is [regular_op_cost](https://github.com/near/nearcore/blob/master/nearcore/res/mainnet_genesis.json#L181)) or Wasm + host functions?

**Comment by birchmd** [comment]
Pure wasm, that's right. You can see the host function breakdown there as well. But pure wasm is 86% of the total

**Comment by nearmax** [comment]
Okay, these are good news. We know how to increase efficiency of pure Wasm and @ailisp is currently working on it. He is implementing a new gas injector that will make cost of single Wasm operation lower. However, to roll it out we would need an extensive testing because this change is very invasive (it transforms Wasm code). You could greatly speed up the roll out of this feature by implementing a replay of past transactions while checking that they consume the same amount of gas with old and new gas injector, see: https://github.com/near/nearcore/issues/4777

Closing this issue, since we have a breakdown now.
