### ISSUE TITLE
Replay of past transactions with new gas counter

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4777]
@ailisp is working on a new gas counter which will very likely make cost of executing pure Wasm cheaper than before. This might in turn benefit EVM execution a lot, since EVM contract is very computationally heavy. However, this change is extremely invasive, since it modifies Wasm instrumentation and host-guest Wasm interactions. For this change to be launched into the production we would need to have a significant confidence in its safety. One of the ways of achieving this confidence is re-running past transactions on Mainnet using new gas counter and ensuring that they burn exactly the same amount of gas as before (using old [regular_op_cost fee](https://github.com/near/nearcore/blob/master/nearcore/res/mainnet_genesis.json#L181)). While @ailisp is working on this change and writes special case tests, Aurora team could help us speed up the development by making a tool to rerun old transactions and compare burnt gas.

CC @matklad

**Comment by Longarithm** [comment]
@ailisp is there a chance that your change reduce loading the contract into memory ~30 times? 
This is the overhead of estimating the cost we have now: https://github.com/near/nearcore/issues/4660

**Comment by nearmax** [comment]
I would let @ailisp answer, but AFAIU it has no effect on contract loading speed.

**Comment by matklad** [comment]
>Aurora team could help us speed up the development by making a tool to rerun old transactions and compare burnt gas.

@nearmax I think the history replay tool was just implemented in 
https://github.com/near/nearcore/pull/4718.

**Comment by bowenwang1996** [comment]
Yeah as @matklad said, the tool has already been implemented by @nikurt. I believe what is left is for @ailisp to go through the entire mainnet (and ideally testnet as well) history to check that nothing breaks.

**Comment by nearmax** [comment]
Since Aurora wants to help @ailisp , it would be great if someone from their team used it to replay the mainnet and testnet and compare the burnt gas with the two counters. @mfornet @birchmd Could you guys do it?

**Comment by nearmax** [comment]
@bowenwang1996 Me and @olonho discussed @nikurt 's tool. I am not sure it does what we need it to do. @nikurt could you confirm the following:
* Can your tool replay all transactions from the genesis and arrive to **exactly the same state** that we have right now at the current block?
* When you process transactions from sequential blocks X, X+1, X+2, do we accumulate the state or we restart from an empty state on each block?

**Comment by bowenwang1996** [comment]
I believe @birchmd might be the best person to move this forward from Aurora side.

**Comment by birchmd** [comment]
I'm happy to include this in my tasks for next week. I am interested in the answer to Max's question above @nikurt 

I may need to sync with someone about accessing mainnet data. When that data will be needed depends on how much more development work is required for the replay tool @nearmax is asking for.

**Comment by ailisp** [comment]
Yeah I'm about to use this tool, Thank you for the information and the question @nearmax @birchmd have discussed are my concerns too.

> @ailisp is there a chance that your change reduce loading the contract into memory ~30 times?

@Longarithm I think it's quite unlikely. The change reduces contract execution by some X, but loading contract into memory - at first time it's about compilation; at subsequent time it's about deserialization - won't be helped from the change.

**Comment by nikurt** [comment]
The tool doesn't accumulate state.
In the current form the tool lets you re-apply transactions/receipts and examine the difference in max/avg/min gas used per chunk and per block.
The tool also doesn't validate if the transaction outcome is the same as the historical outcomes. Say, a historical chunk has two transactions, that decrease an account balance by some ammount and then increases it by the same amount. Say, replaying that chunk got the opposite result of transactions - increase then decrease (or a bigger decrease followed by a bigger increase). That change in the outcomes can't be detected if we only look at the historical state.

**Comment by ailisp** [comment]
> examine the difference in max/avg/min gas used per chunk and per block.

Cool! Check the gas usage difference might be sufficient for my use case, since I majorly want to check is new gas counter has consistent result as old one.

How much work will be to make this tool take state and replay a series of blocks, say from block N to some block N+M? And to compare state difference at every block N+i

**Comment by nikurt** [comment]
Replay from N to N+M is already supported. See https://github.com/near/nearcore/blob/master/test-utils/state-viewer/README.md . You can set `--start_index=N` and `--end_index=N+M`.

The tool already prints the existing ChunkExtra and the one it got during the replay: https://github.com/near/nearcore/blob/master/test-utils/state-viewer/src/main.rs#L421;L423 . It's just that the tool doesn't do any assertions about equality of ChunkExtra and doesn't print any statistics about how often they are the same or different.
If ChunkExtra are the same, the states should also be the same.

**Comment by olonho** [comment]
Regarding state accumulation. Just talked to @frol and he mentioned, that each transaction has Merkle trie root reference, and as it's persistent data structure (https://www.geeksforgeeks.org/persistent-trie-set-1-introduction/) it means that we automatically see versioned view of stored data. So the question is, if there's other state visible via database and not referred via the trie.

**Comment by bowenwang1996** [comment]
> if there's other state visible via database and not referred via the trie.

If you are talking about state in the sense of blockchain state, then no. There are other things we write to database, but the things that affect consensus are captured by `ChunkExtra` and there is an explicit comparison in the tool that @nikurt wrote.

**Comment by nearmax** [comment]
Assigning to @olonho since he was going to rerun transactions with Wasmer 2 anyway.

**Comment by joshuajbouw** [comment]
As per previous discussion, as far I was aware there is already a tool created for this?

**Comment by bowenwang1996** [comment]
@olonho please sync with @mina86 if you have questions about how to use the tool.

**Comment by nearmax** [comment]
Deprecated in favor of https://github.com/near/nearcore/issues/4911
