### ISSUE TITLE
Consider having the same protocol config for all chains

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4783]
We need to decide if we want to have some part of protocol configuration to be the same for all chains.

By protocol config, we currently mean `RuntimeConfig` containing runtime fees, VM limits, etc. But it also can be extended to some contents of `GenesisConfig`.

## Same protocol config

* Betanet and Testnet fully serve as a Mainnet test
* Simpler to maintain, less duplicated data, which mean lower probability of such issues https://github.com/near/nearcore/issues/4775

## Different protocol configs

* We may want to introduce chain-specific parameters later
* We may want to tune parameters specifically for some chains

To come to a decision, we may want to answer the question - when may we need to tune parameters specific for testnet, if testnet is assumed as a test copy of mainnet? Because, to check behaviour for other set of parameters, we can modify configs locally and run localnet.
  
P.S. 
There is also an adjacent topic how it should be stored: 
* Store only genesis protocol config and update it in code, like we do in `ActualRuntimeConfig`
* Store protocol config for each protocol version where it gets updated (or their diff)

The latter one personally seems more desirable, because it makes easier to answer the question "what is the field X for the protocol version V?".

**Comment by Longarithm** [comment]
Another argument for the same protocol config:

Some parameters by definition should be the same for all protocols. For example, `RuntimeFeesConfig` contains fees which corresponds to the number of executed instructions, which itself should not depend on the exact chain.

So we may want to store separate chain-specific and protocol-specific configs anyway.

**Comment by bowenwang1996** [comment]
Testnet should have the same protocol config as mainnet -- that was not the concern. The concern was that we may want to have some separate network for other things. For example, a local network where fees are different to test congestion or somesuch. Even in some of the tests we have today we modify genesis config to make it easier for testing.

**Comment by Longarithm** [comment]
In https://github.com/near/nearcore/pull/4779, we don't fully restrict ourselves. We still can create other stores and implement special command line flags to init runtime with other runtime configs store.
 
Overall the concern makes sense, though it seems there is no ideal solution.

Because there are no other concerns, closing for now.
