### ISSUE TITLE
Upgrading to 1.21.0 causes panic on backup node and appears to corrupt db

### ISSUE THREAD

**Issue by Pete-LunaNova** [near/nearcore#4792]
On one of our backup nodes the upgrade to 1.21.0 resulted in the following error message in the logs:

```
thread 'actix-rt|system:0|arbiter:4' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: ParseAccountError(TooShort, "") }', nearcore/src/lib.rs:336:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The node then gets stuck waiting for peers on block #47107551

Out other backup node experienced no such issues upgrading to 1.21.0

**Comment by janewang** [comment]
@Pete-LunaNova Thanks for submitting this bug. You mentioned that this issue was resolved. What was your solution on this issue. Please let us know. Thanks!

**Comment by bowenwang1996** [comment]
Looks like it is caused by `PeerManager::new`. This means that somewhere in the database you have stored a peer whose account id is not valid. I believe this was possible before this release, but should not be anymore going forward. So I think it is an one-off instance and no action item is needed.

**Comment by Pete-LunaNova** [comment]
@janewang As the db appeared to be corrupted after the panic, I deleted all the files in the data directory and restored them from a backup. The node then booted correctly again.
