### ISSUE TITLE
Move MIT and Apache licenses to their crates folders

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4798]
We need to avoid any confusion of MIT or APACHE license files being attributed to the entire nearcore. It is safer if we move them to the corresponding crates, even if it means we need to copy the files multiple times. 

This is regarding https://github.com/near/nearcore/pull/4732

**Comment by austinabell** [comment]
Should moving these licenses from the root directory and symlinking them to the respective folders be considered an option? Or is it preferred to have a copy in each of the directories?

_I'm not a lawyer_ :)
