### ISSUE TITLE
`make sandbox` fails at the final step due to missing `target/debug` directory

### ISSUE THREAD

**Issue by mieubrisse** [near/nearcore#4799]
**Describe the bug**
Following the steps at https://docs.near.org/docs/develop/contracts/sandbox fails because the `target` directory doesn't exist in `nearcore` so the last step of `make sandbox` fails like so:
```
mv sandbox/debug/neard target/debug/near-sandbox
mv: rename sandbox/debug/neard to target/debug/near-sandbox: No such file or directory
make: *** [sandbox] Error 1
```
Doing `mkdir -p target/debug` and rerunning `make sandbox` fixes the issue.

**To Reproduce**
1. Clone a clean `nearcore` repo
2. Run `make sandbox`

**Expected behavior**
Everything works and the binary shows up in `target/debug`

**Version (please complete the following information):**
Nearcore on commit hash `b84b3fcd`

**Comment by bowenwang1996** [comment]
@chefsale @ailisp could you take a look at this?

**Comment by thanhngvpt** [comment]
same issue
