### ISSUE TITLE
Improve navigation for pytest

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4800]
In `pytest/tests`, we implement lots of imports as follows:

```
 sys.path.append('lib')

import branches
 import cluster
 from utils import load_test_contract, get_near_tempdir
 ```

This complicates navigation, because CLion does't understand these imports.
 The following would work

```
 from pytest.lib import branches
 from pytest.lib import cluster
 from pytest.lib.utils import load_test_contract, get_near_tempdir
 ```

but we are running tests as `python tests/…` so nearcore nor pytest directories end up in sys.path. Imports like `from ...lib import cluster` lead to `ValueError: attempted relative import beyond top-level package`

We could possibly create a separate library `pytest-lib`, add it to requirements.txt and refactor tests correspondingly.

**Comment by mina86** [comment]
I don’t think creating a library is an ergonomic idea.  To add some context, there are two scenarios we need to handle: NayDuck running the tests and people running the tests manually. Dealing with the former is probably rather simple. We can change NayDuck to run set up `sys.path` or run tests as `python -m tests.subdir.test` but we probably still want to make it convenient to execute the tests for developers who just want a simple python invocation to work.

**Comment by bowenwang1996** [comment]
> we probably still want to make it convenient to execute the tests for developers who just want a simple python invocation to work.

Agree. That is pretty important
