### ISSUE TITLE
ActionCreateAccount measurement is volatile

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4802]
ActionCreateAccount measurement discrepancy sometimes exceeds 15% difference which we take as negligible. For example, difference in full measurement:

```
ActionCreateAccount: first=72283125000 second=59837125000 second/first=0.83
```

We may want to
- increase barrier of negligible difference
- make measurement more stable

**Comment by jakmeier** [comment]
This seems to be resolved since merging #7175 and #7197
