### ISSUE TITLE
Update bn borsh dependency

### ISSUE THREAD

**Issue by austinabell** [near/nearcore#4803]
https://github.com/near/nearcore/pull/4730#issuecomment-905803586 wasn't addressed in the PR so opening issue.

I don't have the context to answer this question or do anything more to consolidate the borsh versions so we don't have two different versions.

Options (feel free to edit to add any others):
- https://github.com/zeropoolnetwork/bn/pull/1 is pulled in and released (this is zeropool's repo)
- We have our own fork/release of this and have this change there

**Comment by bowenwang1996** [comment]
@snjax could you take a look at this? Thanks!

**Comment by bowenwang1996** [comment]
@snjax any updates on this? Thanks!

**Comment by snjax** [comment]
Hi @bowenwang1996, sorry for the late reply, the notification was lost.

https://crates.io/crates/zeropool-bn/0.5.10 published

**Comment by bowenwang1996** [comment]
@austinabell please take a look

**Comment by austinabell** [comment]
Completed with https://github.com/near/nearcore/pull/6196
