### ISSUE TITLE
Refactor: create a `PartId` struct

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#4806]
Create a struct
 `
 pub struct PartId 

 { idx: u64, total: u64, } 

`
 to be used in functions like `obtain_state_part` and other

**Comment by bowenwang1996** [comment]
Could you explain a bit more on what `idx` and `total` means as well as why we need this struct?

**Comment by mzhangmzz** [comment]
> Could you explain a bit more on what `idx` and `total` means as well as why we need this struct?

sorry I missed this. In functions such as `obtain_state_part` and `validate_state_part`, to specify a part we always specify both `part_id` and `num_parts` together, it'll be nicer if we create a struct for that

**Comment by Rishabhraghwendra18** [comment]
@mzhangmzz is this issue open ? If yes I will like to help here

**Comment by mzhangmzz** [comment]
@Rishabhraghwendra18 it is open. I just assigned it to you. Feel free to work on it
