### ISSUE TITLE
Compute the number of functions in Aurora EVM

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4814]
Contract Runtime team has found out that the cost of loading Wasm contract into memory (at the beginning of contract invocation) depends not only on the size of the contract in bytes, but on the number of Wasm functions (not just contract methods). This discovery will likely introduce a new fee that will adjust the cost of calling the contract based on the number of functions in it. While it is however possible that @olonho through his work on improving Wasmer will make this fee inconsequential, that current state is that this fee is quite significant according to @Longarithm and @matklad .

We need to know how many functions does Aurora EVM have so that we can plan accordingly if we find out that this new fee will make Aurora EVM execution prohibitively expensive.

**Comment by Longarithm** [comment]
I think the following computation of function number should work:
```
let contract_code = ContractCode::new(code.to_vec(), None);
let module = cache::wasmer0_cache::compile_module_cached_wasmer0(&contract_code, &VMConfig::default(), None);
let module_info = module.info();
println!("{}", module_info.func_assoc.len());
```

**Comment by joshuajbouw** [comment]
We will look into it this week.

**Comment by birchmd** [comment]
The output from @Longarithm 's suggested method of counting is 1280.

See https://github.com/aurora-is-near/aurora-engine/pull/265

**Comment by joshuajbouw** [comment]
Closing as 1280 is what we got.
