### ISSUE TITLE
runtime-tester is sensitive to account names for some reason

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4835]
If I change this line

https://github.com/near/nearcore/blob/3080cf7d305c8e1d25d09d378c7f0ab1f841ec27/test-utils/runtime-tester/src/lib.rs#L23

to use any other account name, like `format!("best_{}", i)`, the test starts to fail. This seems odd -- it should be possible to use different account names.

**Comment by matklad** [comment]
cc https://github.com/near/nearcore/issues/4771#issuecomment-921375049

**Comment by mina86** [comment]
The issue is with `TestEnv::new_with_runtime_and_network_adapter` assuming the format.

**Comment by bowenwang1996** [comment]
@mina86 do you want to fix this?

**Comment by mina86** [comment]
I can take it, sure.
