### ISSUE TITLE
refactor: replace `Arc<Store>` with `Store` throughout the codebase?

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4837]
We use `Arc<Store>` a bunch. But the Store is defined as 

https://github.com/near/nearcore/blob/3080cf7d305c8e1d25d09d378c7f0ab1f841ec27/core/store/src/lib.rs#L48-L52

Ie, it is already an `Arc`. I don't think there can be a conceivable reason for a double indirection.

*However*, I see that `#[derive(Clone)]` was a late addition: 

https://github.com/near/nearcore/pull/3310/files#diff-bc42e726bca3d291bcb277ae2857c8dd36ae5831d1190902b12082d74bc6e302R47

So maybe it's that derive that is wrong? Looking at the code, it seems that Clone is fine:

* there are no store methods which require exclusive access 
* `create_store` already creates an `Arc`, so we never even *have* exclusive access to the store. 

So I suggest replacing all `Arc<Store>` with just `Store`. While we are at it, we have a bunch of `get_store(&self) -> Arc<Store>` methods. I think a more idiomatic signature for those would be `store(&self) -> &Store`.

**Comment by matklad** [comment]
cc @mzhangmzz

**Comment by pmnoxx** [comment]
@matklad https://github.com/near/nearcore/pull/5906
