### ISSUE TITLE
Add opening span in runtime logging

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4839]
Currently inside runtime we use `debug_span` for debug logging. However, as @matklad pointed out, we only configured tracing to log closing span instead of opening span and this makes it harder to gather useful information when a node crashes inside runtime.

**Comment by matklad** [comment]
Link to source: https://github.com/near/nearcore/blob/9b99fcca620db67042e48c305d5fd976895b71de/neard/src/cli.rs#L370-L373

**Comment by matklad** [comment]
Fixed by #4916
