### ISSUE TITLE
Remove `impl Default for RuntimeConfig`

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4870]
We currently have this impl:

https://github.com/near/nearcore/blob/f78ed5048bbb11a9d2f722f29420aef4266ead2e/core/primitives/src/runtime/config.rs#L29-L40

I think this impl is wrong -- `RuntimeConfig` makes sense only in the context of a specific protocol version. We should always get `RuntimeConfig` from `RuntimeConfigStore`.

**Comment by Longarithm** [comment]
Part of work was done here https://github.com/near/nearcore/pull/4891
We also need to do the same for VMConfig and ExtCostsConfig.

**Comment by Longarithm** [comment]
Done. Only `AccountCreationConfig::default()` is left but it does have the same values for all current usecases (probably except some tests).
