### ISSUE TITLE
Historical uptime for validators is tracked

### ISSUE THREAD

**Issue by janewang** [near/nearcore#4967]
For testnet and mainnet, we aim to recruit and retain the best validators. To understand validator's uptime performance, we aim to track historical uptime for each validator across epochs and to monitor the validators' performance. This work is a step in preparing for incentivized testnet, where validators compete for best uptime. The second goal is to track the validators uptime performance on mainnet, including the current active validators.

**Comment by bowenwang1996** [comment]
@marcelo-gonzalez I think this is done. Please reopen if it is not
