### ISSUE TITLE
Failed to start Archive node from backup data

### ISSUE THREAD

**Issue by jsvisa** [near/nearcore#4974]
**Describe the bug**
Please provide a short description of the bug.

I'm following [Run an Archival Node without nearup | NEAR Documentation](https://docs.near.org/docs/develop/node/archival/run-archival-node-without-nearup#mainnet) to run an Archive node, after replace the data from https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/archive/data.tar, the node failed to start, log as below:

```bash
Oct 10 13:26:14.797  INFO neard: Version: 1.21.0, Build: 20545ae0, Latest Protocol: 47
Oct 10 13:26:14.806  INFO near: Opening store database at "/home/amber/.near/mainnet/data"
Oct 10 13:26:15.057 ERROR near: DB version 27 is created by a newer version of neard, please update neard or delete data
```
According to the logs, it looks like the data.tar archived in AWS S3 running a newer node?

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

Success to run the archive node.

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**

**Comment by bowenwang1996** [comment]
Closing as it is obsolete
