### ISSUE TITLE
Duplicate lockfile

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4987]
Unless I am missing something, there's no reason for this lockfile to exist

https://github.com/near/nearcore/blob/5a89698df35f2d11f26bfcd8123c5248e2d910c5/chain/jsonrpc/test-utils/Cargo.lock

we should make sure that the corresponding crate is a part of the workspace.

**Comment by bowenwang1996** [comment]
cc @frol

**Comment by frol** [comment]
I see. If that is not that easy as I suggested (just remove the file), I will ask @miraclx to bring it back to life while he will be working on other issues related to fuzzing jsonrpc.
