### ISSUE TITLE
Add basic test to the current CI workflow that the node can init and run

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#4993]
Betanet CI got broken on the latest betanet release, as it is unable to run with default config. 

For the repro and more information take a look at: https://github.com/near/nearcore/issues/4992. Once fixed we should add a test to CI to make sure this doesn't break anymore. cc: @mina86 @mzhangmzz @bowenwang1996

**Comment by mina86** [comment]
What I don’t get is that we already spin three separate clusters
executing `tests/sanity/backward_compatible.py`,
`tests/sanity/upgradable.py` and `tests/sanity/db_migration.py`.
Granted, they use `./neard testnet` rather than `init` but as far as
number of shards goes the two behave the same.

**Comment by chefsale** [comment]
Seems like this issue was only for nightly build, so that seems missing.
