### ISSUE TITLE
Indexer for Explorer doesn’t stop when signal is sent

### ISSUE THREAD

**Issue by mina86** [near/nearcore#4994]
Reproduction steps:
1. Start the indexer.
2. Send SIGINT to it.
3. Observe indexer continue to run.

The issue is observable in near-indexer-for-explorer but fix will likely need to be made in nearcore.

This is separated from https://github.com/near/nearcore/issues/4937 so each issue tracks a single issue.

**Comment by bowenwang1996** [comment]
@khorolets any updates on this?

**Comment by khorolets** [comment]
> @khorolets any updates on this?

Oh, sorry I've completely forgot about this issue. It's working and should be closed.
