### ISSUE TITLE
Failed to create account "account-name" in 10 retries due to nonce

### ISSUE THREAD

**Issue by idirall22** [near/nearcore#5043]
***Describe the bug***
 The issue happens when I try to create a new user account in the rainbow-bridge

***To Reproduce***
 clone [https://github.com/aurora-is-near/rainbow-bridge](https://github.com/aurora-is-near/rainbow-bridge)
 1\. yarn
 2\. ./cli/index.js clean
 3\. ./cli/index.js prepare
 4\. ./cli/index.js start near-node
 5\. ./cli/index.js start ganache
 6\. ./cli/index.js init-near-contracts
 7\. ./cli/index.js init-eth-ed25519
 8\. ./cli/index.js init-eth-client
 9\. ./cli/index.js init-eth-prover
 10\. ./cli/index.js init-eth-erc20
 11\. ./cli/index.js init-eth-locker
 12\. ./cli/index.js init-near-token-factory <------ ERROR

***Expected behavior***
 Account created successfully.

***Screenshots***
 [https://pastebin.com/9HR5ySdA](https://pastebin.com/9HR5ySdA)

***Version (please complete the following information):***

*   nearcore: version=1.22.0 - deploy=fb1e62168693bd995fa59265209cc89ea184c374
*   rust and cargo versions
     rustc 1.55.0 (c8dfcfe04 2021-09-06)
     cargo 1.55.0 (32da73ab1 2021-08-23)
*   local

**Comment by telezhnaya** [comment]
Hey!
Please update to the latest version and feel free to re-open if it's still an issue for you
