### ISSUE TITLE
Querying historical transaction status should be compatible with re-sharding

### ISSUE THREAD

**Issue by frol** [near/nearcore#5047]
_**Describe the problem**_ 

**While this issue roots down to view-client, I will describe it from JSON RPC point of view.**

Currently, the `tx` endpoint <span class="error">[expects transaction hash and a signer account id]</span>([https://docs.near.org/docs/api/rpc/transactions#transaction-status](https://docs.near.org/docs/api/rpc/transactions#transaction-status)), which is not sufficient given that we use signer account id to map to a shard id which might be different given re-sharding will split the state differently and the same account can move between shards from one epoch to another. @bowenwang1996 suggested to also require to specify epoch id (and assume it is the current epoch if not specified).

@bowenwang1996 Ideally, I would love to ask the chain team to implement the optional epoch_id support on view-client level, and the node interfaces team to take it from there and upgrade JSON RPC implementation.

 _**To Reproduce**_ 

This command does not use valid transaction hash and signer id, so it is just for demo purposes:

 $ http post [https://rpc.testnet.near.org](https://rpc.testnet.near.org)([https://rpc.testnet.near.org](https://rpc.testnet.near.org)) jsonrpc=2.0 id=dontcare method=tx params:='[ "6zgh2u9DqHHiXzdy9ouTP7oGky2T4nugqzqt9wJZwNFm", "sender.testnet"]'

Would you need to find some transaction from a signer account that got re-sharded to some other shard later, the node that is processing the request will route the request to a wrong shard.

 _**Expected behavior**_ 

Historical transaction status should be available no matter what.

**Comment by frol** [comment]
@bowenwang1996 Indeed, it does not affect nodes that track all shards, and that is the current state of things, but when we move on from it, both RPC and archival nodes will be affected. Thus, it is not pressing at the moment, but it is good to keep it in mind.

**Comment by wacban** [comment]
@shreyan-gupta I agree that we're good to go with resharding. However would this issue still be relevant for the state sync rollout when chunk only producers stop tracking all shards? cc state sync team @nikurt @VanBarbascu @telezhnaya I'll leave it to you to either re-open this issue and take ownership, track it separately or leave it as is if irrelevant
