### ISSUE TITLE
Node should not corrupt its state on exit

### ISSUE THREAD

**Issue by frol** [near/nearcore#5050]
**Describe the bug**

We received 3 reports today that our partner Indexer nodes got corrupted after node was aborted with

https://github.com/near/nearcore/blob/0c9ad79a18e431f843e6123cf4559f9c2c5dd228/chain/client/src/client.rs#L1032-L1034

![image](https://user-images.githubusercontent.com/304265/138175638-e9bf6385-eb38-4120-8bda-8befb1fcbdc2.png)

After they recompiled the node with the newer nearcore, they could not boot the node back again:

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/ubuntu/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/fb1e621/chain/epoch_manager/src/lib.rs:1193:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'The lock was poisoned.: PoisonError { .. }', /home/ubuntu/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/fb1e621/nearcore/src/runtime/mod.rs:993:69
thread '<unnamed>' panicked at 'The lock was poisoned.: PoisonError { .. }', /home/ubuntu/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/fb1e621/nearcore/src/runtime/mod.rs:1042:69
thread '<unnamed>' panicked at 'The lock was poisoned.: PoisonError { .. }', /home/ubuntu/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/fb1e621/nearcore/src/runtime/mod.rs:1042:69
thread '<unnamed>' panicked at 'The lock was poisoned.: PoisonError { .. }', /home/ubuntu/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/fb1e621/nearcore/src/runtime/mod.rs:1042:69
thread 'main' panicked at 'assertion failed: queue.send(msg).is_ok()', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/sync.rs:161:25
```

**To Reproduce**

Probably, you need to let the node that does not support newer protocol version to run over the protocol upgrade, so it hits the condition.

**Expected behavior**

nearcore should not corrupt its database and should be able to boot fine after this abort.

**Version (please complete the following information):**
- nearcore commit/branch: 4dbc9f8bbe88c8d2b64a557ecae285fbe568710f
- testnet

**Comment by mina86** [comment]
Closing in favour of https://github.com/near/nearcore/issues/5340 as it’s the same underlying cause.
