### ISSUE TITLE
Centralize documentation for nearcore devlopers

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5079]
Today we have [https://docs.near.org/docs/community/contribute/contribute-nearcore](https://docs.near.org/docs/community/contribute/contribute-nearcore) and [https://github.com/near/nearcore/blob/master/CONTRIBUTING.md](https://github.com/near/nearcore/blob/master/CONTRIBUTING.md) with duplicated content. I feel we should have single-source-of-truth here.

Assuming that the purpose of having nearcore dev docs at docs.near.org is to funnel contract developers into nearcore, I think we should re-target docs there to be pointers into the docs in the repo. Ie, at [https://docs.near.org/docs/community/contribute/contribute-nearcore](https://docs.near.org/docs/community/contribute/contribute-nearcore) it makes sense to talk about good-first-issues, getting rust installed and the overall process of creating a github pull request. It doesn't make sense to explain how to speed up compile times or how to enable logging – that detailed info should be moved into this repository.

**Comment by Rishabhraghwendra18** [comment]
Hi @bowenwang1996 . I will like to work on this issue

**Comment by bowenwang1996** [comment]
@Rishabhraghwendra18 feel free to submit a PR!

**Comment by Rishabhraghwendra18** [comment]
@bowenwang1996 I have opened an issue in the repo regarding setting Up the local development environment few days back , see #5735 . It will also have the instructions to build the repo so do we include same those steps here too ? If we did then I think we need to update the same steps at two places if our setting up environment steps change.

**Comment by matklad** [comment]
superceeded by #7670 and mostly fixed at this point
