### ISSUE TITLE
Epoch manager should work without caches

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#5080]
While investigating #5074, I noticed that if I set the size of block cache in epoch manager to 1, some tests would break

 ---- process_blocks::test_gc_long_epoch stdout ----
 thread 'process_blocks::test_gc_long_epoch' panicked at 'Err(Error 

 { inner: DB Not Found Error: 42qLuuDARf733d3XYRPHSYmhmFQuwp6soXANFuxGY3u9 } 

)', chain/client/src/test_utils.rs:1272:9
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

We should make sure that epoch manager works regardless of the cache size.

**Comment by mooori** [comment]
Running the following test resulted in failures for values `BLOCK_CACHE_SIZE <= 3` (in `epoch_manager.rs`).

```
cargo test -p integration-tests --features no_cache test_gc_long_epoch
```

#### Where occurs the error?
In `EpochManager.get_block_info()` when `BlockInfo` is not in the cache and the attempt to retrieve it from `Store` returns `Ok(None)`.

This is triggered by `Client` in `TestEnv` processing a block.

The error which causes the test to fail contains the hash of the block whose `BlockInfo` couldn't be retrieved from `Store`.

Strangely, however, that `BlockInfo` actually was saved to `Store` _before_ trying to retrieve it.

This can be observed by printing the hash when saving `BlockInfo` to `Store` in `EpochManager.save_block_info()`. (Failure occurs early, so there aren't many logs to skim through.)

#### Thoughts
Maybe there's a delay before a saved `BlockInfo` can be retrieved from `Store`? Then, for a cache size `<= 3` the `Store` is queried _before_ that delay passed, whereas with a larger cache `Store` is queried only _after_ the delay.

Or maybe someone has another idea?
