### ISSUE TITLE
Nightly protocol runtime config includes wrong regular_op_cost

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5094]
This line is wrong:

https://github.com/near/nearcore/blob/5cbb3a386c59601914b6b3d3332e6ce336a0d8dc/nearcore/res/runtime_configs/123.json#L154

It should say this instead:

https://github.com/near/nearcore/blob/5cbb3a386c59601914b6b3d3332e6ce336a0d8dc/nearcore/res/runtime_configs/48.json#L154

This'll probably get caught once https://github.com/near/nearcore/issues/4961 is implemented. But I wonder if we should improve, mid-term, how we represent config changes? 

Configuration bugs are notorious for causing outages, this is the evidence that "let's just dump config to JSON"  is not fool-proof enough. 

I think it makes sense to refactor the code to allow storing just diffs, which explicitly say "we change from *this* value to *this* value". 

I am also 0.7 sure that for source of truth for costs, we should switch from JSON to plain-text readable format from estimator:

https://github.com/near/nearcore/blob/master/runtime/runtime-params-estimator/costs.txt

 but that is blocked on #4633

**Comment by matklad** [comment]
@Longarithm  Closed?

**Comment by Longarithm** [comment]
Yeah, the cost is fixed. I will come back to storing diffs later

**Comment by Longarithm** [comment]
Regarding diffs: today I found that `max_transaction_size` field is taken as default value. If I want to put it into config, I have to put it into each config instead of only the first one.
