### ISSUE TITLE
`pytest sanity/garbage_collection_sharding_upgrade.py` is broken

### ISSUE THREAD

**Issue by mina86** [near/nearcore#5095]
As seen in nightly NayDuck runs, the `pytest sanity/garbage_collection_sharding_upgrade.py` test is broken, e.g.: <[http://nayduck.near.org/#/test/237383](http://nayduck.near.org/#/test/237383)> and <[http://nayduck.near.org/#/test/237509](http://nayduck.near.org/#/test/237509)>.

Variant of the test using regular build has failed three out five times with node reporting:

 ERROR client: Storage Validation failed, [ErrorMessage { col: "ColChunkExtra", key: "(`7Y21nL3uoNDfvpKp2XGRSLXyL6fZM7dYYnKbXoKDjRne`, ShardUId 

 { version: 1, shard_id: 0 } 

)", err: DBNotFound 

 { func_name: "chunk_extra_block_exists", reason: "Can't get Block from DB" } 

 }, ErrorMessage { col: "ColChunkExtra", key: "(`7Y21nL3uoNDfvpKp2XGRSLXyL6fZM7dYYnKbXoKDjRne`, ShardUId 

 { version: 1, shard_id: 1 } 

)", err: DBNotFound 

 { func_name: "chunk_extra_block_exists", reason: "Can't get Block from DB" } 

 }, ErrorMessage { col: "ColChunkExtra", key: "(`7Y21nL3uoNDfvpKp2XGRSLXyL6fZM7dYYnKbXoKDjRne`, ShardUId 

 { version: 1, shard_id: 2 } 

)", err: DBNotFound 

 { func_name: "chunk_extra_block_exists", reason: "Can't get Block from DB" } 

 }, ErrorMessage { col: "ColChunkExtra", key: "(`7Y21nL3uoNDfvpKp2XGRSLXyL6fZM7dYYnKbXoKDjRne`, ShardUId 

 { version: 1, shard_id: 3 } 

)", err: DBNotFound 

 { func_name: "chunk_extra_block_exists", reason: "Can't get Block from DB" } 

 }]

Variant of the test using nightly_protocol,​nightly_protocol_features build has never succeeded and fails on a debug assert in `core/primitives/src/types.rs:567`:

 impl ValidatorStake {
 /* … */
 pub fn into_v1(self) -> ValidatorStakeV1 {
 match self {
 Self::V1(v1) => v1,
 #<span class="error">[cfg(feature = "protocol_feature_chunk_only_producers")]</span>
 Self::V2(v2) => {
 // This function should never be called on a V2 variant, it
 // is only for backwards compatibility purposes.
 /* ❗ */ debug_assert!(false);
 ValidatorStakeV1 

 { account_id: v2.account_id, public_key: v2.public_key, stake: v2.stake, } 

 }
 }
 }
 /* … */
 }

**Comment by shreyan-gupta** [comment]
Deleted tests in https://github.com/near/nearcore/pull/10138
