### ISSUE TITLE
Database snapshot corrupt (s3 hosted, testnet)

### ISSUE THREAD

**Issue by JonathanLogan** [near/nearcore#5098]
**Describe the bug**
neard fails to load official data snapshot due to data corruption. neard then exits.

**To Reproduce**
wget https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/rpc/data.tar
tar -xf data.tar -C /near/data/
neard

**Expected behavior**
neard should load database snapshot and begin listening to network.

**Screenshots**
Oct 28 20:19:06.529  INFO neard: Version: 1.22.0-rc.3, Build: 127ea66aa, Latest Protocol: 48
Oct 28 20:20:37.201  INFO near: Opening store database at "/home/near/data"
thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "Corruption: SST file is ahead of WALs" })', core/store/src/lib.rs:297:42

**Version (please complete the following information):**
- nearcore commit/branch: Version: 1.22.0-rc.3, Build: 127ea66aa
- rust version: 1.56.0
- docker: 20.10.9
- net: testnet 

**Additional context**
Tried both on 2021-10-27 1500 CET and 2021-10-28 2200 CET.
Error does not appear on mainnet with mainnet rpc data and 1.21.0.

**Comment by pietroblandizzi** [comment]
We also have the problem that if you stop the node and start it again it says:
```
Nov 02 11:31:13.567  INFO near: Did not find "/home/near/.near/testnet/data" path, will be creating new store database
```
it deletes all the data and start from scratch syncing.

**Comment by mhalambek** [comment]
This looks like a temporary glitch, tested it out today.
Download mainnet rpc backup.
Node started and downloading blocks.

**Comment by mhalambek** [comment]
Reproduced it, still checking two other pairs mainnet/archive and testnet/archive
testnet/rpc backups is corrupted, identified the issue, working on a fix, will post here when done

**Comment by DDeAlmeida** [comment]
> Reproduced it, still checking two other pairs mainnet/archive and testnet/archive testnet/rpc backups is corrupted, identified the issue, working on a fix, will post here when done

Thank you.
Many member of OSA got this error too.

Thank for your work :)

**Comment by janewang** [comment]
Hi @mhalambek, is there an update on this issue of the snapshots being corrupt? Thank you!

**Comment by DDeAlmeida** [comment]
> Hi @mhalambek, is there an update on this issue of the snapshots being corrupt? Thank you!

Did you have some news about this issue ?

**Comment by bowenwang1996** [comment]
I think it is fixed. @mhalambek please confirm

**Comment by kucharskim** [comment]
How do you guys generate snapshots?

**Comment by frol** [comment]
I think it is resolved now and the backups are not in .tar archives anymore: https://docs.near.org/docs/develop/node/intro/node-data-snapshots

**Comment by kucharskim** [comment]
How do you guys generate snapshots?

**Comment by Longarithm** [comment]
It means that DB is corrupted, perhaps latest DB migration already increased DB version but it was interrupted very soon and didn't create these new mentioned column families at all. The easiest solution is to download fresh DB snapshot.
