### ISSUE TITLE
Don't rely on default features when validating wasm

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5105]
Wasm is a living spec and new features are introduced from time to time. For us, it's important to know exactly which features are introduced when. Today, we just rely on defaults from upstream libraries:

* here, we pass `None` as the config: 
  https://github.com/near/nearcore/blob/1cb995fa77664da5fb22c1ad6b0b81a4d8deecca/runtime/near-vm-runner/src/prepare.rs#L18
* and here, we are not calling `.features`, which again make us rely on defaults:
  https://github.com/near/nearcore/blob/1cb995fa77664da5fb22c1ad6b0b81a4d8deecca/runtime/near-vm-runner/src/wasmer2_runner.rs#L321

We should change both call-sites to explicitly list the features we use. 

I believe this is the config we happen to use today:

```rust
    OperatorValidatorConfig {
        enable_threads: false,
        enable_reference_types: false,
        enable_simd: false,
        enable_bulk_memory: false,
        enable_multi_value: false,
 };
```

Ie, we happen to correctly not to enable any features. 

While we are at it, we should add explicit tests to make sure that attempts to use such features break.

**Comment by nagisa** [comment]
So, after some investigation, the configurations that we do use are definitely not consistent. First of all, both `near-vm-runner` and `wasmer` use `wasmparser`. However the versions of `wasmparser` used are different (`near-vm-runner` uses `0.51` and `wasmer` utilizes the `0.78` release instead.

I'm not sure quite yet what's the reason behind the double verification (maybe we could remove one of those?) but for now it is pretty apparent to me that the defaults are different between the two validators.

The `wasmparser::validate(original_code, None)` does indeed validate with the following configuration, 

```rust
OperatorValidatorConfig {
        enable_threads: false,
        enable_reference_types: false,
        enable_simd: false,
        enable_bulk_memory: false,
        enable_multi_value: false,
        #[cfg(feature = "deterministic")]
        deterministic_only: true,
}
```

And then wasmer validates with the following configuration:

```rust
WasmFeatures {
    bulk_memory: true,
    threads: false,
    reference_types: true,
    multi_value: false, // This is, I believe, required to be false for the singlepass codegen
    simd: true,
    tail_call: false,
    module_linking: false,
    multi_memory: false,
    memory64: false,
    exceptions: false,
    deterministic_only: false,
}
```

The good thing, I guess, is that the mismatch here isn't terribly nonsensical. Provided both verifications are run every time (which seems to be the case AFAICT) the modules will be filtered out to have pretty much every optional wasm feature disabled. That is, even if the `wasmer` allows use of `simd` our own validation pass will disallow it.

One slightly concerning thing to me is that the `deterministic_only` can become `true` if the (currently off) `deterministic` feature of `wasmparser` gets enabled somehow.

I would propose to proceed here by first making sure `wasmparse` version between `wasmer` and `near-vm-runner` is the same. Then we would specify the following featureset

```
WasmFeatures {
    bulk_memory: false,
    threads: false,
    reference_types: false,
    multi_value: false,
    simd: false,
    tail_call: false,
    module_linking: false,
    multi_memory: false,
    memory64: false,
    exceptions: false,
    deterministic_only: false,
}
```

which matches the features we enable today (provided all modules always go through both verification calls)

**Comment by matklad** [comment]
Yeah, the plan looks good to me! I guess I would maybe start with adding some explicit tests for not-enabled features, so that it's easy to see that the refactor is correct.

Couple of potentially related things:

* between our validation and wasmer, we also run instrumentation via pwasm, and that might impose it's own limits
* there's also an issue of implementation limits, which feel similar. Don't think we should do anything about them, except being aware that they exist: 

https://github.com/bytecodealliance/wasm-tools/blob/ee019ce8dbca59db1825e9f11c1fe8ac128f3240/crates/wasmparser/src/limits.rs#L16-L40

**Comment by matklad** [comment]
Also, figuring out if maybe we should specify `deterministic: true` is an obvious follow-up.

**Comment by matklad** [comment]
>Potentially by going through wasmer for validation at all times.

Oh, this bit I am unsure about -- in an ideal world, validation would be independent of the engine, which would allow for swapping the engines. So, we'd validate wasm in the same way, and then run it using some kind of `new_unchecked` function from a specific engine, or maybe run the second validation, but then assert that the results are consistent.
