### ISSUE TITLE
Upgrade openssl dependency

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5109]
Looks like newer version of OpenSSL fails to build for us:

https://buildkite.com/nearprotocol/nearcore/builds/5849#f832f30a-7d82-40da-9f0a-1c25d52990f0/83-680

THe culprit seems to be https://github.com/openssl/openssl/issues/14541 -- open-ssl now requires some core perl libraries to build, and, apparently they are not installed on the builders. 

This should be the fix:

>on Linux distributions based on RPMs, you will need to install perl-core rather than just perl.

I don't know where the fix should be applied though. What are we using to configure the machine running the pipeline, the dockerfile in the repo? 

https://github.com/near/nearcore/blob/af64bfbf9860535ceb70299448d0434185550835/Dockerfile#L44-L46

That `libssl-dev` line seems suspicious to me. Why would we need an openssl *dev* package at runtime, if we vendor openSSL and link it in statically? 

https://github.com/near/nearcore/blob/af64bfbf9860535ceb70299448d0434185550835/chain/telemetry/Cargo.toml#L9

**Comment by matklad** [comment]
Let me formulate the last part as an explicit sanity check question:

* Should we build our own copy of OpenSSL and link to it statically, or
* Should we dynamically link system's of OpenSSL?

I think we should do the former. If that's the case, I don't understand why we need `libssl-dev` package. 

cc @mm-near (are you the right person to cc for "how things are supposed to work in a big way?" questions?)

**Comment by chefsale** [comment]
Created a PR to upgrade: https://github.com/near/nearcore/pull/5565, after issues with CI resolved.

**Comment by matklad** [comment]
Status: it seems like openssl 3.0.0 still has some problems to iron out, and, as 1.1.1 is still supported, we'll stick to that for now. cc https://github.com/sfackler/rust-openssl/issues/1576#issuecomment-990304892
