### ISSUE TITLE
near-cli marks transaction as `Expired` from out of sync nodes

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#5119]
I've also got errors from `near-cli` that marks transaction as `Expired`:

E.g. `ServerError: Transaction has expired`

I think the reason is the node is out of sync and rejects the transaction with the blockhash that is recent, but not synced yet.

I suggest to reply from such nodes with a different error. E.g. `OutOfSync` RPC error, so a client can retry the request to a different RPC node.

_Originally posted by @evgenykuzyakov in https://github.com/near/nearcore/issues/5112#issuecomment-958292477_

**Comment by bowenwang1996** [comment]
@frol please take a look

**Comment by mina86** [comment]
> I suggest to reply from such nodes with a different error. E.g. OutOfSync RPC error, so a client can retry the request to a different RPC node.

How would node know the difference between recent but not synced block and a block that does not exist? We cannot rely on node-side solution only. We will need load balancer to look at the entire fleet of RPC nodes and determine this way which are unhealthy.
