### ISSUE TITLE
Stucking and cannot create any transactions due to not enough balance error

### ISSUE THREAD

**Issue by hmtri1011** [near/nearcore#5128]
**Describe the bug**
Near wallet keeps throwing "Error: Access Key {account_id}:{public_key} does not have enough balance" even though I am pretty sure that I have enough balance.

This error happened 2 days ago and up to now, I cannot use any dApps in NEAR blockchain because the transaction always failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16288424/140126432-5739e0cd-579e-4cac-bcc7-38175fbbca8c.png)

![image](https://user-images.githubusercontent.com/16288424/140128429-95f8260d-4148-47c9-b8b1-ca36592c1b5e.png)
This is an error response from RPC

Any help would be appreciated, because with this error, I cannot do anything in NEAR (stake/unstake, transfer token, IDO, swap, ....)

Thanks in advance!

**Comment by bowenwang1996** [comment]
How are you sure that you have enough balance? It is possible that you depleted your access key allowance.

**Comment by hmtri1011** [comment]
Hi @bowenwang1996,  thanks for your reply.
I have around 100 NEAR in my wallet balance, so I'm sure that is enough.
I have no idea what is `access key allowance` so I cannot delete it.
I'm just a normal user that uses dApps in NEAR, it used to be okie. But 2 days ago, not sure what is going wrong with my wallet, I cannot use or integrate with any dApps (REF, Near Wallet, Metapool), cannot un-stake/claim/transfer token either.

That's why I created this issue just to request some help.

**Comment by hmtri1011** [comment]
Any help would be appreciated because up to now I cannot do anything with my wallet. I have a huge amount of NEAR tokens in my wallet (from Metapool, REF, and Near Wallet) and I cannot do anything with them. Hmm, so stressful now.

**Comment by bowenwang1996** [comment]
It would be helpful if you can provide your account and the access key you used for us to look into the issue.

**Comment by hmtri1011** [comment]
Thanks, I cleared browser cache to sign out Near wallet then login again and the issue is gone.
