### ISSUE TITLE
Rosetta does not allow to withdraw all available funds 

### ISSUE THREAD

**Issue by asmolarek-bc** [near/nearcore#5129]
The situation is that I have an account with 500 NEAR and I am creating transaction to withdraw all the funds, rosetta instead of creating a transaction that will transfer 500 NEAR is creating transaction that transfers less funds, which is understandable because it has to leave funds for storage

What is wrong is:

According to storage_amount_per_byte that is returned from node via near rpc what is left on the account should be 0.00182N
But the leftovers is around 0.0165438N 

which matches the storage_amount_per_byte value to be 9.09 * 10^19 * 182

from this it looks like rosetta rpc is picking different value for storage_amount_per_byte that near rpc is

Version (please complete the following information):

nearcore tag 1.21.0
rustc 1.51.0
rustup 1.24.3 (ce5817a94 2021-05-31)
cargo 1.51.0
docker Docker version 20.10.8, build 3967b7d
local env with local network

node was compiled with --features rosetta_rpc and started with rosetta api enabled in conf file

**Comment by bowenwang1996** [comment]
@frol could you take a look?

**Comment by frol** [comment]
@asmolarek-bc What do you mean by leftovers? Is this the value you *observe* after the transfer? This should not be allowed by the protocol, so this all sounds like your localnet genesis has the storage price set to 9.09 * 10^19.

**Comment by asmolarek-bc** [comment]
By leftover I mean funds that are kept on the account when I am trying to withdraw everything, for some reason when I am asking rosetta construction API to prepare transaction that will withdraw everything, lets say I have an account that has 500N and I am requesting to prepare transaction that will withdraw 500N rosetta will prepare transaction that transfers 499.9834562N

because of that on the account where I had 500N now I will have 0.0165438N - transaction fees

I am referring to the amount that is left on the sending account as leftover

**Comment by frol** [comment]
See https://github.com/near/nearcore/issues/5086#issuecomment-965284072

**Comment by frol** [comment]
To withdraw all the funds from an account in NEAR Protocol, you need to delete it and set the beneficiary_id to the account id that you want to receive all the funds from the given account.

Is there an action item here or should we mark it as resolved?

**Comment by asmolarek-bc** [comment]
Yes that is what we switched to after seeing this behaviour, I am trying to prepare delete account transaction with rosetta construction api, I am trying to create operation of type `DELETE_ACCOUNT`
Is that a correct way to delete account? is it possible to prepare such transaction with rosetta?

**Comment by frol** [comment]
> I am trying to create operation of type DELETE_ACCOUNT. Is that a correct way to delete account?

Yes, that is exactly the correct way to do it.

> is it possible to prepare such transaction with rosetta?

Yes, it is absolutely possible to create any NEAR Protocol transactions from Rosetta Construction API.

**Comment by frol** [comment]
In order to prepare a transaction through Rosetta API, you would need to do some extra work since each operation in Rosetta only has a single account identifier associated with it. Thus, transfers are always TRANSFER minus balance from account1 and TRANSFER plus balance to account2. Account deletion is not an exception, and a single DELETE_ACCOUNT action in NEAR corresponds to 3 Rosetta operations:

https://github.com/near/nearcore/blob/d8a2b5f61ec0c623f63222971fd6fd95a5cd73f5/chain/rosetta-rpc/src/adapters/mod.rs#L451-L478

Thus, you need to create a transaction with the following Rosetta operations:

```json
[
  {"type": "INITIATE_DELETE_ACCOUNT", "account": { "address": "account-for-deletion-here.near" }},
  {"type": "DELETE_ACCOUNT", "account": { "address": "account-for-deletion-here.near" }},
  {"type": "REFUND_DELETE_ACCOUNT", "account": { "address": "beneficiary-account-here.near" }}
]
```
