### ISSUE TITLE
Test randomly failing `test_get_trie_items_for_part`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5139]
I noticed that `test_get_trie_items_for_part` test is randomly failing.
@bowenwang1996 Any ideas?

https://buildkite.com/nearprotocol/nearcore/builds/5957#2c9f2c80-7031-454d-9ec4-4fae067ce0af

**Comment by bowenwang1996** [comment]
This is supposed to be fixed in #5116. @mzhangmzz please take a look

**Comment by pmnoxx** [comment]
@bowenwang1996 Thanks, I'll close the issue.

**Comment by mzhangmzz** [comment]
Yeah the build was before the fix
