### ISSUE TITLE
Track memory usage for each Peer

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5155]
Currently we are not tracing the amount of data that each peer sends to us. It's possible we will run out of memory because we get too many messages for each peer.

We should do the following
- [x] Add TrottledFramedRead - a data structure that tracks the size of all messages, and their count that come from `Peer` and are being processed. (https://github.com/near/nearcore/pull/4927)
- [ ] Add limiting bandwidth usage to `TrottledFramedRead` - we need to investigate first how much bandwidth is reasonable
- [ ] Add bandwidth stats to `TrottledFramedRead` - it's good to know how much bandwidth each peer is using to figure out proper throttling limits
- [x] Refactor `PeerManager` to keep all messages in `Handler` under one enum. https://github.com/near/nearcore/pull/5140
- [x] Add decorator to measure size of all messages that we send to `PeerManager` or `Peer` similar to https://crates.io/crates/deepsize_derive (https://github.com/near/nearcore/pull/5191)
- [ ] Keep tracking all messages that generated from `PeerActor` as they travel to `PeerManager` (https://github.com/near/nearcore/pull/5198)
- [ ] Keep tracking all messages that generated from `PeerActor` as they travel from `PeerManager` to another `Peer`(https://github.com/near/nearcore/pull/5198)

DeepSizeOf improvements - external repo
- [ ] add packages from std https://github.com/Aeledfyr/deepsize/pull/19
- [ ] add .gitignore https://github.com/Aeledfyr/deepsize/pull/20
- [ ] add packages from tokio/actix  https://github.com/Aeledfyr/deepsize/pull/18

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near

**Comment by bowenwang1996** [comment]
>  Add decorator to measure size of all messages that we send to PeerManager or Peer similar to https://crates.io/crates/deepsize_derive

What do we plan to achieve with this? I believe quite a few messages are dynamically sized.

**Comment by pmnoxx** [comment]
@bowenwang1996 `DeepSize` trait works by recursively computing size of each message. The overhead of doing a memory allocations to create given data structure than measuring it's size. So the performance overhead will be negligible.

**Comment by pmnoxx** [comment]
> > Add decorator to measure size of all messages that we send to PeerManager or Peer similar to https://crates.io/crates/deepsize_derive
> 
> What do we plan to achieve with this? I believe quite a few messages are dynamically sized.

I created a PR in the past, that adds `DeepSize` to all our data structures. So it's doable, I'll have to repeat the work.

**Comment by bowenwang1996** [comment]
@pmnoxx my understanding is that `DeepSize` does some static computation right? My question was about the parts that cannot be determined statically.

**Comment by pmnoxx** [comment]
> @pmnoxx my understanding is that `DeepSize` does some static computation right? My question was about the parts that cannot be determined statically.

@bowenwang1996 No, `DeepSize`does computations dynamically. It a decorator that generates a code, which goes through all members of a struct, and add up sizes.

**Comment by pmnoxx** [comment]
`DeepSize` internally uses `pub const fn size_of<T>() -> usize`, to check known rust types, and direct sizes of structures; see https://doc.rust-lang.org/stable/std/mem/fn.size_of.html

Consider `Vec<SomeType>`. To compute memory usage you need to compute size of `Vec<...>`.
Size of ` buf: RawVec<T, A>,` element of `Vec<...>`.
And for each element of `Vec<SomeType>` indirect sizes of all attributes `SomeType` contains. In case `SomeType` contains another array, hashmap, etc.
