### ISSUE TITLE
Potential dead code in the pipeline.yml?

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5168]
This pipeline looks suspect to me:

https://github.com/near/nearcore/blob/5f9c98fd000566dfb024607acb4c95dcd914e90a/.buildkite/pipeline.yml#L67-L79

`nightly-2020-05-15 ` is very, very old, and definitely can't compile `nearcore`. Looking at the `test_nearlib.sh`, it looks like something not terribly reproducible, and chunks of the file are commented away. 

It seems like this is just a bit of bitrotted code. Do we understand what value is created by this test?

**Comment by mina86** [comment]
@pmnoxx, since you were working on `test_nealib.sh` recently, do you have any state on why the version is so old? Can it be updated? Or updated in some other way.?

**Comment by pmnoxx** [comment]
@matklad @mina86 

This is a dead code. Removing it, has no effect on the test:

https://github.com/near/nearcore/pull/5814/files
