### ISSUE TITLE
Being able to use rosetta to determine transaction completion

### ISSUE THREAD

**Issue by asmolarek-bc** [near/nearcore#5173]
This issue is related to the scope of data provided by Rosetta API 

**Describe the bug**
Rosetta does not have a way to determine which part of operation in a block is connected to which transaction because initial operation is connected to transaction id, and subsequent ones are identified by they specific receipt id
Because of that it is not possible to connect operations from single transaction together without using near RPC (which allows querying transaction with all of its receipts)

**To Reproduce**
Reconstruct transaction operations from data provided in rosetta blocks, try to determine transaction ~finality~ completeness only using rosetta API

**Expected behavior**
I am able to connect all operations reported in Rosetta blocks to original transaction, I am able to determine transaction ~finality~ completeness base only on data provided by Rosetta API

Version (please complete the following information):

nearcore tag 1.21.0
rustc 1.51.0
rustup 1.24.3 (ce5817a94 2021-05-31)
cargo 1.51.0
docker Docker version 20.10.8, build 3967b7d
local env with local network

node was compiled with --features rosetta_rpc and started with rosetta api enabled in conf file

**Comment by bowenwang1996** [comment]
Do you mean you want one endpoint that returns this? It is still possible to reconstruct this information I believe

**Comment by asmolarek-bc** [comment]
No I do not need single endpoint, I can reconstruct it from multiple calls, but what I found it is not possible via current implementation of rosetta I do not have a way to ask for transaction base on receipt id (those are the identifiers of subsequent operations), in general (from what I asked) it is not possible to get transaction by one of its receipts id

afaik rosetta api does not allow asking for specific transaction by transaction id
What is supported is asking for transaction by transaction id and block 
https://www.rosetta-api.org/docs/BlockApi.html#blocktransaction
But when I am receiving subsequent operations I do not have transaction id ad previous block, I only have receipt id and current block
And this endpoint returns transaction only in that block, which means it will not return operations related to receipts in subsequent blocks (am I right?)

for now workaround is to keep in memory transactions that are not yet final (there are pending outcomes) and ask near RPC to get transactions + all receipts, from this I have information about every transfer / refund and amount of tokens burnt (fee)

**Comment by frol** [comment]
@asmolarek-bc Yep, there is indeed a gap in Rosetta implementation there (there was no notion of `related_transactions` before the very latest Rosetta 1.4.10 spec while we only implemented Rosetta 1.4.4).

Would you like to contribute this feature to Rosetta implementation in nearcore? (That would require to pull in the list of outgoing receipt ids and expose them as `related_transactions` with direction set to `forward`)

**Comment by mina86** [comment]
This should now be possible. Transaction have no `related_transactions` field populated so a transaction can be determined finished once all the related transactions are finished. This needs to be handled recursively since related transactions can have further related transactions.

**Comment by frol** [comment]
> Transaction have no related_transactions field populated so a transaction can be determined finished once all the related transactions are finished.

I did not get this sentence; could you re-phrase it?

@asmolarek-bc `related_transactions` support was introduced in #5721, and should be part of 1.25.0 release or you can just build nearcore from master today since either way you need to build nearcore from source code with rosetta feature enabled.

**Comment by mina86** [comment]
Sorry, I meant ‘now’ not ‘no’.
