### ISSUE TITLE
Implement near-time - a near create for time

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5174]
As discussed with @matklad, we discussed implementing our of crate for time. 

Currently we use 4 methods to represent time `chrono` (`Utc::now()`) (`Datetime<Utc>`) , `SystemTime`, `Instant::now`, `u64`, they all have their issues.

- We don't want to use external `chrono` library, mainly because we don't really care about timezones
- `Instant` is written in such a way, that it's not possible to convert it to Unix timestamp. 
- `SystemTime` works, but it's not monitonic. It's possible that if we measure time at time `a` then at time `b`; the duration `b-a` will be negative, causing our code to fail.
- We want to use a saturating `Duration`, so any duration such that `a < b`, created by `a - b`, will default to `0`, if the difference were to become nagative. This will reduce chances of any crashed happening, when negative time is not expected.

We are going to create our own wrapper around `SystemTime` and `Duration`. This will allow us to do the mocking properly.

- [x] pt 1 - https://github.com/near/nearcore/pull/5177
- [ ] stop using `pub use` for external crates like UTC - that's a bad practice. 
- [ ] PR for near-network
- [ ] following PRs

**Comment by pmnoxx** [comment]
@matklad @bowenwang1996 @mm-near @yordanmadzhunkov

**Comment by bowenwang1996** [comment]
Please sync with @yordanmadzhunkov to avoid duplication of work

**Comment by pmnoxx** [comment]
@bowenwang1996 I'll discuss it tomorrow with @yordanmadzhunkov during a meeting.

**Comment by pmnoxx** [comment]
@bowenwang1996 This is an independent issue. I'll chose the issue for now. First we need to finish implementing mocking for time.
