### ISSUE TITLE
Indexer memory usage still goes too high after using memory leak fix commit

### ISSUE THREAD

**Issue by BenKurrek** [near/nearcore#5183]
**Describe the bug**
Our indexer's memory was steadily increasing until the indexer crashed this morning and stopped printing blocks. The rate at which memory is being used up is much slower than before we switched to the memory leak fix commit (which is here: 25b000ae4dd9fe784695d07a3f2e99d82a6f10bd --> https://github.com/near/nearcore/releases/tag/1.22.0-rc.4).

**Screenshots**
![image](https://user-images.githubusercontent.com/57506486/140951090-21ee5c51-5df5-4009-94d3-55e2344d9a86.png)

![image](https://user-images.githubusercontent.com/57506486/140951127-81f653de-85d1-418d-a6fe-c696a5fa2b27.png)

**Version (please complete the following information):**
- 25b000ae4dd9fe784695d07a3f2e99d82a6f10bd
- testnet

**Comment by bowenwang1996** [comment]
@frol @khorolets could we add support for `memory_stats` (a nearcore cargo feature) for indexers?

**Comment by khorolets** [comment]
> @frol @khorolets could we add support for `memory_stats` (a nearcore cargo feature) for indexers?

I'm not aware of this feature. Is it enough to enable logs like "memory_stats=debug" or something else?

**Comment by nikurt** [comment]
> > @frol @khorolets could we add support for `memory_stats` (a nearcore cargo feature) for indexers?
> 
> I'm not aware of this feature. Is it enough to enable logs like "memory_stats=debug" or something else?

You can enable this feature in `neard` at compile time: `cargo build -p neard --features memory_stats` and it will print `warn` logs with a stacktrace of allocation when memory usage grows much a lot.
Feature in `neard`: https://github.com/near/nearcore/blob/6afb3473420185b3e61b1cb3d6d84db119064c41/neard/Cargo.toml#L39
Feature in `nearcore`: https://github.com/near/nearcore/blob/6afb3473420185b3e61b1cb3d6d84db119064c41/nearcore/Cargo.toml#L62
Implementation: https://github.com/near/nearcore/blob/master/utils/near-performance-metrics/src/stats_enabled.rs

**Comment by bowenwang1996** [comment]
> can you clarify if I should see such logs on localnet without any contract activities

You will only see logs if the memory usage of some thread is more than some threshold. Please consult with @pmnoxx on this

**Comment by pmnoxx** [comment]
@khorolets You also need to enable `performance_stats` feature, Otherwise we will not be reporting any logs.

**Comment by BenKurrek** [comment]
do you need me to do anything on my side?

**Comment by BenKurrek** [comment]
Our indexer crashed again this morning. The memory had been steadily increasing over the past 6 days and then it suddenly spiked from 64% to 99% in the span of 15 minutes and crashed. 

This is the graph for the past week: 
![image](https://user-images.githubusercontent.com/57506486/141788114-9bebd7b2-a714-4d23-be89-5c9a1441951f.png)

This is the graph for the past 6 hours where it crashed: 
![image](https://user-images.githubusercontent.com/57506486/141788397-ed3748d1-13a2-4746-8687-76b8a49242b1.png)

**Comment by khorolets** [comment]
> @khorolets You also need to enable `performance_stats` feature, Otherwise we will not be reporting any logs.
> 
> You also need to start the thread that's started when `performance_stats` is enabled.

I've enabled both and don't see any logs on localnet. I wonder if I will see them on testnet or mainnet only?

**Comment by khorolets** [comment]
> You also need to start the thread that's started when `performance_stats` is enabled.

@pmnoxx could you help with this?

**Comment by pmnoxx** [comment]
@khorolets How can I compile the indexer. And which binary is it?

**Comment by pmnoxx** [comment]
@khorolets Can you take a look at
```utils/near-performance-metrics/src/stats_enabled.rs ```
Look at `schedule_printing_performance_stats` method.

**Comment by pmnoxx** [comment]
@khorolets Take a look at https://github.com/near/nearcore/pull/5271++

**Comment by BenKurrek** [comment]
Cross posting from TG and messages with @khorolets: 

I’m getting a ton of memory issues with the new commit hash (397a7a45b8efd3e4604374a4efabd567c03c0a19) It has crashed 3 times in a week.

These are my messages with Bohdan: 
![image](https://user-images.githubusercontent.com/57506486/147942880-4edf3245-20ff-4a9a-8d25-764dd3768758.png)
![image](https://user-images.githubusercontent.com/57506486/147942901-57b20788-2460-4574-b832-83b2ada93679.png)
![image](https://user-images.githubusercontent.com/57506486/147942912-8bbc3e07-7967-4db1-8936-d76a763e19a4.png)

**Comment by pmnoxx** [comment]
https://github.com/near/nearcore/pull/5902

**Comment by bowenwang1996** [comment]
I think this is already fixed. Please reopen if that is not the case
