### ISSUE TITLE
`pytest sanity/routing_table_sync.py` test is broken

### ISSUE THREAD

**Issue by mina86** [near/nearcore#5188]
The test currently fails on NayDuck.  To reproduce:

    ./scripts/nayduck -b master -s master -i <<<EOF
    pytest --timeout=480 sanity/routing_table_sync.py --features nightly_protocol,nightly_protocol_features
    EOF

**Comment by pmnoxx** [comment]
@mina86 Thanks, the hotfix has been merged.

**Comment by pmnoxx** [comment]
@mina86 Sorry, I didn't notice that the previous fix didn't fix issue.
https://github.com/near/nearcore/pull/5190/files

**Comment by pmnoxx** [comment]
I reopened this pr.
@bowenwang1996 @mm-near Can you take a look?

**Comment by mina86** [comment]
Looks like it’s still failing: http://nayduck.near.org/#/test/241592

**Comment by pmnoxx** [comment]
> Looks like it’s still failing: http://nayduck.near.org/#/test/241592

I wrote a fix: https://github.com/near/nearcore/pull/5199

I ran in 30 times, it works fine: http://nayduck.near.org/#/run/2200
