### ISSUE TITLE
Package `state-viewer` with `neard`

### ISSUE THREAD

**Issue by nikurt** [near/nearcore#5193]
Please consider including `state-viewer` functionality into the `neard` binary.
The two binaries share >90% of the code, and the code size and compilation time increase should be insignificant.

My motivating use case is investigating issues or incidents. I need `state-viewer` to inspect the state of the DB. Currently it requires me to compile `state-viewer` separately and the version of `neard` and `state-viewer` must be the same, otherwise differences in protocol version or DB version can prevent `state-viewer` from reading the DB. The worst possible outcome is `state-viewer` silently upgrading the DB version.

@matklad

**Comment by matklad** [comment]
>compilation time increase should be insignificant.

I'd expect somewhat significant *decrease* in compilation time, as we'd have to link one fewer binary.
