### ISSUE TITLE
Mocking with `Clock` is not complete

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5245]
We recently added mocking time with `Clock::instant()` and `Clock::utc()`.

I checked `near-network` code, and I see that there are places where time is not mocked. For example usage of `SystemTime::now()`

(https://github.com/near/nearcore/blob/c34ea39d2315a977f4882e4d280649bdbaee05bd/chain/network/src/stats/rate_counter.rs#L62)

`Instant::elapsed` in many places, for example
https://github.com/near/nearcore/blob/c34ea39d2315a977f4882e4d280649bdbaee05bd/chain/network/src/peer_manager/peer_manager_actor.rs#L386

We should finish mocking and do it in all places to be consistent.

@bowenwang1996 @yordanmadzhunkov @mm-near

**Comment by pmnoxx** [comment]
My proposal is to create wrapper, which we can use for mocking time. (https://github.com/near/nearcore/pull/5177)
I'll adjust the change to use `Clock::utc()` instead of `SystemTime::now()`

**Comment by bowenwang1996** [comment]
Given that @yordanmadzhunkov is busy with other things, I'll assign this to @pmnoxx
