### ISSUE TITLE
Improve merging changes to CI

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5274]
I noticed a few issues with CI
- `S-automerge` doesn't automatically rebase changes. Even if I click manually 'update branch'. Then if anyone merges PR meanwhile the change will not merge. This ended me having to manually click "update merge" many times in many requests. In the end, out of 16 approved changes, which were ready to merge, had `S-automerge` I only manged to merge 2 of them. 

- Even if I was the only person doing merges and `S-automerge` worked, it would take like 8 hours to do merges. Right now it takes 20 minutes to run the test, and if someone else pushes meanwhile those changes will not be merged.
Can we change github configuration to
- after rebasing, then waiting for tests to pass, we would automatically merge if there were no issues with doing rebase, after the tests are done.
I understand that this may break build in rare cases. However, currently we have many engineers pushing to repository, and we are limited to merging 2 merge request per hour. 

I had a discussion about this with @bowenwang1996 . 

@chefsale @bowenwang1996 @mm-near

**Comment by bowenwang1996** [comment]
@rtsai123 could the SRE team potentially look into what Alex suggested?
