### ISSUE TITLE
`PrepareError` occurred when call or view contract function

### ISSUE THREAD

**Issue by riversyang** [near/nearcore#5310]
When call or view functions of a contract which written in `near-sdk-rs` v3.1.0, a `PrepareError` occurred and the contract can not work anymore. The sample error message are as the following:

```shell
Scheduling a call: wchain.dev-oct-registry.testnet.migrate_state()
Doing account.functionCall()
Receipt: D6v43eXYFZQVFbvnXgPTaKERGCeUhCCCyN797vYDfZuR
        Failure [wchain.dev-oct-registry.testnet]: Error: Error happened during instantiation
ServerTransactionError: Error happened during instantiation
    at Object.parseResultError (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async scheduleFunctionCall (/usr/local/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'Instantiate',
  context: undefined,
  index: 0,
  transaction_outcome: {
    block_hash: '3Jv4hShujXFwD44A2viRuma69FbAHYCfR9FnUjNnX45M',
    id: 'FzE8e11cJ91CEBv69ravUfCxyUMLdzHj6BjkhRstHi7a',
    outcome: {
      executor_id: 'dev-oct-registry.testnet',
      gas_burnt: 2427954539010,
      logs: [],
      metadata: [Object],
      receipt_ids: [Array],
      status: [Object],
      tokens_burnt: '242795453901000000000'
    },
    proof: []
  }
}
```

```shell
View call: wchain.dev-oct-registry.testnet.get_anchor_settings()
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate))).
{
  "block_hash": "7M3oTMvwEzonNx1NAtFATSWmYx2aAAmfFhCohiMLyCBM",
  "block_height": 71663269,
  "error": "wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate)))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:75:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate))).
{
  "block_hash": "7M3oTMvwEzonNx1NAtFATSWmYx2aAAmfFhCohiMLyCBM",
  "block_height": 71663269,
  "error": "wasm execution failed with error: FunctionCallError(CompilationError(PrepareError(Instantiate)))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:75:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

Please refer to https://github.com/octopus-network/octopus-appchain-anchor/tree/integrate-beefy-light-client for source code.

It can be compiled locally and can be deployed by `near-cli`.

Further more, when running tests with near simulator, the macro `deploy!` will fail due to similar error (`PrepareError`).

It seems the locally compiled wasm file can not run on NEAR vm. This error happens after the repo integrated a [beefy light client implementation](https://github.com/octopus-network/beefy-light-client). We assume it is caused by some dependencies in the light client implementation but have no idea how to find them out, because the repo can be compiled locally.

Please advise how to locate the root cause. Thank you.

**Comment by bowenwang1996** [comment]
@matklad @nagisa please take a look. Thanks!

**Comment by think-in-universe** [comment]
The error comes from here: https://github.com/near/nearcore/blob/2c0703cafc871750eaea74e41bb2401dcce0ab6b/runtime/near-vm-runner/src/prepare.rs#L99

**Comment by nagisa** [comment]
The `beefy-light-client` crate does indeed generate the following wasm imports:

```wat
  (import "__wbindgen_placeholder__" "__wbindgen_describe" (func (;0;) (type 9)))
  (import "__wbindgen_placeholder__" "__wbindgen_throw" (func (;1;) (type 0)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_grow" (func (;2;) (type 10)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_set_null" (func (;3;) (type 9)))
```

which are not allowed. These are coming in through the attempt to use a javascript implementation of the `getrandom` [here](https://github.com/octopus-network/beefy-light-client/blob/2babc60dce5227b6e2fd7fb28ca2ebcbe788a589/Cargo.toml#L14). I don't believe this to be a contract runtime issue.

**Comment by nagisa** [comment]
Except perhaps that we could output errors that are more descriptive.

**Comment by matklad** [comment]
Yeah, it's definitely a bug that we erase the information about what's wrong exactly. Opened https://github.com/near/nearcore/issues/5315 for that.

**Comment by riversyang** [comment]
> The `beefy-light-client` crate does indeed generate the following wasm imports:
> 
> ```webassembly
>   (import "__wbindgen_placeholder__" "__wbindgen_describe" (func (;0;) (type 9)))
>   (import "__wbindgen_placeholder__" "__wbindgen_throw" (func (;1;) (type 0)))
>   (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_grow" (func (;2;) (type 10)))
>   (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_set_null" (func (;3;) (type 9)))
> ```
> 
> which are not allowed. These are coming in through the attempt to use a javascript implementation of the `getrandom` [here](https://github.com/octopus-network/beefy-light-client/blob/2babc60dce5227b6e2fd7fb28ca2ebcbe788a589/Cargo.toml#L14). I don't believe this to be a contract runtime issue.

It's very helpful to know the cause. Already made our contract working by adding a custom `getrandom` function. Thank you!
