### ISSUE TITLE
`routing::test_dropping_routing_messages` test is broken

### ISSUE THREAD

**Issue by mina86** [near/nearcore#5322]
```sh
cargo test --workspace --features test_features \
    --project integration-tests --test network \
    -- --exact routing::test_dropping_routing_messages
```

This hasn’t been caught because the test is guarded by a `cfg(feature = "test_features")` and since we don’t enable that feature on BuildKite the test has not been executed.

**Comment by mina86** [comment]
The test passes on nightly so it seems it should be guarded by one of the `protocol_feature` in addition to `test_features` but I don’t quite know which one. I’ve established that the following passes:

```bash
cargo test --workspace -p integration-tests --test network --features \
    protocol_feature_alt_bn128,protocol_feature_limit_contract_functions_number,protocol_feature_routing_exchange_algorithm,test_features \
    -- --exact routing::test_dropping_routing_messages
```

**Comment by pmnoxx** [comment]
@mina86 Thanks, I'll take a look.

**Comment by pmnoxx** [comment]
That's most likely related to `fn ping_jump() ` randomly failing.

**Comment by pmnoxx** [comment]
This test sometimes works, sometimes fails.

**Comment by pmnoxx** [comment]
@mina86 @matklad @chefsale  For some reason I can't capture output of this test to a file, I tried:
```

cargo t --workspace --features test_features -p integration-tests --test network -- --exact routing::test_dropping_routing_messages 2>&1 > /tmp/out


```

**Comment by mina86** [comment]
Your redirections are in the wrong order, do `>/tmp/out 2>&1`.

**Comment by pmnoxx** [comment]
@mina86 Thanks, I figured out the issue. I'll have to rewrite the test.
