### ISSUE TITLE
Limit amount of entities in the smart contract

### ISSUE THREAD

**Issue by olonho** [near/nearcore#5329]
Smart contract is essentially a WASM program which has well defined set of entities (functions, imports, globals etc), and although WASM spec imposes certain limitations on those values we may want to put our own limits on those entities to make sure compile and execute quickly.

So far this issue is mostly for discussions.

**Comment by jakmeier** [comment]
@Ekleog-NEAR didn't we add some limits recently? Is this issue here still useful to keep open or should we close it? (We also still have #6456 open)

**Comment by Ekleog-NEAR** [comment]
We did not add our own limits recently so this is still relevant, but it’s true that this and #6456 are duplicates. So I’m closing this one, as it seems like other issues referred to #6456
