### ISSUE TITLE
Protocol upgrade related metrics

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#5339]
I would like to see via Prometheus metrics (`127.0.0.1:3030/metrics`) how NEAR protocol_version is progressing. Not sure can granularity be achieved within the epoch and not on the epoch boundary, but if that would be possible it would be great, like:

 $ curl -s 127.0.0.1:3030/metrics | grep -e ^near_protocol_upgrade_progress
 52

Above is just an example that 52% of validators upgraded to the new protocol version. If upgrade is not happening the metric is missing or 0\. Probably missing if no upgrade in progress.

Another metric which would be great is how many blocks (or seconds in the future if epoch is time-based) are left to the cut-off epoch. So for example, after 80% of validators upgraded, and epoch switches:

 $ curl -s 127.0.0.1:3030/metrics | grep -e ^near_protocol_upgrade_epoch_left
 34207

so above shows that there is 34207 blocks (or 9h30m7s `(9*60*60)+(30*60)+7`) left before protocol upgrade takes effect. If upgrade is not active, metric is missing.

Based on both metrics we would like to create alarms. If metric is present with value above X (lets say 23hrs) warning alarm is created, but if only 6 hrs are left, then critical alarm is created and oncall is paged. Lack of metric - no alarm.

**Comment by nikurt** [comment]
This issue is complementary to https://github.com/near/NEPs/issues/205 and provides a short-term fix.

**Comment by kucharskim** [comment]
With configurable number of epoch for upgrade I think this feature request has even more sense. Especially the second type of metric requested here - blocks (seconds) left before new protocol version is active. That creates clear signal for the node runner, time is running out for an upgrade.

**Comment by kucharskim** [comment]
Giving comment in https://github.com/near/nearcore/issues/5331#issuecomment-972243814 with second type of metric (blocks left for protocol switchover) it would be already too late and NEAR would panic() anyway, even if upgrade is done within last 2 epochs.

**Comment by nikurt** [comment]
Fixed by https://github.com/near/nearcore/pull/7877

**Comment by kucharskim** [comment]
Which `nearcore` release this is going to be included in?
