### ISSUE TITLE
Clock doesn't have unit ut

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5344]
**Describe the bug**
Please provide a short description of the bug.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**

**Comment by mina86** [comment]
Looks like mistakenly failed duplicate of https://github.com/near/nearcore/issues/5345
