### ISSUE TITLE
Clock doesn't have unit tests

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5345]
We don't have any tests for `Clock` in `core/primitives/src/time.rs`.
Let's add a bare minimum.

**Comment by Rishabhraghwendra18** [comment]
Hi @pmnoxx is this issue resolved ? I have found some tests in the [file](https://github.com/near/nearcore/blob/master/core/primitives/src/time.rs#L182)

**Comment by pmnoxx** [comment]
@Rishabhraghwendra18 I did it already, see #5362
