### ISSUE TITLE
Allow specifying the number of epochs for data retention in config

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#5347]
Currently for a regular node the number of epochs for which we retain data is fixed (5 epochs) and we have received requests to make that flexible, since some partners have requirements on data retention.

**Comment by pmnoxx** [comment]
@bowenwang1996 It may be a good idea to mention where that constant is stored in the code. That would allow people to judge how easy it is.

**Comment by pmnoxx** [comment]
@bowenwang1996 Is this for `neard` executable?
