### ISSUE TITLE
Near archive nodes stuck on block 52890664

### ISSUE THREAD

**Issue by jwbd1** [near/nearcore#5354]
**Describe the bug**
Near archive node stuck on block 52890664. Node was updated on time to 1.22.0. No errors in logs, just getting 0.00bps at this block.

**To Reproduce**
Update Near archive to 1.22.0. Allow it to continue syncing normally. At block 52890664, the node stops syncing.

**Expected behavior**
The node should continue to sync as per normal

**Screenshots**
```
Nov 18 09:59:41.948  INFO stats: #52890664 Downloading blocks 99.86% (58240)  32/27/40 peers ⬇ 357.3kiB/s ⬆ 285.2kiB/s 0.00 bps 0 gas/s CPU: 82%, Mem: 3.1 GiB
Nov 18 09:59:51.952  INFO stats: #52890664 Downloading blocks 99.86% (58249)  32/27/40 peers ⬇ 355.5kiB/s ⬆ 291.8kiB/s 0.00 bps 0 gas/s CPU: 83%, Mem: 3.1 GiB
Nov 18 10:00:01.955  INFO stats: #52890664 Downloading blocks 99.86% (58258)  32/27/40 peers ⬇ 344.9kiB/s ⬆ 273.7kiB/s 0.00 bps 0 gas/s CPU: 82%, Mem: 3.1 GiB
Nov 18 10:00:11.999  INFO stats: #52890664 Downloading blocks 99.86% (58267)  32/27/40 peers ⬇ 326.7kiB/s ⬆ 269.9kiB/s 0.00 bps 0 gas/s CPU: 83%, Mem: 3.1 GiB
Nov 18 10:00:22.003  INFO stats: #52890664 Downloading blocks 99.86% (58276)  32/27/40 peers ⬇ 327.6kiB/s ⬆ 267.0kiB/s 0.00 bps 0 gas/s CPU: 79%, Mem: 3.1 GiB
Nov 18 10:00:32.015  INFO stats: #52890664 Downloading blocks 99.86% (58284)  32/27/40 peers ⬇ 314.4kiB/s ⬆ 255.1kiB/s 0.00 bps 0 gas/s CPU: 83%, Mem: 3.1 GiB
Nov 18 10:00:42.017  INFO stats: #52890664 Downloading blocks 99.86% (58293)  31/26/40 peers ⬇ 308.3kiB/s ⬆ 245.7kiB/s 0.00 bps 0 gas/s CPU: 80%, Mem: 3.1 GiB
Nov 18 10:00:52.019  INFO stats: #52890664 Downloading blocks 99.86% (58302)  31/26/40 peers ⬇ 316.1kiB/s ⬆ 245.9kiB/s 0.00 bps 0 gas/s CPU: 84%, Mem: 3.1 GiB
Nov 18 10:01:02.028  INFO stats: #52890664 Downloading blocks 99.86% (58311)  31/26/40 peers ⬇ 333.9kiB/s ⬆ 267.6kiB/s 0.00 bps 0 gas/s CPU: 82%, Mem: 3.1 GiB
Nov 18 10:01:12.032  INFO stats: #52890664 Downloading blocks 99.86% (58321)  31/26/40 peers ⬇ 345.5kiB/s ⬆ 266.0kiB/s 0.00 bps 0 gas/s CPU: 83%, Mem: 3.1 GiB
```

**Version (please complete the following information):**
- nearcore docker image 1.22.0
- mainnet
- archive

**Additional context**
This looks to have been reported by a few users on Discord also.

Do you know if the archive snapshot is already updated past this block?

**Comment by bowenwang1996** [comment]
> Update Near archive to 1.22.0. Allow it to continue syncing normally. At block 52890664, the node stops syncing.

I think you upgraded too late and the node is stuck trying to splitting the state. You can either wait for that to finish (may take 12 hours). Or you can download the snapshot

> Do you know if the archive snapshot is already updated past this block?

Yes
