### ISSUE TITLE
`routing::archival_node` is flaky

### ISSUE THREAD

**Issue by mina86** [near/nearcore#5357]
```sh
cargo test -p integration-tests --test network \
    -- --exact routing::archival_node
```

Sometimes passes, sometimes fails.  For example see [7398](https://buildkite.com/nearprotocol/nearcore/builds/7398) and [7404](https://buildkite.com/nearprotocol/nearcore/builds/7404) where I’ve re-run cargo test which passed the second time around.

**Comment by pmnoxx** [comment]
@bowenwang1996 @mina86  I already wrote a fix: https://github.com/near/nearcore/pull/5639
