### ISSUE TITLE
.near/mainnet/data" thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "Corruption: Can't access /3700449.sst: IO error

### ISSUE THREAD

**Issue by dimaelkhsos** [near/nearcore#5377]
**Describe the bug**
.near/mainnet/data"
thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "Corruption: Can't access /3700449.sst: IO error

**To Reproduce**
1. downloaded archive data for mainnet from "https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/archive/data.tar"
2. I switched to github release version 1.22.0
3. Compiled the neard
4. Stopped Near  "nearup stop"
5. tar -xvf data.tar -C ~/.near/mainnet/data
5. nearup start mainnet

**Expected behavior**
Normal sync from 97%

**Screenshots**

**Version (please complete the following information):**
- nearcore 1.22.0
- rust version rustup 1.24.3 (ce5817a94 2021-05-31)
- mainnet

**Additional context**
 i got the error
.near/mainnet/data"
thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "Corruption: Can't access /3700449.sst: IO error
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: near_store::create_store
   4: nearcore::start_with_config
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: neard::cli::NeardCmd::parse_and_run
i downloaded the data.tar from https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/archive/data.tar
and i did
tar -xvf data.tar -C ~/.near/mainnet/data

but the mentioned files on the error not really exist, does the archive from S3 corrupted?
and it is not only one file, it is complaining of a lot of files

**Comment by kucharskim** [comment]
Did that error happen after some uptime of `neard` or straight after starting? I would be good if you provide whole logs from starting until panic, with timestamps. It's hard to understand what happened here.

**Comment by bowenwang1996** [comment]
I think this may be related to #5098 cc @mhalambek

**Comment by bowenwang1996** [comment]
looks obsolete
