### ISSUE TITLE
Rosetta RPC fails to delete an implicit account

### ISSUE THREAD

**Issue by frol** [near/nearcore#5405]
**Describe the bug**

Allegedly, Rosetta RPC cannot delete an implicit account that was just created (see the discussion https://github.com/near/nearcore/issues/5129#issuecomment-959894207). We need to reproduce the issue on our end first. Here is the script that we can use as a starting point: https://github.com/near/nearcore/pull/3301#issuecomment-695054301

**To Reproduce**

Create an account:

1. generate a new key-pair (completely offline step)
2. construct the implicit account id from the public key of the generated key-pair by encoding the public key (32 bytes or 43-44 characters in base58 encoding) into 64-character-long hex string (completely offline step)
3. create a transaction to transfer some funds from some account that has NEAR tokens to the implicit account id from step (2) (requires some online data: https://www.rosetta-api.org/docs/ConstructionApi.html#constructionmetadata (recent hash and access key nonce needs to be pulled out))
4. sign the transaction with the access key of the account that is sending the funds (can be done offline)
5. submit the transaction (online)
6. ... at this stage you will have the new account on the network with the account id from step (2)...

Delete the account:
1. having the generated key-pair (see step 1 above), we are ready to construct the transaction
2. create a transaction with 3 operations:

    ```json
    [
      {"type": "INITIATE_DELETE_ACCOUNT", "account": { "address": "implicit_account" }},
      {"type": "DELETE_ACCOUNT", "account": { "address": "implicit_account" }},
      {"type": "REFUND_DELETE_ACCOUNT", "account": { "address": "holding_account" }}
    ]
    ```
3. sign the transaction with the key from step (1)
4. submit the transaction

**Expected behavior**
The account should be deleted successfully

**Observed behavior**

It is reported to return the following error:

```
Not Found: Access key for public key ed25519:4q4ZEDk2ZBeq5tEqj2PDXuxorvW81nqpviSLtNsj3WyA has never been observed on the node at block #132
```

Note that the public key corresponds to the implicit account id hex representation, so there is no issue there.

What is weird is that if there is a transfer operation between the account creation and account deletion, it is reported to delete account just fine.

**Version (please complete the following information):**
- localnet

**Comment by bowenwang1996** [comment]
cc @mina86

**Comment by mina86** [comment]
Based on test added in https://github.com/near/nearcore/pull/5441 Rosetta RPC can be used to create and then delete implicit accounts just fine.

**Comment by frol** [comment]
It turned out that there is no issue on Rosetta implementation side. The root cause for the reported problem was NEAR Protocol design that does not support creation of an implicit account on account deletion (i.e. beneficiary account id MUST exist to receive the tokens from the deleted account)
