### ISSUE TITLE
Good places to refactor

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5423]
The purpose of this issue is to track ant remaining refactoring that need to be done, created issue for. This is to make sure we don't forget really good comments. And, at the same time we limit scope of changes, so we don't do too code changes in one piece of code.

- [x] Rewrite `RateCounter` #5225 
- [ ] Refactor `PeerStatsResult` https://github.com/near/nearcore/pull/5225/files#r754529253
```rust
pub struct Throughput {
  pub n_messages: usize,
  pub n_bytes: usize
}

struct PeerStatsResult {
  send_per_sec: Throughput,
  recv_per_sec: Throughput,
  is_abusive: bool,
  chain_info: ChainInfo,
}
```
- [x] #5402 
- [x] #5371
- [x] #5416 
- [ ] avoid conditional imports https://github.com/near/nearcore/pull/5373#issuecomment-976584358
```rust
#[cfg(feature = "deepsize")]
use deepsize::DeepSizeOf;
pub use error::{ParseAccountError, ParseErrorKind};

#[cfg_attr(feature = "deepsize", derive(DeepSizeOf))]
#[derive(Eq, Ord, Hash, Clone, Debug, PartialEq, PartialOrd)]
pub struct AccountId(Box<str>);
```

==>>

```rust
pub use error::{ParseAccountError, ParseErrorKind};

#[cfg_attr(feature = "deepsize", derive(deepsize::DeepSizeOf))]
#[derive(Eq, Ord, Hash, Clone, Debug, PartialEq, PartialOrd)]
pub struct AccountId(Box<str>);
```
- [ ] Move out `peer_id_type_field_len`, `is_forward_tx` out of `near-network::codec.rs`
- [ ]  Use debug!(message="...", ?A, ?B, ?C); syntax in rest of the code base simialar to    https://github.com/near/nearcore/pull/5392
- [ ] Hide feature inside delay detector   https://github.com/near/nearcore/pull/5436#pullrequestreview-814734494
- [ ] Don't compute current time multiple times in `near-network` https://github.com/near/nearcore/pull/5556#discussion_r769589102

**Comment by bowenwang1996** [comment]
It is worth mentioning what kind of refactoring you refer to here. "Remaining refactorings" is not very descriptive.

**Comment by pmnoxx** [comment]
> It is worth mentioning what kind of refactoring you refer to here. "Remaining refactorings" is not very descriptive.

Yes, we can write a custom CI pipeline, which does the check.

**Comment by pmnoxx** [comment]
> It is worth mentioning what kind of refactoring you refer to here. "Remaining refactorings" is not very descriptive.

I updated the issue name / description to make it clear on what's going on.
