### ISSUE TITLE
Build status badge not visible in README.md

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/nearcore#5447]
Build status badge is not visible in Reamde.md file . I think it's due to incorrect url behind it .

**Comment by Rishabhraghwendra18** [comment]
I will like to work on this issue if it's legitimate .

**Comment by bowenwang1996** [comment]
> I will like to work on this issue if it's legitimate .

Sure. That would be great!

**Comment by Rishabhraghwendra18** [comment]
I can add but build metadata badge of shields.io is asking for some kind of identifier . Take a look [here](https://shields.io/category/build). May you provide me this identifier

**Comment by chefsale** [comment]
You can use:

 [![Build status](https://badge.buildkite.com/0eae07525f8e44a19b48fa937813e2c21ee04aa351361cd851.svg)](https://buildkite.com/nearprotocol/nearcore-release)

**Comment by bowenwang1996** [comment]
Looks like this is already fixed
