### ISSUE TITLE
1 block will be missing every 100 blocks

### ISSUE THREAD

**Issue by think-in-universe** [near/nearcore#5457]
**Describe the bug**

Some blocks could be skipped in the validation process. But as reported by some developers, it seems 1 block will be missing every 100 blocks, such as 52958941, 52959041, 52959141, etc.  Is this coincidence? 

**DB Not Found Error** will be returned when querying the blocks. 

```bash
http post https://archival-rpc.mainnet.near.org jsonrpc=2.0 id=dontcare method=block \
  params:='{
    "block_id": 52958941
  }'
```

Error

```
{
    "error": {
        "cause": {
            "info": {},
            "name": "UNKNOWN_BLOCK"
        },
        "code": -32000,
        "data": "DB Not Found Error: BLOCK HEIGHT: 52959141 \n Cause: Unknown",
        "message": "Server error",
        "name": "HANDLER_ERROR"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

Since exactly 1 block is missing every 100 blocks, is it possible it's an bug? 

**To Reproduce**
As reported, query the blocks one by one, but 1 block will be missing every 100 blocks. 

**Expected behavior**
The error message maybe could be improved if it's not an bug.

**Comment by bowenwang1996** [comment]
Not a bug. It was because there was a validator who was offline but did not stop their staking pool. They happen to occupy one seat and due to how blocks are produced now, there is a 100 block period upon which the validators rotate.
