### ISSUE TITLE
Fuzzing vm_runner next steps

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5465]
[https://github.com/near/nearcore/pull/5462](https://github.com/near/nearcore/pull/5462) implements basic vm_runner fuzzing. THere's a bunch of stuff we can do on top, in the order of increasing complexity:

*   `impl Arbitrary` for `VMContext`
*   [https://github.com/bytecodealliance/wasm-tools/pull/286](https://github.com/bytecodealliance/wasm-tools/pull/286) – allowing fuzzer to exercise host functions
*   add some way to diffirentially fuzz two neard binaries against each other. Today, to do diff-fuzz you need to add an extra VM Kind, and thats a chore.

**Comment by matklad** [comment]
This was completed: 

* we do differential fuzzing
* we do use host fn

We don't randomize VMContext, but that's not super important I think 

@Ekleog do we consider this done?

**Comment by Ekleog** [comment]
I think so, yes! We still have things like fuzzing host functions, but it's already being tracked in https://github.com/near/nearcore/issues/6500 :)
