### ISSUE TITLE
Update `actix` dependency to stable

### ISSUE THREAD

**Issue by lilses** [near/nearcore#5537]
**Describe the bug**
This is causing extremely frustrating issues when running an indexer because we need to `Cargo.lock` from https://github.com/near/near-indexer-for-explorer to build successfully. Previously didn't need to do this prior to https://github.com/near/nearcore/releases/tag/1.23.0-rc.1

[`actix 11-beta`](https://github.com/near/nearcore/blob/master/chain/indexer/Cargo.toml#L9) is now stable https://github.com/actix/actix/releases/tag/v0.12.0

**To Reproduce**
Build indexer without `Cargo.toml` from https://github.com/near/near-indexer-for-explorer

**Expected behavior**
Deterministically build indexer without relying on anybody's`Cargo.lock`

**Why is this bad**
Getting creative and building any of such just become pointless when convention becomes a web of gotchas documented nowhere.

**Workaround**
This is not a workaround. Copying https://github.com/near/near-indexer-for-explorer is the only way but that also you are implicitly restricted to certain dependencies.

**Comment by frol** [comment]
@miraclx May I ask you to take a look into this and potentially upgrade actix "one last time"? :pray: 

The extreme test are:
* get nearcore compilable after Cargo.lock is removed
* get near-indexer-for-explorer compilable when Cargo.lock is removed
