### ISSUE TITLE
Database migration from version 29 to 30 might be broken

### ISSUE THREAD

**Issue by frol** [near/nearcore#5541]
**Describe the bug**

I received a report from one of our Indexer Framework users that they arrived into a corrupted state database after applying the migration.

**To Reproduce**

I clarified their steps were the following:

1. had a running indexer node based on 1.22 release running on testnet in non-archival mode
2. compiled a new indexer with just updating the Cargo.toml / Cargo.lock with the newer version of nearcore
2.a. ensured that it was compiled in release mode
3. stopped the node with ctrl + c
4. run the newly compiled version of the indexer
5. waited for 25 minutes with the only message saying that it tries to open the database (might be some logging configuration being off not displaying the fact that it actually applied a migration)
6. did not restart our touch the node at all and it crashed itself with the following error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Not all bytes read" }', /home/admin/.cargo/git/checkouts/nearcore-5bf7818cf2261fd0/397a7a4/core/store/src/migrations.rs:788:88
```

That line is the migration code.

**Expected behavior**

It should have completed the migration just fine.

**Version (please complete the following information):**
- nearcore 1.23.0-rc.1
- testnet

**Comment by evergreen-trading-systems** [comment]
I experienced the situation with `RUST_LOG=tokio_reactor=info,stats=info,telemetry=info,indexer_for_wallet=info,info,indexer=info` but the message displayed was `INFO indexer load config from /<path>`.

It stayed like this for 25 minutes. After 25 minutes I manually restarted.

From previous experience I was expecting to see messages such as `applying state`, `state [0: done]` or similar but did not.

**Comment by frol** [comment]
Well, it turned out that the user aborted the node while it was doing the migration, so it is not a surprise that the data got corrupted. The action item here could be: prevent termination of the process during migrations (ignore signals), double-check why the migration logs were not printed.

I'm closing this issue since it is invalid (I missed the fact that the termination of the process was initiated by the user)
