### ISSUE TITLE
In the estimator, track instructions and IO separately 

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5560]
Param estimatror currently tracks two kinds of resources: 

* CPU instructions
* amount of bytes read and written

At the moment, we convert those to gas early on: 

https://github.com/near/nearcore/blob/f820f4425139825e01270455adf935c80116813a/runtime/runtime-params-estimator/src/testbed_runners.rs#L84

This makes it hard to understand the overall cost profile -- in the end you see a high cost, but you don't know whether this is due to instructions, or due to IO.

We should make sure that *inside* the estimator we track the cost as a tripple of (instruction,read_bytes,write_bytes) and convert to gas only at the very end.

Rough plan: 

* Extract https://github.com/near/nearcore/blob/f820f4425139825e01270455adf935c80116813a/runtime/runtime-params-estimator/src/testbed_runners.rs#L59-L100 to a self-contained module called `qemu`, which only reports the counts
* Change https://github.com/near/nearcore/blob/f820f4425139825e01270455adf935c80116813a/runtime/runtime-params-estimator/src/gas_cost.rs#L21-L23 to be several values.

**Comment by matklad** [comment]
This is how to run the estimator: 

```
cargo run --release -p runtime-params-estimator --features required -- --metrics-to-measure ActionDeployContractBase --docker --full
```

**Comment by jakmeier** [comment]
I created PR #5677 for keeping the internal counters for longer and printing them in the end.
But I also discovered a new issue, which I currently believe is independent of my changes. I filed #5678 and will investigate further.

**Comment by matklad** [comment]
I believe this is fixed, thanks @jakmeier !
