### ISSUE TITLE
ci-testnet deploy script stops working 

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5592]
https://github.com/near/near-ops/blob/master/deploy-ci-testnet.py stops working recently. 

It is possibly because the script assumes a certain ordering of testnet accounts after state dump (for example, the second record is account `test.near`. Such ordering are changed after sharding upgrade, because now we dump records per shard.

**Comment by mzhangmzz** [comment]
cc @chefsale @MaximusHaximus

**Comment by mzhangmzz** [comment]
I dumped the testnet state yesterday and checked that at least the second account is not `test.near`. 

Actually I'm not sure why the script worked before. Even before the sharding upgrade, state dump will still dump records in order, and the second account will not be `test.near`

**Comment by mzhangmzz** [comment]
@chefsale can you confirm ci-testnet starts with state dump from testnet? Am I understanding that correctly?

**Comment by chefsale** [comment]
@mzhangmzz It starts from the testnet genesis.json, not from the state dump.

**Comment by mzhangmzz** [comment]
I see. I checked testnet genesis file 
```
"records": [{"Account": {"account_id": "0.base1.testnet", "account": {"amount": "5000000000000000000000000", "locked": "0", "code_hash": "11111111111111111111111111111111", "storage_usage": 182}}}, {"Account": {"account_id": "0.base2.testnet", "account": {"amount": "4999105035569426300000000", "locked": "0", "code_hash": "CyP7uBAqcDAQzgtXMCiuxMbtMVexMvsn7JAapmA3YVm7", "storage_usage": 362351}}}, {"Account": {"account_id": "0.base3.testnet", "account": {"amount": "4998944933660115500000000", "locked": "0", "code_hash": "CyP7uBAqcDAQzgtXMCiuxMbtMVexMvsn7JAapmA3YVm7", "storage_usage": 361325}}},
```
So I don't see why this line in the original script `assert (genesis['records'][1]['AccessKey']['account_id'] == 'test.near')` worked before

**Comment by chefsale** [comment]
I reassigned the issue to myself, will try to fix it tomorrow. @MaximusHaximus can you share some query/tests for validating it works.

**Comment by mzhangmzz** [comment]
@chefsale thanks for taking over the task!

**Comment by chefsale** [comment]
The script is working, so it and node is running, for reference take a look at: https://near--inc.slack.com/archives/C025P00N3QD/p1638385462112900. Closing this issue and creating a new one for the chain/nodeexp team.
