### ISSUE TITLE
Panic when migrating client to 1.23.0-rc.1

### ISSUE THREAD

**Issue by colindickson** [near/nearcore#5646]
**Describe the bug**
I have updated our client to the 1.23.0-rc.1 tag.  When I relaunched our client after the update, it seems unable to connect to peers and eventually I get a panic.   See full logs here:  https://pastebin.com/YRgN5dYs

Does this mean that I will need to discard my previous data and do a full reprocess of the chain? 

**Expected behavior**
Expected to connect to peers and sync blocks correctly 

**Version (please complete the following information):**
- nearcore commit/branch 1.23.0-rc.1.  
- rust version:  compiled with rust toolchain 1.56.0
- running on GKE
- testnet

**Comment by janewang** [comment]
@bowenwang1996 @nikurt FYI on this bug

**Comment by nikurt** [comment]
@colindickson from the logs it's not clear what's wrong.
Deleting the `data` directory and recovering from a backup is the most reliable option.

**Comment by colindickson** [comment]
thank you @nikurt

**Comment by colindickson** [comment]
the node is doing some work, but i feel like maybe it isn't doing as much as it could be doing.  this is running on an HPC node in GKE.   the process seems to be taking up one core at a time, even though our limits are set to much more than that.

any insights would be helpful

```
dstat
You did not select any stats, using -cdngy by default.
--total-cpu-usage-- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai stl| read  writ| recv  send|  in   out | int   csw
 11   2  86   0   0| 177k  558k|   0     0 |   0     0 |5115  5139
 12   1  87   0   0|   0   188k|   0     0 |   0     0 |3832  3793
 12   1  87   0   0|   0   192k|   0     0 |   0     0 |4336  4444
 12   1  86   0   0|   0    84k| 458B  554B|   0     0 |3910  3824
 13   2  85   0   0|   0   140k|   0     0 |   0     0 |6372  7886
 12   1  87   0   0|   0   160k|   0     0 |   0     0 |4122  4648
 12   1  86   0   0|   0   208k|   0     0 |   0     0 |4392  5106
 13   1  86   0   0|   0   128k| 376B 2105B|   0     0 |5779  6885
 12   1  87   0   0|   0   144k| 458B  554B|   0     0 |4344  4342
 12   1  87   0   0|   0    96k|   0     0 |   0     0 |4357  4143
 12   1  87   0   0|   0   288k|   0     0 |   0     0 |4658  5195
 19   3  75   3   0|   0   122M|   0     0 |   0     0 |5418  4598
 20   3  76   2   0|   0   116M| 376B 2103B|   0     0 |7167  8856
 17   2  77   4   0|   0    66M| 458B  554B|   0     0 |5227  4737
 13   1  86   0   0|   0   112k|   0     0 |   0     0 |4687  4718
 12   1  87   0   0|   0    96k|   0     0 |   0     0 |3944  4091
 12   1  87   0   0|   0   160k| 396B  396B|   0     0 |4776  5348
```

**Comment by bowenwang1996** [comment]
@colindickson unfortunately we only use one core during database migration and have not had the time to optimize that.

**Comment by nikurt** [comment]
> for over 24 hours now

This is definitely not normal. Even archival RPC nodes are expected to upgrade in several hours: 4-8h
