### ISSUE TITLE
`impl From<&str> for Config` doesn't make sense

### ISSUE THREAD

**Issue by matklad** [near/nearcore#5680]
This is doesn't make sense and is unnecessary:

https://github.com/near/nearcore/blob/960274091a2a1952b3dfca39b5d2f5572fb7f712/nearcore/src/config.rs#L499-L504

We should remove this impl, and let the caller deserialize json *and handle errors* themselves. Ie, `serde_json::from_str::<Config>` is a strictly better way to do what this is trying to achieve.

**Comment by pmnoxx** [comment]
@matklad Here is a fix https://github.com/near/nearcore/pull/5683
