### ISSUE TITLE
Add mechanics for printing grouped logs.

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5684]
I have seen a few cases, where we added logs which were too spam-my.

We should add some mechanics - struct, which can use used for printing messages, like warnings, errors, at most once per second / minute / and printing their total counts over period of time.

Examples:
- https://github.com/near/nearcore/pull/5566

Design draft:

- new crate `near-logger`
- logger struct, which actor owns
- a trigger runs every 1m to flush logs
- NearLogger<PeerManagerLogs>

```
enum PeerManagerLogs {
    TRY_BAN_DISCONNECTED_PEER.
    NO_ROUTE_BACK,
    NO_ROUTE_TO_PEER,
    ...
}
```

Current code example:
```
    warn!(target: "network", "Try to ban a disconnected peer for {:?}: {:?}", ban_reason, peer_id);
```

How this will look in code:
```
self.log(LEVEL::WARN, "network",PeerManagerLogs::NO_ROUTE_TO_PEER, ||( "Try to ban a disconnected peer for {:?}: {:?}", ban_reason, peer_id));
```

api:
```
self.log(LOG_LEVEL, TARGET, ELEMENT_OF_ENUM,  example: Fn()-> ErrorMsg);
```

We will store a mapping `(LOG_LEVEL, ENUM) -> (COUNT PER MINUTE,  ONE INSTANCE OF THE MESSAGE)`

Some details, may change. this is just the current plan.

Possible changes:
- either a crate or a module inside existing crate
- some api changes, depending on what looks better, easier to use, etc.

Further improvements:
- Report aggregated data once per minute - that can be used for automatic analysis later
- Setup some nodes, which will report data at regular intervals. And, make them send the data over the network, that can be aggregated by some job, and then alter grouped / display in, for example in Graphana.

Worth reading about:
- Rsyslog - https://www.rsyslog.com/
- https://docs.rs/syslog/latest/syslog/
- https://github.com/Geal/rust-syslog

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near I added an issue for topic we discussed today.

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near I added a plan of a new crate, as discussed.

**Comment by bowenwang1996** [comment]
This is not network specific and we probably want to do that for the entirety of neard

**Comment by mm-near** [comment]
nice, I like it.

can you mention more details on how the frequency mapping would look like? (and how are we going to control it)

**Comment by pmnoxx** [comment]
> nice, I like it.
> 
> can you mention more details on how the frequency mapping would look like? (and how are we going to control it)

There are multiple uses cases. By default, we should group data in groups of 1m, for a few reasons:
- from my experience, while analyzing Time Series graphs, a frequency of more than 1m, wasn't that useful, due to there being a lot of variance
- If you group for longer period of time, let's say 1h or 10m. You risk loosing data, due to process closing, node crashing, etc. `1m` frequency seems to be a good default.
- To produce `1h`, `1day` stats, usually, people run `daily` or `hourly` jobs  to do the aggregation, and that's good enough for most cases.

**Comment by pmnoxx** [comment]
@mm-near Take a look at https://www.rsyslog.com/
