### ISSUE TITLE
Evaluate the threshold used for kicking a validator node who didn't produce enough chunks

### ISSUE THREAD

**Issue by janewang** [near/nearcore#5688]
A validator has reported that they have produced all the blocks, but was kicked because NotEnoughChunks

**Expected behavior**
Evaluate if the threshold used to kick a validator node for missing chunks is set to the appropriate number

**Screenshots**
<img width="1196" alt="Screen Shot 2021-12-06 at 3 17 55 PM" src="https://user-images.githubusercontent.com/734336/144925318-4b975780-8330-449c-82be-24ac9678d2b2.png">

**Version (please complete the following information): 1.23.0-rc1
- nearcore 1.23.0-rc.1
- testnet

**Comment by bowenwang1996** [comment]
@EgorKulikov @nikurt please take a look

**Comment by janewang** [comment]
Btw, if we are kicking of validators for missing chunks, we should probably alert. 

Some validators are complaining that they are confused when they are kicked:

> Thanks for the information, because I'm trying to figure it out and can not understand what the cause, the server is fine, blocks are produced (99-100% per epoch), but the node still kicked out.
 > same here. Just happened again. Without any of my alerts being triggered

**Comment by nikurt** [comment]
I can see that validator was missing chunks both before and after the upgrade.
Some epochs have only a few chunks missing and don't result in kicking the validator.
90% Kickout threshold still makes sense to me.

```
$ ./neard view_state epoch_info --validator-account-id namdokmai.pool.f863973.m0 protocol_version 48 | grep 'Validator ' -A 3

epochs-48:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-48-    produced: 716,
epochs-48-    expected: 860,
epochs-48-}
--
epochs-48:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughBlocks {
epochs-48-    produced: 110,
epochs-48-    expected: 216,
epochs-48-}
```

After upgrade:

```
$ ./neard view_state epoch_info --validator-account-id namdokmai.pool.f863973.m0 protocol_version 49 | grep 'Validator ' -A 3

epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 62,
epochs-49-    expected: 75,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 72,
epochs-49-    expected: 83,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 569,
epochs-49-    expected: 944,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 625,
epochs-49-    expected: 942,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 854,
epochs-49-    expected: 1009,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 895,
epochs-49-    expected: 1011,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 917,
epochs-49-    expected: 1044,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 904,
epochs-49-    expected: 1029,
epochs-49-}
--
epochs-49:Validator namdokmai.pool.f863973.m0 kickout: NotEnoughChunks {
epochs-49-    produced: 758,
epochs-49-    expected: 862,
epochs-49-}
```

**Comment by ama31337** [comment]
we've this issue right after update in mainnet, a lot of validators are kicked out next epoch

| Kicked out | abl_pool.poolv1.near                         | -                        | -       |
| Kicked out | anonymous.poolv1.near                        | -                        | -       |
| Kicked out | appload.poolv1.near                          | -                        | -       |
| Kicked out | binancestaking.poolv1.near                   | -                        | -       |
| Kicked out | dragonfly.poolv1.near                        | -                        | -       |
| Kicked out | dsrvlabs.poolv1.near                         | -                        | -       |
| Kicked out | electric.poolv1.near                         | -                        | -       |
| Kicked out | everstake.poolv1.near                        | -                        | -       |
| Kicked out | fish.poolv1.near                             | -                        | -       |
| Kicked out | fresh.poolv1.near                            | -                        | -       |
| Kicked out | galaxydigital.poolv1.near                    | -                        | -       |
| Kicked out | hashquark.poolv1.near                        | -                        | -       |
| Kicked out | jazza.poolv1.near                            | -                        | -       |
| Kicked out | legends.poolv1.near                          | -                        | -       |
| Kicked out | lux.poolv1.near                              | -                        | -       |
| Kicked out | magic.poolv1.near                            | -                        | -       |
| Kicked out | moonlet.poolv1.near                          | -                        | -       |
| Kicked out | nearcrowd.poolv1.near                        | -                        | -       |
| Kicked out | nodeasy.poolv1.near                          | -                        | -       |
| Kicked out | northernlights.poolv1.near                   | -                        | -       |
| Kicked out | sharpdarts.poolv1.near                       | -                        | -       |
| Kicked out | stakin.poolv1.near                           | -                        | -       |
| Kicked out | stardust.poolv1.near                         | -                        | -       |
