### ISSUE TITLE
Investigate garbage collection performance

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#5709]
Currently we run garbage collection in the same thread as client actor and if a node tracks all shard, it may incur unnecessary overhead that we would like to avoid. We should look into the time a node takes to run garbage collection and potentially optimize it by running it in a separate threads. Note that this is not necessarily easy to do due to reference counting on state. See [https://github.com/near/nearcore/pull/3090](https://github.com/near/nearcore/pull/3090) for more details.

**Comment by ashpooljh** [comment]
not stale

**Comment by mm-near** [comment]
We have added additional metrics and have config options to control how much GC is done.

We also plan to move it to a separate thread as a part of our efforts to parallelize client.

**Comment by bowenwang1996** [comment]
Superseded by https://github.com/near/nearcore/issues/10971
