### ISSUE TITLE
nayduck feature: adding the option to run tests multiple tests

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5716]
We encounter flaky tests quite often, because of randomness in some of our tests. It will be nice to add an option to run tests multiple times in nayduck to detect flaky tests. We can also make some especially flaky tests to run multiple times by default in the nightly file, so we can more easily see which commits break them.

**Comment by mzhangmzz** [comment]
cc @mina86 @mm-near @pmnoxx @yordanmadzhunkov

**Comment by mina86** [comment]
You can do that by prefixing test by a number, e.g.:
```
$ echo '10 pytest --timeout=480 sanity/routing_table_sync.py --features nightly_protocol,nightly_protocol_features' | ./scripts/nayduck.py -b master -s master -i 
Sending request ...
Success. Success.  http://nayduck.near.org/#/run/2298
```

**Comment by mzhangmzz** [comment]
Yes, that is possible. My other point is whether we should make specific test run more than once by default in the nightly run. It will help discovering flaky tests

**Comment by mina86** [comment]
> And for that, it will be better if there is an option to just specify a number instead of specifying the same line multiple times

Yes, you can do that by adding the number at the front of the line. ;)

There’s also a related issue: https://github.com/near/nearcore/issues/1868

**Comment by bowenwang1996** [comment]
Looks like there is no action item. Closing
