### ISSUE TITLE
Track errors and warnings

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5717]
We should track errors and warnings from the logs. Right now, they may go unnoticed because they are buried in the logs.

Specifically, I think we can create two more metrics for errors and warnings on graphana. We should set alert if the number of errors is non-zero (a node rarely errors and an error usually means something seriously bad has happened) and set some reasonable thresholds for warnings. We should also collect the details of errors (the full error lines) somewhere, although I'm not sure if graphana has the ability to display arbitrary texts.

**Comment by mzhangmzz** [comment]
cc @bowenwang1996 @mm-near @chefsale

**Comment by matklad** [comment]
cc @nikurt

**Comment by nikurt** [comment]
#9534
