### ISSUE TITLE
cargo test routing::archival_node is flaky

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5718]
https://buildkite.com/nearprotocol/nearcore/builds/9453#6e6adde1-1fe4-461f-be1b-99052ce0f804
I ran the test on master branch locally and it failed too

**Comment by mzhangmzz** [comment]
@mm-near @pmnoxx do you have an idea why it failed

**Comment by bowenwang1996** [comment]
Duplicate of #5357

**Comment by pmnoxx** [comment]
@bowenwang1996 I already wrote a fix: https://github.com/near/nearcore/pull/5639
