### ISSUE TITLE
`Cargo tests` takes a long time to run

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5726]
`Cargo tests` takes a long time to run we should try to fix that.

Changes:
- [ ] https://github.com/near/nearcore/pull/5725
- [ ] Compile tests with -O2 
- [ ] Split tests `integration-tests` vs not `integration tests` https://github.com/near/nearcore/pull/5710

**Comment by bowenwang1996** [comment]
Duplicate of #4490. Let's move the discussion there
