### ISSUE TITLE
PRs using `re` instead of `refactor` as per CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/nearcore#5730]
I have seen that PRs are using `re` term for refactor in PR's titles but as per this [section](https://github.com/near/nearcore/blob/master/CONTRIBUTING.md#submitting-the-pr) in `CONTRIBUTING.md` we have to use `refactor` for refactoring the code .

I think we have to update about it in `CONTRIBUTING.md`

**Comment by bowenwang1996** [comment]
I think `refactor` makes more sense :) We shouldn't update `CONTRIBUTING.md`

**Comment by Rishabhraghwendra18** [comment]
> 

Ok.. So I think we should add about it in PR template to remind contributors to use `refactor` term in PR's titles.
