### ISSUE TITLE
Error while setting up development environment 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/nearcore#5733]
I have forked & cloned the repo and ran `cargo build` in the root of the project but I got this error in the end:
```
error: failed to run custom build command for `librocksdb-sys v6.17.3`

Caused by:
  process didn't exit successfully: `/home/rishabh/Documents/contribution/nearcore/target/debug/build/librocksdb-sys-cc1bb3eedf0335e1/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/rishabh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.57.0/src/lib.rs:1975:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
May anyone help me to resolve this error ?

**Comment by pmnoxx** [comment]
Try installing
```
 sudo apt install libclang
```

**Comment by Rishabhraghwendra18** [comment]
I get this error now:
```
error[E0050]: method `obtain_state_part` has 6 parameters but the declaration in trait `RuntimeAdapter::obtain_state_part` has 5
   --> chain/chain/src/test_utils.rs:929:9
    |
929 | /         &self,
930 | |         _shard_id: ShardId,
931 | |         _block_hash: &CryptoHash,
932 | |         state_root: &StateRoot,
933 | |         part_id: u64,
934 | |         num_parts: u64,
    | |______________________^ expected 5 parameters, found 6
    |
   ::: chain/chain/src/types.rs:686:9
    |
686 | /         &self,
687 | |         shard_id: ShardId,
688 | |         block_hash: &CryptoHash,
689 | |         state_root: &StateRoot,
690 | |         partId: PartId
    | |______________________- trait requires 5 parameters

error[E0050]: method `validate_state_part` has 5 parameters but the declaration in trait `RuntimeAdapter::validate_state_part` has 4
   --> chain/chain/src/test_utils.rs:946:9
    |
946 | /         &self,
947 | |         _state_root: &StateRoot,
948 | |         part_id: u64,
949 | |         num_parts: u64,
950 | |         _data: &Vec<u8>,
    | |_______________________^ expected 4 parameters, found 5
    |
   ::: chain/chain/src/types.rs:696:9
    |
696 | /         &self,
697 | |         state_root: &StateRoot,
698 | |         partId: PartId,
699 | |         data: &Vec<u8>,
    | |______________________- trait requires 4 parameters

error[E0061]: this function takes 4 arguments but 5 arguments were supplied
    --> chain/chain/src/chain.rs:1859:14
     |
1859 |             .obtain_state_part(shard_id, &sync_prev_hash, &state_root, part_id, num_parts)
     |              ^^^^^^^^^^^^^^^^^ --------  ---------------  -----------  -------  --------- supplied 5 arguments
     |              |
     |              expected 4 arguments
     |
note: associated function defined here
    --> chain/chain/src/types.rs:685:8
     |
685  |     fn obtain_state_part(
     |        ^^^^^^^^^^^^^^^^^

error[E0061]: this function takes 3 arguments but 4 arguments were supplied
    --> chain/chain/src/chain.rs:2066:34
     |
2066 |         if !self.runtime_adapter.validate_state_part(&state_root, part_id, num_parts, data) {
     |                                  ^^^^^^^^^^^^^^^^^^^ -----------  -------  ---------  ---- supplied 4 arguments
     |                                  |
     |                                  expected 3 arguments
     |
note: associated function defined here
    --> chain/chain/src/types.rs:695:8
     |
695  |     fn validate_state_part(
     |        ^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0050, E0061.
For more information about an error, try `rustc --explain E0050`.
error: could not compile `near-chain` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by pmnoxx** [comment]
@Rishabhraghwendra18 
It looks like you are not code that's up to date.

Your error code says
`error[E0061]: this function takes 3 arguments but 4 arguments were supplied`
about function `obtain_state_part` on line 685

By looking at the code I see that this function is on line `690` and has 4 arguments
```
 fn validate_state_part(
        &self,
        state_root: &StateRoot,
        part_id: u64,
        num_parts: u64,
        data: &Vec<u8>,
    ) -> bool;
```

**Comment by Rishabhraghwendra18** [comment]
@pmnoxx I re-ran the command `cargo build` in project root directory two times and both the time my laptop gets hanged at this step:
![WhatsApp Image 2021-12-13 at 9 12 32 AM](https://user-images.githubusercontent.com/43534227/145749359-38725dc0-f285-49b4-8505-aeca97aa6aed.jpeg)

I am using Ubuntu 20.04 LTS on my i5 intel 8th gen , 8 gb ram , 1TB HDD laptop . May you have any idea what's going wrong ?

**Comment by pmnoxx** [comment]
> @pmnoxx I re-ran the command `cargo build` in project root directory two times and both the time my laptop gets hanged at this step: ![WhatsApp Image 2021-12-13 at 9 12 32 AM](https://user-images.githubusercontent.com/43534227/145749359-38725dc0-f285-49b4-8505-aeca97aa6aed.jpeg)
> 
> I am using Ubuntu 20.04 LTS on my i5 intel 8th gen , 8 gb ram , 1TB HDD laptop . May you have any idea what's going wrong ?

Yes, by default if you use `cargo build`. You will build other targets as well. That requires memory usage jump to around 40gb on my machine.

Try usign `cargo build -p neard`.

**Comment by Rishabhraghwendra18** [comment]
@pmnoxx Now the installation is complete successful and `cargo run` is running too. But when I run `cargo test` in the root of the project , it again downloads some packages and my pc get hang 
![WhatsApp Image 2021-12-13 at 4 46 10 PM](https://user-images.githubusercontent.com/43534227/145804705-dadbe81c-ab11-4b24-be2d-5dc45f1b4a37.jpeg)
I have also tried `cargo build -p near-rosetta-rpc` but then also if I again run `cargo test` it agains start compiling which hang my pc

**Comment by pmnoxx** [comment]
@Rishabhraghwendra18 Try running `cargo test -j 1`.

**Comment by Rishabhraghwendra18** [comment]
Finally it worked . It did slow down my laptop but I let it do it works . Finally all set up is done. Thanks

**Comment by pmnoxx** [comment]
@Rishabhraghwendra18 Np, I'm glad I could help,
By my estimates we need 4-8gb of memory per single thread. `-j THREADS` options needs to be adjusted.

**Comment by Rishabhraghwendra18** [comment]
oh.. that's a huge memory usage per thread . Anyways thanks , you saved my day otherwise I will be waiting the whole day for environment to setup .

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near It may be worth mentioning in `README.md`, that `cargo test` needs `4-8gb` per thread to run.
