### ISSUE TITLE
`near-api-js test` causes nondeterministic failures in CI.

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5757]
Yarn test keeps failing. 

We have disabled it in https://github.com/near/nearcore/pull/5754

Here is an example of CI failure, caused by it.
https://buildkite.com/nearprotocol/nearcore/builds/9750#834c14d9-c161-45c7-b4e1-4acae3b92a13

We should either:
- Move it to `nayduck` and run it there. It may still fail, at least it won't block CI.
- Figure out why this test is flunky and fix it.

Related cleanup:
- #5796 
- #5797

**Comment by bowenwang1996** [comment]
https://github.com/near/nearcore/pull/5754#issuecomment-991772399

**Comment by bowenwang1996** [comment]
@pmnoxx @mm-near let's fix the flaky test and re-enable near-api-js tests. I agree that we should have a discussion about how in the future downstream libraries should test against nearcore changes, but for now it is important that we avoid breaking near-api-js which is the dominant client side library.

**Comment by pmnoxx** [comment]
> @pmnoxx @mm-near let's fix the flaky test and re-enable near-api-js tests. I agree that we should have a discussion about how in the future downstream libraries should test against nearcore changes, but for now it is important that we avoid breaking near-api-js which is the dominant client side library.

@bowenwang1996  I'm glad we are in agreement, that the CI shouldn't have nondeterministic failures.

The first step to fixing those failures is to be try to reproduce them on localhost.

Running the following command
```shell
scripts/test_nearlib.sh
```
results in a failure
```
+ export RUST_BACKTRACE=full
+ RUST_BACKTRACE=full
+ export NEAR_PID=180029
+ NEAR_PID=180029
+ trap 'pkill -15 -P $NEAR_PID' 0
+ ./scripts/start_unittest.py --local
+ rm -rf near-api-js near-shell create-near-app
+ git clone https://github.com/near/near-api-js.git
Cloning into 'near-api-js'...
Starting unittest nodes with test.near account and seed key of alice.near
cargo 1.56.0 (4ed5d137b 2021-10-04)
   Compiling state-viewer v0.0.0 (/home/pmnoxx/repos/nearcore.master/test-utils/state-viewer)
remote: Enumerating objects: 24099, done.
remote: Counting objects: 100% (1845/1845), done.
remote: Compressing objects: 100% (797/797), done.
remote: Total 24099 (delta 1321), reused 1451 (delta 1040), pack-reused 22254
Receiving objects: 100% (24099/24099), 8.65 MiB | 11.57 MiB/s, done.
Resolving deltas: 100% (16787/16787), done.
+ git clone https://github.com/near/near-shell.git
Cloning into 'near-shell'...
remote: Enumerating objects: 5592, done.
remote: Counting objects: 100% (828/828), done.
remote: Compressing objects: 100% (523/523), done.
remote: Total 5592 (delta 508), reused 549 (delta 301), pack-reused 4764
Receiving objects: 100% (5592/5592), 2.92 MiB | 15.59 MiB/s, done.
Resolving deltas: 100% (3519/3519), done.
+ git clone https://github.com/near/create-near-app.git
Cloning into 'create-near-app'...
remote: Enumerating objects: 5821, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 5821 (delta 171), reused 77 (delta 37), pack-reused 5572
Receiving objects: 100% (5821/5821), 4.10 MiB | 14.58 MiB/s, done.
Resolving deltas: 100% (3940/3940), done.
+ export NODE_ENV=local
+ NODE_ENV=local
++ pwd
++ dirname scripts/test_nearlib.sh
+ SRC_DIR=/home/pmnoxx/repos/nearcore.master/scripts
+ export HOME=/home/pmnoxx/repos/nearcore.master/scripts/../testdir
+ HOME=/home/pmnoxx/repos/nearcore.master/scripts/../testdir
+ cd near-api-js
+ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
+ pkill -15 -P 180029
Compilation failed, aborting    
```

Indeed `$REPO_DIR/testdir` is empty.

@bowenwang1996 Can we first start by fixing the script, and making it work on the localhost?

**Comment by pmnoxx** [comment]
@bowenwang1996 Can you update the documentation of `scripts/test_nearlib.sh`.
It's not clear by reading that file alone, that we are testing `near-api-js`.

**Comment by pmnoxx** [comment]
> @pmnoxx @mm-near let's fix the flaky test and re-enable near-api-js tests. I agree that we should have a discussion about how in the future downstream libraries should test against nearcore changes, but for now it is important that we avoid breaking near-api-js which is the dominant client side library.

@bowenwang1996 A quick fix, would be to retry the test if it fails.
