### ISSUE TITLE
Pull Request template is not showing up while creating pull request

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/nearcore#5800]
When you make pull request , you will not see the Pull Request template as discussed [here](https://github.com/near/nearcore/blob/master/CONTRIBUTING.md#submitting-the-pr) . It discuss about the format of the PR which I think should be visible while creating a PR to remind the contributor to follow the template.

**Comment by bowenwang1996** [comment]
It is a known github limitation. I believe you cannot have more than one PR templates and still expect them to get triggered automatically when you create a PR.

**Comment by Rishabhraghwendra18** [comment]
ok.. I don't know about that github has this kind of limitation . The current PR was not up-to-date and as per docs it had some other kind of PR template so I thought of making a separate file for this . If you thought that we could remove the old PR template then I would removed that .

No problem , I will close this issue
