### ISSUE TITLE
error: field is never read: `memory` in 1.23.0-rc.1.

### ISSUE THREAD

**Issue by guertsen** [near/nearcore#5807]
**Describe the bug**
make sandbox of 1.23.0-rc.1 fails and produces the following error:

```
   Compiling near-vm-runner v0.0.0 (/home/timofei/Code/nearcore/runtime/near-vm-runner)
error: field is never read: `memory`
   --> runtime/near-vm-runner/src/imports.rs:282:9
    |
282 |         memory: wasmer::Memory,
    |         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`

error: could not compile `near-vm-runner` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:69: sandbox] Error 101
```

**To Reproduce**
branch 1.23.0-rc.1.
git clone https://github.com/near/nearcore
make sandbox

**Expected behavior**
The build process is supposed to work.

**Screenshots**

**Version (please complete the following information):**
- Ubuntu 20.04.3 LTS
- rustup 1.24.3 (ce5817a94 2021-05-31)
- rustc 1.55.0 (c8dfcfe04 2021-09-06)
- testnet

**Additional context**

**Comment by bowenwang1996** [comment]
@matklad please take a look

**Comment by matklad** [comment]
Fixed by https://github.com/near/nearcore/pull/5803, but blocked by process -- olonho is OOO this week, and we don't have other code owners

**Comment by matklad** [comment]
was fixed!
