### ISSUE TITLE
Disallow beneficiary of funds from deleted account to be itself

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#5816]
**Describe the bug**
Account deletion transaction where `beneficiaryId` == `accountId` should fail.

**To Reproduce**
See example tx: https://explorer.testnet.near.org/transactions/3GTFEzvTfDiAxm8fdpZeWP7NjRFTjFJaDYQNX6ANAUns
For example: 
```
$ near delete ww.testmewell.testnet ww.testmewell.testnet
Deleting account. Account id: ww.testmewell.testnet, node: https://rpc.testnet.near.org, helper: https://helper.testnet.near.org, beneficiary: ww.testmewell.testnet
Receipt:
	Failure [ww.testmewell.testnet]: Error: Can't complete the action because account ww.testmewell.testnet doesn't exist
Transaction Id 82Bb4LPPQzNm34WPbFY1UjeQWBPTQUuDRjCeL3dsuYRN
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.testnet.near.org/transactions/82Bb4LPPQzNm34WPbFY1UjeQWBPTQUuDRjCeL3dsuYRN
Account ww.testmewell.testnet for network "testnet" was deleted.
```

**Expected behavior**
Transaction doesn't get accepted and account doesn't get deleted in the first place.

**User feedback reference**
See: https://stackoverflow.com/questions/70313278/a-deleted-testnet-account-gets-fully-restored

**Comment by frol** [comment]
@ilblackdragon There is no need to alter the protocol. It is as valid operation as transfer of 0 NEAR. The account got actually deleted just fine, and the remaining tokens were burnt. See my reply there: https://stackoverflow.com/a/70339847/1178806
