### ISSUE TITLE
No peers available on testnet (happens after a few minutes)

### ISSUE THREAD

**Issue by vans163** [near/nearcore#5818]
**Describe the bug**
Testnet node goes into a mode where there are no peers available but its connected. This happens after it starts and connects to a few peers. Then drops all peers.

**To Reproduce**
Run testnet node, I am not sure exactly how its reproduced, some help to log more factors would be appreciated, running with RUST_LOG spams way too much.

**Expected behavior**
Node is correctly synced and keeping up.

**Screenshots**
![image](https://user-images.githubusercontent.com/3028982/145855931-197c479a-5c8e-4591-a578-5bc6ebee5bb9.png)
Left is mainnet node right is testnet node, both running on the same dedicated server bound to different addresses.

**Version (please complete the following information):**
1.23.0-rc.1
rustc 1.57.0 (f1edd0429 2021-11-29)
testnet

**Comment by vans163** [comment]
I think I see the problem, this was because the new release came out and I guess nearup upgrades immediately all the nodes, but I just compiled from source?  

Something useful on the logs I think is if the peer rejected you due to the peer having a higher version. Right now for someone who did not code nearcore, using RUST_LOG there is way too much logs printed to make sense of anything, and a strong error like this (why the peer rejected) would be useful. Unless the reason for the peer not reporting anything (but killing the connection) is for some kind of protection vs ddos but I am not sure how it would help since the connect is already established at this point and at least 1 packet with data is sent.

**Comment by TrevorJTClarke** [comment]
> this was because the new release came out

@vans163 does this mean you were able to solve the issue? If so, what steps? (so basically because 1.23.0 came out, any nearup instances go there but can't do anything because the testnet nodes are mostly on 1.23.0-rc1??)

**Comment by vans163** [comment]
> > this was because the new release came out
> 
> @vans163 does this mean you were able to solve the issue? If so, what steps? (so basically because 1.23.0 came out, any nearup instances go there but can't do anything because the testnet nodes are mostly on 1.23.0-rc1??)

Yea this can be closed. I think its because I did not use nearup (so my config.json and neard checksum was off from what the others on testnet used), I just made a ticket of it because I feel the neard logging does not express critical errors so well. 

If its feasible (to not reveal too much information to potential attackers), examples of what I feel are critical are peers rejecting you (right now its just if your chainid/genesis dont match is logged), a corrupt database, validation errors (if you signed a block that did not get accepted [the errors presented on the smartcontract view call about validator failures are too generic]).

**Comment by janewang** [comment]
@nikurt @bowenwang1996 FYI this is happening on testnet.

**Comment by bowenwang1996** [comment]
Closing as @vans163 mentioned that there was no real issue

**Comment by vans163** [comment]
> Closing as @vans163 mentioned that there was no real issue

It seems 10+ people thumbs upped a discord message that asked if they were having this issue, so its just not being reported.
