### ISSUE TITLE
My testnet node stopped working with No peers 

### ISSUE THREAD

**Issue by dimaelkhsos** [near/nearcore#5824]
Dec 13 21:48:55.999  INFO stats: #70617185 Downloading headers 89.83% (3305668)   2/1/40 peers ⬇ 99.1kiB/s ⬆ 73.0kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 431.6 MiB
Dec 13 21:49:01.829  WARN sync: Sync: ban a fraudulent peer: ed25519:49m4CpgA6A871aPzXiXxQEXfD8TsDgx3eJka3HSBtPWT@65.21.197.23:24567, claimed height: 74893263
Dec 13 21:49:01.829  WARN network: Banning peer Some(ed25519:49m4CpgA6A871aPzXiXxQEXfD8TsDgx3eJka3HSBtPWT@65.21.197.23:24567) for HeightFraud
Dec 13 21:49:01.829  WARN network: Banning peer ed25519:49m4CpgA6A871aPzXiXxQEXfD8TsDgx3eJka3HSBtPWT for HeightFraud
Dec 13 21:49:06.001  INFO stats: #70617185 Downloading headers 89.83% (3305668)   1/1/40 peers ⬇ 64 B/s ⬆ 64 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 415.8 MiB
Dec 13 21:49:16.002  INFO stats: #70617185 Downloading headers 93.65% (1980048)   1/1/40 peers ⬇ 30.3kiB/s ⬆ 80 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 413.7 MiB
Dec 13 21:49:21.839  WARN sync: Sync: ban a fraudulent peer: ed25519:2RG49WPUTXfWAh29P6ZrmnmEde5uVyCd8FU3hJDXhitL@138.197.148.203:24567, claimed height: 73567643
Dec 13 21:49:21.839  WARN network: Banning peer Some(ed25519:2RG49WPUTXfWAh29P6ZrmnmEde5uVyCd8FU3hJDXhitL@138.197.148.203:24567) for HeightFraud
Dec 13 21:49:21.839  WARN network: Banning peer ed25519:2RG49WPUTXfWAh29P6ZrmnmEde5uVyCd8FU3hJDXhitL for HeightFraud
Dec 13 21:49:21.862  WARN client: Sync: no peers available, disabling sync
Dec 13 21:49:26.003 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:49:31.863  WARN client: Sync: no peers available, disabling sync
Dec 13 21:49:36.004 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:49:41.864  WARN client: Sync: no peers available, disabling sync
Dec 13 21:49:46.006 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:49:56.007  INFO stats: #70617185 Downloading headers 89.83% (3305754)   1/1/40 peers ⬇ 97.8kiB/s ⬆ 73.0kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 398.9 MiB
Dec 13 21:50:01.874  WARN sync: Sync: ban a fraudulent peer: ed25519:7ynwTZJ6vwdJUysJkbd3iZYLnZ4BCvottWETDa95S4ej@5.161.64.8:24567, claimed height: 74893349
Dec 13 21:50:01.874  WARN network: Banning peer Some(ed25519:7ynwTZJ6vwdJUysJkbd3iZYLnZ4BCvottWETDa95S4ej@5.161.64.8:24567) for HeightFraud
Dec 13 21:50:01.875  WARN network: Banning peer ed25519:7ynwTZJ6vwdJUysJkbd3iZYLnZ4BCvottWETDa95S4ej for HeightFraud
Dec 13 21:50:01.907  WARN client: Sync: no peers available, disabling sync
Dec 13 21:50:06.009 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:50:11.909  WARN client: Sync: no peers available, disabling sync
Dec 13 21:50:16.011 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:50:21.910  WARN client: Sync: no peers available, disabling sync
Dec 13 21:50:26.013 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:50:31.910  WARN client: Sync: no peers available, disabling sync
Dec 13 21:50:36.014 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:50:41.912  WARN client: Sync: no peers available, disabling sync
Dec 13 21:50:46.015 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:50:56.017  INFO stats: #70617185 Downloading headers 89.83% (3305845)   1/1/40 peers ⬇ 98.6kiB/s ⬆ 73.0kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 403.6 MiB
Dec 13 21:51:01.923  WARN sync: Sync: ban a fraudulent peer: ed25519:E319a9GQ3VmnQsNjtzDQ2XggkddnYiThmf1RUFQVQoZD@5.9.136.82:24567, claimed height: 74893440
Dec 13 21:51:01.923  WARN network: Banning peer Some(ed25519:E319a9GQ3VmnQsNjtzDQ2XggkddnYiThmf1RUFQVQoZD@5.9.136.82:24567) for HeightFraud
Dec 13 21:51:01.924  WARN network: Banning peer ed25519:E319a9GQ3VmnQsNjtzDQ2XggkddnYiThmf1RUFQVQoZD for HeightFraud
Dec 13 21:51:01.957  WARN client: Sync: no peers available, disabling sync
Dec 13 21:51:06.018 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:51:11.957  WARN client: Sync: no peers available, disabling sync
Dec 13 21:51:16.020 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:51:21.959  WARN client: Sync: no peers available, disabling sync
Dec 13 21:51:26.022 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown
Dec 13 21:51:31.960  WARN client: Sync: no peers available, disabling sync
Dec 13 21:51:36.024 ERROR client: Unwrap error: Validator Error: IO: Unexpected variant index: 146
 Cause: Unknown

**Comment by TrevorJTClarke** [comment]
Adding more context here, had the same issues as well, here's the output:
<img width="1156" alt="Screen Shot 2021-12-15 at 11 12 48 AM" src="https://user-images.githubusercontent.com/2633184/146251454-c16f7047-996a-4c50-bb06-cbb5e097bcd4.png">

This was found to happen 2 times, following entirely new machines built on Dec 12th & Dec 14th. Both times the machine was using 1.23.0-rc1
As you can see from the screenshot, a fresh download of RPC snapshot unpacks successfully but somehow has issues and shows "DB Not Found Error"
The other thing seen in the image is the headers download - It seems that the DB issue can be sort of resolved after a restart, but once headers reach 100%, then there is an endless cycle of trying to start getting blocks and falling behind again.
This machine has 20gb ram, 500 SSD, 8 CPU, and 1gb fiber internet connection, which prior to this week worked.

**Comment by janewang** [comment]
@nikurt @bowenwang1996 FYI this is happening on testnet.

**Comment by bowenwang1996** [comment]
> The other thing seen in the image is the headers download - It seems that the DB issue can be sort of resolved after a restart, but once headers reach 100%, then there is an endless cycle of trying to start getting blocks and falling behind again.

Does it show the same DBNotFoundError?

**Comment by TrevorJTClarke** [comment]
> Does it show the same DBNotFoundError?

yes it does:
```
DB Not Found Error: EE9JyX51msdCawbXXmStJ6PjruzPbhtYfzU5jXRWyyeM })
Dec 16 18:46:10.829 ERROR client: Handle block production failed: Chain(Error { inner:    0: failure::backtrace::Backtrace::new
   1: <near_chain_primitives::error::Error as core::convert::From<near_primitives::errors::EpochError>>::from
   2: <nearcore::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::get_epoch_id_from_prev_block
   3: near_client::client_actor::ClientActor::check_triggers
   4: <F as actix::utils::TimerFuncBox<A>>::call
   5: <actix::utils::TimerFunc<A> as actix::fut::ActorFuture>::poll
   6: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
   7: tokio::runtime::task::raw::poll
   8: tokio::task::local::LocalSet::tick
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: neard::cli::NeardCmd::parse_and_run
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_main
  14: _start


DB Not Found Error: EE9JyX51msdCawbXXmStJ6PjruzPbhtYfzU5jXRWyyeM })
Dec 16 18:46:18.299  INFO stats: #75024302 Downloading headers 100.00% (573)   2/1/40 peers ⬇ 121.3kiB/s ⬆ 68.2kiB/s 0.00 bps 0 gas/s CPU: 9%, Mem: 1.3 GiB
```

**Comment by bowenwang1996** [comment]
@TrevorJTClarke I tried to reproduce the issue but could not. The node I ran didn't have problems with syncing

**Comment by zouyuxuan** [comment]
i have the same problem ![image](https://user-images.githubusercontent.com/33485252/147023160-f8778b59-bf7b-4d91-9bf0-44f56b891639.png)

**Comment by dimaelkhsos** [comment]
same happened now for mainnet, how can we get our nodes running

**Comment by bowenwang1996** [comment]
@dimaelkhsos did you use nearup as well?

**Comment by dimaelkhsos** [comment]
Yes i am using nearup

**Comment by nikurt** [comment]
Strange, gave this a try and couldn't reproduce it.

**Comment by dimaelkhsos** [comment]
any update, still facing same issue

**Comment by bowenwang1996** [comment]
@nikurt did you try to reproduce by running a node through nearup?

**Comment by nikurt** [comment]
Made another attempt at reproducing this issue following @dimaelkhsos instructions. No luck, after 24 hours, the node was happy: synced and closely following the chain head.
I can only guess that the is either in some other part of the environment or gets triggered by something specific to the environment.
All my tests were on ubuntu GCP machines of type e2-standard-8 with SSD persistent disk.
