### ISSUE TITLE
Unable to connect to mainnet from local build

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5853]
After building a local version of the binary. I'm unable to connect to MAINNET

Here are the error logs:

```
Dec 15 11:33:00.323  WARN network: Unable to connect to a node (ed25519:33g3PZRdDvzdRpRpFRZLyscJdbMxUA3j3Rf2ktSYwwF8@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:01.328  WARN network: Unable to connect to a node (ed25519:CDQFcD9bHUWdc31rDfRi4ZrJczxg8derCzybcac142tK@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:02.436  WARN network: Unable to connect to a node (ed25519:Cw1YyiX9cybvz3yZcbYdG7oDV6D7Eihdfc8eM1e1KKoh@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:03.249  WARN network: Unable to connect to a node (ed25519:33g3PZRdDvzdRpRpFRZLyscJdbMxUA3j3Rf2ktSYwwF8@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:04.682  WARN network: Unable to connect to a node (ed25519:Cw1YyiX9cybvz3yZcbYdG7oDV6D7Eihdfc8eM1e1KKoh@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:05.836  WARN network: Unable to connect to a node (ed25519:CDQFcD9bHUWdc31rDfRi4ZrJczxg8derCzybcac142tK@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)
Dec 15 11:33:07.395  WARN network: Unable to connect to a node (ed25519:86EtEy7epneKyrcJwSWP7zsisTkfDRH5CFVszt4qiQYw@0.0.0.0:24567) due to a network protocol version mismatch. Our version: (50, 49), their: (48, 34)

```

**Comment by bowenwang1996** [comment]
Good catch! Looks like this happens because while in the latest release the protocol version is 49, mainnet has not been upgraded yet so some nodes are running protocol version 48. On the other hand, due to #5802, on master the protocol version is 50. Given that we have a check that protocol version on master <= protocol version in latest release +1, and that protocol version in latest release <= mainnet protocol version + 1, we have protocol version on master <= mainnet protocol version + 2. So from this perspective, we can change oldest protocol version we support to current protocol version - 2.

**Comment by panbhatt** [comment]
is their any traction on this issue, I am still getting an issue. 
Build the source code from three different tags (1.25.0 - as mentioned in the documentation), 1.28.0 and 1.30.0, Each time my RPC node is unable to sync up with the other peers on the MAINNET. I am following the same steps as present in the NEAR documentation. 
Below is the screenshot for running 1.27.0 on and try to sync it with MAINNET. Please anyone can hep. 
![image](https://user-images.githubusercontent.com/1473470/212392088-4985a7b2-daa2-4cdb-9581-77a1f1e3df17.png)
https://files.slack.com/files-pri/T02CYRENF-F04K7LM6CLR/image.png

**Comment by akhi3030** [comment]
@mzhangmzz, @walnut-the-cat, looks like a core team issue.  Can one of you please look into it and figure out if we need to reopen the issue or create a new one, etc.

**Comment by mm-near** [comment]
Hey @panbhatt - the current mainnet is running the version 1.30 - so when you try to connect with older one, your requests will be rejected.

Can you point me at the place in documentation where you found 1.25 ?

**Comment by panbhatt** [comment]
Team, here is the documentation link. https://near-nodes.io/rpc/run-rpc-node-without-nearup 
we reached to the team on the discord server and they point us out that the documentation is way behind what MAINNET is running on. so we switched to 1.30.0 and all works fine after that.
