### ISSUE TITLE
CPU and Mem pinned after network slowdown

### ISSUE THREAD

**Issue by dtp263** [near/nearcore#5854]
**Describe the bug** After a network slowdown, caused by an AWS outage, a couple nodes got stuck in a bad state. These nodes were:

1.  in sync
2.  logging valid logs
3.  consistently not signing blocks

A node restart fixed the issue.

**To Reproduce** Not sure how to reproduce.

**Expected behavior** A fully synced node that is logging valid logs should produce blocks.

**Screenshots** Example Logs:

 #55223386 HnbdTPGKsCdsU2jT3Ww42NQyF5bVC1dWdDk5o4XCdqPa V/59 28/12/40 peers ⬇ 314.9kiB/s ⬆ 366.3kiB/s 0.50 bps 88.95 Tgas/s CPU: 696%, Mem: 7.2 GiB
 #55223393 8caakZa9eY5wPeoR5171Bc8wk88dK6CEqSfQq76BprRP V/59 28/14/40 peers ⬇ 325.2kiB/s ⬆ 439.6kiB/s 0.60 bps 50.79 Tgas/s CPU: 697%, Mem: 7.0 GiB
 #55223398 44L3prnLpBBddw8j1SDBc3YPbKrMD357t1Myivfe2VJw V/59 28/16/40 peers ⬇ 279.0kiB/s ⬆ 414.0kiB/s 0.20 bps 61.71 Tgas/s CPU: 697%, Mem: 7.0 GiB
 #55223410 HCqwCe1JSanuFML9nreHucbSvAx78rCgR5CuCfPD1mP7 V/59 28/15/40 peers ⬇ 312.1kiB/s ⬆ 444.1kiB/s 0.70 bps 189.97 Tgas/s CPU: 696%, Mem: 7.0 GiB

Memory and CPU Spikes (restart happened around 9:45 on graph) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/3021938/146255609-f20efd5c-bea7-4e2a-9106-5a24313e9626.png)</span>](https://user-images.githubusercontent.com/3021938/146255609-f20efd5c-bea7-4e2a-9106-5a24313e9626.png)

Missing Blocks even after catching up from the network turbulence [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/3021938/146255050-75cffb8c-3e3b-4536-b1a6-e3a60e5a5a4d.png)</span>](https://user-images.githubusercontent.com/3021938/146255050-75cffb8c-3e3b-4536-b1a6-e3a60e5a5a4d.png)

**Version (please complete the following information):**

*   nearcore - 1.21.0
*   docker - yes
*   network - mainnet

**Additional context** This happened during/right after the AWS outage.

**Comment by bowenwang1996** [comment]
This feels like a network-related issue. I suspect that when a node encounters some network connection issue and later on recovers from it, something breaks and causes cpu usage to spike. cc @mm-near
