### ISSUE TITLE
make process_partial_encoded_chunk only validate parts and receipts the node cares about

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5885]
now process_partial_encoded_chunk checks validity for all parts and receipts include the partial encoded chunk. There are two optimizations we can make 
1) only check parts and receipts that are not in the current chunk entry
2) only check parts and receipts that the node cares about
Note that if we only validate some parts and receipts, it is important to only store the parts and receipts that we have validated.

**Comment by bowenwang1996** [comment]
@mzhangmzz is this a duplicate of https://github.com/near/nearcore/issues/3662 ?

**Comment by mzhangmzz** [comment]
> @mzhangmzz is this a duplicate of #3662 ?

Yes, I'll close the request and update 3662

**Comment by mina86** [comment]
@mzhangmzz, there’s still this TODO comment in the code:

```rust
        // 1.d Checking part_ords' validity
        let num_total_parts = self.runtime_adapter.num_total_parts();
        for part_info in partial_encoded_chunk.parts.iter() {
            // TODO: only validate parts we care about
            // https://github.com/near/nearcore/issues/5885
            self.validate_part(header.encoded_merkle_root(), part_info, num_total_parts)?;
        }
```

Can it be removed?
