### ISSUE TITLE
Rewards were not granted to `kicked` validators in 2 epochs prior the kick.

### ISSUE THREAD

**Issue by AngelBlock** [near/nearcore#5903]
**Describe the bug**
After recent protocol update on the 2021-12-17 Rewards were not granted to `kicked` (described here #5901) validators in 2 epochs prior the kick event.

No owner account stake changes recorded from 55439472 to 55482672 and 55482672 to 55525872

**Screenshots**
<img width="607" alt="Screenshot 2021-12-19 at 19 51 48" src="https://user-images.githubusercontent.com/80400686/146688844-6543ae65-98e7-435c-9807-f67e722fb1ad.png">

<img width="749" alt="Screenshot 2021-12-19 at 19 52 53" src="https://user-images.githubusercontent.com/80400686/146688879-e7f41828-9462-4cc6-b747-2c6f42a507be.png">

So last stake change recorded from epoch 55396271 to 55439472

Our node (stardust.poolv1.near) received an alert: You were kicked, because NotEnoughChunks: produced: 414, expected: 465

We were updated to the latest version in time.

Kicked in the last epoch (issue: #5901), absent in current and next, so will be total of 4 epochs of no rewards after a single kick. 

**Version (please complete the following information):**
- nearcore commit/branch: neard (release 1.23.0) (build 1.23.0) (protocol 49) (db 30)
- rust version (if local): rustc 1.57.0 (f1edd0429 2021-11-29)
- mainnet

**Comment by bowenwang1996** [comment]
Just to make it more clear, your node is kicked out in epoch T and you said that it didn't receive rewards for epoch T, T+1, T+2, and T+3? If it is kicked out in epoch T and absent in epoch T+2 and T+3, then for those epochs it should not receive any rewards. Now the question is what happened in epoch T+1. Was your node kicked out in epoch T+1 as well (did not produce enough blocks or chunks)?

**Comment by AngelBlock** [comment]
> Just to make it more clear, your node is kicked out in epoch T and you said that it didn't receive rewards for epoch T, T+1, T+2, and T+3? If it is kicked out in epoch T and absent in epoch T+2 and T+3, then for those epochs it should not receive any rewards. Now the question is what happened in epoch T+1. Was your node kicked out in epoch T+1 as well (did not produce enough blocks or chunks)?

That is a good question I don't have answer to as I don't have means to check that at the time. If assume that it was than it all makes sense and we can close the call, is there a way to check retrospectively?

**Comment by AngelBlock** [comment]
Closing due to inability to check T+1 epoch performance retrospectively.
