### ISSUE TITLE
Devx: Add git hooks

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/nearcore#5924]
I am contributing to the repo and I have found that CI fails if we haven't run `cargo fmt` before pushing our code . I think it will be a good idea to add a git hook which runs `cargo fmt` every time whenever we commit .  This can save time to go back again and run the command and then push the changes .

I have found a package regarding it called [`cargo-husky`](https://crates.io/crates/cargo-husky) . I will like to add this package in the workspace as it can little bit speed up the development process. What are your views on this ?

**Comment by bowenwang1996** [comment]
> I will like to add this package in the workspace as it can little bit speed up the development process. What are your views on this ?

@matklad @nagisa what are your thoughts on this

**Comment by matklad** [comment]
We experimented with formatting hooks in rust-analyzer, and I think it’s better not to, for two main reasons.

*First*, git hooks are not designed to be shared. They don’t “just work” when you clone a repo, you need manual setup steps or extra tools, which add accidental complexity.

*Second*, in my experience rustfmt in particular can be quite annoying when used as a hook, as it can fail on incomplete syntax (and sometimes I do want to commit whatever I have to, eg, switch branches), and it adds perceivable latency to the commit process.

My ideal solution would be to just make `cargo test` a reasonable thing to run locally when submitting a PR (and `cargo test` already checks formatting).

In the meantime, anybody who finds formatting hook useful can add one for themselves, as, again, the hooks are not shared.

**Comment by nagisa** [comment]
I had 101 bad experiences with hooks and I'm not sure if I'm ready for the 102nd. Any workflow that is dependent on git hooks is a hard pass for me personally.

But if others can derive value here, I definitely don't see a problem with them checking in a config for [`pre-commit`](https://pre-commit.com/) or somesuch that they could then recommend people to `pre-commit install` or something. As long as we make sure that there is also a serviceable workflow for those who don't want to deal with hooks and we don't force developers' hand by automatically installing said hooks.

**Comment by matklad** [comment]
Ok, it seems that we don’t necessary want to move forward here!
