### ISSUE TITLE
`cargo install near-vm-runner-standalone` fails: error in `staticvec` dependency with Rust 1.57/1.49/nightly

### ISSUE THREAD

**Issue by fadeevab** [near/nearcore#5927]
**Describe the bug**
There is an example in Near SDK Rust which states  "Install NEAR Runtime standalone runner first":
```bash
cargo install near-vm-runner-standalone
```
However, cargo build fails with many errors.

It fails with the following **Rust** compiler versions:

1. 1.42.0
2. 1.45.0
3. 1.49.0
4. 1.57.0
5. nightly

**OS**: Windows/Linux/WSL

Error sample:
```rust
error[E0557]: feature has been removed
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/staticvec-0.9.3/src/lib.rs:31:3
   |
31 |   const_compare_raw_pointers,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
```

**To Reproduce**
```bash
cargo install near-vm-runner-standalone
```

**Expected behavior**
Installation succeeds.

**Version (please complete the following information):**
- nearcore commit/branch: `master`
- rust version (if local): 1.57, nightly, 1.45, 1.49
- docker (if using docker)
- mainnet/testnet/betanet/local

**More errors:**
```rust
error: generic parameters may not be used in const operations
    --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/staticvec-0.9.3/src/lib.rs:1467:85
     |
1467 |   pub fn concat<const N2: usize>(&self, other: &StaticVec<T, N2>) -> StaticVec<T, { N + N2 }>
     |                                                                                     ^ cannot perform const operation using `N`
     |
     = help: const parameters may only be used as standalone arguments, i.e. `N`

error: generic parameters may not be used in const operations
    --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/staticvec-0.9.3/src/lib.rs:1467:89
     |
1467 |   pub fn concat<const N2: usize>(&self, other: &StaticVec<T, N2>) -> StaticVec<T, { N + N2 }>
     |                                                                                         ^^ cannot perform const operation using `N2`
     |
     = help: const parameters may only be used as standalone arguments, i.e. `N2`
```

**Comment by bowenwang1996** [comment]
@matklad @nagisa any idea why this happens?

**Comment by nagisa** [comment]
I can reproduce the same problem, but note that `near-vm-runner-standalone 2.2.0`, which is what `cargo install` pulls has been uploaded a year ago. There most likely is little relation between current master and what's on crates.io.

```
cargo install -p near-vm-runner-standalone
```

(note the `-p` flag) in repository checkout should work better.

**Comment by nagisa** [comment]
We should definitely look into publishing a new version though.

**Comment by matklad** [comment]
Let's close this: `cargo install near-vm-runner-standalone` is not something we support today
