### ISSUE TITLE
Prefer `neard-sandbox` to `near-sandbox`

### ISSUE THREAD

**Issue by mina86** [near/nearcore#5969]
Currently `make sandbox{,-release}` creates a binary called `near-sandbox`.  That naming is inconsistent with how we call the plain executable.  It would be better if we used `neard-sandbox` instead (notice the `d`).

Just changing the name is of course a trivial affair but we are also uploading sandbox release binary under `near-sandbox` name and documentation refer to it.  Those would need to be updated as well.

**Comment by matklad** [comment]
To play devil's advocate, the current naming isn't necessary bad `neard` is "near daemon", and `near-sandbox` is, well, "near sandbox", not "near daemon sandbox". Today the two are rather similar, but I can see them diverging in the future, and becoming two separaet binaries using a common shared library. For example, it doesn't **really** make sense for the sandbox to carry the whole rocksdb, and pure in-memory store can make sense for it. 

There was also the idea that sandbox name is provisional, and that we might want to rename the thing once we figure out the overall strategy. So something like `neard-workspace` might make sense? 

@ChaoticTempest as the primary customer is probably the right person to make a call on what the name *should* be.

**Comment by mina86** [comment]
> well, "near sandbox", not "near daemon sandbox".

But is it a ‘near sandbox daemon’? ;) I think of it with analogy to daemon built with nightly features which I would call `neard-nightly` rather than `near-nightly`.

Also note that `make docker-nearcore-sandbox` uses a `neard` executable name.
