### ISSUE TITLE
peers keep getting banned

### ISSUE THREAD

**Issue by rencryptofish** [near/nearcore#5976]
running v1.23.0, the node keeps banning peers down to zero peers

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/84360463/147593859-90a3fd80-756c-47ae-8766-825e0e2c673e.png](https://user-images.githubusercontent.com/84360463/147593859-90a3fd80-756c-47ae-8766-825e0e2c673e.png))

**Comment by bowenwang1996** [comment]
@rencryptofish which network is this? This looks like a problem with your set up. Is it possible that your used an incorrect snapshot to run your node?

**Comment by Rishabhraghwendra18** [comment]
I think he is using localnet . I am also having this issue
