### ISSUE TITLE
add rust version to `/status` endpoint

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#5979]
Recently we had issues on different blockchain (Solana) where process was crash looping. With long streak of troubleshooting it turned out, Rust version was the culprit and not Solana codebase itself. Well both rust+solana, but we were only one of very few validators hitting problematic code path, because of Rust, used to compile Solana binary. Please add `rust` version to the `neard` binary, how it was compiled. For example here:
```
$ curl -s 10.130.0.52:3030/status | jq -Mcr .version
{"version":"1.23.0","build":"1.23.0"}
```

**Comment by kucharskim** [comment]
Also, what I found useful, a commit hash of git repo checkout and it the checkout clean or not (local uncommitted changes).

**Comment by Rishabhraghwendra18** [comment]
@bowenwang1996 I think I can help on this issue . I run the `cargo run -- --home ~/.near run` in `neard` directory . It started the node showing block height and all others stuff . But I don't get a way to interact with blocks (or something else) on which I can make a request to `/status` endpoint to reproduce the issue to know how it's currently . May you tell me how can I see the `/status` endpoint and in which file I have to make the changes ?

**Comment by bowenwang1996** [comment]
> @bowenwang1996 I think I can help on this issue . I run the `cargo run -- --home ~/.near run` in `neard` directory . It started the node showing block height and all others stuff . But I don't get a way to interact with blocks (or something else) on which I can make a request to `/status` endpoint to reproduce the issue to know how it's currently . May you tell me how can I see the `/status` endpoint and in which file I have to make the changes ?

It can be accessed at `http://localhost:3030/status`

**Comment by mina86** [comment]
> Also, what I found useful, a commit hash of git repo checkout and if the checkout is clean or not (local uncommitted changes).

That’s `build` in the status, no?

**Comment by kucharskim** [comment]
not sure does it say repo was clean or not, I didn't test it, but yeah, that hash below is from a repo, without letter `g`:

```
{
  "version": "1.24.0-rc.1",
  "build": "crates-0.11.0-67-gfdd3cffea"
}
```

```
nearcore@near04:~/nearcore$ git log -n1 fdd3cffea | wc -c
733
```

**Comment by kucharskim** [comment]
I think having a hash should always be there. I cannot experiment now, but `trunk` doesn't really say anything, right? Trunk today, tomorrow, last month, next year? It cannot be translated into specific checkout.

**Comment by mina86** [comment]
`trunk` is only for the version if building from `master` branch. `build` will always include a tag or hash; it’s literally output of `git describe --always --dirty=-modified`.

**Comment by kucharskim** [comment]
Cool. Works for me.
