### ISSUE TITLE
Compute RocksDB stats in runtime

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#5985]
RocksDB allows to compute statistics on the fly. We can do this for rocksdb object:

```
 for cf in self.cfs.clone() {
 unsafe 

 { let column_family = cf.read(); let stats = self .db .property_value_cf(&column_family, "rocksdb.cfstats-no-file-histogram").unwrap().unwrap(); } 

}
 ```

List of property descriptions is here - [https://github.com/facebook/rocksdb/blob/6e0f62f2b68f0fc1b40e0a143008a3b8a5ba3c41/include/rocksdb/db.h#L722](https://github.com/facebook/rocksdb/blob/6e0f62f2b68f0fc1b40e0a143008a3b8a5ba3c41/include/rocksdb/db.h#L722).

We can extract size of each column from compaction stats. But we can't find total number of entries, `estimated_num_keys` can be very wrong [https://github.com/facebook/rocksdb/issues/6501](https://github.com/facebook/rocksdb/issues/6501). To do so, I plan to use `sst_dump` tool like this - [https://hackmd.io/1IYnmAlZR2-qxKg1ESHJxw](https://hackmd.io/1IYnmAlZR2-qxKg1ESHJxw)

But running it requires ~2m on rpc node and ~45m on archival node, which will grow in time. So it may make sense to add some user-defined property to rocksdb: [https://github.com/facebook/rocksdb/blob/main/include/rocksdb/table_properties.h#L20-L21](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/table_properties.h#L20-L21)

I guess it requires rocksdb code modification, and then adding its support to rust-rocksdb. Alternatively we could add to rust-rocksdb support of native function like `rocksdb_approximate_sizes` which allows to get sizes of columns directly.

**Comment by mina86** [comment]
This is now implemented. cc @nikurt, @posvyatokum
