### ISSUE TITLE
Validate and clean up all cost estimations

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#5993]
Let's go through all costs defined inside [`runtime-params-estimator/src/cost.rs`](https://github.com/near/nearcore/blob/4166c155e812fb4fc2fb02e94ca318d07b957d81/runtime/runtime-params-estimator/src/cost.rs#L9) and check that the estimation makes sense as it is.

Some things are already known that they need a clean-up:

- [ ] Missing estimations for `Cost::ContractCompileBase` and `Cost::ContractCompileBytes` 
   - Code already exists in `Cost::ActionDeploy*` so I think no extra issue is needed here
- [ ] Missing estimations for fundamental units
    - #5991 
- [ ] Gas metering cost is negative sometimes
    - #5992
- [ ] Touching trie node cost estimation
    - This still only uses this formula for approximation: `storage_read_base/log_16(20000)` ([suggested here almost 2 years ago](https://github.com/near/nearcore/pull/2574#discussion_r423410097))
    - Issue #3193 is not specifically for parameter estimation but definitely related.

**Comment by matklad** [comment]
@jakmeier I think we can maybe close this? We've gone through all the estimations, and openened specific issues for the ones which still need fixing.

**Comment by jakmeier** [comment]
Yes, let's close it
