### ISSUE TITLE
Quantify under/ overcharging of parameters

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#5996]
We need to keep an eye on how much we under- or overcharge operations on the blockchain.

I see this as a task with several stages:

1.  Get a rough overview of where we are right now, comparing estimations to real execution times (and to current mainnet gas costs since #4474 is still hanging)
2.  Improve our confidence of each estimation one-by-one. (Tracked in many other issues independent from this.)
3.  Once step two is done sufficiently, produce a detailed report of estimated under- and overcharging.
4.  (Optional) create an automated monitoring system that provides a weekly history of _estimations_ vs _real-time execution_ of the master branch

Step two and three might need to be iterated several times. I plan to gather the reports here in this issue. (Until it might eventually be replaced by step 4)

**Comment by jakmeier** [comment]
Here is a first cost table for `f03f518f20afbfbbfcbf13b7f9dcaaf5fef25e87` as a baseline for current estimations.

<details>

<summary> Expand table </summary>


| Cost                                         |           Time-based  |                   Instruction count + I/O  | Time/ICount |
|---|---|---|---|
| ActionDeployContractBase                     |  98_634_116_000 |        7_451_307_222_337  |        75.54 |
| ActionFunctionCallPerByte                    |         373_732 |                   59_997  |         0.16 |
| ActionFunctionCallBase                       | 438_405_798_000 |          108_757_918_875  |         0.25 |
| WriteRegisterByte                            |          86_236 |                   43_513  |         0.50 |
| WriteMemoryByte                              |         117_149 |                   59_143  |         0.50 |
| ReadMemoryByte                               |          82_858 |                   43_437  |         0.52 |
| ReadRegisterByte                             |          49_630 |                   29_760  |         0.60 |
| Keccak512Byte                                |       7_271_778 |               10_846_592  |         1.49 |
| Keccak256Byte                                |       3_914_403 |                5_815_405  |         1.49 |
| Sha256Byte                                   |       5_706_416 |                8_164_295  |         1.43 |
| EcrecoverBase                                |  66_277_907_186 |           92_743_186_309  |         1.40 |
| ActionTransfer                               |  48_510_581_000 |           67_118_718_375  |         1.38 |
| ActionCreateAccount                          |  54_576_771_000 |           73_715_478_250  |         1.35 |
| ActionStake                                  |  94_793_738_000 |          127_306_996_625  |         1.34 |
| ActionDeployContractPerByte                  |     305_259_903 |              406_779_543  |         1.33 |
| DataReceiptCreationPerByte                   |       2_560_472 |                2_064_811  |         0.81 |
| Keccak256Base                                |     947_207_141 |            1_149_751_865  |         1.21 |
| Keccak512Base                                |     943_542_771 |            1_144_197_900  |         1.21 |
| ActionAddFunctionAccessKeyBase               |  59_874_226_000 |           69_022_760_375  |         1.15 |
| Utf8DecodingBase                             |     441_253_821 |              383_994_685  |         0.87 |
| DataReceiptCreationBase                      |  76_313_002_800 |           67_015_645_893  |         0.88 |
| ReadMemoryBase                               |     242_157_306 |              213_241_768  |         0.88 |
| WriteRegisterBase                            |     330_455_276 |              293_609_086  |         0.89 |
| Sha256Base                                   |     797_743_356 |              889_664_682  |         1.12 |
| Utf8DecodingByte                             |     114_505_400 |              103_036_892  |         0.90 |
| Utf16DecodingByte                            |      61_815_730 |               56_668_054  |         0.92 |
| LogBase                                      |     576_015_696 |              533_059_712  |         0.93 |
| Utf16DecodingBase                            |     570_469_151 |              532_537_320  |         0.93 |
| WriteMemoryBase                              |     292_883_216 |              275_484_954  |         0.94 |
| ActionDeleteKey                              |  28_160_460_000 |           29_923_758_250  |         1.06 |
| ActionSirReceiptCreation                     | 223_250_635_000 |          236_828_227_000  |         1.06 |
| Ripemd160Base                                |     622_205_431 |              587_213_039  |         0.94 |
| ActionAddFullAccessKey                       |  61_657_569_000 |           65_031_198_250  |         1.05 |
| ActionAddFunctionAccessKeyPerByte            |      46_391_735 |               48_586_825  |         1.05 |
| HostFunctionCall                             |      41_548_132 |               40_872_318  |         0.98 |
| Ripemd160Block                               |     227_454_025 |              230_812_070  |         1.01 |
| WasmInstruction                              |         276_276 |                  273_274  |         0.99 |
| ActionReceiptCreation                        | 310_734_728_000 |          314_031_353_000  |         1.01 |
| ActionDeleteAccount                          | 273_978_507_000 |          271_627_358_125  |         0.99 |
| LogByte                                      |       3_362_503 |                3_336_866  |         0.99 |
| ReadRegisterBase                             |     190_582_921 |              190_872_169  |         1.00 |

</details>

Two things to note: 
* `ActionDeployContractBase` might have an error in the formula
* Storage costs are not in here, changes to how they are estimated are imminent

**Comment by matklad** [comment]
@jakmeier could we close this or split into more specific issues? I think we now understand pretty well the relation between deployed parameters and measured costs, no?

**Comment by jakmeier** [comment]
Thanks for the ping, we can close it. There is always more that could be done. But the original intention here has been completed IMO.
