### ISSUE TITLE
init and unsafe_reset_all subcommands enhancement

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6010]
When neard is run with "init" parameter it will overwrite any existing files without warning, including node_key.json and validator_key.json. Yes, validators should backup their keys, data, etc. But adding a simple rename function to the code once it finds the existing file would be a safety feature. The rename pattern may be "original_filename_<cur-timestamp>.original_extension.bak
For unsafe_reset_all it will make sense not to truncate the whole dir, but to delete only files that neard knows and uses. Wiping the whole directory came as a surprise to me when I first faced this.

**Comment by mina86** [comment]
Dunno, `unsafe_reset_all` is explicitly market as unsafe command so I’m not convinced we need extra safety features. The documentation might be updated though to explicitly state that the entire directory is deleted.

**Comment by mintiayields** [comment]
unsafe_reset_all - I agree. Yet, this was a surprise to get the whole directory wiped. A warning or a confirmation request would be nice though - like it is accepted in linux systems.

**Comment by mina86** [comment]
Again, I dunno. `rm -r directory` will delete the directory without any warning or confirmation.

Were you surprised because the documentation didn’t mention that the whole directory is deleted? I.e. would #6038 solve the confusion?

**Comment by mintiayields** [comment]
Adding this behavior description in documentation is good. What do you think about adding an explicit notice at run and a request to confirm with "yes/no"? If the latter is not possible,  #6038 will be the only option.

**Comment by mina86** [comment]
It’s not that it’s not possible, but it’s more code I’m not sure is necessary plus it’s not clear what to do if command is snot run on the terminal. Should it not delete the directory then? That might break existing scripts.

**Comment by mintiayields** [comment]
I am just not aware of the cases when this kind of command can be run not from the terminal. If you do not think my suggestion is feasible, feel free to close it :) I learned my lesson. The question is what other node runners' experiences will be.

**Comment by mina86** [comment]
> I am just not aware of the cases when this kind of command can be run not from the terminal.

Tests, startup scripts.
