### ISSUE TITLE
`sanity/routing_table_sync.py` is broken

### ISSUE THREAD

**Issue by mina86** [near/nearcore#6021]
In the loop at line 190 the node never receives `RoutingTableSyncV2` message. This has been broken by https://github.com/near/nearcore/pull/5455

**Comment by pmnoxx** [comment]
This test should be rewritten from Python to Rust. I have plans on how to do that. I'll work on that later.

**Comment by pmnoxx** [comment]
@mina86 Thanks for reporting the issue.
I made a fix for it: https://github.com/near/nearcore/pull/6174
