### ISSUE TITLE
Contract preparation may sometimes produce invalid WASM

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#6042]
Preparing WASM such as this:

<pre>(module (import "env" "memory" (memory 4097 4097)))</pre>

Ends up producing non-sense such as this:

<pre>(module
 (type (;0![](/images/icons/emoticons/wink.png) (func (param i32)))
 (import "env" "memory" (memory (;0![](/images/icons/emoticons/wink.png) 2049 2049))
 (import "env" "memory" (memory (;1![](/images/icons/emoticons/wink.png) 1024 2048))
 (import "env" "gas" (func (;0![](/images/icons/emoticons/wink.png) (type 0)))
 (global (;0![](/images/icons/emoticons/wink.png) (mut i32) (i32.const 0)))</pre>

Luckily this fails later when `wasmer` attempts to re-parse the module, but ideally we wouldn't be producing invalid WASM in the first place.

**Comment by Ekleog-NEAR** [comment]
With https://github.com/near/nearcore/pull/8146 this is now fixed
