### ISSUE TITLE
Downloading Headers Potential Bug

### ISSUE THREAD

**Issue by BenKurrek** [near/nearcore#6061]
**Describe the bug**
When I started my indexer, it was downloading headers but the remaining headers kept going up. After a few minutes, the downloading stopped as shown below:
![image](https://user-images.githubusercontent.com/57506486/149386551-2bec5679-d14a-452c-82ab-1870db89c017.png)
After about an hour, the same info kept showing up:
![image](https://user-images.githubusercontent.com/57506486/149386591-cef1822e-957a-4172-9afa-92987c8fa9b9.png)

I talked to Vlad and we tried debugging some things. I cloned the nearcore repo and built the binary and ran that as well. I got the following screenshots:
![image](https://user-images.githubusercontent.com/57506486/149386720-063e8947-7f0e-48b6-807c-cac8fe9ff9e9.png)
![image](https://user-images.githubusercontent.com/57506486/149386735-c0d5e4ae-52ef-4862-bb1c-84b78ccd4d86.png)
![image](https://user-images.githubusercontent.com/57506486/149386748-352f6d7c-7ed0-4e36-a00f-633e5a9aea9d.png)
![image](https://user-images.githubusercontent.com/57506486/149386765-cf91e6ef-25fb-4366-b44e-675843a96b88.png)

The same issue was happening where the downloading headers went up and then finally stopped and the same message was being outputted.

**Expected behavior**
Download headers properly and the number should go down and not stop.

**Version (please complete the following information):**
- c0551c84ba9f54509abe05cb1291dbeb33cbd85d
- testnet

**Comment by BenKurrek** [comment]
EDIT - after re-downloading the `data.tar` on my indexers, everything worked properly.

**Comment by frol** [comment]
cc @bowenwang1996 @mm-near @rtsai123

**Comment by bowenwang1996** [comment]
Yes, I believe this is caused by a corrupt snapshot
