### ISSUE TITLE
Data folder Size

### ISSUE THREAD

**Issue by DDeAlmeida** [near/nearcore#6125]
Hello,

Latest version of nearcore on mainnet.

I asked OSA members to tell me the data folder size.

Folder size:
- 186Gb
- 176Gb
- 436Gb
- 473Gb
- 169Gb
- **621Gb**
- **655Gb**

this is not depending of how we got data (snapshot/from scratch)

If you need more infos, details and maybe remote acces to servers we can provide it.
You can also open a discussion about this problem on OSA Discord: https://discord.gg/GcjQf27B

**Comment by nikurt** [comment]
The number of transactions increased a lot recently.
@bowenwang1996 can it be that garbage collection triggers differently for different nodes?

**Comment by DDeAlmeida** [comment]
This data size where reported at the same time from 6 members (one report testnet + backup)

**Comment by mintiayields** [comment]
Please, check the latest snapshots. They are back to normal as per my latest downloads. I hope the code gets updated soon, too.

**Comment by bowenwang1996** [comment]
@DDeAlmeida is your concern that sizes are very different? Unfortunately there are certain migrations we did in the past that did not fully clean some of the old data to optimize for the speed of running the migrations.

**Comment by DDeAlmeida** [comment]
Did we need to remove data folder and use only latest snapshot ?
We also avec different size if we download from snapshot or from scratch.
I can ask OSA community, if they can try with the latest snapshot

**Comment by DDeAlmeida** [comment]
On my Mainnet Node, i have 336GB for folder data.

**Comment by bowenwang1996** [comment]
> Did we need to remove data folder and use only latest snapshot ? We also avec different size if we download from snapshot or from scratch. I can ask OSA community, if they can try with the latest snapshot

It wouldn't affect correctness, but if you want to save some space, sure.

**Comment by bowenwang1996** [comment]
Looks like there is no action item. Closing
