### ISSUE TITLE
Memory Leak + block downloading stuck

### ISSUE THREAD

**Issue by DDeAlmeida** [near/nearcore#6126]
Network: Testnet

Since the lastest update, some of OSA Member reported that they are stuck on Downloading Header and the CPU usage don't stop growing

![image](https://user-images.githubusercontent.com/52310650/150138615-f22f04f7-3720-4f91-86d0-f09b011ab27f.png)

Another Memory usage climbing fast :
![image](https://user-images.githubusercontent.com/52310650/150139024-ede13b8c-d978-427e-afba-989a879ac336.png)
Then

![image](https://user-images.githubusercontent.com/52310650/150139065-ccde4e89-2a71-4956-a079-2eaa8f701554.png)

Feel free to contact me if you need more infos, details or remote access to servers

**Comment by nikurt** [comment]
@DDeAlmeida Can you please run these nodes with the debug logging on?

```
RUST_LOG=debug /home/ubuntu/neard run
```

**Comment by mintiayields** [comment]
To add to the topic: memory usage grows and the block position gets stuck. While this is happening the node is actually falling back and need to catch up a lot after restart. This is on a node with nearup, not built from nearcore. Freshly downloaded testnet DB snapshot.
Part of the log (note memory usage growth):
Jan 21 02:22:34.250  INFO stats: #79613988 5xnZRedxaydGmRayqSiFM3bwQVq293NsyaSZ8XbGEWzv V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.50 bps 2.04 Tgas/s CPU: 160%, Mem: 8.5 GiB
Jan 21 02:22:44.260  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.10 bps 0 gas/s CPU: 126%, Mem: 8.7 GiB
Jan 21 02:22:54.268  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 109%, Mem: 8.8 GiB
Jan 21 02:23:04.277  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 109%, Mem: 9.0 GiB
Jan 21 02:23:14.286  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 113%, Mem: 9.2 GiB
Jan 21 02:23:24.295  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 108%, Mem: 9.4 GiB
Jan 21 02:23:34.662  INFO stats: #79613989 3aCKJX3TGf6ZpLvoxZAWMMoRKrfWo6W9ymgngNJpnjN8 V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 230%, Mem: 9.7 GiB
Jan 21 02:23:44.668  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.50 bps 242.67 Ggas/s CPU: 1374%, Mem: 10.1 GiB
Jan 21 02:23:54.675  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 133%, Mem: 10.2 GiB
Jan 21 02:24:04.681  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 133%, Mem: 10.5 GiB
Jan 21 02:24:14.687  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 135%, Mem: 10.7 GiB
Jan 21 02:24:24.693  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 135%, Mem: 10.9 GiB
Jan 21 02:24:34.698  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 135%, Mem: 11.2 GiB
Jan 21 02:24:44.704  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 135%, Mem: 11.4 GiB
Jan 21 02:24:54.711  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 142%, Mem: 11.6 GiB
Jan 21 02:25:04.723  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 144%, Mem: 11.9 GiB
Jan 21 02:25:14.730  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 143%, Mem: 12.1 GiB
Jan 21 02:25:24.737  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 144%, Mem: 12.3 GiB
Jan 21 02:25:34.743  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 145%, Mem: 12.6 GiB
Jan 21 02:25:44.749  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 145%, Mem: 12.8 GiB
Jan 21 02:25:54.755  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 146%, Mem: 13.0 GiB
Jan 21 02:26:04.762  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 144%, Mem: 13.3 GiB
Jan 21 02:26:14.768  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 144%, Mem: 13.5 GiB
Jan 21 02:26:24.775  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 142%, Mem: 13.7 GiB
Jan 21 02:26:34.782  INFO stats: #79613995 8LAYiwyszYPyirEH8wiYcyssNn55aTJkqDzF45v6chDY V/103 30/30/40 peers ⬇ 1.5MiB/s ⬆ 2.1MiB/s 0.00 bps 0 gas/s CPU: 143%, Mem: 14.0 GiB

**Comment by bowenwang1996** [comment]
Assigning it to @mm-near since he already figured out what most of the underlying causes are

**Comment by bowenwang1996** [comment]
@BenKurrek could you check whether https://github.com/near/nearcore/releases/tag/1.24.0-rc.2 addresses this issue?

**Comment by BenKurrek** [comment]
> @BenKurrek could you check whether https://github.com/near/nearcore/releases/tag/1.24.0-rc.2 addresses this issue?

Yup I've been in contact with @khorolets and all 3 of our indexers are working fine with the new commit hash. Thanks so much.

**Comment by DDeAlmeida** [comment]
Looks closed with the latest version. I don't have issue now on indexer / testnet / guildnet
Thank you guys !
