### ISSUE TITLE
Actix - deadlock investigation

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#6135]
There is a potential dealock in Actix.

My plan is as follows:
- PR, where we remove limits, locks in Actix - https://github.com/near/nearcore/pull/6132
- `rust-memory-analyzer` - see https://github.com/near/nearcore/pull/6134 https://crates.io/crates/rust-memory-analyzer
- Code, which detects deadlocks in Actix - https://github.com/near/nearcore/pull/6136

Original issue https://github.com/near/nearcore/issues/6126

**Comment by matklad** [comment]
Oh wow, great catch. 

My gut feeling is that, if we go as far as patching actix, than it probably makes sense to:

* patch actix short-term, to fix current memory leak
* replace actix with our own in-house thing

That is, I think using a fork of actix long term is a form of technical debt with high interest rate.

**Comment by pmnoxx** [comment]
> Oh wow, great catch.
> 
> My gut feeling is that, if we go as far as patching actix, than it probably makes sense to:
> 
> * patch actix short-term, to fix current memory leak
> * replace actix with our own in-house thing
> 
> That is, I think using a fork of actix long term is a form of technical debt with high interest rate.

I've been thinking about writing my own in house equivalent of `actix`, and maybe even `tokio` down the line.
The reason why I didn't decide to do it, is because it still not exactly clear what the final state of such in-house system should be.

For row, it would be an actix equivalent api + statistics. I think a lot of code simplification can be done on the way, they are some weird design choices of `Actix`, that don't work well for us. Like, lack of back-pressure, stats, control over the messages, etc.
