### ISSUE TITLE
node cannot catch up after the 1.24.0-rc.1 release

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#6137]
An archival node that runs 1.24.0-rc.1 release on mainnet cannot catch up with the network. It processes blocks at a speed of less than 0.5 bps with relatively high cpu usage (around 200%). We should investigate what happened and whether the new logic for block catchup introduced in 1.24.0-rc.1 is problematic.

**Comment by mzhangmzz** [comment]
We figured out the issue, it's because when a node is sufficiently behind, it starts to ignore blocks sent by other nodes, but only relies on requesting block one at a time. This is inefficient. I'm working on a fix that makes the node request for more than block in blocks catching up mode.
