### ISSUE TITLE
Mainnet snapshot on S3 is newer version than 1.23.1 release can handle

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6153]
I had to download the mainnet snapshot yesterday and found it to be for neard 1.24.x
1.23.1 release will not open it. Updating mainnet to 1.24.0-rc.1 is not in option now I believe.
Please, set up snapshot service to the current mainnet version.

**Comment by mhalambek** [comment]
Are you sure this is not a testnet backup, mainnet backup is working fine from me

**Comment by DDeAlmeida** [comment]
Same for me.
Maybe issue appear yesterday and not today

**Comment by mintiayields** [comment]
Downloaded today again - and the issue did not reproduce. Closing.
