### ISSUE TITLE
Acitx `BytesMut` leaks memory

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#6173]
There is a  memory leak, which affects `Codec` from `Actix`.

Actix uses `BytesMut` to represent read/write buffers, however, internally `BytesMut` uses vector, which never frees memory, even if the number of elements used drops to 0.

For example, if you were to receive a message of 500mb, this buffer would grow to 500mb,  and never shrink back. Assuming we have 40 connects, we have 80 such buffers, even if was 20mb, we would be using extra 1.6gb, potentially up to 40gb, in long time.

This should be fixed with https://github.com/near/nearcore/pull/5902.

**Comment by bowenwang1996** [comment]
looks like #5902 is merged
