### ISSUE TITLE
Differential fuzzing of wasmtime vs wasmer

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6184]
Make sure that we not only fuzz wasmer itself (to catch loud crashes), but also compare the results with wasmtime (to catch silent differences in behavior). Roughly, here: 

https://github.com/near/nearcore/blob/977388192ab50c5e9c04242aa2a6d08a89b12c95/runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs#L16

We should run this function with both `VMKind::Wasmer2` and `VMKind::Wasmtime` and make sure that results are identical.

**Comment by Ekleog** [comment]
I still need to come back to this after handling the few changes left in the fuzzer infra
