### ISSUE TITLE
Parallelize fetching receipts inside streamer

### ISSUE THREAD

**Issue by frol** [near/nearcore#6187]
https://github.com/near/nearcore/blob/776f1e86f857e8c90f6edad5dfa73f2a74cb9048/chain/indexer/src/streamer/fetchers.rs#L90-L91

@khorolets This code causes the receipts being fetched in sequential requests, let's introduce batching (futures ordered buffer)

**Comment by bowenwang1996** [comment]
@khorolets is this fixed?

**Comment by khorolets** [comment]
@bowenwang1996 no, @frol and I think that it might cause additional issues, so we haven't decided whether it should be done. @frol what do you think?

**Comment by frol** [comment]
Let's close it for now, we don't have any evidence that it causes any performance issues so far. Since the time I reported this issue we confirmed that Indexer Framework is very far from being a bottleneck - NEAR Lake Indexer mostly spends its time in network waiting for S3 to respond to put object operation (quite fast when we are in the same region, so not a dealbreaker either)
