### ISSUE TITLE
version check fails for release branches

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6197]
Today, we set crate's versions as `0.0.0`, and rely on global version in the root Cargo.toml for auto-publishing. This is also checked by CI. 

This approach breaks when we do a release, as then we specify the version in the Cargo.toml manually. Here's an example of failure: 

https://buildkite.com/nearprotocol/nearcore/builds/12774#58d60fb7-22a9-4ce6-8e74-c87385766c11/105-192

I haven't looked too deeply into this (@miraclx is probably the better person here, but I can take a look if needed), but i think we should do one of the following: 

* disable that check on rc branches
* change our release process to specify the global version instead
* change both the process and the check to:
  * specify the version only in neard/Cargo.toml (not nearcore/Cargo.toml)
  * exempt neard from version checking and publishing
* completely divorce "version of neard"  from "version in Cargo.toml"
  * some precident here is Cargo: what cargo prints in `cargo --version` is different from cargo-as-a-crate version

My prior is that one of the two last approaches is better.

**Comment by miraclx** [comment]
Acknowledged. Indeed the better option is to make `neard` binary independent from `nearcore` crate version. My patch of cargo-workspaces can already sufficiently exempt specific crates from being versioned. We just need to update the check to whitelist neard. I'll work on this now so it's not blocking anyone.

**Comment by matklad** [comment]
I don't think this is blocking, but yeah, would be nice to fix, thanks!
