### ISSUE TITLE
Validation node falls off sync precisely during the block production time slot

### ISSUE THREAD

**Issue by frol** [near/nearcore#6220]
**Describe the bug**

Validation node constantly falls off syncing when it switches becoming a validator:

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/304265/151704842-7c550e1d-55d6-418a-a062-a27e4e4d3fa9.png">

I initially blamed the hardware since the machine that I used was a bit underspeced:

* CPU: Intel Core i7-2600
* RAM: 16GB DDR3
* SSD 512GB

The node worked fine when it does not participate in validation.

When I saw that it missed all the blocks during the validation, I bumped the specs to:

* CPU: AMD Ryzen 5 3600 6C/12T 3.60GHz
* RAM: 32 Gb DDR4 ECC
* NVME 1TB

But that did not help at all, and at the time when the block production should happen, the node just falls out of sync:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/304265/151959438-f30a3af1-0364-478e-8166-2a385fe5dde5.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/304265/151959113-17c75e62-6abb-4aa1-ad3b-4ad84ae20790.png">

Is there a way to debug the issue? (running the node with `--verbose debug` creates gigabytes of logs...

I double-checked the validator_key.json and it seems to be fine and the public key matches the one that is used for staking. 

I still feel there is some misconfiguration, but I cannot think of anything at the moment.

Here is the ping stats to the boot nodes from the validation node (I feel the network delay might cause the issues, right?):

<img width="482" alt="image" src="https://user-images.githubusercontent.com/304265/151960779-f1592160-e990-4308-99ff-fa536b023a4a.png">

**To Reproduce**

```
$ docker run -it --rm -v /home/near/.near:/home/near/.near nearprotocol/nearcore:1.23.1 neard --home /home/near/.near run
```

**Expected behavior**

Node should not fall off sync or at least communicate why it gets stuck.

**Version (please complete the following information):**
- nearcore commit/branch: 1.23.1 and 1.24.0-rc.1
- docker (if using docker): `nearprotocol/nearcore:1.23.1`
- mainnet

**Comment by frol** [comment]
@janewang I also want to use this issue to highlight a problem that it is hard to troubleshoot such problems.

**Comment by frol** [comment]
What I spotted is that time was 2 hours out of sync (common timezone BIOS vs Linux handling issue).

Log:

I installed `ntpdate` package and run `sudo ntpdate-debian` to sync the time:

```
$ date ; sudo ntpdate-debian ; date
Tue Feb  1 09:47:31 EST 2022
 1 Feb 07:48:07 ntpdate[18508]: step time server 91.189.94.4 offset -7170.787189 sec
Tue Feb  1 07:48:07 EST 2022
```

I hope this fixes the issue. It would be great to bake in the sanity checks during node boot time.

**Comment by bowenwang1996** [comment]
Indeed if your time is not correct you will reject blocks. You should be able to see this if you enable debug logs, but yeah, there should be some check :)

**Comment by janewang** [comment]
@frol  Thanks for creating the issue. Having more useful logs is definitely something we need to work on and improve, hopefully soon

**Comment by janewang** [comment]
Thanks for the wish list @frol. Keep them coming

**Comment by bowenwang1996** [comment]
@janewang could you Frol's suggestions into issues? Thanks!
