### ISSUE TITLE
Add tracing span calls for deploy action

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6224]
Basically, add `tracing::degug_span` here

https://github.com/near/nearcore/blob/d1d45597abe41228e60f725e56c216e87a4c9b84/runtime/runtime/src/actions.rs#L439

and here 

https://github.com/near/nearcore/blob/d1d45597abe41228e60f725e56c216e87a4c9b84/runtime/near-vm-runner/src/cache.rs#L403

so that we know which fraction of deploy is compilation.

**Comment by jakmeier** [comment]
I guess you were just thinking of the first commit in #6229?

I also added a param estimator CLI flag to make it usable but not sure if this is the best way of handling it.
