### ISSUE TITLE
Indexer initialization fails on fresh directory (Cannot deserialize genesis)

### ISSUE THREAD

**Issue by tifrel** [near/nearcore#6228]
**Describe the bug**
I think this bug is best described by a stacktrace: ![Screenshot 2022-02-01 at 18 06 12](https://user-images.githubusercontent.com/31419678/152025587-6fe618a6-2327-479e-a327-4bb7f36da08c.png)

**To Reproduce**
- Wipe your NEAR data directory
- Try to init the indexer with downloading genesis and config

**Expected behavior**
I expect it not to fail. More specifically, the downloaded `genesis.json` should conform to the `Genesis` struct from ` nearcore/core/chain-configs/src/genesis_config.rs`.

**Screenshots**
See above

**Version (please complete the following information):**
- nearcore 1.24.0-rc2 (commit: 6c5199f3b8b72ea8065e25cdd0bd3661ef95f878)
- stable-x86_64-unknown-linux-gnu (default), rustc 1.56.1 (59eed8a2a 2021-11-01)
- not using docker
- happens on testnet

**Additional context**
From the stacktrace, it seems to be looking for a `u32` in the `genesis.json`, but finds some object, thus deserialization fails. Chasing down the location in the JSON failed so far because of file size, chasing `u32`s in the `Genesis` struct gave two preliminary candidates: `Genesis.genesis_config.protocol_version` and `Genesis.genesis_config.shard_layout::ShardLayoutV0.0.version`, no guarantees that those are all `u32` occurences inside `Genesis`

@bowenwang1996 and @khorolets have confirmed it to be highly likely a bug on the NEAR side of things.

**Comment by tifrel** [comment]
Update: We had `dependencies.serde_json.features = ["arbitrary_precision"]` in our "Cargo.toml". Removing the feature fixes the issue.

**Comment by khorolets** [comment]
@bowenwang1996 @frol we should decide whether we need to ensure we support that feature and check if we don't break it and open a separate issue for that if we want. This one should be closed.

**Comment by bowenwang1996** [comment]
> we should decide whether we need to ensure we support that feature

I don't see a good reason for doing that, but we should document this. cc @janewang
