### ISSUE TITLE
Archival node stuck at block #80955179 on NEAR Testnet

### ISSUE THREAD

**Issue by maoueh** [near/nearcore#6243]
**Describe the bug** On February 1st around 12:00 EST time, both our indexer node stopped syncing properly with the network, both of our instances where at near core version 1.23.1 and both of them stopped roughly at the same time on block #80955179\. Whatever we tried since then, nothing worked

*   Restart both node multiple times over multiple days
*   Updated to 1.24.0-rc.2 (trying rc.3 soon but I don't have more hope)
*   Updated some boot nodes

Upon restart, we can see that the first block that we process from the indexer framework is block #80955177 (8fb1d55bbb2dc1d529d268b7c435b728f1b7ce0ef8b945f65803e81fd20a274b) Shards: 4, Transactions: 0, Receipts: 1, ExecutionOutcomes: 1

After which we more or less see these lines which we repeat forever afterwards:

 Feb 03 16:32:48.289 INFO stats: #80955179 Waiting for peers 1/1/40 peers ⬇ 0.3kiB/s ⬆ 15 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 0 B
 Feb 03 16:33:05.359 INFO stats: #80955179 Downloading headers 100.00% (254) 4/1/40 peers ⬇ 237.0kiB/s ⬆ 682.5kiB/s 0.00 bps 0 gas/s CPU: 39%, Mem: 7.5 GiB
 Feb 03 16:33:14.507 WARN network: Attempting to connect to a node (ed25519:2BKPTEHdMibdf1kj2jFkStStm5tyXYRakejNNjfpiibe@0.0.0.0:24567@kserx.stake.guildnet) with a different genesis block. Our genesis: GenesisId 

 { chain_id: "testnet", hash: `FWJ9kR6KFWoyMoNjpLXXGHeuiy7tEY6GmoFeCA5yuc6b` } 

, their genesis: GenesisId 

 { chain_id: "guildnet", hash: `3GadzH2KgWo12ryFL94KJ1REnbr3WVySkYtPduWCSPR3` } 

 Feb 03 16:33:14.523 WARN network: Attempting to connect to a node (ed25519:GmCHi7oKyTAUDjqToANkpi3UpxuBQsKjsuCbNE75HXXy@0.0.0.0:24567@grassets-tech.stake.guildnet) with a different genesis block. Our genesis: GenesisId 

 { chain_id: "testnet", hash: `FWJ9kR6KFWoyMoNjpLXXGHeuiy7tEY6GmoFeCA5yuc6b` } 

, their genesis: GenesisId 

 { chain_id: "guildnet", hash: `3GadzH2KgWo12ryFL94KJ1REnbr3WVySkYtPduWCSPR3` } 

 Feb 03 16:33:15.371 INFO stats: #80955179 Downloading blocks 99.34% (255932) 6/4/40 peers ⬇ 332.5kiB/s ⬆ 653.9kiB/s 0.00 bps 0 gas/s CPU: 58%, Mem: 7.5 GiB
 Feb 03 16:33:19.239 WARN network: Attempting to connect to a node (ed25519:55JfXREsLj5kqi6Y9npjETro5JeQfsHzmhJ4mM1TdMxq@0.0.0.0:24567@lastnode.poolv1.near) with a different genesis block. Our genesis: GenesisId 

 { chain_id: "testnet", hash: `FWJ9kR6KFWoyMoNjpLXXGHeuiy7tEY6GmoFeCA5yuc6b` } 

, their genesis: GenesisId 

 { chain_id: "mainnet", hash: `EPnLgE7iEq9s7yTkos96M3cWymH5avBAPm3qx3NXqR8H` } 

 Feb 03 16:33:25.374 INFO stats: #80955179 Downloading blocks 99.34% (255944) 6/4/40 peers ⬇ 414.3kiB/s ⬆ 872.9kiB/s 0.00 bps 0 gas/s CPU: 19%, Mem: 7.5 GiB
 Feb 03 16:33:31.529 WARN network: Attempting to connect to a node (ed25519:Dzag6h9RkB6QUjzcAZFiSULWSbAra6c2gxwmru43dK3G@0.0.0.0:24567@cryptoblossom.poolv1.near) with a different genesis block. Our genesis: GenesisId 

 { chain_id: "testnet", hash: `FWJ9kR6KFWoyMoNjpLXXGHeuiy7tEY6GmoFeCA5yuc6b` } 

, their genesis: GenesisId 

 { chain_id: "mainnet", hash: `EPnLgE7iEq9s7yTkos96M3cWymH5avBAPm3qx3NXqR8H` } 

 Feb 03 16:33:35.377 INFO stats: #80955179 Downloading blocks 99.34% (255959) 6/4/40 peers ⬇ 425.2kiB/s ⬆ 876.8kiB/s 0.00 bps 0 gas/s CPU: 17%, Mem: 7.5 GiB
 Feb 03 16:33:37.229 INFO near_network::peer_manager::peer_manager_actor: Bandwidth stats total_bandwidth_used_by_all_peers=26269862 total_msg_received_count=1639 max_max_record_num_messages_in_progress=42
 Feb 03 16:33:45.380 INFO stats: #80955179 Downloading blocks 99.34% (255966) 8/6/40 peers ⬇ 503.3kiB/s ⬆ 951.3kiB/s 0.00 bps 0 gas/s CPU: 19%, Mem: 7.6 GiB
 Feb 03 16:33:55.383 INFO stats: #80955179 Downloading blocks 99.34% (255981) 9/7/40 peers ⬇ 590.7kiB/s ⬆ 1.0MiB/s 0.00 bps 0 gas/s CPU: 20%, Mem: 7.6 GiB
 Feb 03 16:34:05.387 INFO stats: #80955179 Downloading blocks 99.34% (255995) 9/7/40 peers ⬇ 516.8kiB/s ⬆ 951.1kiB/s 0.00 bps 0 gas/s CPU: 25%, Mem: 7.6 GiB
 Feb 03 16:34:15.390 INFO stats: #80955179 Downloading blocks 99.34% (256009) 9/7/40 peers ⬇ 369.3kiB/s ⬆ 464.9kiB/s 0.00 bps 0 gas/s CPU: 19%, Mem: 7.6 GiB
 Feb 03 16:34:25.393 INFO stats: #80955179 Downloading blocks 99.34% (256017) 9/7/40 peers ⬇ 300.4kiB/s ⬆ 252.3kiB/s 0.00 bps 0 gas/s CPU: 18%, Mem: 7.6 GiB
 Feb 03 16:34:35.396 INFO stats: #80955179 Downloading blocks 99.34% (256031) 9/7/40 peers ⬇ 317.4kiB/s ⬆ 265.7kiB/s 0.00 bps 0 gas/s CPU: 21%, Mem: 7.6 GiB
 Feb 03 16:34:37.231 INFO near_network::peer_manager::peer_manager_actor: Bandwidth stats total_bandwidth_used_by_all_peers=19909971 total_msg_received_count=5620 max_max_record_num_messages_in_progress=24
 Feb 03 16:34:45.411 INFO stats: #80955179 Downloading blocks 99.34% (256045) 9/7/40 peers ⬇ 253.8kiB/s ⬆ 198.1kiB/s 0.00 bps 0 gas/s CPU: 18%, Mem: 7.6 GiB
 Feb 03 16:34:55.414 INFO stats: #80955179 Downloading blocks 99.34% (256054) 9/7/40 peers ⬇ 171.3kiB/s ⬆ 121.3kiB/s 0.00 bps 0 gas/s CPU: 17%, Mem: 7.6 GiB
 Feb 03 16:35:05.417 INFO stats: #80955179 Downloading blocks 99.34% (256066) 9/7/40 peers ⬇ 94.5kiB/s ⬆ 46.9kiB/s 0.00 bps 0 gas/s CPU: 22%, Mem: 7.7 GiB
 Feb 03 16:35:15.421 INFO stats: #80955179 Downloading blocks 99.34% (256082) 9/7/40 peers ⬇ 102.3kiB/s ⬆ 52.0kiB/s 0.00 bps 0 gas/s CPU: 24%, Mem: 7.7 GiB

**To Reproduce** Hard to tell

**Expected behavior** It should sync

**Screenshots** Logs that we see:

 Feb 03 16:26:21.769 INFO stats: #80955179 Downloading blocks 99.34% (255390) 29/26/40 peers ⬇ 581.8kiB/s ⬆ 347.5kiB/s 0.00 bps 0 gas/s CPU: 38%, Mem: 8.8 GiB
 Feb 03 16:26:31.773 INFO stats: #80955179 Downloading blocks 99.34% (255399) 29/26/40 peers ⬇ 1.7MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 26%, Mem: 8.8 GiB
 Feb 03 16:26:41.776 INFO stats: #80955179 Downloading blocks 99.34% (255412) 29/26/40 peers ⬇ 1.7MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 30%, Mem: 8.8 GiB
 Feb 03 16:26:51.779 INFO stats: #80955179 Downloading blocks 99.34% (255423) 29/26/40 peers ⬇ 1.7MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 27%, Mem: 8.8 GiB
 Feb 03 16:27:01.782 INFO stats: #80955179 Downloading blocks 99.34% (255435) 29/26/40 peers ⬇ 1.7MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 32%, Mem: 8.8 GiB
 Feb 03 16:27:11.787 INFO stats: #80955179 Downloading blocks 99.34% (255448) 29/26/40 peers ⬇ 1.7MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 27%, Mem: 8.8 GiB
 Feb 03 16:27:21.790 INFO stats: #80955179 Downloading blocks 99.34% (255464) 29/26/40 peers ⬇ 1.5MiB/s ⬆ 1.5MiB/s 0.00 bps 0 gas/s CPU: 41%, Mem: 8.8 GiB
 Feb 03 16:27:31.795 INFO stats: #80955179 Downloading blocks 99.34% (255477) 29/26/40 peers ⬇ 362.6kiB/s ⬆ 164.7kiB/s 0.00 bps 0 gas/s CPU: 37%, Mem: 8.8 GiB
 Feb 03 16:27:41.798 INFO stats: #80955179 Downloading blocks 99.34% (255488) 29/26/40 peers ⬇ 359.2kiB/s ⬆ 161.1kiB/s 0.00 bps 0 gas/s CPU: 29%, Mem: 8.8 GiB
 Feb 03 16:27:51.802 INFO stats: #80955179 Downloading blocks 99.34% (255504) 29/26/40 peers ⬇ 389.4kiB/s ⬆ 179.4kiB/s 0.00 bps 0 gas/s CPU: 43%, Mem: 8.8 GiB
 Feb 03 16:28:01.805 INFO stats: #80955179 Downloading blocks 99.34% (255518) 29/26/40 peers ⬇ 388.0kiB/s ⬆ 178.3kiB/s 0.00 bps 0 gas/s CPU: 33%, Mem: 8.8 GiB

There is I/O activity, there is CPU activity but the node seems to just be stuck there refusing to continue over.

**Version (please complete the following information):**

*   nearcore 1.23.1 and 1.24.0-rc.2
*   rust version 1.56
*   docker
*   testnet

**Additional context** Add any other context about the problem here. [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/123014/152430846-4c5e4a18-7189-47e1-a31d-f6821eb1b401.jpg)</span>](https://user-images.githubusercontent.com/123014/152430846-4c5e4a18-7189-47e1-a31d-f6821eb1b401.jpg)

All EST times

**Comment by maoueh** [comment]
[near-stuck-trace-trimmed.log](https://github.com/near/nearcore/files/7998548/near-stuck-trace-trimmed.log)

Trace of around 2m of running from start to stuck mode, trimmed some logs that repeated often and did not seems to be useful here (`cat ~/Downloads/near-stuck-trace.log| grep -Ev "near_rate_limiter::framed_read: attempting to decode a frame|near_rate_limiter::framed_read: frame decoded from buffer" > ~/Downloads/near-stuck-trace-trimmed.log`)

**Comment by maoueh** [comment]
Just updated to 1.24.0-rc.3 on one of the stuck node, does not seem to change anything.

**Comment by maoueh** [comment]
Most interesting logs in the trace that did not show on the default logging level:

```
Feb 03 16:45:06.125  WARN sync: Block sync: 80955179/81212053 No available archival peers to request block 5d2DnzwcVJNCvHpB32oztpkvBtHnmEzz2Xcqr87kURBX from
```

And also I see

```
Feb 03 16:45:06.160 DEBUG indexer: Streaming is about to start from block #80955178 and the latest block is #80955177
```

Repeated 151 times, seems a bit weird to me that we are about to start so many time, but could be all good.

**Comment by nikurt** [comment]
Can you please restart your node with debug logs enabled?
For neard it's done like this:

```
RUST_LOG=debug neard run
```

Should be similar for an indexer node.

**Comment by maoueh** [comment]
@nikurt trace logs have been appended already to this post https://github.com/near/nearcore/issues/6243#issuecomment-1029438521.

Is this all good to you?

**Comment by nikurt** [comment]
Sorry, missed the log.
Haven't found anything obviously broken in it though.

Can you please try setting `boot_nodes` in `config.json` to the following value?

```
"boot_nodes": "ed25519:B4KsEaq85XzyouwLfqbPJDinBvzcDfdDwDLyLs1BA9kH@34.69.236.241:24567,ed25519:2Pcr2cak84xku8gYSqC1UdbaP4uWU1BAzuhxPYRVDt1R@35.239.157.74:24567,ed25519:61erhmQHnktXcDJ5yt5VR1C4C81HgCT2uTasKX5iFv6o@34.80.32.110:24567,ed25519:H5DFaHAVFgcwULbH4facDEgQ7rhWG4GdVT2DudUw33pq@34.80.122.48:24567,ed25519:8DaVgTq9aYgU2oQPMXnViHjkPBB4VEBr6VbB71xXewZM@34.145.132.37:24567,ed25519:uogeFsgNnGbqcViAzXm1WtUNqErdPyxk8FEjVncWsWt@34.150.247.162:24567,ed25519:3wiBVynN1jxggZSayTyM71TRcbpBDHrXdRgSnB9kC3qA@34.150.236.231:24567,ed25519:3VJ6fykjBRR8qkEyiQKSRmzJM99FDku4ic2cUCe8LqAP@34.145.197.182:24567,ed25519:rwov4eWLtwTDEerFayfoLCsngteuVc9Xg79B9eaWPJr@34.86.45.68:24567,ed25519:CcSGtsMe7bSzZ5wxB7Ci3AZyQyvRsjBqzNGYSoPQMXU5@34.90.74.167:24567,ed25519:EYPAx1j65nZp9W57MYmsV59C5Fcir7nnuBG8ah98TTPZ@34.147.41.184:24567,ed25519:8hk2hehSVitMMSsd1cBGHBnPt8Tgk64BGTU9WDLNiZYg@34.147.91.248:24567,ed25519:h4WBbnqipU6ybZXhHerJ1qoGTZMsx5KURzC3bL8e4Jg@34.92.204.117:24567",
```

**Comment by maoueh** [comment]
Ok we updated the config with this boot nodes list. Seems it did not help, I can see in the network info results that we seem to be connected to a least one of the peer in the list.

Now, I've settled on running with `RUST_LOG=debug` instead of `trace` and something else interesting came out of the log:

```
Feb 04 12:18:20.660 DEBUG Process block{#80955180}: chain: Failed to validate chunk extra: Error { inner:    0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: <near_chain_primitives::error::Error as core::convert::From<near_chain_primitives::error::ErrorKind>>::from
   3: near_chain::validate::validate_chunk_with_chunk_extra
   4: near_chain::chain::ChainUpdate::apply_chunks_preprocessing
   5: near_chain::chain::ChainUpdate::process_block
   6: near_chain::chain::Chain::process_block_single
   7: near_chain::chain::Chain::process_block
   8: near_client::client::Client::process_block
   9: near_client::client_actor::ClientActor::process_block
  10: near_client::client_actor::ClientActor::receive_block
  11: near_performance_metrics::stats_disabled::measure_performance_with_debug
  12: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  13: <actix::address::envelope::SyncEnvelopeProxy<M> as actix::address::envelope::EnvelopeProxy<A>>::handle
  14: actix::mailbox::Mailbox<A>::poll
  15: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  16: tokio::runtime::task::core::CoreStage<T>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::task::local::LocalSet::tick
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  23: tokio::runtime::Runtime::block_on
  24: actix_rt::system::SystemRunner::run
  25: near_dm_indexer::main
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: std::rt::lang_start::{{closure}}
  28: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
      std::rt::lang_start_internal::{{closure}}
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
      std::panicking::try::do_call
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
      std::rt::lang_start_internal
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  29: main
  30: __libc_start_main
  31: _start


Invalid State Root Hash }
Feb 04 12:18:20.660 DEBUG Process block{#80955180}: chain: Verifying challenges []
```

I'm wondering why it did not show up in `trace` log?

Which seems interesting at first even though not sure if it's the cause of our problem.
[network_info.json.txt](https://github.com/near/nearcore/files/8005002/network_info.json.txt) (It's a JSON file but required a .txt extension to upload).

**Comment by marcelo-gonzalez** [comment]
@maoueh do you remember if you saw the `No available archival peers` log line after setting the boot nodes?

**Comment by maoueh** [comment]
@marcelo-gonzalez Note that I could remember but not impossible there was still there. However the logs did not seem to be stable like changing `RUST_LOG=trace` to `RUST_LOG=debug` surfaced logs that I never seen while in tracing so I'm not totally confident I did see all lines correctly.

**Comment by bowenwang1996** [comment]
> I'm wondering why it did not show up in trace log?

Yeah that seems like a bug. @marcelo-gonzalez could you look into it?

**Comment by telezhnaya** [comment]
Hey!
Please update to the latest version and feel free to re-open if it's still an issue for you
