### ISSUE TITLE
nearcore 1.24.0-rc.3 does not keep up with mainnet

### ISSUE THREAD

**Issue by frol** [near/nearcore#6249]
**Describe the bug**

It was reported by the community and I confirmed it today myself, that 1.24.0-rc.3 release cannot sync up with mainnet since the sync speed is slower than the block production:

![image](https://user-images.githubusercontent.com/304265/152670359-3a1fc165-56b9-4872-b726-ab3db0135183.png)

I initially bumped into it with indexer-for-explorer, but I eliminated anything Indexer-specific by simply switching the binary to `neard`, and the issue is still there. This exact server used to work fine for Indexer for Explorer based on nearcore 1.23.1.

**To Reproduce**

Run neard of 1.24.0-rc.3 version on mainnet.

**Expected behavior**

neard should sync faster than blocks are produced on the network.

**Version (please complete the following information):**
- nearcore commit/branch: 1.24.0-rc.3 (the binary is downloaded from near s3 bucket)
- archival node (I have not tested on RPC node)
- mainnet

**Comment by tarkhil** [comment]
Same here. Not a disk speed issue, neither throughput nor latency. Disk shows about 0% busy. Maybe it's CPU-bound, CPU usage is always over 100% (but before update it was catching up just fine).

**Comment by frol** [comment]
It is a duplicate of #6137
