### ISSUE TITLE
Archival nodes do not need to store trie changes for old blocks

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#6250]
`ColTrieChanges` accounts for about 2TB of archival node's storage on mainnet. However, we can reconstruct them easily if we have prev state, transactions, and receipts for a give chunk. To save storage space, we can compute them on the fly if needed.

**Comment by abacabadabacaba** [comment]
In fact, I think that trie changes can be reconstructed more efficiently by diffing the tries. No need to actually reexecute anything. So, I think that we should eventually get rid of ColTrieChanges completely, for all nodes.

**Comment by frol** [comment]
@abacabadabacaba diffs won't give you the reason, e.g. why the balance has changed.

**Comment by marcelo-gonzalez** [comment]
@mzhangmzz @bowenwang1996 @mina86  Am i correct here in saying that getting rid of this is actually not that complicated for archival nodes?

So looks to me like the only place `ColTrieChanges` is accessed after storing to it is when clearing old data in `clear_block_data()`. This in turn is only called from `clear_data()` (and `clear_forks_data()`, which is called by `clear_data()`) and `reset_data_pre_state_sync()`:

https://github.com/near/nearcore/blob/a83db115e4ef01152bbe2f89cf11b0f3da32006d/chain/client/src/client.rs#L1050-L1055

https://github.com/near/nearcore/blob/a83db115e4ef01152bbe2f89cf11b0f3da32006d/chain/client/src/client_actor.rs#L1504-L1506

so in both cases only if archival=false. So as a quick solution before maybe just getting rid of it completely like @abacabadabacaba suggested, should be possible to just get rid of the whole column now and avoid storing to it in the future for archival nodes

**Comment by mina86** [comment]
I think you’re actually right. The only two reads I could find are in `clear_block_data` which is not called in archival nodes.

And the changes is just a trie key→value list so if we ever need that information diffing two tries seem like obvious approach.

**Comment by bowenwang1996** [comment]
@marcelo-gonzalez yeah please do that (removing the whole column)

**Comment by mina86** [comment]
FYI, in https://github.com/near/nearcore/pull/6477 I’m adding an option to recompress-storage to clean out that column.
