### ISSUE TITLE
Add time check during node boot time

### ISSUE THREAD

**Issue by janewang** [near/nearcore#6264]
Sometimes node operators forgets to sync time such that their node rejects blocks. It is not transparent initially what the issue is. At node boot time, we should run a time check when the node is going to do validation, and WARN user and stop the booting if the time is not set correctly.
 Also we should warn and stop about the time drift regularly (it seems it is safe to ignore those on non-validating nodes).

```
 $ date ; sudo ntpdate-debian ; date
 Tue Feb 1 09:47:31 EST 2022
 1 Feb 07:48:07 ntpdate<span class="error">[18508]</span>: step time server 91.189.94.4 offset -7170.787189 sec
 Tue Feb 1 07:48:07 EST 2022
 $ sudo timedatectl set-timezone Etc/UTC
 ```

**Comment by janewang** [comment]
Related to https://github.com/near/nearcore/issues/6220

**Comment by mina86** [comment]
There’s nothing for us to do here to be honest.  There are tools designed to keep computer time in sync (e.g. [timesyncd](https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html)).  Debian for example enables time synchronisation by default.  It falls outside of the scope of nearcore to make sure that the host is configured correctly.
