### ISSUE TITLE
Enable jemalloc support in rocksdb

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6290]
After [https://github.com/near/nearcore/pull/6289](https://github.com/near/nearcore/pull/6289), we should be able to take advantage of [https://github.com/rust-rocksdb/rust-rocksdb/pull/542/](https://github.com/rust-rocksdb/rust-rocksdb/pull/542/) – making rocks aware that the allocator we use is jemalloc. Intuitively, it seems like that might bring some substantional perf wins.

**Comment by bowenwang1996** [comment]
Sadly we reverted #6289 as the performance of 0.18 is worse than that of 0.16 according to our benchmark

**Comment by akhi3030** [comment]
https://github.com/near/nearcore/pull/6351 upgraded back to 0.18.  We have been running on 0.18 for some time now.
