### ISSUE TITLE
Account deserialization fails on ARM64

### ISSUE THREAD

**Issue by frol** [near/nearcore#6293]
**Describe the bug**

The versioning check for Account type deserialization is invalid since it compares the size of the buffer holding serialized data (72 bytes) with a memory layout size of the struct (platform-dependent due to alignment and it seems to be 72 bytes on amd64, while it is 80 bytes on arm64 [Apple M1]) instead of the size of the serialized struct.

https://github.com/near/nearcore/blob/5568df666a0f5025c724027814069050acb194c6/core/primitives-core/src/account.rs#L113-L130

cc @EgorKulikov @mm-near 

**To Reproduce**

1. Compile neard for Apple M1 (#6200 is already on master)
2. Init neard: `./target/debug/neard --home /tmp/near-home init`
3. Run neard: `./target/debug/neard --home /tmp/near-home run`

![](https://user-images.githubusercontent.com/304265/154052627-bfb81fd1-d23d-433f-ad94-8fac19d544be.jpg)

**Expected behavior**

It should deserialize the value just fine, and it does when I just remove the condition and let it deserialize the LegacyAccount struct.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/304265/154054689-437b39d2-ee07-4348-a2f2-03cd2f11b5f9.png">

**Version (please complete the following information):**
- nearcore commit/branch: master 5568df666a0f5025c724027814069050acb194c6
- rust version (if local): 1.58.1
- docker (if using docker): no
- mainnet/testnet/betanet/local

**Comment by bowenwang1996** [comment]
I think it is important that we fix this. Otherwise developers with M1 machines cannot run a node locally. @EgorKulikov could we fix this issue?
