### ISSUE TITLE
[Param Estimator] Docker not found 

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#6295]
**Describe the bug**
Running runtime params estimator with docker: `Unable to find image 'rust-emu:latest' locally`

**To Reproduce**

> $ cargo run --release --package runtime-params-estimator --features required --bin runtime-params-estimator -- --accounts-num 20000 --additional-accounts-num 200000 --iters 1 --warmup-iters 1   --docker --metric icount
    Finished release [optimized] target(s) in 0.32s
     Running `/home/ilblackdragon/nearcore/target/release/runtime-params-estimator --accounts-num 20000 --additional-accounts-num 200000 --iters 1 --warmup-iters 1 --docker --metric icount`
[elapsed 00:00:48 remaining 00:00:00] Writing into storage ████████████████████  200000/200000
Unable to find image 'rust-emu:latest' locally
docker: Error response from daemon: pull access denied for rust-emu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by jakmeier** [comment]
Oops, I introduced this bug with #6213. Since then we use an explicit docker tag for each Rust version.

Apparently, I didn't test it properly. It tested on three different machines but all of them still had the implicit tag `latest` of the image...
