### ISSUE TITLE
[Param Estimator] Fails with gas metering assertion

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#6296]
**Describe the bug**
Running param estimator fails with gas metering should be higher than without:

```thread 'main' panicked at 'Cost with gas metering should be higher than without. Metric: Time. Estimated with gas metering: 54990508000000, without: 63502153000000', runtime/runtime-params-estimator/src/gas_metering.rs:219:5```

**To Reproduce**
```cargo run --release --package runtime-params-estimator --features required --bin runtime-params-estimator -- --accounts-num 20000 --additional-accounts-num 200000 --iters 1 --warmup-iters 1 --metric time```

**Expected behavior**
Should not fail or provide a clear guidance what should be changed for successful run.

**Comment by bowenwang1996** [comment]
@jakmeier could you take a look at this?

**Comment by jakmeier** [comment]
This particular panic is already tracked in #5992. But I didn't work on it very actively, as it rarely failed for me. (It behaves quite non deterministic.) A possible solution is provided in #6345
