### ISSUE TITLE
Implement chunk nodes cache for `TrieRecordingStorage`

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#6316]
When we enable challenges, `fn apply` will need to work with both `TrieCachingStorage` and `TrieRecordingStorage`, so we need to maintain correct nodes accounting in both of them.

IMO it's a good idea to postpone it because the current architecture around `TrieStorage` is not optimal, but it is also easy to forget about.

**Comment by robin-near** [comment]
@Longarithm Could you elaborate on what you mean by:

> the current architecture around TrieStorage is not optimal, but it is also easy to forget about.

For context, I need to implement this now to enable storage proof for stateless validation. Thanks!

**Comment by Longarithm** [comment]
The issue was that `TrieRecordingStorage::get_trie_nodes_count` is not implemented.

Recently I made a change which allows calling `TrieRecordingStorage::storage.get_trie_nodes_count()` and I think it will just work correctly.

**Comment by Longarithm** [comment]
I think #9004 nicely covers what I was unhappy about.

**Comment by Longarithm** [comment]
Done in #9350 in other way.
