### ISSUE TITLE
Allow Node Logging in JSON format

### ISSUE THREAD

**Issue by janewang** [near/nearcore#6320]
Node logging could allow logs to use different format: plaintext or JSON. 

Background:
 Current logs in ext requires custom regex for parsing and is suboptimal for managing highly available nodes. As we work on enhancing the log content, I suggest we use JSON such logs are backward compatible as we make these changes.

Enhancement:
 JSON format is easily digestible and easily used in third party software for node monitoring and alerting.

**Comment by nikurt** [comment]
This issue is obsolete because of intergration with opentelemetry.
Logs can be ingested into Grafana Tempo or Jaeger.

Please let me know if there is a specific use case for json logs that isn't covered by the opentelemetry integration.
