### ISSUE TITLE
Validator nodes get stuck at the beginning of an epoch

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#6323]
Multiple validators reported that their nodes get stuck in the beginning of an epoch. Neard is still running but no new block is processed. For example, [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/13601726/154857076-4d1a9262-6fec-4acf-8ebf-46d2dde5abee.jpg)</span>](https://user-images.githubusercontent.com/13601726/154857076-4d1a9262-6fec-4acf-8ebf-46d2dde5abee.jpg)

At the same time, we observe that the block processing time at the beginning of an epoch spikes [https://grafana.near.org/d/zzGDUdcnk/block-processing-and-chunk-delay?viewPanel=18&orgId=1&from=now-7d&to=now&var-chain_id=mainnet&var-role=canary&var-node_id=All](https://grafana.near.org/d/zzGDUdcnk/block-processing-and-chunk-delay?viewPanel=18&orgId=1&from=now-7d&to=now&var-chain_id=mainnet&var-role=canary&var-node_id=All) There seems to be something wrong with the start of an epoch. Note that the [block processing time metric](https://github.com/near/nearcore/blob/11279e91dbc67f397323eb138a071a592c830118/chain/chain/src/metrics.rs#L18) measures the time spent in [this function](https://github.com/near/nearcore/blob/4038f249bcc58abf52db117df6f40cd25504d118/chain/chain/src/chain.rs#L1316), so it should be unrelated to #5709

**Comment by ashpooljh** [comment]
Restarting the node helps unstuck it. After restarting the node it will proceed to operate normally until the beginning of the next epoch. During the first few minutes of every new epoch the node is very likely to stall again.

**Comment by bowenwang1996** [comment]
More info from validators: this usually happens with an increase in cpu and memory usage. So it feels similar to https://github.com/near/nearcore/issues/6126. @mzhangmzz do you think the change to chunk request logic in 1.24.0 may have contributed to this?

**Comment by mzhangmzz** [comment]
@bowenwang1996 actually seems like this issue was resolved after the validators increased their machine spec, so it's probably due to the chunk request logic change

**Comment by bowenwang1996** [comment]
> Do we observe this in any of our rpc nodes?

We didn't observe this on any of the nodes we run

**Comment by bentleybm** [comment]
We have only increased disk capacity but left CPU at 8 and memory at 16GB. We are noticing the spike only in CPU usage. However, since March 13th we have had a 10% growth in disk consumption indicated in attachments. If you need more detail on the spikes I can provide exact time stamps.
![image](https://user-images.githubusercontent.com/12435807/158852926-d645453b-1d00-45d2-94b2-c9008e6c3f70.png)
![image](https://user-images.githubusercontent.com/12435807/158853165-c89582d8-68f9-482e-8a69-da17765da729.png)

**Comment by janewang** [comment]
From Lunanova

> As requested, please find logs [LunaNova_NEAR_Validator_20220324.log.tar.gz](https://github.com/near/nearcore/files/8366455/LunaNova_NEAR_Validator_20220324.log.tar.gz) or our node that was running as a validator at the start of the current epoch. Approximately 3.5 hours in to the epoch it began dropping blocks and after alerts were triggered we migrated the identity to one of our backup nodes. This is the second time we've encountered an issue with the v1.25.0 software. With previous versions of the software we rarely encountered issues with our current hardware configuration. 
> I took a look at the github issue you linked and I can see there is some discussion about whether this could be due to insufficient system resources. Our nodes are configured in VMs provisioned with 8 core /16 thread CPU (AMD EPYC 2nd generation) and 16Gb RAM. I took a look at our Prometheus metrics at the time of the incident and could see no spike in CPU or memory usage at the time.
