### ISSUE TITLE
Allow log levels to be changed without shutting down neard

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#6364]
It is desirable to be able to change the log level of a node while it is running because 1) having very verbose logs on by default affects performance and generates a huge amount of logs and 2) when debugging a node, restarting the node may lead to a change of state and loss of information.

@nagisa do you have any idea what the best way to do this is?

**Comment by nagisa** [comment]
Using the [`tracing_subscriber::reload`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/index.html) is perhaps the most flexible option to achieve this.

**Comment by nagisa** [comment]
Do we have an idea on how we'd inform a running process that the log level needs to be changed? Once we figure it out, implementing this shouldn't be difficult.

**Comment by bowenwang1996** [comment]
> Do we have an idea on how we'd inform a running process that the log level needs to be changed? Once we figure it out, implementing this shouldn't be difficult.

Good question. We can potentially do this through a rpc call. Do you have any suggestions?

**Comment by nagisa** [comment]
Other alternative options I can think of are watch for modifications to some configuration file or perhaps just have a location in the filesystem (e.g. `$NEAR_HOME/verbose`) which if present makes `neard` log verbosely while it exists.

RPC has a benefit that the admins can turn on/off debug logging remotely without direct access to the machine and if some sort of distributed log aggregator is being used, there can be a switch to make one or other node become verbose from the log aggregator view.

**Comment by matklad** [comment]
An alternative to a temporal switch would be a spatial switch: log only `info` to stderr, and dump `debug` to a rotated file.

**Comment by nagisa** [comment]
A spatial switch mostly doesn’t address the performance motivations for not logging debug at all, does it? Every `debug!` will invoke the tracing machinery to get the event/span into the subscriber.

**Comment by matklad** [comment]
Correct! For perf, I *think* we are still not doing https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/struct.NonBlocking.html, which feels like it could be an easy win.

**Comment by vlad-kopcil** [comment]
Limiting to localhost might be providing false sense of security here. 
While modifying or creating file follows permissions, any local process can reach localhost. You'd still need to implement some other checks, like ownership of process connecting to you service at very least.

Also, I specifically did say that monitoring config files periodically is not a good idea :)

**Comment by mina86** [comment]
We might need to bite the bullet and implement Google authentication or some other OAuth in general for all `/debug` paths.
