### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.72`

### ISSUE THREAD

**Issue by raojianli** [near/nearcore#6378]
os :mac version: 1.24.0

error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by: process didn't exit successfully: `/Users/abel/bworkspace/blockchain/near/nearcore/target/release/build/openssl-sys-f351fd47df521c03/build-script-main` (exit status: 101) — stdout

**Comment by bowenwang1996** [comment]
@nagisa @matklad  I think we fixed something around openssl versions. Do you happen to know what this might be about?

**Comment by matklad** [comment]
This seems unrelated to that issue we had a while back. Was that the full output of the build? It feels strange that there isn't any kind of error message. Re-running with `cargo build -vv` (very verbose) might help.

**Comment by nagisa** [comment]
I'm surprised we vendor and build our own copy of openssl, rather than using the system provided one. 

Guesstimating, since there's no output, but you might be missing a tool (perl, a C compiler, make) necessary to build openssl.

**Comment by telezhnaya** [comment]
Hey!
Please update to the latest version and feel free to re-open if it's still an issue for you
