### ISSUE TITLE
Upgrade to Rust 1.60, skipping 1.59

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6400]
Rust 1.59 was released recently: https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html

This is a big release, but it contains one notable regression: incremental compilation is off by default. This would be a big hit for the development velocity, so I suggest skipping this upgrade and move directly to 1.60, once that is released.

**Comment by kakoc** [comment]
I think it could be closed
