### ISSUE TITLE
Disable state sync from validators

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#6462]
State syncs are expensive and given that most nodes today do track all the shards, nodes don't need to do state sync from validators and it can reduce resource usage for validator nodes.

**Comment by bowenwang1996** [comment]
@mzhangmzz this issue isn't addressed by #6471. A regular node can still state sync from a validator node and state sync requests can be expensive.

**Comment by mzhangmzz** [comment]
@bowenwang1996 I guess I understood this wrong. Do you want regular nodes to send their state sync requests to non-validators? Are you worried that state sync requests sent to validators are slowing down validators?

**Comment by bowenwang1996** [comment]
> Are you worried that state sync requests sent to validators are slowing down validators?

Yes
