### ISSUE TITLE
Miss upgrade again

### ISSUE THREAD

**Issue by appop** [near/nearcore#6474]
Could you give a prompt every time we upgrade whether we need to upgrade or not, we have reset the data several times.

**Comment by bowenwang1996** [comment]
> Could you give a prompt every time we upgrade whether we need to upgrade or not

This is done in the release notes. If `PROTOCOL_UPGRADE` is `true` then you need to

**Comment by janewang** [comment]
Hi @appop  Please take a look at the near node docs for the release notes. https://near-nodes.io/maintenance/maintenance
