### ISSUE TITLE
nearcore snapshot delayed about a week

### ISSUE THREAD

**Issue by barryz** [near/nearcore#6475]
We followed the official [doc](https://near-nodes.io/intro/node-data-snapshots) and downloaded the latest snapshot of nearcore, and when the node starts, it shows that the most recent block height is 61614213. This situation may take a long time to sync to the current height. 

Is the possible cause the wrong snapshot file was uploaded?

**Comment by bowenwang1996** [comment]
That is indeed the cause. @barryz it should be fixed now.
