### ISSUE TITLE
Switch ext costs to strum

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6520]
We use the following open-codded pattern to "reflect" on the number of elements in an enum.

https://github.com/near/nearcore/blob/cf6c3177dd0b0bc883038d5c320d92197dd9f315/core/primitives-core/src/config.rs#L615-L617

We should switch that to the `strum` crate, as we use it elsewhere. 

I am not entirely sure that using `strum` for these is worth it (the usual argument -- a little boilerplate compiles much faster than a little of proc-macro), but we definitely should be consitent, and we use `strum` today.

**Comment by AnhTuDo1998** [comment]
Hi, I am new to NEAR and would like to try out this problem. 

I do notice that the enum ActionCosts in the same file also has this open-codded pattern. Should we fix this also ?

**Comment by matklad** [comment]
Yes!
