### ISSUE TITLE
Remove impl From<EpochConfig> for ShardConfig

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6553]
Basically, remove this

https://github.com/near/nearcore/blob/6dd51ec4e981798fae16a60b49a20cf09faac5b7/core/primitives/src/epoch_manager.rs#L64-L73

and replace with just 

```rust
impl ShardConfig {
  pub fn new(epoch_cofig: &EpochConfig)
}
```

The `From` impl requires an owed `EpochConfig`, but that contains a bunch of allocated vecs, which are just dropped. So this is a minor perf footgun.

In general, prefer `new` to `From` unless you intend to use `From` in generic contexts (or it fits the semantics of injective mapping *really* well)

**Comment by matklad** [comment]
cc @mzhangmzz

**Comment by mzhangmzz** [comment]
Thanks!

**Comment by kakoc** [comment]
Seems that can be closed due to https://github.com/near/nearcore/pull/6568

**Comment by mina86** [comment]
By the way, in the future you can put:

```
Fixes: https://github.com/near/nearcore/issues/6553
```

in PR’s description and once the PR is merged it will automatically
close the corresponding issue.
