### ISSUE TITLE
Don’t ignore RocksDB iterator errors

### ISSUE THREAD

**Issue by mina86** [near/nearcore#6583]
RocksDB iterator will return None on error and requires <span class="error">[status method]</span>([https://docs.rs/rocksdb/latest/rocksdb/struct.DBRawIteratorWithThreadMode.html#method.status](https://docs.rs/rocksdb/latest/rocksdb/struct.DBRawIteratorWithThreadMode.html#method.status)) to be called to check if there were any errors. We’re currently not doing that which means we’re silently ignoring any errors during iteration. This needs to be fixed. Possibly by changing `iter` et al methods to iterate over `Result`s.

**Comment by kris524** [comment]
Hello, can I pick this issue? If there is any additional info that can help me let me know

**Comment by mina86** [comment]
Go ahead.

There isn’t much additional info other than the fact that you’ll be mostly looking at core/store/src/db.rs and core/store/src/db/refcount.rs files. Changing implementation for TestDB should be a trivial matter of just wrapping the values in an `Ok(...)`. With implementation for RocksDB you’ll need to wrap values and then at the end of the iterator check underlying rocksdb iterator’s status and either return None or Some(Err(...)).

Quick greps shows nine places where the methods are called. Updating those shouldn’t be that complicated either. Though some places which weren’t previously fallible may now fail so you might need to introduce error-propagation paths in a couple places.
