### ISSUE TITLE
update to stable actix web

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6599]
We use a bunch of actix-web related crates at random versions:

*   actix-web 4.0.0-beta.6
*   actix-http 3.0.0-beta
*   forked actix-cors
*   forked paperclip

Now that actix-web 4 is released, all of the above impose a tax on us, as they make upgrades more painful, all the while ecosystem moves on. We should unfork these non-essential dependencies.

**Comment by matklad** [comment]
cc @miraclx I wonder if there's anything preventing us from just doing the upgrades here? (as in, I don't have a backstory as to why we ended up in this situation, but I am guessing that you might know)

**Comment by miraclx** [comment]
Yes, it was the next step after https://github.com/near/nearcore/pull/6573. I'll tackle it before the end of the week.

**Comment by frol** [comment]
@matklad The backstory was initially called futures 0.2, then it was futures 0.3 and async/await, then it was transformed into tokio 1.0 release story and pulled actix, actix-web, and paperclip into being forked. It seems that all of those (even actix-web and paperclip) have reasonable releases cut on crates.io!

@miraclx It is tiresome work, but I hope it is the last time we actually need to go through this cumbersome process, and hopefully we don't need to go into that rabbit hole ever again 🙏
