### ISSUE TITLE
Look into removing DBCol::ChunkHashesByHeight or DBCol::ChunkPerHeightShard

### ISSUE THREAD

**Issue by mina86** [near/nearcore#6792]
DBCol::ChunkHashesByHeight is indexed by height and contains `Vec<ChunkHash>` values. DBCol::ChunkPerHeightShard is indexed by (height, shard) and contains `ChunkHash` values. It looks like the two columns contain the exact same data. It could be worth looking into simplifying the database by getting rid of one of the columns.

**Comment by mina86** [comment]
Closed by https://github.com/near/nearcore/pull/7671

**Comment by robin-near** [comment]
LOL I did not even realize I had unknowingly resolved this issue :)
