### ISSUE TITLE
Unable to run the node DBError("IO error: No such file or directory: ...)

### ISSUE THREAD

**Issue by KorayBarkin** [near/nearcore#6801]
When I try to run the node it gives me this error:
```
ubuntu@ip-172-32-1-164:~/near/nearcore$ ./target/release/neard --home ~/.near run
2022-05-13T12:45:53.920837Z  INFO neard: version="1.26.0-rc.3" build="crates-0.12.0-283-gc164b7df5" latest_protocol=53
2022-05-13T12:45:53.924602Z  INFO near: Opening store database at "/home/ubuntu/.near/data"
thread 'main' panicked at 'Failed to open the database: DBError("IO error: No such file or directory: While opening a file for sequentially reading: /home/ubuntu/.near/data/MANIFEST-5280556: No such file or directory")', core/store/src/migrations.rs:48:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I did install near files in /home/ubuntu/near/nearcore but .near is in the root folder (/home/ubuntu/.near) does the problem related with this one? I checked the file location and there isn't file created named MANIFEST-5280556.

**Comment by mina86** [comment]
Could you provide output of `find ~/.near -type f`?

**Comment by mina86** [comment]
Is that an existing node that you’re upgrading or did you [download the snapshot](https://near-nodes.io/intro/node-data-snapshots)? My best guess at this moment is that you didn’t download all the files because I don’t see how else you could get to a state where `data` directory is missing MANIFEST files.

**Comment by KorayBarkin** [comment]
> 

I did followed this steps on documentation:

```
$ aws s3 --no-sign-request cp s3://near-protocol-public/backups/mainnet/rpc/latest .
$ LATEST=$(cat latest)
$ aws s3 --no-sign-request cp --no-sign-request --recursive s3://near-protocol-public/backups/mainnet/rpc/$LATEST ~/.near/data
```

**Comment by KorayBarkin** [comment]
I guess figure it out what's the problem. Due to not having enough space in the root directory it did not fetch the all snapshots. I did mount the memory to /near folder, now, it's downloading whole files. Thanks for your help!
