### ISSUE TITLE
Remove the logic to add dummy data to estimator test contracts

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6822]
When running parameter estimator, we have some logic to pad it with dummy data to various sizes:

https://github.com/near/nearcore/blob/5fff3e6e9e18afd97f1d33a1c7f78e179f6aca9b/runtime/runtime-params-estimator/test-contract/build.sh#L46-L53

We should get rid of this, for a couple of reasons:

* I believe we are not actually using this anymore
* Padding with just data is not the best, as it hits the best-case, not the worst case
* Even if we do want to do such padding, probably better to do it via wasm encode in code

**Comment by matklad** [comment]
@jakmeier I think we should do this, as it's clear tech debt. Do you have some spare cycles? I feel I can also spend some cycles here ,feel free to re-assign.

**Comment by jakmeier** [comment]
@matklad thanks for reminding, I'll push it up on my internal priority queue a bit. Should not be much work.

**Comment by jakmeier** [comment]
Having done this in #7067, I think we should probably remove `build.sh` entirely and replace it with Rust / xshell. Feels cleaner to me.
@matklad WDYT?

If we want to remove it, I can most likely find time for it this week. Or if you want to do it, that would also be appreciated. :)

**Comment by matklad** [comment]
Yeah, we should kill `build.sh`. Using `xshell` or maybe just manual command invoction would work. We could extract some helper to build a contract out of `near-test-contracts` presumably. 


It also makes sense to think who should be in charge of building the contract for estimation -- the host (so that the contract is treated as an input to the estimator) or the target (so that we use specific pinned rustc from the docked image to build the contract). 

I think I am unlikely to have capacity for this -- I'll be looking at some of the core issues in the comming weeks I think.

**Comment by jakmeier** [comment]
Cool, thank you for this valuable input!

I created #7070 to track this and will try to work on it this week.
