### ISSUE TITLE
test_dropping_routing_messages is flaky

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6823]
Noticed it failing a couple of times: 

* https://buildkite.com/nearprotocol/nearcore/builds/16295#2f03a668-aae3-4c59-8eba-563924bcc5c1/6-3029
* https://buildkite.com/nearprotocol/nearcore/builds/16287#cbd70a98-fabf-46ee-aeeb-5193cae376f0/6-3096
* https://buildkite.com/nearprotocol/nearcore/builds/16360#220c7c4f-06f3-4123-9083-cd794bd3c206/6-3074

**Comment by matklad** [comment]
cc @pompon0, another ToT guidelines violation :)

**Comment by pompon0** [comment]
:) you mean flakiness in general, or some more specific tott?

**Comment by matklad** [comment]
flakiness in general -- I think "not having flakes" is one of the primary goals at google (at least according to SWE@G book)

**Comment by pompon0** [comment]
sure, ack, on it

**Comment by pompon0** [comment]
The test tests::network::routing::test_dropping_routing_messages apparently times out (the timeout is hardcoded to 15s). When I run the test repeatedly on all cores locally with the same flags the test consistently completes in 4s. I'll increase the timeout to 30s. If it doesn't help, then we should probably try to reproduce the timeout on the buildkite infra.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
