### ISSUE TITLE
RPC end point to configure broadcast transaction await

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#6837]
**Describe the use case** Currently there is only option to either broadcast tx or broadcast and wait for finality. There should be a way to configure what user wants to wait when broadcasting tx.

**Proposed solution** Deprecating both `broadcast_tx_async` and `boardcast_tx_commit` and replacing it with a new configurable `broadcast`:

<pre>enum BroadcastWait {
 /// Returns right away.
 None,
 /// Waits only for inclusion into the block.
 Inclusion,
 /// Waits until block with inclusion is finalized.
 InclusionFinal,
 /// Waits until all non-refund receipts are executed.
 Executed,
 /// Waits until all non-refund receipts are executed and the last of the blocks is final.
 ExecutedFinal,
 /// Waits until everything has executed and is final.
 Final,
 }</pre>

**Comment by telezhnaya** [comment]
In my opinion, we want to redesign `tx` method as well
https://docs.near.org/api/rpc/transactions#transaction-status

Now the doc says "please go and check the statuses of all receipts, the finality of the blocks, etc"
It would be useful to take this responsibility on us

**Comment by ilblackdragon** [comment]
If implemented and used by wallets, this can speed up perceived transaction speed by 5-7 seconds in wallets.
