### ISSUE TITLE
Take storage configuration into consideration when opening storage

### ISSUE THREAD

**Issue by mina86** [near/nearcore#6857]
Currently we have a bunch of places where we open RocksDB with `create_store` which uses a default store configuration.  The defaults usually work just fine so this is not an issue but as we add more options it may be necessary to take them into consideration.  In particular, I’m envisioning adding a `path` to `StoreConfig` such that it won’t be possible to assume path being `<home>/data`.

**Comment by Mic92** [comment]
This can also break setups for example currently I have to patch neard to not bypass my max_open_files limit when checking the rocks db version, because my unittests run a sandbox that limits the amount of open file descriptors.

**Comment by Mic92** [comment]
> This shouldn’t affect tests since tests keep using default configuration. In non-tests this will make them respect max_open_files limit set in configuration file.

Sorry that came a bit out of context. I was talking about our tests not the one used by neard. We are building a supervisor on top of neard, that implements ha failover and testing them in a nix build.

> 
> @Mic92, do you have no way to update the hard limit in the sandbox?

On the machines we control yes, but we want later also normal nix users to be able to test this without having to change their setup.
