### ISSUE TITLE
genesis_config can be modified manually

### ISSUE THREAD

**Issue by markotonic** [near/nearcore#6868]
**Describe the bug** [genesis_config.json](https://github.com/near/nearcore/blob/master/nearcore/res/genesis_config.json) is generated by [update_res.py](https://github.com/near/nearcore/blob/master/scripts/state/update_res.py). This file should not be modified by hand. However, no automated test catches a manual modification to this file. This could be fixed by running the same logic in `update_res.py check`.

**To Reproduce** Modify any field in `genesis_config.json` and run tests.

**Expected behavior** A clear and concise description of what you expected to happen.

**Version (please complete the following information):**

*   nearcore commit/branch: master (d159821834107f2d2b975695005ee9e7b62af0c8)
*   rust version (if local) 1.60.0
*   local

**Comment by mina86** [comment]
> However, no automated test catches a manual modification to this file.

This isn’t true.  We’re running `update_res.py check` as part of presubmit tests.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
