### ISSUE TITLE
network tests are flaky

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6935]
Running

 $ cargo t -q --features nightly -p integration-tests --lib – tests::network

with high CPU load (compiling rust-analyzer in the background) makes some test fail with timeouts. I am not sure I've seen such failures on CI. The immediate problem I face is that such failures interfere with investigating different flake ([https://github.com/near/nearcore/issues/6920](https://github.com/near/nearcore/issues/6920))

**Comment by matklad** [comment]
cc @pompon0, looking at this more, it seems that this indeed causes CI failures, but somehow they fire through `chunks_produced_and_distributed_2_vals_per_shard`. See details in #6920

**Comment by pompon0** [comment]
can you list the flaky tests for me?

**Comment by nagisa** [comment]
https://buildkite.com/nearprotocol/nearcore/builds/23318#018512c9-e764-40f8-b2ba-bccf5ecb67eb is another flaky test (`tests::network::ban_peers::dont_connect_to_banned_peer`) specimen.

[The logs from this test run (in case the link expires)](https://github.com/near/nearcore/files/10236699/nearcore_build_23318_cargo-test-integration-tests-star.log.gz)

**Comment by akhi3030** [comment]
Another instance of flaky test: https://buildkite.com/nearprotocol/nearcore/builds/23297#01851027-c2de-4d11-813c-e84b69e64bef.

**Comment by walnut-the-cat** [comment]
maybe related to https://github.com/near/nearcore/issues/8855
