### ISSUE TITLE
Rename the `function_call_cost_per_byte` parameter

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#7021]
Is isn't immediately apparent from the name which bytes (parameters) are being charged here, and there have been more instances than one where there was confusion about this, so lets make sure the name makes it self-documenting.

**Comment by matklad** [comment]
We now have `wasm_contract_loading_bytes` cost which actually measures what one would *think* function call cost should measure. I think having the right cost here goes a long way to remove confusion here, so I don't think it's necessary to reame the cost after all. like, it'll probably marginally help, but not worth it anymore, so closing.
