### ISSUE TITLE
Staking Smart Contract V2 (pool.near)

### ISSUE THREAD

**Issue by PizBernina** [near/nearcore#7032]
Since we have to migrate to the new staking pool smart contract I was looking for the smart contract. Is this the official one: https://github.com/referencedev/staking-farm/blob/master/staking-factory/src/lib.rs ?

If so, are 30% [link to code ](https://github.com/referencedev/staking-farm/blob/b7e53dd2c6bdceabdafe5af6db99d1bd2b7a5c3f/staking-factory/src/lib.rs#L20)
taken from gas or the staking rewards? It seems to be hard coded and only the factory can change it.

[Here ](https://github.com/referencedev/staking-farm/blob/07c60f04d69847723ab0629acdc9379a264d21fb/staking-farm/src/internal.rs#L244)it says NEAR staking rewards. `            let burn_fee = self.burn_fee_fraction.multiply(total_reward);
`

**Comment by telezhnaya** [comment]
Hey!
Sorry for the late response.
I don't think you have to migrate somewhere, you can still use https://github.com/near/core-contracts/tree/master/staking-pool
