### ISSUE TITLE
can't find block 9820429

### ISSUE THREAD

**Issue by macrocan** [near/nearcore#7089]
**Describe the bug**
can't find block 9820429 from https://archival-rpc.mainnet.near.org and blockexplorer

**To Reproduce**
get block by jsonrpc

**Expected behavior**
a block

**Screenshots**
{"jsonrpc":"2.0","error":{"name":"HANDLER_ERROR","cause":{"info":{},"name":"UNKNOWN_BLOCK"},"code":-32000,"message":"Server error","data":"DB Not Found Error: BLOCK HEIGHT: 9820429 \n Cause: Unknown"}

**Comment by bowenwang1996** [comment]
Block heights are not necessarily consecutive. You can query block 9820430 to see that its previous block is 9820428.
