### ISSUE TITLE
Running Bytecode other than WebAssembly on NEAR?

### ISSUE THREAD

**Issue by PaulFidika** [near/nearcore#7116]
I'm wondering how feasible this is: instead of writing smart-contract code in Rust and then compiling it down to a wasm file and running that, what if I wanted to write code in Move, compile to Move's native bytecode, and then run that in the NEAR?

It sounds kind of insane, but Move is a blockchain-specific language similar to Rust that was created by Facebook for its now defunct Libra / Diem project originally, and I think it's quite promising. However Move has its own bytecode (it can't be compiled to wasm). What would have to happen for something like this to work? Would it have to be a complete rewrite of Nearcore?

You can learn about it here:

https://move-book.com/introduction/getting-started.html

**Comment by mina86** [comment]
This isn’t feasible.  It’s not too hard on technical level.  All that’s needed is adding Move VM to contract runtime.  The real problem is that this would introduce new attack vectors and would need to be maintained.  All that without offering any tangible benefits.
