### ISSUE TITLE
init doesn’t handle download errors correctly

### ISSUE THREAD

**Issue by mina86** [near/nearcore#7122]
https://github.com/near/nearcore/issues/7121 shows that download errors (403 in that case) are not handled correctly and init continues even though the file wasn’t downloaded.

(One more reason to do second point from https://github.com/near/nearcore/issues/6416#issuecomment-1155234660 ?)

**Comment by andrei-near** [comment]
Fixed in https://github.com/near/nearcore/pull/11456
