### ISSUE TITLE
How to setup external_address ?

### ISSUE THREAD

**Issue by scholtz** [near/nearcore#7198]
Hi, I am quite new to near, but I would like to run the node in k8s with public ip setup. In kubernetes, so the app thinks it is on private network, but for outside world it should look as running on public ip address.

**Describe the bug**
I see in the configuration external_address , but when i search near organization for the code usage it does not seems to be used anywhere besides defining configiguration.

**To Reproduce**
[Git search](https://github.com/search?q=org%3Anear+external_address&type=code)

**Expected behavior**

I assume the documentation should work 
    /// Address to advertise to peers for them to connect.
    /// If empty, will use the same port as the addr, and will introspect on the listener.

https://github.com/near/nearcore/blob/7db5ca0f996f0319330d2f88af836f56d126e5a9/chain/network-primitives/src/config_json.rs#L52

**Screenshots**
![image](https://user-images.githubusercontent.com/1223439/179283239-239e3fdb-27f5-4e30-aa9b-af205a6779f8.png)

**Version (please complete the following information):**
- nearcore: master branch

**Comment by mina86** [comment]
Indeed.  It appears the field isn’t used and in fact has never been used.  You can just set it to empty value.

**Comment by scholtz** [comment]
@mina86 Btw i dont think that this should be closed.. i guess you should either remove it from config options, or make announcing of the node public address possible.  I prefer the second option :)

**Comment by mina86** [comment]
Well, this issue was a question which I’ve answered.  I’ve [discussed](https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/external_address) and am tracking removal of the field separately.  As for announcing public addresses, there’s [a separate design](https://docs.google.com/document/d/1RDd9ETfLQL_JfnEePmUPjkLvIxAtLV-c5AKWV8IMJEo/edit) for it which is being worked on.
