### ISSUE TITLE
Remove `bytes_as_str`

### ISSUE THREAD

**Issue by matklad** [near/nearcore#7203]
We have `bytes_as_str` module to support serialization of `Vec<u8>` which is secretely a `String` (ie, valid utf8). I belive this code is now unused and can be removed. That is, `Serialize` can be dropped from all structs that actually use this (and potentially we can remove `serde` for vm_logic altogether?)

**Comment by akhi3030** [comment]
> @akhi3030 not really: I think we can just remove all `derive(Serialize)` from stuff which uses`bytes_as_str`. The problem isn't that it should be `String`, the problem is that we are not actually serializing this stuff at all.
> 

Hmm... in that case should we using something like https://docs.serde.rs/serde_bytes/ instead?  Otherwise, won't we get a very inefficient handling of such vectors?

**Comment by matklad** [comment]
I mean we can remove serializtion completely: 

```diff
diff --git a/runtime/near-vm-logic/src/types.rs b/runtime/near-vm-logic/src/types.rs
index 334d5015b..518f0ccdf 100644
--- a/runtime/near-vm-logic/src/types.rs
+++ b/runtime/near-vm-logic/src/types.rs
@@ -8,10 +8,9 @@ pub type PromiseIndex = u64;
 pub type ReceiptIndex = u64;
 pub type IteratorIndex = u64;
 
-#[derive(Debug, PartialEq, Serialize, Deserialize, Clone)]
+#[derive(Debug, PartialEq Clone)]
 pub enum ReturnData {
     /// Method returned some value or data.
-    #[serde(with = "serialize::bytes_as_str")]
     Value(Vec<u8>),
 
     /// The return value of the method should be taken from the return value of another method
```

At least, I *think* we should be able to do that, this needs checking!

**Comment by akhi3030** [comment]
Ah, I see, OK, let me play with this then.
