### ISSUE TITLE
Update latest_deploy and latest_release on new release

### ISSUE THREAD

**Issue by mina86** [near/nearcore#7210]
Our current release process is as follows:
1. Prepare new release.
2. Kick off nearcore-release which builds the executables and uploads them to S3.
3. Announce the new release and ping SREs about it.
4. SREs kick off deployment which (among other things) updates latest_deploy and latest_release files on S3.

The problem is that nearup uses the latest_deploy and latest_release files to figure out what is the latest binary.  So while users expect to be able to run the new executable as soon as the announcement happens, they in reality need to way unspecified amount of time until deployment on our side starts.

We might want to move when the files are updated.

**Comment by andrei-near** [comment]
nearup is deprecated
