### ISSUE TITLE
node crashes in macOS GitHub actions test workflow due to std::time inconsistency

### ISSUE THREAD

**Issue by ChaoticTempest** [near/nearcore#7235]
**Describe the bug**
The near node crashes when running on the `macos-latest` platform within Github Actions workflow. The backtrace can be found in the workspaces-rs [test branch](https://github.com/near/workspaces-rs/runs/7439908888?check_suite_focus=true). It's caused from `PeerManagerActor::update_routing_table_trigger` when calling into `self.clock.now() - PRUNE_UNREACHABLE_PEERS_AFTER`. This panic is only happening in Github Actions, and regularly works on the ubuntu instance of GithubActions, and also on a local macOS computer (x86 and M1).

**To Reproduce**
Run `neard` on Github Actions macos-latest. A crash should occur pointing `PeerManagerActor::update_routing_table_trigger`.

Or just fork off the branch from https://github.com/near/workspaces-rs/tree/test/non-deterministic-tests since that's already pulling in the nearcore binary with macos-latest.

**Expected behavior**
Does not crash the node with overflow

**Version**
- nearcore master/13a66dda709a4148f6395636914dca2a55df1390
- localnet/sandbox

**Additional context**
Found related issue in https://github.com/rust-lang/rust/issues/48980 where this panic is platform specific, so not sure if there's a straightforward solution to this.

**Comment by volovyk-s** [comment]
Can we prioritize this issue? We are forced to disable macOS tests in Workspaces JS, RS, SDK JS, and all the projects that will use Workspaces tests.

**Comment by matklad** [comment]
closed by #7341
