### ISSUE TITLE
Browser gives a warning when accessing Docs site

### ISSUE THREAD

**Issue by krakxn** [near/nearcore#7249]
## Description:

The link (specifically: https://docs.nearprotocol.com/docs/contribution/contribution-overview) gives me this warning; of course, could be just a security cert. expiry -- but worth looking at, maybe for enhancement or attention.

![image](https://user-images.githubusercontent.com/108299225/180661657-c0d78ffc-5936-408e-9f0a-107a4f322ce3.png)

*Caveat: If it never had security cert.*

*Note: The clock part is correct, so nothing on my end*

Cheers!

**Comment by mina86** [comment]
> Expires on: 15 July 2022

@rtsai123, I’m guessing it’s owned by SRE team?

**Comment by mm-near** [comment]
it is fixed now -- thanks for reporting @krakxn

**Comment by krakxn** [comment]
Awesome!
