### ISSUE TITLE
Run a 1.27.0 rpc node failed

### ISSUE THREAD

**Issue by jaslin-W** [near/nearcore#7293]
Hi, teams. When i  run a 1.27.0 rpc node. I get this error. 
I have download config and aws s3 data. I follow this doc https://near-nodes.io/rpc/run-rpc-node-without-nearup
<img width="1666" alt="image (7)" src="https://user-images.githubusercontent.com/65018397/181669776-f6948fae-1535-402c-a451-4a9ab56c98c4.png">
Plz help me to solve this. Thanks

**Comment by andrei-near** [comment]
Likely neard misconfiguration.
