### ISSUE TITLE
Mainnet validator issue

### ISSUE THREAD

**Issue by DDeAlmeida** [near/nearcore#7306]
Mainnet node, used snapshot, latest config and latest genesis.

Launch node => Sync with only 1 peer
Then stuck

Impossible to have more peer,
tried modify network => addr
network => added another mainnet node in bootnode
network => external addr

Nothing help

![image](https://user-images.githubusercontent.com/52310650/182047598-74c9cdb1-68cb-4cf6-9d0d-a5eff8be194e.png)
And when stucked :
![image](https://user-images.githubusercontent.com/52310650/182047614-4fe6c29b-f632-45bf-a1c7-b3696c578c53.png)
@bowenwang1996

**Comment by bowenwang1996** [comment]
cc @gmilescu

**Comment by mina86** [comment]
Could you post the start of the logs? Somewhere at the beginning node should output `Found known peers` line.

**Comment by DDeAlmeida** [comment]
![image](https://user-images.githubusercontent.com/52310650/182258460-a46be11c-0a90-4be1-b751-f3c40bfcfd60.png)
Nothing else ...

**Comment by mina86** [comment]
‘Attempting to connect to a node with a different genesis block’ indicates that the node somehow has guildnet nodes in its peer store.  Could you double check that boot nodes in config.json are the one from mainnet’s config?  There’s sadly no good way to clear out peer store.

**Comment by mina86** [comment]
```
ldb --db="$HOME/.near/data" --column_family=col10 deleterange --hex 0x000000000000000000000000000000000000000000000000000000000000000000 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
is the best we’ve got.  `ldb` comes from `rocksdb-utils` and it needs to be a fairly recent one.

**Comment by DDeAlmeida** [comment]
> 

I used mainnet yes. I double check md5 with another mainnet node which run well

**Comment by DDeAlmeida** [comment]
> ```
> ldb --db="$HOME/.near/data" --column_family=col10 deleterange --hex 0x000000000000000000000000000000000000000000000000000000000000000000 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
> ```
> 
> is the best we’ve got. Of course do it while the node is down. `ldb` comes from `rocksdb-utils` and it needs to be a fairly recent one.

going to try it

**Comment by DDeAlmeida** [comment]
![image](https://user-images.githubusercontent.com/52310650/182386744-fe283794-cb55-46c6-a82a-dfa279d5739b.png)
@mina86

**Comment by mina86** [comment]
```
2022-08-02T21:59:34.188869Z  WARN chain: Failed to validate chunk extra: InvalidStateRoot.
```
This would indicate that the node was running older protocol version while the rests of the network has already updated.  This caused the node to create a state transition inconsistent with the rest of the network.  This is a known issue but currently without a solution (other than starting anew).
