### ISSUE TITLE
Bind trie to specific state root / block hash

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#7362]
I propose to restrict Trie interface to get values only for one state root.

For Trie structs, we currently allow to query keys for arbitrary state roots. It wasn't an issue because we could freely query any state roots for the last 5 epochs for RPC nodes.

However, with flat state we will be able to query only the limited amount of state roots close to chain head. Because in our current usecases for **certain** Trie object we query only **one** state root all the time, I suggest to make state root a field of Trie and remove it from `get` and `get_ref`' arguments. This allow us to decide if we can use flat storage on Trie creation, and we won't need to handle the case when `get` receives state root which is not accessible from flat storage.

**Comment by mm-near** [comment]
>flat state we will be able to query only the limited amount of state roots close to chain head. 
Can you explain this part a little bit more ?

AFAIK the rollout of flat storage should not impact the data that we store in TRIE, right ?

**Comment by Longarithm** [comment]
It doesn't. This issue is only about interface we use to interact with trie
