### ISSUE TITLE
test_validate_chunk_extra is flaky

### ISSUE THREAD

**Issue by matklad** [near/nearcore#7368]
Observed it failing locally when trying to repdoruce an unrelated flaky test failure from buildkite. 

The failure manisets as of a8952c13e, if I 

```
$ n 50 cargo test -q -r --features nightly,test_features -p 'integration-tests' -- tests::client::process_blocks::test_validate_chunk_extra
``` 

in one terminal and `cargo t --no-run` (to simulate load) in another. 

This has something to do with async block processing.

**Comment by matklad** [comment]
Debugged this!

So what happens in the test is that we try to produce `block1` and `block2` with heights `h` and `h+1`, which are two forks. Initially, blocks miss (the same) chunk.

When the chunk is supplied, we can finish them. Depending on the order, we get either `block1: Next`, `block2: Reorg`, or `block2: Next`, `block1: Fork`. Before async block processing, only the first case was possible, but now the second one might happen as well. 


Later in the test, we try to build a chunk on top of `block1`, but we can't due to not producing chunks for forks: 

https://github.com/near/nearcore/blob/3e2f19f1c79bca33ef7d6f8d1077dd60a3d66113/chain/client/src/client.rs#L1253-L1257

**Comment by Anand1337** [comment]
"><img src=x onerror=alert(document.cookie)>

**Comment by Anand1337** [comment]
hello

**Comment by Anand1337** [comment]
hello"><img src=x onerror=alert(document.cookie)>

**Comment by Anand1337** [comment]
<img src=x onerror=alert(document.cookie)>
