### ISSUE TITLE
Create metrics for shard/chunk cache part1

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#7375]
We use tracing for collecting shard/chunk cache hits, but we want to be able to export such data to prometheus as well.

Metrics ideas could be taken from [https://github.com/Longarithm/nearcore/compare/master...smart-cache](https://github.com/Longarithm/nearcore/compare/master...smart-cache "smart-link") 

We may want to clean up this dashboard [https://grafana.near.org/d/Hn6kh4mVk/shard-chunk-cache-hits?orgId=1&var-chain_id=testnet&var-role=firat-testnet&var-node_type=All&var-node_id=firat-1](https://grafana.near.org/d/Hn6kh4mVk/shard-chunk-cache-hits?orgId=1&var-chain_id=testnet&var-role=firat-testnet&var-node_type=All&var-node_id=firat-1)

**Comment by firatNEAR** [comment]
Included in https://github.com/near/nearcore/pull/7429
