### ISSUE TITLE
Estimator hangs forever in `random_unused_account` if all accounts have been used

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#7448]
**Describe the bug**

Our code for `random_unused_account` ends up in an infinite loop whenever we run out of unused accounts. 
```rust
pub(crate) fn random_unused_account(&mut self) -> AccountId {
        loop {
            let account = self.random_account();
            if self.used_accounts.insert(account.clone()) {
                return account;
            }
        }
    }
```

**To Reproduce**
```
cargo run --release --package runtime-params-estimator --features required,nightly --bin runtime-params-estimator -- --accounts-num 200 --additional-accounts-num 200 --iters 3 --warmup-iters 0 --metric time --costs EcrecoverBase
```
It will never terminate.

Change it to `--accounts-num 300 --additional-accounts-num 300` and it terminates in <5s,

**Expected behavior**
Exit with an error that describes that no more unused accounts available.

**Comment by blasrodri** [comment]
I think it would also be helpful to have some logs so that if this happens again with a different configuration, the user is notified.

**Comment by jakmeier** [comment]
@blasrodri Would an error message like 

```
All accounts used. Try running with a higher value for the parameter `--accounts-num <NUM>`.
```
cover your suggestion?

**Comment by blasrodri** [comment]
> @blasrodri Would an error message like 
> 
> ```
> All accounts used. Try running with a higher value for the parameter `--accounts-num <NUM>`.
> ```
> cover your suggestion?
Yes
