### ISSUE TITLE
Compile error on Mac M1

### ISSUE THREAD

**Issue by akhi3030** [near/nearcore#7580]
**Describe the bug**
`cargo check --tests --benches` fails on top of master on Mac M1 machines.

**To Reproduce**
```
$ cargo check --tests --benches
    Checking near-vm-runner v0.0.0 (/Users/akhi/projects/nearcore/runtime/near-vm-runner)
    Checking nearcore v0.0.0 (/Users/akhi/projects/nearcore/nearcore)
    Checking near-jsonrpc-tests v0.0.0 (/Users/akhi/projects/nearcore/chain/jsonrpc/jsonrpc-tests)
error[E0432]: unresolved import `crate::wasmer2_runner`
  --> runtime/near-vm-runner/src/tests/fuzzers.rs:15:12
   |
15 | use crate::wasmer2_runner::Wasmer2VM;
   |            ^^^^^^^^^^^^^^ could not find `wasmer2_runner` in the crate root

error[E0432]: unresolved import `wasmer_engine`
  --> runtime/near-vm-runner/src/tests/fuzzers.rs:11:5
   |
11 | use wasmer_engine::Executable;
   |     ^^^^^^^^^^^^^ use of undeclared crate or module `wasmer_engine`

    Checking near-jsonrpc-fuzz v0.0.0 (/Users/akhi/projects/nearcore/chain/jsonrpc/fuzz)
For more information about this error, try `rustc --explain E0432`.
error: could not compile `near-vm-runner` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Expected behavior**
`cargo check --tests --benches` should succeed.

**Version (please complete the following information):**
- nearcore commit/branch: `72affb9`
- rust version: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- local

**Comment by akhi3030** [comment]
CC: @Ekleog-NEAR.  Maybe this is something you could take a look at.

**Comment by Ekleog-NEAR** [comment]
Right, I just submitted #7587 that fixes the build, thank you for the heads’up! It’d be great if we could get m1 CI, but last we checked it’d have be hard so…

**Comment by akhi3030** [comment]
Thanks for the quick fix.  Indeed, without a proper M1 CI, we will have to rely on me to report the occasional issues.
