### ISSUE TITLE
Don't enable SSE for wasm compilation

### ISSUE THREAD

**Issue by akhi3030** [near/nearcore#7650]
In https://github.com/near/nearcore/pull/7130 we had disabled setting SSE for WASM compilation which helped in removing a bunch of warnings for WASM compilation.  

We discovered that this PR causes some performance regressions (in effect it actually disabled SSE for x86 compilation as well) and did some investigation in https://github.com/rust-lang/cargo/pull/11114.  For now we have reverted the above PR.  This issue is to track the work to disable setting SSE for WASM in a way that does not cause a performance regression.

CC: @matklad, @mm-near

**Comment by matklad** [comment]
Status: this is fixed in Cargo, so we probably should just wait 10-ish weeks for fix to land the stable and then revert the revert. 

If someone feels strongly about this, we can try to apply some work-around faster.

**Comment by akhi3030** [comment]
I don't think this is pressing.  We can wait for a clean fix.

**Comment by pugachAG** [comment]
```
$ rustup update
...
   stable-aarch64-apple-darwin updated - rustc 1.66.0 (69f9c33d7 2022-12-12) (from rustc 1.65.0 (897e37553 2022-11-02))
```

it seems like 1.66 was released and we can proceed with this
