### ISSUE TITLE
Rosetta: Add Metadata Tagging Fee Related Operations

### ISSUE THREAD

**Issue by nasmithan** [near/nearcore#7654]
Today, a standard transfer ([explorer example](https://explorer.near.org/transactions/Ai8LX3GQEdSrFSRpyKqVvFQyroX1ycFEUc8ZhDwMjMQh)) will have 3 parts:

1.  `tx:Ai8LX3GQEdSrFSRpyKqVvFQyroX1ycFEUc8ZhDwMjMQh`, 2 payment operations. `3.3538 NEAR` as the transfer and `0.00008618 NEAR` as the gas prepayment.
2.  `receipt:6DEuh78kRc4TM2bFuuRTjAzAfYnidfZV1nh4zaozRA6t`, 1 payment operation, `3.3538 NEAR`
3.  `receipt:AYwML97wNXKSbNTqhPRRrYEv3bHuVXpuaM4Bw3heHU1Q`, 1 gas refund operation, `0.00000127 NEAR`

We need to be able to differentiate the `0.00008618 NEAR` gas prepayment operation from the `3.3538 NEAR` operation in the initial tx. Ideally we can also mark the gas refund operation.

 curl -H "Content-Type: application/json" -d '{ "network_identifier": 

 {"blockchain":"nearprotocol", "network": "mainnet"} 

, "block_identifier": 

 {"index":74553709} 

 }' 'localhost:3000/block'

 RESPONSE:

 {
 "transaction_identifier": 

 { "hash": "tx:Ai8LX3GQEdSrFSRpyKqVvFQyroX1ycFEUc8ZhDwMjMQh" } 

,
 "operations": [
 {
 "operation_identifier": 

 { "index": 0 } 

,
 "type": "TRANSFER",
 "status": "SUCCESS",
 "account": 

 { "address": "25ab96ddd0d9a8e0ab48b45c2ef7473a83c4ff7e49239b46613b3d688e024731" } 

,
 "amount": {
 "value": "-3353895615031144000000000",
 "currency": 

 { "symbol": "NEAR", "decimals": 24 } 

 }
 },
 {
 "operation_identifier": 

 { "index": 1 } 

,
 "type": "TRANSFER",
 "status": "SUCCESS",
 "account": 

 { "address": "25ab96ddd0d9a8e0ab48b45c2ef7473a83c4ff7e49239b46613b3d688e024731" } 

,
 "amount": {
 "value": "-86184677687500000000",
 "currency": 

 { "symbol": "NEAR", "decimals": 24 } 

 }
 }
 ],
 "related_transactions": [
 {
 "transaction_identifier": 

 { "hash": "receipt:6DEuh78kRc4TM2bFuuRTjAzAfYnidfZV1nh4zaozRA6t" } 

,
 "direction": "forward"
 }
 ],
 "metadata": 

 { "type": "TRANSACTION" } 

 },

Ideally all gas payments (and gas refund) can be tagged with metadata (on the operation, not the transaction). Previously `predecessor_id.address = 'system'` was used to identify gas refunds, but it doesn't seem to be working anymore. Maybe just having `metadata.operation_type = 'fee'` and `metadata.operation_type = 'gas_refund'` could work? Or just tag both as `fee`?

 "metadata" : {
 "predecessor_id" : 

 { "address" : "system" } 

 },

**Comment by bowenwang1996** [comment]
Assigning it to @frol since @firatNEAR is on vacation :)

**Comment by nasmithan** [comment]
@frol it looks like 1.28.1 doesn't have the changes from https://github.com/near/nearcore/pull/7360 so you'll likely want to build on top of what's in the existing metadata there.

**Comment by firatNEAR** [comment]
@frol https://github.com/near/nearcore/pull/7576 includes changes that fixes the 'predecessor_id' not showing on all operations problem? It will fix the gas refunds not correctly showing problem.

**Comment by frol** [comment]
@firatNEAR It seems that the problem with the "missing" predecessor id is due to local receipts and delayed local receipts, and #7576 won't solve it since local receipts and delayed local receipts are not stored in the local database.

@nasmithan It will be easier from our side to implement `operation_type` (`FEE` / `NOT_FEE`) than to expose `predecessor_id` for all the transactions, so let's define our path forward:

1. Can you use the `related_transaction` to resolve `predecessor_id` backwards, so we can drop it from metadata to avoid confusion or should we hammer it from our side?
2. `operation_type` is an ambiguous name given that there is `operation.type` field already. Any ideas of a better name? What should be the value variants? (`FEE` / `NOT_FEE` look ugly to me, but I have no better ideas at the moment)
2. Given that 1.29 has been released just 1 hour ago, should we actually build on top of it?

@bowenwang1996 @mm-near By the way, we had a different conversation with a requirement to have fast access to local and delayed local receipts for Indexer Framework (cc @nikurt) https://nearinc.atlassian.net/browse/DPLT-348?focusedCommentId=18807

**Comment by frol** [comment]
@nasmithan given that predecessor id will only be missing when transaction receiver is the same as sender (e.g. 2FA function call, adding new access key, deploying contact) and transfers won't make sense to send to the account itself (i.e. frol.near transfer 10NAER to frol.near is pointless), can you work around the missing predecessor id?

**Comment by nasmithan** [comment]
Ideally we can keep `predecessor_id` as-is without changes. There was a separate issue where 1.28.1 didn't have `predecessor_id` so we're good for now. Just tagging fee operations is needed.

Maybe `is_fee: true/false` in metadata? Or just omit if false?

Building on top of 1.29 is great. We just need to tag the `0.00008618 NEAR` operation from the above example, and optionally tag the gas refund if it's not difficult.

**Comment by frol** [comment]
@nasmithan #7704 should cover your need. Can you give it a try?

**Comment by nasmithan** [comment]
@frol I've deployed and verified that PR on testnet, it's perfect! Thank you for making it happen! Do you know when we can expect to see it in an official release?

**Comment by frol** [comment]
@posvyatokum (as per https://github.com/near/nearcore/pull/7704#issuecomment-1262373130), please, consider including #7704 into the next 1.30.0 RC release 🙏  (I don't see any of RC cut yet, though)

@nasmithan If we will catch 1.30.0 train, it might be part of 1.30.0 release (testnet in the upcoming week, and mainnet in 2 weeks from now, I believe). Yet, feel free to just use the patch with your custom node as it does not require any protocol or database changes.

**Comment by posvyatokum** [comment]
@frol will cherry pick #7704 into 1.30.0-rc.1 that is planned for Monday (we moved the schedule a bit to avoid confusion during 1.29 protocol change).
Node team didn't yet discuss how this shift will affect mainnet schedule but I think it will not. So, assume that mainnet release is still on October 26th (Wednesday) as per community calendar https://calendar.google.com/calendar/u/1/embed?src=nearprotocol.com_ltk89omsjnc2ckgbtk6h9157i0@group.calendar.google.com (it has some problems with testnet releases, but mainnet releases seem to be accurate).
