### ISSUE TITLE
Move ShardsManager chunk management logic to a separate Actix thread

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#7662]
Right now, all chunk management logic is handled by the ClientActor thread, including the handling of partial encoded chunk messages, sending partial encoded chunk requests, responding to partial encoded chunk requests, handling partial encoded chunk responses, decoding chunks, etc. This unnecessarily clogs the ClientActor thread. We should move these to a separate actor.

**Comment by matklad** [comment]
Consider re-using existing sync jobs actor: 

https://github.com/near/nearcore/blob/3b38ad1b821248dec6f35e497b691b6e85e605f9/chain/client/src/client_actor.rs#L149-L156

That is, I think we can re-name this actor as "stuff we do in background actor". 

I don't have enough context to understand whether that 's actually a good idea or not, but seems worth consideration

**Comment by robin-near** [comment]
Hmm, I also don't have much context on what sync jobs actor does, but chunks management is also a critical task (as it affects validator latency) and not less important than ClientActor, so I don't think it should share with a generic background queue.
