### ISSUE TITLE
node_key missing in /status endpoint for non-validator nodes

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#7672]
Under `/status` endpoint, `.node_key` is missing for an RPC node. At present, from my observation, only Validators have `.node_key` present. I think all nodes should have that json entry, no matter are they validator, or not.

```
$ curl -s validator:3030/status | jq -r .version  
{
  "version": "1.29.0",
  "build": "1.29.0",
  "rustc_version": "1.62.1"
}

$ curl -s validator:3030/status | jq -r .node_key
ed25519:5Y9hW8cKBb5RnsJBqttHHC5ujz5zcZZ5xnrJPwkCWmGQ
```

```
$ curl -s rpc:3030/status | jq -r .version  
{
  "version": "1.29.0",
  "build": "1.29.0",
  "rustc_version": "1.62.1"
}

$ curl -s rpc:3030/status | jq -r .node_key
null
```

From above output my expectation from operational perspective would be that all nodes would return public part of node key via `curl -s rpc:3030/status | jq -r .node_key` however non-validators return `null`.

**Comment by kucharskim** [comment]
Shoot. I didn't even notice. I would change this and drop `node_key` for 2 `mainnet` releases and scream out loud on Telegram, Discord, email and release notes that `node_key` is renamed to `validator_key` (names based on settings in `config.json` without `_file` suffix). Then 2 releases later would introduce `node_key` back as content of the node key. However the question is then, what do expect people to put into `public_addrs` - the node key or validator key? I thought all this time that node key was added to `/status` endpoint because of `public_addrs` content.

**Comment by kucharskim** [comment]
This is super confusing and in long run, as painful as it is, I would break people scripts, but scream loud that this is going to happen.

**Comment by mina86** [comment]
I think node key should go into public_addrs but in reality I think it might not matter.  The node will connect, notice node key is different and update its bookkeeping.  @pompon0, any thoughts on what to do here?

**Comment by kucharskim** [comment]
Then why you created `public_addrs` in the first place? Keep it simple then and drop the req of node key there.
