### ISSUE TITLE
Use Cargo's "workspace inheritance" to reduce copy-paste in Cargo.tomls

### ISSUE THREAD

**Issue by matklad** [near/nearcore#7674]
We now use version of Cargo which supports workspace inheritance: 

https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

We should use this feature to:

* specify `rust-version` in one place to avoid huge diffs like in https://github.com/near/nearcore/pull/7669
* share common crates.io deps, like rocksdb

Maybe there's something else we can share here, i didn't spend more than 30 seconds thinking this, so please double check. 

We might also need to adjust the logic here: 

https://github.com/near/nearcore/blob/f9d46c3363ccf7b957f7d583b69a43496e03b672/tools/themis/src/main.rs#L14

**Comment by matklad** [comment]
cc @akhi3030

**Comment by akhi3030** [comment]
Looks like `Cargo.toml`s inside `runtime/near-test-contracts` are not part of the top level workspace or any workspace for that matter.  We will still have to manage them individually unless we can add them to the workspace.

**Comment by matklad** [comment]
Yeah, those are delibertely not part of the workspace, and they shouldn't have any shared attributes.
