### ISSUE TITLE
Is RPC node disable light mode?

### ISSUE THREAD

**Issue by UranusLin** [near/nearcore#7686]
**Describe the bug**
In [rpc node doc](https://near-nodes.io/rpc/run-rpc-node-without-nearup), said can use light mode just to set config.json whereby tracked_shards is set to an empty array. But in [Issue-7388](https://github.com/near/nearcore/issues/7388), add check tracked_shards can't be empty; it's mean RPC node disable light or change tracked_shards spec in light mode.

**To Reproduce**
change config.json tracked_shards to 
```
"tracked_shards": []
```

**Expected behavior**
RPC node can run on light mode

**Screenshots**
![截圖 2022-09-26 上午11 54 11](https://user-images.githubusercontent.com/5743898/192190820-dd94ed4e-5aff-4b41-aa73-7cb0d2f34491.png)

**Version (please complete the following information):**

- nearcore commit/branch: main
- rust version (if local): 1.64.0
- mainnet/testnet/betanet/local: testnet

**Additional context**

**Comment by akhi3030** [comment]
Sounds like this is something that someone from the node team could help with.  CC: @nikurt

**Comment by nikurt** [comment]
cc: @mina86

**Comment by andrei-near** [comment]
nearup is deprecated and configuration generated with near --init have correct values for tracked_shards. 
on a side note: leaving tracked_shards empty will not make the node to run in "light mode" anymore
