### ISSUE TITLE
Expose ProtocolUpgradeVotingSchedule via an RPC endpoint

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#7692]
Expose `ProtocolUpgradeVotingSchedule` via an RPC endpoint like `/status`. I think something along the lines of: `{"proto": 56, "timestamp": "2022-09-28T15:00:00Z"}` would be good enough for me.

Ref https://github.com/near/nearcore/commit/cdebd3fa2cf516f0b672710c404718c331dd1b07

**Comment by mina86** [comment]
But why?

**Comment by kucharskim** [comment]
So, I don't need to look into source code to know. For monitoring purposes. I would like to see the deadline in Prometheus. I could update one RPC node early and get highest protocol version and date into Prometheus and have alarms based on that.

In perfect scenario, chain would have that info, and having metric for it no matter what version of neard you are running would be even better.

Basically it would help me from operational perspective.

**Comment by mina86** [comment]
So rather than adding it to status it might be better to add a metric for it?

**Comment by kucharskim** [comment]
Sure, yeah. That would be even better. I wouldn't mind if it would be both, as I usually by hand more spent time looking at json rpc outputs from near than prometheus metrics.

**Comment by mina86** [comment]
So a question now is, should it be a separate metric whose value is the timestamp, or perhaps label on the existing near_node_protocol_version metric.

**Comment by mina86** [comment]
So Prometheus doesn’t have `label_value` function I see.  Yes, that means that separate metric is the only viable option.  `and` will need to be used to pick timestamp for the latest protocol version.  I should have a PR by EOD.

**Comment by kucharskim** [comment]
Thanks!
