### ISSUE TITLE
Consider initializing state from genesis in Chain only

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#7708]
I took a deep look on the way how we initialize state from genesis, and it looks convoluted. We call `NightshadeRuntime::initialize_genesis_state_if_needed` for this, but it makes more sense in chain. Moving it there is not trivial, because this method produces genesis state roots, which are then saved to `NightshadeRuntime`.

However, these genesis state roots don’t seem to belong to it. It is used only in `RuntimeAdapter::genesis_state`, but it itself has few usages. For example, `KeyValueRuntime` just returns empty roots.

Consequence of the current logic is that we need additional step to init flat storage:

1. In runtime initialization, `DBCol::FlatState` is populated
2. In chain initialization, `set_flat_storage_state_for_genesis` is called to set flat head in db
3. A flat storage state instance is created and added to `FlatStateFactory`

So (1) and (2) could be united.

cc @mzhangmzz

**Comment by soonnear** [comment]
According to @Longarithm , there may exist circular dependency that could be avoided based on the order of the calls.

**Comment by Longarithm** [comment]
I think I figured out a plan to complete the whole issue. It is not that easy.
1) We actually need to eliminate NightshadeRuntime::initialize_genesis_state_if_needed from Runtime. It doesn’t belong there, it modifies state, etc. But where to put it?
2) The main loop we care about is start_with_config_and_synchronization which sets the node up. And you can notice that we actually have a method Chain::make_genesis_block there. This is a perfect candidate. Yes it accepts RuntimeAdapter as an arg… but it is needed only to get state_roots which initialize_genesis_state_if_needed constructs! This is a good example of convoluted design we currently have.
3) You are right that now in every place where NightshadeRuntime::new is called we need to ensure that genesis is created if needed. There are two main places where it is called: from_config for real usecases and test_with_runtime_config_store for mocks. For the first one I think you can mostly assume that genesis is already created. Like, if it is called in tools/, then you are working with existing DB. For the second one, I think there is enough data in the context just to call Chain::make_genesis_block. Honestly this seems even better than silent genesis creation inside Runtime
4) After that, we can replace genesis with smth simpler in NightshadeRuntime::new. Like, we can pass (state_roots, genesis_block_info) and use the latter one to create flat storage. And this finally allows to get rid of “two-phase initialization” - set_flat_storage_for_genesis.

**Comment by robin-near** [comment]
We should TOTALLY do this. The runtime should have nothing to do about chain initialization, and I ran into this too when refactoring runtime away from EpochManager. Doing this refactoring should also make initilization simpler in tests.
