### ISSUE TITLE
All values from the configs should be settable via json file

### ISSUE THREAD

**Issue by mm-near** [near/nearcore#7842]
All the fields that we have in NearConfig, NetworkConfig etc - should be settable/overwritable via JSON file.

**Comment by posvyatokum** [comment]
The easy solution to the easy part is here #8124 
Now to look at 76 configs we have in nearcore, find out if they have hardcoded constants, and decide if those constants need to be configurable. It is probably easier than it sounds, but it sounds too dramatic not to announce.
