### ISSUE TITLE
Strategy for building the frontend code

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#7958]
neard currently serves the frontend debug UI as static javascript files verbatim from the compiled-in html and vanilla js source code. The lack of a frontend build system (such as npm) severely limits frontend development as we cannot easily use TypeScript, React, etc. and need to rely on unreliable third party services like unpkg.

We should figure out a reasonable strategy to build and serve the frontend.

**Comment by mm-near** [comment]
I'd personally try to keep our debug pages simple & lightweight (at least the ones that we compile into nearcore).


If we want to go 'deeper' into getting real frontend - then we could think about deploying it as a separate binary, 'next to' neard.

**Comment by matklad** [comment]
Not that I have a stake here, but my vote would also be to keep it simple: raw JavaScript & CSS, with maybe one or two core libraries for stuff. We won't be able to do fancy stuff, but I'd say absence of fanciness is a feature for debug pages, as it makes it easier to hack them. 

I do think there's a lot of potential for improvement by just "untangling" our htmls and basically just laying out the source code nicely.

**Comment by robin-near** [comment]
For posterity here, I've started work on a separate UI project at nearcore/tools/debug-ui, based on standard npm, typescript, and React. Linking some PRs here for migrating the existing pages.

#8174
#8337
#8341

There are a few important advantages to doing this:
 - Debug pages can be typechecked (typescript) and linted (eslint) like the rest of the codebase
 - Modularization is much easier: extracting css/js/ts out to separate files is trivial, extracting a UI element (such as [HashElement](https://github.com/near/nearcore/pull/8174/files#diff-f0403e1e93710ab7c2c0b794378375e2a07e43a0cc201917f2852f9cafbe8feaR22) for click-to-expand) is far more natural than with html + jQuery
 - Third-party libraries can be imported easily (since everybody uses npm)
 - The UI can pull data from multiple nodes (see cluster view from #8174 )
 - Running the UI does not require running a node (can point to any node via the URL), which also allows quick iterative development of the UI

I'll close this issue since this strategy exists now, and start a new issue to track the things we need to do to finish setting up the new project.
