### ISSUE TITLE
Add prometheus metric to display dynamic config

### ISSUE THREAD

**Issue by yanganto** [near/nearcore#7990]
The dynamic config is introduced in https://github.com/near/nearcore/pull/7872.
We need a Prometheus metric for the config, such that users can easier to check and confirm the changing in the dynamic config.

_Originally posted by @mm-near in https://github.com/near/nearcore/pull/7872#discussion_r1013855953_

**Comment by yanganto** [comment]
From my viewpoint, the log is enough, the user sends SIGHUP to reload the dynamic config, such that he already can access the log. 

The RPC is much easier to query the latest config and was requested in the previous PR. And it is not a requirement for the previous PR.

If there is no other concern from @mm-near, We can close this issue.

**Comment by mm-near** [comment]
My comment was the following:
> maybe in separate PR -- I'd add a prometheus metric to display the current value of expected shutdown.

so my goal wasn't to display the whole config - just this particular value.

**Comment by yanganto** [comment]
Hi @mm-near, 
Agreed, the original request is not all the dynamic config.  

By the way, do you think the idea to use an increase indicates a change in the dynamic config is good?  It is a good solution and easy to know the dynamic config is correctly apply.

**Comment by mm-near** [comment]
Yes - having something that indicates a successful change in the config is also good.
