### ISSUE TITLE
Move CSS into separate file

### ISSUE THREAD

**Issue by mm-near** [near/nearcore#7995]
Currently all our HTML debug pages have the CSS/style embedded inside HTML:
https://github.com/near/nearcore/blob/869a0110d1e10ee7588875778a01e37c5e85c6b5/chain/jsonrpc/res/sync.html#L4

We should instead move it to a 'common' css file, that it hosted separately:
https://github.com/near/nearcore/blob/869a0110d1e10ee7588875778a01e37c5e85c6b5/chain/jsonrpc/src/lib.rs#L1410

**Comment by mm-near** [comment]
#7958 has a longer term plan - here I was thinking about a small-scale fix for the existing code.

**Comment by Rajiv620019** [comment]
Hey is there anyone working on this issue? Can I fix it?
