### ISSUE TITLE
Meta issue for when RPCs are not tracking all the shards

### ISSUE THREAD

**Issue by mm-near** [near/nearcore#8011]
Currently, all the nodes are tracking all the shards. This bug collects a list of issues/problems that start occurring once this is no longer true.

This was verified on localnet, that is running with 4 nodes, 4 shards, each node tracking just one shard.

- [ ] Cross shard transactions are timing out for near-cli (``NEAR_ENV=local near send shard0 shard1 400``) is timing out, but the transaction is actually processed
- [ ] State viewer fails with ChunkMissing when looking at view-state (``target/debug/neard --home ~/.near/localnet/node0 view-state chain --start-index 915 --end-index 920``)

**Comment by pompon0** [comment]
Tracking a subset of shards (especially a dynamic subset) is not even implemented: https://cs.github.com/near/nearcore/blob/045498b8f34fb555b157993b9572535556a06889/nearcore/src/shard_tracker.rs?q=ShardTracker#L34 . So perhaps we should implement it first and only then look for induced issuess?
