### ISSUE TITLE
Track gas spending per parameter

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8033]
Currently we only track gas spending for gas profiles. The list is defined by `core/primitives-core/src/profile.rs::Cost` which is not in a one-to-one relation to gas parameters. But we want gas weights to be per gas parameter.

The specific task here is to make sure we at track gas spending per parameter. In this first step, we don't want to change the output of the gas profiles, we just want to make the reduction to `Cost` at a later stage in the code.

Follow-up work on this could be to also update gas profiles, but let's keep that as a separate discussion.
Further, this probably makes https://github.com/near/nearcore/issues/5719 more straight-forward, as we can always reconstruct the counters from profiles once gas profiles are detailed enough.

**Comment by jakmeier** [comment]
This is a bit tricky to do without making the code base even more horrible. I think it is worth doing major refactor and deleting a bunch of types. It will require multiple PRs. But here is an outline of where it should lead in the end.

## Current situation:
- Gas burning is done by looking up specific field in `RuntimeConfig`.
- Gas profiles are `Cost` -> `Gas` mappings, where `Cost` only exists for profiling.
- From a profile, it is impossible to reconstruct the per-parameter gas costs for actions.
- We also have a feature `"costs_counting"` that counts without multiplying by gas values. Only used for estimator, basically because we cannot easily go back to `Parameter` from `Cost`.
- The source of truth for `RuntimeConfig` is `ParameterTable` and the `Parameter` values inside. But we after the `ParameterTable` -> JSON -> `RuntimeConfig` conversion we lose the ability to index gas costs by `Parameter`.
- `RuntimeConfig` cannot be changed because it uses serde derived deserialization to JSON in `ProtocolConfigView` that is returned by the `"EXPERIMENTAL_protocol_config"` RPC call


## Goal
- Detach the RPC output from `RuntimeConfig` struct.
- Index both profiles and the runtime config by `Parameter` -> `Gas`, and delete `enum Cost` used in profiles today. Also delete `ExtCostsConfig` but probably still keep `ActionsCosts` to combine send/exec fee tripple parameters to a single variant.
- Change all places where gas is charged to be defined by `Parameter` only instead of idependently looking up `Cost` and a specific field in config.
- Bonus: Delete feature `"costs_counting"`

## Refactoring steps
1. Expand `ActionsCosts` to have a 1:1 mapping with action parameter tripples.
2. Replace `RuntimeConfig` in `ProtocolConfigView` with e.g. `json::Value` that is constructed manually rather than through serde.
5. Replace structured `ExtCostsConfig` with `Map<Parameter,Gas>` and replace `(ExtCostsConfig,Parameter)` -> `Gas` boilerplate code with simple map lookup.
4. Simplify `RuntimeConfig` to allow action fee lookup by `ActionCosts`, e.g.:
```rust
 struct RuntimeConfig {
    // used to be `RuntimeFeesConfig` with several levels of nesting down
    pub transaction_costs: Map<ActionCosts,Fee>,

    // unchanged
    pub storage_amount_per_byte: Balance,
    pub account_creation_config: AccountCreationConfig,
    pub wasm_config: VMConfig,

    // lifted up from `RuntimeFeesConfig`
    pub storage_usage_config: StorageUsageConfig,
    pub burnt_gas_reward: Rational,
    pub pessimistic_gas_price_inflation_ratio: Rational,
}
```
then use `ActionCosts` to lookup action fees and update profile.
```rust
/// before
let action_cost = ActionCosts::add_key;
let fee = transaction_costs.action_creation_config.add_key_cost.full_access_cost;
deduct_gas(fee.send_fee(sir), fee.exec_fee());
update_profile_action(action_cost, fee.send_fee(sir));

// after
let action_cost = ActionCosts::add_full_access_key;
let fee = transaction_costs[action_cost];
deduct_gas(fee.send_fee(sir), fee.exec_fee());
update_profile_action(action_cost, fee.send_fee(sir));
```
5. Change profile to track by `Parameter` instead of by `Cost`, without breaking backwards-compatibility with existing profiles on DB. (Serialize and deserialize the same as today.)
6. Optional: Introduce `ExecutionMetadata::V3(ProfileDataV3)` that keeps more detailed profiles than today.
7. Optional: Delete feature `"costs_counting"` and instead get counters by dividing profiles by parameter values.

**Comment by matklad** [comment]
Tangentially related, but today profile exists only in the `action_function_call` and doesn't account for costs we charge elsewhere. Making gas profile a runtime concept (rathre than a vm_runner concept) seems like a good idea.

**Comment by jakmeier** [comment]
That's a great point, thanks for pointing it out! I didn't even consider it but if we want parameter weights to work everywhere, this is actually required.
