### ISSUE TITLE
Validator keep downloading blocks but without progress

### ISSUE THREAD

**Issue by yanganto** [near/nearcore#8093]
The root cause of this bug is not really well defined based on my poor knowledge about neard.  We will use try to figure out commits by commits, if you have any ideas on this, please kindly provide it.  

**Describe the bug**
A validator node with `1.30-rc4` version `neard` stuck in a state downloading blocks and the block height will stop growing.
> "#12 Downloading blocks 0.00% (7 left; at 12) 3 peers ⬇ 361 B/s ⬆ 320 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 47.9 MB"

However, this does not happen in `1.29` versions.

**To Reproduce**
Setup a cluster with 3 nodes, and add a validator into the cluster,  all the nodes running `1.30-rc4`.  This will not happen with `1.29` with same configures.

**Expected behavior**
The node can keep downloading blocks

**Version (please complete the following information):**
- nearcore commit/branch `1.30-rc4`
- rust version (if local) `1.65.0`
- local

**Comment by akhi3030** [comment]
@nikurt: this seems like an issue for the node team to investigate.

**Comment by nikurt** [comment]
Q1:
> #12

Is the node syncing from the genesis block?

Q2:
> Setup a cluster with 3 nodes

Why is a cluster with 3 nodes important here? Can this be reproduced with a single node?

Q3: `testnet` or `mainnet`?

Q4: Would you mind sharing debug logs? Without them I can't tell why your node gets into state.
```
echo '{"verbose_module": ""}' > ~/.near/log_config.json
killall -SIGHUP neard
```

**Comment by yanganto** [comment]
A1: It is from genesis.
A2: it is not important, and we first start a cluster with 3 nodes
A3: `localtestnet`
A4: Here is the all the log for the cluster(3 node start first, then 1 validator), only the validator enable the `verbose_module`
[error_debug.txt](https://github.com/near/nearcore/files/10057363/error_debug.txt)

Here is something important from the debug log
```
2022-11-21T14:28:31.476113Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}: client: enter
2022-11-21T14:28:31.476231Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:process_accepted_blocks{num_blocks=0}: client: enter
2022-11-21T14:28:31.476242Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:process_accepted_blocks{num_blocks=0}: client: close time.busy=9.93µs time.idle=2.21µs
2022-11-21T14:28:31.476262Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:try_doomslug_timer: client: enter
2022-11-21T14:28:31.476373Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:try_doomslug_timer: client: close time.busy=110µs time.idle=1.80µs
2022-11-21T14:28:31.476398Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:handle_block_production: client: enter
2022-11-21T14:28:31.476429Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:handle_block_production: client: Cannot produce any block: not enough approvals beyond 12
2022-11-21T14:28:31.476453Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}:handle_block_production: client: close time.busy=54.7µs time.idle=1.76µs
2022-11-21T14:28:31.476480Z DEBUG handle{handler="NetworkClientMessages" msg="NetworkInfo"}: client: close time.busy=368µs time.idle=2.97µs
```

Could you help me to learn more about this?  Thanks in advanced. :pray:

**Comment by nikurt** [comment]
What is this peer that is offline?
```
2022-11-21T14:28:32.847926Z  INFO network: Error connecting to addr=127.0.0.1:10020 err=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
```

I see that you enabled the debug logs after the localnet already reached this stuck state. Hard to say for what reason it's stuck in that state.

Would you mind nuking the databases of your whole localnet cluster and trying again with the debug logs enabled from the beginning?

Fortunately nowadays we have the /debug pages for debugging such issues. Screenshots of them can provide more insight into why the localnet is stuck.

**Comment by yanganto** [comment]
When adding a validator key to the node, we need to change the config and restart the node, meanwhile, the node will be down for a little time.  Does this relate to not having enough approvals?  Could we add a validator key without restarting?  If not, we are happy to add this feature in near.  Many thanks.  :smile: 

Here is another log turn on the debug before adding the validator key to a node.  And we can see not having enough approvals only happen after the downtime.
[error_debug.txt](https://github.com/near/nearcore/files/10062442/error_debug.txt)

**Comment by Mic92** [comment]
We can also produce this issue in testnet reliable. It also does not matter if the node is a validator or not. We have noticed that it happens more likely with a release build than a debug build in localnet. In testnet we only used release builds so far.
Here is one log sample where a node was stuck in syncing for 5 minutes before having all the data (Before the node was just simply restarted and in sync). The CPU load during this was lower than usual. We have also seen 10 minutes or more but than the logs get a bit large. Here is the logs with `verbose_module` enabled: https://dl.thalheim.io/i4Lie5VY7i6gS72xTp_6dQ/sync-stuck.log.zst (the logs are compressed with zstandard)

**Comment by yanganto** [comment]
There is also a restart-related issue.
https://github.com/near/nearcore/issues/4930

**Comment by yanganto** [comment]
This issue can workaround by adding `tracked_shards": [0]` in the config.

This issue happens after [#7412](https://github.com/near/nearcore/pull/7412/files).

And the default behavior of tracking shards will become false.

BTW, the `tracked_shards` will be changed to `track_all_shards`.

@nikurt many thanks for your time and help on this. :smile:

**Comment by Mic92** [comment]
Yeah, after seeing what the solution was for this problem, I think the delays I see in testnet is something else.
