### ISSUE TITLE
Nearcore logging still showing 100 validators 

### ISSUE THREAD

**Issue by AngelBlock** [near/nearcore#8156]
**Describe the bug**

2022-12-04T10:42:53.902919Z  INFO stats: #79888677 8Mh3vhisr9vAzHzSWGYNN4VLnhRkF6PMvsybXaSH8Ynd **100 validators** 30 peers ⬇ 684 kB/s ⬆ 613 kB/s 0.90 bps 25.0 Tgas/s CPU: 45%, Mem: 12.4 GB

**To Reproduce**
`journalctl -u neard -fn100 -o cat | grep stats`

**Expected behavior**
actual number of validators, 132 for example

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch: * 1.29.2 72d4a4d3a [origin/1.29.2]
- mainnet/testnet/betanet/local: **mainnet**

**Comment by akhi3030** [comment]
Seems like a node issue.  CC: @nikurt

**Comment by nikurt** [comment]
Thanks for the report. Reproduced the issue. Needs fixing.
