### ISSUE TITLE
Merge `Testbed` and `RuntimeTestbed` in estimator

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8201]
We have

```rust
// runtime/runtime-params-estimator/src/estimator_context.rs
pub(crate) struct Testbed<'c> {
    pub(crate) config: &'c Config,
    inner: RuntimeTestbed,
    transaction_builder: TransactionBuilder,
}
```

Here the indirection of an inner `RuntimeTestbed` only makes some code more verbose without any clear benefit. Let's clean this up. Suggestion: Merge all fields from inside `RuntimeTestbed` to the outer struct and remove `RuntimeTestbed`.

**Comment by akashin** [comment]
This is addressed with https://github.com/near/nearcore/pull/8242.

**Comment by akhi3030** [comment]
@akashin: in case you were not familiar with [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), you can use keywords to link issues and PRs and then github will automatically close issues saving some clicks.
