### ISSUE TITLE
Consider replacing `near_rust_alloctor_proxy` with `bytehound`

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#8227]
We have a configuration (`assertions-release`) of neard that can measure some memory usage statistics at runtime and report peaks as they occur.

This relies on the https://github.com/near/near-memory-tracker crate to override the allocator, however this has been found to cause some issues that are inherent to the approach.

Rather than rolling our own, we could utilize tools like [`bytehoud`](https://github.com/koute/bytehound) for much deeper insights while at the same time getting an implementation that has some significant attention put into it. While the primary mode of use for this crate is via `LD_PRELOAD`, there's nothing that would prevent us from straight up dynamically linking to the instrumentation crate either in the `assertions-release` configuration.

**Comment by akhi3030** [comment]
Should we track this as a tech debt issue and put it on https://github.com/near/nearcore/issues/8203 assuming that someone from contract runtime would work on it.

**Comment by nagisa** [comment]
Not sure if this is something contract runtime will have bandwidth for near-to-mid term.

**Comment by nagisa** [comment]
We aren't using this anymore. There is a remaining reference to this in the comments of utils/near-performance-metrics/src/stats_enabled.rs but otherwise I believe this is fixed.
