### ISSUE TITLE
Storage prefetch tests are flaky

### ISSUE THREAD

**Issue by pugachAG** [near/nearcore#8252]
For more context see the [discussion in zulip](https://near.zulipchat.com/#narrow/stream/295302-general/topic/test_basic_prefetch_account.20fails)

Recent changes that might affect this test:
* https://github.com/near/nearcore/pull/8205
* https://github.com/near/nearcore/pull/8207

Some failures instances
* [test_basic_prefetch_account](https://buildkite.com/nearprotocol/nearcore/builds/23421#01852fc5-d3b6-4b70-9de0-5ee6e082b419)
* [test_prefetch_multiple_accounts](https://buildkite.com/nearprotocol/nearcore/builds/23406#01852ed1-f2ab-40ca-8e59-b811c1429793)
* [another test_basic_prefetch_account](https://buildkite.com/nearprotocol/nearcore/builds/23424#01852fe4-e82a-4071-b496-a1384731e592)

**Comment by jakmeier** [comment]
This failed again, we need to investigate further...
https://buildkite.com/nearprotocol/nearcore/builds/23557#018573b7-8acf-4b34-b7e5-79da4c8c6f55/97-1488

```
thread 'prefetch::tests::test_prefetch_multiple_accounts' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `10`: unexpected number of prefetched values', runtime/runtime/src/prefetch.rs:287:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:181:5
   4: node_runtime::prefetch::tests::check_prefetch_account
             at ./src/prefetch.rs:352:9
   5: node_runtime::prefetch::tests::test_prefetch_multiple_accounts
             at ./src/prefetch.rs:287:9
   6: node_runtime::prefetch::tests::test_prefetch_multiple_accounts::{{closure}}
             at ./src/prefetch.rs:239:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by pugachAG** [comment]
@jakmeier it seems like your PR is based on the outdated master branch which doesn't include the fix:
https://github.com/jakmeier/nearcore/compare/doc-meta-txgas...near:nearcore:master
or am I missing something?

**Comment by jakmeier** [comment]
Oh haha I am stupid, you are right. Good catch @pugachAG , in that case we can close it again. :)
