### ISSUE TITLE
Update condition for a full chunk to respect parameter weights

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8265]
Update the calculation for when a chunk is full in terms of gas.

This has to be backwards-compatible. That is, old protocol versions must not change their behavior. A protocol feature flag will have to be introduced, if it has not bee n added before.

To enable this, we also need to track weight-adjusted gas. We might want to name it something more distinct, to avoid confusion between already existing terms of gas, such as "used gas", "burned gas", "prepaid gas", "attached gas". Fumes as a new terms has come up in discussions. Maybe we can find something better.

**Comment by akashin** [comment]
This is addressed with https://github.com/near/nearcore/pull/8805.
