### ISSUE TITLE
[network] Race condition when creating account data

### ISSUE THREAD

**Issue by mm-near** [near/nearcore#8315]
If we're a validator running with node_key1 and then we restart and run with node_key2, the account data might be still showing the invalid key (node_key1) for 15 minutes (advertise_proxies_interval).
This means that our node will not receive any approvals (or routed messages in general) and would not be able to produce blocks.

Seems that the function below, might be called before we fetch the account information from the peers, which results in us setting the version '1' to my_data object (and therefore this object will be ignored by our peers - as they probably have an accountData with a higher version). 

Only when this method runs again - after 15 minutes (advertise_proxies_interval) - this function will fetch the correct version and publish it. 

https://github.com/near/nearcore/blob/4820b04aec53337bd3ed6fc00b274fa804ae6f5f/chain/network/src/peer_manager/network_state/tier1.rs#L152

**Comment by pompon0** [comment]
This WAI, as we don't know the state of the whole network locally. What kind of guarantee would you like to have here?

**Comment by mm-near** [comment]
The current code is breaking the test in tests/sanity/switch_node_key.py (and blocking the 1.31).

I guess my goal, is to make sure that you can smoothly move the validator key to a new machine (for example moving to a backup machine due to the main datacenter outage).

With the current code in master, you'll be missing blocks for 15 minutes in such scenario.

I see 3 possible solutions:

a) use a timestamp as a version
b) when you get the network message, and you see your validators annoucement with a different peer_node -- immediately send over the correct one with a higher version
c) change the interval advertise_proxies_interval to run more often (every 10 seconds?) during the first couple minutes after startup.
