### ISSUE TITLE
[RPC] EXPERIMENTAL_tx_status doesn't include all the receipts

### ISSUE THREAD

**Issue by luixo** [near/nearcore#8321]
**Describe the bug**
On request of `EXPERIMENTAL_tx_status` with params `["9fE3x4pyXatK2kiysLiMoS3ncTSq3nHi3vc4eWpagNj1", "any"]` I get the response with transaction `9fE3x4pyXatK2kiysLiMoS3ncTSq3nHi3vc4eWpagNj1` that produced receipt `J8Zr8V4hMaRQWjEpn7xhzbZZNGXHq4ZpFzLvmzdgctEA` which itself produced `9pP2bVrQLV7ommF2RrnbTxEoMsoTQi1sybEBejCaDTkN`, `HUNdtSp31bioen1r8T8exGiGE5VfuN3Yd2q428pXzqsr` and `2tYbNiCQhPoGdcvMJR2TfwxscnCxcxQ1eNWmuXLe3UX7`.
The first two of them are in the `result.receipts` array (as well as in `result.receipts_outcome` array), but the latter is not.

Is that intended to be like that? If so, where the data on receipt `2tYbNiCQhPoGdcvMJR2TfwxscnCxcxQ1eNWmuXLe3UX7` can be found?

**To Reproduce**
```
curl --location --request POST 'https://archival-rpc.testnet.near.org' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": "dontcare",
  "method": "EXPERIMENTAL_tx_status",
  "params": ["9fE3x4pyXatK2kiysLiMoS3ncTSq3nHi3vc4eWpagNj1", "any"]
}'
```

**Expected behavior**
All the receipts in tree-like structure starting from the transaction should have descriptions in `result.receipts` array as well as in `result.receipts_outcome` array.

**Comment by frol** [comment]
This is definitely not an expected behavior for an archival node.

@bowenwang1996 Given that this RPC method purely relies on what the near-client returns, can you help to find a person who can take a closer look into this issue?

**Comment by jakmeier** [comment]
Hm, if the missing receipts are always refunds, then I think that might be due to PR #7928 which has been done to satisfy issue #6834. That issue basically asked to not include refunds in the tx status query.

**Comment by khorolets** [comment]
> Hm, if the missing receipts are always refunds, then I think that might be due to PR #7928 which has been done to satisfy issue #6834. That issue basically asked to not include refunds in the tx status query.

You seem to be right. In this case, it is really unfortunate, as it breaks the Explorer. It'd be great to receive a comment on whether it might be reverted or whether Explorer should handle it differently.

**Comment by jakmeier** [comment]
I can't comment on that, I have no idea where the requirement came from.

cc @bowenwang1996 @firatNEAR @anthony-near

**Comment by firatNEAR** [comment]
That is indeed unfortunate, I would suggest to revert the change if it breaks Explorer behaviour and provide a different EXPERIMENTAL endpoint for transaction status querying that doesn't involve the refund receipt. 
cc @bowenwang1996 what do you think?

**Comment by akhi3030** [comment]
May I also add a requirement that we have some sort of automated test in the nearcore CI to make sure that we do not accidentally break the explorer in the future again.

**Comment by frol** [comment]
> When querying for a transaction, users don't really care whether the gas refund generated by the system finishes and rather cares more about the transaction and the receipt it generates.

Well, it is a valid UX concern. The problem is that it became a breaking change for the downstream projects. @anthony-near Please, consider adding an RPC endpoint parameter to the affected endpoints to control this behavior.

**Comment by firatNEAR** [comment]
Is this something that is urgent and currently blocking explorer? Could it wait until next week to be fixed?

**Comment by luixo** [comment]
> Is this something that is urgent and currently blocking explorer? Could it wait until next week to be fixed?

It's not urgent, we currently have a placeholder for missing receipts.

**Comment by firatNEAR** [comment]
Alright, @anthony-near please take a look at it next week when you are back.

**Comment by anthony-near** [comment]
I'm going to fix this by reverting https://github.com/near/nearcore/pull/7928 for now. I'll add an RPC endpoint parameter to the affected endpoints in a follow up PR.

**Comment by anthony-near** [comment]
Created PRs to revert both the original PR that caused the issue https://github.com/near/nearcore/pull/8388 and the related PR that updated related tests https://github.com/near/nearcore/pull/8389.

**Comment by jakmeier** [comment]
@anthony-near is this also getting deployed to a testnet rc? Just checking because I saw some chat in the node team about a testnet rc being tested right now.

**Comment by anthony-near** [comment]
I'm not sure but for the upcoming 1.31.0 release it should definitely include the change to revert the tx status not waiting for refunds.

**Comment by jakmeier** [comment]
Okay, I asked the node team to include it, they might come back to you with questions. @anthony-near

**Comment by jakmeier** [comment]
@luixo is this resolved?

**Comment by jakmeier** [comment]
I assume this is now resolved, please reopen if I am wrong.
