### ISSUE TITLE
Quick flat state removal for non-tracked shard

### ISSUE THREAD

**Issue by pugachAG** [near/nearcore#8332]
The original idea was to use `delete_range` introduced in #8200 when [cleaning flat state](https://github.com/near/nearcore/blob/master/core/store/src/flat_state.rs#L973). That doesn't work due to sub-accounts for fixed shards.

With #8670 we can just remove all keys with a given `shard_uid` prefix.

**Comment by pugachAG** [comment]
@Longarithm let's consider the following layout with 3 shards:
```
ShardLayoutV1{
  fixed_shards: ["alice.near"],
  boundary_accounts: ["bob.near"],
  ..
}
```
What would the range we can use when cleaning shard with index 1 (with all keys before `bob.near`) without removing any subaccounts of `alice.near` (because those belong to shard with index 0)?

**Comment by Longarithm** [comment]
Hm I didn't realize that there is a plan to put subaccounts of a fixed account to the same shard. This is confusing because resharding of such shards will be computation-heavy. Asked in Zulip https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/fixed.20shards/near/320919706

**Comment by Longarithm** [comment]
Discussed offline: it is fine to ignore subaccounts feature because fixing single account is enough. Though we don't want to drop fixed accounts completely because in theory they could allow us to quickly move some large account to a separate shard.
We should mention this in comments to avoid future confusions.

**Comment by pugachAG** [comment]
Update: we've decided not to implement it for now.

This requires removing subaccounts support for accounts in `fixed_shards` which is a pretty significant change. Also this would be the first place in our codebase where we start relying on trie keys belonging to a single shard forming ranges, which introduces more assumptions to the systems and makes it prone to breaking in case of future changes. Considering that we don't find the underlying use case to be significant enough, so we are not proceeding with this for now.

**Comment by pugachAG** [comment]
FlatState is prefixed with `shard_uid` now, so this can easily be implemented with rocksdb range delete
