### ISSUE TITLE
[tools/debug-ui] Migrate Chain and Chunks Info page

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#8350]
Currently, we have an old Debug UI, and a new Debug UI:
 - The old one is in `chain/jsonrpc/res/*.html` ; these are static files served from nearcore with the Actix Web framework (search for display_debug_html), on the rpc port :3030 of a running nearcore node. For example, see http://35.204.17.24:3030/debug .
 - The new one is in tools/debug-ui ; this is a React + TypeScript project managed by npm. At the moment, it needs to be separately served and will perform the same debug RPC calls as the old pages to render the content. See tools/debug-ui/README.md for simple instructions on how to bring it up and point it to a node to see its debug info.

We're in the process of migrating from the old debug UI to the new debug UI. The first three pages have already been migrated. This task is about migrating the Chain and Chunks Info page. The following is a suggested approach:
 - Gain a basic understanding of how the debug RPC works for this page: (1) look at chain_n_chunk_info.html for when it makes the `$.ajax` calls; (2) look at the server side - search for `chain_processing_status` (the ajax call specific to this page) and trace where the handling logic goes.
 - Familiarize yourself with how to develop on the new debug UI (from tools/debug-ui/README.md).
 - Familiarize yourself with basic React development
 - Attempt the migration. Look at https://github.com/near/nearcore/pull/8586/files as well as existing code for example. Feel free to tweak the page as you see fit.

**Comment by soonnear** [comment]
Pull request 
- https://github.com/near/nearcore/pull/8903

**Comment by soonnear** [comment]
Merged
