### ISSUE TITLE
Unable to determine if a TX is Contract tx

### ISSUE THREAD

**Issue by panbhatt** [near/nearcore#8373]
**Unable to determine if a tx belong a specific contract as Contract ADDR is missing**

**To Reproduce**
1. Take any token E.g. (TETHER USD) present on the mainnet. 
2. Determine any block that has a transaction related to that TOKEN in it. 
3. Call the JSON RPC to get the list of all the CHUNKS & then the transactions. 
 Example -> 1 
Block -> 83086807
CHUNK Hash -> Fmb3s5iWWhSsUT5jfxFTDDDZf8GnC393maFVvn9kzka4
TXhash -> 5HtHfsCawhwWepGjo87rtHoj6dKRADBqPhWTyKqZAVdY

Tx Explorer link: [https://nearblocks.io/txns/5HtHfsCawhwWepGjo87rtHoj6dKRADBqPhWTyKqZAVdY ](https://nearblocks.io/txns/5HtHfsCawhwWepGjo87rtHoj6dKRADBqPhWTyKqZAVdY)  

**Expected behavior**
There should be a way in the "ft_transfer_call" details in the actions to determine, if this TX belongs to a CONTRACT (Tether USD) in this case. 

![image](https://user-images.githubusercontent.com/1473470/212798867-105d60f6-e56e-4bf5-a7cc-0392c5f619d4.png)
**Decrypted Args attribute value is :** 
 {"force":0,"actions":[{"pool_id":239,"token_in":"token.pembrock.near","token_out":"token.jumbo_exchange.near","min_amount_out":"0","amount_in":"67975059989093080360"},{"pool_id":228,"token_in":"token.jumbo_exchange.near","token_out":"d9c2d319cd7e6177336b0a9c93c21cb48d84fb54.factory.bridge.near","min_amount_out":"0"},{"pool_id":289,"token_in":"d9c2d319cd7e6177336b0a9c93c21cb48d84fb54.factory.bridge.near","token_out":"**dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near**","min_amount_out":"2831670"}]} 

**Example 2 ->** 
BLOCK -> 83087563
CHUNK Hash -> E681YweVSCympAPaR41F4qnHcZeMqBEn8tS334BpLmjm
TX Hash ->  7DLCs2kLCmHDycxjLUg4WGBxsjYnfHej23jdBWV3hdgV
Tx Explorer link -> [https://nearblocks.io/txns/7DLCs2kLCmHDycxjLUg4WGBxsjYnfHej23jdBWV3hdgV](https://nearblocks.io/txns/7DLCs2kLCmHDycxjLUg4WGBxsjYnfHej23jdBWV3hdgV)

![image](https://user-images.githubusercontent.com/1473470/212799707-c08871c7-aa9b-4bfd-8803-f38b6ed69f8b.png)

Decrypted Args value is: 
 {"receiver_id":"farming-v1.jumbo_exchange.near","amount":"100000000","msg":"v1.jumbo_exchange.near@184#2"}  

This does not give any co-relation to the CONTRACT. 

**Example 3 ->** 
Block -> 83087287 
CHUNK Hash -> FSt2wUSVD7dJ87dJ6yNVnayKNiX7jC41BrsDDfexMVu6 
Tx Hash -> 4DhrRLdfQMHVC6LjXYSVkT4nojoAwTRoZ6qVAfuPbEp6 

TX Explorer link -> [https://nearblocks.io/txns/4DhrRLdfQMHVC6LjXYSVkT4nojoAwTRoZ6qVAfuPbEp6](https://nearblocks.io/txns/4DhrRLdfQMHVC6LjXYSVkT4nojoAwTRoZ6qVAfuPbEp6)

![image](https://user-images.githubusercontent.com/1473470/212799725-fdef156d-2323-4e59-bc56-732c17aa7583.png)

Decrypted Args Value is : 
 {"receiver_id":"v2.ref-finance.near","amount":"418799441600744532340623545","msg":"{\"force\":0,\"actions\":[{\"pool_id\":4,\"token_in\":\"wrap.near\",\"token_out\":\"dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near\",\"amount_in\":\"418799441600744532340623545\",\"min_amount_out\":\"900000000\"}]}"}

The Near docs API does not reflect, how to determine if a Tx belongs to a CONTRACT or not. Can anyone help me to understand what wrong I am doing here. There is something called "executor_id" in the Tx API response, but the problem is how to find the co-relation between the tx & that specific executor_id, as there are multiple executor_id in the response. 

Please, if someone can help, as it is baffling mystery for me.

**Comment by flmel** [comment]
What do you mean with "... if this TX belongs to a CONTRACT (Tether USD) in this case." ?
You are given an action `functioncall` and the receiver is the account(contract) of that action

**Comment by telezhnaya** [comment]
Closing this since there are no other clarifying questions
