### ISSUE TITLE
Dependency error when trying to download genesis file for indexer 

### ISSUE THREAD

**Issue by gamenautdips** [near/nearcore#8479]
While executing cargo run --release -- --home-dir ~/.near/testnet init --chain-id testnet --download-config --download-genesis

Getting the following error 

  Compiling near-rosetta-rpc v0.0.0 (https://github.com/near/nearcore?rev=9a3edd1fd2b8ee6968be69b30593dd134c2da7fa#9a3edd1f)
error[E0560]: struct `ResponseWrapper<_, _>` has no field named `responder`
   --> /home/dips/.cargo/git/checkouts/nearcore-5bf7818cf2261fd0/9a3edd1/chain/rosetta-rpc/src/lib.rs:76:1
    |
76  | #[api_v2_operation]
    | ^^^^^^^^^^^^^^^^^^^ field does not exist
    |
   ::: /home/dips/.cargo/registry/src/github.com-1ecc6299db9ec823/paperclip-core-0.5.2/src/v2/actix.rs:638:12
    |
638 | pub struct ResponseWrapper<T, H>(#[pin] pub T, pub H);
    |            --------------- `ResponseWrapper<_, _>` defined here
    |
    = note: this error originates in the attribute macro `api_v2_operation` (in Nightly builds, run with -Z macro-backtrace for more info)
help: `ResponseWrapper<_, _>` is a tuple struct, use the appropriate syntax
    |
76  | ResponseWrapper<_, _>(/* fields */)

**Comment by akhi3030** [comment]
Thanks for raising the issue @gamenautdips!  

@pompon0: you seem to have touched this file most recently.  Could you take a look please?

**Comment by evgenykuzyakov** [comment]
Have the same issue with the indexer for `1.31.0` dependency.

**Comment by evgenykuzyakov** [comment]
Looks  like I'm able to solve the issue for my indexer by locking versions for some nearcore dependencies:
```toml
paperclip = { version = "=0.7.0", features = ["actix4"] }
paperclip-actix = "=0.5.0"
paperclip-macros = "=0.6.0"
```

Here is the commit: https://github.com/evgenykuzyakov/indexer-tutorials/commit/1656ac86a029456d409d6ced6f03286e15a760d0

**Comment by akhi3030** [comment]
@pompon0: is there any update on this issue please?  Do you have time investigate this or should someone else take a look?

CC: @walnut-the-cat.  Maybe you can also help drive this.

**Comment by pompon0** [comment]
Hi @gamenautdips , at 9a3edd1fd2b8ee6968be69b30593dd134c2da7fa paperclip-core is locked to 0.5.1 (see Cargo.lock), while your error message indicates that paperclip-core 0.5.2 is compiled. Can you retry compiling with a fresh clone of the nearcore repository?

**Comment by pompon0** [comment]
Hi @evgenykuzyakov please provide
* the commit at which you experience the compilation error
* your compilation command
* your compilation error

**Comment by telezhnaya** [comment]
Hey!
Please update to the latest version and feel free to re-open if it's still an issue for you
