### ISSUE TITLE
Blocks with 100 fungible token transfer transactions should take no longer than 1.3s on average

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#8486]
This is a tracking issue for the work associated with the NI-KR-1381 key result for the core and/or contract runtime teams.

We want to be absolutely sure we can support constant load of 100 fungible token transfers per second per shard, and under such a load blocks should take no longer than 1.3 seconds to execute on average.

# Tasks

* [x] #8487
* [ ] In case the benchmark from above produces non-satisfactory results, use the benchmark to profile the codebase for bottlenecks and attempt to achieve the target 1.3 seconds.

**Comment by akashin** [comment]
I did a quick measurement using Locust FT workload - processing 100 FT transfers per second takes around 150 TGas and 30ms per chunk. So I think we can close this.
