### ISSUE TITLE
Alternative flat state implementation idea

### ISSUE THREAD

**Issue by pugachAG** [near/nearcore#8506]
### Core idea

Instead of storing state updates (deltas) per-block let's group all value changes under single key.

For each key we store all values for not-yet-fanalised blocks as a list of `(BlockHash, ValueRef)` pairs. The whole list is stored as a single value in rocksdb. When the value is updated we simply append the corresponding tuple to the list. To read a value at a certain block we traverse the list to find the latest block which is relevant for the current fork. All values before the latest final block can be GCed. GC can be performed periodically and on write.

### Pros

* Doesn't require storing deltas in RAM.
* Finding corresponding `ValueRef` requires on average single disk read: the size of single tuple in the list is `32 + 32 = 64B`, so with `4KB` SSD page size we can fetch `~60` list values in one disk read. 

### Cons

* The value list can grow large in case of long forks resulting in performance degradation for reads.
* GC process is pretty involved and becomes critical for read performance.
* Limits value inlining.
* Storing big values in rocksdb can reduce cache hit rate.

**Comment by jakmeier** [comment]
I really like the performance implications. Decreasing the IOPS for deltas by a factor of ~60 in the worst case might just be what we need to make flat storage passable even under slow finality conditions.

> To read a value at a certain block we traverse the list to find the latest block which is relevant for the current fork. All values before the latest final block can be GCed.

How does that interact with forks? Let's say `100` is the current value and gets overwritten by `101`. This happens in 3 forks all trying to build on the same block hash `hash0`. I think the list after that would look like:
[
  (`hash0`,`hash(100)`),
  (`hash1`,`hash(101)`),
  (`hash2`,`hash(101)`),
  (`hash3`,`hash(101)`)
]

Now let's say the chain including `hash1` wins. GC will remove `hash0` because it's before `hash1` in the list. But will it also remove `hash2` and `hash3`?

**Comment by mm-near** [comment]
That's why it might be a better idea to store both hash & height in there (this makes GC code a lot simpler).

**Comment by mm-near** [comment]
The other thing to consider, is whether we should do read-modify-writes, or write a custom rocksDB merge operator & compaction filter.

This way, we could store tuples like:
(`height`, `hash`, `value`, `gc_height`)

where gc_height means - remove all the data that is older than this.
So then the custom merge operator could handle the compaction internally.
(but this might be a premature optimization ;-)

**Comment by walnut-the-cat** [comment]
> For each key we store all potentially relevant values as a list of (BlockHash, ValueRef) pairs.

Can we elaborate more on what 'potentially relevant values' really indicates?

**Comment by pugachAG** [comment]
@jakmeier 
> How does that interact with forks? 

My idea is that GC should also remove `hash2` and `hash3` since those belong to the "dead" forks. So GC should be more involved than dropping everything with height lower than the latest final block. This is what I meant by "GC process is pretty involved" in cons list :)

**Comment by pugachAG** [comment]
@walnut-the-cat 

> Can we elaborate more on what 'potentially relevant values' really indicates?

updated the description

**Comment by pugachAG** [comment]
After thinking about this for some time I no longer consider this to be a viable option.
The same result can be achieved in the current design by storing FlatStateDelta entries under `(key_hash, block_height, block_hash)` key. Then updates for the same key will end up in the same rocksdb block resulting in data locality. So we can just use backward iterator to find the latest entry in the fork.
