### ISSUE TITLE
Implement the TestLoop unit test framework

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#8513]
- [x] #8519 
- [x] #8516 
- [x] #8517 
- [x] #8518 
- [x] #8520 
- [x] #8521 
- [x] #8522 
- [x] #8523

**Comment by walnut-the-cat** [comment]
#8516 completed on 02/14
#8517 completed on 02/17
#8518 completed on 02/14

**Comment by walnut-the-cat** [comment]
looks like everything is done? should we close?

**Comment by robin-near** [comment]
Yeah I'll close this.
