### ISSUE TITLE
Is it time to update the Hardware Requirements for Validator Node?

### ISSUE THREAD

**Issue by zavodil** [near/nearcore#8543]
Could you check if [Hardware Requirements for Validator Node](https://near-nodes.io/validator/hardware) are valid?
Since the release of version 1.31, I've seen several reports that mainnet nodes are getting stuck on migration.
Has anyone tested nearcore 1.31 on validator node with [Recommended Hardware Specifications](https://near-nodes.io/validator/hardware#recommended-hardware-specifications)?

**Comment by akhi3030** [comment]
@nikurt, @gmilescu: sounds like this is a node related issue.

**Comment by gmilescu** [comment]
Yes, this will be handled by the Node team. We aim to make the hw requirements check automatic, by verifying each future release against nodes with different hw configurations.

**Comment by telezhnaya** [comment]
The doc is updated
https://near-nodes.io/rpc/hardware-rpc
https://near-nodes.io/validator/hardware-validator
https://near-nodes.io/archival/hardware-archival
