### ISSUE TITLE
Fix stdx dependency in public crates

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8604]
https://github.com/near/nearcore/pull/8087 introduced the stdx crate for some shared code that should be in std but isn't (yet).

This has the problem that we can no longer publish our public crate with our usual CI job. It complains with this message.

```
error: all dependencies must have a version specified when publishing.
dependency `near-stdx` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
error: unable to publish package near-crypto
```

For now, the CI job already published the stdx crate, so now I can depend on this specific version from the other crates. But it's super messy and breaks the automated process. We need to fix this.

I tagged the node team because nearcore release management seems closest to your team, and the change came from your team. Feel free to reassign if you think that's not your responsibility.

**Comment by akhi3030** [comment]
CC: @gmilescu, @nikurt

**Comment by akhi3030** [comment]
If I understand the problem correctly, sounds like we need to document the steps required for introducing new crates.

**Comment by jakmeier** [comment]
According to this comment: https://github.com/near/nearcore/pull/8605#issuecomment-1437362930

It could also be fixed in our fork of caro-workspaces. (Although, I am not sure why we need that fork in the first place.)
