### ISSUE TITLE
neard command to manually drop certain data should be added

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#8650]
We should have a command that would allow users to drop pieces of data from the database, which the node is then able to later recover in some way or form during operation. In the case this data gets corrupted for whatever reason these can be quite helpful to restore operation.

A particular example where dropping data would have helped is the contract artifact cache & [this issue](https://github.com/near/nearcore/issues/8293#issuecomment-1446655744).

**Comment by Longarithm** [comment]
Is this task a blocker for anything? If not, I think it is a nice simple onboarding task - it's just a command for `CachedContractCode` removal. Can be extended to removing other cols which don't ruin DB completely.

**Comment by nagisa** [comment]
This is not blocking anybody, no. +1 on making this an onboarding task.

----------------------------------------

7 Mar 2023 15:22:40 Aleksandr Logunov ***@***.***>:

**Comment by shreyan-gupta** [comment]
I had an offline discussion with @nagisa and it was discussed that we can have a generic command to clear recoverable DB columns which we can keep expanding the scope of this command over time. Does this approach sounds good? I was thinking the following details. Please feel free to suggest an alternative
- This would be a sub command under `view-state`, probably opened with read write DB permissions. Let me know if this sounds fine.
- We can call the command/subcommand `clear_cache` or `clean_cache`. Suggest alternatives pls!
- To start with, the command would delete all data under column `DBCol::CachedContractCode`. Let me know if there's anything else which is suitable to clear off here.

@Longarithm, thoughts?
