### ISSUE TITLE
Prepend ShardUId to FlatState key

### ISSUE THREAD

**Issue by pugachAG** [near/nearcore#8670]
We've decided to prepend `ShardUId` to `FlatState` column key.
This has 2 major benefits: fast FlatState deletion when node stops tracking the shard and quick retrieval for a range of shard keys (needed for state sync). 

One downside is that it makes resharding slower. We've decided to deal with it is the future along with `State` column which already has shard id as a prefix.

See [zulip discussion](https://near.zulipchat.com/#narrow/stream/345766-pagoda.2Fstorage.2Fflat-storage/topic/shard.20id.20in.20prefix/near/327093459) for more context.

**Comment by Longarithm** [comment]
Would be also nice to prepend `ShardUId` to `FlatStateDeltas` key, but it is less crucial and could be done separately, even outside MVP. Maybe this part could be an onboarding task then...

**Comment by Longarithm** [comment]
Completed in https://github.com/near/nearcore/pull/8685
