### ISSUE TITLE
Unable to create an archive node with archive flag using docs. 

### ISSUE THREAD

**Issue by suggalla** [near/nearcore#8686]
I'm trying to stand-up an archive node by setting `"archive": true` in the `config.json` as documented here: https://near-nodes.io/archival/run-archival-node-without-nearup#4-replacing-the-configjson-1. After deleting the data directory and enabling this flag our node is still not in archive mode. 

Relevant configs:
```
  "tracked_accounts": [],
  "tracked_shards": [
    0
  ],
  "gc_blocks_limit": 2,
  "view_client_throttle_period": {
    "secs": 3000,
    "nanos": 0
  },
  "view_client_threads": 4,
  "archive": true
 ```

**Comment by akhi3030** [comment]
Looks like something for the node team to investigate.  CC: @nikurt, @wacban

**Comment by nikurt** [comment]
@suggalla Please elaborate how exactly you check that the node is in the archive mode and what result you get.

**Comment by suggalla** [comment]
> @suggalla Please elaborate how exactly you check that the node is in the archive mode and what result you get.

I'm seeing it's only using 492 GB of storage and I'm querying an older block (86263308) which isn't available.

**Comment by suggalla** [comment]
> > deleting the data directory
> 
> > 492 GB of storage
> 
> Where do you get the data directory from after you delete your data directory?

Basically I turned off the node and deleted the data directory then restarted the node with the archive flag to start it from a fresh state 16 hours ago.

**Comment by nikurt** [comment]
> > > deleting the data directory
> > 
> > 
> > > 492 GB of storage
> > 
> > 
> > Where do you get the data directory from after you delete your data directory?
> 
> Basically I turned off the node and deleted the data directory then restarted the node with the archive flag to start it from a fresh state 16 hours ago.

Then it wasn't an operational node yet.
When a node starts without the data directory, it first downloads and validates headers of all blocks, which can take multiple hours. Then it downloads and processes every block in history. This will take weeks to complete.

Please delete the `data/` directory and get the backup as described in Step 5: https://near-nodes.io/archival/run-archival-node-without-nearup#5-get-data-backup-1

Then start a node and it should become in-sync with the head of the chain, it will contain information about all blocks that ever existed.

**Comment by nikurt** [comment]
@suggalla did that help? Were you able to run an archival node?
Please re-open if there is anything else I can help with.
