### ISSUE TITLE
Investigation: Automated gas usage estimation

### ISSUE THREAD

**Issue by akashin** [near/nearcore#8881]
This is a tracking issue to investigate whether we can build an accurate and performant gas usage estimator for transactions.

If we had accurate gas estimates for transactions, we can give a much tighter bound on the latency of processing transactions. We should try simple ways to estimate gas usage of transactions before they are accepted to the queue and see how accurate those estimates are.

Logically, there are two types of estimation:
 1. Run estimation **before** the transaction is accepted in the queue.
This can either be done by the client submitting the transaction or by the chunk producer that includes the transaction into the block.
 2. Run estimation as a part of the protocol when putting receipts into the delayed receipts queue. In this case the estimation should be faster than actually running the receipt - either executed in background on some older state or done without actual execution using tools like finite-wasm.

Concretely after this investigation, we should understand:
- [ ] Can we get <X% (e.g. 50%) relative error rate for at least Y% (e.g. 80%) of the transactions (weighted by gas)?
- [ ] Can the gas estimation be used on the client that submits the transaction? On the chunk producer? As a part of the protocol that all nodes run?

There is a prior work in this space that we can try to reuse:
- https://github.com/idea404/gas-buddy
- Gas estimator built by @robin-near

**Comment by bowenwang1996** [comment]
@akashin I believe this is already supported in https://github.com/near/workspaces-rs. cc @DavidM-D

**Comment by robin-near** [comment]
https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/congestion.20brief/near/359079715
