### ISSUE TITLE
Implement test for local congestion control

### ISSUE THREAD

**Issue by akashin** [near/nearcore#8920]
We should have a test that generates an interesting workload with non-trivial congestion metrics. This test will quickly evaluate the various designs that attempt to solve the congestion problem.

The concrete test for the local congestion control milestone would evaluate liveness when the system receives 1000 transactions per second (eventually every transaction should be processed after the load is stopped). This simulates a short bursty sustained load (e.g. for a minute) at 10x of the network capacity.

It is intended as a functional correctness test, not a performance test.

As a part of the test, we should track the following:
- Delayed receipts queue size
- Transaction pool size
- Distribution of transaction latency

We should aim to reuse a framework from https://github.com/near/nearcore/pull/8847

Some related work issues:
- https://github.com/near/nearcore/issues/8880
- https://github.com/near/nearcore/issues/8705

**Comment by jakmeier** [comment]
I plan to start working on this on 1 May.

**Comment by jakmeier** [comment]
I have started _thinking_ about this. Reusing #8847 sounds good and all. But I am contemplating whether it's a bit of an overkill for a congestion test that specifically doesn't care about performance. Maybe a pytest on a single machine would be simpler and give us the same results?

For now, I will try to come up with a sketch for what I think is a good test workload for local congestion. Then I will see how easy it is to integrate it in #8847.

**Comment by akashin** [comment]
> I have started _thinking_ about this. Reusing #8847 sounds good and all. But I am contemplating whether it's a bit of an overkill for a congestion test that specifically doesn't care about performance. Maybe a pytest on a single machine would be simpler and give us the same results?

There is a way to launch that test on a single machine without any additional setup steps using `setup-cluster` flag: https://github.com/near/nearcore/blob/a5ed70bd2b513aadaaa9f0ec3220d78b2c536d46/pytest/tests/loadtest/loadtest2.py#L391-L402

One of the reasons why we also extended it to work with a cluster started in advance is to simplify export of Grafana metrics which is tricky to do in pytest/local run environment. For this test, Grafana will at least be useful to track the size of transaction pools, though arguably we can try to query that metric directly from the test runner.

**Comment by jakmeier** [comment]
With the recent progress in #9118 I will soon shift my focus over here.

The locust setup should be good enough now to simulate congestion. Next week I'll try to produce a mocknet-like setup with Prometheus / Grafana integration to look at different queue lengths. Then I will report my findings around how our system generally behaves under congestion.

From there it should be easy to come up with useful test scenarios and define them using locust. Increased receipt sizes combined with lowered TX pool size limits will be one of the first things I want to play around with.

**Comment by akashin** [comment]
I've ran a quick and dirty test with the following setup:
- 1 locust master node, 16 locust worker
- 100 parallel users
- Each user issues a request "sha256("a" * 100000)" (around 100KB of payload) and waits till result

The test ran for 5 minutes, with latency creeping towards 10s timeout and the transaction pool growing to 30 MB. Then all the nodes crashed for an unknown reason. Will be looking into logs to understand why this happened.

**Comment by akashin** [comment]
I did a further investigation - with 20 users, the network works without changes to latency, but with 40 users, the chunk production stalls and we get forks in the chain:

![image](https://github.com/near/nearcore/assets/1192958/0958c106-3126-4a8d-9a00-8eee4533d73d)

This could be potentially explained by the fact that both the network and the loadtest run on the same machine and there is resource contention between then, though I've checked that nodes are doing fine and the CPU is only 70% utilized.
I'll try to separate the load generator and see if this helps.

**Comment by akashin** [comment]
With 1 node and 1 shard, I was reliably able to get to a regime that represents a congested network.
The exact workload was:
- 1 locust node
- 150 concurrent users
- around 12 requests per second
- Fibonacci number computation with n = 33

This load generated around 12 seconds of congestion in the delayed receipts queue. This in turn resulted in all locust requests timing out, which is expected.

The chain is utilized most of the time:
![image](https://github.com/near/nearcore/assets/1192958/af6eb14c-fcc1-4000-a1ca-dda0682410af)

The detailed Grafana graphs for the relevant period can be found here: https://nearinc.grafana.net/goto/PRNdCRlVR?orgId=1

Next up, I want to introduce a backpressure in the delayed receipts queue and confirm that this workload generates an increasing transaction pool queue size.

I also will look into adding a metric about the delayed receipts queue size mentioned in https://github.com/near/nearcore/issues/8880

**Comment by akashin** [comment]
We now have the [workload](https://github.com/near/nearcore/commit/d584d021ad262d217b8233148a2d7eb282b13d84) that can reproduce congestion and the bursty workload described in https://github.com/near/nearcore/issues/8920#issue-1672842114.

I'm resolving this, as the functional part is there and it's now just a matter of analyzing how the system performs under this load.
