### ISSUE TITLE
Consistent Metrics Naming

### ISSUE THREAD

**Issue by nikurt** [near/nearcore#9065]
Rename prometheus metrics to have 'near_' prefix.
See #9064

**Comment by Longarithm** [comment]
Is it possible to seamlessly migrate https://nearinc.grafana.net/d/Vg9SREA4k/flat-storage so it would support both old and new naming?

**Comment by nikurt** [comment]
Yes. All graphs can be replaced by tracking a sum of `near_flat_storage_XXX` and `flat_storage_XXX`.

Alternatively, as step 1 a node can export both `near_flat_storage_XXX` and `flat_storage_XXX`, and then migrating the dashboard will be easier. But I'd rather switch it to the new naming without the extra complexity of this extra step.

**Comment by Longarithm** [comment]
Interesting idea. Can I run some script over dashboard' JSON to do that automatically?

**Comment by nikurt** [comment]
Apparently, my idea doesn't work.
I'm getting "Data does not have a time field" when I query a non-existing metric.

**Comment by nagisa** [comment]
Adding an additional duplicate query with just the `near_` prefix to the same dashboard should work just fine and transparently switch over when the metric name changes.

(When editing the query there's a button on the top right of the query editor panel which allows you to duplicate the selected query – do that and add a `near_` prefix)

**Comment by Longarithm** [comment]
Done in #10763
