### ISSUE TITLE
rosetta-rpc stake tx format

### ISSUE THREAD

**Issue by colossus-digital** [near/nearcore#9184]
Hi guys, I'm trying to understand how to build a staking tx (and all related txs: 'deposit_and_stake', 'stake', 'unstake_all', 'unstake', 'withdraw_all' and 'withdraw').
Should i use the 'STAKE' operation type or the 'FUNCTION_CALL' ? 
With the 'FUNCTION_CALL' I'll be able to call all the above method, i guess. But with the 'STAKE' type not, or am I wrong ?
Could you also help me and provide an example (or point me to an existing one) of the structure of the tx please?

Thank you very much
A.

**Comment by telezhnaya** [comment]
Hey!
Sorry for the late response.
I highly recommend you this tool https://github.com/near/near-cli-rs
