### ISSUE TITLE
[Resharding] Investigate the feasibility of shard deletion by reference counting

### ISSUE THREAD

**Issue by wacban** [near/nearcore#9198]
This shard deletion algorithm can be used for the `<node hash>` and the `<shard uid><node hash> - mapping` solutions of the storage dimension as described in [Decomposing Resharding](https://docs.google.com/document/d/1S5WsvBpokVIhNOAItmFBCStd6pbxLnKRgEl0yIdnPkQ/edit#heading=h.wbgrw9opdwl0). While the expectation is that this deletion algorithm would work the same in both storage structures we should prioritize the `<node hash>` as more promising. 

The goal of this issue is to find out if this deletion is feasibly and write down how it would work.

**Comment by shreyan-gupta** [comment]
I took a quick look at the garbage collection (GC) code and learnt the following
- GC happens at most two blocks at a time and the `clear_data()` function is called every time we add a new block
- Under the hood, GC for tries `DBCol::State` column happens by fetching data from `DBCol::TrieChanges` for the particular block and applying the reverse of those transactions. This decrements the ref_count for the keys by the appropriate amount.
- `DBCol::State` is basically ref counted, meaning each entry has a a count and this count value is common across all the blocks and all entries. This means if we are tracking two 
- There's a `get_shard_uids_to_gc()` function to determine which all shards to GC in the `clear_block_data()` function

This basically means we can't directly use GC code to delete a whole shard as we are only tracking deltas across blocks.

The best approach I could think of to delete a shard that relied on the GC was the following.
- For shard i, GC all blocks till head such that we only have trie data from only one block. (or till flat_storage head)
- Use flat storage to iterate through all keys for that block and call a trie key delete function. That should hopefully remove all keys

This I guess is a very bad approach, prone to bugs, doesn't directly guarantee a clean deletion unlike range deletion, and is probably way more time and resource consuming compared to range deletion.

Anyone has better ideas?

**Comment by shreyan-gupta** [comment]
Deleting trie data using ref counting can potentially be benchmarked against range deletion to check how much of a difference it creates. We can use the trie generated from flat storage as that contains data from only one block.

High level, the algo would do the following
```
for all keys in flat_storage (possibly in batches) : 
    build batch of changes
trie.update(batch)
trie.apply_all()
store_update.commit()
```

**Comment by wacban** [comment]
Thanks @shreyan-gupta!

Does this answer our question on how does reference counting work as well? Does this mean that neither parent nor child hold a strong reference to a node, but rather the strong reference is kept in the TrieChanges column? 

> DBCol::State is basically ref counted, meaning each entry has a a count and this count value is common across all the blocks and all entries. This means if we are tracking two

I think you forgot to finish this sentence and now I'm really curious. What does exactly happen if we are tracking two...? ;) 

> The best approach I could think of 

Same here, I don't think we can do much better. 

> This I guess is a very bad approach, prone to bugs, doesn't directly guarantee a clean deletion unlike range deletion, and is probably way more time and resource consuming compared to range deletion.

I generally agree with you, I don't think it's completely undoable but it is clearly inferior to range deletion both in implementation complexity and performance.

**Comment by walnut-the-cat** [comment]
What are we trying to achieve by garbage collecting up to head? To understand what ref counts should be at the current state snapshot? If that's the case, (if possible) Would it be faster to just walk over the current state and recalculate ref count from the scratch?

**Comment by shreyan-gupta** [comment]
Did a bit more research, and it seems like neither parent or child hold reference to a node. Non-leaf nodes seems to have a ref count of 1 always (I may be wrong), while the leaf nodes have multiple ref counts depending on the number of occurrences.

I don't completely understand how `trie.update()` function works in collaboration with tracking trie changes across different blocks, as it seems like the function is deleting intermediate trie nodes once we are modifying a value.

For example, if I had `root` -> `a` -> `leaf 1` and I add node `leaf2`, to change the structure to `root'` -> `a'` -> `{leaf1}, {leaf2}` the update functions seems to be doing insert `root'`, `a'`, `leaf2`, delete `root`, `a`, which looks like time history isn't preserved

> DBCol::State is basically ref counted, meaning each entry has a a count and this count value is common across all the blocks and all entries. This means if we are tracking two

So sorry, forgot to add details. So I was saying, if we are tracking two blocks, transaction details of both blocks are stored in the same trie structure.
