### ISSUE TITLE
[Resharding] Investigate the feasibility of the <account id><node hash> storage structure

### ISSUE THREAD

**Issue by wacban** [near/nearcore#9200]
- @wacban To check with other teams if there are any dependencies on it. 
- @shreyan-gupta To analyze the trie and find out how much duplication is there.

**Comment by wacban** [comment]
This was discussed on zulip and in protocol discussion meeting. The key take-aways are:
- This storage structure removes the nice "deduplication" property of using hashes. 
  - This should only matter for the CONTRACT_CODE column. We should be able to solve that independently. 
  - It's worth checking if any other types benefit from the deduplication and by how much. 
- This storage structure is good for large state contracts as it puts all of the state closer to each other in the db. 
  
[zulip - resharding designs - request for comments](https://near.zulipchat.com/#narrow/stream/295302-general/topic/resharding.20designs.20-.20request.20for.20feedback)

**Comment by wacban** [comment]
@shreyan-gupta when doing the analysis please do it per trie type. As we know that for contract code we'd need a dedicated solution anyway we don't need to worry about that one in this issue.

**Comment by shreyan-gupta** [comment]
Sharing some statistics regarding the duplication of storage.

## Items of interest

For the duplication statistics, we care about the **hash of the value** for trie leaf node and the **size of the value** in bytes.

As per the trie structure, the leaf node is stored as key : `{shard_id} {value_hash}`. In a shard, all trie keys that have the same value are stored only once in RocksDB.

## Implementation

The current implementation to figure out the duplication statistics iterates over flat storage key, value pair. 
The flat storage key is the `trie_key` that in a unique entry in the trie.
The flat storage value is either `FlatStateValue::Ref` which stores the hash and length of the value to fetch from `State` col or `FlatStateValue::Inlined` which directly gives us the value.

Draft PR for implementation: https://github.com/near/nearcore/pull/9243 (not to be merged)

## Findings

### Shard statistics

- Shard: shard_id
- trie size: size of the whole trie structure. This data is got from the previous reconstruct trie from flat storage experiment and is the size of the RocksDB directory
- leaf node value size: the size of all **values** stored in the leaf node. This is different from the trie size
- extra storage required: The extra additional size of the leaf node values IF we did not implement de-duplication. Calculated as `value.size * (value.count - 1)`
- % increase: % increase required in storage if there was no de-duplication. Calculated as `extra storage required / leaf node value size`
- duplicate value count: number of duplicated values in storage. These are all values present atleast twice in storage.

| shard | trie size | leaf node value size | extra storage required | % increase | duplicate value count |
| -- | -- | -- | -- | -- | -- |
| shard 0 | 8.0G | 0.38 GB | 2.54 GB | 572.27% | 18,997,709 |
| shard 1 | 6.6G | 0.58 GB | 2.92 GB | 405.89% | 22,546,034 |
| shard 2 | 6.1G | 0.82 GB | 3.36 GB | 307.47% | 13,034,155 |
| shard 3 | 18G | 3.40 GB | 6.26 GB | 83.91% | 27,296,418 |

### Additional statistics split by trie key

`type_dup_bytes` is basically the number of duplicate bytes split by the TrieKey type. Summing the number of bytes should give us the `extra storage required` column above

TrieKey type
- 0 : Account
- 1 : ContractCode
- 2 : AccessKey
- 7 : DelayedReceiptIndices
- 9 : ContractData

```
Shard 0
    type_dup_bytes: {
        0: 965_200_176,
        1: 1_299_406_745,
        2: 45_558_652,
        7: 0,
        9: 13_826_895,
    },

Shard 1
    type_dup_bytes: {
        0: 0,
        1: 0,
        2: 0,
        7: 0,
        9: 2_515_109_516,
    },

Shard 2
    type_dup_bytes: {
        0: 507_004_704,
        1: 2_110_449_534,
        2: 20_112_064,
        7: 0,
        9: 85_358_990,
    },

Shard 3
    type_dup_bytes: {
        0: 112_714_920,
        1: 2_531_385_154,
        2: 10_672_643,
        7: 0,
        9: 411_230_694,
    },
```

## Comments

- As expected, our storage layer optimizes a lot by ref counting and de-duping leaf nodes. For shards 0, 1 and 2, the difference is quite large, ~2.5 GB and 3x to 5.7x more leaf node storage.
- While a lot of duplication comes from key 1, i.e. `ContractCode` (as expected), there's a significant amount of de-duplication happening for other keys as well, specially `Account` and `ContractData`.
- `DelayedReceiptIndices` do not have any duplication, this is expected.
- Surprisingly shard 1 does not have any duplication for any of the keys other than `ContractData`, which is about ~2 GB.
- If we are implementing an explicit de-duplication, we would need to do this for all trie keys and not just `ContractData`.

## Next steps

We can use this data to safely say we would most definitely require an explicit de-duplication strategy if we are to go with the `<account id><node hash>` storage structure.

What is left to be determined is the exact implementation strategy that we would use for this and the associated costs that would have. Some ideas, new column for actual value with ref count, keyed with `<shard_id><value hash>`.

**Comment by shreyan-gupta** [comment]
Probably can close this issue

**Comment by wacban** [comment]
Nice work @shreyan-gupta! 

I'm quite surprised about the difference between trie size and leaf node value size. Does that mean that trie intermediate nodes take up most of the storage? 

>% increase: % increase required in storage if there was no de-duplication. Calculated as extra storage required / leaf node value size 

I'm curious why did you choose to compare the extra storage to the leaf node value size rather than the trie size. At the end of the day we care mostly about the trie size. Just to make sure I understand correctly - without deduplication shard 0 would take 8.0G + 2.54GB = 10.54GB on disk. Is that correct? 

Also just for reference have a look at the metrics exposed in the debug page, at the very bottom of [epoch_info](http://34.90.40.148:3030/debug/pages/epoch_info). There is a small discrepancy between those numbers and the trie sizes that you got. Nothing significant but I'm curious where is the difference coming from. 

Good find about the value of deduplication for other types, it's really valuable insight.
