### ISSUE TITLE
[resharding] Add flat storage support

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#9207]
Flat storage is currently not aware of new shards (shard uids) appearing on the node, thus it doesn't create flat states for new shards. When we do resharding, we must to support flat storage as well. Reconstructing it from Trie was long and inefficient.

Known issues:
* I don't know how [some existing tests](https://github.com/near/nearcore/blob/a7aed55996109781c86b7bb45e99b84f96a3f15c/integration-tests/src/tests/client/sharding_upgrade.rs) pass now because flat storage for new shards shouldn't be created
* @nikurt said that Nayduck test `sanity/state_sync_fail.py` triggers resharding and stops working
* maybe there are other testcases currently commented, we need to revive and fix them.

**Comment by shreyan-gupta** [comment]
Working on this https://github.com/near/nearcore/issues/9418
