### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by kevitator6** [near/nearcore#9242]
**Describe the bug**
Please provide a short description of the bug.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**

**Comment by nagisa** [comment]
Please file a bug report with information about the issue filled in.

Thanks!
