### ISSUE TITLE
[resharding] Include state_changes in ApplySplitStateResult for split_state

### ISSUE THREAD

**Issue by shreyan-gupta** [near/nearcore#9420]
For more context please view https://github.com/near/nearcore/issues/9418

During resharding we need to split the trie/state changes across the child shards. This is mainly handled by the `tries.apply_state_changes_to_split_states` function which takes the set of trie state updates and distributes it as trie updates across the child shards as per account id. 

During pre-processing `runtime.apply_update_to_split_states` function calls `tries.apply_state_changes_to_split_states` and saves the state changes as `ApplySplitStateResult` which would later be applied to the child shards during postprocessing after catchup.

Note that the `WrappedTrieChanges` (for each child shard) also contains the field called `state_changes` which wasn't being populated. This would eventually be used in the `process_split_state` function where we apply and commit the changes to the child shards to DB. We would use the state changes to update flat storage.

**Comment by wacban** [comment]
Thanks for the nice description! Makes sense. 

I couldn't find the reference to `state_changes` in the `process_split_state`, can you point me to where is it? Or is that only going to be added later when you also `ApplySplitStateResult` to the flat storage?

**Comment by shreyan-gupta** [comment]
@wacban, right, so, this task is to populate `state_changes` in `ApplySplitStateResult` and the actual use of the `state_changes` is a part of this PR https://github.com/near/nearcore/pull/9421
