### ISSUE TITLE
[resharding] Update flat storage state and head during process_split_state

### ISSUE THREAD

**Issue by shreyan-gupta** [near/nearcore#9423]
Once we are done with resharding, we need to catch up on the blocks that came in during resharding and we also need to handle splitting and updating state for the child shards till the end of the epoch.

For these tasks, for all new blocks that come in, we split the state changes and trie changes of the parent shard to the child shards. This is handled in two steps:
- Preprocessing by the `apply_state_changes_to_split_states` function after which we save the split state changes.
- Postprocessing by the `process_split_state` function where we take the state changes from preprocessing step and apply them.

In a previous task https://github.com/near/nearcore/issues/9420, we made changes to include the child shard `state_changes` in `ApplySplitStateResult`. Now we need to use these state changes to update the flat storage state (add deltas) and update the flat storage head for the child shards.

**Comment by wacban** [comment]
Just to be technically correct: `apply_state_changes_to_split_states` is not part of the preprocessing. It looks like that in code because it's embedded in the `apply_chunks_preprocessing` method but it actually is captured in the `process_one_chunk` closure. It is then passed on to the thread pool and executed there as part of processing (no 'pre').

**Comment by shreyan-gupta** [comment]
Oh right! I had missed seeing it in the closure. Another reason why we desperately need some refactoring in this part of the codebase.

**Comment by wacban** [comment]
> Oh right! I had missed seeing it in the closure. Another reason why we desperately need some refactoring in this part of the codebase.

Yep, I'm just waiting for you to merge your stuff and I'm on it, just splitting it to a few methods and adding comments would be such an improvement.
