### ISSUE TITLE
RPC end point with more fine grained tx status 

### ISSUE THREAD

**Issue by telezhnaya** [near/nearcore#9542]
I want to rework `tx` and `EXPERIMENTAL_tx_status` methods:
1. I want to add `include_receipts` flag to `tx` method (default `false`, it saves backward compatibility). `true` will return the result from `EXPERIMENTAL_tx_status`
2. The new flag will allow us to deprecate `EXPERIMENTAL_tx_status` and hopefully we may drop it in one day. It's not experimental from it's very first day
3. (most important for me) I want to redesign the way how and when we return the response. Right now, we are uncertain which receipts are finalised, which are not, and we ask the users to re-check this. The doc is full of ambiguity. https://github.com/near/docs/pull/1499
I suggest to add to response the new enum value, as Illia suggested in https://github.com/near/nearcore/issues/6837, it will answer what is the status of the execution.

**Comment by jakmeier** [comment]
Great idea to clean this up!

Disclaimer, my knowledge here is not perfect on how these endpoints work. But I'll try to explain how I think it works today.

I believe both endpoints look up recursively all execution statuses of the receipts DAG, then they aggregate the status of all receipts into a single `FinalExecutionStatus`. Aggregation is a bit weird, in each step it only looks at the first (or last?) outgoing receipt and takes the result of that IIRC. This means if two receipts spawn and the first returns `SuccessValue` then it doesn't matter if the second receipt has failed, succeeded, or hasn't even started execution yet.

The `FinalExecutionStatus` we return, I think , has zero finality guarantees (as in blockchain finality). In my understanding, it corresponds to `BroadcastWait::Executed`.

However, putting finality aside, for some reason I used to think `EXPERIMENTAL_tx_status` waits for all execution outcomes (`BroadcastWait::Executed`) but  `tx` doesn't (`BroadcastWait::Inclusion`). But I am no longer sure. The code looks to me like both endpoints behave the same, except the experimental call also includes receipts. And I think actually both wait for all outcomes to be known, at least that's how I understand the description in #6834.

----
So much about what the status quo is. I think the ideal API would be exactly as you describe in points 1,2,3. But for the aggregated status, I would probably keep it as is but at least make it much clearer in the documentation what it means.

**Comment by wacban** [comment]
I like the idea of reusing the same wait enum for both broadcast and status endpoints. I have no clue how do clients actually use the endpoint so it's hard to say for me what is the best design. Logically speaking there are three separate functionalities that we're considering: broadcast, status and wait. Today 'wait' seems to be integrated into the other two in one way or another. Depending on the client usage it may make sense to add the WaitCondition as either an argument, return value or both for both endpoints. I think what you're suggesting is one viable option. 

At the end of the day what matters is that the API is usable and well documented so any improvement is welcome.

**Comment by telezhnaya** [comment]
Done 😎
