### ISSUE TITLE
[first-issue] Add --limit cmdline parameter to the `view-state view-trie` neard command

### ISSUE THREAD

**Issue by nikurt** [near/nearcore#9548]
Originally filed by @wacban:

The `neard view-state view-trie` is a neat tool for looking at the trie. Currently it supports the `--max-depth` cmdline parameter. For more details please see: [Using state-viewer](https://pagodaplatform.atlassian.net/wiki/spaces/EAP/pages/136609793/Using+state-viewer). The one drawback is that when executed on a production blockchain like testnet or mainnet it can produce a bit too much output. The goal of this task is to add a `--limit` parameter that will limit how many entries are printed to the output.

**Comment by wacban** [comment]
As a cool follow up we can also add --from, --to, --type and a few other filters to allow looking at exact values in the trie.
