### ISSUE TITLE
[State Sync] Setup garbage collection of state for old epochs

### ISSUE THREAD

**Issue by Sarah-NEAR** [near/nearcore#9574]
Setup garbage collection of state for old epochs.

The issue is that storage isn't infinite and we don't want the state-parts bucket to accumulate terabytes of data.
Ideal goal: keep state parts for 2-10 most recent epochs.

**Comment by telezhnaya** [comment]
It's about cloud garbage collection
This can be done by SRE

**Comment by VanBarbascu** [comment]
Done, we only keep 5 days of data.
