### ISSUE TITLE
Enable branch protection in Github to prevent PRs being modified after approvals 

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9694]
Today in Github is configured such that, after a PR is approved, it can be modified before merging.

We want to change this approach and force a reapproval flow if PRs are modified after approval.

**Comment by andrei-near** [comment]
done https://near.zulipchat.com/#narrow/stream/295302-general/topic/Github.20nearcore.20branch.20protection

**Comment by wau-fdt** [comment]
Does it mention what kind of "modifications" are classified to be reviewable commits?  I would like to be able exclude non-conflicting merge commits from parent branch.
