### ISSUE TITLE
saturate multiple shards with the locust FT transfer benchmark

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9750]
--- Old description ---

<p>There’s a discrepancy in tgas/sec in this test when load is split across 3 shards vs all in one shard. This seems like probably an issue with the test, so find and fix it if so.</p>
<i>[ND-475] created by None</i>

[ND-475]: https://pagodaplatform.atlassian.net/browse/ND-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by akashin** [comment]
I'll take over and repurpose this issue for the work that @MCJOHN974 is doing for https://github.com/near/nearcore/issues/10885.

**Comment by akashin** [comment]
Actually, bad idea, I'll create a new issue.
