### ISSUE TITLE
Run state sync as a catchup of all shards

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9754]
<i>[ND-471] created by None</i>

[ND-471]: https://pagodaplatform.atlassian.net/browse/ND-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment]
It's not 100% plan, it's an idea we want to consider

**Comment by nikurt** [comment]
The refactoring is not worth it. Code duplication can be addressed directly without re-writing how `Client` drives state sync.
