### ISSUE TITLE
[Far Future] Make state syncs work with resharding

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9756]
<i>[ND-469] created by None</i>

[ND-469]: https://pagodaplatform.atlassian.net/browse/ND-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nikurt** [comment]
Agreed with @wacban that:
* It would be a significant effort to make this write
* After pre-state-root migration completes it's no longer needed.
The conclusion was to skip this significant project and instead wait until for the pre-state-root migration to complete.

A minor change will be needed to how requests for state header or for state parts are interpreted. The nodes will need to assume that the `ShardId` in the request (or even better `ShardUId`) corresponds to the new `ShardLayout`, i.e. to the `ShardLayout` of the new epoch.

Pre-state-root migration will make it unnecessary to replay the last chunk of a shard, and will simplify the interaction of state sync and resharding.
