### ISSUE TITLE
Tool to drop blocks from latest epochs to speed up the state sync testing

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9764]
<i>[ND-457] created by None</i>

[ND-457]: https://pagodaplatform.atlassian.net/browse/ND-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment]
Done by @VanBarbascu
