### ISSUE TITLE
Put together an engineering plan for Decentralised State Sync

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9767]
<i>[ND-451] created by None</i>

[ND-451]: https://pagodaplatform.atlassian.net/browse/ND-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment]
Done by @VanBarbascu
