### ISSUE TITLE
Implement a solution for replaying blocks in the presence of Flat Storage

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9776]
<i>[ND-435] created by None</i>

[ND-435]: https://pagodaplatform.atlassian.net/browse/ND-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Longarithm** [comment]
Tracked in #8741, also see #10961.
