### ISSUE TITLE
State Sync: Rework how parts are fetched from external storage

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9782]
<p>The current implementation is overly complicated, it was designed for managing async requests to peers.</p>

<p>Use <tt>SyncJobsActor</tt> or use a rayon-for-loop or anything else that makes sense.</p>

<p>The field <tt>response</tt> shouldn’t be <tt>Arc<Mutex<Vec>></tt>, but just a <tt>Vec</tt> should be enough.</p>
<i>[ND-426] created by None</i>

[ND-426]: https://pagodaplatform.atlassian.net/browse/ND-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment]
Suboptimal, but it works
