### ISSUE TITLE
Bitcoin Bridge

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#980]
This should not require any custom changes on the runtime side, but we need to make sure we have exposed all the tools like SHA256 etc by writing the light client for Bitcoin (e.g. Summa's SPV model) in our smart contract.

**Comment by bowenwang1996** [comment]
@ilblackdragon what changes on nearcore side do we still need?

**Comment by ilblackdragon** [comment]
Should not require any changes in nearcore. Closing.
