### ISSUE TITLE
Release GCS-based State Sync to mainnet

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9830]
<p><a href="http://go/state-sync-v2" class="external-link" rel="nofollow noreferrer">http://go/state-sync-v2</a></p>

<p><a href="https://pagodaplatform.atlassian.net/wiki/spaces/EAP/pages/140214353/Improved+State+Sync" title="smart-link" class="external-link" rel="nofollow noreferrer">https://pagodaplatform.atlassian.net/wiki/spaces/EAP/pages/140214353/Improved+State+Sync</a></p>
<i>[ND-252] created by None</i>

[ND-252]: https://pagodaplatform.atlassian.net/browse/ND-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment]
Copy of https://github.com/near/nearcore/issues/9571
