### ISSUE TITLE
Runtime hits unknown perfomance cliff in the estimator

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9933]
<p>See </p>

<p><a href="https://github.com/matklad/nearcore/commit/80b44a877a1d2de76b4adcf63567984d615e7c36" class="external-link" rel="nofollow noreferrer">https://github.com/matklad/nearcore/commit/80b44a877a1d2de76b4adcf63567984d615e7c36</a></p>

<p>In that commit, I add a benchmark which sends 150 blocks, where each<br/>
block contains 100 deploy code transaction.</p>

<p>EDIT: <a href="https://github.com/near/nearcore/issues/4771#issuecomment-933347496" class="external-link" rel="nofollow noreferrer">https://github.com/near/nearcore/issues/4771#issuecomment-933347496</a> is modernized version.</p>

<p>The benchmark is implemented in two ways:</p>

<ul>
	<li>on top of parameter estimator testbed</li>
	<li>on top of runtime tester</li>
</ul>

<p>In the first case, I observe a very stage behavior, where at some point<br/>
block processsing times severely degrades.</p>

<p>To reproduce, checkout this commit and run</p>

<p>```console<br/>
$ cargo test --release --package runtime-params-estimator --lib --features required &#8211; v2::fast --exact --nocapture<br/>
$ cargo test --release --package runtime-params-estimator --lib --features required &#8211; v2::slow --exact --nocapture<br/>
```</p>

<p>Look for `Runtime::apply` lines in the output, they they tell you how<br/>
long it takes to process one apply.</p>

<p>In the `fast` case, every apply takes about 16ms for me. In the `slow`<br/>
case, apply start at about 30ms, but then abruptly go to 600ms.</p>

<p>Would be great to understand why the time suddenly balloons! </p>
<i>[ND-98] created by None</i>

[ND-98]: https://pagodaplatform.atlassian.net/browse/ND-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Longarithm** [comment]
Duplicate of https://github.com/near/nearcore/issues/4771
